### ISSUE TITLE
20151226_kiev_fashion_park - intermediate point - wrong heading size h1

### ISSUE THREAD

**Issue by OleksiiShch** [scholokov/long-travel-2#1000]
Steps to reproduce
Open page https://test.long-travel.live/20151226_kiev_fashion_park/
Pay attention to the name fonts of the intermediate point of the travel

Actual Result:
heading size - "h1"

Expected result:
heading size - "h2"

Environment:
Windows 10, Google Chrome Версія 103.0.5060.134 (Розробка) (64-розрядна версія
![Fonts name](https://user-images.githubusercontent.com/25012427/182380887-703a36b2-45e1-4415-81f4-ced5f95ddfdc.png)
)

**Comment by OleksiiShch** [comment]
corrected

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by OleksiiShch** [comment]
Verified
