### ISSUE TITLE
20211029_0911_portugal - Header is missing a time period

### ISSUE THREAD

**Issue by RomaSkorokhod** [scholokov/long-travel-2#1013]
Steps to reproduce:
https://test.long-travel.live/20211029_0911_portugal/

Actual result:
Header is missing a time period

Expected result:
There is a time period in the header
![222](https://user-images.githubusercontent.com/108660894/182639926-a62ca8e7-3f03-42ca-baaa-f9331cd38a0d.png)
r

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by RomaSkorokhod** [comment]
Closed
