### ISSUE TITLE
20160518_22_eger - Endless scroll

### ISSUE THREAD

**Issue by OleksiiShch** [scholokov/long-travel-2#1028]
Steps to reproduce:
Open https://test.long-travel.live/20160518_22_eger/
Scroll down to the footer

Actual Result:
endless scroll

Expected result:
scroll not endless

Environment:
Windows 10, Google Chrome Версія 103.0.5060.134 (Розробка) (64-розрядна версія)
![GcSNEyEhEM](https://user-images.githubusercontent.com/25012427/182834613-70cea841-0029-47b2-83f4-78485729eb9b.png)

**Comment by scholokov** [comment]
fixed

**Comment by OleksiiShch** [comment]
Verified
