### ISSUE TITLE
20160618_mezhigorie - intermediate point - wrong heading size font

### ISSUE THREAD

**Issue by OleksiiShch** [scholokov/long-travel-2#1034]
Steps to reproduce
Open page https://test.long-travel.live/20160618_mezhigorie/
Pay attention to the name fonts of the intermediate point of the travel

Actual Result:
heading size font- "h1"

Expected result:
heading size font- "h2"

Environment:
Windows 10, Google Chrome Версія 103.0.5060.134 (Розробка) (64-розрядна версія)
![travel fonts](https://user-images.githubusercontent.com/25012427/182858697-41ec031b-f4a4-414a-8370-4ad44ddcc6a5.png)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by OleksiiShch** [comment]
Verified
