### ISSUE TITLE
20160618_mezhigorie - Endless scroll

### ISSUE THREAD

**Issue by OleksiiShch** [scholokov/long-travel-2#1037]
Steps to reproduce:
1.Open https://test.long-travel.live/20160618_mezhigorie/
2.Scroll down to the footer
3.A new travel page opens

Actual Result:
endless scroll

Expected result:
scroll not endless

Environment:
Windows 10, Google Chrome Версія 103.0.5060.134 (Розробка) (64-розрядна версія)
![endless scroll](https://user-images.githubusercontent.com/25012427/182862328-f356c7a1-7e03-42a3-a48a-bfc3640d5136.png)

**Comment by scholokov** [comment]
тут для детализации лучше дописать - что именно происходит - т.е. когда закнчивается одно путешествие - появляется другое (т.е. безконечный скрол)

**Comment by OleksiiShch** [comment]
Corrected but problem fixed

**Comment by scholokov** [comment]
непонятен статус. исправлено или не?

**Comment by scholokov** [comment]
почему с статусе need triage и закрыто?

**Comment by OleksiiShch** [comment]
verified
