### ISSUE TITLE
20200719_belya_tsercov - Travel Name - wrong font-weight

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/long-travel-2#1045]
Steps to reproduce:
1. Open page https://test.long-travel.live/20200719_belya_tsercov/
2. Scroll down to the "Київська область, Україна"
3. Pay attention to the font-weight "Київська область, Україна"

Actual result:
bold

Expected result:
normal

Environment:
Windows 11, Версия 103.0.5060.134 (64 бит)

![fOT8qyf](https://user-images.githubusercontent.com/57997443/183569927-6c8e50c1-6428-4896-be31-981b60b93ec2.png)

**Comment by scholokov** [comment]
20200719_belya_tsercov - wrong header font-weight

было бы понятнее, если написать например:
20200719_belya_tsercov - Travel Name - wrong font-weight

**Comment by scholokov** [comment]
3. Pay attention to the font-weight "Київська область, Україна", the requirements do not specify what should be the font-weight

в шагах мы не пишем на чем основан экспект резалт

**Comment by scholokov** [comment]
если в шаге уже указано, что обратить внимание на font-weight, то дублировать это в результате не обязательно

**Comment by scholokov** [comment]
после заведения бага перемещаем его в Need Triage статус
Ready For Testing - это уже для исправленных

**Comment by dmitryylev** [comment]
> после заведения бага перемещаем его в Need Triage статус Ready For Testing - это уже для исправленных
changed

**Comment by dmitryylev** [comment]
> если в шаге уже указано, что обратить внимание на font-weight, то дублировать это в результате не обязательно

уточните, мне полностью убрать результат или изменить на "Actual result: bold, Expected result: normal"

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by dmitryylev** [comment]
verified
