### ISSUE TITLE
20071027_uman - Title - does not meet the requirements

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1046]
Steps To Reproduce:
1. Open https://www.long-travel.live/20071027_Uman/
2. Check that the content title is appropriate.
Expected result: 
Черкаська область, місто Умань, Національний дендрологічний парк "Софіївка"
Actual result: 
Умань. Дендропарк "Софиевка" 
<img width="1440" alt="Снимок экрана 2022-08-09 в 2 31 17 PM" src="https://user-images.githubusercontent.com/110661667/183638521-8c0be55e-0ba0-456f-bc26-745dffe9d32b.png">

**Comment by scholokov** [comment]
в принципе ок, но для удобочитаемости лучше разнести

1. Open https://www.long-travel.live/20071027_Uman/
2. Check that the content title is appropriate.

Expected result:
Черкаська область, місто Умань, Національний дендрологічний парк "Софіївка"

Actual result:
Умань. Дендропарк "Софиевка"

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
> fixed

**Comment by LesiaBezukh** [comment]
Check again, the bug is not fixed. @GeorgiiZ90

**Comment by GeorgiiZ90** [comment]
https://test.long-travel.live/20071027_Uman/
please check this link

**Comment by KaterinaNimenko35** [comment]
Verified,an issue is not reproduced
