### ISSUE TITLE
20160518_22_Eger - Link to the hotel is not visible (not colored)

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/long-travel-2#1047]
Steps to reproduce:
1. Open page https://test.long-travel.live/20160518_22_Eger/
2. Scroll down to the title hotel "Magyarország, Egerszalók, hotel – Ámbitus-ház"
3. Pay attention, after hotel not visible link

Actual result: not visible
Expected result: visible

Environment:
Windows 11, Версия 103.0.5060.134 (64 бит)

![y1kmBx2](https://user-images.githubusercontent.com/57997443/183816896-63c0217d-9f6c-4605-9949-93647855f1e9.png)

**Comment by scholokov** [comment]
fixed

**Comment by dmitryylev** [comment]
verified
