### ISSUE TITLE
20160518_22_Eger - Link to the hotel is not visible (not colored)

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/long-travel-2#1048]
Steps to reproduce:
1. Open page https://test.long-travel.live/20160518_22_Eger/
2. Scroll down to the title hotel "Львів, Україна, Отель Копа"
3. Pay attention, after hotel invisible link

Actual result: not visible
Expected result: visible

Environment:
Windows 11, Версия 103.0.5060.134 (64 бит)

![Hxdx3Kd](https://user-images.githubusercontent.com/57997443/183817558-46339820-1a6b-454c-9239-41730a893763.png)

**Comment by scholokov** [comment]
fixed

**Comment by dmitryylev** [comment]
verified
