### ISSUE TITLE
20210305_07_odessa. Travel distance not specified.

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#1049]
**Steps to reproduce:**

1. Open page <https://test.long-travel.live/20210305_07_odessa>
2. Scroll down the page to the trip map.
3. Pay attention of missing of travel distance

**Actual result:**
Travel distance is indicated.

**Expected result:**
Travel distance is indicated.

**Environment:**
MacBook/macOS Monterey 12.5/Chrome 103.0.5060.134 (arm64)

![odessa 1](https://user-images.githubusercontent.com/108996909/183844717-06e1bac3-63b9-4ee1-9941-f4df5702eedd.png)

**Comment by scholokov** [comment]
fixed

**Comment by SerhiiBurdieiev** [comment]
verified
