### ISSUE TITLE
20080427_feofania - Title - does not meet the requirements

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1050]
Steps To Reproduce:
1. Open https://www.long-travel.live/20080427_feofania/

2. Check that the content title is appropriate. 

Expected result:  Київська область, Київ, парк "Феофанія"
Actual result:  Киев - Парк «Феофания»

<img width="1432" alt="Снимок экрана 2022-08-10 в 2 50 54 PM" src="https://user-images.githubusercontent.com/110661667/183894299-fdac561d-dbdb-47af-a4d0-ab59db13a2b5.png">

**Comment by GeorgiiZ90** [comment]
https://test.long-travel.live/20080427_feofania/
Fixed

**Comment by LesiaBezukh** [comment]
Verified
