### ISSUE TITLE
 20160326_konotop - Title does not meet the requirements

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1054]
Steps To Reproduce:
1. Open https://www.long-travel.live/20160326_konotop/
2. Check that the content title is appropriate.

Expected result: Сумська область, Конотоп 

Actual result: Konotop/Sumy region/Ukraine 

<img width="1435" alt="Снимок экрана 2022-08-10 в 4 00 33 PM" src="https://user-images.githubusercontent.com/110661667/183908059-a97ef39b-8514-441b-b1f8-a744ca615e61.png">

**Comment by GeorgiiZ90** [comment]
https://test.long-travel.live/20160326_konotop/
please check this link

**Comment by LesiaBezukh** [comment]
verified
