### ISSUE TITLE
20160326_konotop - Date of travel is missing

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1055]
Steps To Reproduce:
1. Open https://www.long-travel.live/20160326_konotop/
2. Check travel date

Expected result: there is a date under the name of the trip «26.03.2016»

Actual result: there is no travel date.
<img width="1435" alt="Снимок экрана 2022-08-10 в 4 10 13 PM" src="https://user-images.githubusercontent.com/110661667/183909954-44333e51-31e0-4483-acfb-8d983b447222.png">

**Comment by GeorgiiZ90** [comment]
https://test.long-travel.live/20160326_konotop/   
please check on this link

**Comment by LesiaBezukh** [comment]
verified
