### ISSUE TITLE
20200719_Belya_tsercov - In the travel map is absent link on travel

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/long-travel-2#1059]
Steps to reproduce:
1. Open page https://test.long-travel.live/20200719_Belya_tsercov/
2. Pay atttention to the detalis trave on travel map

Actual result: **link is absent**
Expected result: **link is avalible**

Environment:
Windows 11, Версия 104.0.5112.81 (64 бит)

![chrome_ycpQH8Oti1](https://user-images.githubusercontent.com/57997443/184068184-5c64ed9b-5c9e-4394-ab20-bc03d31af366.png)
![20200719_Belya_tsercov](https://user-images.githubusercontent.com/57997443/184068198-adf70bc5-8332-46d5-89e2-ea4854df9276.png)

**Comment by scholokov** [comment]
скрины лучше в теле располагать в порядке следования экшуал-экспектид резалт

т.е. экшуал находится сверху
ниже идет экспектид
а картинки наоборот - сначала экспектид, а ниже - экшуал

**Comment by scholokov** [comment]
fixed

**Comment by dmitryylev** [comment]
verified
