### ISSUE TITLE
Requirements analysis, structure

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/long-travel-2#1060]
Description: Absent unambiguous formulation of the **concept of a point.** 

Actual result: point
Expected result: place in travel, city, region, country 

![chrome_gJoxO0QL0N](https://user-images.githubusercontent.com/57997443/184068581-33b4abe7-576f-45b2-abe7-f66f07674790.png)

![structure](https://user-images.githubusercontent.com/57997443/184068414-20535fea-6127-4f8e-9c9b-aada49a0a150.png)

**Comment by scholokov** [comment]
fixed

**Comment by dmitryylev** [comment]
verified
