### ISSUE TITLE
Requirements analysis, content, title of travel

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/long-travel-2#1061]
Description: Absent unambiguous formulation **what should be in the title of travel**. As a result - different options

Actual rusult: no formulation
Expected rusult: unambiguos formulation

![content1](https://user-images.githubusercontent.com/57997443/184068750-12e8c9d3-9b1d-4c51-b0a6-524f08f26e60.png)
![content2](https://user-images.githubusercontent.com/57997443/184068756-61a515fc-14b6-4872-a559-8c6c628e74aa.png)
![content3](https://user-images.githubusercontent.com/57997443/184068760-70dadbfa-449d-4724-afa7-094b6ff75ffe.png)
![content4](https://user-images.githubusercontent.com/57997443/184068762-aa37d52d-f3f3-404b-9744-360ac5a0f672.png)

**Comment by scholokov** [comment]
для удобства хорошо бы писать прямую ссылку :)

**Comment by scholokov** [comment]
fixed
https://github.com/scholokov/long-travel-2/wiki/2.3-Travel.Content
