### ISSUE TITLE
20160326_konotop - Incorrect Structure 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1063]
Steps To Reproduce: 
1. Open https://test.long-travel.live/20160326_konotop/ 
2. Check if the content structure is correct. 

Actual result: the caption under the title is duplicated. 
Expected result: There is no caption under the title. 

<img width="1440" alt="Снимок экрана 2022-08-11 в 2 04 18 PM" src="https://user-images.githubusercontent.com/110661667/184120099-46e0c532-7901-4be0-bed6-d0c3d96a88fb.png">

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
