### ISSUE TITLE
20160326_konotop - Incorrect travel title

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1064]
Steps To Reproduce: 
1. Open https://test.long-travel.live/20160326_konotop/ 
2.  Check if the name of the trip is correct. 

Actual result: Конотоп, Сумська обл., Україна
Expected result: Конотоп, Сумська область

<img width="1440" alt="Снимок экрана 2022-08-11 в 2 08 16 PM" src="https://user-images.githubusercontent.com/110661667/184120466-6b0fe5f5-6dce-4fc1-9de3-befc9920c7af.png">

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Uncorrected, check again the expected result.

**Comment by scholokov** [comment]
если ошибка все еще существует, лучше использовать более мягкую форму:
"Still reproduce". Потому что когда говорим - "не исправлено" - это значит разработчик "ничего не делал", что не всегда так, даже если видимых изменений нет.
и еще очень хорошая практика - если баг все еще существует - помимо текста что баг все еще существует, добавлять и новый скрин
