### ISSUE TITLE
20071027_uman - Font-weight is incorrect 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1065]
Steps To Reproduce: 
1. Open https://test.long-travel.live/20071027_Uman/
2. Check if the Font-weight of the travel name is correct

Actual result: Font-weight normal
Expected result: Font-weight 700

<img width="1440" alt="Снимок экрана 2022-08-11 в 2 14 06 PM" src="https://user-images.githubusercontent.com/110661667/184121592-40c81882-334a-4cef-915d-7ddc76304c65.png">

**Comment by scholokov** [comment]
на чем основаны требования?
