### ISSUE TITLE
20200627_29_yuzhniy/Home page. Preview image - missing

### ISSUE THREAD

**Issue by yuriiboikokiev** [scholokov/long-travel-2#107]
**Steps:**
1. Open home page.
2. We go down to the miniature "Южный".
3. Attention to the preview image

**Actual result :**
Miniature "Южный"  has no a image

**Expected result:**
Miniature "Южный" has a image. (according to the requirements).
[https://github.com/scholokov/long-travel-2/wiki/Travels]

**Screenshot:** https://skr.sh/s9uVhLZqsQx?a

**Additional Information:**
-Operating System: Windows 10, x64.
-Browser : Google Chrome 93.0.4577.63 (Official build), (64 bit)

**Comment by scholokov** [comment]
превьюшка относится к самому путешествию. нужен айдишник путешествия в тайтле
