### ISSUE TITLE
20160814_24_Shadsk - Punctuation error in arrival time

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1073]
Steps To Reproduce:
1. Open  https://test.long-travel.live/20160814_24_Shadsk/
2. Check the text of the road description Київ-Світязь

Actual result: Прибытие 16.50
Expected result: Прибытие 16:50
<img width="1440" alt="Снимок экрана 2022-08-11 в 5 21 44 PM" src="https://user-images.githubusercontent.com/110661667/184155841-64b39943-5de9-41fa-8065-6e0a516f09d7.png">

**Comment by scholokov** [comment]
20160814_24_Shadsk - Punctuation error

слишкоб общее название. лучше уникализировать
например, а что будет если будет 2 опечатки в одном путешествии?

**Comment by LesiaBezukh** [comment]
Verified
