### ISSUE TITLE
  20160814_24_Shadsk - Problem in the type of photo gallery.

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1088]
Steps To Reproduce:
1. Open https://test.long-travel.live/20160814_24_Shadsk/
2. Check the photo gallery to make sure it meets the requirements.

Actual result: Photos are not displayed correctly for the Justified Grid gallery type.
Expected result: photos are displayed correctly for the Justified Grid gallery type.

<img width="1440" alt="Снимок экрана 2022-08-16 в 10 10 53 AM" src="https://user-images.githubusercontent.com/110661667/184821440-89a0edfa-9eac-4d93-88f9-29933f4a4a0f.png">
<img width="1440" alt="Снимок экрана 2022-08-16 в 10 11 13 AM" src="https://user-images.githubusercontent.com/110661667/184821460-7a6ca62e-cb68-4621-84c8-159d5cb13464.png">
<img width="1440" alt="Снимок экрана 2022-08-16 в 10 21 14 AM" src="https://user
<img width="1440" alt="Снимок экрана 2022-08-16 в 10 10 29 AM" src="https://user-images.githubusercontent.com/110661667/184821766-6ba7e0f4-1db5-4748-a28a-d4e4b693cd49.png">
-images.githubusercontent.com/110661667/184821492-c89602bb-330f-44c7-b865-c16b3659a081.png">

**Comment by DmytroMarkulych** [comment]
1. В Summary потрібно уникати слів "problem", "not correct", "doesn't work" і т.д. Використання таких слів призводить до не розуміння зі сторони розробника, і з точки зору трекінгу дефектів призведе до наявності сотень дефектів із подібними словами в summary, що максимально ускладнить пошук по ключових словах потрібного дефекту.
Приклад:
**Неправильний приклад**: Сторінка відображається коректно
**Правильний приклад**: Поле для введення логіка відображається в межах блоку «Реєстрація» на головній сторінці
2. В "Steps to reproduce" останній step повинен містити слова "Pay attention to...". Таким чином передостанній step вказує на блок чи розділ на сторінці, а останній із словами "Pay attention to..." на конкретний елемент на сторінці в якому і є дефект.
3. Actual Result and Expected Result Ви використовуєте словосполучення  "not displayed correctly", що призводить до певного не розуміння з точки зору конкретності. Кращою та більш детальною практикою буде використання слів "вирівнювання по ширині, вирівнювання по лівому краю і т.д" в залежності від контексту проблеми, що дає більше деталей.
