### ISSUE TITLE
20160814_24_Shadsk - Description of the road "Kyiv-Svitiaz" grammatical error «впрочем» 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1089]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20160814_24_Shadsk/
2. Open the section of the road "Світязь-Київ" 
3. Check the text of the description of the road "Київ-Світязь" for grammatical errors
4. Pay attention to the word "врежиме"

Actual result: "врежиме"
Expected result: " в режиме"

<img width="1440" alt="Снимок экрана 2022-08-16 в 5 46 45 PM" src="https://user-images.githubusercontent.com/110661667/184909503-8614d03b-727b-43e2-a94c-637bafa3551f.png">

**Comment by DmytroMarkulych** [comment]
1. Summary повинно відповідати на питання "Що? Де? Коли?", і описувати стисло і лаконічно суть дефекту. 
2. В "Steps to reproduce" останній step повинен містити слова "Pay attention to...". Таким чином передостанній step вказує на блок чи розділ на сторінці, а останній із словами "Pay attention to..." на конкретний елемент на сторінці в якому і є дефект.

**Comment by LesiaBezukh** [comment]
Добрый день, я не понимаю где ошибка в Summary. Summary отвечает на вопросы "Что? Где? Когда?", объясните пожалуйста. 
Обязательно ли для всех баг-репортов использование "Pay attention to"? Это только должно присутствовать в рамках нашего проекта или является обязательным независимо от проекта?

**Comment by DmytroMarkulych** [comment]
Доброго дня. 
1. Summary коротко описує суть проблеми, відповідаючи на питання: ЩО не так працює? в якому місці продукту, тобто ДЕ? і КОЛИ дана проблема з’являється?.  Саме в такій послідовності. Це є загальним правилом оформлення баг репортів. Звичайно, що існують дефекти в яких ми не можемо відповісти на всі три питання, в такому випадку ми можемо опустити, до прикладу,  "Коли?" - якщо це загальна проблема для всього проєкту. 
Давайте розглянемо Ваше Summary:
**When opening the page there is a grammatical error in the description of the road "Kyiv-Svitiaz"**
**ЩО?** - а grammatical error
**ДЕ?** - in the description of the road "Kyiv-Svitiaz"
**КОЛИ?** - When opening the page there is
Бачимо, що питання "ЩО?" та "КОЛИ?" не на своїх законних місцях. 
2. На рахунок "Pay attention..." - це теж загальне правило, для того щоб вказати на конкретний елемент. Бувають проєкти із десятками buttons, а у нас не працює тільки одна із них, тому ми вказуємо саме на неї фразою "Pay attention..".

**Comment by LesiaBezukh** [comment]
Вчера я попросила скинуть мне материал о написании баг-репортов чтобы не допускать идентичных ошибок. На портале QAX допускается использование написание названия ошибки в порядке "Где?Что?Когда?". Исходя из информации указанной на портале, Summary в баг-репорте является корректным. 

<img width="1440" alt="Снимок экрана 2022-08-17 в 11 04 44 AM" src="https://user-images.githubusercontent.com/110661667/185068303-844c6970-6659-42b4-ad62-6c5367c3519f.png">

**Comment by DmytroMarkulych** [comment]
1. На рахунок послідовності приношу вибачення, краще використовувати послідовність, що в матеріалу курсів. Але зверну Вашу увагу, на те, що в майбутньому буде зустрічатися і така послідовність, що приведена мною вище, це буде залежати від компанії та проєкту. 
2. Якщо говорити про сам опис дефекту, то воно трішки довге. **When opening the page there is** подібні фрази варто використовувати для динамічних речей, а у нашому випадку це статична помилка, яка не потребує ніяких дій. 
Де? - description of the road "Kyiv-Svitiaz"
Що? - grammatical error (і краще вказати саме наявну граматичну помилку)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
