### ISSUE TITLE
20200627_29_yuzhniy. Block "Дорога: Киев – Южный". Incorrect number of photos 

### ISSUE THREAD

**Issue by sokol13ua** [scholokov/long-travel-2#109]
**Steps:**
1.Open page 20200627_29_yuzhniy
2.We go down to the block "Дорога: Киев – Южный".
3.Attention to the number of photos.

**Actual result :** 
6 photos are present - incorrect.

**Expected result:**
There are 7 photos.( according to the requirements).
[https://skr.sh/s9uRtqkmHN3?a]

**Screenshot:**  https://skr.sh/s9u2K70Lcna?a

**Additional Information:**
-Operating System: Windows 10, x64.
-Browser : Google Chrome 93.0.4577.63 (Official build), (64 bit).

**Comment by scholokov** [comment]
Screenshot: https://skr.sh/s9u2K70Lcna?a
эта информация относится к экшуал результату. т.е. и должна располагаться в соответствующем блоке

**Comment by scholokov** [comment]
в экспекте тоже 6 фото...
