### ISSUE TITLE
20160814_24_Shadsk - Description of the road "Kiev-Svytyaz" punctuation error (100км) 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1094]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20160814_24_Shadsk/
2. Open the section of the road "Київ-Світязь"
3. Check the text of the description of the road "Київ-Світязь" for  punctuation error
4. Pay attention to the element  «100км»

Actual result: 100км (missing a point)
Expected result: 100км.

<img width="1440" alt="Снимок экрана 2022-08-17 в 11 31 54 AM" src="https://user-images.githubusercontent.com/110661667/185076440-bab23733-8e19-4bcf-8da3-d53bdd08c71d.png">

**Comment by DmytroMarkulych** [comment]
За уважність величезний плюс, молодець😊

**Comment by GeorgiiZ90** [comment]
fixed
