### ISSUE TITLE
20160814_24_Shadsk - Description of the road "Kiev-Svytyaz" punctuation error (5:53ч)

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1095]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20160814_24_Shadsk/
2. Open the section of the road "Київ-Світязь"
3. Check the text of the description of the road "Київ-Світязь" for  punctuation error 
4. Pay attention to the element  «5:53ч»

Actual result: 5:53ч (missing a point) 
Expected result: 5:53ч. 

<img width="1440" alt="Снимок экрана 2022-08-17 в 12 11 41 PM" src="https://user-images.githubusercontent.com/110661667/185082373-fd755b7f-b7c8-4041-a41c-7fda0b82f530.png">

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
bug fixed
