### ISSUE TITLE
20160814_24_Shadsk - Description of the road "Svytyaz-Kiev" punctuation error (527км)

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1096]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20160814_24_Shadsk/
2. Open the section of the road "Світязь-Київ"
3. Check the text of the description of the road "Світязь-«Київ» for  punctuation error 
4. Pay attention to the element  «527км»

Actual result: 527км (missing a point) 
Expected result: 527км.

<img width="1440" alt="Снимок экрана 2022-08-17 в 12 35 02 PM" src="https://user-images.githubusercontent.com/110661667/185086333-858a259a-3056-46f7-abab-4ed417eebc0a.png">

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
bug fixed
