### ISSUE TITLE
20160814_24_Shadsk - Description of the road «Svytyaz-Kyiv» punctuation error (538км)

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1097]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20160814_24_Shadsk/
2. Open the section of the road "Світязь-Київ"
3. Check the text of the description of the road "Світязь-«Київ» for  punctuation error 
4. Pay attention to the element  «538км»

Actual result: 538км (missing a point) 
Expected result: 538км.

<img width="1440" alt="Снимок экрана 2022-08-17 в 12 44 03 PM" src="https://user-images.githubusercontent.com/110661667/185088065-b5740896-2eaa-4780-95bc-3f739bcba084.png">

**Comment by DmytroMarkulych** [comment]
Зверніть, будь ласка увагу, що це є не критичні дефекти, які не ломають сайт. Вони швидше відносяться до Low priority.

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
bug fixed
