### ISSUE TITLE
20200627_29_yuzhniy. Block "Дорога: Киев – Южный". Travel map missing

### ISSUE THREAD

**Issue by yuriiboikokiev** [scholokov/long-travel-2#110]
**Steps:**
1.Open page 20200627_29_yuzhniy.
2.We go down to the block "Дорога: Киев – Южный".
3.Attention to the block context.

**Actual result :**
Travel map missing.

**Expected result:**
Travel map is present.( according to the requirements).
[https://skr.sh/s9uHSqdklxY?a]

**Screenshot:**  https://skr.sh/s9uGtMfX04m?a

**Additional Information:**
-Operating System: Windows 10, x64.
-Browser : Google Chrome 93.0.4577.63 (Official build), (64 bit).

**Comment by scholokov** [comment]
скрине карта видна. перепроверь плиз
