### ISSUE TITLE
Check requirements of TRAVELS page "Состоит из блоков: Блок для поиска путешествий, Список путешествий, сортировка от нового сверху"

### ISSUE THREAD

**Issue by ViktoriiaDerhausova** [scholokov/long-travel-2#1100]
**Steps To Reproduce:**
1. Go to https://github.com/scholokov/long-travel-2/wiki/4.1-Travels
2. Pay attention to wiki requirements of the TRAVELS page

**Actual result:**
Состоит из блоков:
Блок для поиска путешествий
Список путешествий, сортировка от нового сверху

**Expected result:**
2. Состоит из блоков:
2.1. Блок для поиска путешествий
2.2. Список путешествий, сортировка от нового сверху
2.3. Изображения путешествий с заголовком

**Notes:** В разделе wiki "1. Global.Structure.Pages" 
https://github.com/scholokov/long-travel-2/wiki/1.-Global.Structure.Pages указан ещё блок "Med size image with Title" (see attached file). 
Этот раздел будет на странице TRAVELS? Нет требований к этому разделу : изображения - это превью путешествия? Заголовок - это название?

![1](https://user-images.githubusercontent.com/107997177/185088294-07b2635d-34fc-4911-b1d0-972e5f2d649a.jpg)

**Comment by scholokov** [comment]
Этот раздел будет на странице TRAVELS? - да
Нет требований к этому разделу - https://github.com/scholokov/long-travel-2/wiki/4.1-Travels
изображения - это превью путешествия? - да
Заголовок - это название? - да
