### ISSUE TITLE
Check requirements of TRAVELS page "Имени путешествия, стране"

### ISSUE THREAD

**Issue by ViktoriiaDerhausova** [scholokov/long-travel-2#1102]
**Steps To Reproduce:**
1. Go to https://github.com/scholokov/long-travel-2/wiki/4.1-Travels
2. Pay attention to wiki requirements of the TRAVELS page

**Actual result:**
Имени путешествия
стране

**Expected result:**
3.1. Названию путешествия
3.2. Стране

**Notes:** В разделах требований 
"2. Travel.Structure" https://github.com/scholokov/long-travel-2/wiki/2.-Travel.Structure (see attached file) и
"2.3 Travel.Content"  https://github.com/scholokov/long-travel-2/wiki/2.3-Travel.Content (see attached file)
указана категория "Название путешествия". Категория "Имя путешествия" в требованиях ранее не употреблялась. 
Название путешествия в строку поиска вводить нужно полностью или достаточно одного из элементов названия (или названия объекта путешествия, или города, или страны? )
Если название городов, областей, стран должно быть на языке страны, к которой принадлежит город, а поиск производится на русском или украинском языке, каким должен быть результат поиска? 

![2](https://user-images.githubusercontent.com/107997177/185091468-cc83cefa-7a9e-43ea-8db8-10a089ec1590.jpg)
![3](https://user-images.githubusercontent.com/107997177/185091474-bd3f2ed0-9d09-42d6-90bc-3a52095a4930.jpg)

**Comment by scholokov** [comment]
общее правило (не только для багов, но и для любой деловой переписки):
если задаешь более одного вопроса - их надо нумеровать. так отвечать будет намного проще

**Comment by scholokov** [comment]
указана категория "Название путешествия". Категория "Имя путешествия" в требованиях ранее не употреблялась. - fixed
Название путешествия в строку поиска вводить нужно полностью или достаточно одного из элементов названия (или названия объекта путешествия, или города, или страны? ) - в поле можно вводить полностью или часть названия путешествия. для поиска по остальным критериям будут присутствовать отдельные поля
Если название городов, областей, стран должно быть на языке страны, к которой принадлежит город, а поиск производится на русском или украинском языке, каким должен быть результат поиска? - должно быть полное соответствие
