### ISSUE TITLE
Check requirements of TRAVELS page "Список путешествий, сортировка от нового сверху" is absent

### ISSUE THREAD

**Issue by ViktoriiaDerhausova** [scholokov/long-travel-2#1104]
**Steps To Reproduce:**
1. Go to https://github.com/scholokov/long-travel-2/wiki/4.1-Travels
2. Pay attention to wiki requirements of the TRAVELS page

**Actual result:** is absent
 
**Expected result:**
4. Список путешествий, сортировка от нового сверху
4.1.

**Notes:** Нет совсем никаких описанных требований к пункту "Список путешествий, сортировка от нового сверху". Существует ли дефолтная сортировка? Будет ли сброс сортировки, который может осуществить пользователь самостоятельно? Если по дефолту сортировка и так от нового к старому, то зачем вообще сортировка?

**Comment by scholokov** [comment]
fixed
