### ISSUE TITLE
20200307_09_lviv_vinnitsa/ the legend is written incorrectly 

### ISSUE THREAD

**Issue by rozenvasser** [scholokov/long-travel-2#1108]
Steps to reproduce:
Open page https://test.long-travel.live/20200307_09_lviv_vinnitsa/

Actual result:
legend starts from end date

Expected result:
the legend shoul start from the start date of the journey, from top to bottom

Environment:
Windos 10 Browser Google Chrome 102.0.5005.115

![5555](https://user-images.githubusercontent.com/110543889/185398233-4855cbf4-8b7d-47a8-87d7-cb5d5dbf7292.jpg)

**Comment by DmytroMarkulych** [comment]
1. Це не є дефектом. Дослідіть будь ласка дану функцію більш детальніше. 
2. В "Steps to reproduce" останній step повинен містити слова "Pay attention to...". Таким чином передостанній step вказує на блок чи розділ на сторінці, а останній із словами "Pay attention to..." на конкретний елемент на сторінці в якому і є дефект.
