### ISSUE TITLE
20200627_29_yuzhniy. Block "Южный". Incomplete display of photo thumbnails 

### ISSUE THREAD

**Issue by yuriiboikokiev** [scholokov/long-travel-2#111]
**Steps:**

1.Open page 20200627_29_yuzhniy.
2.We go down to the block "Южный".
3.Attention to thumbnail photos

**Actual result :**
Thumbnail photos are not displayed in full.

**Expected result:**
Thumbnail photos are displayed in full.( according to the requirements).
[https://github.com/scholokov/long-travel-2/wiki/Travels]

**Screenshot:**
https://skr.sh/s9uvOXxuFR5?a 
https://skr.sh/s9uTR2MS1Ix?a

**Additional Information:**
-Operating System: Windows 10, x64.
-Browser : Google Chrome 93.0.4577.63 (Official build), (64 bit).

**Comment by scholokov** [comment]
fixed
