### ISSUE TITLE
20200307_09_lviv_vinnitsa/ In legend hotel link not meet requirement

### ISSUE THREAD

**Issue by rozenvasser** [scholokov/long-travel-2#1112]
Steps to reproduce:
1 Open page https://test.long-travel.live/20200307_09_lviv_vinnitsa/
2 Pay attention to legend
3 Hotel link is missing
4 Pay attention to wiki requirements of the Travel.Content

Actual result:
Missing links

Expected result:
 Hotel links

Environment:
Windos 10 Browser Google Chrome 102.0.5005.115

![u6567y](https://user-images.githubusercontent.com/110543889/185604822-c5d74445-7995-4bf1-97d1-040e1ac05cf0.jpg)

**Comment by DmytroMarkulych** [comment]
1. Насправді ми не знаємо, чи посилання відповідає вимогам ( Возле каждого отеля должна находится линка на букинг, это приоритетно, но если нет линки на букинг должна быть линка на отель, что не является багом), тому що фактично вого не представлене на UI

2. Якщо відтворити дефект по степах, то виходить:
1. Переходимо за посиланням https://test.long-travel.live/20200307_09_lviv_vinnitsa/
2. Звернаємо увагу на вимоги Travel.Content. 
Додайте будь ласка більше деталей в steps for reproduce

**Comment by DmytroMarkulych** [comment]
При тестуванні Travel Map, буде краще звіряти вимоги до контенту, з пунктом 2.6 Travel.Map https://github.com/scholokov/long-travel-2/wiki/2.6-Travel.Map
