### ISSUE TITLE
20170709_Protsiv - Body - Photos are displayed only during page refresh

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#1115]
**Steps to reproduce:**

1. Open page https://test.long-travel.live/20170709_protsiv/
2. Scroll down the page to the "Photo gallery" block
3. Please note that **the photos on the page are not displayed**
4. Refresh the page
5. Please note that **when the page is refreshed, the photos are displayed**
6. Wait for the full page refresh
7. Please note that **photos are not displayed after refreshing the page**

**Actual Result:**
Photos are displayed **only during page refresh**

**Expected Result:**
Photos are **always** displayed

**Environments:**
Windows 10, Chrome 104.0.5112.102 (64 bit)
Android 8.1.0, Crome 104.0.5112.69

![Процев,Киевская область, Украина – Long-Travel - Google Chrome 17 08 2022 13_08_01](https://user-images.githubusercontent.com/95171672/185928786-512b9c06-80af-4a41-9199-4e91cd9744dd.png)

https://user-images.githubusercontent.com/95171672/185928770-d56f7d77-c981-4008-91a2-456d88d091ca.mp4

![photo_2022-08-22_16-05-36](https://user-images.githubusercontent.com/95171672/185928781-6e93655e-357b-4861-a4ef-ff64e538900b.jpg)

https://user-images.githubusercontent.com/95171672/185928783-dee9e674-48e7-4151-82a1-a1abf359eb08.mp4

**Comment by DmytroMarkulych** [comment]
1. В Summary потрібно уникати слів "problem", "incorrect", "doesn't work" і т.д. Використання таких слів призводить до не розуміння зі сторони розробника, і з точки зору трекінгу дефектів призведе до наявності сотень дефектів із подібними словами в summary, що максимально ускладнить пошук по ключових словах потрібного дефекту.

Приклад:
Неправильний приклад: Сторінка відображається коректно
Правильний приклад: Поле для введення логіка відображається в межах блоку «Реєстрація» на головній сторінці

2. В "Steps to reproduce" останній step повинен містити слова "Pay attention to...". Таким чином передостанній step вказує на блок чи розділ на сторінці, а останній із словами "Pay attention to..." на конкретний елемент на сторінці в якому і є дефект.

3. Виділіть, будь ласка, на скрішнотах місце дефекту (прямокутником, стрілкою)

**Comment by KaterinaNimenko35** [comment]
Description corrected

Please note the bug is duplicated  
Exists bug #921

**Comment by DmytroMarkulych** [comment]
Будь ласка, зробіть коментар, що це дублікат та закрийте баг репорт

**Comment by KaterinaNimenko35** [comment]
Bug is duplicated
Exists bug https://github.com/scholokov/long-travel-2/issues/921
