### ISSUE TITLE
 20140616_0707_Greece - In the body of the road block Kiev-Krosno doesn’t match the design in the Figma

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1117]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block of the Kiev-Krosno road

Actual result: The road block does not contain preview photos, there are no trip flags. 
Expected result: The road block contains a preview photo. Contains the Ukrainian and Polish flag of the trip. The location of the flag is on the opposite side of the travel points.

<img width="1440" alt="Снимок экрана 2022-08-23 в 1 30 01 PM" src="https://user-images.githubusercontent.com/110661667/186136361-85a4cf41-1dbf-4660-b2bd-1aab9e33ca1d.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 1 10 43 PM" src="https://user-images.githubusercontent.com/110661667/186133193-1fce61c5-aa3b-40b1-b713-264f14e6dd9c.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 1 11 20 PM" src="https://user-images.githubusercontent.com/110661667/186133227-495f5608-1747-49d3-88a8-aca655843f22.png">

**Comment by DmytroMarkulych** [comment]
Додайте, будь ласка, Actual and Expected results

**Comment by DmytroMarkulych** [comment]
Будь ласка, після виправлення зауважень переводьте із "Need more info" в "Needs triage"

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
