### ISSUE TITLE
20140616_0707_Greece - In the body of the road block Krosno-Budapest doesn’t match the design Figma

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1119]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to the roadblock Krosno-Budapest 

Actual result: The roadblock **does not contain preview** photo
Expected result: The roadblock **contains a preview** photo
<img width="1440" alt="Снимок экрана 2022-08-23 в 1 46 57 PM" src="https://user-images.githubusercontent.com/110661667/186141744-b5ac57cd-ebe5-4b06-82c6-8f569dee76dc.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 1 11 20 PM" src="https://user-images.githubusercontent.com/110661667/186142000-0851e46b-0b5e-415d-975a-af69244142a1.png">

**Comment by DmytroMarkulych** [comment]
Great Job!

**Comment by DmytroMarkulych** [comment]
Розділіть, будь ласка,  цей дефект, теж на кілька дефектів

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
