### ISSUE TITLE
20200627_29_yuzhniy. Block "27.07.2020 – 29.07.2020". Missing title H2

### ISSUE THREAD

**Issue by yuriiboikokiev** [scholokov/long-travel-2#112]
**Steps:**
1.Open page 20200627_29_yuzhniy.
2.We go down to the block ""27.07.2020 – 29.07.2020".
3.Attention  to the title H2.

**Actual result :**
H2 title is missing

**Expected result:**
Title H2 - Ukraine.( according to the requirements).
[https://github.com/scholokov/long-travel-2/wiki/Travels]

**Screenshot:** 
https://skr.sh/s9vx7FVhaFK?a

**Additional Information:**
-Operating System: Windows 10, x64.
-Browser : Google Chrome 93.0.4577.63 (Official build), (64 bit).

**Comment by scholokov** [comment]
fixed
