### ISSUE TITLE
20140616_0707_Greece - In the body of the hotel Helios block no link to the hotel

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1121]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block hotel Helios

Actual result: There is **no link to** a booking service near the hotel
Expected result: There is **a link to** a booking service near the hotel

<img width="1440" alt="Снимок экрана 2022-08-23 в 2 25 09 PM" src="https://user-images.githubusercontent.com/110661667/186146335-00c4597a-49a1-4c04-8641-a722813c9692.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 1 42 38 PM" src="https://user-images.githubusercontent.com/110661667/186146373-049f27fc-1535-46cf-86fb-313ed3ff117b.png">

**Comment by DmytroMarkulych** [comment]
👍

**Comment by scholokov** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
Verified, an issue is not reproduced
