### ISSUE TITLE
 20140616_0707_Greece - In the body of the hotel Helios block doesn’t match the design Figma

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1122]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block hotel Helios

Actual result: the hotel block contains a **doesn't preview** of the photo
 Expected result: the hotel block contains **a preview** of the photo

<img width="1440" alt="Снимок экрана 2022-08-23 в 2 25 09 PM" src="https://user-images.githubusercontent.com/110661667/186147334-b21fdd61-7d71-432a-911f-59e1e654097c.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 1 41 59 PM" src="https://user-images.githubusercontent.com/110661667/186147377-fb2e2594-5ddc-4aa5-aa10-1c33a6baacd9.png">

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
