### ISSUE TITLE
 20140616_0707_Greece - The road block Krosno-Budapest NO flags 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1124]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to the roadblock Krosno-Budapest

Actual result: there are **no flags** of Poland and Hungary aligned in the middle of the right edge on the opposite side of the travel points
Expected result: Polish and Hungarian flags are aligned in the middle of the right edge on the opposite side of the travel points

<img width="1440" alt="Снимок экрана 2022-08-23 в 2 58 13 PM" src="https://user-images.githubusercontent.com/110661667/186152351-d2fab919-7985-46ff-9ed7-56d3eef7f28f.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 2 57 32 PM" src="https://user-images.githubusercontent.com/110661667/186152390-636b9402-70d0-4730-bde9-5ec080c455a2.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 2 59 28 PM" src="https://user-images.githubusercontent.com/110661667/186152640-8a4f3e81-15ad-4b03-9a84-d27b89024a3e.png">

**Comment by DmytroMarkulych** [comment]
Actual, Expected Results: Використовуйте, будь ласка, чітке вказання UI елементів. Ви можете використовувати вирівнювання по лівому краю, вирівнювання по правому краю, вирівнювання по лівому верхньому краю і т.д.. Старайтеся уникати загальних фраз.

**Comment by LesiaBezukh** [comment]
Добрый день, тогда вопрос к формулировке в документации.

**Comment by DmytroMarkulych** [comment]
Звичайно, у нас є специфікація + дизайн Figma. Специфікація нам каже, що повинні бути прапори країн, а дизайн Figma- де? і як? вони повинні бути. Тобто коли ми вкажемо, що прапори мають вирівнюватися по центру лівого краю блока, то у девелопера не виникне питань де саме і як. Якщо ж ми вкажемо що навпроти, то девелопер ввімкне фантазію (проігнорувавши скріншоти, і таке може бути, всі ми люди), і вирівняє прапори по лівому верхньому краю. З точки зору Expected result та специфікації все вірно, навпроти? - навпроти. А от з точки зору дизайну Figma, щось піде не так. І що ми будемо мати в результаті? Вірно, трішки нервів з боку QA і трішки нервів з боку Dev. Чи потрібно воно нам? Не думаю😅 Тому інколи одне, два слова можуть вберегти не тільки нерви, а і час

**Comment by LesiaBezukh** [comment]
проверьте пожалуйста, таким образом должна выглядеть формулировка?

**Comment by DmytroMarkulych** [comment]
**Expected Result чудовий!)** в Actual Result ми говоримо про фактично те що маємо, а маємо ми відсутні прапори, тому деякі деталі можна опустити

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
