### ISSUE TITLE
20140616_0707_Greece - In the body of the Budapest block doesn’t match the design Figma

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1125]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block Budapest

Actual result: the Budapest block contains a **doesn't preview** of the photo 
Expected result: the Budapest block **contains a preview** of the photo

<img width="1440" alt="Снимок экрана 2022-08-23 в 3 02 31 PM" src="https://user-images.githubusercontent.com/110661667/186153790-7d07b7de-078c-4c2f-aa50-abfb24946a5e.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 3 06 54 PM" src="https://user-images.githubusercontent.com/110661667/186153962-30f62834-9ff5-4f07-896b-cdd40d2a4cea.png">

**Comment by scholokov** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
