### ISSUE TITLE
20140616_0707_Greece - In the ZOO block No photo preview

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1126]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block ZOO

Actual result: the hotel block contains a **doesn't preview** of the photo 
Expected result: the hotel block **contains a preview** of the photo
<img width="1440" alt="Снимок экрана 2022-08-23 в 3 08 13 PM" src="https://user-images.githubusercontent.com/110661667/186154694-edd02049-4a7d-46f1-9ed3-338f4a91244d.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 3 06 54 PM" src="https://user-images.githubusercontent.com/110661667/186154753-04a3c22a-95d2-4986-9899-caa68cc11cf1.png">

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
