### ISSUE TITLE
20140616_0707_Greece - The roadblock Budapest-Zitoradja NO preview-photo

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1127]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block Budapest-Zitoradja

Actual result: the hotel block contains a **doesn't preview** of the photo 
Expected result: the hotel block **contains a preview** of the photo
<img width="1440" alt="Снимок экрана 2022-08-23 в 3 12 29 PM" src="https://user-images.githubusercontent.com/110661667/186155929-602dadd4-187a-4be8-b533-c3f47dc813fd.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 3 18 52 PM" src="https://user-images.githubusercontent.com/110661667/186156256-461aa12b-3dfd-4bf7-bf36-db283e03e2e7.png">

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
