### ISSUE TITLE
20140616_0707_Greece - The roadblock Budapest-Zitoradja NO FLAGS 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1128]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to the roadblock Budapest-Zitoradja

Actual result: there are NO flags of Hungary and Serbia aligned in the middle of the right edge on the opposite side of the travel points
Expected result: there are flags of Hungary and Serbia aligned in the middle of the right edge on the opposite side of the travel points

<img width="1440" alt="Снимок экрана 2022-08-23 в 3 12 29 PM" src="https://user-images.githubusercontent.com/110661667/186157365-7d64ba4f-40eb-4d30-9f4e-692d12f223b6.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 2 59 28 PM" src="https://user-images.githubusercontent.com/110661667/186157466-1d25d763-c21e-4f4d-a645-142c1584e289.png">

**Comment by DmytroMarkulych** [comment]
Actual, Expected Results: Використовуйте, будь ласка, чітке вказання UI елементів. Ви можете використовувати вирівнювання по лівому краю, вирівнювання по правому краю, вирівнювання по лівому верхньому краю і т.д.. Старайтеся уникати загальних фраз.

**Comment by DmytroMarkulych** [comment]
Будь ласка, після виправлення зауважень переводьте із "Need more info" в "Needs triage"

**Comment by GeorgiiZ90** [comment]
fixed
