### ISSUE TITLE
20140616_0707_Greece - The hotel Konak Fontana block NO preview photo 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1129]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block hotel Konak Fontana 

Actual result: the hotel block contains **doesn't preview** of the photo 
Expected result: the hotel block **contains a preview** of the photo
Снимок экрана 2022-08-23 в 3.29.00 PM
<img width="1440" alt="Снимок экрана 2022-08-23 в 3 29 35 PM" src="https://user-images.githubusercontent.com/110661667/186158679-6c1633ec-d139-4136-8b2f-0b51027f6256.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 3 29 00 PM" src="https://user-images.githubusercontent.com/110661667/186158826-5ff5d537-e920-40f2-83a0-4595b5aad2b1.png">

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
