### ISSUE TITLE
20200627_29_yuzhniy. Block "Road: Южный – Винница – Киев". Incorrect name

### ISSUE THREAD

**Issue by yuriiboikokiev** [scholokov/long-travel-2#113]
**Steps:**
1.Open page 20200627_29_yuzhniy.
2.We go down to the block "Road: Южный – Винница – Киев".
3.Attention to the name block.

**Actual result :**
Block name - "Road: Южный – Винница – Киев".

**Expected result:**
Block name - Дорога: Южный – Киев( according to the requirements).
[https://github.com/scholokov/long-travel-2/wiki/Travels]

**Screenshot:**
https://skr.sh/s9vtJbhS0ZV?a

**Additional Information:**
-Operating System: Windows 10, x64.
-Browser : Google Chrome 93.0.4577.63 (Official build), (64 bit).

**Comment by scholokov** [comment]
fixed
