### ISSUE TITLE
20140616_0707_Greece - The hotel Konak Fontana block NO LINK to the hotel

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1130]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block hotel Konak Fontana 

Actual result: There is no link to a booking service near the hotel
Expected result: There is a link to a booking service near the hotel

<img width="1440" alt="Снимок экрана 2022-08-23 в 3 29 35 PM" src="https://user-images.githubusercontent.com/110661667/186159838-fe81a737-425c-4382-825d-5f6dd73b8d19.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 3 29 00 PM" src="https://user-images.githubusercontent.com/110661667/186159938-1b6ed084-006d-4ab9-8ffd-6b3963d9d1f1.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 3 38 12 PM" src="https://user-images.githubusercontent.com/110661667/186160043-63212d53-3990-413f-82f9-97faf6e5833b.png">

**Comment by scholokov** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
Verified, an issue is not reproduced
