### ISSUE TITLE
20140616_0707_Greece - The block Zitoradja NO preview photo

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1131]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block Zitoradja

Actual result: the block contains a **doesn't preview** of the photo 
Expected result: the block **contains a preview** of the photo

<img width="1440" alt="Снимок экрана 2022-08-23 в 3 40 05 PM" src="https://user-images.githubusercontent.com/110661667/186160750-abf567c7-f0c8-438f-9761-b74ca4902e6c.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 3 42 50 PM" src="https://user-images.githubusercontent.com/110661667/186160894-64a423c4-fb64-4818-9eb0-1ad5a1754b60.png">

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
