### ISSUE TITLE
20140616_0707_Greece - The backroad Zitoradja-Ouranoupolis NO FLAGS

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1134]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to  block road Zitoradja-Ouranoupolis 

Actual result: there are no flags of Serbia and Greece aligned in the middle of the right edge on the opposite side of the travel points
Expected result: there are flags of Serbia and Greece aligned in the middle of the right edge on the opposite side of the travel points
<img width="1440" alt="Снимок экрана 2022-08-23 в 3 47 55 PM" src="https://user-images.githubusercontent.com/110661667/186163521-62d7d761-461e-4c25-9971-f419a641832d.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 3 55 04 PM" src="https://user-images.githubusercontent.com/110661667/186163569-c017beab-b8ae-40d7-8c88-7b14422c671c.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 3 57 02 PM" src="https://user-images.githubusercontent.com/110661667/186163679-6437f850-0870-4273-be3f-6038cb01334b.png">

**Comment by DmytroMarkulych** [comment]
Actual, Expected Results: Використовуйте, будь ласка, чітке вказання UI елементів. Ви можете використовувати вирівнювання по лівому краю, вирівнювання по правому краю, вирівнювання по лівому верхньому краю і т.д.. Старайтеся уникати загальних фраз.

**Comment by DmytroMarkulych** [comment]
Будь ласка, після виправлення зауважень переводьте із "Need more info" в "Needs triage"

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
