### ISSUE TITLE
20140616_0707_Greece - The hotel Akrathos block NO preview photo 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1135]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block hotel Akrathos 

Actual result: the hotel block contains a **doesn't preview** of the photo 
Expected result: the hotel block **contains a preview** of the photo

<img width="1440" alt="Снимок экрана 2022-08-23 в 3 57 55 PM" src="https://user-images.githubusercontent.com/110661667/186164507-34b9615b-665f-4c58-9f4b-545ffd4ecfc5.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 3 59 53 PM" src="https://user-images.githubusercontent.com/110661667/186164526-e069ef8b-8695-4637-a53a-68e7ed7696d2.png">

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
