### ISSUE TITLE
20140616_0707_Greece - The block hotel Akrathos block NO LINK 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1136]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block hotel Akrathos 

Actual result: There is NO link to a booking service near the hotel
Expected result: There is a link to a booking service near the hotel

<img width="1440" alt="Снимок экрана 2022-08-23 в 4 02 45 PM" src="https://user-images.githubusercontent.com/110661667/186165186-5cce300a-f1a6-44db-a623-895bd41c676d.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 3 59 53 PM" src="https://user-images.githubusercontent.com/110661667/186165217-24dbfa4f-0d20-4719-92c4-ae980a8b4ae9.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 3 57 55 PM" src="https://user-images.githubusercontent.com/110661667/186165270-8964f019-1bc5-4f85-807d-b7d284d60499.png">

**Comment by scholokov** [comment]
fixed
