### ISSUE TITLE
20140616_0707_Greece - The block Beach NO preview photo

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1137]
Steps To Reproduce:
1. Open https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block Beach

Actual result: the hotel block contains a **doesn't preview** of the photo 
Expected result: the hotel block **contains a preview** of the photo
<img width="1440" alt="Снимок экрана 2022-08-23 в 4 05 34 PM" src="https://user-images.githubusercontent.com/110661667/186165900-71a5d258-869f-465b-81f0-6e02cfe67b43.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 4 07 53 PM" src="https://user-images.githubusercontent.com/110661667/186165990-4092294e-e719-4cca-816f-9eaf821d846b.png">

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
