### ISSUE TITLE
20140616_0707_Greece - The content block hotel Akrathos the youtube video link is not clickable

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1138]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Open block Hotel Acrathos 
3. Pay attention to block content video

Actual result: the link is **not clickable**
Expected result: The video should play after you click the Play button

<img width="1440" alt="Снимок экрана 2022-08-23 в 4 18 38 PM" src="https://user-images.githubusercontent.com/110661667/186168379-023e6f7d-10b6-4a47-80a7-86920dce0332.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 4 12 09 PM" src="https://user-images.githubusercontent.com/110661667/186168468-0e4a873d-7b32-41e4-90ba-de61192cb179.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 4 10 07 PM" src="https://user-images.githubusercontent.com/110661667/186168520-3d9842af-7471-4098-bb58-613c14b4c6d1.png">

**Comment by DmytroMarkulych** [comment]
Коли відтворювати дефект по степах, то ми відкриваємо посилання, і звертаємо увагу на блок із відео. Я не зміг відтворити дефект по steps. Можливо, потрібно додати більше інформації в Steps for Reproduce🤔

**Comment by DmytroMarkulych** [comment]
Будь ласка, після виправлення зауважень переводьте із "Need more info" в "Needs triage"

**Comment by DmytroMarkulych** [comment]
Зверніть будь ласка увагу на цей коментар, https://github.com/scholokov/long-travel-2/issues/1138#issuecomment-1224325933
Якщо додати в степи пункт де ми клікаємо на відео (саме вказати  **дію**, яка нам покаже, що відео не клікабельні), то це наш дефект зробить просто неймовірним)

**Comment by DmytroMarkulych** [comment]
https://github.com/scholokov/long-travel-2/issues/1138#issuecomment-1227460738

**Comment by LesiaBezukh** [comment]
я не считаю, что это является ошибкой и нужно переделывать баг-репорт. По степам и summary все понятно.

**Comment by DmytroMarkulych** [comment]
Якщо відтворювати Ваш дефект по степах, то що ми будемо мати? 

Open the page https://test.long-travel.live/20140616_0707_Greece/ - _Перейшли за посиланням, все ок_
Open block Hotel Acrathos - _Відкрили блок Hotel Acrathos_
Pay attention to block content video - _звернули свою увагу на block content video_ 
В результаті ми не робимо ніяких дій в цих степах, просто шукаємо і дивимося, а суть дефекту в тому, що ми **МАЄМО КЛІКНУТИ** на лінку. І якби ви додали між 2 та 3-м степом, click on the youtube video link, всі питання просто автоматично знялися, і в результі Ви б вказали саме ДІЮ при якій цей дефект відтворюється

**Comment by KaterinaNimenko35** [comment]
an issue is not reproduced
