### ISSUE TITLE
20140616_0707_Greece - The block Greece NO preview photo

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1139]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block Greece

Actual result: the hotel block contains a **doesn't preview** of the photo
 Expected result: the hotel block **contains a previe**w of the photo
<img width="1440" alt="Снимок экрана 2022-08-23 в 4 22 27 PM" src="https://user-images.githubusercontent.com/110661667/186169517-97026fdf-60ac-4f25-83cf-ec878ac87724.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 4 07 53 PM" src="https://user-images.githubusercontent.com/110661667/186169580-0560c15a-aa17-4128-ace9-81d7becd15ae.png">

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
