### ISSUE TITLE
20200627_29_yuzhniy. Block "Дорога: Киев – Южный".Travel date missing

### ISSUE THREAD

**Issue by yuriiboikokiev** [scholokov/long-travel-2#114]
**Steps:**
1.Open page 20200627_29_yuzhniy.
2.We go down to the block "Дорога: Киев – Южный"
3.Attention to travel date.

**Actual result :**
Travel date missing

**Expected result:**
Travel date - 27.07.2020 ( according to the requirements).
[https://github.com/scholokov/long-travel-2/wiki/Travels]

**Screenshot:**
https://skr.sh/s9vzBQ8o9uJ?a

**Additional Information:**
-Operating System: Windows 10, x64.
-Browser : Google Chrome 93.0.4577.63 (Official build), (64 bit).

**Comment by scholokov** [comment]
fixed
