### ISSUE TITLE
20140616_0707_Greece - The backroad  Greece-Bulgaria NO FLAGS

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1140]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to  block road Greece-Bulgaria

Actual result: there are **no flags** of Greece-Bulgaria aligned in the middle of the right edge on the opposite side of the travel points
Expected result: **there are flags** of Greece-Bulgaria aligned in the middle of the right edge on the opposite side of the travel points
<img width="1440" alt="Снимок экрана 2022-08-23 в 4 25 14 PM" src="https://user-images.githubusercontent.com/110661667/186170325-007e4359-d8d0-4838-8b9a-eba377e49bae.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 4 28 30 PM" src="https://user-images.githubusercontent.com/110661667/186170579-1bdd7e0e-20ad-4341-9b28-79179931f0f2.png">

**Comment by DmytroMarkulych** [comment]
Actual, Expected Results: Використовуйте, будь ласка, чітке вказання UI елементів. Ви можете використовувати вирівнювання по лівому краю, вирівнювання по правому краю, вирівнювання по лівому верхньому краю і т.д.. Старайтеся уникати загальних фраз.

**Comment by DmytroMarkulych** [comment]
Будь ласка, після виправлення зауважень переводьте із "Need more info" в "Needs triage"

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
