### ISSUE TITLE
20140616_0707_Greece - The block road Greece-Bulgaria NO preview-photo

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1141]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to  block road Greece-Bulgaria
Actual result: the block road contains a **doesn't preview** of the photo 
Expected result: the block road **contains a preview** of the photo
<img width="1440" alt="Снимок экрана 2022-08-23 в 4 25 14 PM" src="https://user-images.githubusercontent.com/110661667/186171255-10cd630d-897f-4e89-a7e2-cf63cd42febb.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 4 32 21 PM" src="https://user-images.githubusercontent.com/110661667/186171391-ad849910-40a5-41ba-90bb-e723f512300e.png">

**Comment by DmytroMarkulych** [comment]
The **backroad** Greece-Bulgaria NO preview-photo. backroad - це мова йде про дорогу додому? чи про звичайний блок "дорога"?

**Comment by DmytroMarkulych** [comment]
Давайте будемо трішки уважнішими) 
![image](https://user-images.githubusercontent.com/88647733/186873722-4428c030-86c3-4d59-9296-61134f3ac549.png)

**Comment by DmytroMarkulych** [comment]
Чудово😌

**Comment by GeorgiiZ90** [comment]
fixed
