### ISSUE TITLE
0140616_0707_Greece - The block hotel Luliaka Island NO LINK

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1143]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block hotel Luliaka Island

Actual result: There is NO link to a booking service near the hotel
Expected result: There is a link to a booking service near the hotel
<img width="1440" alt="Снимок экрана 2022-08-23 в 4 39 54 PM" src="https://user-images.githubusercontent.com/110661667/186173265-03be0fc1-8f95-4929-95fe-de6d34e756e9.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 4 36 57 PM" src="https://user-images.githubusercontent.com/110661667/186173305-8aab8c04-8e37-4c72-b4db-e03c92fba482.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 4 33 38 PM" src="https://user-images.githubusercontent.com/110661667/186173349-a459017f-9747-470d-b488-2da7c2741ec1.png">

**Comment by KaterinaNimenko35** [comment]
Verified, an issue is not reproduced
