### ISSUE TITLE
20140616_0707_Greece - The block Ruce NO preview photo

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1144]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block Ruce

Actual result: the block Ruce contains a **doesn't preview** of the photo 
Expected result: the block Ruce contains a preview of the photo
<img width="1440" alt="Снимок экрана 2022-08-23 в 4 41 35 PM" src="https://user-images.githubusercontent.com/110661667/186174142-ca0ee94d-e912-499f-8ac3-38aefc704be8.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 4 44 10 PM" src="https://user-images.githubusercontent.com/110661667/186174270-8be7e8ae-5a3c-4abb-acc2-8bab6d6bd4a0.png">

**Comment by DmytroMarkulych** [comment]
Expected result: the block **###** contains a preview of the photo

**Comment by DmytroMarkulych** [comment]
Будь ласка, після виправлення зауважень переводьте із "Need more info" в "Needs triage"

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
