### ISSUE TITLE
20140616_0707_Greece - The block road Ruse-Sibiu NO preview photo

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1145]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to  block road Ruse-Sibiu 

Actual result: the block road Ruse-Sibiu contains **doesn't preview** of the photo 
Expected result: the block road Ruse-Sibiu **contains a preview** of the photo

<img width="1440" alt="Снимок экрана 2022-08-23 в 4 45 18 PM" src="https://user-images.githubusercontent.com/110661667/186174950-acbec80f-8f25-44bc-8bd1-e2ca75e82a59.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 4 48 21 PM" src="https://user-images.githubusercontent.com/110661667/186175200-f57015fa-a36f-4762-93a0-088e432fc790.png">

**Comment by DmytroMarkulych** [comment]
Додайте, будь ласка, назву блока в Actual and Expected Results, для більш чіткого розуміння проблеми

**Comment by DmytroMarkulych** [comment]
Actual Result - я думаю якщо поставимо doesn't перев contain, то буде не перевершено)

**Comment by scholokov** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
Verified, an issue is not reproduced
