### ISSUE TITLE
20140616_0707_Greece - The backroad Ruse-Sibiu NO FLAGS 

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1146]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block road Ruse-Sibiu 

Actual result: there are NO flags of Bulgaria and Romania aligned in the middle of the right edge on the opposite side of the travel points
Expected result: there are flags of Bulgaria and Romania aligned in the middle of the right edge on the opposite side of the travel points
<img width="1440" alt="Снимок экрана 2022-08-23 в 4 51 39 PM" src="https://user-images.githubusercontent.com/110661667/186176005-ac462332-fc08-4ef5-9bec-9aa11a2e58ce.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 4 52 09 PM" src="https://user-images.githubusercontent.com/110661667/186176110-1762edc5-bbe7-4b91-9a91-c4822778bda8.png">

**Comment by DmytroMarkulych** [comment]
Actual, Expected Results: Використовуйте, будь ласка, чітке вказання UI елементів. Ви можете використовувати вирівнювання по лівому краю, вирівнювання по правому краю, вирівнювання по лівому верхньому краю і т.д.. Старайтеся уникати загальних фраз.

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
