### ISSUE TITLE
20140616_0707_Greece - The blockroad Transfagarasan NO preview-photo

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1148]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block road Transfagarasan

Actual result: the block road Transfagarasan contains a **doesn't preview** of the photo 
Expected result: the block road Transfagarasan contains a preview of the photo
<img width="1440" alt="Снимок экрана 2022-08-23 в 4 53 32 PM" src="https://user-images.githubusercontent.com/110661667/186177830-6b17895d-262a-496f-8009-e82c4ae56243.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 4 48 21 PM" src="https://user-images.githubusercontent.com/110661667/186177867-303290bd-6918-4be6-81c0-32b01e5041ab.png">

**Comment by DmytroMarkulych** [comment]
Додайте, будь ласка, назву блока в Actual and Expected Results, для більш чіткого розуміння проблеми

**Comment by DmytroMarkulych** [comment]
Будь ласка, після виправлення зауважень переводьте із "Need more info" в "Needs triage"

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
