### ISSUE TITLE
20140616_0707_Greece - The block hotel Stefani NO preview-photo

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1149]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block hotel Stefani 

Actual result: the block hotel Stefani contains a **doesn't preview** of the photo 
Expected result: the block hotel Stefani **contains a preview** of the photo
<img width="1440" alt="Снимок экрана 2022-08-23 в 5 00 55 PM" src="https://user-images.githubusercontent.com/110661667/186178595-ad7b3905-f74c-4d05-82dc-d2854842f03b.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 5 03 16 PM" src="https://user-images.githubusercontent.com/110661667/186178801-9a35adaf-ad91-4103-9c50-4df7ecc642ed.png">

**Comment by DmytroMarkulych** [comment]
Додайте, будь ласка, назву блока в Actual and Expected Results, для більш чіткого розуміння проблеми

**Comment by DmytroMarkulych** [comment]
Будь ласка, після виправлення зауважень переводьте із "Need more info" в "Needs triage"

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
