### ISSUE TITLE
20200627_29_yuzhniy. Block "Apartamenty". Date is incorrect

### ISSUE THREAD

**Issue by yuriiboikokiev** [scholokov/long-travel-2#115]
Steps:
1.Open page 20200627_29_yuzhniy.
2.We go down to the block "Apartamenty"
3.Attention to travel date.

Actual result :
Travel date - 27.06.2020 – 29.06.2020

Expected result:
Travel date - 27.07.2020 – 29.07.2020

Screenshot:
https://skr.sh/s9vL36q0HZy?a

Additional Information:
-Operating System: Windows 10, x64.
-Browser : Google Chrome 93.0.4577.63 (Official build), (64 bit).

**Comment by scholokov** [comment]
на чем основаны требования?

**Comment by yuriiboikokiev** [comment]
> на чем основаны требования?

я спросил у тебя и на основании этого написал , и плюс , что апартаменты должны быть сняты в период путешествия.   ( про требование , понял ошибку, исправил.
