### ISSUE TITLE
20140616_0707_Greece - The block hotel Stefani NO LINK

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1150]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block hotel Stefani 

Actual result: There is no link to a booking service near the hotel
Expected result: There is a link to a booking service near the hotel

<img width="1440" alt="Снимок экрана 2022-08-23 в 5 03 16 PM" src="https://user-images.githubusercontent.com/110661667/186179312-ce9da142-de07-4623-bf34-38e0674152b5.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 5 00 55 PM" src="https://user-images.githubusercontent.com/110661667/186179384-b06d0351-2376-46b0-88a8-ca98e1f63156.png">

**Comment by scholokov** [comment]
fixed
