### ISSUE TITLE
 20140616_0707_Greece - The block road Sibiu-Шаян NO preview-photo

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1151]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to  block road Sibiu-Шаян

Actual result: the block contains a **doesn't preview** of the photo 
Expected result: the block **contains a preview** of the photo
<img width="1440" alt="Снимок экрана 2022-08-23 в 5 06 38 PM" src="https://user-images.githubusercontent.com/110661667/186180272-a9f24dd2-b7ac-4a7f-949d-d6cb3c830f26.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 4 48 21 PM" src="https://user-images.githubusercontent.com/110661667/186180342-1fd7bc36-6644-44e5-8803-103d3264b1cc.png">

**Comment by DmytroMarkulych** [comment]
В Summary мова йде про road Sibiu-Шаян, а в Actual and Expected Results Ви вказуєто "hotel"

**Comment by DmytroMarkulych** [comment]
В Actual Result трішки мішанина в словах

**Comment by DmytroMarkulych** [comment]
Actual Result: 
**English:** the block contains a doesn't preview of the photo  
**Українською**  блок містить не попередній перегляд фотографії
Думаю, що так: **_блок не містить попереднього перегляду фото_** буде краще
