### ISSUE TITLE
20140616_0707_Greece - The block road Sibiu-Шаян NO FLAGS

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1152]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to  block road Sibiu-Шаян

Actual result: there are no flags of Romania and Ukraine aligned in the middle of the right edge on the opposite side of the travel points
Expected result: there are flags of  Romania and Ukraine  aligned in the middle of the right edge on the opposite side of the travel points
<img width="1440" alt="Снимок экрана 2022-08-23 в 5 12 28 PM" src="https://user-images.githubusercontent.com/110661667/186180967-6adddf0f-7040-4b4a-b97d-be1f246ed6ca.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 5 06 38 PM" src="https://user-images.githubusercontent.com/110661667/186180996-1545f342-8195-4dda-8ce4-931dff8636c0.png">

**Comment by DmytroMarkulych** [comment]
Будь ласка, після виправлення зауважень переводьте із "Need more info" в "Needs triage"

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
