### ISSUE TITLE
20140616_0707_Greece - The block Erney Laz NO preview photo

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1153]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block Erney Laz

Actual result: the Erney Laz block contains a **doesn't preview** of the photo 
Expected result: the Erney Laz block contains a preview of the photo

<img width="1440" alt="Снимок экрана 2022-08-23 в 5 13 14 PM" src="https://user-images.githubusercontent.com/110661667/186181491-4e36e0c8-1903-44ea-9281-05804b7eb1b5.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 5 15 28 PM" src="https://user-images.githubusercontent.com/110661667/186181632-101caca8-c7ea-418f-887d-a5215d2b94b3.png">

**Comment by DmytroMarkulych** [comment]
В Summary мова йде про Erney Laz, а в Actual and Expected Results Ви вказуєто "hotel"

**Comment by DmytroMarkulych** [comment]
Будь ласка, після виправлення зауважень переводьте із "Need more info" в "Needs triage"

**Comment by LesiaBezukh** [comment]
Дмитрий, я просмотрю все баги переведу в "need more info" :)

**Comment by GeorgiiZ90** [comment]
fixed
