### ISSUE TITLE
20140616_0707_Greece - The block Zoo Хуст NO preview photo

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1154]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block Zoo Хуст

Actual result: the Zoo Хуст block contains a **doesn't preview** of the photo 
Expected result: Zoo Хуст block contains a preview of the photo
<img width="1440" alt="Снимок экрана 2022-08-23 в 5 16 45 PM" src="https://user-images.githubusercontent.com/110661667/186182294-2daae961-0b37-4d5a-ad1d-311cd1ef7f13.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 5 15 28 PM" src="https://user-images.githubusercontent.com/110661667/186182349-273d48db-1667-47b6-ac9f-070dc1248951.png">

**Comment by DmytroMarkulych** [comment]
В Summary мова йде про Zoo, а в Actual and Expected Results Ви вказуєто "hotel"

**Comment by scholokov** [comment]
fixed
