### ISSUE TITLE
20140616_0707_Greece - In the header the date trip date format doesn't match design in Figma

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1157]
Steps To Reproduce:
1. Open https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to date trip 

Actual result: 16.06-07.07.2014
Expected result: 16.06.2014-07.07.2014
<img width="1440" alt="Снимок экрана 2022-08-23 в 5 33 16 PM" src="https://user-images.githubusercontent.com/110661667/186188517-d83141f2-ff3c-4260-8dc9-be22fe9c3bbe.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 5 44 52 PM" src="https://user-images.githubusercontent.com/110661667/186188658-e834f459-f30b-4b49-83f7-28a4237c90c6.png">

**Comment by DmytroMarkulych** [comment]
1. Із Summary можна не відразу здогадатися, що мова йде НЕ про формат дати, а складається враження що ми порівнюємо дату публікації на сайті із датою публікації в Figma. Додайте будь ласка більше конкретики в summary
2. А як же номерація Steps To Reproduce?)

**Comment by DmytroMarkulych** [comment]
Будь ласка, після виправлення зауважень переводьте із "Need more info" в "Needs triage"

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
