### ISSUE TITLE
 20140616_0707_Greece - The Twist Hotel block has the year of the trip doesn't match the date

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1158]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block hotel Twist date

Actual result: 16-17.06.2016
Expected result: 16.06.-17.06.2014
<img width="1440" alt="Снимок экрана 2022-08-23 в 5 51 11 PM" src="https://user-images.githubusercontent.com/110661667/186190222-3a555978-79ec-4e88-a3cd-205810359e4f.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 5 52 19 PM" src="https://user-images.githubusercontent.com/110661667/186190444-93e6b44f-c189-42e5-bded-e78f2a62cd25.png">

**Comment by DmytroMarkulych** [comment]
The Twist Hotel block has the wrong travel date - можливо там справа у форматі дати? 🤔
І якщо це так, то мабуть Expected Result не дуже відповідає прикріпленому скріншоту

**Comment by DmytroMarkulych** [comment]
В _Summary_ **НЕ**  використовуйте будь ласка слова типу wrong, incorrect, don't-doesn't work ... вони не дають конкретики в опис дефекту і збивають із суті проблеми.

**Comment by DmytroMarkulych** [comment]
Будь ласка, після виправлення зауважень переводьте із "Need more info" в "Needs triage"

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
