### ISSUE TITLE
The Poland-Hungary road block has the year of the trip doesn't match the date

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1159]
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block road Poland-Hungary year date 

Actual result: 17.06.2016
Expected result: 17.06.2014
<img width="1440" alt="Снимок экрана 2022-08-23 в 5 55 44 PM" src="https://user-images.githubusercontent.com/110661667/186191267-3850a0d7-eee1-444a-828c-e0f133c613d8.png">

**Comment by DmytroMarkulych** [comment]
В Summary НЕ використовуйте будь ласка слова типу wrong, incorrect, don't-doesn't work ... вони не дають конкретики в опис дефекту і збивають із суті проблеми.

**Comment by scholokov** [comment]
fixed
