### ISSUE TITLE
20200307_09_lviv_vinnitsa/ In travel waypoints photo doesn't match the requirement

### ISSUE THREAD

**Issue by rozenvasser** [scholokov/long-travel-2#1160]
Steps to reproduce:
1 Open page https://test.long-travel.live/20200307_09_lviv_vinnitsa/
2 Pay attention waypoints , photo is missing

Actual result:
Photo is missing

Expected result:
Photos should be at all waypoints

Environment:
Windos 10 Browser Google Chrome 102.0.5005.115

![55555](https://user-images.githubusercontent.com/110543889/186191176-b43cf162-53ce-4362-a0d9-f5b01fc5999d.jpg)

**Comment by DmytroMarkulych** [comment]
Насправді фото пристуні. Перед тим як заводити, переконайтеся що дефект відтворюється. Якщо це дефект котрий стосується UI спробуйте почистити КЕШ (Ctrl+F5) на сторінці, відкрити DevTools та звернути увагу на помилки в вклаці Console or Network. Подібні речі зберігають Ваш час та час розробника.

**Comment by DmytroMarkulych** [comment]
Зверніть, будь ласка, увагу на зауваження до оформлення дефекту.

**Comment by KaterinaNimenko35** [comment]
Verified, an issue is not reproduced

![2022-10-31 19 56 18](https://user-images.githubusercontent.com/105543094/199065885-d4a6ea3f-aa70-4a21-a7c5-f7f6aaaadfca.png)
