### ISSUE TITLE
 20140616_0707_Greece - In the Budapest block, travel date format doesn't match the design in Figma

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1162]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block Budapest date
Actual result: 17-19.06.2016
Expected result: 17.06.2014-19.06.2014
<img width="1440" alt="Снимок экрана 2022-08-23 в 6 06 20 PM" src="https://user-images.githubusercontent.com/110661667/186194067-41200a07-3f6e-4f9f-b834-be4b7e69c97c.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 6 07 19 PM" src="https://user-images.githubusercontent.com/110661667/186194248-ff870c0c-0a82-4b91-a47d-242a553d80db.png">

**Comment by DmytroMarkulych** [comment]
Із Summary можна не відразу здогадатися, що мова йде НЕ про формат дати, а складається враження що ми порівнюємо дату публікації на сайті із датою публікації в Figma. Додайте будь ласка більше конкретики в summary

**Comment by DmytroMarkulych** [comment]
Будь ласка, після виправлення зауважень переводьте із "Need more info" в "Needs triage"

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
