### ISSUE TITLE
 20140616_0707_Greece-In the Zoo Budapest block, travel date format doesn't match the design in Figma

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1163]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block Zoo Budapest
Actual result: 17-19.06.2016
Expected result: 17.06.2014-19.06.2014
<img width="1440" alt="Снимок экрана 2022-08-23 в 6 07 19 PM" src="https://user-images.githubusercontent.com/110661667/186195182-697788ec-c150-4991-9f3d-3634c4bece2b.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 6 11 54 PM" src="https://user-images.githubusercontent.com/110661667/186195311-18dfc7d5-8c4b-4875-9cc8-0906c973b52e.png">

**Comment by DmytroMarkulych** [comment]
Із Summary можна не відразу здогадатися, що мова йде про формат дати, а складається враження що ми порівнюємо дату публікації на сайті із датою публікації в Figma. Додайте будь ласка більше конкретики в summary
А як же номерація Steps To Reproduce?)

**Comment by DmytroMarkulych** [comment]
Будь ласка, після виправлення зауважень переводьте із "Need more info" в "Needs triage"

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
