### ISSUE TITLE
 20140616_0707_Greece - In the Zitoradja block, travel date format doesn't match the design in Figma

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1165]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block Zitoradja date
Actual result: 19-21.06.2016
Expected result: 19.06.2014-21.06.2014
<img width="1440" alt="Снимок экрана 2022-08-23 в 6 24 00 PM" src="https://user-images.githubusercontent.com/110661667/186198138-8a1624b8-aee0-449f-9ad5-a449a413ed4e.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 6 24 33 PM" src="https://user-images.githubusercontent.com/110661667/186198261-a95ae76e-7428-4bc1-90fd-3561efdf8fa0.png">

**Comment by DmytroMarkulych** [comment]
Із Summary можна не відразу здогадатися, що мова йде НЕ про формат дати, а складається враження що ми порівнюємо дату публікації на сайті із датою публікації в Figma. Додайте будь ласка більше конкретики в summary

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
