### ISSUE TITLE
20140616_0707_Greece - The block Serbia, travel date format doesn't match the design in Figma

### ISSUE THREAD

**Issue by LesiaBezukh** [scholokov/long-travel-2#1166]
Steps To Reproduce:
1. Open the page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to block Serbia date
Actual result: 19-21.06.2016
Expected result: 19.06.2014-21.06.2014
<img width="1440" alt="Снимок экрана 2022-08-23 в 6 26 41 PM" src="https://user-images.githubusercontent.com/110661667/186198752-758fe852-4406-47fd-b016-9798ee37cedb.png">
<img width="1440" alt="Снимок экрана 2022-08-23 в 6 07 19 PM" src="https://user-images.githubusercontent.com/110661667/186198855-8b0d2a3b-abb9-42ca-8ea2-3f7f2facd5ef.png">

**Comment by DmytroMarkulych** [comment]
Із Summary можна не відразу здогадатися, що мова йде про формат дати, а складається враження що ми порівнюємо дату публікації на сайті із датою публікації в Figma. Додайте будь ласка більше конкретики в summary

**Comment by DmytroMarkulych** [comment]
Будь ласка, після виправлення зауважень переводьте із "Need more info" в "Needs triage"

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by LesiaBezukh** [comment]
Verified
