### ISSUE TITLE
Requirements - Travel.Structure - Header - Requirements are outdated

### ISSUE THREAD

**Issue by KaterinaNimenko35** [scholokov/long-travel-2#1167]
**Steps to reproduce:**

1. Open page https://github.com/scholokov/long-travel-2/wiki/2.-Travel.Structure
2. Pay attention to the block "Header"

**Actual result:**
There are components "Хлебные крошки с категорией", "Город, Область, страна"

**Expected result:**
 "Хлебные крошки с категорией", "Город, Область, страна" components are missing

**Notes:**
Please note that the requirements are outdated due to a design update
Pay attention to the new design https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986%3A6

**Environment:**
Desktop/W10/Google Chrome 101.0.4951.67 (64 bit)

![2022-08-25 18 43 11](https://user-images.githubusercontent.com/105543094/186711182-e2dd35e7-92c0-453f-9e8d-2fad54376ef9.png)

![2022-08-25 18 42 03](https://user-images.githubusercontent.com/105543094/186711209-f7f47dfc-2f19-4042-9c5a-74954b4b5421.png)

**Comment by scholokov** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
verified
