### ISSUE TITLE
Requirements - Travel.Structure - Header - Add Component

### ISSUE THREAD

**Issue by KaterinaNimenko35** [scholokov/long-travel-2#1168]
**Description:**
Requirements - Travel. Structure - Header - add a new component, where the flag denotes the travel category - country

**Notes:**
Please note that the requirements for the **Travel. Structure - Header** section are deprecated due to a design update
Pay attention to the new design https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986%3A6
Pay attention to issue  https://github.com/scholokov/long-travel-2/issues/1167

![2022-08-25 19 08 30](https://user-images.githubusercontent.com/105543094/186716678-43cc93ed-5b89-4fda-b3e4-6994002e0adf.png)

**Comment by scholokov** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
verified
