### ISSUE TITLE
Travels - Global Map with routs - Drop-down list - Missing "Global map" element

### ISSUE THREAD

**Issue by KaterinaNimenko35** [scholokov/long-travel-2#1169]
**Steps to reproduce:**
1. Open page https://test.long-travel.live/travels/
2. Pay attention to the drop-down list with travels

**Actual result:**
Missing "Global map" element

**Expected result:**
There is a "Global map" element

**Notes:**
Pay attention, according to the requirements for the project, the "Global map" element should be in the drop-down list of travels and return the user to the general map of travels

**Environment:**
Desktop/W10/Google Chrome 101.0.4951.67 (64 bit)

![2022-08-25 19 54 58](https://user-images.githubusercontent.com/105543094/186725858-84334f86-7a01-410c-90da-afb1a8efb88a.png)

![2022-08-25 19 56 59](https://user-images.githubusercontent.com/105543094/186726200-6fcdbbd7-50ef-4883-9de8-6989ac0c5e0f.png)

![2022-08-25 20 02 25](https://user-images.githubusercontent.com/105543094/186727081-1552fed6-3f15-4474-939a-73b53a58fc82.png)

**Comment by scholokov** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
Verified,an issue is not reproduced
