### ISSUE TITLE
20200627_29_yuzhniy - "Дорога: Южный – Винница – Киев" - Title - Incorrect level of text

### ISSUE THREAD

**Issue by yuriiboikokiev** [scholokov/long-travel-2#117]
**Steps:**
1.Open page 20200627_29_yuzhniy
2.Scrol to the  "Дорога: Южный – Винница – Киев".
3.Attention to the level of text in the heading.
.
**Actual result :**
Text level - H1.

**Screenshot:** 
https://skr.sh/s9xxheWoumX?a

**Expected result:**
Text level - H2. ( according to the requirements).
[https://github.com/scholokov/long-travel-2/wiki/Travels]

**Additional Information:**
-Operating System: Windows 10, x64.
-Browser : Google Chrome 93.0.4577.63 (Official build), (64 bit).

**Comment by scholokov** [comment]
2.We go down to the block "Дорога: Южный – Винница – Киев".
--->
2.Scrol to the block "Дорога: Южный – Винница – Киев".

**Comment by scholokov** [comment]
Screenshot:
https://skr.sh/s9xxheWoumX?a

должно быть в экшуал резалте

**Comment by scholokov** [comment]
20200627_29_yuzhniy.Block "Дорога: Южный – Винница – Киев". Incorrect level of text in the title

зачем слово "block" - в тайтле? это само собой разумеещеся
и тайтл тоже должен быть написан по принципу матрешки - от большего к меньшему

20200627_29_yuzhniy - "Дорога: Южный – Винница – Киев" - Title - Incorrect level of text
