### ISSUE TITLE
20160701_0807_italy_odessa - Header - Not all travel countries are present

### ISSUE THREAD

**Issue by olgaatanasova93** [scholokov/long-travel-2#1174]
Steps to reproduce:
1. Open page https://test.long-travel.live/20160701_0807_italy_odessa
2. Pay attention to the travel category name 

Actual result:
20160701_ 0807_Italy_Odessa

Expected result:
Italy-Hungary-Austria-Germany-Poland-Ukraine

![photo_2022-08-31_18-32-36](https://user-images.githubusercontent.com/108815667/187718898-a0905851-d119-4b12-ba0c-1686571b6324.jpg)
![photo_2022-08-31_18-32-38](https://user-images.githubusercontent.com/108815667/187718904-37026fab-c90d-484b-99c6-8664589a02eb.jpg)

Environment:
Windows 10 Pro, Версия 103.0.5060.134 (Официальная сборка), (64 бит)

**Comment by DmytroMarkulych** [comment]
Зверніть, будь ласка, увагу на зауваження 1

**Comment by DmytroMarkulych** [comment]
Знову ж таки в Summary використовується слово wrong, що являє собою загальну назву. Давайте використаємо ту доступну інофрмацію яка у нас є доступною. Ми маємо специфікацію, де вказано: **В категоріях повинні бути пристуні всі країни з подорожі**. Давайте, на тверджені із специікації сформулюємо Summary яке буде унікальним для цього дефекту і буде максимально інформативно описувати проблему.

**Comment by DmytroMarkulych** [comment]
Чудово)

**Comment by scholokov** [comment]
fixed
