### ISSUE TITLE
20061028_Bila_Tserkva - travel name does not meet requirements

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/long-travel-2#1187]
Steps to reproduce:
1. Open page https://test.long-travel.live/20061028_Bila_Tserkva/
2. Pay attention to the **travel name**

Actual result: Біла Церква_Київська область_ Україна
Expected result: Біла Церква

Environment: Windows 11, Google Chrome - 104.0.5112.102, (64 бит)

![T9exqqVbLH](https://user-images.githubusercontent.com/57997443/188365671-5f3a677b-10d6-4256-96eb-deacbe3e4a7c.png)

![chrome_k6cJYZGBKD](https://user-images.githubusercontent.com/57997443/188365790-d416ddae-e646-4876-adc5-c2c82c37f183.png)

**Comment by scholokov** [comment]
fixed

**Comment by dmitryylev** [comment]
not fixed

**Comment by DmytroMarkulych** [comment]
Старайтеся, не використовувати фрази типу Not Fixed, бо так Ви вказуєте на те, що розробник ніби нічого не робив.. Краще використовуйте, що дефект відтворюється

**Comment by dmitryylev** [comment]
the bug is reproduce

**Comment by scholokov** [comment]
fixed

**Comment by dmitryylev** [comment]
verified
