### ISSUE TITLE
20061028_Bila_Tserkva - overview picture is out of shadow

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/long-travel-2#1188]
Steps to reproduce:
1. Open page https://test.long-travel.live/20061028_Bila_Tserkva/
2. Pay attention to the **overview**

Actual result: picture is out
Expected result: picture does not out

Environment: Windows 11, Google Chrome - 104.0.5112.102, (64 бит)

![chrome_KyV92lOp72](https://user-images.githubusercontent.com/57997443/188367800-a1955543-a1c0-42c3-a53e-a6d9b04a635d.png)

**Comment by scholokov** [comment]
fixed

**Comment by dmitryylev** [comment]
not fixed

**Comment by DmytroMarkulych** [comment]
Старайтеся, не використовувати фрази типу Not Fixed, бо так Ви казуєте на те, що розробник ніби нічого не робив.. Краще використовуйте, що дефект відтворюється

**Comment by dmitryylev** [comment]
verified
