### ISSUE TITLE
20061028_Bila_Tserkva - date is outside overview block

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/long-travel-2#1189]
Steps to reproduce:
1. Open page https://test.long-travel.live/20061028_Bila_Tserkva/
2. Pay attention to the **date**

Actual result: date outside overview
Expected result: date inside overview

Environment: Windows 11, Google Chrome - 104.0.5112.102, (64 бит)

![chrome_myCvqQR3BM](https://user-images.githubusercontent.com/57997443/188369546-4d8b5a1c-3815-4e2e-899e-8e983eb312a7.png)

![chrome_IUSNSYPjSj](https://user-images.githubusercontent.com/57997443/188369531-3a875e06-45bb-418c-8635-a9e249824aa4.png)

**Comment by DmytroMarkulych** [comment]
Summary написано загально, і з нього важко зрозуміти суті дефекту. У нас є конкретний дефект (дата знаходить поза блоком). Будь ласка, додайте конкретики в Summary

**Comment by dmitryylev** [comment]
summary changed

**Comment by scholokov** [comment]
fixed

**Comment by dmitryylev** [comment]
not fixed, now the date of travel is missing

**Comment by DmytroMarkulych** [comment]
Старайтеся, не використовувати фрази типу Not Fixed, бо так Ви вказуєте на те, що розробник ніби нічого не робив.. Краще використовуйте, що дефект відтворюється

**Comment by dmitryylev** [comment]
the bug is reproduced, now the date of travel is missing

**Comment by scholokov** [comment]
fixed

**Comment by dmitryylev** [comment]
verified
