### ISSUE TITLE
20200627_29_yuzhniy. Block "Дорога: Южный – Винница – Киев". The date is on the incorrect level.

### ISSUE THREAD

**Issue by yuriiboikokiev** [scholokov/long-travel-2#119]
**Steps**
1.Open page 20200627_29_yuzhniy
2.We go down to the block ""Дорога: Южный – Винница – Киев".
3.Attention on the date level

**Actual result :**
Date level - p.

**Expected result:**
Date level - H3. ( according to the requirements).
[https://github.com/scholokov/long-travel-2/wiki/Travels]

**Screenshot:**
https://skr.sh/s9xzhVdTnaT?a

**Additional Information:**
-Operating System: Windows 10, x64.
-Browser : Google Chrome 93.0.4577.63 (Official build), (64 bit).

**Comment by scholokov** [comment]
fixed
