### ISSUE TITLE
20061028_Bila_Tserkva - date of travel does not meet heading requirements

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/long-travel-2#1190]
Steps to reproduce:
1. Open page https://test.long-travel.live/20061028_Bila_Tserkva/
2. Pay attention to the **date heading** 

Actual result: H2
Expected result: H3

Environment: Windows 11, Google Chrome - 104.0.5112.102, (64 бит)

![chrome_1r48cwBp5i](https://user-images.githubusercontent.com/57997443/188370809-ca0435e3-3c0a-425d-9353-40093b545b51.png)

![chrome_C433ZLSK3A](https://user-images.githubusercontent.com/57997443/188371456-0f9bfed9-f4d6-4c77-9aac-dc428588356e.png)

**Comment by DmytroMarkulych** [comment]
В  Summary уточніть краще яким вимограм не відповідає розмір шрифту, або перефразуйте, так, щоб воно стало унікальним.

**Comment by dmitryylev** [comment]
Summary changed

**Comment by DmytroMarkulych** [comment]
А дата чого?) початку, кінця, відпочинку? мабуть подорожі) Насправді є подорожі які тривають місяць і подібних дат на сторінці може бути 10) тому, Ваш найкращий інструмент це конкретика)

**Comment by dmitryylev** [comment]
Summary changed

**Comment by DmytroMarkulych** [comment]
Насправді, все чудово і дефекти описуються доволі інофрмативно та лаконічно. Далі це окремі деталі, які в процесі роботи будуть приносити мініму запитань зі сторони девів. Тому, молодець)

**Comment by scholokov** [comment]
fixed

**Comment by dmitryylev** [comment]
not fixed

**Comment by DmytroMarkulych** [comment]
Старайтеся, не використовувати фрази типу Not Fixed, бо так Ви вказуєте на те, що розробник ніби нічого не робив.. Краще використовуйте, що дефект відтворюється

**Comment by dmitryylev** [comment]
the bug is reproduced

**Comment by DmytroMarkulych** [comment]
👍

**Comment by scholokov** [comment]
fixed

**Comment by dmitryylev** [comment]
the bug is reproduced, now heading is missing

**Comment by scholokov** [comment]
fixed

**Comment by dmitryylev** [comment]
the bug is reproduced, heading H3 still missing

**Comment by DmytroMarkulych** [comment]
@dmitryylev в специфікації оновилися вимоги до шрифтів, зверніть увагу будь ласка

**Comment by dmitryylev** [comment]
verified
