### ISSUE TITLE
20091026_1102_Toronto/ ND Missing the flag of country at header.

### ISSUE THREAD

**Issue by IrinK1** [scholokov/long-travel-2#1191]
Steps to reproduce:
1. Open https://test.long-travel.live/20091026_1102_Toronto/
2. Pay attention at header. 

Actual result:
Missing the flag of the country on the right side of the block header. 

Expected result:
The flag of country is included on the right side of the block header. 

Environment:
Windows 10 Pro (x64),
Google Chrome v.104.0.5112.102 (x64)

![Screenshot_1](https://user-images.githubusercontent.com/94845943/189128349-e205f5ed-4250-4503-9a89-f26771b6ea4d.png)
![Screenshot_4](https://user-images.githubusercontent.com/94845943/189128369-ea0d513a-71bb-4acf-b24b-12ed8c787ecb.png)

**Comment by DmytroMarkulych** [comment]
Давайте разом розберемо оформлення дефекту..

1. Старайтеся не використовувати в Summary слова типу Incorrect, Doesn't work, Wrong і т.д. Вони є загальними й не вказують на чітко на місце та суть проблеми. У нас є конкретний функціонал або UI елементи із конкретними назвами,  тому краще використовувати конкретні назви, та дотримуватися правили Де? Що? Коли? при написанні Summary.
2. "Pay attention to the header at **this** page." в сторінки this є назва, менше того у неї є навіть власне посилання, але ж мова йде не про сторінку у дефекті, а про конкретну частину UI сторінки.
3. Хорошим тоном при оформленні дефектів, є спочатку писати Actual Result, а після того, Expected, тому що після проходження всіх степів відтворення дефекту, нас має зустріти фактичний результат і показати де саме і яка проблема. Після того ми дивимося на очікуваний і знаємо як воно має працювати згідно з документацією (якщо вона є)

І насправді якщо порівняти дизайн із фактичним, що є на сторінці, то у нас виявляється, є кілька дефектів.. Я б радив цей дефект розділити на окремі дефекти, дотримуючись правил оформлення дефектів. 

Додаткова інфорамація по оформленню:  (https://portal.qax-camp.com.ua/courses/qa-basics/lessons/defect/)

**Comment by DmytroMarkulych** [comment]
В Summary у вас пише про весь Header, а в Actual Expected Result описується про прапор.. Старайтеся не використовувати такі загальні summary для баг репортів, а чітко прописувати назви UI елементів

**Comment by DmytroMarkulych** [comment]
Чудова робота)

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
verified
