### ISSUE TITLE
20160701_0807_italy_odessa - Gallery photos not loading

### ISSUE THREAD

**Issue by olgaatanasova93** [scholokov/long-travel-2#1193]
Steps to reproduce:

1. Open page https://test.long-travel.live/20160701_0807_italy_odessa
2. Pay attention to Travel.FotoGallery

Actual result:
Gallery photos not loading

Expected result:
Photos must be uploaded according to the type of photo gallery

Environment:
Windows 10 Pro, Версия 103.0.5060.134 (Официальная сборка), (64 бит)
Iphone 11 Pro Max, Версия ПО 15.6.1

![photo_2022-09-07_20-17-33](https://user-images.githubusercontent.com/108815667/188940782-299b6267-ff96-4436-af36-e81f503a806a.jpg)

![photo_2022-09-05_22-36-18](https://user-images.githubusercontent.com/108815667/188940619-67650268-f561-4925-a83f-262cb2b6859e.jpg)

![photo_2022-09-07_20-07-10](https://user-images.githubusercontent.com/108815667/188940634-b8bcef56-0df2-45d5-87f7-a47c9de03602.jpg)

**Comment by DmytroMarkulych** [comment]
Досить круто заведений дефект. Але в 2-й пункт, steps for reproduce, ви додали ще й Expected Result.. мабуть він там лишній?)

**Comment by olgaatanasova93** [comment]
Дякую! Так скопіювала випадково)

**Comment by scholokov** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
Verified, an issue is not reproduced
