### ISSUE TITLE
20191012_14_dnipro  - Language of blocks incorrect #4

### ISSUE THREAD

**Issue by IvYarosh** [scholokov/long-travel-2#1194]
Steps:

1) Go to the page Днепр 
2) Scroll the page from up to down

   Actual result: Name of blocks in russian 
   
   Expected result: Name of blocks in ukrainian

   Link with screenshoot:
![image_2022-08-23_12-54-32](https://user-images.githubusercontent.com/111362138/188957225-f3813e30-573f-4e2b-bb2b-c02ddcc02c3f.png)

   Additional Information:
 - Operating System: Windows 7 Ultimate
 - Browser: Google Chrome version 90.0.4430.93 (Official Build) (64-bit)

**Comment by DmytroMarkulych** [comment]
В Summary потрібно уникати слів "problem", "not correct", "doesn't work" і т.д. Використання таких слів призводить до не розуміння зі сторони розробника, і з точки зору трекінгу дефектів призведе до наявності сотень дефектів із подібними словами в summary, що максимально ускладнить пошук по ключових словах потрібного дефекту.
Приклад:
Неправильний приклад: Сторінка відображається коректно
Правильний приклад: Поле для введення логіка відображається в межах блоку «Реєстрація» на головній сторінці
