### ISSUE TITLE
20091026_1102_Toronto/ ND Missing preview photo at header.

### ISSUE THREAD

**Issue by IrinK1** [scholokov/long-travel-2#1195]
Steps to reproduce:

1. Open https://test.long-travel.live/20091026_1102_Toronto/
2. Pay attention preview photo is missing at header.

Actual result:
Missing preview photo at header.
Expected result:
Header must contain a preview photo.

Environment:
Windows 10 Pro (x64),
Google Chrome v.104.0.5112.102 (x64)
![Screenshot_3](https://user-images.githubusercontent.com/94845943/189127957-488e98a2-36b3-4ea6-a2a3-001ae268ded7.png)
![Screenshot_6](https://user-images.githubusercontent.com/94845943/189127981-10a8638d-dd9a-4d2b-8f1e-1fe8b0559661.png)

**Comment by DmytroMarkulych** [comment]
Чудова робота!) Але давайте трішки попрацюємо над оформленням скріншота, давайте зробимо скрін всієї сторінки, щоб було видно URL, і до виділеного дефекту прямокутником, додамо ще стрілку. І цей баг репорт буде одним із найкрутіших) 
Тут трішки інфи по оформленню скрінів.: https://portal.qax-camp.com.ua/courses/qa-basics/lessons/defect/

**Comment by IrinK1** [comment]
> Чудова робота!) Але давайте трішки попрацюємо над оформленням скріншота, давайте зробимо скрін всієї сторінки, щоб було видно URL, і до виділеного дефекту прямокутником, додамо ще стрілку. І цей баг репорт буде одним із найкрутіших) Тут трішки інфи по оформленню скрінів.: https://portal.qax-camp.com.ua/courses/qa-basics/lessons/defect/

Done!)

**Comment by scholokov** [comment]
fixed
