### ISSUE TITLE
20070722_0809_Crimea closed picture from lightbox are appeared over the map

### ISSUE THREAD

**Issue by Xalep4ik** [scholokov/long-travel-2#1196]
**Preconditions :** 
open https://test.long-travel.live/20070722_0809_Crimea/

**Steps to reproduce :**
1. Click on random preview picture from gallery 
2. Close opened window by one of way: cross in a right top of LightBox or push 'ESC' button
3. Go to the top of the Header

**Actual result :**
Picture that was opened previously is appeared over the map

**Expected result :**
Map is seen good

**Note:**
If refresh the page problem will gone till next opening the picture.

**Environment:**
Operating system: Windows 10 Pro
Browser: Google Chrome 105.0.5195.102 (64 bit)
![завантаження](https://user-images.githubusercontent.com/92167884/190085478-599ad045-562d-42cb-b968-6d299a845a10.png)

**Comment by DmytroMarkulych** [comment]
В загальному не погано заведений дефект, та є кілька неточностей
1. Actual Result являється наслідком кроків відтворення, тобто після Steps for reproduce має бути відразу Actual Result, а вже потім Expected Result. І нам не потрібно їх номерувати, тому що вони є тільки одними і не може бути кілька Actual, Expected Results
2. На скріншоті краще виділяти проблемне місце прямокутником та стрілкою.

**Comment by DmytroMarkulych** [comment]
Тоді виходить, що ми маємо 2 дефекти, тому краще завести по дефекту на кожну проблему

**Comment by Xalep4ik** [comment]
зрозумів, дякую

**Comment by DmytroMarkulych** [comment]
@Xalep4ik  Якщо, ви розділили даний баг-репорт на 2 окремих, будь ласка, напишіть комент про це і закрийте цей баг-репорт)

**Comment by Xalep4ik** [comment]
Розділив на 2 баг-репорти. А що значить закрити?

**Comment by DmytroMarkulych** [comment]
@Xalep4ik перевести в статус Closed
