### ISSUE TITLE
20071027_Uman/ In the body block flag missing

### ISSUE THREAD

**Issue by rozenvasser** [scholokov/long-travel-2#1199]
Steps to reproduce:
1 Open page https://test.long-travel.live/20071027_Uman/
2 Pay attention to body block

Actual result:
Flag is missing

Expected result:
The flag should be on the right side of the block in the middle

Environment:
Windos 10 Browser Google Chrome 102.0.5005.115
![аауаауауауауау](https://user-images.githubusercontent.com/110543889/190091873-9cd3d9ed-4647-4f00-9a6d-1830a6d359b3.jpg)

**Comment by DmytroMarkulych** [comment]
Якщо у вас є якійсь пункт або лінк на специфікацю, то його краще винести як Note. А в Expected Result його не бажано писати

**Comment by DmytroMarkulych** [comment]
Передивіться будь ласка дефект, він скоріше за все пофікшений https://i.imgur.com/D2e8TYt.jpg

**Comment by rozenvasser** [comment]
Я знаю що він вже виправленний , питання в тому чи я вірно написав Summary .

**Comment by DmytroMarkulych** [comment]
In the body block flag missing 
Давайте розберемо: 
1. Не block flag - правильніше **icon** flag 
2. In the body block - краще було використати **In the header**
