### ISSUE TITLE
20200725_26_piviha - extra block

### ISSUE THREAD

**Issue by AlexandrLyahov** [scholokov/long-travel-2#1208]
Steps to reproduce:
Open page https://test.long-travel.live/20200725_26_piviha/

Actual result:
extra block

Expected result:
no extra block

![2022-09-15 01_19_24-Window](https://user-images.githubusercontent.com/105969368/190273437-71e5425d-e320-44a4-8c33-b8fb40023971.png)

![2022-09-15 01_21_57-Window](https://user-images.githubusercontent.com/105969368/190273446-6b2db7ef-ae97-43ab-a90a-d1bc3ffc135f.png)

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 105.0.5195.127 (64bit)
Screen resolution: 1600 x 900

**Comment by DmytroMarkulych** [comment]
Будь ласка, старайтеся не використовувати загальні фрази в  summary типу there is.. у нас є чіткий UI елемент та назви відстутніх. Давайте дотримуватися принципу Де? Що? Коли? при офорамленні дефектівф

**Comment by AlexandrLyahov** [comment]
corrected

**Comment by DmytroMarkulych** [comment]
@AlexandrLyahov ознайомтеся із статею по оформленню дефектів https://portal.qax-camp.com.ua/courses/qa-basics/lessons/defect-old/
