### ISSUE TITLE
20200725_26_piviha - block map - light background

### ISSUE THREAD

**Issue by AlexandrLyahov** [scholokov/long-travel-2#1209]
Steps to reproduce:
Open page https://test.long-travel.live/20200725_26_piviha/

Actual result:
light background

Expected result:
dark background

![2022-09-15 01_29_32-](https://user-images.githubusercontent.com/105969368/190274521-aba1797b-21b9-4d0c-a6e1-5f09560c89f7.png)

![2022-09-15 01_31_07-Window](https://user-images.githubusercontent.com/105969368/190274525-1516d4c2-ff1d-4d1d-ac19-328e36f44246.png)

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 105.0.5195.127 (64bit)
Screen resolution: 1600 x 900

**Comment by scholokov** [comment]
fixed

**Comment by AlexandrLyahov** [comment]
verified
