### ISSUE TITLE
20200627_29_yuzhniy. Block "Украина". Travel date is incorrect.

### ISSUE THREAD

**Issue by yuriiboikokiev** [scholokov/long-travel-2#121]
**Steps**
1.Open page 20200627_29_yuzhniy
2.Scrol to the block "Украина".
3.Attention on the date

**Actual result :**
Date - 27.07.2020 – 29.07.2020

**Screenshot:**
https://skr.sh/s9yS2LJpeXE?a

**Expected result:**
Date - 27.06.2020 – 29.06.2020 .

**Additional Information:**
-Operating System: Windows 10, x64.
-Browser : Google Chrome 93.0.4577.63 (Official build), (64 bit).

**Comment by scholokov** [comment]
fixed
