### ISSUE TITLE
20200725_26_piviha - body blocks - does not match the design

### ISSUE THREAD

**Issue by AlexandrLyahov** [scholokov/long-travel-2#1210]
Steps to reproduce:
1.Open page https://test.long-travel.live/20200725_26_piviha/
2.Scroll down

Actual result:
does not match the design

Expected result:
design matches

![2022-09-15 01_43_59-Window](https://user-images.githubusercontent.com/105969368/190276614-a084a7ac-549e-4026-a6e8-61f7848262b1.png)
![2022-09-15 01_44_53-Window](https://user-images.githubusercontent.com/105969368/190276639-c07ef393-271a-45aa-8d25-8e9d7075eddf.png)
![2022-09-15 01_45_38-Window](https://user-images.githubusercontent.com/105969368/190276645-9c161131-6ed8-405b-9fdd-f6ca4b112f4a.png)
![2022-09-15 01_46_24-Window](https://user-images.githubusercontent.com/105969368/190276646-75289818-b411-4e46-89fe-91112d920dca.png)
![2022-09-15 01_47_17-Window](https://user-images.githubusercontent.com/105969368/190276656-37d1c6f9-2f34-4abd-a823-2add9f25b074.png)
![2022-09-15 01_48_32-Window](https://user-images.githubusercontent.com/105969368/190276659-fe4feed7-11a8-4e47-b00f-fb42014d7614.png)

![2022-09-15 01_49_27-Window](https://user-images.githubusercontent.com/105969368/190276661-71c6b8e0-c3d2-4047-b34f-b486c62a56a8.png)

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 105.0.5195.127 (64bit)
Screen resolution: 1600 x 900

**Comment by DmytroMarkulych** [comment]
Додайте будь ласка більше деталей в дефект, щоб зробити його більш чіткішим.
