### ISSUE TITLE
20070722_0809_Crimea font of "Промежуточные точки путешествия" is P in Body

### ISSUE THREAD

**Issue by Xalep4ik** [scholokov/long-travel-2#1215]
Steps to reproduce: 
1. Open https://test.long-travel.live/20070722_0809_Crimea/
2. Scroll to "Рыбачье Крым Украина"
3. Pay your attention to font of intermediate point 

Actual result:
Font of intermediate point is P

Expected result: 
Font of intermediate point is H2

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 105.0.5195.102 (64 bit)

![Промежуточные_точки_путешествия_1](https://user-images.githubusercontent.com/92167884/190381511-3f973645-254f-4422-bbba-6d60648a6070.jpg)

**Comment by DmytroMarkulych** [comment]
При написані Summary ми констатуємо помилку, тобто якщо у нас має бути Н2, а ми маємо р, то вказуємо р, а в expected result вже будемо писати що має бути Н2.

**Comment by scholokov** [comment]
fixed
