### ISSUE TITLE
На головній сторінці з права, розділ HOME, при наведенні курсором на Home міняється на чорний колір

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#1221]
Передумови :
Відкрити  https://test.long-travel.live/
Кроки для відтворення:
1.  На сторінці з права наведіть курсор на меню  TRAVALS
2.  Навидіть курсор на  Home яка знаходиться з ліва в верхній частині сторінки

Фактичний результат: При наведення курсором на кнопку ''Home'' вона світиться чорним кольором
Очікуваний результат: При наведенні курсором на кнопку ''Home'' вона повинна світитися білим кольором

Середовище: Windows 10 Pro
Операційна система:  
Браузер: Google Chrome  Версія

https://user-images.githubusercontent.com/113175298/190630218-1edda38b-8b6a-4371-a90b-a8322eab9f8c.mp4

![Screenshot_2](https://user-images.githubusercontent.com/113175298/190630399-44789933-276c-4168-8e41-fe6030515f98.jpg)
 105.0.5195.127 (Официальная сборка), (64 бит)

**Comment by DmytroMarkulych** [comment]
1. Це не кнопка, це хлібна крихта (breadcrumbs). Ось трішки інформації на рахунок них  https://www.ukraine.com.ua/uk/blog/seo-optimization/chto-takoe-hlebnie-kroshki-na-sajte-i-zachem-oni-nuzhni.html
2. Старайтеся не використовувати подібні фрази "зовсім не замітною" в summary. При написанні Summary ми констатуємо дефект дотримуючись правила Де? Що? Коли? . В загальному, структура Вашого summary вірна, тільки потрібно кілька виправлень.
3. "Кроки для відтворення:" - в 1-му кроці Ви вказуєте на те, що потрібно клікнути на "кнопку", хоча це не кнопка, а меню. 
І в 2-му кроці вказуєте, що потрібно клікнути, хоча в summary, на відео, і в Expected Result говориться про наведення курсора.

**Comment by Nadiyk** [comment]
Виправила, тілки не зрозуміла, потрібно замість "кнопки" вказувати  хлібна крихта (breadcrumbs)???

**Comment by Nadiyk** [comment]
Доброго вечора, я вибачаюсь, але хочу уточнити один момент, після того як я
по вашому коментарю виправляю опис багу тоді мені необхідно вручну
перенести баг з колонки "Потрібно більше інформації" в колонку "Для дев?"

пт, 16 сент. 2022 г. в 17:45, DmytroMarkulych ***@***.***>:

**Comment by DmytroMarkulych** [comment]
@Nadiyk Попутані фактині та актуальні результати

**Comment by Nadiyk** [comment]
Виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk а тепер давайте зробимо так, щоб після кроків після вітворення йшов фактичний результат, а після нього очікуваний

**Comment by Nadiyk** [comment]
Виправила

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
Pass
