### ISSUE TITLE
20200627_29_yuzhniy. Block "Южный". Travel date is incorrect.

### ISSUE THREAD

**Issue by yuriiboikokiev** [scholokov/long-travel-2#123]
**Steps**
1.Open page 20200627_29_yuzhniy
2.Scrol to the block "Южный".
3.Attention on the date

**Actual result :**
Date - 28.07.2020

**Screenshot:**
https://skr.sh/s9yG41Bh4Zl?a

**Expected result:**
Date - 28.06.2020

Additional Information:
-Operating System: Windows 10, x64.
-Browser : Google Chrome 93.0.4577.63 (Official build), (64 bit).

**Comment by scholokov** [comment]
fixed
