### ISSUE TITLE
20151226_Kiev_Fashion_Park/ ND Фотографія не закривається після натискання на кнопку "Закрити"

### ISSUE THREAD

**Issue by ABatalov** [scholokov/long-travel-2#1233]
Кроки для відтворення:
1.Відкрити https://test.long-travel.live/20151226_Kiev_Fashion_Park/
2.Натисніть випадкове зображення попереднього перегляду з галереї
3.Закрийте відкрите вікно одним із способів: хрестик у правому верхньому куті LightBox або натисніть кнопку «ESC».
4.Перейти до верхньої частини заголовка
Фактичний результат:
Поверх карти з'являється зображення, яке було відкрито раніше

Очікуваний результат :
фото закривається хрестиком у правому верхньому куті LightBox або натисканням кнопки «ESC»

Середовище:
Операційна система: Windows 10
Браузер: Google Chrome Версія 105.0.5195.127 (64 біт)
Розрішення екрану 1366х768
![не закривається](https://user-images.githubusercontent.com/113344723/190897309-4dac3f2b-e9a1-4675-b7d9-4d400e0d803f.png)

**Comment by DmytroMarkulych** [comment]
@RomanTaradai  Різні URL  на скріншоті і в Кроках для відтворення

**Comment by RomanTaradai** [comment]
> @RomanTaradai Різні URL на скріншоті і в Кроках для відтворення

виправив

**Comment by DmytroMarkulych** [comment]
@RomanTaradai 
Якщо сформулювати summary за принципом Де? Що? Коли? то у нас вийде наступне
Фотографія не закривається після натискання на кнопку "Закрити"
Зверніть будь ласка на це увагу

**Comment by RomanTaradai** [comment]
> @RomanTaradai Якщо сформулювати summary за принципом Де? Що? Коли? то у нас вийде наступне Фотографія не закривається після натискання на кнопку "Закрити" Зверніть будь ласка на це увагу

Дякую, виправив

**Comment by DmytroMarkulych** [comment]
@RomanTaradai  Давайте звернемо увагу на Очікуваний результат. Суть дефекту що у нас не закривається фото, а в очікуваному результаті ми кажемо щоб було добре видно карту

**Comment by RomanTaradai** [comment]
> @RomanTaradai Давайте звернемо увагу на Очікуваний результат. Суть дефекту що у нас не закривається фото, а в очікуваному результаті ми кажемо щоб було добре видно карту

виправив

**Comment by RomanTaradai** [comment]
> fixed

помилку виправлено

**Comment by scholokov** [comment]
please retest
