### ISSUE TITLE
20091026_1102_Toronto/ ND Photo Gallery. Image could not be loaded on mobile devices.

### ISSUE THREAD

**Issue by IrinK1** [scholokov/long-travel-2#1234]
Steps to reproduce:
1. Open https://test.long-travel.live/20091026_1102_Toronto on mobile devices. 
2. Scroll down the page to photo gallery 
3. Open photos preview
4. Pay attention to LightBox. Photos could not be loaded 
 
 Actual result: 
Photos could not be loaded in LightBox on mobile devices 
Expected result:
Photos is loaded in LightBox on mobile devices 

environment:
Iphone XR
IOS 16, Google Chrome 
Iphone XS,
IOS 15, Safari 
Samsung Galaxy A32,
Android 11, Google Chrome 
![B4674873-9FA7-4982-8406-3438ACE37D56](https://user-images.githubusercontent.com/94845943/190676567-79dc7322-de46-4289-977e-224113c6949d.jpeg)
![91FFD833-49B2-4DE6-B689-72F747E9F9A3](https://user-images.githubusercontent.com/94845943/190676570-6aabe4c5-7bc6-4310-9221-b96fd573f323.jpeg)
![487ACF04-2F41-418A-BA70-2298AC81100D](https://user-images.githubusercontent.com/94845943/190676572-05d22ac9-b6d6-41eb-bcb8-8c1182472543.jpeg)

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
defect is reproduced
![photo_2022-09-26_12-19-00](https://user-images.githubusercontent.com/94845943/192241134-9aa1dadf-83fd-4e12-a41c-2ac73e817720.jpg)
![photo_2022-09-26_12-20-47](https://user-images.githubusercontent.com/94845943/192241144-e255d3e6-b934-4353-b72d-6f22f50c0c7a.jpg)

**Comment by scholokov** [comment]
please retest

**Comment by IrinK1** [comment]
@scholokov defect is reproduced
![photo_2022-10-18_17-10-24](https://user-images.githubusercontent.com/94845943/196455046-2572e453-a57d-4257-b541-9c53e2e21d86.jpg)

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
Verefied
