### ISSUE TITLE
20071027_uman - Body - Preview - The name of the travel is duplicated

### ISSUE THREAD

**Issue by rozenvasser** [scholokov/long-travel-2#1235]
**Steps to reproduce:**

1. Open page https://test.long-travel.live/20071027_Uman/
2. Scroll down the page to the Body block
3. Pay attention to the preview

**Actual result:**
The name of the travel is **duplicated**

**Expected result:**
The name of the travel is **not duplicated**

**Environment:**
Windos 10 Browser Google Chrome 102.0.5005.115

![ktujdjtfkjdty](https://user-images.githubusercontent.com/110543889/190843214-5b6572a6-b8a3-40ab-acd4-8b9b379f7d62.jpg)

**Comment by DmytroMarkulych** [comment]
**Де?** - Під блоком Header пристуня **Що?** - назва подорожі "Умань, Національний ...."

**Comment by DmytroMarkulych** [comment]
Приклад правильного Summary з дотриманням послідовності Де? Що? Коли? 
**Де?** - Під блоком Header пристуня **Що?** - назва подорожі "Умань, Національний ...."

**Comment by KaterinaNimenko35** [comment]
Verified, an issue is not reproduced
