### ISSUE TITLE
20070722_0809_Crimea functional buttons in Header doesn't respond after closing lightbox

### ISSUE THREAD

**Issue by Xalep4ik** [scholokov/long-travel-2#1236]
[17a23112-9609-4058-b414-6571f89afae5.webm](https://user-images.githubusercontent.com/92167884/192241603-31f9b43a-0537-4309-8bd9-6fa39801232e.webm)
Steps to reproduce:

   1.Open https://test.long-travel.live/20070722_0809_Crimea/
   2.Click on random preview picture from gallery
   3.Close opened window by one of way: cross in a right top of LightBox or push 'ESC' button
   4.Go to the top of the Header
   5.Click on buttons "HOME" , "TRAVELS" , "TOPICS" 

Actual result :
Functional buttons in top of the Header doesn't respond

Expected result :
Opens selected section

Note:
If refresh the page problem will gone till next opening the picture.

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 105.0.5195.102 (64 bit)

![b1](https://user-images.githubusercontent.com/92167884/192242876-19854cb1-deba-4e57-803d-3db8dc601e16.jpg)

Video:

[17a23112-9609-4058-b414-6571f89afae5.webm](https://user-images.githubusercontent.com/92167884/192241735-2097d8bd-b6bd-4517-a397-4f9c097ac6a0.webm)

**Comment by DmytroMarkulych** [comment]
Чудова робота!) Але давайте, зробимо скрін всієї сторінки, а краще запис екрану

**Comment by Xalep4ik** [comment]
Додав)
