### ISSUE TITLE
20140616_0707_Greece/ ND - Body-All travel names are repeated

### ISSUE THREAD

**Issue by olgaatanasova93** [scholokov/long-travel-2#1241]
Steps to reproduce:

1. Open page https://test.long-travel.live/20140616_0707_Greece/
2. Pay attention to the travel category "Body". Delete all duplicate travel names, according to the specified requirements. Photo attached below

Actual result:
All travel names are duplicated

Expected result:
The name of the travel should not be repeated

Environment:
Windows 10 Pro, Версия 103.0.5060.134 (Официальная сборка), (64 бит)
Iphone 11 Pro Max, Версия ПО 15.6.1

![photo_2022-09-18_11-11-27](https://user-images.githubusercontent.com/108815667/190894425-a8045521-efbd-48a2-84dd-e07bf5576f28.jpg)

![photo_2022-09-18_11-11-45](https://user-images.githubusercontent.com/108815667/190892766-02ccadc8-0266-4ceb-93a5-dbe9809d92f6.jpg)

![photo_2022-09-18_11-11-17](https://user-images.githubusercontent.com/108815667/190892800-ec0f655a-803b-45f7-b37e-aed01517b29e.jpg)

![photo_2022-09-18_11-23-04](https://user-images.githubusercontent.com/108815667/190894669-342101e8-0f80-462a-a071-7089822f6e60.jpg)

**Comment by DmytroMarkulych** [comment]
Можна деталей в баг-репорт?

**Comment by scholokov** [comment]
fixed
