### ISSUE TITLE
20061028_Bila_Tserkva - in travel point, html-heading of travel name (H1) and travel date (H3) is missing

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/long-travel-2#1246]
Steps to reproduce:
1. Open page https://test.long-travel.live/20061028_Bila_Tserkva/
2. Pay attention in the travel point to the **html-heading** of **travel name** and **travel date**

Actual result: heading is missing
Expected result: travel name is  H1, travel date is H3

Environment: Windows 11, Google Chrome - 105.0.5195.127, (64 бит)

![chrome_FNN240REww](https://user-images.githubusercontent.com/57997443/190976534-10e1f712-7cf8-4885-87ba-4480ba6646a2.png)

![ShareX_ruURO1HBby](https://user-images.githubusercontent.com/57997443/190976565-c5a67c7c-484c-40d8-bf71-2f07e2fe8c95.png)

**Comment by DmytroMarkulych** [comment]
@dmitryylev насправді Назва та Дата подорожі не пропущені, вони там є)

**Comment by dmitryylev** [comment]
> @dmitryylev насправді Назва та Дата подорожі не пропущені, вони там є)

Heading - це позначення заголовка у html-коді, який використовується для оптимізації SEO доступності сайту у Google пошуку (як варіант), в описі багу та на скріні вказано, що позначення heading у коді відсутнє

**Comment by scholokov** [comment]
fixed

**Comment by dmitryylev** [comment]
the bug is reproduced

**Comment by DmytroMarkulych** [comment]
@dmitryylev    в специфікації оновилися вимоги до шрифтів, зверніть увагу будь ласка

**Comment by dmitryylev** [comment]
verified
