### ISSUE TITLE
20061028_Bila_Tserkva - in travel point, region and country is missing

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/long-travel-2#1247]
Steps to reproduce:
1. Open page https://test.long-travel.live/20061028_Bila_Tserkva/
2. Pay attention to **region** and **country** in travel point are missing

Actual result: region and country are missing
Expected result: Київська область, Україна

Environment: Windows 11, Google Chrome - 104.0.5112.102, (64 бит)

![chrome_tLja9EuB5s](https://user-images.githubusercontent.com/57997443/191708262-2442f49b-a6cb-4321-b482-98650403c09b.png)

![chrome_ffzJKcuabc](https://user-images.githubusercontent.com/57997443/191707774-e9234d59-83bb-40c6-9061-d182bbcc3943.png)
![37VZ3d7NCR](https://user-images.githubusercontent.com/57997443/191707803-956c7328-55cc-4ba6-8b4b-3d5f1454d2be.png)

**Comment by DmytroMarkulych** [comment]
Щось не можу зрозуміти суті дефекту, Ви пишете, що назва подорожі відсутня, хоча там є блок із назвою населеного пункут Біла Церква..

**Comment by dmitryylev** [comment]
> Щось не можу зрозуміти суті дефекту, Ви пишете, що назва подорожі відсутня, хоча там є блок із назвою населеного пункут Біла Церква..

Відсутня область та країна, що і написано в назві. Змінив скріншоти на біль зрозуміліші.

**Comment by DmytroMarkulych** [comment]
@dmitryylev чудова вийшла робота!)

**Comment by scholokov** [comment]
fixed

**Comment by dmitryylev** [comment]
баг частково відтворюється, додана область, але відсутня країна

**Comment by scholokov** [comment]
якщо баг "частково" відтворюється - то це вже інший баг

**Comment by dmitryylev** [comment]
verified
