### ISSUE TITLE
In content requirements the information how to display the preview travel and preview travel point is missing

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/long-travel-2#1249]
Steps to reproduce:
1. Open design in figma https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986%3A6
2. Open content requirements https://github.com/scholokov/long-travel-2/wiki/2.3-Travel.Content
3. Pay attention that the information how to display the **preview travel** and **preview travel point** is missing

Actual result: the information how to display is missing

Expected result:
- Preview путешествия должно быть уникальным в разрезе всех путешествий
![chrome_zdxE4FhSZJ](https://user-images.githubusercontent.com/57997443/191205474-1790fc9c-87bf-417c-8893-365ffaeafc48.png)

- Preview точек путешествия имеют стандартный вид, в зависимости от особености точки
![chrome_2BpxZpdmSp](https://user-images.githubusercontent.com/57997443/191204372-0b00b7a5-a557-4163-9e3f-6b068a5fa80a.png)

**Comment by DmytroMarkulych** [comment]
@dmitryylev додайте будь ласка деталей в баг репорт, щоб більш чіткіше розуміти проблему

**Comment by dmitryylev** [comment]
changed

**Comment by scholokov** [comment]
fixed
https://github.com/scholokov/long-travel-2/wiki/2.-Travel.Structure

**Comment by dmitryylev** [comment]
verified
