### ISSUE TITLE
20061028_Bila_Tserkva - travels point review picture does not match the picture in figma

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/long-travel-2#1250]
Steps to reproduce:
1. Open design in Figma https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986%3A6
2. Open page https://test.long-travel.live/20061028_Bila_Tserkva/
3. Pay attention to the travels point review image

Actual result: 
![chrome_G6QcjO27kP](https://user-images.githubusercontent.com/57997443/190989149-fea28a43-36f9-4f9a-8587-6a39dcbeb26e.png)

Expected result: 
![chrome_ZmpV2UA1zX](https://user-images.githubusercontent.com/57997443/193506722-3eb3b0f3-e793-4a63-bf9f-04957234ab41.png)

Environment: Windows 11, Google Chrome - 104.0.5112.102, (64 бит)

![chrome_4cUDHx6Tmu](https://user-images.githubusercontent.com/57997443/193506888-5e56bf94-263a-40c9-8620-8afb2afdca00.png)

![chrome_NHG53vpIWj](https://user-images.githubusercontent.com/57997443/190989077-c7602724-0c72-49f1-8527-a5cd554fcfbb.png)

**Comment by dmitryylev** [comment]
> @dmitryylev вийшов дуже загальний баг репорт, будь ласка офоміть відповідно правил оформлення дефектів https://portal.qax-camp.com.ua/courses/qa-basics/lessons/defect-old/

в описі дефекта вказано що? (review) де? (travel point) що потрібно зробити? (я не пишу що не та картинка, так як це не етично, тому я написав потрібно замінити should be change), вказано приклад картинки на яку потрібно замінити, та вказаний скрін де знаходиться цей блок.  Якщо допоможете знайти чого саме не вистачає - буду вдячний.

**Comment by DmytroMarkulych** [comment]
@dmitryylev якщо ми відкриємо специфікацію https://github.com/scholokov/long-travel-2/wiki/2.-Travel.Structure 
то можна побачити, що дані є в Header та Body. Відповідно ми їх можемо порівняти із фактичним результатом, та додати деталей в баг репорт file:///home/markulych/Pictures/12313123123.png

**Comment by dmitryylev** [comment]
змінено опис дефекту

**Comment by dmitryylev** [comment]
changed

**Comment by scholokov** [comment]
fixed

**Comment by dmitryylev** [comment]
verified
