### ISSUE TITLE
20091026_1102_Toronto/ ND Block Hotel missing preview photo

### ISSUE THREAD

**Issue by IrinK1** [scholokov/long-travel-2#1252]
Steps to reproduce:

1. Open https://test.long-travel.live/20091026_1102_Toronto/
2. Scroll down the page to the hotel block.
3. Pay attention hotel block.

Actual result:
Preview photo is missing at hotel block
Expected result:
Preview photo is included at hotel block

Environment:
Windows 10 Pro (x64),
Google Chrome v.104.0.5112.102 (x64)
![Screenshot_1](https://user-images.githubusercontent.com/94845943/190997612-d9d43925-663c-41f2-9439-cefb82abb75d.png)
![Screenshot_2](https://user-images.githubusercontent.com/94845943/190997636-6c25b0d5-9ecf-4baf-8cbc-42abe098b1db.png)

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
Verified

**Comment by IrinK1** [comment]
bug is reproduced
![Screenshot_2](https://user-images.githubusercontent.com/94845943/201662420-fe10495c-0501-4890-ac60-e06ee485fbb4.png)

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
verified
