### ISSUE TITLE
20091026_1102_Toronto/ ND Block hotel. The photo gallery tape doesn't meet the requirements

### ISSUE THREAD

**Issue by IrinK1** [scholokov/long-travel-2#1253]
Steps to reproduce:

1. Open https://test.long-travel.live/20091026_1102_Toronto/
2. Scroll down the page to the hotel block.
3. Pay attention to the photo gallery at hotel block.

Actual result:
The photo gallery type doesn't meet the requirements (Square Grid)
Expectsd result:
The photo gallery type should be Justified Grid.

Environment:
Windows 10 Pro (x64),
Google Chrome v.104.0.5112.102 (x64)
![Screenshot_3](https://user-images.githubusercontent.com/94845943/190999658-68617efa-a946-477e-b20d-8975a605924d.png)
![Screenshot_4](https://user-images.githubusercontent.com/94845943/190999677-b6eb508d-96a2-44a4-b4a0-92dc7557632b.png)

**Comment by scholokov** [comment]
please retest
