### ISSUE TITLE
20091026_1102_Toronto/ ND Global map. Missed element "link" of travel on the global map

### ISSUE THREAD

**Issue by IrinK1** [scholokov/long-travel-2#1258]
Steps to reproduce:

1. Open https://test.long-travel.live/travels/
2. Search 20091026_1102_Toronto
3. Press the button to go to the detailed description of the trip.
4. Pay attention element "link" is missed 

Actual result:
Element "link" of travel is missed on the global map.
Expected result:
Element "link" of travel is included on the global map.

Environment:
Windows 10 Pro (x64),
Google Chrome v.104.0.5112.102 (x64
![Screenshot_9](https://user-images.githubusercontent.com/94845943/191025228-49ce3378-8f75-44d7-8fa7-25c872167eeb.png)
![Screenshot_10](https://user-images.githubusercontent.com/94845943/191025238-9e2bf70f-518a-4579-8a8f-63c6fcfc6f91.png)

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
verified
