### ISSUE TITLE
20091026_1102_Toronto/ ND Photo Gallery. Image could not be loaded on PC.

### ISSUE THREAD

**Issue by IrinK1** [scholokov/long-travel-2#1261]
Steps to reproduce:

1. Open https://test.long-travel.live/20091026_1102_Toronto
2. Scroll down the page to photo gallery
3. Open photos preview
4. Pay attention to LightBox. Photo could not be loaded

Actual result:
Photo could not be loaded in LightBox on PC
Expected result:
Photos are loaded in LightBox on PC

Environment:
Windows 10 Pro (x64),
Google Chrome v.104.0.5112.102 (x64)
![Screenshot_15](https://user-images.githubusercontent.com/94845943/191220127-44332e92-731d-4cfd-a521-0b2dde45e110.png)
![Screenshot_16](https://user-images.githubusercontent.com/94845943/191220134-e9f77b85-cf91-461d-9992-bb2f7268e4cf.png)
![Screenshot_17](https://user-images.githubusercontent.com/94845943/191220136-60dafe59-c8ce-48ee-b1e7-ab6bd6eedca4.png)

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
defect is reproduced
![Screenshot_14](https://user-images.githubusercontent.com/94845943/192234393-10cbd76b-6995-45be-ba13-4a2a75ff69f2.png)

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
defect is reproduced partially
![Screenshot_9](https://user-images.githubusercontent.com/94845943/196455805-2037bc6f-f2c1-414b-9df4-cd0b60287312.png)
![Screenshot_10](https://user-images.githubusercontent.com/94845943/196455811-031d0642-f8c7-4aca-848c-f803e599e6bf.png)

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
Verefied
