### ISSUE TITLE
20091026_1102_Toronto/ ND Block Downtown-Toronto. Missed preview photo

### ISSUE THREAD

**Issue by IrinK1** [scholokov/long-travel-2#1262]
Steps to reproduce:

1. Open https://test.long-travel.live/20091026_1102_Toronto/
2. Scroll down the page to the Downtown-Toronto block.
3. Pay attention Downtown-Toronto block.

Actual result:
Preview photo is missing at Downtown-Toronto block
Expected result:
Preview photo is included at Downtown-Toronto block

Environment:
Windows 10 Pro (x64),
Google Chrome v.104.0.5112.102 (x64)
![Screenshot_18](https://user-images.githubusercontent.com/94845943/191224725-81a906a7-3a63-4073-b941-077f39857679.png)
![Screenshot_20](https://user-images.githubusercontent.com/94845943/191224734-5d9839bd-1d45-4bb4-8444-a6cbf15e1633.png)

**Comment by IrinK1** [comment]
bug is reproduced
![Screenshot_3](https://user-images.githubusercontent.com/94845943/201662992-60c4e2bf-20cd-4afd-ada5-f789472c54d8.png)

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
verified
