### ISSUE TITLE
20151226_Kiev_Fashion_Park/ NDзаголовок блоку - не весь фон темний

### ISSUE THREAD

**Issue by RomanTaradai** [scholokov/long-travel-2#1274]
Кроки для відтворення:
1.Відкрийте https://test.long-travel.live/20151226_Kiev_Fashion_Park/
2. Звернути увагу на заголовок блоку

Фактичний результат:
не весь фон темний

Очікуваний результат:
весь фон темний
Середовище:
Операційна система: Windows 10
Браузер: Google Chrome Версія 105.0.5195.127 (64 біт)
Розрішення екрану 1366х768
![заголовок](https://user-images.githubusercontent.com/113344723/191326797-65b38b1a-3760-446e-a721-3f1978b83488.png)
![Screenshot_3](https://user-images.githubusercontent.com/113344723/191327125-d909b3a9-d04b-405e-9824-10b80439a387.png)

**Comment by DmytroMarkulych** [comment]
@RomanTaradai  Різні URL  на скріншоті і в Кроках для відтворення

**Comment by RomanTaradai** [comment]
> @RomanTaradai Різні URL на скріншотах і в Кроках для відтворення

виправив

**Comment by scholokov** [comment]
fixed

**Comment by RomanTaradai** [comment]
> fixed

виправлено
