### ISSUE TITLE
20070406_09_Lviv/ ND.In the travel block an excess second map.

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#1302]
**Steps to reproduce:**

**1.** Open page https://www.long-travel.live/20070406_09_Lviv/
**2.** Scroll down the page to the trip map.
**3.** Note the second block of travel map.

**Actual result:**
Two blocks of map on the travel.

**Expected result:**
There should be only one block with a map.

**Environment:**
MacBook/macOS Monterey 12.5/Chrome 105.0.5195.125 (arm64)

![lviv nd 1](https://user-images.githubusercontent.com/108996909/191510296-e5345e05-d0fb-4ea8-88b4-72ee9df5c7b2.png)
![lviv nd 2](https://user-images.githubusercontent.com/108996909/191510368-b62aa99d-0651-4183-9879-56b4289c0274.png)

**Comment by SerhiiBurdieiev** [comment]
Corrected.

**Comment by scholokov** [comment]
fixed

**Comment by SerhiiBurdieiev** [comment]
Not fixed.

**Comment by DmytroMarkulych** [comment]
@SerhiiBurdieiev старайтеся не використовувати not fixed, краще використовуйте defect reproduce

**Comment by scholokov** [comment]
якщо помилка все ще існую, приєднуйте скріншот, як підтвердження
також перевірте, чи ви використовуюєте коректний енвайромент
https://www.test.long-travel.live/20070406_09_Lviv/
