### ISSUE TITLE
20210510_stariy_solvin/ 2 preview

### ISSUE THREAD

**Issue by AleferkoIurii** [scholokov/long-travel-2#1306]
STR:

https://test.long-travel.live/20210510_stariy_solvin/

Actual result:
Preview above the map and another preview under the map

Expected result:
Preview above the map

Environment:
Desktop/ Windows 11 Home 21H2(22000.675)/ 1440x900/ Chrome 105.0.5195.127 (Official Build) (64-bit)
![2t](https://user-images.githubusercontent.com/104926198/191534609-91485560-32c6-460d-8eb0-b7a2295db23f.jpg)

**Comment by DmytroMarkulych** [comment]
@AleferkoIurii  зверніть увагу на Специфікацію https://github.com/scholokov/long-travel-2/wiki/2.-Travel.Structure

**Comment by KaterinaNimenko35** [comment]
The bug is not relevant

![2022-10-30 16 57 42](https://user-images.githubusercontent.com/105543094/198882873-278fefd6-c700-443d-b06b-11feaafb4949.png)
![2022-10-30 17 00 46](https://user-images.githubusercontent.com/105543094/198882996-863083d8-f90f-4612-a5a5-2c212c421329.png)
