### ISSUE TITLE
20191019_roshen/ Point font is not H2

### ISSUE THREAD

**Issue by AleferkoIurii** [scholokov/long-travel-2#1315]
STR:

1. Open https://test.long-travel.live/20191019_roshen/
2. Look at point name "Киев, Украина"

Actual result:
text's font is not H2

Expected result:
text's font is H2

Environment:
Desktop/ Windows 11 Home 21H2(22000.675)/ 1440x900/ Chrome 105.0.5195.127 (Official Build) (64-bit)
![SizetxtRosh](https://user-images.githubusercontent.com/104926198/191544697-21e2e761-8da8-42a2-a3f1-eae85ce4d5a8.jpg)

**Comment by DmytroMarkulych** [comment]
@AleferkoIurii в Summary вкажіть на фактичний результат. Таким чином, ми підкреслимо проблему

**Comment by KaterinaNimenko35** [comment]
The bug is not relevant - font requirements are outdated
