### ISSUE TITLE
20191019_roshen/ Point name wrong language

### ISSUE THREAD

**Issue by AleferkoIurii** [scholokov/long-travel-2#1316]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20191019_roshen/
2. Look at point name "Киев, Украина"

**Actual result:**
Text "Киев, Украина" (rus)

**Expected result:**
Text "Київ, Україна" (ukr)

**Environment:**
Desktop/ Windows 11 Home 21H2(22000.675)/ 1440x900/ Chrome 105.0.5195.127 (Official Build) (64-bit)
![kyiv](https://user-images.githubusercontent.com/104926198/191546235-db3fd655-206e-4902-b92d-a3f69986acbe.jpg)

**Comment by DmytroMarkulych** [comment]
@AleferkoIurii

1. Давайте додамо деталей дотримуючись правила Де? Що? Коли? в Summary. Не використовуючи слова типу incorrect, not correct і т.д. Вони є загальними та не дають конкретики в суть проблеми
2. Давайте додамо номери кроків  в STR
