### ISSUE TITLE
20091026_1102_Toronto/ ND Block CN Tower. The photo gallery tape doesn't meet the requirements

### ISSUE THREAD

**Issue by IrinK1** [scholokov/long-travel-2#1318]
Steps to reproduce:

1. Open https://test.long-travel.live/20091026_1102_Toronto/
2. Scroll down the page to the CN Tower block.
3. Pay attention to the photo gallery at CN Tower block.

Actual result:
The photo gallery type doesn't meet the requirements (Square Grid)
Expectsd result:
The photo gallery type should be Justified Grid.

Environment:
Windows 10 Pro (x64),
Google Chrome v.104.0.5112.102 (x64)
![Screenshot_3](https://user-images.githubusercontent.com/94845943/191718250-6f27a9b2-3a8a-47f7-ae33-0a76bc54d923.png)
![Screenshot_23](https://user-images.githubusercontent.com/94845943/191718287-e651f8fd-334e-4e0f-b7c5-78ebf79e1c2e.png)

**Comment by IrinK1** [comment]
@DmytroMarkulych

**Comment by scholokov** [comment]
please retest

**Comment by IrinK1** [comment]
> please retest

після ретесту через dev tools фотогалерея відповідає новим вимогам
![Screenshot_5](https://user-images.githubusercontent.com/94845943/196447591-893b53ba-3182-435d-9f3d-aa44dcd3ad85.png)
але тоді тут https://github.com/scholokov/long-travel-2/wiki/2.5-Travel.FotoGallery  в пункті 2.3 є невідповідність, так як там все ж вказано Justified Grid

**Comment by DmytroMarkulych** [comment]
@IrinK1 якщо проблему пофіксили, то можете закривати

**Comment by scholokov** [comment]
це просто Justified Grid так відображається у коді. Square Grid інакше
тут ми нічого не можемо зробити
