### ISSUE TITLE
20091026_1102_Toronto/ ND CN Tower missing preview photo

### ISSUE THREAD

**Issue by IrinK1** [scholokov/long-travel-2#1320]
Steps to reproduce:

1. Open https://test.long-travel.live/20091026_1102_Toronto/
2. Scroll down the page to the CN Tower block.
3. Pay attentionCN Tower block.

Actual result:
Preview photo is missing at CN Tower block
Expected result:
Preview photo is included CN Tower block

Environment:
Windows 10 Pro (x64),
Google Chrome v.104.0.5112.102 (x64)
![Screenshot_1](https://user-images.githubusercontent.com/94845943/191724817-550d91d7-2488-4b4a-868d-fcb8f42d6d41.png)
![Screenshot_20 (2)](https://user-images.githubusercontent.com/94845943/191724938-af48025e-6e19-4f32-bf36-777c76e1d303.png)

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
Verified

**Comment by IrinK1** [comment]
bug is reproduced
![Screenshot_4](https://user-images.githubusercontent.com/94845943/201662656-869f1f17-9bb8-4360-8e86-965fe8f7e516.png)

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
verified
