### ISSUE TITLE
20091026_1102_Toronto/ ND Block Pumpkin parade missing preview photo.

### ISSUE THREAD

**Issue by IrinK1** [scholokov/long-travel-2#1321]
Steps to reproduce:

1. Open https://test.long-travel.live/20091026_1102_Toronto/
2. Scroll down the page to the Pumpkin parade block.
3. Pay attention Pumpkin parade block.

Actual result:
Preview photo is missing at Pumpkin parade block.
Expected result:
Preview photo is included at Pumpkin parade block.

Environment:
Windows 10 Pro (x64),
Google Chrome v.104.0.5112.102 (x64)
![Screenshot_4](https://user-images.githubusercontent.com/94845943/191725654-7f46b7e2-878d-4375-8b9d-6ef8a8498a89.png)
![Screenshot_20 (2)](https://user-images.githubusercontent.com/94845943/191725683-3e0fb192-d89e-45b6-9f0c-4c7a9b1d2bce.png)

**Comment by IrinK1** [comment]
@DmytroMarkulych

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
Verified

**Comment by IrinK1** [comment]
bug is reproduced
![Screenshot_5](https://user-images.githubusercontent.com/94845943/201662803-9bfd7396-3032-4d9c-a588-0bcfa5e0a244.png)

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
verified
