### ISSUE TITLE
Design. Absence hover hotel link.

### ISSUE THREAD

**Issue by AleferkoIurii** [scholokov/long-travel-2#1346]
STR:

1. Open design page in Figma (https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986%3A6)
2. Look at field "Стандартні блоки", at block "Hotel"

Actual result:
Absence design hover hotel link 

Expected result:
Present  design hover hotel link 
![withouthoberhot](https://user-images.githubusercontent.com/104926198/191987612-c7424704-6762-4660-badb-ab3cc6842e75.jpg)

**Comment by scholokov** [comment]
design
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1765%3A37

**Comment by KaterinaNimenko35** [comment]
Verified, an issue is not reproduced
