### ISSUE TITLE
20070722_0809_Crimea photo in Lightbox doesn't displayed after opening in Body 

### ISSUE THREAD

**Issue by Xalep4ik** [scholokov/long-travel-2#1361]
Steps to reproduce:
1.Open https://test.long-travel.live/20070722_0809_Crimea/
2.Scroll down to photo gallery
3.Click on random photo

Actual result:
Photo doesn't displayed in Lightbox 

Expected result:
Photo displayed in Lightbox 

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 105.0.5195.102 (64 bit)

[c5e0a977-1b81-4615-959c-2f712778a949.webm](https://user-images.githubusercontent.com/92167884/192241203-fc7210bc-2a8a-4abc-ab7d-3cce9f028a65.webm)

**Comment by scholokov** [comment]
fixed
