### ISSUE TITLE
20150530_Kiev_Aviation_Museum/ ND Photo remains on the main page after closing the lightbox.

### ISSUE THREAD

**Issue by IrinK1** [scholokov/long-travel-2#1366]
Steps to reproduce:
1. Open https://test.long-travel.live/20150530_kiev_aviation_museum/
2. Scroll down the page to the PhotoGallery.
3. Open LightBox 
4. Press button "Esc".

Actual result:
Photo remains on the main page after closing the lightbox.
Expected result:
Photo doesn't remain on the main page after closing the lightbox.

Environment:
Windows 10 Pro (x64),
Google Chrome v.105.0.5195.127 (x64)
![Screenshot_24](https://user-images.githubusercontent.com/94845943/192284421-a5621f25-0847-450a-b43d-a10aae6b734c.png)
![Screenshot_23](https://user-images.githubusercontent.com/94845943/192284448-331435af-f2b7-4c9d-91d0-5c723399648d.png)

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
verified
