### ISSUE TITLE
20150530_Kiev_Aviation_Museum/ ND. Global map. Missing preview photo of travel on the global map.

### ISSUE THREAD

**Issue by IrinK1** [scholokov/long-travel-2#1368]
Steps to reproduce:

1. Open https://test.long-travel.live/travels/
2. Search 20150530_Kiev_Aviation_Museum
3. Pay attention to the preview photo

Actual result:
Preview photo of travel is missing on the global map.
Expected result:
Preview photo of travel is included on the global map.

Environment:
Windows 10 Pro (x64),
Google Chrome v.105.0.5195.127 (x64)
![Screenshot_1](https://user-images.githubusercontent.com/94845943/192508461-1e3d9eee-10dd-4bf2-bb71-0515beefb94e.png)
![Screenshot_3](https://user-images.githubusercontent.com/94845943/192508469-24bfba51-2bff-4a57-bddd-13af10a4197f.png)

**Comment by IrinK1** [comment]
@DmytroMarkulych

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
verified
