### ISSUE TITLE
20150530_Kiev_Aviation_Museum/ ND. Global map. Missed element "link" of travel on the global map.

### ISSUE THREAD

**Issue by IrinK1** [scholokov/long-travel-2#1369]
Steps to reproduce:

1. Open https://test.long-travel.live/travels/
2. Search 20150530_Kiev_Aviation_Museum
3. Press the button to go to the detailed description of the trip.
4. Pay attention element "link" is missed

Actual result:
Element "link" of travel is missed on the global map.
Expected result:
Element "link" of travel is included on the global map.

Environment:
Windows 10 Pro (x64),
Google Chrome v.105.0.5195.127 (x64)
![Screenshot_2](https://user-images.githubusercontent.com/94845943/192509508-a9b47270-3cc7-4c4f-a87a-46f6729a534d.png)
![Screenshot_4](https://user-images.githubusercontent.com/94845943/192509518-4500eb44-b1bc-4779-bc71-9cf7e78787a6.png)

**Comment by IrinK1** [comment]
@DmytroMarkulych

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
verified
