### ISSUE TITLE
20151031_Haisyn_Uman Мова контенту не відповідає країні подорожі

### ISSUE THREAD

**Issue by RomanTaradai** [scholokov/long-travel-2#1376]
Кроки для відтворення:

1.Відкрити сторінку https://test.long-travel.live/20151031_Haisyn_Uman/
2.Зверніть увагу на мову контенту: назви міст, областей, доріг

Фактичний результат:
мова контенту російська

Очікуваний результат:
Назва міст, областей, країн має бути мовою країни де відбувається подорож

[Назва міст, областей, країн має бути мовою країни, до якої належить місто](https://github.com/scholokov/long-travel-2/wiki/2.3-Travel.Content)
Середовище:
Операційна система: Windows 10
Браузер: Google Chrome Версія 105.0.5195.127 (64 біт)
Розрішення екрану 1366х768
![Screenshot_19](https://user-images.githubusercontent.com/113344723/192606142-b1b15a70-281f-4a0c-98c0-1d9551d11fea.png)
![Screenshot_20](https://user-images.githubusercontent.com/113344723/192606174-c63a0c1c-0995-4937-a007-254e0bb61c7d.png)
![Screenshot_12](https://user-images.githubusercontent.com/113344723/192609745-2be898f3-e9a7-4d03-93fc-ea1ab8062027.png)

**Comment by DmytroMarkulych** [comment]
@RomanTaradai посилання на специфікацію винесіть як окремим пунктом, а очікуваний результат сформулюйте та напишіть текстом

**Comment by scholokov** [comment]
fixed

**Comment by RomanTaradai** [comment]
> fixed

помилка відтворюється
![Screenshot_24](https://user-images.githubusercontent.com/113344723/192847167-d3c814e8-7256-45a8-a558-052aae65f5a2.png)

**Comment by scholokov** [comment]
але описана проблема не та проблема, яка була вище. тобто це новий баг...

**Comment by RomanTaradai** [comment]
> але описана проблема не та проблема, яка була вище. тобто це новий баг...

дякую
дану помилку виправлено
