### ISSUE TITLE
20151031_Haisyn_Uman розмір заголовка

### ISSUE THREAD

**Issue by RomanTaradai** [scholokov/long-travel-2#1377]
Кроки для відтворення:
1. відкрити  https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1201%3A27
2. .Відкрити сторінку https://test.long-travel.live/20151031_Haisyn_Uman/
3. відкрити DevTools
4. звернути увагу на розмір заголовку
 
Фактичний результат:
946,8х79,96

Очікуваний результат
1280х80

Середовище:
Операційна система: Windows 10
Браузер: Google Chrome Версія 105.0.5195.127 (64 біт)
Розрішення екрану 1366х768
![Screenshot_25](https://user-images.githubusercontent.com/113344723/193628511-9915516c-5e4d-497a-909f-7e796d4a2594.png)
![Screenshot_26](https://user-images.githubusercontent.com/113344723/193628533-c6b75170-42b7-4709-82ef-92316f68e649.png)

**Comment by DmytroMarkulych** [comment]
@RomanTaradai Зверніть увагу на те, що дані вимоги застаріли

**Comment by RomanTaradai** [comment]
> @RomanTaradai Зверніть увагу на те, що дані вимоги застаріли

Вибачаюсь, не підкажите де можна переглянути нові вимоги?

**Comment by DmytroMarkulych** [comment]
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986%3A6 
@RomanTaradai вибачаюся що дового відповідав

**Comment by DmytroMarkulych** [comment]
@RomanTaradai а давайте  Devtools вирівняємо по низу екрану і ще раз перевіримо розмір блоку

**Comment by RomanTaradai** [comment]
> @RomanTaradai а давайте Devtools вирівняємо по низу екрану і ще раз перевіримо розмір блоку

а так все вірно)
