### ISSUE TITLE
20150530_Kiev_Aviation_Museum/ ND Type of photo gallery of travel is Square grid. 

### ISSUE THREAD

**Issue by IrinK1** [scholokov/long-travel-2#1379]
Steps to reproduce:
1. Open https://test.long-travel.live/20150530_kiev_aviation_museum/
2. Scroll down the page to the photo gallery
3. Pay attention to the type of photo gallery

Actual result:
Type of photo gallery is Square Grid
Expected result:
Type of photo gallery is Justified Grid

Environment:
Windows 10 Pro (x64),
Google Chrome v.105.0.5195.127 (x64)
![Screenshot_7](https://user-images.githubusercontent.com/94845943/192761674-bf3ff43a-a1fb-4e80-a736-680b07da83f0.png)
![Screenshot_8](https://user-images.githubusercontent.com/94845943/192761695-2deaadf1-1aa0-490d-b79a-db5bca73cddc.png)

**Comment by IrinK1** [comment]
@DmytroMarkulych

**Comment by DmytroMarkulych** [comment]
@IrinK1 В Summary краще напишіть фактично який тип фотогалереї є насправді, замінивши фразу "не відповідає вимогам"

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
defect is reproduced
![Screenshot_13](https://user-images.githubusercontent.com/94845943/194308507-09032554-27d7-4754-8431-7521042c2813.png)

**Comment by scholokov** [comment]
please retest according to updated requarements:
https://github.com/scholokov/long-travel-2/wiki/2.5-Travel.FotoGallery

**Comment by IrinK1** [comment]
ретест проведений, тип фотогалереї відповідає оновленим вимогам

> please retest according to updated requarements: https://github.com/scholokov/long-travel-2/wiki/2.5-Travel.FotoGallery
