### ISSUE TITLE
20140913_Kiev_Spivoche_Pole_in the blok map legend, the name of the citycity "Київ" written in Ukrainian_#1388

### ISSUE THREAD

**Issue by Vshapko** [scholokov/long-travel-2#1388]
Steps to reproduce:
1.Open page https://test.long-travel.live/20140913_Kiev_Spivoche_Pole/
2. scroll down to the maps
3. pay attention to the legend in the maps

Actual result:
the name of the citycity "Київ" written in Ukrainian. Country "Ukraine"written in English

Expected result:
the name of the  citycity "Kyiv", Country "Ukraine" written in English

![image](https://user-images.githubusercontent.com/108400151/193235328-9ceb5912-1f4e-4c3a-b6b8-d5441e0e8dbd.png)

![image](https://user-images.githubusercontent.com/108400151/193234972-505cd983-af4c-490f-b6a2-f0e4499ccede.png)

Environment:
Operating system: Lenovo/Windows 10 Pro 21H1
Browser: google chrome 103.0.5060.114 (64bit)
Screen resolution: 1920 x 1080

**Comment by DmytroMarkulych** [comment]
@Vshapko в загальному добре, але давайте зробимо більш лаконічне summary.
Де? - в блоці леганда карти Що? - назва міста Київ написана українською 

І давайте звернемо увагу на специфікацію https://github.com/scholokov/long-travel-2/wiki/2.3-Travel.Content пункт 1.3

**Comment by Vshapko** [comment]
@DmytroMarkulych 
**Де? - в блоці леганда карти Що? - назва міста Київ написана українською** - Дякую, виправила

**І давайте звернемо увагу на специфікацію https://github.com/scholokov/long-travel-2/wiki/2.3-Travel.Content пункт 1.3**
що до специфікації маю питання:
Trevel. Content пункт 1.3 стосується контенту. 
Перевіряющи легенду, я користувалася п. 2,6 Travel map,п.2 Легенда
В ньому місце подорожі - Українською, місто та країна  - Англійською. 
Тому прошу зорієтнувати мене, яким пунктом керуватися.
Дякую
![image](https://user-images.githubusercontent.com/108400151/193263316-908226e1-a776-44c1-a0c2-be2f1b6977f9.png)

**Comment by DmytroMarkulych** [comment]
@Vshapko щодо мови, варто орієнтуватися на даний пункт https://github.com/scholokov/long-travel-2/wiki/1.2-Global.Language
