### ISSUE TITLE
20140616_0707_Greece/ ND - Body - The flag of another country is specified

### ISSUE THREAD

**Issue by olgaatanasova93** [scholokov/long-travel-2#1393]
Steps to reproduce:

Open page https://test.long-travel.live/20140616_0707_Greece/
Pay attention to the Serbian flag. Change the flag of Ukraine to the flag of Serbia

Actual result:
The photo shows the flag of Ukraine

Expected result:
The photo shows the flag of Serbia

Environment:
Windows 10 Pro, Версия 103.0.5060.134 (Официальная сборка), (64 бит)

![photo_2022-09-30_21-58-57](https://user-images.githubusercontent.com/108815667/193338875-ea685688-e07e-4436-b7b0-9a8ee4f79eb3.jpg)

![photo_2022-09-30_22-06-35](https://user-images.githubusercontent.com/108815667/193339780-47aaaeee-f41f-4dd1-b5b0-942863ef8e72.jpg)

**Comment by scholokov** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
Verified, an issue is not reproduced
