### ISSUE TITLE
20140616_0707_Greece/ ND - No link to booking or hotel

### ISSUE THREAD

**Issue by olgaatanasova93** [scholokov/long-travel-2#1394]
Steps to reproduce:

Open page https://test.long-travel.live/20140616_0707_Greece/
Pay attention to near each hotel there should be a link to the Booking or hotel

Actual result:
No link to booking or hotel

Expected result:
There must be a link to the booking or hotel

Environment:
Windows 10 Pro, Версия 103.0.5060.134 (Официальная сборка), (64 бит)

![photo_2022-09-30_22-35-38](https://user-images.githubusercontent.com/108815667/193344039-44f88f78-3648-49d2-a2f0-53de9862bd3d.jpg)
![photo_2022-09-30_22-35-43](https://user-images.githubusercontent.com/108815667/193344043-0297c34e-d610-4658-ac95-5296d42d3919.jpg)
![photo_2022-09-30_22-35-45](https://user-images.githubusercontent.com/108815667/193344045-10f59dc6-9cae-48af-bf0f-58aaf6f0d09d.jpg)
![photo_2022-09-30_22-35-47](https://user-images.githubusercontent.com/108815667/193344046-bbddc3c9-2eab-4620-a14b-b7fca6174805.jpg)
![photo_2022-09-30_22-35-49](https://user-images.githubusercontent.com/108815667/193344049-5b9035e6-b48c-4975-bca6-1ba6100c97b2.jpg)
![photo_2022-09-30_22-35-51](https://user-images.githubusercontent.com/108815667/193344050-12fe6eae-97bc-4ccc-b4a9-8b47e8c67868.jpg)
![photo_2022-09-30_22-35-53](https://user-images.githubusercontent.com/108815667/193344051-5307423b-3e8b-4b96-862c-2f52f1cc49ef.jpg)

**Comment by scholokov** [comment]
назва готеля сама по собі і являється лінкою
тобто вона не буде "рядом"
от тут на дизайні це видно:
![image](https://user-images.githubusercontent.com/22824947/194065996-cb904ec4-7cbe-46ff-9613-37b81fdec613.png)
буд ласка ще раз перевірте

**Comment by KaterinaNimenko35** [comment]
Verified, an issue is not reproduced
