### ISSUE TITLE
20061028_Bila_Tserkva - the font family for country travel is "Geneva"

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/long-travel-2#1396]
Steps to reproduce:
1. Open design in Figma https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986%3A7
2. Open page https://test.long-travel.live/20061028_Bila_Tserkva/
3. Pay attention to the font-family

Actual result: Geneva
Expected result: Poppins

Environment: Windows 11, Google Chrome - 105.0.5195.127 , (64 бит)

![chrome_zY5z9iJwMo](https://user-images.githubusercontent.com/57997443/193510854-51db29e8-ccd8-4776-851b-e18034e04b33.png)

![chrome_te5vjYFINp](https://user-images.githubusercontent.com/57997443/193510836-4d9679b4-e0f7-4d70-a26f-282420468d03.png)

**Comment by dmitryylev** [comment]
changed

**Comment by poroskundenys** [comment]
Для кириллицы нет шрифта Poppins. В фигме отображается Open Sans. https://qna.habr.com/q/909569. Для сайта установил базовым шрифтом Open Sans
