### ISSUE TITLE
20061028_Bila_Tserkva - in the travel point review, the flag's rendered size is 16x11px

### ISSUE THREAD

**Issue by dmitryylev** [scholokov/long-travel-2#1400]
Steps to reproduce:
1. Open design in Figma https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986%3A7
2. Open page https://test.long-travel.live/20061028_Bila_Tserkva/
3. Pay attention to the **size of the flag** in the travel point review

Actual result: 16x11 px
Expected result: 26x18 px

Environment: Windows 11, Google Chrome - 105.0.5195.127 , (64 бит)

![chrome_igJvSucYIp](https://user-images.githubusercontent.com/57997443/193533337-6cd0d13c-39e3-4280-8e75-380aca25bd04.png)
![chrome_7j2Wl4aJEb](https://user-images.githubusercontent.com/57997443/193533359-231fa88b-32f8-4953-bc3b-65a41379b2b7.png)

**Comment by DmytroMarkulych** [comment]
@dmitryylev при написанні summary по факту ми пишемо най фактичний результат, тобто вказуємо що у нас є така і така проблеми, ми не вказуємо, що нам потрібно зробити(це вказується в фактичного). Ми маємо констатувати проблему

**Comment by scholokov** [comment]
fixed

**Comment by dmitryylev** [comment]
verified
