### ISSUE TITLE
20151031_Haisyn_Uman в заголовку вид шрифту Geneva

### ISSUE THREAD

**Issue by RomanTaradai** [scholokov/long-travel-2#1411]
Кроки для відтворення:

1.Відкрити сторінку https://test.long-travel.live/20151031_Haisyn_Uman/
2. відкрити DevTools
3. звернути увагу на шрифт заголовку

Фактичний результат:
 вид шрифту Geneva

Очікуваний результат
 вид шрифту  Poppins
Додаткова інформація https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1201%3A27

Середовище:
Операційна система: Windows 10
Браузер: Google Chrome Версія 105.0.5195.127 (64 біт)
Розрішення екрану 1366х768
![Screenshot_30](https://user-images.githubusercontent.com/113344723/193633510-af46566b-0910-42e1-aaf1-770ab5610ad9.png)
![Screenshot_31](https://user-images.githubusercontent.com/113344723/193633536-0d18d7de-8fcc-4a9a-8c79-e417053ff057.png)

**Comment by DmytroMarkulych** [comment]
@RomanTaradai при оформлені summary дотримуйтеся принципу Де? Що? Коли? 
- посилання на дизайн краще виносити як додаткова інформація. А не включати в кроки для відтворення

**Comment by DmytroMarkulych** [comment]
@RomanTaradai Давайте першим пунктом в кроках зробимо Відкрити сторінку https://test.long-travel.live/...
а посилання на дизайн зробимо наступним чином. Після Очікуваного результату додамо пункт Додаткова інформація і там розмістимо лінк на дизайн

**Comment by RomanTaradai** [comment]
> @RomanTaradai Давайте першим пунктом в кроках зробимо Відкрити сторінку https://test.long-travel.live/... а посилання на дизайн зробимо наступним чином. Після Очікуваного результату додамо пункт Додаткова інформація і там розмістимо лінк на дизайн

Виправив

**Comment by scholokov** [comment]
please retest

**Comment by DmitriiNasonov** [comment]
bug-report isn't actual
