### ISSUE TITLE
20141102_10_Egypt_Hurghada doesn't displaying full-size photo in LightBox after opening preview in Body

### ISSUE THREAD

**Issue by Xalep4ik** [scholokov/long-travel-2#1416]
**STR:**
1.Open https://test.long-travel.live/20141102_10_Egypt_Hurghada/
2.Scroll down to photo gallery
3.Click on random picture

**Actual result:**
Photo doesn't displayed in LightBox, there is taxt : The image could not be loaded  

**Expected result:**
Full-size photo displayed in LightBox

**Environment:**
Operating system: Windows 10 Pro
Browser: Google Chrome 105.0.5195.127 (64 bit)

![img_bug](https://user-images.githubusercontent.com/92167884/194013827-05160d55-f48d-41e5-b455-17551a65364d.jpg)

Video:

[Hurgada-–-Long-Travel_4.webm](https://user-images.githubusercontent.com/92167884/194014173-e3a15e14-c31b-4d0a-9b04-622f9c13602d.webm)

**Comment by scholokov** [comment]
fixed
