### ISSUE TITLE
Requirements. It does not have information about the language to be used on the map and in the footer for each individual trip.

### ISSUE THREAD

**Issue by IrinK1** [scholokov/long-travel-2#1418]
Steps to reproduce:
1. Open https://github.com/scholokov/long-travel-2/wiki/2.3-Travel.Content
2. Search item - 1.3
3. Pay attention that It does not have information about the language to be used on the map and in the footer for each individual trip.

Actual result:
It does not have information about the language to be used on the map and in the footer for each individual trip.
Expected result:
Information about the language to be used on the map and in the footer for each individual trip should be present.
![Screenshot_12](https://user-images.githubusercontent.com/94845943/194044418-09a43719-11d8-4ff2-8a0a-073c3141c621.png)

**Comment by scholokov** [comment]
fixed
https://github.com/scholokov/long-travel-2/wiki/1.2-Global.Language
