### ISSUE TITLE
20151031_Haisyn_Uman/ текст блоків подорожі темного кольору

### ISSUE THREAD

**Issue by RomanTaradai** [scholokov/long-travel-2#1426]
Кроки для відтворення:

1.Відкрити сторінку https://test.long-travel.live/20151031_Haisyn_Uman/
2.Зверніть увагу на колір тексту в блоках подорожі

Фактичний результат:
колір тексту #101010
Очікуваний результат:
колір тексту #FFFFF
додаткова інфо https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1201%3A27
Середовище:
Операційна система: Windows 10
Браузер: GoogleChrome Версія 105.0.5195.127 (64 біт)
Розрішення екрану 1366х768
![Screenshot_10](https://user-images.githubusercontent.com/113344723/194398765-bdfbe97e-eb79-4ce8-abb6-59b50b2f2d9e.png)
![Screenshot_9](https://user-images.githubusercontent.com/113344723/194398827-dfa0417a-5ee8-4b39-8ca7-fd391d026c07.png)

**Comment by scholokov** [comment]
fixed

**Comment by RomanTaradai** [comment]
> fixed

помилку виправлено
