### ISSUE TITLE
20151031_Haisyn_Uman/ блоки подорожі не відповідають дизайну

### ISSUE THREAD

**Issue by RomanTaradai** [scholokov/long-travel-2#1427]
Кроки для відтворення:

1.Відкрити сторінку https://test.long-travel.live/20151031_Haisyn_Uman/
2.Зверніть увагу на дизайн блоків
Фактичний результат:
не відповідає дизайну - відсутній попередній перегляд блоку (фон блоку), прапор

Очікуваний результат:
дизайн відповідає figma
додаткова інформація https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986%3A6
Середовище:
Операційна система: Windows 10
Браузер: Google Chrome Версія 105.0.5195.127 (64 біт)
Розрішення екрану 1366х768
![Screenshot_11](https://user-images.githubusercontent.com/113344723/194400252-b3a795c6-4e76-4d48-be24-32913017e538.png)
![Screenshot_12](https://user-images.githubusercontent.com/113344723/194400276-e0629ac4-e5d0-4d68-8a2d-a97087f56761.png)

**Comment by RomanTaradai** [comment]
> fixed

помилка відтворюється

в блоці відсутнє фонове зображення та прапор країни
![Screenshot_35](https://user-images.githubusercontent.com/113344723/195669324-9bb5e571-22e6-4a84-bfc6-27a8a98fb9ce.png)

**Comment by scholokov** [comment]
fixed

**Comment by RomanTaradai** [comment]
> fixed

помилка відтворюється
![Screenshot_39](https://user-images.githubusercontent.com/113344723/197348049-1349063b-7c2f-4c82-a05d-d5794378b146.png)
![Screenshot_40](https://user-images.githubusercontent.com/113344723/197348052-dd5ca660-5072-4a3a-8016-2ae5f53ce57a.png)

**Comment by scholokov** [comment]
fixed

**Comment by RomanTaradai** [comment]
> fixed

помилка відтворюється
відсутній прапор
![Screenshot_49](https://user-images.githubusercontent.com/113344723/198689850-7a63e1b8-64a1-4dab-b447-fe7d20868bb1.png)
![Screenshot_48](https://user-images.githubusercontent.com/113344723/198689866-850a625d-dd04-4678-8f84-0af98d510cb4.png)

**Comment by scholokov** [comment]
fixed

**Comment by RomanTaradai** [comment]
> fixed

виправлено
