### ISSUE TITLE
20180721_cherkassy. Homepage. Preview travel "Черкассы". Incorrect travel date

### ISSUE THREAD

**Issue by yuriiboikokiev** [scholokov/long-travel-2#143]
**Steps:**
1.Open homepage.
2.Scroll to the preview travel "Черкассы".
3.Attention to the travel date

**Actual result :**
Travel date - Sep 1, 2021 

**Screenshot:**
https://skr.sh/sA3DXXNsj37?a

**Expected result:**
Travel date-  July 21, 2018 ( according to the requirements).
[https://github.com/scholokov/long-travel-2/wiki/Travels]

**Additional Information:**
-Operating System: Windows 10, x64.
-Browser : Google Chrome 93.0.4577.63 (Official build), (64 bit).

**Comment by scholokov** [comment]
fixed

**Comment by yuriiboikokiev** [comment]
issue is not present
