### ISSUE TITLE
20070722_0809_crimea - Travels - Global map with routes - Detailed travels list - Travel is duplicated

### ISSUE THREAD

**Issue by KaterinaNimenko35** [scholokov/long-travel-2#1431]
**Steps to reproduce:**

1. Open page https://test.long-travel.live/travels/
2. Scroll down the detailed travel list, find a travel 20070722_0809_crimea
3. Scroll down the detailed travel list
4. Pay attention, in the detailed list of travel there is another travel with ID 20070722_0809_crimea

**Actual result:**
Travel is **duplicated**

**Expected result:**
Travel is **not duplicated**

**Environment:**
Desktop/W10/Google Chrome 101.0.4951.67 (64-bit)

![2022-10-09 14 23 20](https://user-images.githubusercontent.com/105543094/194756405-be2ff218-46b7-4185-97dc-b50dbf25bc53.png)

![2022-10-09 14 24 06](https://user-images.githubusercontent.com/105543094/194756411-6323ad96-a33a-4b20-b9ff-fffe1e0e5f86.png)

**Comment by DmytroMarkulych** [comment]
@KaterinaNimenko35 в STR у Вас аж 3 pay attention to.. бажано щоб він був один

**Comment by KaterinaNimenko35** [comment]
@DmytroMarkulych  "Steps to reproduce" виправила. 
 Подорожі мають однаковий ID **20070722_0809_crimea** та однакові місця відвідування, схиляюся до думки що це все ж таки дублікат


![2022-10-18 10 24 59](https://user-images.githubusercontent.com/105543094/196380618-ed4b98da-29d2-4d8e-8a98-9e69adadf241.png)
![2022-10-18 10 39 05](https://user-images.githubusercontent.com/105543094/196380634-2494d8a0-d348-46c3-bd46-5aa32a92d09b.png)

**Comment by DmytroMarkulych** [comment]
@KaterinaNimenko35 тоді можливо це дефект в одинакових ID подорожей?) Як ви гадаєте?)

**Comment by scholokov** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
Verified, an issue is not reproduced
