### ISSUE TITLE
20160618_Mezhigorie/ ND An extra block with information about the city and the date between header and map.

### ISSUE THREAD

**Issue by IrinK1** [scholokov/long-travel-2#1448]
Steps to reproduce:
1. Open https://test.long-travel.live/20160618_Mezhigorie/
2. Pay attention to the block between header and map.

Actual result:
An extra block with information about the city and the date between header and map is included.
Expected result:
An extra block with information about the city and the date between header and map is missed.

Environment:
Windows 10 Pro (x64),
Google Chrome v.106.0.5249.91 (x64)
![Screenshot_16](https://user-images.githubusercontent.com/94845943/195133185-24dea5e1-2801-432a-a52a-3623bbcac50f.png)
![Screenshot_17](https://user-images.githubusercontent.com/94845943/195133197-cebc16e4-bff3-4329-937f-d8db8d76a564.png)

**Comment by IrinK1** [comment]
@DmytroMarkulych

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
verified
