### ISSUE TITLE
20160618_Mezhigorie/ ND The location of the country's flag on the right side of the header doesn't match the Figma design

### ISSUE THREAD

**Issue by IrinK1** [scholokov/long-travel-2#1451]
Steps to reproduce:
1. Open https://test.long-travel.live/20160618_Mezhigorie/
2. Pay attention to the flag of country in the right side of the header.

Actual result:
Location of the country's flag on the right side of the header doesn't match the Figma design.
Expected result:
Location of the country's flag on the right side of the header should match the Figma design.
![Screenshot_20](https://user-images.githubusercontent.com/94845943/195139431-01a00b7c-a51c-4e08-8ca4-b54916c3bb14.png)
![Screenshot_21](https://user-images.githubusercontent.com/94845943/195139443-10aff7c0-6433-462b-be72-94d14b7923fb.png)
![Screenshot_22](https://user-images.githubusercontent.com/94845943/195139448-ea4e3f94-934e-4756-bf69-1954b19c27a3.png)

**Comment by DmytroMarkulych** [comment]
@IrinK1 вийшов трішки загальний опис дефекту, давайте додамо конкретики

**Comment by IrinK1** [comment]
> @IrinK1 вийшов трішки загальний опис дефекту, давайте додамо конкретики

тут я не дуже зрозуміла чому він трішки загальний)

**Comment by DmytroMarkulych** [comment]
@IrinK1 краще замінити фразу "Не відповідає дизайну Figma" на більш конкретне
