### ISSUE TITLE
20160618_Mezhigorie/ ND The content's color at "Body" does not match the Figma design. 

### ISSUE THREAD

**Issue by IrinK1** [scholokov/long-travel-2#1453]
Steps to reproduce:
1. Open https://test.long-travel.live/20160618_Mezhigorie/
2. Scroll the page down to the text description of the travel.
3. Pay attention to the color of the text description.

Actual result:
The content's color at body is dark #101010;
Expected result:
The content's color at body is white #FFFFFF.

Environment:
Windows 10 Pro (x64),
Google Chrome v.106.0.5249.91 (x64)
![Screenshot_23](https://user-images.githubusercontent.com/94845943/195147062-eb28ffd5-7ad3-4c5d-baa2-6ff74bfe7513.png)
![Screenshot_1](https://user-images.githubusercontent.com/94845943/195330836-ee624b9b-16f4-463c-90ae-370b49743f2a.png)
![Screenshot_2](https://user-images.githubusercontent.com/94845943/195330867-f4c5ba93-1af9-4304-a419-1322cf660a57.png)

**Comment by IrinK1** [comment]
@DmytroMarkulych

**Comment by DmytroMarkulych** [comment]
@IrinK1 давате додамо більше конкретики в Summary та Actual and Expected Results

**Comment by scholokov** [comment]
please retest

**Comment by IrinK1** [comment]
@scholokov defect is reproduced
![Screenshot_4](https://user-images.githubusercontent.com/94845943/196182630-ec7dcff7-be4f-433a-934c-b5274cfe017a.png)

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
verified
