### ISSUE TITLE
20160618_Mezhigorie/ ND Missing structural block "Preview" at Body

### ISSUE THREAD

**Issue by IrinK1** [scholokov/long-travel-2#1455]
Steps to reproduce:
1. Open https://test.long-travel.live/20160618_Mezhigorie/
2. Scroll down thw page to the "Body"
3. Pay attention missing structural block "preview" at "Body"

Actual result:
Structural block "Preview" is missed at "Body"
Expected result:
Structural block "Preview" is included at "Body"

Environment:
Windows 10 Pro (x64),
Google Chrome v.106.0.5249.91 (x64)
![Screenshot_25](https://user-images.githubusercontent.com/94845943/195149311-d2acc458-d1b7-4e1d-99cc-33c35bf1635b.png)
![Screenshot_26](https://user-images.githubusercontent.com/94845943/195149324-98cf36cd-f95c-4155-a873-d0d0fbdf9ded.png)
![Screenshot_27](https://user-images.githubusercontent.com/94845943/195149334-9764b4c1-d567-400d-ac1f-1c20be7d6f22.png)

**Comment by IrinK1** [comment]
@DmytroMarkulych

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
verified
