### ISSUE TITLE
20160618_Mezhigorie/ ND Global map. An extra symbol at the name of the travel

### ISSUE THREAD

**Issue by IrinK1** [scholokov/long-travel-2#1456]
Steps to reproduce:
1. Open https://test.long-travel.live/travels/
2. Search 20160618_Mezhigorie
3. Pay attention to te extra symbol at the name of the travel

Actual result:
An extra symbol at the name of the travel is included.
Expected result:
An extra symbol at the name of the travel is missed.

Environment:
Windows 10 Pro (x64),
Google Chrome v.106.0.5249.91 (x64)
![Screenshot_28](https://user-images.githubusercontent.com/94845943/195152829-f2d01854-b8c4-49e7-adbd-13989b073ea3.png)
![Screenshot_29](https://user-images.githubusercontent.com/94845943/195152834-140b94b6-5a87-4f2c-a074-1d5682dd06a7.png)

**Comment by IrinK1** [comment]
@DmytroMarkulych

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
verified
