### ISSUE TITLE
20160618_Mezhigorie/ ND Global map. Missing preview photo of the travel

### ISSUE THREAD

**Issue by IrinK1** [scholokov/long-travel-2#1458]
Steps to reproduce:
1. Open https://test.long-travel.live/travels/
2. Search 20160618_Mezhigorie 
3. Pay attention preview photo of the travel is missed.

Actual result:
Preview photo of the travel is missed.
Expected result:
Preview photo of the travel is included.

Environment:
Windows 10 Pro (x64),
Google Chrome v.106.0.5249.91 (x64)
![Screenshot_30](https://user-images.githubusercontent.com/94845943/195154826-5d7f3d78-6acb-4de8-b1c4-ad1b8aa9354e.png)
![Screenshot_31](https://user-images.githubusercontent.com/94845943/195154832-86a79352-a32c-4460-9e15-f3c086f0faec.png)

**Comment by IrinK1** [comment]
@DmytroMarkulych

**Comment by scholokov** [comment]
fixed

**Comment by IrinK1** [comment]
Verified
