### ISSUE TITLE
20180721_cherkassy. "Черкассы". Incorrect number of photos

### ISSUE THREAD

**Issue by yuriiboikokiev** [scholokov/long-travel-2#146]
**Steps**
1.Open page 20180721_cherkassy/
2.Scroll to the block "Черкассы".
3.Attention to the number of photos.

**Actual result :**
Number of photos - 37 

**Screenshot:**
https://skr.sh/sA4ojfInSt2?a

**Expected result:**
Number of photos - 62  ( according to the requirements).
The quantity should be the same as on the old version of the site.
[https://legacy.long-travel.live/blog.php?article=20180721_Cherkassy]

**Additional Information:**
-Operating System: Windows 10, x64.
-Browser : Google Chrome 93.0.4577.63 (Official build), (64 bit).

**Comment by scholokov** [comment]
it is ok in this case.

**Comment by yuriiboikokiev** [comment]
issue is not present
