### ISSUE TITLE
20180721_cherkassy. "Дорога: Киев – Черкассы". Video. Incorrect video 

### ISSUE THREAD

**Issue by yuriiboikokiev** [scholokov/long-travel-2#148]
**Steps**
1.Open page 20180721_cherkassy/.
2.Scroll to the block "Дорога: Киев – Черкассы".
3.Attention to  the video.

**Actual result :**
Videos with incorrect content. Doesn't fit the trip.
Video title - "Kiev - Boguslav".

**Screenshot:**
https://skr.sh/sA6bFA8aulf?a

**Expected result:**
Videos with correct content. Consistent with the trip.
Video title - "Kiev - Cherkassy".

**Additional Information:**
-Operating System: Windows 10, x64.
-Browser : Google Chrome 93.0.4577.63 (Official build), (64 bit).

**Comment by scholokov** [comment]
fixed

**Comment by yuriiboikokiev** [comment]
issue is not present
