### ISSUE TITLE
20180721_cherkassy. "Черкассы". Incorrect text level in the block name

### ISSUE THREAD

**Issue by yuriiboikokiev** [scholokov/long-travel-2#149]
**Steps**
1.Open page 20180721_cherkassy/.
2.Scroll to the block "Черкассы".
3.Attention to the level of text in the name.

**Actual result :**
Text level - h1.

**Screenshot:**
https://skr.sh/sA6LkATk4CL?a

**Expected result:**
Text level - h2 ( according to the requirements).
[https://github.com/scholokov/long-travel-2/wiki/Travels]

**Additional Information:**
-Operating System: Windows 10, x64.
-Browser : Google Chrome 93.0.4577.63 (Official build), (64 bit).

**Comment by scholokov** [comment]
fixed

**Comment by yuriiboikokiev** [comment]
issue is not present
