### ISSUE TITLE
20180721_cherkassy. "Дорога : ЧЕРКАССЫ - КИЕВ ". Incorrect date in the block

### ISSUE THREAD

**Issue by yuriiboikokiev** [scholokov/long-travel-2#150]
**Steps:**
1.Open page 20180721_cherkassy.
2.Scrol to the "Дорога: Черкассы - Киев".
3.Attention to the the travel date
.
**Actual result :**
Travel date - 08.07.2018.

**Screenshot:**
https://skr.sh/sA6594dUaA9?a

**Expected result:**
Travel date - 21.07.2018 ( according to the requirements).
[https://github.com/scholokov/long-travel-2/wiki/Travels]

**Additional Information:**
-Operating System: Windows 10, x64.
-Browser : Google Chrome 93.0.4577.63 (Official build), (64 bit).

**Comment by scholokov** [comment]
duplicate

**Comment by yuriiboikokiev** [comment]
> duplicate

added information, bug not fixed

**Comment by scholokov** [comment]
fixed
