### ISSUE TITLE
20170115_Kiev_Zoo_12_Month _ Назва подорожі в детальному блоці відрізняється від назви подорожі на сторінці Travels

### ISSUE THREAD

**Issue by Serhii-Ishchuk** [scholokov/long-travel-2#1507]
**Steps to reproduce:**

1. Відкрити сторінку https://test.long-travel.live/travels/
2. В детальному блоці подорожей, знайти дану подорож
3. Звернути увагу на назву подорожі

**Actual result:**
Назва подорожі "Kiev_Zoo_12_Month"

**Expected result:**
Назва подорожі "Зоопарк XII Месяцев"

**Environment:**
Операційна система: Windows 10 Pro
Браузер: Google Chrome Версія 107.0.5304.18 (64 біт)
Розрішення екрану 1366х768

![Screenshot_2](https://user-images.githubusercontent.com/114660385/197182493-fef8ae88-ff81-4de9-a7ae-a452c17bf13a.png)

![Screenshot_4](https://user-images.githubusercontent.com/114660385/197182545-4c0c0580-7017-41e4-a6f5-75b9b22e28a6.png)
![Screenshot_1](https://user-images.githubusercontent.com/114660385/197182565-195e7c46-1b9b-4af2-9781-70ed42965872.png)

**Comment by scholokov** [comment]
fixed

**Comment by scholokov** [comment]
please retets
