### ISSUE TITLE
20170115_Kiev_Zoo_12_Month _ Назва подорожі у випадаючому списку подорожей з картами, відрізняється від назви подорожі на сторінці Travels

### ISSUE THREAD

**Issue by Serhii-Ishchuk** [scholokov/long-travel-2#1509]
**Steps to reproduce:**

1. Відкрити сторінку https://test.long-travel.live/travels/
2. Натиснути на випадаючий список подорожей з картами
3. Знайти дану подорож прокручуючи вниз список
4. Звернути увагу на назву подорожі

**Actual result:**
Назва подорожі "Kiev_Zoo_12_Month"

**Expected result:**
Назва подорожі "Зоопарк XII Месяцев"

**Environment:**
Операційна система: Windows 10 Pro
Браузер: Google Chrome Версія 107.0.5304.18 (64 біт)
Розрішення екрану 1366х768

![Screenshot_6](https://user-images.githubusercontent.com/114660385/197188002-3a3d45b2-7aca-4d9d-b860-8ca380816cf8.png)

![Screenshot_7](https://user-images.githubusercontent.com/114660385/197188149-655ed1c6-3818-4d28-abe9-8fbc9f1a0c84.png)
![Screenshot_1](https://user-images.githubusercontent.com/114660385/197188168-21e868c4-0a03-4ae8-9c7e-080e1bbd745c.png)

**Comment by Serhii-Ishchuk** [comment]
В нашому випадку замість транслітерації відбувся переклад на англійську мову тобто, назву подорожі "Зоопарк XII Месяцев" було переведено на англійську мову  "Kiev_Zoo_12_Month", а не проведено транслітерацію.

**Comment by DmytroMarkulych** [comment]
@Serhii-Ishchuk будь ласка не використовуйте слова типу "не виправлено", краще замініть на "Дефект відтворюється".

**Comment by Serhii-Ishchuk** [comment]
Зрозумів. Виправлено.

**Comment by scholokov** [comment]
please retest
