### ISSUE TITLE
20180721_cherkassy."Дорога: Черкассы - Киев". Video. Incorrect video

### ISSUE THREAD

**Issue by yuriiboikokiev** [scholokov/long-travel-2#151]
**Steps**
1.Open page 20180721_cherkassy/.
2.Scroll to the block "Дорога: Черкассы - Киев".
3.Attention to the video.

**Actual result :**
Videos with incorrect content. Doesn't fit the trip.
Video title - "Boguslav - Kiev".

**Screenshot:**
https://skr.sh/sA67auletZC?a

**Expected result:**
Videos with correct content. Consistent with the trip.
Video title - "Cherkassy - Kiev".

**Additional Information:**
-Operating System: Windows 10, x64.
-Browser : Google Chrome 93.0.4577.63 (Official build), (64 bit).

**Comment by scholokov** [comment]
duplicate

**Comment by yuriiboikokiev** [comment]
duplicate checked, bug fixed
