### ISSUE TITLE
20170709_Protsiv - Body -  Part of the photos have Photo Gallery type is "Square Grid"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#1524]
**Steps of reprodusing:**

1) Open https://test.long-travel.live/20170709_protsiv/
2) Scroll to Body

**Actual Result:**

FotoGallery type - "Square Grid"

**Expected Result:**

FotoGallery type - "Justified Grid"

**Environments:**

Windows 10, Chrome 106.0.5249.119 (64 bit)
Android 8.1.0, Crome 106.0.5249.126
![photo_2022-10-25_15-02-30](https://user-images.githubusercontent.com/95171672/197770058-61468d6a-e9e7-4a94-8ddf-d6bf97f9c03a.jpg)
![photo_2022-10-25_15-02-35](https://user-images.githubusercontent.com/95171672/197770062-165cdf71-6be3-4ab6-9648-0d397bd517d1.jpg)
![Процев,Киевская область, Украина – Long-Travel - Google Chrome 25 10 2022 14_55_59](https://user-images.githubusercontent.com/95171672/197770064-98efed5e-eeda-4e4c-9e40-5950b1335c59.png)

**Comment by scholokov** [comment]
please check that you use latest requarements

**Comment by DmitriiNasonov** [comment]
verified. Used latest requarements
![2 5 Travel FotoGallery · scholokov_long-travel-2 Wiki - Google Chrome 26 10 2022 15_08_00](https://user-images.githubusercontent.com/95171672/198022122-d032ceb9-bb8d-4365-be4e-dfdaeced1d91.png)

**Comment by DmytroMarkulych** [comment]
@DmitriiNasonov 
![image](https://user-images.githubusercontent.com/88647733/198135726-83ee8cc8-1765-45f9-a7f0-fdbef7217654.png)

**Comment by DmitriiNasonov** [comment]
bug-report is canceled
