### ISSUE TITLE
Create a document in which to indicate which names of trips, waypoints, and attractions will be used on the site

### ISSUE THREAD

**Issue by KaterinaNimenko35** [scholokov/long-travel-2#1528]
**Examples:**

![1](https://user-images.githubusercontent.com/105543094/198110822-970ef892-0539-455b-b0b4-48cf28ac4ceb.png)

![2](https://user-images.githubusercontent.com/105543094/198110918-9fd031db-0053-4851-b417-c9712b037a14.png)

![3](https://user-images.githubusercontent.com/105543094/198111013-0fbe6bde-a79a-41b3-9c90-070f831c382c.png)

![4](https://user-images.githubusercontent.com/105543094/198111203-d9fe2e09-3328-43ab-9730-c8807cf3d64c.png)

![5](https://user-images.githubusercontent.com/105543094/198111259-a530db95-924c-452f-b4e4-16d406549825.png)

![6](https://user-images.githubusercontent.com/105543094/198111284-5b7d0423-a31f-41eb-a933-3e8946c181e6.png)

**Comment by scholokov** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
Verified, issues found

![github com_scholokov_long-travel-2_wiki_4 2-Travels List](https://user-images.githubusercontent.com/105543094/201521609-563913bc-dc43-4292-94f7-4a1d1b68232b.png)


![github com_scholokov_long-travel-2_wiki_4 23-Travels List](https://user-images.githubusercontent.com/105543094/201521623-fe2ff37b-3078-48b1-8fd1-b3da2050d82c.png)


![2022-11-13 13 17 5778](https://user-images.githubusercontent.com/105543094/201521637-3a570207-8fdc-4a8f-b8b9-84bce37e43d2.png)

**Comment by scholokov** [comment]
fixed
