### ISSUE TITLE
20160814_24_Shadsk_header does not respond design requirements

### ISSUE THREAD

**Issue by tatarvit** [scholokov/long-travel-2#1532]
**Attachment**
Requirements to page,
https://github.com/scholokov/long-travel-2/wiki/2.-Travel.Structure
Figma (design)
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=0%3A1

**Steps to reproduce:**
1. Open the website https://www.long-travel.live/20160814_24_shadsk/

**Actual result**
The header doesn't respond to the design requirements
The image, name of the trip, and data are different elements.

**Expected result**
The header responds to the design requirements. 
The image, name of the trip, and data have to be one block.

![header_shadsk](https://user-images.githubusercontent.com/111632610/198364745-ccb9f3ba-2028-48bc-a87a-599af1a22072.png)

**Environment**
Operating system: Windows 10
Browser: Google Chrome Version 106.0.5249.119 (64-bit)

**Comment by DmytroMarkulych** [comment]
@tatarvit Вийшов дуже загальний баг репорт, додайте будь ласка деталей в нього

**Comment by tatarvit** [comment]
Я роблю свій перший баг репорт на проекті. Підскажи,як краше і зручніше для розробника вказати додаткові деталі. Я зробив скрін з фігми, як повинен виглядати header. Додаю вимоги.

Тут в тестовому варіанті показано, як повино виглядати https://test.long-travel.live/20160814_24_shadsk/
![структура блока Header](https://user-images.githubusercontent.com/111632610/198410744-ba71e37a-1a40-4b47-98e1-81e9e15b7f40.png)

**Comment by tatarvit** [comment]
як я розумію прев'ю, повина бути одним блоком, а тут різні блоки
![Screenshot_4](https://user-images.githubusercontent.com/111632610/198413303-1676bc1b-54b9-44db-b469-fd05f2fd8a20.png)
![Screenshot_5](https://user-images.githubusercontent.com/111632610/198413305-86fd3e46-5918-4352-af02-49e35c141edf.png)
![Screenshot_6](https://user-images.githubusercontent.com/111632610/198413307-d5238ce5-35d8-4e10-b52e-2ad8c9830ff5.png)
![Screenshot_7](https://user-images.githubusercontent.com/111632610/198413308-61998e60-d9e3-4ecd-802b-ea7490799868.png)
![Screenshot_8](https://user-images.githubusercontent.com/111632610/198413311-22f92949-e806-40b0-93a6-4d30f09929d6.png)

**Comment by tatarvit** [comment]
@DmytroMarkulych 
Ще питання, чому на компі текст сіруватий, а на мобілі білий, такий, як необхідно

**Comment by DmytroMarkulych** [comment]
@tatarvit елементи які мають бути в прев'ю не зібрані в одне ціле. 
1. Не варто в актуальний і очікуваний результати перелічувати всі вимоги, якщо звичайно у нас є одна вимога то її потрібно. Додайте окремим пунктом Attachment і там лишіть  посилання на специфікацію і дизайн. 
2. В STR  останім пунктом додайте "Pay attention to ..." і вкажіть проблемне місце. 
3. Скріни в загальному добре оформлені, але якщо є можливість зробити скрін цілої сторінки то робіть це. 
4. Не можу зрозуміти який текст на ПК сірий а на смартфоні білий?

**Comment by tatarvit** [comment]
@DmytroMarkulych  STR -- це string (рядок) правильно я зрозумів. Ми порізному сприймаємо і розуміємо інформацію
Як коректного вказати проблемне місце, щоб було розуміло де це місце і невтрачався час на розуміння і пошук. Якщо можеш наведи приклад.

**Comment by tatarvit** [comment]
@DmytroMarkulych Не можу зрозуміти який текст на ПК сірий а на смартфоні білий?
цей текст
![Incorrect_text_color](https://user-images.githubusercontent.com/111632610/198531141-95928c98-cb4f-467d-aa62-7f25eadc151d.png)

**Comment by DmytroMarkulych** [comment]
@tatarvit 
1. STR - steps for reproduce 
Ок. Тоді приклад: 
На сторінці подорожі Шацьк превю не відповідає вимогам:
Описуємо кроки відтворення
Актуальний - що відсутнє в превю і Очікуваний результат що має бути . 
Пункт attacment - з посиланням на специфікацію і дизайн 
Скріни де на однму ми показуємо як є  а на іншому як має бути.

**Comment by tatarvit** [comment]
@DmytroMarkulych Давай тут я уточню, томущо я в фігмі побачив одне, там був блок. Потім знайшов вимоги до контенту, там текст. Якесь двояке бачення результата, а можливо я щось ще не розумію
