### ISSUE TITLE
20160814_24_Shadsk_russian language under Travel Map

### ISSUE THREAD

**Issue by tatarvit** [scholokov/long-travel-2#1533]
**Steps to reproduce:**
1. Open the website https://www.long-travel.live/20160814_24_shadsk/
2. Scroll to the end of google map

**Actual result**
russian language

**Expected result**
Ukrainian language

**Environment**
Operating system: Windows 10
Browser: Google Chrome Version 106.0.5249.119 (64-bit)

**![Ukr_lang](https://user-images.githubusercontent.com/111632610/198376701-77eb8802-0788-44e8-b188-bfaa91802cfa.png)**

**Comment by DmytroMarkulych** [comment]
@tatarvit це не зовсім google map. Правильну назву можна знайти в документації

**Comment by scholokov** [comment]
fixed
