### ISSUE TITLE
20160814_24_Shadsk_russian language under block with id="photonic-google-stream-1"

### ISSUE THREAD

**Issue by tatarvit** [scholokov/long-travel-2#1535]
**Description**
The text write russian language under the block with id="photonic-google-stream-1" 

**Steps to reproduce:**
1. Open the website https://www.long-travel.live/20160814_24_shadsk/
2. Scroll to the end of the first photo block

**Actual result**
The text is russian language 

**Expected result**
The text is Ukrainian language 

**Environment**
Operating system: Windows 10
Browser: Google Chrome Version 106.0.5249.119 (64-bit)

![Screenshot_4](https://user-images.githubusercontent.com/111632610/198605254-78e558e2-046e-4699-9c08-76b13c4ff4be.png)

**Comment by DmytroMarkulych** [comment]
@tatarvit це 2 окремі дефекти, розділіть його будь ласка

**Comment by DmytroMarkulych** [comment]
@tatarvit 
1.Проводьте тестування на даному середовищі https://test.long-travel.live/ 
Воно в нас тестове і всі актуальні фікси там.
