### ISSUE TITLE
20160814_24_Shadsk_russian language under block with id="photonic-google-stream-5"

### ISSUE THREAD

**Issue by tatarvit** [scholokov/long-travel-2#1536]
**Description**
The text write russian language under the block with id="photonic-google-stream-5" 

**Steps to reproduce:**
1. Open the website https://www.long-travel.live/20160814_24_shadsk/
2. Scroll to the end of the fifth photo block

**Actual result**
The text is russian language 

**Expected result**
The text is Ukrainian language 

**Environment**
Operating system: Windows 10
Browser: Google Chrome Version 106.0.5249.119 (64-bit)

![Screenshot_5](https://user-images.githubusercontent.com/111632610/198603980-42b6038d-59bf-4bcd-a6e5-79d01177240f.png)

**Comment by DmytroMarkulych** [comment]
@tatarvit це 2 різні дефекти в одному баг репорті. Розділіть будь ласка

**Comment by tatarvit** [comment]
@DmytroMarkulych Питання? Там по факту помилка в стилі до h4. Можу я завести баг на стилі? Нажаль я немаю доступа до коду, щоб впевнитися, але скоріше завсе можна через хром дев тулс.

**Comment by DmytroMarkulych** [comment]
@tatarvit 
1.Проводьте тестування на даному середовищі https://test.long-travel.live/ 
Воно в нас тестове і всі актуальні фікси там. 
2. Взагалі звертайте свою увагу при тестуванні на дизайн https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=0%3A1
3. Якщо там немає відповіді тоді на специфікацію і таким чином у вас буде 2 джерела
