### ISSUE TITLE
20150919_Kiev_Aviation_Museum/ На головній сторінці елементи меню  Home,Travels  по типу шрифта не відповідають вимогам

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1539]
Кроки для відтворення:

1.Відкрити сторінку https://test.long-travel.live/20150919_kiev_aviation_museum/
2.Звернути увагу на ти п шрифта  елементів меню Home,Travels
Фактичний результат :
Тип шрифта"inherit" елементів меню Home,Travels не відповідають вимогам
Очікуваний результат:
Тип шрифта "poppins"елементів меню Home,Travels  відповідають вимогам
Додаткова інформація : https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986%3A7
Середовище:
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_24](https://user-images.githubusercontent.com/109720075/198958374-88a473fc-156d-4391-a155-4464959f69c4.jpg)
![Screenshot_25](https://user-images.githubusercontent.com/109720075/198958379-d7eca3b8-fce3-4936-8da2-8ce4562b84a6.jpg)

![Screenshot_20](https://user-images.githubusercontent.com/109720075/198848458-98e877c7-29aa-444a-904a-e1ecf274e993.jpg)

**Comment by scholokov** [comment]
буд ласка перевірте ще раз на корректному середовищі:
test.long-travel.live

**Comment by DmytroMarkulych** [comment]
@andry1729 можливо там справа в типу шрифта ? Як гадаєте?

**Comment by andry1729** [comment]
> @andry1729возможны там права в маркировке шрифта ? Як гадаете?
Я гадаю ,що і баг репорт ось цей теж не правильно написано
![Screenshot_19](https://user-images.githubusercontent.com/109720075/198848321-f9d6422e-ee2d-4fd1-ab7a-298aa6e43d4b.jpg)

**Comment by DmytroMarkulych** [comment]
@andry1729 тоді давайт виправимо

**Comment by DmytroMarkulych** [comment]
@andry1729 в очікуваний та актуальний результати допишіть який шрифт є і який має бути

**Comment by DmytroMarkulych** [comment]
@andry1729 В Актуальний та Очікуваний результати допишіть назви шрифтів

**Comment by scholokov** [comment]
даний баг не має відношення до даної подорожі. це загальний баг
