### ISSUE TITLE
20160814_24_Shadsk_The main text describing the trip  is black

### ISSUE THREAD

**Issue by tatarvit** [scholokov/long-travel-2#1544]
**Description**
The main text describing the trip is black. The mistake is in the CSS file
 when writing styles for teg h4

**Steps to reproduce:**
1. Open the website https://www.long-travel.live/20160814_24_shadsk/
2. Scroll to the end of the first photo block

**Actual result**
The text is black

**Expected result**
The text has to be white (#ffffff)

**Environment**
Operating system: Windows 10
Browser: Google Chrome Version 106.0.5249.119 (64-bit)
![fault](https://user-images.githubusercontent.com/111632610/198624199-f7865b60-c099-4f13-8ced-b43151c9e41d.png)

**Comment by DmytroMarkulych** [comment]
@tatarvit 
1.Проводьте тестування на даному середовищі https://test.long-travel.live/ 
Воно в нас тестове і всі актуальні фікси там.
