### ISSUE TITLE
20160618_mezhigorie - FotoGallery - YoutubeVideo - Link is not active

### ISSUE THREAD

**Issue by KaterinaNimenko35** [scholokov/long-travel-2#1555]
**Steps to reproduce:**

1. Open page https://test.long-travel.live/20160618_mezhigorie/
2. Scroll down the page to the block "FotoGallery"
3. Hover your mouse over the YouTube link

**Actual result:**
Link is not active

**Expected result:**
Link is active

**Environment:**
Desktop/W10/Google Chrome 101.0.4951.67 (64-bit)

![test long-travel live_20160618_mezhigorie_ (1)](https://user-images.githubusercontent.com/105543094/198894340-c2c795fb-8dfa-4f1d-9262-ded563703f83.png)

https://user-images.githubusercontent.com/105543094/198894645-321983fb-36bb-4227-bc1e-2570fda0ab25.mp4

**Comment by scholokov** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
Verified, an issue is not reproduced
