### ISSUE TITLE
Подорож Львів-Вінниця, Preview повинно бути під картою

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#1559]
Передумови :
Відкрити https://test.long-travel.live/
Кроки для відтворення:
1. Клікніть на Travels
2. Клікніть на подорож Львів-Вінниця

Фактичний результат:  відсутнє фонове зображення
Очікуваний результат: відбражається фонове зображення

Середовище: Windows 10 Pro
Операційна система:
Браузер: Google Chrome  Версія 107.0.5304.88
![image](https://user-images.githubusercontent.com/113175298/199306224-2a8b4979-4523-4093-8e90-8ea055e20754.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk ну насправді це чорний прямокутник, а якщо більш правильніше то це відсутнє фонове зображення в прев'ю

**Comment by Nadiyk** [comment]
в самарі описати що відсутне фонове зображення?

**Comment by DmytroMarkulych** [comment]
@Nadiyk ні, але ми маємо задвоєння превю, і одне із них з фоновим зображення а інше ні, якщо судити по тому, що Ви описали то саме відсутнє фонове зображення

**Comment by DmytroMarkulych** [comment]
@Nadiyk можна звірити із дизайном

**Comment by DmytroMarkulych** [comment]
@Nadiyk ok)
