### ISSUE TITLE
20070722_0809_crimea route on map could not be found on travel page in Header 

### ISSUE THREAD

**Issue by Xalep4ik** [scholokov/long-travel-2#1560]
STR:
1.Open https://test.long-travel.live/20070722_0809_crimea/
2.Pay your attention to map.

Actual result:
Error message: The page you are looking for could not be found

Expected result:
On the map displayed route of travel.

![missing_map](https://user-images.githubusercontent.com/92167884/199474095-05403925-369f-4187-a7ac-d34ddda27d0f.png)

**Comment by scholokov** [comment]
fixed

**Comment by Xalep4ik** [comment]
Verified
