### ISSUE TITLE
20200307_09_Lviv_Vinnitsa прев'ю подорожі не відповідає дизайну

### ISSUE THREAD

**Issue by RomanTaradai** [scholokov/long-travel-2#1565]
Кроки для відтворення:

1.Відкрити сторінку https://test.long-travel.live/20200307_09_Lviv_Vinnitsa/
2.Зверніть увагу на дизайн заголовка

Фактичний результат:
не відповідає дизайну - подвійне прев'ю або відсутнє на інших блоках подорожі

Очікуваний результат:
дизайн відповідає figma
додаткова інформація https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986%3A6

Середовище:
Операційна система: Windows 10
Браузер: Google Chrome Версія 105.0.5195.127 (64 біт)
Розрішення екрану 1366х768
![Screenshot_56](https://user-images.githubusercontent.com/113344723/199718657-0c51341c-9663-4230-bc27-1c9104aa21a0.png)
![Screenshot_57](https://user-images.githubusercontent.com/113344723/199720962-1feaffd7-ea2a-49c0-8410-d0f6ae99c09b.png)
![Screenshot_58](https://user-images.githubusercontent.com/113344723/199720977-45f5f2dc-e7fb-4335-87de-88dde5c0ad22.png)
![Screenshot_59](https://user-images.githubusercontent.com/113344723/199720999-3df6f19f-0ec0-4cbd-8987-b4a40958881c.png)
![Screenshot_60](https://user-images.githubusercontent.com/113344723/199721019-5633ef8f-dfe3-4285-944a-5f96c038d580.png)

**Comment by scholokov** [comment]
fixed

**Comment by RomanTaradai** [comment]
> fixed

помилка відтворюється
![Screenshot_68](https://user-images.githubusercontent.com/113344723/200349053-531a8a2b-ffe9-4c14-899b-7e19dc73eaa1.png)
![Screenshot_64](https://user-images.githubusercontent.com/113344723/200349063-a737a20b-29fc-43af-a14c-2f2673d7adfb.png)
![Screenshot_65](https://user-images.githubusercontent.com/113344723/200349066-f8da97e2-ec85-4f14-a717-3e0cdd44b23a.png)
![Screenshot_66](https://user-images.githubusercontent.com/113344723/200349070-7c8e5b5f-3616-4118-9d72-5b9706d12112.png)
![Screenshot_67](https://user-images.githubusercontent.com/113344723/200349074-36b4cd5f-be47-4b00-b1f1-87e8c72a8e31.png)

**Comment by scholokov** [comment]
fixed

**Comment by scholokov** [comment]
fixed
