### ISSUE TITLE
20170805_20_Odessa/ Формат дати подорожі прев'ю  не відповідає вимогам

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1577]
Кроки для відтворення:
1.Відкрити сторінку https://test.long-travel.live/20170805_20_odessa/
2. Звернути увагу на формат дати подорожі
3. Фактичний результат:
Формат дати  подорожі в прев'ю не відповідає вимогам
Очікуваний результат:
Формат дати  подорожі в прев'ю  відповідає вимогам- 05.08.2017- 20.08.2017
Додаткова інформація: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986%3A6
Середовище:
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_21](https://user-images.githubusercontent.com/109720075/199975075-cffd0e22-8118-4cf4-94fa-46ec0445eada.png)
![Screenshot_20221104-142956~3](https://user-images.githubusercontent.com/109720075/199975627-3c10c313-52c0-4ed9-9230-e5403231d470.png)

**Comment by scholokov** [comment]
fixed

**Comment by DmytroMarkulych** [comment]
@andry1729 краще вживати "дефект відтворюється" замість "не змінився"
