### ISSUE TITLE
20170612_buki-2/ немає фото подорожі

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#1582]
Передумови:
Відкрити  https://test.long-travel.live/20170612_buki-2/
Кроки для відтворення:

1. Звеніть увагу, що немає фото на сторінці

Фактичний результат: немає фото подорожі
Очікуваний результат: є на сторінці фото з подорожі

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версия 107.0.5304.88 
![Букі](https://user-images.githubusercontent.com/113175298/200044234-1a762f78-499b-4ec3-914d-9c324677edaf.png)

**Comment by scholokov** [comment]
помилка не у відсутності фото
коректне айді подорожі:
https://test.long-travel.live/20170612_Buki/
а ви знайшли
https://test.long-travel.live/20170612_buki-2/

це якась помилкова подорож
видалив її
