### ISSUE TITLE
20071027_uman - Body - Preview - Image missing

### ISSUE THREAD

**Issue by KaterinaNimenko35** [scholokov/long-travel-2#1583]
**Steps to reproduce:**

1. Open page https://test.long-travel.live/20071027_uman/
2. Scroll down the page to the Body block
3. Pay attention to the preview

**Actual result:**
Image missing

**Expected result:**
Image present

**Environment:**
Desktop/W10/Google Chrome 101.0.4951.67 (64-bit)

![MyCollages](https://user-images.githubusercontent.com/105543094/200121868-60aaf6db-44d1-40d3-bbd6-4fd0ed4f3491.png)

**Comment by scholokov** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
Verified, an issue is not reproduced
