### ISSUE TITLE
20071027_uman - Header - The date of the travel is duplicated under the preview

### ISSUE THREAD

**Issue by KaterinaNimenko35** [scholokov/long-travel-2#1584]
**Steps to reproduce:**

1. Open page https://test.long-travel.live/20071027_Uman/
2. Pay attention to the preview

**Actual result:**
Travel date is **duplicated**

**Expected result:**
Travel date is **not duplicated**

**Environment:**
Desktop/W10/Google Chrome 101.0.4951.67 (64-bit)

![MyCollages (1)](https://user-images.githubusercontent.com/105543094/200124174-144cc73b-7d79-4541-b863-cb7b58ed88c2.png)

**Comment by scholokov** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
Verified, an issue is not reproduced
