### ISSUE TITLE
20071027_uman - Travels - Global map with routes - Detailed travels list - Travel details - Missing "Link" element

### ISSUE THREAD

**Issue by KaterinaNimenko35** [scholokov/long-travel-2#1586]
**Steps to reproduce:**

1. Open page https://test.long-travel.live/travels/
2. On the global map, in the detailed travel list, click on travel  **20071027_Uman**
3. Click on the "arrow" element that appears
4. Pay attention to travel details

**Actual result:**
Missing "Link" element

**Expected result:**
Present "Link" element

**Notes:**
Pay attention, the "Link" element opens travel on the Production environment

**Environment:**
Desktop/W10/Google Chrome 101.0.4951.67 (64-bit)

![MyCollages (2)](https://user-images.githubusercontent.com/105543094/200127717-80407557-ef46-47f8-977e-6eb707b3beb4.png)

![2022-11-05 162 50 207](https://user-images.githubusercontent.com/105543094/200127731-44182e22-a09c-400c-8491-f1d051d6927c.png)

**Comment by DmytroMarkulych** [comment]
@KaterinaNimenko35 додайте будь ласка деталей про те, куди саме цей лінк має вести

**Comment by KaterinaNimenko35** [comment]
@DmytroMarkulych  доповнила опис

**Comment by scholokov** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
Verified, an issue is not reproduced
