### ISSUE TITLE
20131019_Petrovtsi_Bitva_Za_Kiev/ На сторінці подорожі відсутній Header (Прев'ю) під картою

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1594]
Кроки відтворення:
1.Відкрити сторінку https://test.long-travel.live/20131019_Petrovtsi_Bitva_Za_Kiev/
2.Проскролити сторінку до Header (Прев'ю) сторінки
3.Звернути увагу на Header (Прев'ю) сторінки
Фактичний результат:
Header (Прев'ю) сторінки під картою  відсутній
Очікуваний результат:
Header (Прев'ю) сторінки під картою присутній
Додаткова інформація : https://github.com/scholokov/long-travel-2/wiki/2.-Travel.Structure
Середовище:
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_39](https://user-images.githubusercontent.com/109720075/200294417-4a1dc511-8c06-4dfd-8f22-636a323165d8.png)
![Screenshot_40](https://user-images.githubusercontent.com/109720075/200294428-c464a01b-b6ed-48a2-b6c4-6bdfbf7a58e8.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 давайте ще додамо деталей, що цей header саме ПІД картою

**Comment by scholokov** [comment]
fixed
