### ISSUE TITLE
20161023_Chaiky_Aerofly/ ND прев'ю подорожі не відповідає дизайну

### ISSUE THREAD

**Issue by RomanTaradai** [scholokov/long-travel-2#1598]
Кроки для відтворення:

1.Відкрити сторінку https://test.long-travel.live/20161023_Chaiky_Aerofly/
2.Зверніть увагу на дизайн заголовка

Фактичний результат:
не відповідає дизайну - відсутній  фон превю, відсутній прапор країни

Очікуваний результат:
дизайн відповідає figma
додаткова інформація https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986%3A6

Середовище:
Операційна система: Windows 10
Браузер: Google Chrome Версія 105.0.5195.127 (64 біт)
Розрішення екрану 1366х768
![Screenshot_70](https://user-images.githubusercontent.com/113344723/200352814-3d059a49-36af-423e-99b8-62d948781259.png)

**Comment by DmytroMarkulych** [comment]
@RomanTaradai скоріше там відсутній фон превю ніж попередній перегляд, в актуальному результаті

**Comment by scholokov** [comment]
fixed

**Comment by scholokov** [comment]
fixed
