### ISSUE TITLE
20201025_vedmy/ Немає фото з подорожі

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#1600]
Передумови:
Відкрити  https://test.long-travel.live/20201025_vedmy/
Кроки для відтворення:

1. Зверніть увагу, що відсутні фото подорожі

Фактичний результат:  Немає фото з подорожі
Очікуваний результат: Відображаються фото з подорожі
 
Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версия 107.0.5304.88 
![image](https://user-images.githubusercontent.com/113175298/200386244-47850b4f-e27b-437c-8104-5b95bff57a4d.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
