### ISSUE TITLE
20210508_12months - Header - Structural block "Назва подорожi" is duplicated

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#1603]
**Steps of reproducing:**
1. Open https://test.long-travel.live/20210508_12months/
2. Pay attention to Header

**Actual Result:**
Structural block "Назва подорожi" is present at structural block "Прев'ю" and under structural block "Прев'ю"

**Expected Result:**
Structural block "Назва подорожi" is present only at structural block "Прев'ю"

**Specification:**
https://github.com/scholokov/long-travel-2/wiki/2.-Travel.Structure

**Environment:**
Windows 10, Chrome 107.0.5304.88 (64 bit)
Android 8.1.0, Chrome 107.0.5304.91
![08 05 2021 Демидів, Київська область, Україна – Long-Travel - Google Chrome 08 11 2022 17_42_22](https://user-images.githubusercontent.com/95171672/200610820-8204f2d7-b82c-4168-888f-f62a2c941097.png)
![photo_2022-11-08_17-43-17](https://user-images.githubusercontent.com/95171672/200610840-8cbbf119-3572-4e74-9e1d-2339c0210598.jpg)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
verified. bug is not reproducing
