### ISSUE TITLE
20210508_12months - Header - Structural block "Перiод часу" is duplicated

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#1604]
**Steps of reproducing:**
1. Open https://test.long-travel.live/20210508_12months/
2. Pay attention to Header

**Actual Result:**
Structural block "Перiод часу" is present at structural block "Прев'ю" and under structural block "Прев'ю"

**Expected Result:**
Structural block "Перiод часу" is present only at structural block "Прев'ю"

**Specification:**
https://github.com/scholokov/long-travel-2/wiki/2.-Travel.Structure

**Environment:**
Windows 10, Chrome 107.0.5304.88 (64 bit)
Android 8.1.0, Chrome 107.0.5304.91
![08 05 2021 Демидів, Київська область, Україна – Long-Travel - Google Chrome 08 11 2022 17_47_21](https://user-images.githubusercontent.com/95171672/200612300-747497f2-3993-41a8-893f-1726c4a545ab.png)
![photo_2022-11-08_17-47-27](https://user-images.githubusercontent.com/95171672/200612313-4774fa0e-8fac-432c-9866-e99a7956cd06.jpg)

**Comment by scholokov** [comment]
fiixed
