### ISSUE TITLE
Travels - в блокові  "Легенда,  ID та хронології подорожей не відповідають специфікації (від останньої до найдавнішої) 

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1607]
Кроки відтворення
1.Відкрити сторінку https://test.long-travel.live/travels/
2.Звернути увагу на ID та хронологію усіх подорожей в блокові легенда
Фактичний результат:
В блокові легенда  ID та хронологія подорожей не відровідає специфікації (від останньої до найдавнішої)
Очікуваний результат:
В блокові легенда  ID та хронологія подорожей відровідає специфікації (від останньої до найдавнішої)
Додаткова інформація: https://github.com/scholokov/long-travel-2/wiki/1.-Global.Structure.Pages
https://docs.google.com/document/d/1HSLwXt9jQvRTYDwq_owDaw3IMDcOvlXtaHv5m5M2C_c/edit?usp=sharing      -вірна хронологія та ID
Середовище:
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![199735753-83df3321-9573-4599-94b0-8fa40553978c](https://user-images.githubusercontent.com/109720075/200862519-7df29427-1d52-4ddf-be02-1d2e2a380d6d.png)
![199735761-85bb45e0-581f-4b04-943a-7755f46b9bb9](https://user-images.githubusercontent.com/109720075/200862526-06faad21-ce5e-4536-81ee-a84f26c94e8c.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 у нас є конкретний пункт в специфікації із конкретними вимогами, давайте переформулюємо баг репорт так, щоб виключити фрази "не відповідає вимогам" спираючись на специфікацію

**Comment by scholokov** [comment]
але баг там глибше і цікавіше :)
виходячи зі скріна:
сортування корекне, але некоректна дата подорожі (бо судячи з айді - рік там 2014, а у даті 2010)

**Comment by andry1729** [comment]
Я перевірив всі подорожі в блокові Легенда,переглядав дату кожної подорожі . Проблема в основному в датах подорожі.
Також і в айді,в деяких подорожах воно зовсім відсутнє. Якщо треба ще один баг репорт завести на тему id,я зроблю

**Comment by DmytroMarkulych** [comment]
@andry1729 ви можете більш детально дослідити проблему, спираючись на дату подорожі 
![image](https://user-images.githubusercontent.com/88647733/201085988-4f74421a-f75d-4c02-8941-caeaa20737a2.png)

**Comment by andry1729** [comment]
На цьому скріні подорожі  проблема в id.

**Comment by andry1729** [comment]
Перевіряючи кожну подорож ,я перевіряв чи співпадають id та дата подорожі . Гугл док я прикріпив до баг репорту, в якому виписана хронологія від самої старішої до самої новішої подорожі і виправлені id 
 .які б могли впливати на хронологію.https://docs.google.com/document/d/1HSLwXt9jQvRTYDwq_owDaw3IMDcOvlXtaHv5m5M2C_c/edit?usp=sharing

**Comment by andry1729** [comment]
Ось скрін подорожей ,у яких id співпадає з датами ,але в блокові легенда вони ідуть не в равильній хронології
![Screenshot_7](https://user-images.githubusercontent.com/109720075/201090225-975dbc3d-c67f-4328-81b7-ecb275acaf64.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
Баг відтворюється. В подорожі 20141102_10_Egypt_Hurghada ,потрібно змінити id на  20101102_10_Egypt_Hurghada і в хронології ця проблема зникне.

**Comment by andry1729** [comment]
В подорожі 20150623_0711_Croatia теж потрібно змінити  id  на 20150623_0811_Croatia
![Screenshot_15](https://user-images.githubusercontent.com/109720075/201650980-43ad6619-63b4-42e3-b773-0defd4a58c42.png)
Подорож 20150530 Kiev Aviation Museum в хронології  повинна бути після  подорожі 20150523 picnic dnipro
![Screenshot_16](https://user-images.githubusercontent.com/109720075/201651419-1d5f54ed-b9ea-4e7f-8c09-8dfd728c858b.png)

**Comment by andry1729** [comment]
Подорож 20170805_20_odessa в хронології має знаходитись після подорожі 20170722_Boguslav
В подорожі 20200719_Belya_tsercov потрібно змінити id  на 20190719_Belya_tsercov і в хронології вона повинна бути після подорожі 20190616_Korostishevsky_Kanyon
![Screenshot_17](https://user-images.githubusercontent.com/109720075/201653231-1e2c2760-8113-43f1-bad9-2fd0a9da8cbb.png)

**Comment by andry1729** [comment]
Подорож 20200725_26_piviha повинна бути після подорожі 20200719_Belya_tsercov
Подорож 20201010_11_brech повинна бути після подорожі 20200918_20_kharkiv
![Screenshot_18](https://user-images.githubusercontent.com/109720075/201654526-e2257090-93e8-409d-a05f-1133dbea3d98.png)

**Comment by andry1729** [comment]
Також потрібно звернути увагу на ось ці подорожі 
![Screenshot_19](https://user-images.githubusercontent.com/109720075/201654963-518a89ef-7f72-426b-ad87-68edc84a8c0b.png)
Белая Церковь -зробити  id подорожі  20170624 Bila Tserkva в блокові легенда
Мемориальный комплекс Национального музея истории Великой Отечественной войны- зробити  id подорожі 20170905 kiev-museum-ww2 в блокові легенда
Букский каньон, Буки -зробити  id подорожі 20180612 buki в блокові легенда

**Comment by DmytroMarkulych** [comment]
@andry1729 Вже виходить, що маємо кілька дефектів в одному баг репорті. Давайте розділимо на окремі баг-репорти кожну проблему

**Comment by andry1729** [comment]
Зрозумів,розділю на окремі баг-репорти кожну проблему
