### ISSUE TITLE
20150623_0711_Croatia/  Different widths of the video fields on the travel page

### ISSUE THREAD

**Issue by RostKleimenov** [scholokov/long-travel-2#1610]
Steps to reproduse:

1. Open page https://test.long-travel.live/20150623_0711_Croatia/ 
2. Observe preview video clip 
Actual result:
Different widths of the video fields on the travel page
Expected result:
The appearance of the elements on the page must be the same
Environment
windows 10 Google
Chrome v.106.0.5249.103
Ubuntu 20.04.5 LTS
Google Chrome v 105.0.5195.125 (x64)
![image](https://user-images.githubusercontent.com/113580264/201070317-d327fdfc-6f47-4841-b5d3-30b1f572c31d.png)

**Comment by DmytroMarkulych** [comment]
@RostKleimenov швидше вони не мають бути одного розміру. Зверніть будь ласка увагу на специфікацію, там можна знайти більше деталей

**Comment by scholokov** [comment]
@DmytroMarkulych @RostKleimenov 
підтверджую - мають :)
і одразу на те що в документації такого немає, а має бути

**Comment by DmytroMarkulych** [comment]
@DmytroMarkulych @RostKleimenov
Хмм...тоді це хороший привід завести таску про додавання даних деталей в специфікацію? Як думаєте?)

**Comment by scholokov** [comment]
ну я про це і написав :)

**Comment by RostKleimenov** [comment]
зроблю
