### ISSUE TITLE
20201025_vedmy немає карти подорожі

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#1625]
Передумови :
Відкрити https://test.long-travel.live/20201025_vedmy/#gallery[photonic-google-album-1]/AE29bMETQdcezF5idA29fUy9T5m0EfcPdF-fpn2Fah4c2ZP2vkikcQw_FXgGbNnqNkKrWDQD4h9-hWEIQGtMdjJs3rHDrBwbFA/

1. Зверніть увагу, на сторінці подорожі немає карти

Фактичний результат: немає карти подорожі
Очікуваний результат: відображається карта подорожі

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версія 107.0.5304.88
![image](https://user-images.githubusercontent.com/113175298/201535858-bd117c82-5b54-40f1-bae9-19224d0c652c.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk додайте будь ласка, назву пункту "Кроки для відтворення"

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk Я мав на увазі: 
**Приклад:** 
Передумова : (лишаєте тут лінку на сторінку з дефектом)
Кроки для відтворення: 
1. Клікнути на відео з подорожю
2. Звернути увагу на, те що відео не відтворюється

**Comment by Nadiyk** [comment]
цей баг про відсутність карти

**Comment by DmytroMarkulych** [comment]
@Nadiyk я знаю, тому і написав що це "Приклад" як правиьно оформляти

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
