### ISSUE TITLE
20210926_mashrooms/ немає карти подорожі

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#1626]
Передумови :
Відкрити https://test.long-travel.live/20210926_mashrooms/

Кроки для відтворення

1. Зверніть увагу, що відсутня карта подорожі

Фактичний результат: немає карти подорожі
Очікуваний результат: відтворюється карти подорожі

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версія 107.0.5304.88
![image](https://user-images.githubusercontent.com/113175298/201536952-9bdb569c-02ec-4dc0-b9c9-f18d023b2728.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk додайте будь ласка, назву пункту "Кроки для відтворення"

**Comment by Nadiyk** [comment]
Виправила

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
Pass
