### ISSUE TITLE
20200725_26_piviha/На сторінці подорожі ,між фото прев'ю та картою ,присутня дата та назва подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1630]
Кроки відтворення:
1.Відкрити сторінку https://test.long-travel.live/20200725_26_piviha/
2.Проскролити сторінку до фото прев'ю і карти
3.Звернути увагу на дату між фото прев'ю і картою
Фактичний результат:
На сторінці подорожі ,між фото прев'ю та картою ,присутня дата та назва подорожі
Очікуваний результат:
На сторінці подорожі ,між фото прев'ю та картою, відсутня дата та назва подорожі
Додаткова інформація: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986%3A6
Середовище:
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_4](https://user-images.githubusercontent.com/109720075/201662602-a4008cd7-b005-4245-998f-23f6dfe41126.png)
![Screenshot_20](https://user-images.githubusercontent.com/109720075/201662608-ef128ffe-93ff-4709-9fc1-2ac4e85bd837.png)

**Comment by scholokov** [comment]
fixed
