### ISSUE TITLE
20200725_26_piviha/ В блокові легенда подорожі ,мова контенту російська

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1631]
Кроки відтворення:
1.Відкрити сторінку https://test.long-travel.live/20200725_26_piviha/
2.Проскролити сторінку до блоку легенда подорожі
3.Звернути увагу на мову контенту
Фактичний результат:В блокові легенда подорожі ,мова контенту російська
Очікуваний результат: В блокові легенда подорожі ,мова контенту  українська 
Додаткова інформація :https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986%3A6
Середовище:
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_22](https://user-images.githubusercontent.com/109720075/201666045-bca75c88-3c6d-412d-b1df-08ddeae1e0b8.png)
![Screenshot_23](https://user-images.githubusercontent.com/109720075/201666053-1cb832b8-4649-4cb7-a856-e54b7092ce9d.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
Потрібно виправити тільки назву гори
![Screenshot_48](https://user-images.githubusercontent.com/109720075/201916004-aadca898-abea-4efa-ac1a-ec3ba5463418.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
Ще ось тут потрібно виправити назву
![Uploading Screenshot_17.png…]()

**Comment by scholokov** [comment]
fixed
