### ISSUE TITLE
20200725_26_piviha/ На сторінці подорожі під картою відсутнє фото прев'ю та прапор України

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1634]
Кроки відтворення:
1.Відкрити сторінку https://test.long-travel.live/20200725_26_piviha/
2.Проскролити сторінку до фото прев'ю під картою
3. Звернути увагу на фото прев'ю
Фактичний результат: На сторінці подорожі під картою відсутнє фото прев'ю та прапор України
Очікуваний результат: На сторінці подорожі під картою присутнє фото прев'ю та прапор України
Додаткова інформація: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986%3A6
Середовище:
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_13](https://user-images.githubusercontent.com/109720075/201670201-8a2d0f47-e08f-4d17-a437-74729f625ca2.png)
![Screenshot_26](https://user-images.githubusercontent.com/109720075/201670208-a996f6b0-b4a2-48ad-ba08-c6cc29bd2fde.png)

**Comment by scholokov** [comment]
fixed
