### ISSUE TITLE
20200725_26_piviha/ На сторінці подорожі під картою опис  прев'ю російською мовою

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1635]
Кроки відтворення:
1.Відкрити сторінку https://test.long-travel.live/20200725_26_piviha/
2.Проскролити сторінку до фото прев'ю під картою
3. Звернути увагу на опис прев'ю
Фактичний результат: На сторінці подорожі під картою опис  прев'ю російською мовою
Очікуваний результат: На сторінці подорожі під картою опис  прев'ю українською мовою
Середовище:
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_27](https://user-images.githubusercontent.com/109720075/201671884-401c78ef-4e95-46e0-9de4-91996b943082.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
Баг відтворюється.Виправити Киев на Київ
![Screenshot_52](https://user-images.githubusercontent.com/109720075/201920738-d204eb2a-2dba-4111-811c-ad5aa19e2cf6.png)

**Comment by scholokov** [comment]
fixed
