### ISSUE TITLE
20200725_26_piviha/ В  Галереї фото та відео ,відсутні фото прев'ю, прапор України і мова контенту російська

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1636]
Кроки відтворення:
1.Відкрити сторінку https://test.long-travel.live/20200725_26_piviha/
2.Проскролити сторінку до блоку  (г.Пивиха, Полтавская Область, Украина)
3.Звернути увагу на фото прев'ю, прапор України і мову контенту
Фактичний результат: 
Відсутні фото прев'ю, прапор України і мова контенту російською мовою
Очікуваний результат:
Присутні  фото прев'ю, прапор України і мова контенту українською мовою
Середовище:
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_28](https://user-images.githubusercontent.com/109720075/201685983-ad005993-9f91-4c51-afa6-56495b2151f2.png)
![Screenshot_13](https://user-images.githubusercontent.com/109720075/201686494-1f63fa78-9b86-4c34-a111-ca97f084aabc.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 
В Summary можна не вказувати шлях до сторінки (В Галереї фото та відео , Блок (г.Пивиха, Полтавская Область, Украина), для цього є Кроки для відтворення. Summary потрібно робити лаконічним. Теж потрібно застосовувати для Актуального та Очікуваного результатів

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
Баг відтворюється.Відсутній прапор та граматична помилка - ь пропущена в слові Полтавська
![Screenshot_22](https://user-images.githubusercontent.com/109720075/202999242-2e666c21-db7b-4120-8356-5d91dc254201.png)

**Comment by scholokov** [comment]
fixed
