### ISSUE TITLE
20200725_26_piviha/ В Галереї фото та відео ,відсутні фото прев'ю,дата, прапор України і мова контенту російською мовою

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1637]
Кроки відтворення:
1.Відкрити сторінку https://test.long-travel.live/20200725_26_piviha/
2.Проскролити сторінку до блоку (Дорога Пивиха – Кременчук)
3.Звернути увагу на фото прев'ю, прапор України і мову контенту
Фактичний результат:
Відсутні фото прев'ю,дата, прапор України і мова контенту російською мовою
Очікуваний результат:
Присутні фото прев'ю,дата, прапор України і мова контенту українською мовою
Середовище:
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_13](https://user-images.githubusercontent.com/109720075/201687612-ca52d5bd-2777-4bbd-b93d-4fa6462e89fa.png)
![Screenshot_29](https://user-images.githubusercontent.com/109720075/201687619-e67e3162-c50f-4a8a-9ae5-c84e2d390718.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 
В Summary можна не вказувати шлях до сторінки (В Галереї фото та відео , Блок (г.Пивиха, Полтавская Область, Украина), для цього є Кроки для відтворення. Summary потрібно робити лаконічним. Теж потрібно застосовувати для Актуального та Очікуваного результатів

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
Баг відтворюється. Відсутня дата
![Screenshot_21](https://user-images.githubusercontent.com/109720075/202998673-4e26da10-02bc-40da-b591-5d0e8cd0e2d4.png)

**Comment by scholokov** [comment]
fixed
