### ISSUE TITLE
20200725_26_piviha/ В Галереї фото та відео , відсутні фото прев'ю, прапор України і мова контенту російською мовою

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1638]
**Кроки відтворення:**

1.Відкрити сторінку https://test.long-travel.live/20200725_26_piviha/
2.Проскролити сторінку до блоку ( Отель, Кременчук)
3.Звернути увагу на фото прев'ю, прапор України і мову контенту

**Фактичний результат:**

Відсутні фото прев'ю,дата, прапор України і мова контенту російською мовою
**Очікуваний результат:**

Присутні фото прев'ю,дата, прапор України і мова контенту українською мовою

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_13](https://user-images.githubusercontent.com/109720075/201688786-64027bca-0aa9-4f65-be48-79fceb73607e.png)
![Screenshot_30](https://user-images.githubusercontent.com/109720075/201688792-1344808d-4c3c-416a-92c0-776f896fed5c.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 
В Summary можна не вказувати шлях до сторінки (В Галереї фото та відео , Блок (г.Пивиха, Полтавская Область, Украина), для цього є Кроки для відтворення. Summary потрібно робити лаконічним. Теж потрібно застосовувати для Актуального та Очікуваного результатів

**Comment by DmytroMarkulych** [comment]
@andry1729 зробіть будь ласка між рядкові відступи та виділіть жирним назви атрибутів

**Comment by andry1729** [comment]
Виправив

**Comment by scholokov** [comment]
fixed
