### ISSUE TITLE
20200725_26_piviha/Превю"Кременчук 26.07.2020" - відсутній прапор України 

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1639]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20200725_26_piviha/
2.Проскролити сторінку до прев'ю (  Кременчук,26.07.2020)
3.Звернути увагу на  прапор України
 
**Фактичний результат:** Відсутній  прапор України в прев'ю "Кременчук 26.07.2020"
**Очікуваний результат:** Присутні  прапор України  в прев'ю "Кременчук 26.07.2020"

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_31](https://user-images.githubusercontent.com/109720075/204030067-c8f6e8a7-5156-459a-b32d-d2ec34c38b85.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 
В Summary можна не вказувати шлях до сторінки (В Галереї фото та відео , Блок (г.Пивиха, Полтавская Область, Украина), для цього є Кроки для відтворення. Summary потрібно робити лаконічним. Теж потрібно застосовувати для Актуального та Очікуваного результатів

**Comment by DmytroMarkulych** [comment]
@andry1729 в summary ще варто вказати де саме прапор відсутній, в якому блоці

**Comment by DmytroMarkulych** [comment]
@andry1729 даний блок називається превю

**Comment by scholokov** [comment]
fixed
