### ISSUE TITLE
20200725_26_piviha/ В Галереї фото та відео , відсутні фото прев'ю,дата, прапор України і мова контенту російською мовою

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1640]
Кроки відтворення:
1.Відкрити сторінку https://test.long-travel.live/20200725_26_piviha/
2.Проскролити сторінку до блоку (Дорога Кременчук – пивиха)
3.Звернути увагу на фото прев'ю, прапор України і мову контенту
Фактичний результат:
Відсутні фото прев'ю,дата, прапор України і мова контенту російською мовою
Очікуваний результат:
Присутні фото прев'ю,дата, прапор України і мова контенту українською мовою
Середовище:
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_13](https://user-images.githubusercontent.com/109720075/201690848-421a8fd2-bdcd-4394-ae57-58d9beee46a1.png)
![Screenshot_32](https://user-images.githubusercontent.com/109720075/201690858-3a699a14-1e0f-4dbd-b773-805aab0810aa.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 
В Summary можна не вказувати шлях до сторінки (В Галереї фото та відео , Блок (г.Пивиха, Полтавская Область, Украина), для цього є Кроки для відтворення. Summary потрібно робити лаконічним. Теж потрібно застосовувати для Актуального та Очікуваного результатів

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
Виправити написання Пивиха . П з великої букви

**Comment by scholokov** [comment]
але ж поточний баг не дорівнює начальному.
у даному випадку ми не можемо використовувати попередній.
ми повинні ідти по схемі:
- відкриваємо новий баг
- старий закриваємо з коментом, що відкрито "такий-то" баг на дану проблему

використовувати попередній ми можемо лише у випадку коли попередній баг на 100%  той же самий
![image](https://user-images.githubusercontent.com/22824947/203939438-2e1ee55b-6848-42a5-a166-4695b2dec556.png)
