### ISSUE TITLE
20200725_26_piviha/ В Галереї фото та відео , відсутні фото прев'ю, прапор України і мова контенту російською мовою

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1641]
Кроки відтворення:
1.Відкрити сторінку https://test.long-travel.live/20200725_26_piviha/
2.Проскролити сторінку до блоку (  г.Пивиха, Полтавская Область, Украина)
3.Звернути увагу на фото прев'ю, прапор України і мову контенту
Фактичний результат:
Відсутні фото прев'ю,дата, прапор України і мова контенту російською мовою
Очікуваний результат:
Присутні фото прев'ю,дата, прапор України і мова контенту українською мовою
Середовище:
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_13](https://user-images.githubusercontent.com/109720075/201691819-b21087ec-cbb9-4e02-8d1c-3e7b27de0e77.png)
![Screenshot_33](https://user-images.githubusercontent.com/109720075/201691826-1afed7e6-8967-4fd2-b658-dd64f99ffa2c.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 
В Summary можна не вказувати шлях до сторінки (В Галереї фото та відео , Блок (г.Пивиха, Полтавская Область, Украина), для цього є Кроки для відтворення. Summary потрібно робити лаконічним. Теж потрібно застосовувати для Актуального та Очікуваного результатів

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
Баг відтворюється ,м. Пивиха,Полтавська обл, Україна
![Screenshot_19](https://user-images.githubusercontent.com/109720075/202997339-e3746818-a5a2-4393-81be-b7126a3677f2.png)

**Comment by scholokov** [comment]
але ж поточний баг не дорівнює начальному.
у даному випадку ми не можемо використовувати попередній.
ми повинні ідти по схемі:
- відкриваємо новий баг
- старий закриваємо з коментом, що відкрито "такий-то" баг на дану проблему

використовувати попередній ми можемо лише у випадку коли попередній баг на 100%  той же самий
![image](https://user-images.githubusercontent.com/22824947/203939438-2e1ee55b-6848-42a5-a166-4695b2dec556.png)
