### ISSUE TITLE
20200725_26_piviha/  Прев'ю (Дорога Пивиха – Київ 26.07.2020)-відсутній прапор України 

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1642]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20200725_26_piviha/
2.Проскролити сторінку до прев'ю ( Дорога Пивиха – Київ 26.07.2020)
3.Звернути увагу на  прапор України в  прев'ю( Дорога Пивиха – Київ 26.07.2020)

**Фактичний результат:** Відсутній прапор України в  прев'ю( Дорога Пивиха – Київ 26.07.2020)
**Очікуваний результат:** Присутній прапор України  в прев'ю ( Дорога Пивиха – Київ 26.07.2020)

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_32](https://user-images.githubusercontent.com/109720075/204031125-7399b946-2746-45e0-804d-e134a2e55e08.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 
В Summary можна не вказувати шлях до сторінки (В Галереї фото та відео , Блок (г.Пивиха, Полтавская Область, Украина), для цього є Кроки для відтворення. Summary потрібно робити лаконічним. Теж потрібно застосовувати для Актуального та Очікуваного результатів

**Comment by DmytroMarkulych** [comment]
@andry1729 в summary ще варто вказати в якому блоці відсутній елемент

**Comment by DmytroMarkulych** [comment]
@andry1729 даний блок називається превю

**Comment by scholokov** [comment]
fixed
