### ISSUE TITLE
20200725_26_piviha/ В Галереї фото та відео , відео  2020.07.26 Пивиха-Киев,мова не українська

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1643]
Кроки відтворення:
1.Відкрити сторінку https://test.long-travel.live/20200725_26_piviha/
2.Проскролити до кінця сторінки до відео  2020.07.26 Пивиха-Киев
3. Звернути увагу на мову опису подорожі
Фактичний результат: Мова опису подорожі на відео російська 
Очікуваний результат : Мова опису подорожі на відео українська
Додаткова інформація : https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery
Середовище:
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_34](https://user-images.githubusercontent.com/109720075/201696245-d67c1d8d-b9be-4532-befc-f581e73c49b2.png)
![Screenshot_35](https://user-images.githubusercontent.com/109720075/201696251-5dba8a49-cc9a-4fde-b600-0be2a46a8d9c.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 
В Summary можна не вказувати шлях до сторінки (В Галереї фото та відео , Блок (г.Пивиха, Полтавская Область, Украина), для цього є Кроки для відтворення. Summary описує саме дефект, тобто ми не кажемо "мова контенту не українська", а буде правильно констатація "мова контенту рос.". Теж потрібно застосовувати для Актуального та Очікуваного результатів
