### ISSUE TITLE
20200725_26_piviha/ В Галереї фото та відео ,мова контенту російська

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1644]
Кроки відтворення:
1.Відкрити сторінку https://test.long-travel.live/20200725_26_piviha/
2.Проскролити до  відео 2020.07.25 Киев-Пивиха
3. Звернути увагу на мову опису подорожі
Фактичний результат: Мова опису подорожі на відео російська
Очікуваний результат : Мова опису подорожі на відео українська
Додаткова інформація : https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery
Середовище:
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_36](https://user-images.githubusercontent.com/109720075/201697272-b6d97dd9-13df-490c-9382-fedefb620e23.png)
![Screenshot_37](https://user-images.githubusercontent.com/109720075/201697281-76b85e71-14d4-4481-b734-ae12db1d715d.png)

**Comment by DmytroMarkulych** [comment]
@andry1729
В Summary можна не вказувати шлях до сторінки (В Галереї фото та відео , Блок (г.Пивиха, Полтавская Область, Украина), для цього є Кроки для відтворення. Summary описує саме дефект, тобто ми не кажемо "мова контенту не українська", а буде правильно констатація "мова контенту рос."

**Comment by scholokov** [comment]
fixed
