### ISSUE TITLE
Travels - в блокові "Легенда, подорож Белая Церковь ,id відсутнє і розташування подорожі в хронології не вірне 

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1652]
Кроки відтворення
1.Відкрити сторінку https://test.long-travel.live/travels/
2. Проскролити сторінку до подорожі Белая Церковь
2.Звернути увагу на ID Белая Церковь ,дату подорожі та хронологію в блокові легенда
Фактичний результат: Id відсутнє і розташування подорожі в хронології не вірне 
Очікуваний результат:  Id 20170624_Bila Tserkva/.В блокові легенда знаходиться після подорожі 20170605_Kiev_Mariinskiy/
Додаткова інформація:https://docs.google.com/document/d/1HSLwXt9jQvRTYDwq_owDaw3IMDcOvlXtaHv5m5M2C_c/edit
Середовище:
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_44](https://user-images.githubusercontent.com/109720075/201715575-688b0345-a233-4012-9b01-ca28b1956f91.png)

**Comment by scholokov** [comment]
некоректна дата подорожі
виправлено
коректна
20180624_bila_tserkva

**Comment by andry1729** [comment]
Змінити тільки June 2017 на June 2018
![Screenshot_57](https://user-images.githubusercontent.com/109720075/201935408-0f7fdc52-a7db-4808-a0c2-938e699e77c7.png)

**Comment by scholokov** [comment]
по факту це зовсім інша проблема і потрібен новий баг
але виправлено
