### ISSUE TITLE
Travels - в блокові "Легенда", подорож"Мемориальный комплекс Национального музея истории Великой Отечественной войны" ,id відсутнє і розташування подорожі в хронології не вірне

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1654]
Кроки відтворення
1.Відкрити сторінку https://test.long-travel.live/travels/
2. Проскролити сторінку до подорожі Мемориальный комплекс Национального музея истории Великой Отечественной войны
2.Звернути увагу на ID Мемориальный комплекс Национального музея истории Великой Отечественной войны ,дату подорожі та хронологію в блокові легенда
Фактичний результат: Id відсутнє і розташування подорожі в хронології не вірне
Очікуваний результат: Id 20170905 kiev-museum-ww2/.В блокові легенда знаходиться після подорожі 20170805_20_odessa/
Додаткова інформація:https://docs.google.com/document/d/1HSLwXt9jQvRTYDwq_owDaw3IMDcOvlXtaHv5m5M2C_c/edit
Середовище:
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_45](https://user-images.githubusercontent.com/109720075/201722503-9599615c-52f2-48e2-b140-e25b913a7498.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
Баг відтворюється . В блокові легенда не  знаходиться після подорожі 20170805_20_odessa/,а знаходиться після 20170417_Kiylov/
![Screenshot_49](https://user-images.githubusercontent.com/109720075/201917594-692632fe-eeaf-4f5c-8784-dd25a8a60f6c.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
Баг відтворюється. Ця подорож має знаходитись під цією подорожжю
![Screenshot_51](https://user-images.githubusercontent.com/109720075/201919689-6d807322-444d-4796-9730-29f18ba80984.png)

**Comment by scholokov** [comment]
сортування коректне
некоректна дата подорожі на мапі

**Comment by andry1729** [comment]
Ви праві , потрібно змінити місяць  в блокові легенда з вересня на травень
![Screenshot_55](https://user-images.githubusercontent.com/109720075/201931907-1db884fd-8ce3-4fd3-b3af-9c2c4e8ac252.png)
![Screenshot_56](https://user-images.githubusercontent.com/109720075/201931912-e8d778de-a806-498d-b258-0720ddbb108c.png)

**Comment by scholokov** [comment]
тобто виходить зовсім інша проблема
а якщо так - то це зовсім інший баг
