### ISSUE TITLE
Travels - в блокові "Легенда, подорож "Букский каньон, Буки" ,id відсутнє і розташування подорожі в хронології не вірне

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1655]
Кроки відтворення
1.Відкрити сторінку https://test.long-travel.live/travels/
2. Проскролити сторінку до подорожі "Букский каньон, Буки"
2.Звернути увагу на ID "Букский каньон, Буки" ,дату подорожі та хронологію в блокові легенда
Фактичний результат: Id відсутнє і розташування подорожі в хронології не вірне
Очікуваний результат: Id 20180612 buki/.В блокові легенда знаходиться після подорожі 20180611_Kiev_Sea/
Додаткова інформація:https://docs.google.com/document/d/1HSLwXt9jQvRTYDwq_owDaw3IMDcOvlXtaHv5m5M2C_c/edit
Середовище:
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_46](https://user-images.githubusercontent.com/109720075/201723590-95826593-4179-4320-99bd-285661fcb07c.png)

**Comment by scholokov** [comment]
fixed
correct id is
20170612_buki

**Comment by andry1729** [comment]
Баг відтворюється. Коректна Id -  20180612_buki/, так як подорож була у 2018 році
![Screenshot_50](https://user-images.githubusercontent.com/109720075/201918793-82017cd1-5f80-43c3-8f6f-93eb6c500745.png)

**Comment by scholokov** [comment]
виправлено на 2017 рік
