### ISSUE TITLE
Travels - в блокові "Легенда, подорож 20210926_mashrooms/ розташована не вірно в хронології подорожей

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1656]
Кроки відтворення
1.Відкрити сторінку https://test.long-travel.live/travels/
2.Проскролити сторінку до подорожі 20210926_mashrooms/
3.Звернути увагу на подорож 20210926_mashrooms/в блокові легенда та її хронологію
Фактичний результат: Подорож 20210926_mashrooms/ розташована не вірно в хронології подорожей
Очікуваний результат: Подорож 20210926_mashrooms/ розташована вірно в хронології подорожей після подорожі 20210912_lazalky/
Додаткова інформація:https://docs.google.com/document/d/1HSLwXt9jQvRTYDwq_owDaw3IMDcOvlXtaHv5m5M2C_c/edit
Середовище:
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_47](https://user-images.githubusercontent.com/109720075/201727803-cbea7e06-713f-4f00-92a5-c29bc7a5146a.png)

**Comment by scholokov** [comment]
fixed
