### ISSUE TITLE
20201025_vedmy/  в preview немає дати подорожі

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#1657]
Передумови:
Відкрити https://test.long-travel.live/20201025_vedmy/
Кроки для відтворення:

1. Зверніть, в preview нерозміщена дата подорожі

Фактичний результат:   в preview немає дати подорожі
Очікуваний результат:   в preview відображається дата подорожі

Середовище: Microsoft Edge   Операційна  
система:
Браузер:  Версія 107.0.1418.42

![025](https://user-images.githubusercontent.com/113175298/203600174-d12e697b-30c7-4105-8e25-b82af755f802.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk Підкажіть будь ласка, а є різниця між датою публікації і датою подорожі?

**Comment by DmytroMarkulych** [comment]
https://github.com/scholokov/long-travel-2/wiki/2.-Travel.Structure

**Comment by Nadiyk** [comment]
Дата публікації повинна бути в превю, так?

**Comment by DmytroMarkulych** [comment]
@Nadiyk ну давайте так, у нас є 2 дати, дата подорожі і дата публікації, то яка в превю дата має бути?

**Comment by Nadiyk** [comment]
дата подорожі

**Comment by DmytroMarkulych** [comment]
@Nadiyk чудово) тоді давайте опираючись на цей висновок виправимо баг репорт

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk ще давайте поправимо скрін

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
