### ISSUE TITLE
20150523_picnic_dnipro/ На сторінці подорожі ,між фото прев'ю та картою ,присутня дата та назва подорожі 

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1658]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150523_picnic_dnipro/
2.Проскролити сторінку до галереї
3.Звернути увагу присутність дати між фото прев'ю та картою

**Фактичний результат:** Між фото прев'ю та картою ,присутня дата та назва подорожі 
**Очікуваний результат:** Між фото прев'ю та картою ,відсутня дата та назва подорожі 

**Додаткова інформація:**
 https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986%3A6

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)

![Screenshot_4](https://user-images.githubusercontent.com/109720075/201927829-6801cb84-66d8-4253-85df-0ff02a107333.png)
![Screenshot_53](https://user-images.githubusercontent.com/109720075/201927837-61b2c31b-7a3e-4a9f-81d8-dc413e7c5945.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 Приклад : 
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150523_picnic_dnipro/
2.Проскролити сторінку до галереї
3.Звернути увагу на фото та відео

**Фактичний результат:** Галерея-фото та відео не відтворюються в LightBox
**Очікуваний результат:** Галерея-фото та відео відтворюються в LightBox

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)

**Comment by andry1729** [comment]
Виправив

**Comment by scholokov** [comment]
fixed
