### ISSUE TITLE
20150523_picnic_dnipro/ В прев'ю відсутні дата і назва подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1660]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150523_picnic_dnipro/
2.Проскролити сторінку до фото прев'ю 
3.Звернути увагу на дату і назву подорожі

**Фактичний результат:** В прев'ю відсутні дата і назва подорожі
**Очікуваний результат:** В прев'ю присутні  дата і назва подорожі

**Додаткова інформація:** 
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986%3A6

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_6](https://user-images.githubusercontent.com/109720075/201982379-54895322-66cd-4a06-936f-52b6386a06ac.png)
![Screenshot_7](https://user-images.githubusercontent.com/109720075/201982384-0c79f935-156e-4bc6-9378-e98be2e34302.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 Давайте в тілі баг репорту головні пункти повиділяємо жирним,і  зробимо інтервальні відступи між ними, щоб баг репорт був максимально читабельний

**Comment by andry1729** [comment]
виправив

**Comment by scholokov** [comment]
fixed
