### ISSUE TITLE
20150523_picnic_dnipro/ На сторінці подорожі під картою відсутні фото прев'ю , прапор України та назва подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1661]
**Кроки відтворення:**
1.Відкрити сторінку  https://test.long-travel.live/20150523_picnic_dnipro/
2.Проскролити сторінку до фото прев'ю під картою  , прапора України та назви подорожі
3. Звернути увагу на фото прев'ю,прапор України та назву подорожі 

**Фактичний результат:**  Під картою відсутні фото прев'ю , прапор України та назва подорожі
**Очікуваний результат:**  Під картою присутні фото прев'ю , прапор України та назва подорожі

**Додаткова інформація:** 
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986%3A6

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_4](https://user-images.githubusercontent.com/109720075/201981615-859f618e-2485-47a9-a471-57c4327604b0.png)
![Screenshot_5](https://user-images.githubusercontent.com/109720075/201981622-030fef05-9b59-4e8a-bc73-e618d13493b6.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 
1. Давайте в тілі баг репорту головні пункти повиділяємо жирним,і  зробимо інтервальні відступи між ними, щоб баг репорт був максимально читабельний 
2. Якщо і додайте всі пропущені елементи в 3-й пункт кроків для відтворення, бо ви там вказали тільки одне фото

**Comment by DmytroMarkulych** [comment]
@andry1729 Приклад : 
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150523_picnic_dnipro/
2.Проскролити сторінку до галереї
3.Звернути увагу на фото та відео

**Фактичний результат:** Галерея-фото та відео не відтворюються в LightBox
**Очікуваний результат:** Галерея-фото та відео відтворюються в LightBox

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)

**Comment by DmytroMarkulych** [comment]
@andry1729  в "3. Звернути увагу на фото прев'ю" просите звернути увагу тільки на фото в превю, але в баг репорті вказуєте ще прапор та назву подорожі.

**Comment by scholokov** [comment]
fixed
