### ISSUE TITLE
20091026_1102_Toronto/ ND An extra element "link" on the map of travel.

### ISSUE THREAD

**Issue by IrinK1** [scholokov/long-travel-2#1667]
Steps to reproduce:
1. Open https://test.long-travel.live/20091026_1102_Toronto/
2. Scroll down the page to the map.
3. Pay attention to the the link on the map.

Actual result:
An extra element "link" is included on the map of travel.
Expected result:
An extra element "link" is missed on the map of travel

Environment:
Windows 10 Pro (x64),
Google Chrome v. 107.0.5304.107
![Screenshot_7](https://user-images.githubusercontent.com/94845943/202201375-d7b1896a-ba6a-4b72-b74a-fc1ba7e5f234.png)
![Screenshot_8](https://user-images.githubusercontent.com/94845943/202201380-1cf08d8f-ae6a-49d3-81ca-9adb0a6db600.png)

**Comment by scholokov** [comment]
according to requirements - it is ok
https://github.com/scholokov/long-travel-2/wiki/2.6-Travel.Map
