### ISSUE TITLE
20141102_10_Egypt_Hurghada/  Дати в фото прев'ю та блокові "легенда" готелю Sentido Mamlouk Palace Resort не співпадають

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1668]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20141102_10_Egypt_Hurghada/
2.Проскролити сторінку до блоку "легенда" подорожі та фото прев'ю під картою
3.Звернути увагу на дати в фото прев'ю та блокові "легенда"  готелю Sentido Mamlouk Palace Resort

**Фактичний результат:**  Дати в фото прев'ю та блокові "легенда" готелю Sentido Mamlouk Palace Resort не співпадають.

**Очікуваний резльтат:**  Дати в фото прев'ю та блокові "легенда" готелю Sentido Mamlouk Palace Resort співпадають

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_8](https://user-images.githubusercontent.com/109720075/202209580-81d98457-9d18-40e5-9caa-999cc3f88c18.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 Актуальний і Фактичний результати ідентичні

**Comment by DmytroMarkulych** [comment]
@andry1729 знову ж summary про не вірну дату, а актуальний і очікувані результати про те що не співпадають дати

**Comment by scholokov** [comment]
fixed
