### ISSUE TITLE
20141102_10_Egypt_Hurghada/Відео знаходиться у блоці "Synbad Navy Museum, Synbad Submarine ,Hurgada08.11.2014". Дата відео і дата блоку не співпадають 

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1669]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20141102_10_Egypt_Hurghada/
2.Проскролити сторінку до кінця фото та відеогалереї блоку "Synbad Navy Museum, Synbad Submarine ,Hurgada
08.11.2014"
3.Звернути увагу на дату  відео "2014.11.06 Egypt - About Sea by Hazzem 1"

**Фактичний результат:**  Відео знаходиться у блоці "Synbad Navy Museum, Synbad Submarine ,Hurgada
08.11.2014"

**Очікуваний резльтат:**  Відео  знаходиться у блоці " El Gouna Egypt ,06.11.2014 "

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_10](https://user-images.githubusercontent.com/109720075/202222774-e37b82a9-b709-48b3-9a85-cbe5552511bd.png)
![Screenshot_11](https://user-images.githubusercontent.com/109720075/202222780-f476baa1-6ffa-4cf9-92e6-d40dcee0b4c9.png)
![Screenshot_12](https://user-images.githubusercontent.com/109720075/202222785-8ea641cd-b315-483b-8a36-30807d42097c.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 давайте перешишемо Summary  таким чином, щоб не використовувати слосполучення "не у вірному блоці"

**Comment by DmytroMarkulych** [comment]
@andry1729 в summary вказуєте, що дати не співпадають, а в Актуальному і Фактичному результатах вказуєте, оґщо відео знаходиться не в тому блоці. Будь ласка вкажіть актуальну проблему

**Comment by DmytroMarkulych** [comment]
@andry1729 Старайтеся не використовувати подібні фрази "Відео знаходиться не у тому блоці", вказуйте конкретні назви елементів або блоків

**Comment by scholokov** [comment]
2 videos merged in one playlist and added to block " El Gouna Egypt ,06.11.2014 "
