### ISSUE TITLE
20201025_vedmy/ в Preview  не має дати подорожі

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#1672]
Передумови :
Відкрити: https://test.long-travel.live/20201025_vedmy/#gallery%5Bphotonic-google-album-1%5D/AE29bMETQdcezF5idA29fUy9T5m0EfcPdF-fpn2Fah4c2ZP2vkikcQw_FXgGbNnqNkKrWDQD4h9-hWEIQGtMdjJs3rHDrBwbFA/

1. Зверніть увагу, що в previwe немає дати подорожі

Фактичний результат:  в Preview  не має дати подорожі
Очікуваний результат: в Preview  відображається дата подорожі

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версія 107.0.5304.88
![image](https://user-images.githubusercontent.com/113175298/202866257-8d9b6f1e-32d2-405e-a43f-872f2b683b0d.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk 
1. Виправіть, будь ласка, гараматичні помилки
2. Давайте пригадаємо, яка дата повинна бути в превю, публікації чи дата подорожі?)

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk поправте будь ласка скріншот, він не завантажується

**Comment by Nadiyk** [comment]
виправила

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
