### ISSUE TITLE
20201025_vedmy/ в розділі легасі немає Назви - Link про подорож

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#1674]
Передумови :
Відкрити https://test.long-travel.live/20201025_vedmy/#gallery%5Bphotonic-google-album-1%5D/AE29bMETQdcezF5idA29fUy9T5m0EfcPdF-fpn2Fah4c2ZP2vkikcQw_FXgGbNnqNkKrWDQD4h9-hWEIQGtMdjJs3rHDrBwbFA/

1. Зверніть увагу, що в легасі відсутня інформація Назва - Link подорожі
 
Фактичний результат:   в розділі легасі немає Назва - Link подорожі  подорож
Очікуваний результат: в розділі легасі є  Назва - Link подорожі про подорож   

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версія 107.0.5304.88
![near card](https://user-images.githubusercontent.com/113175298/202689436-2826fd7a-eb94-45cd-9746-9883f2dc1bac.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk
1. Якщо у нас кроки відтворення дефекту вміщаються в 6-7 кроків, то передумови не потрібно писати
2. Даний елемент карти має назву, будь ласка, подивіться в документації

**Comment by Nadiyk** [comment]
я неможу зрозумітись де тут назва

![image](https://user-images.githubusercontent.com/113175298/202784703-6a3f79a4-d79e-4405-97aa-23277b312b08.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk можемо ще подивитися тут https://github.com/scholokov/long-travel-2/wiki/2.6-Travel.Map

**Comment by Nadiyk** [comment]
Виправила

**Comment by scholokov** [comment]
краще казати саме якої інформації там не вистачає (на приклад превью, лінк). це все прописано у вимогах. фігма відповідає лише за зовнішній вигляд. і не каже яку саме інформацію потрібно там відображати

**Comment by Nadiyk** [comment]
Виправила

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
Pass
