### ISSUE TITLE
20210510_stariy_solvin/ в Preview після карти немає  дати подорожі

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#1675]
Передумови :
Відкрити: https://test.long-travel.live/20210510_stariy_solvin/

1. Зверніть увагу, що в Previwe немає дати подорожі

Фактичний результат:  в Preview немає дати подорожі
Очікуваний результат: після в Preview відображається дата подорожі

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версія 107.0.5304.88
![низ ПРВ](https://user-images.githubusercontent.com/113175298/202692873-12dc8443-3c1f-4114-8b6b-c5c4a2aa0a45.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk Якщо у нас кроки відтворення дефекту вміщаються в 6-7 кроків, то передумови не потрібно писати

**Comment by Nadiyk** [comment]
то як виправити?

**Comment by DmytroMarkulych** [comment]
@Nadiyk давайте впишемо яких елементів в превю не вистачає (у нас є тільки назва подорожі)

**Comment by Nadiyk** [comment]
Брати з відси інформацію?
![image](https://user-images.githubusercontent.com/113175298/202866827-4d05f252-024d-4707-8a44-8f5c8ee6b09e.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk по факту у нас є 2 джерела інформації, це специфікація в git (wiki), та Figma. У Figma актуальніша, але в Wiki Ви можете дізнатися назви UI елементів. Тому найкраща практика брати із 2-х джерел потрібну інфу

**Comment by Nadiyk** [comment]
Якщо дивитися тут то в перевю яке під картою повинна бути, дата подорожі назва, а також фот в первю.  Чи я не права?

![image](https://user-images.githubusercontent.com/113175298/202908576-4e08eb83-f998-4342-9fc6-cefc8367f17c.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk так, все вірно. У нас із цього всього є тільки назва подорожі

**Comment by Nadiyk** [comment]
Значить переформувати цей баг, що в превю під картою немає зображення?

**Comment by DmytroMarkulych** [comment]
@Nadiyk зображення і інших елементів які мають бути 
![image](https://user-images.githubusercontent.com/88647733/202917862-f627cb8e-c02b-437f-a9fb-c35b3b183fca.png)

**Comment by Nadiyk** [comment]
дата подорожі і прапор? так?

**Comment by DmytroMarkulych** [comment]
@Nadiyk так)

**Comment by DmytroMarkulych** [comment]
@Nadiyk зверніть увагу на  summary

**Comment by Nadiyk** [comment]
Виправила

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
