### ISSUE TITLE
20140616_0707_Greece/ Фото прев'ю під картою- мова контенту російською мовою 

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1678]
**Кроки для відтворення:**
1.Відкрити сторінку https://test.long-travel.live/travels/20140616_0707_Greece/
2.Звернути увагу на мову контенту  в фото  прев'ю під картою

**Фактичний результат:** Мова контенту російською мовою 
**Очікуваний результат:** Мова контенту українською мовою 

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_46](https://user-images.githubusercontent.com/109720075/203114735-1325c2bb-3fa4-40f5-89bb-2082090e2866.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 цей дефект можете розділити на 2 окремі

**Comment by scholokov** [comment]
fixed
