### ISSUE TITLE
20140616_0707_Greece/ Блок "Budapest Magyarorszáта "- відсутнє фото прев'ю 

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1680]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20140616_0707_Greece/
2.Проскролити сторінку до блоку  "Budapest Magyarország ,17-19.06.2016"
3.Звернути увагу на фото прев'ю 

**Фактичний результат:** Відсутнє фото прев'ю
**Очікуваний результат:** Присутнє фото прев'ю 

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_43](https://user-images.githubusercontent.com/109720075/203112472-f4ebdda4-0c9b-45b3-9355-14c7b3487436.png)

**Comment by scholokov** [comment]
fixed
