### ISSUE TITLE
20140616_0707_Greece/ Блок "Žitorađa Србија 19.06.2014-21.06.2014"-відсутнє фото прев'ю 

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1681]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20140616_0707_Greece/
2.Проскролити сторінку до блоку "Žitorađa Србија 19.06.2014-21.06.2014"
3.Звернути увагу на фото прев'ю 

**Фактичний результат:** Відсутнє фото прев'ю 
**Очікуваний результат:** Присутнє фото прев'ю 

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_30](https://user-images.githubusercontent.com/109720075/203069302-3882769b-a29d-4317-839f-36dd3e4e9df4.png)

**Comment by scholokov** [comment]
fixed
