### ISSUE TITLE
20140616_0707_Greece/ Блок "Србија Србија 19.06.2014-21.06.2014"-відсутнє фото прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1682]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20140616_0707_Greece/
2.Проскролити сторінку до блоку "Србија Србија 19.06.2014-21.06.2014"
3.Звернути увагу на фото прев'ю

**Фактичний результат:** Відсутнє фото прев'ю
**Очікуваний результат:** Присутнє фото прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_31](https://user-images.githubusercontent.com/109720075/203070766-eb59a81e-d2ac-41ca-910d-25f02204a522.png)

**Comment by scholokov** [comment]
fixed
