### ISSUE TITLE
20140616_0707_Greece/  Рік подорожі не збігається з роком в блокові "Greece Ouranoupolis 21.06-01.07.2016"

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1683]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20140616_0707_Greece/
2.Проскролити сторінку до блоку "Greece Ouranoupolis 21.06-01.07.2016"
3.Звернути увагу на  рік подорожі в блокові

**Фактичний результат:** Рік подорожі не збігається з роком в блокові "Greece Ouranoupolis " (2016)
**Очікуваний результат:** Рік подорожі  збігається з роком в блокові "Greece Ouranoupolis " (2014)

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_48](https://user-images.githubusercontent.com/109720075/203117049-0c0c30eb-0838-478c-b44d-2d043fc4e7b3.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
Баг відтворюється
![Screenshot_45](https://user-images.githubusercontent.com/109720075/204084624-c00dd5cf-b4f3-4225-94a1-2cb8a6fae478.png)

**Comment by scholokov** [comment]
fixed
