### ISSUE TITLE
20140616_0707_Greece/ Рік подорожi не співпадає з роком в блокові "Ouranoupolis, Greece Akrathos Beach Hotel 21.06-01.07.2016"

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1684]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20140616_0707_Greece/
2.Проскролити сторінку до блоку "Ouranoupolis, Greece Akrathos Beach Hotel 21.06-01.07.2016"
3.Звернути увагу на  рік подорожі в блокові "Ouranoupolis, Greece Akrathos Beach Hotel 21.06-01.07.2016"
 
**Фактичний результат:** Рік подорожi не співпадає з роком в блокові "Ouranoupolis, Greece Akrathos Beach Hotel"
**Очікуваний результат:**  Рік подорожi  співпадає з роком в блокові "Ouranoupolis, Greece Akrathos Beach Hotel"

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_33](https://user-images.githubusercontent.com/109720075/203074201-ce0e5899-4f3a-4dae-90d1-d3a587b2a171.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 при оформленні баг репортів не використовуйте слова "не вірний", а замініть їх на більш конкретні

**Comment by DmytroMarkulych** [comment]
@andry1729 одинакові Актуальний та Очікувані результати

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
Баг відтворюється
![Screenshot_44](https://user-images.githubusercontent.com/109720075/204084246-00ecb495-0184-4728-80ca-f189b3f2687f.png)

**Comment by scholokov** [comment]
fixed
