### ISSUE TITLE
20140616_0707_Greece/ Рік подорожi не співпадає з роком в блокові"Greece Greece 21.06-01.07.2016"

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1685]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20140616_0707_Greece/
2.Проскролити сторінку до блоку "Greece Greece 21.06-01.07.2016"
3.Звернути увагу на  рік подорожі  блоку "Greece Greece 21.06-01.07.2016"

**Фактичний результат:** Рік подорожi не співпадає з роком в блокові"Greece Greece
**Очікуваний результат:** Рік подорожi  співпадає з роком в блокові"Greece Greece

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_55](https://user-images.githubusercontent.com/109720075/203123884-071419e5-3c3e-4ce4-9198-e045b5e86474.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 при оформленні баг репортів не використовуйте слова "не вірний", а замініть їх на більш конкретні. Розділіть цей баг репорт на 2 окремих

**Comment by scholokov** [comment]
fixed
