### ISSUE TITLE
20140616_0707_Greece/   Рік подорожi не співпадає з роком в блокові "Ruse Ruse 01.07-03.07.2016"

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1686]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20140616_0707_Greece/
2.Проскролити сторінку до блоку ""Ruse Ruse 01.07-03.07.2016""
3.Звернути увагу на  рік подорожі

**Фактичний результат:**  Рік подорожi не співпадає з роком в блокові (2016)
**Очікуваний результат:** Рік подорожi  співпадає з роком в блокові (2014)

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_35](https://user-images.githubusercontent.com/109720075/203076783-c564e13a-0381-4667-99e3-9dccb231d796.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 при оформленні баг репортів не використовуйте слова "не вірний", а замініть їх на більш конкретні

**Comment by scholokov** [comment]
fixed
