### ISSUE TITLE
20140616_0707_Greece/ Рік подорожi не співпадає з роком в блокові "Дорога Ruse, Bulgaria – Sibiu, Romania 03.07.2016"

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1687]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20140616_0707_Greece/
2.Проскролити сторінку до блоку "Дорога Ruse, Bulgaria – Sibiu, Romania 03.07.2016"
3.Звернути увагу на рік подорожі в блокові "Дорога Ruse, Bulgaria – Sibiu, Romania 03.07.2016"

**Фактичний результат:** Рік подорожi не співпадає з роком в блокові "Дорога Ruse, Bulgaria – Sibiu, Romania"
**Очікуваний результат:** Рік подорожi співпадає з роком в блокові "Дорога Ruse, Bulgaria – Sibiu, Romania

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_36](https://user-images.githubusercontent.com/109720075/203077511-fb9f6220-12de-4d8e-820f-5cab1a943804.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 при оформленні баг репортів не використовуйте слова "не вірний", а замініть їх на більш конкретні

**Comment by scholokov** [comment]
ffixed
