### ISSUE TITLE
20140616_0707_Greece/Рік подорожi не співпадає з роком в блокові "Romania Transfagarasan Road 03.07.2016"

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1688]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20140616_0707_Greece/
2.Проскролити сторінку до блоку "Romania Transfagarasan Road 03.07.2016"
3.Звернути увагу на рік подорожі в блокові "Romania Transfagarasan Road 03.07.2016"

**Фактичний результат:** Рік подорожi не співпадає з роком в блокові  "Romania Transfagarasan Road"
**Очікуваний результат:** Рік подорожi  співпадає з роком в блокові  "Romania Transfagarasan Road"

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_37](https://user-images.githubusercontent.com/109720075/203078871-fe953a42-bec4-4e44-a0f8-4cd45760c62b.png)

**Comment by scholokov** [comment]
fixed
