### ISSUE TITLE
20140616_0707_Greece/ Рік подорожi не співпадає з роком в блокові  "Нotel Stefani Sibiu, Romania 03.07-05.07.2016"

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1689]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20140616_0707_Greece/
2.Проскролити сторінку до блоку "Нotel Stefani Sibiu, Romania 03.07-05.07.2016"
3.Звернути увагу на рік подорожі в блокові "Нotel Stefani Sibiu, Romania 03.07-05.07.2016"

**Фактичний результат:** Рік подорожi не співпадає з роком в блокові "Нotel Stefani Sibiu, Romania" 
**Очікуваний результат:** Рік подорожi  співпадає з роком в блокові "Нotel Stefani Sibiu, Romania"

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_52](https://user-images.githubusercontent.com/109720075/203120677-68d25a90-b68d-46ed-a7f8-ddc29f517b1c.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 при оформленні баг репортів не використовуйте слова "не вірний", а замініть їх на більш конкретні та розділіть дефект на 2 окремих

**Comment by scholokov** [comment]
fixed
