### ISSUE TITLE
20140616_0707_Greece/ Блок "Erney Laz Шаян, Украина 05.07-07.07.2014" - мова контенту російська

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1690]
Кроки відтворення:
1.Відкрити сторінку https://test.long-travel.live/20140616_0707_Greece/
2.Проскролити сторінку до блоку "Erney Laz Шаян, Украина 05.07-07.07.2014"
3.Звернути увагу на мову контенту

Фактичний результат: Мова контенту російська
Очікуваний результат: Мова контенту українська

Середовище:
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_39](https://user-images.githubusercontent.com/109720075/203081451-6f5aee41-03d2-49e0-812e-4910230ab528.png)

**Comment by scholokov** [comment]
fixed
