### ISSUE TITLE
20140616_0707_Greece/ Блок "Zoo, Хуст, Украина 06.07.2014"- відсутнє фото прев'ю 

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1691]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20140616_0707_Greece/
2.Проскролити сторінку до блоку "Zoo, Хуст, Украина 06.07.2014"
3.Звернути увагу на фото прев'ю 

**Фактичний результат:** Відсутнє фото прев'ю 
**Очікуваний результат:** Присутнє фото прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_49](https://user-images.githubusercontent.com/109720075/203118197-16c2d4d5-042f-41d5-b33c-32ec247a115a.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 розділіть на окремі дефекти

**Comment by scholokov** [comment]
fixed
