### ISSUE TITLE
20140616_0707_Greece/ Блок "Budapest Magyarország"-відсутній прапор Угорщини і присутній Український

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1692]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20140616_0707_Greece/
2.Проскролити сторінку до блоку "Budapest Magyarország ,17-19.06.2016"
3.Звернути увагу на прапор

**Фактичний результат:** Відсутній прапор Угорщини і присутній Український
**Очікуваний результат:** Присутній прапор Угорщини

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_44](https://user-images.githubusercontent.com/109720075/203112751-1f589933-4f0f-4b61-b5f4-f03d1d8ecead.png)

**Comment by scholokov** [comment]
fixed
