### ISSUE TITLE
20140616_0707_Greece/ Фото прев'ю під картою-  відсутній прапор України

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1693]
**Кроки для відтворення:**
1.Відкрити сторінку https://test.long-travel.live/travels/20140616_0707_Greece/
2.Звернути увагу на прапор України в фото прев'ю під картою

**Фактичний результат:**  Відсутній прапор України
**Очікуваний результат:**  Присутній прапор України

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_45](https://user-images.githubusercontent.com/109720075/203114321-8663f1a0-aa8c-4fce-9992-ffc10ee1ef90.png)

**Comment by scholokov** [comment]
fixed
