### ISSUE TITLE
20140616_0707_Greece/ Блок "Greece Ouranoupolis 21.06-01.07.2016"-відсутній прапор Греції

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1694]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20140616_0707_Greece/
2.Проскролити сторінку до блоку "Greece Ouranoupolis 21.06-01.07.2016"
3.Звернути увагу на прапор 

**Фактичний результат:** Відсутній прапор Греції
**Очікуваний результат:** Присутній прапор Греції

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_47](https://user-images.githubusercontent.com/109720075/203116256-8cccfe7a-83a5-4a02-bb2e-04f53d1a15da.png)

**Comment by scholokov** [comment]
fixed
