### ISSUE TITLE
20140616_0707_Greece/ Блок "Zoo, Хуст, Украина 06.07.2014"- мова контенту російською

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1695]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20140616_0707_Greece/
2.Проскролити сторінку до блоку "Zoo, Хуст, Украина 06.07.2014"
3.Звернути увагу на мову контенту

**Фактичний результат:** Мова контенту російською
**Очікуваний результат:** Мова контенту українською

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_51](https://user-images.githubusercontent.com/109720075/203119476-967e40a5-5d61-4f2d-a0d5-4b46c674619e.png)

**Comment by scholokov** [comment]
fixed
