### ISSUE TITLE
20140616_0707_Greece/ Блок "Zoo, Хуст, Украина 06.07.2014"- відсутній прапор України 

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1696]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20140616_0707_Greece/
2.Проскролити сторінку до блоку "Zoo, Хуст, Украина 06.07.2014"
3.Звернути увагу на прапор в фото прев'ю

**Фактичний результат:** Відсутній прапор України 
**Очікуваний результат:** Присутній прапор України 

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_50](https://user-images.githubusercontent.com/109720075/203119512-01a67c55-0dba-4fb3-b4c3-267852727543.png)

**Comment by scholokov** [comment]
fixed
