### ISSUE TITLE
20140616_0707_Greece/ Прев'ю подорожі "Нotel Stefani Sibiu, Romania 03.07-05.07.2016"-   зображено прапор країни Польща

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1697]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20140616_0707_Greece/
2.Проскролити сторінку до прев'ю подорожі"Нotel Stefani Sibiu, Romania 03.07-05.07.2016"
3.Звернути увагу в прев'ю  на прапор в прев'ю

**Фактичний результат:** В прев'ю подорожі  прапор Польщі, а повинен бути зображений  прапор Румунії
**Очікуваний результат:** В прев'ю подорожі зображений  прапор Румунії

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_53](https://user-images.githubusercontent.com/109720075/203121370-4b56258f-3c05-4dc0-81c7-14ad9baec605.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 додайте деталей в summary. Зверніть увагу на Очікуваний результат, назву країни

**Comment by DmytroMarkulych** [comment]
@andry1729 прапор країни Польща - Що?

**Comment by DmytroMarkulych** [comment]
@andry1729 давайте ще додамо назву цього блоку де зображено прапор

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_3](https://user-images.githubusercontent.com/109720075/205672661-08b7dcf6-b080-4357-b2ad-3334713e2a00.png)
Залишився прапор Польщі

**Comment by scholokov** [comment]
please retest

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_23](https://user-images.githubusercontent.com/109720075/206147454-81bd8dfe-9c54-4d81-8e62-1da4918e6289.png)

**Comment by scholokov** [comment]
please retest

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_57](https://user-images.githubusercontent.com/109720075/206496616-8edfa470-552e-4544-a779-939fb20bb9bc.png)
