### ISSUE TITLE
20140616_0707_Greece/ Блок "Greece Greece 21.06-01.07.2016"-відсутній прапор Греції

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1698]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20140616_0707_Greece/
2.Проскролити сторінку до блоку "Greece Greece 21.06-01.07.2016"
3.Звернути увагу на прапор 

**Фактичний результат:** Відсутній прапор Греції 
**Очікуваний результат:** Присутній прапор Греції 

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_54](https://user-images.githubusercontent.com/109720075/203123365-c19d77ed-40ca-4bcb-891d-3692eca894af.png)

**Comment by scholokov** [comment]
fixed
