### ISSUE TITLE
20210510_stariy_solvin/Галерея-фото не відтворюються в LightBox

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1699]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210510_stariy_solvin/
2.Проскролити сторінку до галереї
3.Натиснути на фото
4.Звернути увагу на фото

**Фактичний результат:** Галерея-фото не відтворюються в LightBox
**Очікуваний результат:** Галерея-фото відтворюються в LightBox

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_1](https://user-images.githubusercontent.com/109720075/203277373-dcd3962d-0b93-43d2-8398-e2d4d447e2fc.png)
![Screenshot_2](https://user-images.githubusercontent.com/109720075/203277384-51fbfe47-768d-42b7-ab6c-8cb4dfdf4bd6.png)

**Comment by poroskundenys** [comment]
У меня отображается фото в LightBox

**Comment by scholokov** [comment]
там відображаються, якщо авторизований. а колі ні - то не відображаються
