### ISSUE TITLE
20210510_stariy_solvin/ Відсутнє фото прев'ю під картою подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1700]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210510_stariy_solvin/
2.Проскролити сторінку до фото прев'ю під картою подорожі
3.Звернути увагу на фото прев'ю

**Фактичний результат:** Відсутнє фото прев'ю під картою подорожі
**Очікуваний результат:** Присутнє фото прев'ю під картою подорожі

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_3](https://user-images.githubusercontent.com/109720075/203297666-67d84d54-9b50-4654-bfa5-a86087b971a8.png)

**Comment by scholokov** [comment]
fixed
