### ISSUE TITLE
20210510_stariy_solvin/  Під картою подорожі -блок "Дорога Київ - Старий Солотвін" граматична помилка 

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1701]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210510_stariy_solvin/
2.Проскролити сторінку до блоку "Дорога Київ - Старий Солотвін"
3.Звернути увагу на граматику

**Фактичний результат:** Блок "Дорога Київ - Старий Солотвін"- граматична помилка(Словин)
**Очікуваний результат:** В назві  блок "Дорога Київ - Старий Солотвін" граматичних помилок немає

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_4](https://user-images.githubusercontent.com/109720075/203300305-cc094a1a-e7b4-4d4f-9eb3-781c69d646d6.png)

**Comment by scholokov** [comment]
fixed
