### ISSUE TITLE
20210510_stariy_solvin/ Блок "Дорога Київ - Старий Солотвін" під картою подорожі -відсутній прапор України

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1702]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210510_stariy_solvin/
2.Проскролити сторінку до фото прев'ю під картою подорожі
3.Звернути увагу на прапор

**Фактичний результат:** Блок "Дорога Київ - Старий Солотвін" під картою подорожі -відсутній прапор України
**Очікуваний результат:** Блок "Дорога Київ - Старий Солотвін" під картою подорожі -присутній прапор України

**Додаткова інформація :** https://github.com/scholokov/long-travel-2/wiki/2.-Travel.Structure

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_5](https://user-images.githubusercontent.com/109720075/203301206-209e33e4-f7eb-49b9-b581-8ea807177128.png)
![Screenshot_6](https://user-images.githubusercontent.com/109720075/203301867-dc717947-1e98-4c63-b6cd-373d5e71d526.png)

**Comment by scholokov** [comment]
fixed
