### ISSUE TITLE
20210510_stariy_solvin/ Під картою подорожі -блок "Дорога Київ - Старий Солотвін" -відсутня дата подорожі 

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1703]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210510_stariy_solvin/
2.Проскролити сторінку до фото прев'ю під картою подорожі
3.Звернути увагу на дату подорожі

**Фактичний результат:** Під картою подорожі -блок "Дорога Київ - Старий Солотвін" -відсутня дата  подорожі 
**Очікуваний результат:** Під картою подорожі -блок "Дорога Київ - Старий Солотвін" -присутня дата подорожі 

**Додаткова інформація :** https://github.com/scholokov/long-travel-2/wiki/2.-Travel.Structure

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_7](https://user-images.githubusercontent.com/109720075/203303495-2830d89d-dd5a-41e2-a7f4-be2508c7aebd.png)
![Screenshot_8](https://user-images.githubusercontent.com/109720075/203303504-9e46c113-2989-4e76-9634-dbd4af06861b.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 відсутня дата чого?)
