### ISSUE TITLE
20200725_26_piviha/Блок"Дорога Кременчук – пивиха 26.07.2020" - орфографічна  помилка 

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1713]
**Кроки відтворення:**

1.Відкрити сторінку https://test.long-travel.live/20200725_26_piviha/
2.Проскролити сторінку до блоку (Дорога Кременчук – пивиха)
3.Звернути увагу на назву гори
 
**Фактичний результат:** Назва гори(пивиха) написана з маленької літери- орфографічна  помилка 
**Очікуваний результат:** Назва гори(Пивиха) написана з великої  літери

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_28](https://user-images.githubusercontent.com/109720075/203944762-31250f64-59a2-44ae-8e05-7526b4e852f5.png)

**Comment by scholokov** [comment]
fixed
