### ISSUE TITLE
20200725_26_piviha/Блок"Дорога Пивиха – Кременчук" відсутня дата подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1714]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20200725_26_piviha/
2.Проскролити сторінку до блоку (Дорога Пивиха – Кременчук)
3.Звернути увагу на дату подорожі 

**Фактичний результат:** Відсутня дата подорожі в блокові (Дорога Пивиха – Кременчук)
**Очікуваний результат:** Присутня дата подорожі (Дорога Пивиха – Кременчук)

**Додаткова інформація :** https://github.com/scholokov/long-travel-2/wiki/2.-Travel.Structure

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_29](https://user-images.githubusercontent.com/109720075/204024471-127938d8-ae47-450f-90f8-db15579a350c.png)
![Screenshot_30](https://user-images.githubusercontent.com/109720075/204024480-700d732d-8b07-431b-a397-bd88cf744f00.png)
a

**Comment by scholokov** [comment]
fixed
