### ISSUE TITLE
20141102_10_Egypt_Hurghada/ Блок"Шоу 1000 и одна ночь Hurgada 03.11.2014"- мова контенту російська

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1715]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20141102_10_Egypt_Hurghada/
2.Проскролити сторінку до блоку"Шоу 1000 и одна ночь Hurgada 03.11.2014"
3.Звернути увагу на мову контенту

**Фактичний результат:** Мова контенту російська Назва блоку "Шоу 1000 и одна ночь Hurgada 03.11.2014"
**Очікуваний результат:**  Назва блоку "Шоу 1000 і одна ніч Hurgada 03.11.2014 "

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_33](https://user-images.githubusercontent.com/109720075/204035116-c35e8c37-78c7-4e2f-aca9-92ecd8f830fe.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 спираючись на спеціфікацію, давайте виправимо баг репорт https://github.com/scholokov/long-travel-2/wiki/1.2-Global.Language

**Comment by DmytroMarkulych** [comment]
@andry1729 
![image](https://user-images.githubusercontent.com/88647733/204086348-5f22fb79-a5e1-4973-bc84-e78956c47c4a.png)

**Comment by scholokov** [comment]
fixed
