### ISSUE TITLE
20141102_10_Egypt_Hurghada/ Блок"Шоу 1000 и одна ночь Hurgada 03.11.2014"- назва відео  з галереї на російській мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1716]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20141102_10_Egypt_Hurghada/
2.Проскролити сторінку до блоку"Шоу 1000 и одна ночь Hurgada 03.11.2014"
3.Звернути увагу на назву відео з блоку"Шоу 1000 и одна ночь Hurgada 03.11.2014"

**Фактичний результат:** Назва відео  з галереї на російській мові (2014.11.03 Egypt - Hurghada - Шоу 1000 и 1 ночь 01)
**Очікуваний результат:** Назва відео  з галереї (2014.11.03 Egypt - Hurghada - Шоу 1000 і одна ніч)

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_34](https://user-images.githubusercontent.com/109720075/204036001-79976df5-f2e9-4c93-90a8-1064fd157de8.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 давайте ще раз переглянемо специфікацію так виправимо баг репорт https://github.com/scholokov/long-travel-2/wiki/1.2-Global.Language

**Comment by DmytroMarkulych** [comment]
@andry1729 
![image](https://user-images.githubusercontent.com/88647733/204086439-8b388088-0821-4cd1-8830-ad170f89758c.png)

**Comment by scholokov** [comment]
fixed
