### ISSUE TITLE
20141102_10_Egypt_Hurghada/ Подорож"Дорога обратно 10.11.2014"- назва подорожі  на російській мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1717]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20141102_10_Egypt_Hurghada/
2.Проскролити сторінку до подорожі"Дорога обратно 10.11.2014"
3.Звернути увагу на назву  подорожі"Дорога обратно  10.11.2014"

**Фактичний результат:**  Назва подорожі  на російській мові "Дорога обратно  10.11.2014"
**Очікуваний результат:** Назва подорожі  "Дорога назад 10.11.2014"

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_35](https://user-images.githubusercontent.com/109720075/204053233-c4f685a2-1c0c-433c-af34-b75806ec8d36.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 давайте ще раз переглянемо специфікацію так виправимо баг репорт https://github.com/scholokov/long-travel-2/wiki/1.2-Global.Language

**Comment by DmytroMarkulych** [comment]
@andry1729 це не назва блоку, а насправді, це назва подорожі 
![image](https://user-images.githubusercontent.com/88647733/204086498-49e3826d-f335-438e-a690-32400d7e3b5b.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_89](https://user-images.githubusercontent.com/109720075/205030921-1765d96f-3dca-4104-9258-3eea02996028.png)

**Comment by andry1729** [comment]
без змін
![Screenshot_90](https://user-images.githubusercontent.com/109720075/205033920-8e0a4a72-b5a6-43bd-a0cb-5da594b50e21.png)
