### ISSUE TITLE
20160618_Mezhigorie/ Блок "Національний Парк Межигір’я Нові Петрівці, Київська обл., Україна 18.06.2016"-фото прев'ю під картою відсутнє

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1718]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20160618_Mezhigorie/
2.Проскролити сторінку до блоку "Національний Парк Межигір’я Нові Петрівці, Київська обл., Україна 18.06.2016"
3.Звернути увагу на фото прев'ю

**Фактичний результат:** Відсутнє фото прев'ю під картою
**Очікуваний результат:** Присутнє фото прев'ю під картою

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_36](https://user-images.githubusercontent.com/109720075/204054781-f8afb605-6691-4219-8b7a-0661de5aba55.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 якщо перейти по лінку що в кроках для вітворення то там превю присутнє)

**Comment by scholokov** [comment]
fixed
