### ISSUE TITLE
20160618_Mezhigorie/ Блок прев'ю під картою"Національний Парк Межигір’я Нові Петрівці, Київська обл., Україна 18.06.2016"- відсутній прапор України

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1719]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20160618_Mezhigorie/
2.Проскролити сторінку до блоку прев'ю під картою "Національний Парк Межигір’я Нові Петрівці, Київська обл., Україна 18.06.2016"
3.Звернути увагу на прапор у фото прев'ю

**Фактичний результат:** Відсутій прапор України у фото  прев'ю  блоку "Національний Парк Межигір’я Нові Петрівці, Київська обл., Україна 18.06.2016"
**Очікуваний результат:** Присутній прапор України у фото  прев'ю  блоку "Національний Парк Межигір’я Нові Петрівці, Київська обл., Україна 18.06.2016"

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_37](https://user-images.githubusercontent.com/109720075/204055249-63c23467-bba1-4d48-96fe-c0b1b305579e.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 
1. в баг репорті лінки відрізняються.
2. Вкажіть назву блоку в summary де відсутній прапор

**Comment by DmytroMarkulych** [comment]
@andry1729 назва блока - превю

**Comment by scholokov** [comment]
fixed
