### ISSUE TITLE
20160618_Mezhigorie/ Відео в блокові "Національний Парк Межигір’я Нові Петрівці, Київська обл., Україна 18.06.2016"-мова контенту російська

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1720]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20160618_Mezhigorie/
2.Проскролити сторінку до відео в  блокові "Національний Парк Межигір’я Нові Петрівці, Київська обл., Україна 18.06.2016"
3.Звернути увагу на мову в відео"2016.06.18 Межигорье 1"

**Фактичний результат:** Мова контенту російська(Межигорье 1)
**Очікуваний результат:** мова контенту Українська (Межигір’я 1)

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_38](https://user-images.githubusercontent.com/109720075/204055835-6b0aa3d5-a0ca-406c-9c3f-bd08f56cac73.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 зверніть увагу на лінк в кроках для відтворення

**Comment by scholokov** [comment]
fixed
