### ISSUE TITLE
20131019_Petrovtsi_Bitva_Za_Kiev/ Фото прев'ю під картою відсутнє

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1721]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20131019_Petrovtsi_Bitva_Za_Kiev/
2.Проскролити сторінку до фото  прев'ю під картою
3.Звернути увагу на фото прев'ю  під картою

**Фактичний результат:** Фото прев'ю під картою відсутнє
**Очікуваний результат:** Фото прев'ю під картою присутнє

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_39](https://user-images.githubusercontent.com/109720075/204056312-d7108da2-2406-4e96-83b6-881e1557b519.png)

**Comment by scholokov** [comment]
fixed
