### ISSUE TITLE
20170805_20_Odessa/  Відсутній прапор України в  прев'ю під картою подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1722]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20170805_20_Odessa/
2.Проскролити сторінку до фото прев'ю під картою подорожі
3.Звернути увагу на прапор України в  прев'ю під картою подорожі

**Фактичний результат:** Відсутній прапор України в  прев'ю під картою подорожі
**Очікуваний результат:** Присутній прапор України в  прев'ю під картою подорожі

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_40](https://user-images.githubusercontent.com/109720075/204057334-705a6b08-9363-419b-81fa-672cb7205704.png)

**Comment by scholokov** [comment]
fixed
