### ISSUE TITLE
20170805_20_Odessa/ Блок"Дорога Київ – Одеса 05.08.2017"- присутня попередня назва подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1723]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20170805_20_Odessa/
2.Проскролити сторінку до блоку "Дорога Київ – Одеса 05.08.2017"
3.Звернути увагу на назву подорожі під блоком "Дорога Київ – Одеса 05.08.2017"
 
**Фактичний результат:** Під блоком присутня попередня назва подорожі
**Очікуваний результат:** Під блоком відсутня попередня назва подорожі

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_41](https://user-images.githubusercontent.com/109720075/204058080-296a900b-f051-4430-8dfa-569105a84d3b.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 в summary вкажіть назву саме назву блоку замінивши фразу додавши до фрази під блоком

**Comment by scholokov** [comment]
fixed
