### ISSUE TITLE
20170805_20_Odessa/ Прев'ю"Одеса Одеська Область 05-19.08.2017"-відсутній прапор України в фото прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1724]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20170805_20_Odessa/
2.Проскролити сторінку до прев'ю "Одеса Одеська Область 05-19.08.2017"
3.Звернути увагу на прапор України в прев'ю  "Одеса Одеська Область 05-19.08.2017"

**Фактичний результат:** Відсутній прапор України в фото прев'ю  "Одеса Одеська Область 05-19.08.2017"
**Очікуваний результат:** Присутній прапор України в  фото прев'ю   "Одеса Одеська Область 05-19.08.2017"

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_42](https://user-images.githubusercontent.com/109720075/204058452-d4cc5431-a59c-48aa-a4aa-b7fd5404fb43.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 вкажіть назву елементу в якому відсутній прапор

**Comment by DmytroMarkulych** [comment]
@andry1729 даний блок називається превю

**Comment by scholokov** [comment]
fixed
