### ISSUE TITLE
20170805_20_Odessa/ Прев'ю"Одеса Одеська Область 05-19.08.2017"-під прев'ю присутня попередня назва подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1725]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20170805_20_Odessa/
2.Проскролити сторінку до прев'ю "Одеса Одеська Область 05-19.08.2017"
3.Звернути увагу на назву подорожі під прев'ю "Одеса Одеська Область 05-19.08.2017"

**Фактичний результат:** Під прев'ю присутня попередня назва подорожі
**Очікуваний результат:** Під прев'ю відсутня попередня назва подорожі

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_43](https://user-images.githubusercontent.com/109720075/204058632-dcc0a3e5-a146-4942-93ee-b2f5178a47c0.png)

**Comment by DmytroMarkulych** [comment]
@andry1729  в summary давайте додамо саме назву блоку під яким присутня назва подорожі

**Comment by scholokov** [comment]
fixed
