### ISSUE TITLE
20170805_20_Odessa/ Прев'ю"Пляж Одеса, Одеська Область 05-19.08.2017"-під прев'ю присутня попередня назва подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1726]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20170805_20_Odessa/
2.Проскролити сторінку до прев'ю "Пляж Одеса, Одеська Область 05-19.08.2017"
3.Звернути увагу на назву подорожі під прев'ю "Пляж Одеса, Одеська Область 05-19.08.2017"

**Фактичний результат:** Під прев'ю присутня попередня назва подорожі
**Очікуваний результат:** Під прев'ю відсутня попередня назва подорожі

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_46](https://user-images.githubusercontent.com/109720075/204087818-a44fa477-4a6c-4baa-9604-9b271325bc7e.png)

**Comment by scholokov** [comment]
fixed
