### ISSUE TITLE
20170805_20_Odessa/ Відсутній прапор України в прев'ю "Пляж Одеса, Одеська Область 05-19.08.2017"

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1727]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20170805_20_Odessa/
2.Проскролити сторінку до фото прев'ю "Пляж Одеса, Одеська Область 05-19.08.2017"
3.Звернути увагу на прапор України в прев'ю "Пляж Одеса, Одеська Область 05-19.08.2017"

**Фактичний результат:** Відсутній прапор України в прев'ю 
**Очікуваний результат:** Присутній прапор України в прев'ю 

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_48](https://user-images.githubusercontent.com/109720075/204088205-deda1054-6099-4fc8-b696-978fcd698b4d.png)

**Comment by scholokov** [comment]
fixed
