### ISSUE TITLE
20170805_20_Odessa/ Відсутній прапор України в прев'ю "Дорога Одеса – Київ 20.08.2017"

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1728]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20170805_20_Odessa/
2.Проскролити сторінку до фото прев'ю "Дорога Одеса – Київ 20.08.2017"
3.Звернути увагу на прапор України в прев'ю "Дорога Одеса – Київ 20.08.2017"

**Фактичний результат:** Відсутній прапор України в прев'ю
**Очікуваний результат:** Присутній прапор України в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_49](https://user-images.githubusercontent.com/109720075/204088420-418c0ac5-dfab-4ca0-8bd3-34c957217d83.png)

**Comment by scholokov** [comment]
fixed
