### ISSUE TITLE
20170805_20_Odessa/ Прев'ю"Дорога Одеса – Київ 20.08.2017"-під прев'ю присутня попередня назва подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1729]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20170805_20_Odessa/
2.Проскролити сторінку до прев'ю "Дорога Одеса – Київ 20.08.2017"
3.Звернути увагу на назву подорожі під прев'ю "Дорога Одеса – Київ 20.08.2017"

**Фактичний результат:** Під прев'ю присутня попередня назва подорожі
**Очікуваний результат:** Під прев'ю відсутня попередня назва подорожі

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_50](https://user-images.githubusercontent.com/109720075/204088548-a57fa009-35a4-42f3-a035-c2253de4965b.png)

**Comment by scholokov** [comment]
fixed
