### ISSUE TITLE
20130526_Vishgorod/ Відсутній прапор України в прев'ю "Вишгород Київська область 26.05.2013"

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1730]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20130526_Vishgorod/
2.Проскролити сторінку до фото прев'ю "Вишгород Київська область 26.05.2013"
3.Звернути увагу на прапор України в прев'ю "Вишгород Київська область 26.05.2013"

**Фактичний результат:** Відсутній прапор України в прев'ю
**Очікуваний результат:** Присутній прапор України в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_51](https://user-images.githubusercontent.com/109720075/204088822-2dde6996-3177-4ee7-9508-b5283bf82c23.png)

**Comment by scholokov** [comment]
fixed
