### ISSUE TITLE
20150919_Kiev_Aviation_Museum/ Блок"Державний музей авіації Київ, Україна 19.09.2015"- назва відео з галереї на російській мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1731]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150919_Kiev_Aviation_Museum/
2.Проскролити сторінку до відео з  блоку"Державний музей авіації Київ, Україна 19.09.2015"
3.Звернути увагу на назву відео з блоку

**Фактичний результат:** Назва відео з галереї на російській мові (2015.09.19 Киев - Выставка самолетов 01)
**Очікуваний результат:** Назва відео з галереї (2015.09.19 Київ - Виставка літаків 01)

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_52](https://user-images.githubusercontent.com/109720075/204089181-61f9bf4d-33f6-44fd-ae18-97328cfa4792.png)

**Comment by scholokov** [comment]
fixed
