### ISSUE TITLE
20150919_Kiev_Aviation_Museum/ Відсутній прапор України в прев'ю "Державний музей авіації Київ, Україна 19.09.2015"

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1732]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150919_Kiev_Aviation_Museum/
2.Проскролити сторінку до фото прев'ю "Державний музей авіації Київ, Україна 19.09.2015"
3.Звернути увагу на прапор України в прев'ю "Державний музей авіації Київ, Україна 19.09.2015"

**Фактичний результат:** Відсутній прапор України в прев'ю
**Очікуваний результат:** Присутній прапор України в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_53](https://user-images.githubusercontent.com/109720075/204089354-d98cb148-b793-4701-a10c-400149971358.png)

**Comment by scholokov** [comment]
fixed
