### ISSUE TITLE
20220124_0128_netherlands/ Прев'ю над картою"24-28.01.2022 Eindhoven – Den Haag – Amsterdam – Eindhoven "-під прев'ю присутня попередня назва подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1734]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2.Звернути увагу на назву подорожі під прев'ю "24-28.01.2022 Eindhoven – Den Haag – Amsterdam – Eindhoven"

**Фактичний результат:** Під прев'ю присутня попередня назва подорожі
**Очікуваний результат:** Під прев'ю відсутня попередня назва подорожі

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_54](https://user-images.githubusercontent.com/109720075/204754952-87f1163e-a3c3-4b51-9e06-c8af32893cd9.png)

**Comment by scholokov** [comment]
fixed
