### ISSUE TITLE
20220124_0128_netherlands/Прев'ю над картою"24-28.01.2022 Eindhoven – Den Haag – Amsterdam – Eindhoven "-дублюється  дата подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1735]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2.Звернути увагу на дублювання дати  подорожі в прев'ю "24-28.01.2022 Eindhoven – Den Haag – Amsterdam – Eindhoven"

**Фактичний результат:** Дублюється  дата подорожі
**Очікуваний результат:** В прев'ю відсутня попередня дата подорожі

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_55](https://user-images.githubusercontent.com/109720075/204756898-0fc2293b-3cf8-4ea9-900b-e324e2c2089e.png)

**Comment by scholokov** [comment]
всі назви подорожей прописані у вимогах
краще ссилатися на той документ

**Comment by scholokov** [comment]
дата прибрана
