### ISSUE TITLE
20220124_0128_netherlands/Опис "Подготовка" під картою-мова контенту російською мовою

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1736]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2. Проскролити сторінку до опису під картою
2.Звернути увагу на мову контенту під картою

**Фактичний результат:** Мова контенту російською мовою
**Очікуваний результат:** Мова контенту українською мовою

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_56](https://user-images.githubusercontent.com/109720075/204759453-d3984fb3-8c42-4d1f-8530-e38d0635c5fb.png)
![Screenshot_57](https://user-images.githubusercontent.com/109720075/204759457-eff0d223-cb64-4f39-ba23-6e969f66cce9.png)

**Comment by scholokov** [comment]
fixed
