### ISSUE TITLE
20220124_0128_netherlands/Опис "Подготовка" під картою-"Дорога Киев – Eindhoven 24.01.2022"-присутні два прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1737]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2. Проскролити сторінку до опису під картою
2.Звернути увагу на назву прев'ю"Дорога Киев – Eindhoven 24.01.2022"

**Фактичний результат:**Присутні два прев'ю
**Очікуваний результат:** Присутні одне прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_59](https://user-images.githubusercontent.com/109720075/204764121-83a4e135-75ed-4e3d-9257-338e40786143.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 краще вказати що пристуні 2 превю, ніж використовувати слово дублювання

**Comment by scholokov** [comment]
fixed
