### ISSUE TITLE
20220124_0128_netherlands/Прев'ю"Дорога Киев – Eindhoven 24.01.2022"- опис подорожі знаходиться над прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1738]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2. Проскролити сторінку до прев'ю"Дорога Киев – Eindhoven 24.01.2022"
2.Звернути увагу на опис над прев'ю"Дорога Киев – Eindhoven 24.01.2022"

**Фактичний результат:** Опис подорожі знаходиться над прев'ю
**Очікуваний результат:** Опис подорожі знаходиться під прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_60](https://user-images.githubusercontent.com/109720075/204765664-34d71468-eddb-4e46-8da3-a0eebcf7c449.png)

**Comment by scholokov** [comment]
fixed
