### ISSUE TITLE
20220124_0128_netherlands/ Прев'ю"Дорога Киев – Eindhoven 24.01.2022"-Киев написано на російській мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1740]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2.Проскролити сторінку до прев'ю"Дорога Киев – Eindhoven 24.01.2022"
3.Звернути увагу на назву  прев'ю

**Фактичний результат:** Киев написано на російській мові
**Очікуваний результат:** Київ  написано на українській мові

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_62](https://user-images.githubusercontent.com/109720075/204768408-3c310b75-077c-4537-bd4f-93740409f4ba.png)

**Comment by scholokov** [comment]
fixed
