### ISSUE TITLE
20220124_0128_netherlands/ Прев'ю"Eindhoven – Car Rental 24.01.2022"-відсутнє фото  прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1741]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2.Проскролити сторінку до прев'ю"Eindhoven – Car Rental 24.01.2022"
3.Звернути увагу на фото прев'ю

**Фактичний результат:** Фото прев'ю відсутнє
**Очікуваний результат:** Фото прев'ю присутнє

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_63](https://user-images.githubusercontent.com/109720075/204770289-1ee76a79-40d5-4d3f-83bb-80d0722faaa2.png)

**Comment by scholokov** [comment]
fixed
