### ISSUE TITLE
20220124_0128_netherlands/ Прев'ю"Eindhoven – Car Rental 24.01.2022"-відсутній прапор Нідерландів в  фото прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1742]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2.Проскролити сторінку до прев'ю"Eindhoven – Car Rental 24.01.2022"
3.Звернути увагу на прапор Нідерландів в   фото прев'ю

**Фактичний результат:** Відсутній прапор Нідерландів в  фото прев'ю
**Очікуваний результат:** Присутній прапор Нідерландів в  фото прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_64](https://user-images.githubusercontent.com/109720075/204770662-df39b90c-8777-42f6-9f7d-d98ba5cc3989.png)

**Comment by scholokov** [comment]
fixed
