### ISSUE TITLE
20220124_0128_netherlands/ Прев'ю"Отель: Appt City Centre Royal Garden Den Haag 24-26.01.2022"-відсутнє фото прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1745]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2.Проскролити сторінку до прев'ю"Отель: Appt City Centre Royal Garden Den Haag 24-26.01.2022"
3.Звернути увагу на фото прев'ю

**Фактичний результат:** Фото прев'ю відсутнє
**Очікуваний результат:** Фото прев'ю присутнє

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_67](https://user-images.githubusercontent.com/109720075/204773067-eaef245c-beeb-4ba6-a483-ce4c2de6f341.png)

**Comment by scholokov** [comment]
fixed
