### ISSUE TITLE
20220124_0128_netherlands/ Прев'ю"Отель: Appt City Centre Royal Garden Den Haag 24-26.01.2022"-слово "Отель" російською мовою

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1746]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2.Проскролити сторінку до прев'ю"Отель: Appt City Centre Royal Garden Den Haag 24-26.01.2022"
3.Звернути увагу на слово "Отель"

**Фактичний результат:** Слово "Отель" російською мовою
**Очікуваний результат:** Назва  прев'ю "Готель: Appt City Centre Royal Garden Den Haag 24-26.01.2022"

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_68](https://user-images.githubusercontent.com/109720075/204821656-6c207476-9ebb-4223-80e6-d475c9a2e365.png)

**Comment by scholokov** [comment]
fixed
