### ISSUE TITLE
20220124_0128_netherlands/ В прев'ю подорожі" Den Haag 24-26.01.2022"-відсутній прапор Нідерландів в правому кутку прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1748]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2.Проскролити сторінку до прев'ю" Den Haag 24-26.01.2022"
3.Звернути увагу на прапор Нідерландів в  прев'ю

**Фактичний результат:** Відсутній прапор Нідерландів в  прев'ю
**Очікуваний результат:** Присутній прапор Нідерландів в  прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_70](https://user-images.githubusercontent.com/109720075/204823120-92666ed5-68d6-47dc-8ae4-6c2d3546da7b.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 прапор є частиною превю як і фото, тому це два різні елементи які складають превю

**Comment by DmytroMarkulych** [comment]
@andry1729 давайте перефразуємо баг репорт щоб зробити його більш унікальним

**Comment by scholokov** [comment]
fixed
