### ISSUE TITLE
20220124_0128_netherlands/ В подорожі"De Pier, North Sea, Den Haag 26.01.2022" -відсутнє фото в блокові прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1749]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2.Проскролити сторінку до прев'ю"Отель: De Pier, North Sea.Den Haag 24-26.01.2022"
3.Звернути увагу на фото прев'ю

**Фактичний результат:**Відсутнє фото в блокові прев'ю
**Очікуваний результат:** Присутнє фото в блокові прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_71](https://user-images.githubusercontent.com/109720075/204824312-d4c8ce6e-382c-417f-8419-541b73426ae6.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 Давайте перефразуємо і зробимо унікальним превю, до прикладу можна: в подорожі (назва подорожі) відсутнє фото в блокові превю

**Comment by scholokov** [comment]
fixed
