### ISSUE TITLE
20220124_0128_netherlands/ Прев'ю"De Pier, North Sea, Den Haag 26.01.2022"-відсутній прапор Нідерландів в  прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1750]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2.Проскролити сторінку до прев'ю" De Pier, North Sea, Den Haag 26.01.2022"
3.Звернути увагу на прапор Нідерландів в  прев'ю

**Фактичний результат:** Відсутній прапор Нідерландів в  прев'ю 
**Очікуваний результат:** Присутній прапор Нідерландів в  прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_72](https://user-images.githubusercontent.com/109720075/204825086-0afc8df5-7365-43bc-ab88-64ba692ab840.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 прапорт та фото в превю це два окремі елементи які в сумі роблять превю

**Comment by scholokov** [comment]
fixed
