### ISSUE TITLE
20220124_0128_netherlands/ Подорож"Amsterdam 26-27.01.2022"-відсутнє фото  в блокові прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1751]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2.Проскролити сторінку до прев'ю"Amsterdam 26-27.01.2022"
3.Звернути увагу на фото прев'ю

**Фактичний результат:** Фото прев'ю відсутнє
**Очікуваний результат:** Фото прев'ю присутнє

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_73](https://user-images.githubusercontent.com/109720075/204825885-ce42d76e-d692-4d23-bc1e-9e0bc148b15d.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 давайте спробуємо написати більш унікальне summary

**Comment by scholokov** [comment]
fixed
