### ISSUE TITLE
20220124_0128_netherlands/ Прев'ю"Amsterdam 26-27.01.2022"-відсутній прапор Нідерландів в  прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1752]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2.Проскролити сторінку до прев'ю"Amsterdam 26-27.01.2022"
3.Звернути увагу на прапор Нідерландів в  прев'ю

**Фактичний результат:** Відсутній прапор Нідерландів в  прев'ю
**Очікуваний результат:** Присутній прапор Нідерландів в  прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_74](https://user-images.githubusercontent.com/109720075/204828478-3c11c1d3-5d40-41b1-b09b-046afcbbd2bd.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 фото та прапор це 2 окремі елементи які є частинами превю

**Comment by scholokov** [comment]
fixed
