### ISSUE TITLE
20220124_0128_netherlands/ Прев'ю"Restraurant: Puncake Burger ,Amsterdam 26.01.2022"-відсутнє фото прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1753]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2.Проскролити сторінку до прев'ю"Restraurant: Puncake Burger ,Amsterdam 26.01.2022"
3.Звернути увагу на фото прев'ю

**Фактичний результат:** Фото прев'ю відсутнє
**Очікуваний результат:** Фото прев'ю присутнє

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_75](https://user-images.githubusercontent.com/109720075/204831535-8a495aa8-d047-4a75-bcf3-bd43fa09637f.png)

**Comment by scholokov** [comment]
fixed
