### ISSUE TITLE
20220124_0128_netherlands/ Прев'ю"Restraurant: Puncake Burger ,Amsterdam 26.01.2022"-відсутній прапор Нідерландів в  прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1754]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2.Проскролити сторінку до прев'ю"Restraurant: Puncake Burger ,Amsterdam 26.01.2022"
3.Звернути увагу на прапор Нідерландів в  прев'ю

**Фактичний результат:** Відсутній прапор Нідерландів в  прев'ю
**Очікуваний результат:** Присутній прапор Нідерландів в  прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_76](https://user-images.githubusercontent.com/109720075/204831927-8afc48c7-6ac7-4762-9012-3d42b3dcdfb9.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 фото та прапор це 2 окремі елементи які є частинами превю

**Comment by scholokov** [comment]
fixed
