### ISSUE TITLE
20220124_0128_netherlands/ Прев'ю "Отель: Olympic Hotel Amsterdam 26-28.01.2022 "-над прев'ю присутня попередня назва подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1755]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2.Проскролити сторінку до  прев'ю "Отель: Olympic Hotel Amsterdam 26-28.01.2022"
3.Звернути увагу на назву подорожі над прев'ю "Отель: Olympic Hotel Amsterdam 26-28.01.2022"

**Фактичний результат:** Над прев'ю присутня попередня назва подорожі
**Очікуваний результат:** Над прев'ю відсутня попередня назва подорожі

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_77](https://user-images.githubusercontent.com/109720075/204833578-89e9e037-3d91-45b8-b169-11f470093cc0.png)

**Comment by scholokov** [comment]
fixed
