### ISSUE TITLE
20220124_0128_netherlands/ Прев'ю"Отель: Olympic Hotel Amsterdam 26-28.01.2022"-відсутнє фото прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1756]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2.Проскролити сторінку до прев'ю"Отель: Olympic Hotel Amsterdam 26-28.01.2022"
3.Звернути увагу на фото прев'ю

**Фактичний результат:** Фото прев'ю відсутнє
**Очікуваний результат:** Фото прев'ю присутнє

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_78](https://user-images.githubusercontent.com/109720075/204835834-1aba0d08-3894-47d1-8e58-b9d99e1622e1.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 давайте зробимо більш унікальним summary
