### ISSUE TITLE
20220124_0128_netherlands/ Прев'ю"Отель: Olympic Hotel Amsterdam 26-28.01.2022"-відсутній прапор Нідерландів в  прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1757]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2.Проскролити сторінку до прев'ю" Отель: Olympic Hotel Amsterdam 26-28.01.2022"
3.Звернути увагу на прапор Нідерландів в  прев'ю

**Фактичний результат:** Відсутній прапор Нідерландів в  прев'ю
**Очікуваний результат:** Присутній прапор Нідерландів в  прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_79](https://user-images.githubusercontent.com/109720075/204836368-86beaba9-4bfe-40ef-b442-66d83b842775.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 фото та прапор це 2 окремі елементи які є частинами превю

**Comment by scholokov** [comment]
fixed
