### ISSUE TITLE
20220124_0128_netherlands/ Прев'ю"Отель: Olympic Hotel Amsterdam 26-28.01.2022"-слово "Отель" російською мовою

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1758]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2.Проскролити сторінку до прев'ю"Отель:Olympic Hotel Amsterdam 26-28.01.2022"
3.Звернути увагу на слово "Отель"

**Фактичний результат:** Слово "Отель" російською мовою
**Очікуваний результат:** Назва прев'ю "Готель: Olympic Hotel Amsterdam 26-28.01.2022"

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_80](https://user-images.githubusercontent.com/109720075/204837125-016b7411-62fe-428e-a646-fb7964a89122.png)

**Comment by scholokov** [comment]
fixed
