### ISSUE TITLE
20220124_0128_netherlands/ Прев'ю"  Eindhoven 28.01.2022"-відсутнє фото прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1759]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2.Проскролити сторінку до прев'ю" Eindhoven 28.01.2022"
3.Звернути увагу на фото прев'ю

**Фактичний результат:** Фото прев'ю відсутнє
**Очікуваний результат:** Фото прев'ю присутнє

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_81](https://user-images.githubusercontent.com/109720075/204840522-9eb46d0f-04c1-4fb8-9c2e-7a695ca76bfc.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 давайте зробимо більш унікальне summary
