### ISSUE TITLE
20220124_0128_netherlands/Опис прев'ю "Eindhoven 28.01.2022"-мова контенту російською мовою

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1761]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2. Проскролити сторінку до прев'ю "Eindhoven 28.01.2022"
2.Звернути увагу на мову контенту під картою

**Фактичний результат:** Мова контенту російською мовою
**Очікуваний результат:** Мова контенту українською мовою

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_83](https://user-images.githubusercontent.com/109720075/204841916-5cae7717-5161-4487-b592-ca21b41a801d.png)

**Comment by scholokov** [comment]
fixed
