### ISSUE TITLE
20220124_0128_netherlands/ Прев'ю"Дорога Eindhoven- Киев 28.01.2022"-відсутнє фото прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1762]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2.Проскролити сторінку до прев'ю" Дорога Eindhoven- Киев 28.01.2022"
3.Звернути увагу на фото прев'ю

**Фактичний результат:** Фото прев'ю відсутнє
**Очікуваний результат:** Фото прев'ю присутнє

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_84](https://user-images.githubusercontent.com/109720075/204843070-1297a5b7-bc4e-466a-8197-73ae4da88c2c.png)

**Comment by scholokov** [comment]
fixed
