### ISSUE TITLE
20220124_0128_netherlands/ Прев'ю"Дорога Eindhoven- Киев 28.01.2022"-відсутні прапори Нідерландів та України в фото прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1763]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2.Проскролити сторінку до прев'ю"Дорога Eindhoven- Киев 28.01.2022"
3.Звернути увагу на прапори Нідерландів та України в фото прев'ю

**Фактичний результат:** Відсутні прапори Нідерландів та України в фото прев'ю
**Очікуваний результат:** Присутні прапори Нідерландів та України в фото прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_86](https://user-images.githubusercontent.com/109720075/204843849-b839d96f-a41a-46e8-8622-205571bba1d8.png)

**Comment by scholokov** [comment]
fixed
