### ISSUE TITLE
20220124_0128_netherlands/ Прев'ю"Дорога Eindhoven- Киев 28.01.2022"-слово "Киев" російською мовою

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1764]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2.Проскролити сторінку до прев'ю"Дорога Eindhoven- Киев 28.01.2022"
3.Звернути увагу на слово "Киев"

**Фактичний результат:** Слово "Киев" російською мовою
**Очікуваний результат:** Назва прев'ю "Дорога Eindhoven- Київ 28.01.2022"

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_87](https://user-images.githubusercontent.com/109720075/204844959-e2f16296-66cc-48d5-8c43-37de50c416fd.png)

**Comment by scholokov** [comment]
fixed
