### ISSUE TITLE
20220124_0128_netherlands/Опис під галереєю прев'ю"Дорога Eindhoven- Киев 28.01.2022"- мова контенту російська

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1765]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2.Проскролити сторінку до опису під галереєю прев'ю" Дорога Eindhoven- Киев 28.01.2022"
3.Звернути увагу на мову контенту

**Фактичний результат:** Мова контенту російська
**Очікуваний результат:** Мова контенту українська

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_88](https://user-images.githubusercontent.com/109720075/204846083-c7ce5c19-6267-4840-8579-3359ba36e948.png)

**Comment by scholokov** [comment]
fixed
