### ISSUE TITLE
20220124_0128_netherlands/Опис прев'ю "Eindhoven 28.01.2022"- слова білого кольору на білому фоні

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1766]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2. Проскролити сторінку до прев'ю "Eindhoven 28.01.2022"
2.Звернути увагу на опис  прев'ю

**Фактичний результат:** Слова білого кольору на білому фоні
**Очікуваний результат:** Слова білого кольору на загальному темному фоні

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_92](https://user-images.githubusercontent.com/109720075/205035901-0191f5a5-9628-4c37-80e3-a98251784b11.png)

**Comment by scholokov** [comment]
fixed
