### ISSUE TITLE
20201010_11_brech/ Блок прев'ю"20201010_11_Бречь_Чернігівська область_Україна"- присутій id в назві подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1767]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20201010_11_brech/
2.Звернути увагу на назву подорожі в прев'ю

**Фактичний результат:** Присутій id в назві подорожі
**Очікуваний результат:** Відсутій id в назві подорожі. Назва подорожі-Бреч_Чернігівська область_Україна

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_93](https://user-images.githubusercontent.com/109720075/205044670-3cf2829c-8d62-4de7-a209-4218d675093a.png)

**Comment by scholokov** [comment]
fixed
