### ISSUE TITLE
20201010_11_brech/ Блок прев'ю"20201010_11_Бречь_Чернігівська область_Україна"-  дата подорожі знаходиться під прев'ю 

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1768]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20201010_11_brech/
2.Звернути увагу на дату подорожі в прев'ю

**Фактичний результат:** Дата подорожі знаходиться під прев'ю 
**Очікуваний результат:** Дата подорожі знаходиться в прев'ю 

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_94](https://user-images.githubusercontent.com/109720075/205045679-b4a5484f-4ca6-47e6-8d6d-4c8fd98efaf0.png)

**Comment by scholokov** [comment]
fixed
