### ISSUE TITLE
20201010_11_brech/ Блок прев'ю"20201010_11_Бречь_Чернігівська область_Україна"- фото прев'ю наполовину затемнене

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1769]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20201010_11_brech/
2.Звернути увагу на фото прев'ю

**Фактичний результат:** Фото прев'ю наполовину затемнене
**Очікуваний результат:** Фото прев'ю чітке

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_95](https://user-images.githubusercontent.com/109720075/205046965-26bf669a-5271-4694-b642-b99eb596c741.png)
![Screenshot_96](https://user-images.githubusercontent.com/109720075/205046974-e40ac31a-1a81-4d39-a82f-06ffeb7e76c2.png)
a

**Comment by scholokov** [comment]
fixed
