### ISSUE TITLE
20201010_11_brech/ Блок прев'ю"Дорога Київ -Бреч"- відсутнє фото прев'ю подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1770]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20201010_11_brech/
2.Проскролити сторінку до прев'ю подорожі "Дорога Київ -Бреч"
3.Звернути увагу на фото прев'ю

**Фактичний результат:** Фото прев'ю відсутнє
**Очікуваний результат:** Фото прев'ю присутнє

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_97](https://user-images.githubusercontent.com/109720075/205048518-4756748b-007b-440c-aefb-d413cc7bdf6a.png)

**Comment by scholokov** [comment]
fixed
