### ISSUE TITLE
20201010_11_brech/ Блок прев'ю"Дорога Київ -Бреч"- відсутній прапор України в прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1771]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20201010_11_brech/
2.Проскролити сторінку до прев'ю"Дорога Київ -Бреч"
3.Звернути увагу на прапор України в прев'ю

**Фактичний результат:** Відсутній прапор України в прев'ю
**Очікуваний результат:** Присутній прапор України в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_98](https://user-images.githubusercontent.com/109720075/205049732-c4ad7feb-a3f0-47de-9165-250a5f188226.png)

**Comment by scholokov** [comment]
fixed
