### ISSUE TITLE
20201010_11_brech/ Блок прев'ю"Дорога Київ -Бреч"- відсутня дата подорожі  в прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1772]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20201010_11_brech/
2.Проскролити сторінку до прев'ю"Дорога Київ -Бреч"
3.Звернути увагу на дату подорожі в прев'ю

**Фактичний результат:** Відсутня дата подорожі  в прев'ю
**Очікуваний результат:** Присутня дата подорожі  в прев'ю

**Додаткова інормація:** https://github.com/scholokov/long-travel-2/wiki/2.-Travel.Structure

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_99](https://user-images.githubusercontent.com/109720075/205050616-e5fa6229-32cc-4709-9f31-b2a7c783a065.png)
![Screenshot_100](https://user-images.githubusercontent.com/109720075/205050624-ab07c956-51b1-4b9f-9614-4f5e807fcdfe.png)

**Comment by scholokov** [comment]
fixed
