### ISSUE TITLE
20201010_11_brech/ Блок прев'ю"Brech Resort & SPA"- відсутнє фото прев'ю подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1773]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20201010_11_brech/
2.Проскролити сторінку до прев'ю подорожі "Brech Resort & SPA"
3.Звернути увагу на фото прев'ю

**Фактичний результат:** Фото прев'ю відсутнє
**Очікуваний результат:** Фото прев'ю присутнє

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_101](https://user-images.githubusercontent.com/109720075/205051473-5d6eff76-b05b-4f6e-9cae-99af076ca844.png)

**Comment by scholokov** [comment]
fixed
