### ISSUE TITLE
20201010_11_brech/ Блок прев'ю"Brech Resort & SPA"- відсутній прапор України в прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1774]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20201010_11_brech/
2.Проскролити сторінку до прев'ю"Brech Resort & SPA"
3.Звернути увагу на прапор України в прев'ю

**Фактичний результат:** Відсутній прапор України в прев'ю
**Очікуваний результат:** Присутній прапор України в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_102](https://user-images.githubusercontent.com/109720075/205052085-97a23603-f7c8-4b5f-8853-779eb55398fa.png)

**Comment by scholokov** [comment]
fixed
