### ISSUE TITLE
20201010_11_brech/ Блок прев'ю"Brech Resort & SPA"- відсутня дата подорожі в прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1775]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20201010_11_brech/
2.Проскролити сторінку до прев'ю"Brech Resort & SPA"
3.Звернути увагу на дату подорожі в прев'ю

**Фактичний результат:** Відсутня дата подорожі в прев'ю
**Очікуваний результат:** Присутня дата подорожі в прев'ю

**Додаткова інормація:** https://github.com/scholokov/long-travel-2/wiki/2.-Travel.Structure

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_100](https://user-images.githubusercontent.com/109720075/205052459-b8ca1bcb-402e-426e-8f2e-2b7dc543d2b3.png)
![Screenshot_103](https://user-images.githubusercontent.com/109720075/205052466-d9196cdd-4efc-4bf8-a979-5f727e4475c4.png)

**Comment by scholokov** [comment]
fixed
