### ISSUE TITLE
20201010_11_brech/ В прев'ю подорожі"Бречь, Чернігівська область, Україна  10-11.10.2020"- відсутнє фото прев'ю 

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1776]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20201010_11_brech/
2.Проскролити сторінку до прев'ю подорожі "Бречь, Чернігівська область, Україна  10-11.10.2020"
3.Звернути увагу на фото прев'ю

**Фактичний результат:** Фото прев'ю відсутнє
**Очікуваний результат:** Фото прев'ю присутнє

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_104](https://user-images.githubusercontent.com/109720075/205053508-9b1c84a3-349c-450f-85ac-ccc93ed2c96f.png)

**Comment by scholokov** [comment]
fixed
