### ISSUE TITLE
20201010_11_brech/ В прев'ю подорожі"Бречь, Чернігівська область, Україна 10-11.10.2020"- відсутній прапор України в правому кутку в прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1777]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20201010_11_brech/
2.Проскролити сторінку до прев'ю"Бречь, Чернігівська область, Україна 10-11.10.2020"
3.Звернути увагу на прапор України в прев'ю

**Фактичний результат:** Відсутній прапор України в прев'ю
**Очікуваний результат:** Присутній прапор України в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_105](https://user-images.githubusercontent.com/109720075/205053841-7ebb90e6-f051-4965-8dba-5368cbd88693.png)

**Comment by scholokov** [comment]
fixed
