### ISSUE TITLE
20201010_11_brech/ Блок прев'ю"Бречь, Чернігівська область, Україна 10-11.10.2020"- "Бречь" на російській мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1778]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20201010_11_brech/
2.Проскролити сторінку до прев'ю"Бречь, Чернігівська область, Україна 10-11.10.2020"
3.Звернути увагу на подорожі в прев'ю

**Фактичний результат:** "Бречь" на російській мові
**Очікуваний результат:** Назва подорожі в прев'ю- Бреч, Чернігівська область, Україна

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_106](https://user-images.githubusercontent.com/109720075/205055021-1842bde0-f4f1-4d25-987f-495d51ac2810.png)
![Screenshot_107](https://user-images.githubusercontent.com/109720075/205055041-9952ed68-0ff1-4fc9-8e00-f60a79ad83fd.png)

**Comment by scholokov** [comment]
fixed
