### ISSUE TITLE
20201010_11_brech/ Блок прев'ю"Дорога Бречь – Київ"- відсутнє фото прев'ю подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1779]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20201010_11_brech/
2.Проскролити сторінку до прев'ю подорожі "Дорога Бречь – Київ"
3.Звернути увагу на фото прев'ю

**Фактичний результат:** Фото прев'ю відсутнє
**Очікуваний результат:** Фото прев'ю присутнє

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_108](https://user-images.githubusercontent.com/109720075/205055541-700b1c7f-aa5d-4880-8af6-ae404da34c3d.png)

**Comment by scholokov** [comment]
fixed
