### ISSUE TITLE
20201010_11_brech/ Блок прев'ю"Дорога Бречь – Київ"- відсутній прапор України в прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1780]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20201010_11_brech/
2.Проскролити сторінку до прев'ю"Дорога Бречь – Київ"
3.Звернути увагу на прапор України в прев'ю

**Фактичний результат:** Відсутній прапор України в прев'ю
**Очікуваний результат:** Присутній прапор України в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_109](https://user-images.githubusercontent.com/109720075/205056067-7fc9905a-467e-4c29-b591-0e94d1c37f75.png)

**Comment by scholokov** [comment]
fixed
