### ISSUE TITLE
20201010_11_brech/ Блок прев'ю"Дорога Бреч -Київ "- відсутня дата подорожі в прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1781]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20201010_11_brech/
2.Проскролити сторінку до прев'ю"Дорога Бреч -Київ"
3.Звернути увагу на дату подорожі в прев'ю

**Фактичний результат:** Відсутня дата подорожі в прев'ю
**Очікуваний результат:** Присутня дата подорожі в прев'ю

**Додаткова інормація:** https://github.com/scholokov/long-travel-2/wiki/2.-Travel.Structure

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_110](https://user-images.githubusercontent.com/109720075/205056527-4d77e5ab-af8d-4eb4-96ed-118d9e31606e.png)
![Screenshot_100](https://user-images.githubusercontent.com/109720075/205057287-2b364d0e-2fef-4807-95e9-7bdb0666446b.png)

**Comment by scholokov** [comment]
fixed

**Comment by scholokov** [comment]
fixed
