### ISSUE TITLE
20201010_11_brech/ Блок прев'ю"Дорога Київ -Бречь"- "Бречь" на російській мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1782]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20201010_11_brech/
2.Проскролити сторінку до прев'ю"Дорога Київ -Бречь"
3.Звернути увагу на подорожі в прев'ю

**Фактичний результат:** "Бречь" на російській мові
**Очікуваний результат:** "Бреч" написано українською мовою

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_111](https://user-images.githubusercontent.com/109720075/205057168-418a0981-a46d-4f1c-a13c-824d520d41e5.png)
![Screenshot_107](https://user-images.githubusercontent.com/109720075/205057369-8a80a9d0-f551-48a5-ac02-2be3a2742208.png)

**Comment by andry1729** [comment]
Дорога Бреч Київ

**Comment by DmytroMarkulych** [comment]
@andry1729 поправте будь ласка очікуваний результат

**Comment by scholokov** [comment]
fixed
