### ISSUE TITLE
20210611_13_vinnitsa/Блок прев'ю"Вінниця"- фото прев'ю наполовину затемнене

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1783]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210611_13_vinnitsa/
2.Звернути увагу на фото прев'ю блоку "Вінниця"

**Фактичний результат:** Фото прев'ю наполовину затемнене
**Очікуваний результат:** Фото прев'ю чітке

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_1](https://user-images.githubusercontent.com/109720075/205078680-db4426db-728e-4e91-926f-a6c98d9cb239.png)
![Screenshot_2](https://user-images.githubusercontent.com/109720075/205078686-c27f338f-3f1e-4fcb-b571-045e49eaf38c.png)

**Comment by scholokov** [comment]
fixed
