### ISSUE TITLE
20210611_13_vinnitsa/ Блок прев'ю над картою"Вінниця"- дата подорожі знаходиться під прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1784]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210611_13_vinnitsa/
2.Звернути увагу на дату подорожі в прев'ю "Вінниця"

**Фактичний результат:** Дата подорожі знаходиться під прев'ю
**Очікуваний результат:** Дата подорожі знаходиться в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_3](https://user-images.githubusercontent.com/109720075/205079939-72128376-fdb2-4496-a2b9-5b34fafdfc9b.png)

**Comment by scholokov** [comment]
fixed
