### ISSUE TITLE
20210611_13_vinnitsa/В прев'ю подорожі"Готель ”Rooms Hotel” Вінниця 11-13.06.2021"- розмір елементу зображення "прапор" (Width-16,Height-11)

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1788]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210611_13_vinnitsa/
2.Проскролити сторінку до прев'ю подорожі "Готель ”Rooms Hotel” Вінниця 11-13.06.2021"
3.Звернути увагу на розмір елементу зображення "прапор"

**Фактичний результат:** Розмір елементу зображення "прапор" (Width-16,Height-11)-не відповідає вимогам
**Очікуваний результат:** Розмір елементу зображення "прапор" (Width-26,Height-17.33)- відповідає вимогам

**Додаткова інформація:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1201%3A27&t=gEmIKDTFdZ2qOxna-0

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_7](https://user-images.githubusercontent.com/109720075/205086697-0b307f7e-a67f-4957-bf3b-e0df9e207758.png)
![Screenshot_8](https://user-images.githubusercontent.com/109720075/205086704-7a0d058e-217b-4c12-b063-c8e706241dea.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 давайте додамо точних розмірів в баг репорт. у нас є фактичні розміри і очікувані

**Comment by scholokov** [comment]
fixed
