### ISSUE TITLE
20210611_13_vinnitsa/ В прев'ю подорожі"Варенична-Сметана, Вінниця 12.06.2021"-відсутній прапор України в правому кутку прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1792]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210611_13_vinnitsa/
2.Проскролити сторінку до прев'ю"Варенична-Сметана, Вінниця 12.06.2021"
3.Звернути увагу на прапор України в прев'ю

**Фактичний результат:** Відсутній прапор України в прев'ю
**Очікуваний результат:** Присутній прапор України в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_12](https://user-images.githubusercontent.com/109720075/205096068-c1397b4c-16d6-4742-9034-e3b1d321b949.png)

**Comment by scholokov** [comment]
fixed
