### ISSUE TITLE
20210611_13_vinnitsa/ В прев'ю подорожі"Вінницький фонтан Roshen 12.06.2021"-відсутній прапор України в правому кутку прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1796]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210611_13_vinnitsa/
2.Проскролити сторінку до прев'ю" Вінницький фонтан Roshen 12.06.2021"
3.Звернути увагу на прапор України в прев'ю

**Фактичний результат:** Відсутній прапор України в прев'ю
**Очікуваний результат:** Присутній прапор України в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_16](https://user-images.githubusercontent.com/109720075/205098650-5adfdd88-e645-4a9f-87f6-88e2e860cca1.png)

**Comment by scholokov** [comment]
fixed
