### ISSUE TITLE
20210611_13_vinnitsa/В прев'ю подорожі" Дорога Вінниця- Київ 13.06.2021"- відсутнє фото прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1797]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210611_13_vinnitsa/
2.Проскролити сторінку до прев'ю подорожі "Дорога Вінниця- Київ 13.06.2021"
3.Звернути увагу на фото прев'ю

**Фактичний результат:** Фото прев'ю відсутнє
**Очікуваний результат:** Фото прев'ю присутнє

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_17](https://user-images.githubusercontent.com/109720075/205099528-ce09ffdb-a443-4a8a-ba5a-c26197ba3cbf.png)

**Comment by scholokov** [comment]
fixed
