### ISSUE TITLE
20210611_13_vinnitsa/ В прев'ю подорожі"Дорога Вінниця- Київ 13.06.2021"-відсутній прапор України в правому кутку прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1798]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210611_13_vinnitsa/
2.Проскролити сторінку до прев'ю" Дорога Вінниця- Київ 13.06.2021"
3.Звернути увагу на прапор України в прев'ю

**Фактичний результат:** Відсутній прапор України в прев'ю
**Очікуваний результат:** Присутній прапор України в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_18](https://user-images.githubusercontent.com/109720075/205100630-2c346a0c-7348-49d0-baae-7e0a09339eeb.png)

**Comment by scholokov** [comment]
fixed
