### ISSUE TITLE
20210510_stariy_solvin/ The name of the travel on "Travel Map" misspelling

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#1804]
Steps:
1) Open page https://test.long-travel.live/20210510_stariy_solvin/
2) Pay attention to the NAME of travel on the Travel Map

Actual Result:
incorrect name of the travel  _stariy_solvin/

Expected Result
correct name of the travel  _staryi_solotvyn/

![Screenshot_2](https://user-images.githubusercontent.com/114935450/205317069-272ad695-5f15-4f95-8bad-82efafc4eeab.png)

**Comment by DmytroMarkulych** [comment]
@MarynaChurylo в Summary старайтеся не використовувати слова типу incorrect, doesn't work... це є загальні фрази і вони не описують конкретно дефект

**Comment by MarynaChurylo** [comment]
@DmytroMarkulych Дякую! Виправила.

**Comment by DmytroMarkulych** [comment]
@MarynaChurylo будь ласка зверніть увагу на даний розділ в специфікації, можливо це не є дефектом https://github.com/scholokov/long-travel-2/wiki/2.8-Travel.URL
