### ISSUE TITLE
20200627_29_yuzhniy/Прев'ю подорожі "Южный"- фото прев'ю наполовину затемнене 

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1805]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20200627_29_yuzhniy/
2.Звернути увагу на фото прев'ю блоку "Южный"

**Фактичний результат:** Фото прев'ю наполовину затемнене
**Очікуваний результат:** Фото прев'ю чітке

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_24](https://user-images.githubusercontent.com/109720075/205131940-f70f68fd-9f7a-406a-b4b5-d902e55b0848.png)

**Comment by scholokov** [comment]
fixed
