### ISSUE TITLE
20200627_29_yuzhniy/Прев'ю подорожі "Южный"-дата подорожі знаходиться під прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1806]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20200627_29_yuzhniy/
2.Звернути увагу на дату подорожі прев'ю  "Южный"

**Фактичний результат:** Дата подорожі знаходиться під прев'ю
**Очікуваний результат:** Дата подорожі знаходиться в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_25](https://user-images.githubusercontent.com/109720075/205132705-6686416f-44a0-470a-8048-087de1353ca0.png)

**Comment by scholokov** [comment]
fixed
