### ISSUE TITLE
20160814_24_Shadsk # 159 - Отсутствуют даты путешествия

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#181]
### Steps to reproduce:
1. Открыть страницу https://long-travel.live/20160814_24_shadsk/
2. Обратить внимание на дату путешествия

### Actual result:
Даты  **отсутствуют**

### Expected result:
Даты присутствуют **14.08.2016 - 24.08.2016**

![image](https://user-images.githubusercontent.com/86321831/136676140-e84ea0ce-089e-4927-8227-6fa95d9c6649.png)

### Environment:
Windows 10, Google Chrome v. 94.0.4606.71

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
открыты 2 новых бага: #184  и #185
