### ISSUE TITLE
20210510_stariy_solvin/ Travel's name on the map - does not match specifications

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#1810]
Steps:

1) Open page https://test.long-travel.live/20210510_stariy_solvin/
2) Pay attention to the NAME of travel on the Travel Map

Actual Result:
incorrect name of the travel   20210510_stariy_solvin 

Expected Result
correct name  of the travel    2021.05.10 Старий Солотвин

Link to specifications https://github.com/scholokov/long-travel-2/wiki/3.1-Maps.Global-Map-with-routs

Link to Travels.List https://github.com/scholokov/long-travel-2/wiki/4.2-Travels.List

![Screenshot_4](https://user-images.githubusercontent.com/114935450/206249733-f5189584-d39f-4bfd-96e0-9a3b5dfa9568.png)

**Comment by DmytroMarkulych** [comment]
@MarynaChurylo в Summary старайтеся не використовувати слова типу incorrect, doesn't work... це є загальні фрази і вони не описують конкретно дефект

**Comment by MarynaChurylo** [comment]
@DmytroMarkulych Дякую! Виправила.

**Comment by DmytroMarkulych** [comment]
@MarynaChurylo в баг репорті мова йдеться про ID подорожі, а в специфікації про імя подорожі

**Comment by MarynaChurylo** [comment]
Виправила

**Comment by DmytroMarkulych** [comment]
https://i.imgur.com/dm7lHYn.png

**Comment by scholokov** [comment]
fixed

**Comment by MarynaChurylo** [comment]
successful
