### ISSUE TITLE
20200627_29_yuzhniy/ В прев'ю подорожі"Дорога: Киев-Южный 27.06.2020"-відсутній прапор України в правому кутку прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1813]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20200627_29_yuzhniy/
2.Проскролити сторінку до прев'ю" Дорога: Киев-Южный 27.06.2020"
3.Звернути увагу на прапор України в прев'ю

**Фактичний результат:** Відсутній прапор України в прев'ю
**Очікуваний результат:** Присутній прапор України в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_32](https://user-images.githubusercontent.com/109720075/205137145-deaf5e11-5ee6-48f1-9edb-910bed2461f8.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_8](https://user-images.githubusercontent.com/109720075/205676772-453b31d0-53b8-425d-b269-504d0d7520bd.png)

**Comment by scholokov** [comment]
fixed
