### ISSUE TITLE
20200627_29_yuzhniy/ В прев'ю подорожі"Дорога: Киев-Южный 27.06.2020"-назва подорожі російською мовою

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1814]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20200627_29_yuzhniy/
2.Проскролити сторінку до прев'ю" Дорога: Киев-Южный 27.06.2020"
3.Звернути увагу на назву подорожі в прев'ю

**Фактичний результат:** Назва подорожі в прев'ю російською мовою
**Очікуваний результат:** Назва подорожі  в прев'ю українською  мовою

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_33](https://user-images.githubusercontent.com/109720075/205137751-96add258-b917-48b3-9bbc-b0ce3c7df2fe.png)

**Comment by scholokov** [comment]
fixed
