### ISSUE TITLE
20200627_29_yuzhniy/В прев'ю подорожі"Южный 28.06.2020"- відсутнє фото прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1816]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20200627_29_yuzhniy/
2.Проскролити сторінку до прев'ю подорожі "Южный 28.06.2020"
3.Звернути увагу на фото прев'ю

**Фактичний результат:** Фото прев'ю відсутнє
**Очікуваний результат:** Фото прев'ю присутнє

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_35](https://user-images.githubusercontent.com/109720075/205139612-d381ad14-6958-41fb-9da1-51e070aabc18.png)

**Comment by scholokov** [comment]
fixed
