### ISSUE TITLE
20200627_29_yuzhniy/ В прев'ю подорожі"Apartamenty 27.06.2020 – 29.06.2020"-відсутній прапор України в правому кутку прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1819]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20200627_29_yuzhniy/
2.Проскролити сторінку до прев'ю"Apartamenty 27.06.2020 – 29.06.2020"
3.Звернути увагу на прапор України в прев'ю

**Фактичний результат:** Відсутній прапор України в прев'ю
**Очікуваний результат:** Присутній прапор України в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_38](https://user-images.githubusercontent.com/109720075/205141746-59c128f2-87ea-473f-b508-45e611cf9b52.png)

**Comment by scholokov** [comment]
fixed
