### ISSUE TITLE
20160814_24_Shadsk # 159 - Отсутствует карта путешествия

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#182]
### Steps to reproduce:
1. Открыть страницу https://long-travel.live/20160814_24_shadsk/
2. Обратить внимание на карту путешествия

### Actual result:
Карта **отсутствуют**

### Expected result:
Карта **присутствует**

![image](https://user-images.githubusercontent.com/86321831/136676343-cddb77f5-dfaf-4dc6-ac45-7e20d7e07a64.png)

### Environment:
Windows 10, Google Chrome v. 94.0.4606.71

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверен
