### ISSUE TITLE
20200627_29_yuzhniy/ В прев'ю подорожі"Дорога: Южный – Винница – Киев 29.06.2020 "-відсутній прапор України в правому кутку прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1821]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20200627_29_yuzhniy/
2.Проскролити сторінку до прев'ю"Дорога: Южный – Винница – Киев 29.06.2020 "
3.Звернути увагу на прапор України в прев'ю

**Фактичний результат:** Відсутній прапор України в прев'ю
**Очікуваний результат:** Присутній прапор України в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_40](https://user-images.githubusercontent.com/109720075/205143137-8cc713b6-605d-48d0-a1b4-4b5d456588d7.png)

**Comment by scholokov** [comment]
fixed
