### ISSUE TITLE
20200627_29_yuzhniy/ В прев'ю подорожі"Дорога: Южный – Винница – Киев 29.06.2020"-назва подорожі російською мовою

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1822]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20200627_29_yuzhniy/
2.Проскролити сторінку до прев'ю"Дорога: Южный – Винница – Киев 29.06.2020"
3.Звернути увагу на назву подорожі в прев'ю

**Фактичний результат:** Назва подорожі в прев'ю російською мовою
**Очікуваний результат:** Назва подорожі в прев'ю українською мовою

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_41](https://user-images.githubusercontent.com/109720075/205143584-df1c791f-77e0-44a4-bb52-2248dc74d9b3.png)

**Comment by scholokov** [comment]
fixed
