### ISSUE TITLE
20220124_0128_netherlands/ Прев'ю  подорожі "Amsterdam 26-27.01.2022"- дата подорожі знаходиться під прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1824]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2.Проскролити сторінку до прев'ю  подорожі "Amsterdam 26-27.01.2022"
3.Звернути увагу на дату подорожі в прев'ю 

**Фактичний результат:** Дата подорожі знаходиться під прев'ю
**Очікуваний результат:** Дата подорожі знаходиться в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_45](https://user-images.githubusercontent.com/109720075/205252584-aa29cc9f-2a68-4494-9ba8-fee0921c2b09.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_9](https://user-images.githubusercontent.com/109720075/205678103-da35edc1-4afd-4f00-ad4c-40a17b97bf9b.png)

**Comment by scholokov** [comment]
please retest

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_22](https://user-images.githubusercontent.com/109720075/206146704-6bb22278-848f-4ba9-9eca-159113b06b1e.png)

**Comment by scholokov** [comment]
fixed
