### ISSUE TITLE
20220124_0128_netherlands/Прев'ю подорожі"Car Rental Eindhoven 24.01.2022"-присутні два прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1825]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20220124_0128_netherlands/
2. Проскролити сторінку до прев'ю подорожі"Car Rental Eindhoven 24.01.2022"
3.Звернути увагу на присутність двох прев'ю"Car Rental Eindhoven 24.01.2022"

**Фактичний результат:** Присутні два прев'ю
**Очікуваний результат:** Присутні одне прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_46](https://user-images.githubusercontent.com/109720075/205254614-430a7787-90bb-4aad-9bcd-577ac80190a6.png)

**Comment by scholokov** [comment]
fixed
