### ISSUE TITLE
20201025_vedmy/ в легенда нема проміжуточного кілометражу відстані

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#1827]
Передумови:
Відкрити https://test.long-travel.live/20201025_vedmy/
Кроки для відтворення:

1. Звеніть уагу, що врозділі Легенда немає  проміжуточного кілометражу відстані

Фактичний результат: в легенда немає проміжуточного кілометражу відстані
Очікуваний результат: в легенда відображається  проміжуточної кілометраж відстані

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версия 107.0.5304.12
![прміжуточна відстань](https://user-images.githubusercontent.com/113175298/205284112-ab3e467e-0fb8-49ad-88a9-42bcdebaf148.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk враховуючи дану інформацію з специфікації, давай поправимо баг репорт 
![image](https://user-images.githubusercontent.com/88647733/205335692-e02714dc-e306-4cb2-a786-9fed8667c40e.png)

**Comment by Nadiyk** [comment]
маєш на увазі виправити самарі? чи що?

**Comment by DmytroMarkulych** [comment]
@Nadiyk так

**Comment by Nadiyk** [comment]
виправила

**Comment by scholokov** [comment]
враховуючи що тут лише одна точка, то і відстані не існує...

**Comment by Nadiyk** [comment]
закривати цей баг?

**Comment by DmytroMarkulych** [comment]
@так
