### ISSUE TITLE
20210926_mashrooms/ в preview  немає назви подорожі

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#1828]
Передумови:
Відкрити https://test.long-travel.live/20210926_mashrooms/
Кроки для відтворення:

1. Зверніть увагу, що в preview немає назви подорожі

Фактичний результат: в preview  немає назви подорожі
Очікуваний результат:  в preview  є назва подорожі Загальці-Гриби

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версия 107.0.5304.122
![по,назва подорожі](https://user-images.githubusercontent.com/113175298/205286240-3e6276cd-b435-4b47-8f62-07db249dfb12.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk в очікуванлму результаті давайте додамо саме назву яка має бути

**Comment by Nadiyk** [comment]
Це правельна назва подорожі?

![Загальці - Гриби](https://user-images.githubusercontent.com/113175298/205344670-3de35d59-0f45-407c-aef4-3cd3c2d8c1dc.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk якщо збігаються id то так

**Comment by DmytroMarkulych** [comment]
@Nadiyk в очікуваний результат, ви вписуєте потенційний дефект

**Comment by Nadiyk** [comment]
в очікуваний результат я вписалал назву яку ми очікуємо побачити, чи то не добре?

**Comment by DmytroMarkulych** [comment]
@Nadiyk все вірно, але придивіться до назви

**Comment by Nadiyk** [comment]
я в назві небачу помилки) забрати ""?

**Comment by DmytroMarkulych** [comment]
в preview є назва подорожі **Загальці_Гриби**

**Comment by Nadiyk** [comment]
![image](https://user-images.githubusercontent.com/113175298/205910853-b806d675-ee66-4a81-aaf0-509699c170f1.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk назву подорожі ми пишемо через дефіз, чи через нижнє підчеркування?

**Comment by Nadiyk** [comment]
Виправила

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
