### ISSUE TITLE
20210926_mashrooms/  в розділі Легенда  немає відстані подорожі

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#1829]
Передумови:
Відкрити https://test.long-travel.live/20210926_mashrooms/
Кроки для відтворення:

1. Зверніть увагу, що в розділі легенда немає відстані подорожі

Фактичний результат: в розділі легенда немає відстані подорожі
Очікуваний результат: в розділі легенда є відстань подорожі

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версия 107.0.5304.122
![гриби відстань](https://user-images.githubusercontent.com/113175298/205288063-e83746f2-a620-4026-96b0-293c454dac76.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk звернуться будь ласка до WIKI щоб дізнатися точні назви даних елементів

**Comment by Nadiyk** [comment]
Тут, невірно я дивлюсь?
![Легенда](https://user-images.githubusercontent.com/113175298/205345367-96d1f645-da4e-4a5b-a113-6163846c7f7b.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk так, вірно, але ті цифри мають конкретну назву

**Comment by Nadiyk** [comment]
цифри які? кілометраж?

**Comment by DmytroMarkulych** [comment]
@Nadiyk 
![image](https://user-images.githubusercontent.com/88647733/205498466-8ce2edb9-1de8-4c00-adb4-0449ab13d072.png)

**Comment by Nadiyk** [comment]
km?

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
