### ISSUE TITLE
20210917_19_lviv/ немає зображення в preview

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#1831]
Передумови:
Відкрити  https://test.long-travel.live/20210917_19_lviv/
Кроки для відтворення:

1. Зверніть увагу що в preview немає зображення 

Фактичний результат: немає зображення в preview
Очікуваний результат: в preview є зображення

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версия 107.0.5304.122
![львів](https://user-images.githubusercontent.com/113175298/205297350-ededfe63-bd08-4b99-a6d6-3041d1c29578.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
Pass
