### ISSUE TITLE
20210917_19_lviv/ на сторінці немає карти подорожі

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#1833]
Передумови:
Відкрити https://test.long-travel.live/20210917_19_lviv/
Кроки для відтворення:

1. Зверніть увагу, на сторінці немає карти
 
Фактичний результат:  на сторінці немає карти подорожі
Очікуваний результат:  на сторінці є карта подорожі

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версія 107.0.5304.122
![Lviv map](https://user-images.githubusercontent.com/113175298/205298776-4d3493bb-0ed5-452b-b508-bfcda6dd8ad4.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
