### ISSUE TITLE
20210510_stariy_solvin/ First travel's preview - mistake in date 25.10.2021

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#1835]
Steps:

1) Open page https://test.long-travel.live/20210510_stariy_solvin/
2) Pay attention to first preview - travel's date

Actual Result:    incorrect date of the travel -  25.10.2021

Expected Result:    correct date of the travel - 10.05.2021
![Screenshot_1](https://user-images.githubusercontent.com/114935450/205304524-a204c683-546b-44ce-bb99-77568ab21b2b.png)

**Comment by DmytroMarkulych** [comment]
@MarynaChurylo Давайте в summary вкажемо дату яка є фактичною.

**Comment by MarynaChurylo** [comment]
@DmytroMarkulych Дякую! Виправила.

**Comment by scholokov** [comment]
fixed
