### ISSUE TITLE
20210510_stariy_solvin/ 3th travel's preview - mistake in date 05.10.2021

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#1836]
Steps:

1) Open page https://test.long-travel.live/20210510_stariy_solvin/
2) Scroll down the page to the 3rd preview
3) Pay attention to the travel's date

Actual Result: incorrect date of the travel - 05.10.2021

Expected Result: correct date of the travel - 10.05.2021

![Screenshot_1](https://user-images.githubusercontent.com/114935450/205306667-2adf2de3-5a83-458a-805e-f4361663eac6.png)

**Comment by DmytroMarkulych** [comment]
@MarynaChurylo давайте вкажемо конкретну дату в summary яка є як дефект

**Comment by scholokov** [comment]
fixed

**Comment by MarynaChurylo** [comment]
Pass
