### ISSUE TITLE
20210510_stariy_solvin/ Bottom of the page - mistake in publication date 

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#1837]
Steps:

1) Open page https://test.long-travel.live/20210510_stariy_solvin/
2) Scroll the page to the bottom
3) Pay attention to the publication date

Actual Result: incorrect date of publication - 05.10.2021

Expected Result: correct date of publication - 10.05.2021

Link to specifications https://github.com/scholokov/long-travel-2/wiki/2.3-Travel.Content

![Screenshot_3](https://user-images.githubusercontent.com/114935450/205646326-ca444eaa-a563-41c4-8142-41a3765e0ea9.png)

**Comment by DmytroMarkulych** [comment]
@MarynaChurylo додайте буедь ласка посилання на документацію, в якій вказаний формат дати публікації

**Comment by MarynaChurylo** [comment]
@DmytroMarkulych Дякую! Виправила.

**Comment by scholokov** [comment]
fixed

**Comment by MarynaChurylo** [comment]
pass
