### ISSUE TITLE
20210508_12months/ В прев'ю подорожі"Демидів, Київська область, Україна 08.05.2021"- відсутнє фото прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1838]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210508_12months/
2.Проскролити сторінку до прев'ю подорожі "Демидів, Київська область, Україна 08.05.2021"
3.Звернути увагу на фото прев'ю

**Фактичний результат:** Фото прев'ю відсутнє
**Очікуваний результат:** Фото прев'ю присутнє

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_49](https://user-images.githubusercontent.com/109720075/205315043-e765f610-6898-448e-bea7-9104d4ae142f.png)

**Comment by scholokov** [comment]
fixed
