### ISSUE TITLE
20210508_12months/ В прев'ю подорожі"Демидів, Київська область, Україна 08.05.2021"-відсутній прапор України в правому кутку прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1839]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210508_12months/
2.Проскролити сторінку до прев'ю"Демидів, Київська область, Україна 08.05.2021"
3.Звернути увагу на прапор України в прев'ю

**Фактичний результат:** Відсутній прапор України в прев'ю
**Очікуваний результат:** Присутній прапор України в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_50](https://user-images.githubusercontent.com/109720075/205315575-0ee3bc93-2a7f-4ce9-83fb-20b91213679f.png)

**Comment by scholokov** [comment]
fixed
