### ISSUE TITLE
20210510_stariy_solvin/ Gallery structure of a page - unexpected element (date)

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#1844]
Steps:

1) Open page https://test.long-travel.live/20210510_stariy_solvin/
2) Scroll the page to the 3th preview
3) Pay attention to the date between 3th preview and photo gallery

Actual Result: unexpected date  05.10.2021

Expected Result: no any date

![Screenshot_9](https://user-images.githubusercontent.com/114935450/205324159-bd38c99e-20ad-4e5c-955c-d89406c63df4.png)

**Comment by scholokov** [comment]
fixed

**Comment by MarynaChurylo** [comment]
Pass
