### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі"Дорога Київ – Nyíregyháza 23.06.2015"-відсутні прапори України та Угорщини в прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1846]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю"Дорога Київ – Nyíregyháza 23.06.2015"
3.Звернути увагу на прапори України та Угорщини в прев'ю

**Фактичний результат:** Відсутні прапори України та Угорщини в прев'ю
**Очікуваний результат:** Присутні прапори України та Угорщини в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_56](https://user-images.githubusercontent.com/109720075/205328864-5ff0d968-8791-4809-9392-41d72ee07dae.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_4](https://user-images.githubusercontent.com/109720075/205674312-03f6db3f-003e-453f-8a2f-20b589a5c3ef.png)

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_18](https://user-images.githubusercontent.com/109720075/206144892-2c39d942-efbb-4985-8319-2ce4a0fc91e4.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
Другий прапор України замінити на прапор Угорщини
![Screenshot_10](https://user-images.githubusercontent.com/109720075/206916049-c3cd49cf-7f92-45f5-8029-e44e28d80381.png)

**Comment by scholokov** [comment]
у коментах описаний інший баг, який не відповідає описаному в тілі бага.
у такому випадку поточний баг закривається з відповідними коментарями
і створюється новий баг
