### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі"Pagony Wellness & Conference  Nyíregyháza  24-25.06.2015"-відсутній прапор  Угорщини в прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1847]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю"Pagony Wellness & Conference  Nyíregyháza 24-25.06.2015"
3.Звернути увагу на прапор Угорщини в прев'ю

**Фактичний результат:** Відсутній прапор  Угорщини в прев'ю
**Очікуваний результат:** Присутній  прапор  Угорщини в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_57](https://user-images.githubusercontent.com/109720075/205329731-d1602b56-01ca-43f1-880b-1eebef844763.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_5](https://user-images.githubusercontent.com/109720075/205674680-d30877fd-de8f-4baf-bbc4-3aabc1160fc7.png)

**Comment by scholokov** [comment]
please retest

**Comment by scholokov** [comment]
fixed
