### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі"Hungary 23.06.2015"-відсутній прапор Угорщини в прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1848]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю"Hungary 23.06.2015"
3.Звернути увагу на прапор Угорщини в прев'ю

**Фактичний результат:** Відсутній прапор Угорщини в прев'ю
**Очікуваний результат:** Присутній прапор Угорщини в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_58](https://user-images.githubusercontent.com/109720075/205330730-1d126ee4-dd96-4c20-a57a-f0db6516d655.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_6](https://user-images.githubusercontent.com/109720075/205674929-b7273a76-6846-4fba-a9ba-fb48eed25743.png)

**Comment by scholokov** [comment]
please retest

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_16](https://user-images.githubusercontent.com/109720075/206135759-3eb2a6f0-231b-4e4c-b7c2-3c0900581c83.png)

**Comment by scholokov** [comment]
fixed
