### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі"Nyiregyhaza Animal Park, Zoo Nyiregyhaza 24.06.2015"-відсутній прапор Угорщини в прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1849]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю"Nyiregyhaza Animal Park, Zoo Nyiregyhaza 24.06.2015"
3.Звернути увагу на прапор Угорщини в прев'ю

**Фактичний результат:** Відсутній прапор Угорщини в прев'ю
**Очікуваний результат:** Присутній прапор Угорщини в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_59](https://user-images.githubusercontent.com/109720075/205332038-f5481ed6-ec82-4966-a689-736ed824ebe2.png)

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_7](https://user-images.githubusercontent.com/109720075/205675176-254050cf-8cd6-40ec-86d5-1949bd331e7b.png)

**Comment by scholokov** [comment]
please retest

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_15](https://user-images.githubusercontent.com/109720075/206135385-e4c0e5bf-cc78-4264-bb3a-1156652eee52.png)

**Comment by scholokov** [comment]
fixed
