### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі"Дорога 25.06.2015"-відсутній прапор Угорщини в прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1850]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю"Дорога 25.06.2015"
3.Звернути увагу на прапор Угорщини в прев'ю

**Фактичний результат:** Відсутній прапор Угорщини в прев'ю
**Очікуваний результат:** Присутній прапор Угорщини в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_60](https://user-images.githubusercontent.com/109720075/205487143-6a7faf9a-3cec-4c61-8f47-f339224f969c.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_12](https://user-images.githubusercontent.com/109720075/205681479-ea2908a2-d5c2-43e4-bcc3-bcf245ec08c7.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_13](https://user-images.githubusercontent.com/109720075/206134253-a78d3528-0a3a-42be-800c-353f41107365.png)

**Comment by scholokov** [comment]
fixed
