### ISSUE TITLE
20150623_0711_Croatia/ Блок прев'ю"Apartments Poljanak Poljanak"- відсутня дата подорожі в прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1852]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю"Apartments Poljanak Poljanak"
3.Звернути увагу на дату подорожі в прев'ю

**Фактичний результат:**  Відсутня дата подорожі в прев'ю
**Очікуваний результат:** Присутня дата подорожі в прев'ю- 26.06.2015

**Додаткова інормація:** https://github.com/scholokov/long-travel-2/wiki/2.-Travel.Structure

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![205057287-2b364d0e-2fef-4807-95e9-7bdb0666446b](https://user-images.githubusercontent.com/109720075/205487805-d19614bb-dd97-4923-a7a8-964bf46a5832.png)
![Screenshot_62](https://user-images.githubusercontent.com/109720075/205487809-d105460b-e411-41af-aeea-e790873ccf36.png)
![Screenshot_63](https://user-images.githubusercontent.com/109720075/205487810-a459ddc9-92ed-4611-a3e4-19873c741c37.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_2](https://user-images.githubusercontent.com/109720075/205671476-e557bb53-b208-46cd-a503-c7532b53d405.png)

**Comment by scholokov** [comment]
please retest

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_19](https://user-images.githubusercontent.com/109720075/206145211-fe2b9e3c-f4b6-458f-8abd-4b112a1755fc.png)
