### ISSUE TITLE
20150623_0711_Croatia/ Блок прев'ю"Apartments Poljanak Poljanak"- відсутній  link на готель

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1853]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю"Apartments Poljanak Poljanak"
3.Звернути увагу на link  готелю

**Фактичний результат:** Відсутній  link на готель
**Очікуваний результат:** Присутній  link на готель

**Додаткова інормація:** https://github.com/scholokov/long-travel-2/wiki/2.3-Travel.Content

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_64](https://user-images.githubusercontent.com/109720075/205488205-d5461522-8c0c-4996-a29b-75027b7f9e12.png)
![Screenshot_65](https://user-images.githubusercontent.com/109720075/205488207-d6181ed3-0736-495c-87f5-2918b77ec00e.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
Баг відтворюється
![Screenshot_67](https://user-images.githubusercontent.com/109720075/205596631-32ba5fa7-98dc-4879-a6d9-f8c4326243ff.png)

**Comment by scholokov** [comment]
please retest

**Comment by andry1729** [comment]
Баг відтворюється
![Screenshot_21](https://user-images.githubusercontent.com/109720075/206146189-72ab8f04-305c-490f-9e90-133ad01f9961.png)

**Comment by scholokov** [comment]
fixed
