### ISSUE TITLE
20210917_19_lviv/ в Preview немає дати подорожі

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#1855]
Передумови:
Відкрити https://test.long-travel.live/20210917_19_lviv/
Кроки для відтворення:

1. Зверніть увагу, що в preview немає дати подорожі

Фактичний результат: в preview немає дати подорожі
Очікуваний результат: в preview є дата подорожі

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версія 107.0.5304.122
![1](https://user-images.githubusercontent.com/113175298/205510281-74ab94bc-49d9-49d3-897d-41569282a4be.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
