### ISSUE TITLE
20210917_19_lviv/ в Preview немає прапора країни

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#1856]
Передумови:
Відкрити https://test.long-travel.live/20210917_19_lviv/
Кроки для відтворення:

1. Зверніть увагу, що в Previwe немає прапора країни

Фактичний результат: в Preview немає прапора країни
Очікуваний результат: в Preview є прапор країни

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версія 107.0.5304.122
![2 львів](https://user-images.githubusercontent.com/113175298/205510555-6839034c-6da6-4410-8594-83d66044d3d8.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
