### ISSUE TITLE
20210510_stariy_solvin/ 3th travel's preview - unexpected element in preview's structure (Україна)

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#1858]
Steps:

1) Open page https://test.long-travel.live/20210510_stariy_solvin/
2) Scroll the page to the 3th preview
3) Pay attention to the preview's structure 

Actual Result: unexpected element - Україна

Expected Result: no text - Україна 

Link to specifications https://github.com/scholokov/long-travel-2/wiki/2.-Travel.Structure

![Screenshot_3](https://user-images.githubusercontent.com/114935450/205677869-38bc2dd2-5e1d-4e8f-a8f6-e8a55c8edffd.png)

**Comment by scholokov** [comment]
fixed

**Comment by MarynaChurylo** [comment]
pass
