### ISSUE TITLE
20210510_stariy_solvin/ Travel.YoutubeVideo- missformat of the date (10.05.2021)

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#1860]
Steps:

1) Open page https://test.long-travel.live/20210510_stariy_solvin/
2) Scroll the page to the 2nd block "Дорога"
3) Pay attention to YoutubeVideo's date. 

Actual Result: missformat of the date -  10.05.2021

Expected Result: format of the date - 2021.05.10

Link to specifications https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery

![Screenshot_5](https://user-images.githubusercontent.com/114935450/205685847-c372d43e-d2f5-463d-98a6-112274386d4e.png)

**Comment by scholokov** [comment]
fixxed

**Comment by MarynaChurylo** [comment]
pass
