### ISSUE TITLE
20210510_stariy_solvin/ Travel.YoutubeVideo - travel's name misspelling 

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#1861]
Steps:

1) Open page https://test.long-travel.live/20210510_stariy_solvin/
2) Scroll the page to the 2nd block "Дорога"
3) Pay attention to YoutubeVideo's name.

Actual Result: misspell in travel's name - Старий Солотвін

Expected Result: travel's name - Старий Солотвин

![Screenshot_3](https://user-images.githubusercontent.com/114935450/205690695-5bddee81-8c77-4168-b6aa-7ae93a6da08b.png)

**Comment by scholokov** [comment]
fixed

**Comment by MarynaChurylo** [comment]
pass
