### ISSUE TITLE
20210510_stariy_solvin/ Travels. Med size image with Title - misspelling travel's name

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#1862]
Steps:

1) Open page https://test.long-travel.live/travels/
2) Scroll the page down - until finding travel's name (Старий Солотвін)
3) Pay attention to travel's name

Actual Result: misspelling name - Старий Солотвін

Expected Result: name - Старий Солотвин

![Screenshot_6](https://user-images.githubusercontent.com/114935450/205699307-f042a398-ec87-495b-b63f-74daf5613273.png)

**Comment by scholokov** [comment]
fixed

**Comment by MarynaChurylo** [comment]
Bug was not fixed

**Comment by DmytroMarkulych** [comment]
@MarynaChurylo краще вкажіть, що дефект відтворюється , і додайте скрін із дефектом

**Comment by MarynaChurylo** [comment]
bug still reproduced 

![Screenshot_1](https://user-images.githubusercontent.com/114935450/206694740-9965da6a-f199-4e5c-9715-e3151661f883.png)

**Comment by scholokov** [comment]
fixed

**Comment by MarynaChurylo** [comment]
successful
