### ISSUE TITLE
20210510_stariy_solvin/ Travels. Med size image with Title - mistake in travel's date (05.10.2021) 

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#1865]
Steps:

1) Open page https://test.long-travel.live/travels/
2) Scroll the page down - until finding med size image with Title - Старий Солотвін
3) Pay attention to travel's date

Actual Result: the date - 05.10.2021

Expected Result: the date - 10.05.2021

![Screenshot_5](https://user-images.githubusercontent.com/114935450/205705185-df211d22-a7c5-4353-a158-8de506524631.png)

**Comment by scholokov** [comment]
please retest

**Comment by MarynaChurylo** [comment]
bug still reproduced 

![Screenshot_1](https://user-images.githubusercontent.com/114935450/206697429-585aa326-d8a7-4e01-b723-639175cfd2e7.png)

**Comment by scholokov** [comment]
please retest

**Comment by MarynaChurylo** [comment]
successful
