### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі "Ferry 27.06.2015"- відсутній прапор Хорватії

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1866]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю "Ferry 27.06.2015"
3.Звернути увагу на прапор Хорватії

**Фактичний результат:** Відсутній прапор Хорватії 
**Очікуваний результат:** Присутній прапор Хорватії

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95  (Офіційне складання), (64 біт)
![Screenshot_24](https://user-images.githubusercontent.com/109720075/206205319-579f8abb-a3cb-438a-af7e-09da22938561.png)

**Comment by scholokov** [comment]
fixed
