### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі "Готель"- відсутній прапор Хорватії

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1867]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю "Готель",яке знаходиться під прев'ю "Ferry 27.06.2015"
3.Звернути увагу на прапор Хорватії

**Фактичний результат:** Відсутній прапор Хорватії
**Очікуваний результат:** Присутній прапор Хорватії

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_25](https://user-images.githubusercontent.com/109720075/206206811-6620daf4-52e9-47a4-b7e1-bcc8ff4315af.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_9](https://user-images.githubusercontent.com/109720075/206915715-a0926ba0-4c63-4ae1-b7c5-e3af147ec4d7.png)

**Comment by scholokov** [comment]
please retest
