### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі "Bol 28.06-03.07.2015"- відсутній прапор Хорватії

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1871]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю "Bol 28.06-03.07.2015"
3.Звернути увагу на прапор Хорватії

**Фактичний результат:** Відсутній прапор Хорватії
**Очікуваний результат:** Присутній прапор Хорватії

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_30](https://user-images.githubusercontent.com/109720075/206210868-434d69c0-93d2-4074-9f12-29f776527846.png)

**Comment by scholokov** [comment]
fixed
