### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі "Golden Horn Beach 28.06-03.07.2015"- відсутній прапор Хорватії

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1872]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю "Golden Horn Beach 28.06-03.07.2015"
3.Звернути увагу на прапор Хорватії

**Фактичний результат:** Відсутній прапор Хорватії
**Очікуваний результат:** Присутній прапор Хорватії

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_31](https://user-images.githubusercontent.com/109720075/206211817-14bd0086-23ad-4a63-88fe-d0d990a9ce58.png)

**Comment by scholokov** [comment]
fixed
