### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі "Дорога 04.07.2015"- відсутній прапор Хорватії

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1874]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю "Дорога 04.07.2015"
3.Звернути увагу на прапор Хорватії

**Фактичний результат:** Відсутній прапор Хорватії
**Очікуваний результат:** Присутній прапор Хорватії

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_33](https://user-images.githubusercontent.com/109720075/206213866-aca68ea9-67dc-4a70-8ddd-9d775618bd7d.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_6](https://user-images.githubusercontent.com/109720075/206915431-9b507b17-cd42-41ee-8cfd-a58d7722d444.png)

**Comment by scholokov** [comment]
please retest
