### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі "Готель"- відсутній прапор Хорватії 

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1875]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю "Готель",яке знаходиться під прев'ю "Дорога 04.07.2015"
3.Звернути увагу на прапор Хорватії

**Фактичний результат:** Відсутній прапор Хорватії
**Очікуваний результат:** Присутній прапор Хорватії

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_34](https://user-images.githubusercontent.com/109720075/206215647-d0c6cbc4-b4ab-4055-a2ec-2187555b7b0d.png)

**Comment by scholokov** [comment]
fixed

**Comment by scholokov** [comment]
please retest
