### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі "Загреб 05.07.2015"- відсутній прапор Хорватії

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1879]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю "Загреб 05.07.2015"
3.Звернути увагу на прапор Хорватії

**Фактичний результат:** Відсутній прапор Хорватії
**Очікуваний результат:** Присутній прапор Хорватії

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_37](https://user-images.githubusercontent.com/109720075/206221544-f9be96c8-98b2-4b1a-bd3c-4df9b63b3f52.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_65](https://user-images.githubusercontent.com/109720075/206656904-d1f6e347-c796-4da0-a731-b4e0afa6d2ef.png)

**Comment by scholokov** [comment]
fixed
