### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі "Загреб 05.07.2015"-  дата подорожі в прев'ю та блокові легенда не співпадають

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1880]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю "Загреб 05.07.2015"
3.Звернути увагу на дату подорожі 

**Фактичний результат:** Дата подорожі в прев'ю не співпадає з датою в блокові "Легенда"
**Очікуваний результат:** Дата подорожі в прев'ю співпадає з датою в блокові "Легенда"

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_38](https://user-images.githubusercontent.com/109720075/206222840-71380fb4-cb62-4f7e-ac94-90700106e46a.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 точно 08- місяць?

**Comment by andry1729** [comment]
В блокові легенда дати подорожей в Хорватії припадають на серпень місяць 
![Uploading Screenshot_20221208-145012-958.png…]()
