### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі "Zoloski vrt grada Zagreba, Zoo Zagreb 05.07.2015"- відсутній прапор Хорватії

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1881]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю "Zoloski vrt grada Zagreba, Zoo Zagreb 05.07.2015"
3.Звернути увагу на прапор Хорватії

**Фактичний результат:** Відсутній прапор Хорватії
**Очікуваний результат:** Присутній прапор Хорватії

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_39](https://user-images.githubusercontent.com/109720075/206224331-55d426b1-b5ff-4a37-bb36-1fdaa7e2b60c.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_64](https://user-images.githubusercontent.com/109720075/206656710-4ab1c2aa-7db6-49ff-b226-b064d7c01602.png)

**Comment by scholokov** [comment]
fixed
