### ISSUE TITLE
20150623_0711_Croatia/ Відео  "2015.07.05 Zoloski vrt grada Zagreba - Zagreb Zoo - Croatia 01" подорожі"Zoloski vrt grada Zagreba, Zoo Zagreb 05.07.2015"- дата подорожі в відео не співпадає з датою в блокові "Легенда"

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1883]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до відео  "2015.07.05 Zoloski vrt grada Zagreba - Zagreb Zoo - Croatia 01" подорожі"Zoloski vrt grada Zagreba, Zoo Zagreb 05.07.2015"
3.Звернути увагу на дату подорожі

**Фактичний результат:** Дата подорожі в відео не співпадає з датою в блокові "Легенда"
**Очікуваний результат:** Дата подорожі в відео  співпадає з датою в блокові "Легенда" - 2015.08.05

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_42](https://user-images.githubusercontent.com/109720075/206227305-4ae00eb5-261f-416b-8561-bfea9e7e2f69.png)
![Screenshot_41](https://user-images.githubusercontent.com/109720075/206227698-2171d009-d7e9-4e4a-b718-0fc1048a4a31.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 в Summary краще вказати конкретну проблему, замінивши фразу "не вірна дата"

**Comment by scholokov** [comment]
fixed
