### ISSUE TITLE
20210510_stariy_solvin/ Travels' list on the Global map - travel's name does not match specifications 

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#1884]
Steps:

1) Open page https://test.long-travel.live/travels/
2) Scroll the travels' list to travel  20210510_stariy_solvin
2)  Pay attention to the NAME of travel 

Actual Result:
incorrect name of the travel 20210510_stariy_solvin

Expected Result
correct name of the travel 2021.05.10 Старий Солотвин

Link to specifications https://github.com/scholokov/long-travel-2/wiki/3.1-Maps.Global-Map-with-routs

Link to Travels.List https://github.com/scholokov/long-travel-2/wiki/4.2-Travels.List

![Screenshot_5](https://user-images.githubusercontent.com/114935450/206258300-e9a62576-c4e8-4451-9698-abf92203d299.png)

**Comment by scholokov** [comment]
fixed

**Comment by MarynaChurylo** [comment]
Successful
