### ISSUE TITLE
Wiki/ 2.3 Travel.Content. Paragraph in the specifications is irrelevant

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#1885]
Steps:

1) Open page https://github.com/scholokov/long-travel-2/wiki/2.3-Travel.Content
2) Scroll the page to 2nd paragraph
2) Pay attention to subparagraph 2.6 

Actual Result:
Якщо є блок "дорога" він повинен мати наступний формат: 
Дорога: ХХХ - YYY
де XXX - початкова точка, YYY - кінцева точка. 

Expected Result
Якщо є блок "дорога" він повинен мати наступний формат: 
Дорога 
ХХХ - YYY
де XXX - початкова точка, YYY - кінцева точка.

 
![Screenshot_3](https://user-images.githubusercontent.com/114935450/206263108-f378b4c4-2677-4a75-8248-1c7c820fa922.png)

**Comment by scholokov** [comment]
виправлено
https://github.com/scholokov/long-travel-2/wiki/4.1.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%9A%D0%BE%D0%BD%D1%82%D0%B5%D0%BD%D1%82

**Comment by ODrobik** [comment]
@scholokov перевірено
