### ISSUE TITLE
Wiki/  2. Travel.Structure - unexpected element on the screenshot (Україна)

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#1887]
Steps:

1) Open page https://github.com/scholokov/long-travel-2/wiki/2.-Travel.Structure
2) Scroll the page to 2nd preview's screenshot
3) Pay attention to the name of the country (left side)

Actual Result:  country name is present Україна

Expected Result: country name missing

![Screenshot_5](https://user-images.githubusercontent.com/114935450/206268992-23afd9da-e576-4eaf-8b27-f56bb30cdcf1.png)

**Comment by scholokov** [comment]
fixed

**Comment by MarynaChurylo** [comment]
successful
