### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі "Дорога 06.07.2015"- відсутній прапор Хорваті та Австрії

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1888]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до попередньої "Дорога 06.07.2015"
3.Звернути увагу на прапор Хорватії

**Фактичний результат:** Відсутній прапор Хорватії та Австрії
**Очікуваний результат:** Присутній прапор Хорватії та Австрії

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_45](https://user-images.githubusercontent.com/109720075/206404971-c8782ee3-bb61-4b40-adbd-988271e12d2f.png)

**Comment by scholokov** [comment]
fixed

**Comment by scholokov** [comment]
fixed
