### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі "Дорога 06.07.2015"-  дата подорожі в  прев'ю не співпадає з блоком"Легенда"

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1889]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю "Дорога 06.07.2015"
3.Звернути увагу на дату подорожі

**Фактичний результат:** Дата подорожі в прев'ю не співпадає з блоком"Легенда
**Очікуваний результат:** Дата подорожі в прев'ю  співпадає з блоком"Легенда -06.082015

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_47](https://user-images.githubusercontent.com/109720075/206405825-4b61f9fa-2131-44d8-adbb-575feb54459c.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 в Summary краще вказати конкретну проблему, замінивши фразу "не вірна дата"

**Comment by DmytroMarkulych** [comment]
@andry1729 поправте ще очікуваний результат

**Comment by DmytroMarkulych** [comment]
@andry1729 вкажіть будь ласка точні дати в очікуваному результаті

**Comment by scholokov** [comment]
виправлено на мапі
