### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі "Дорога 06.07.2015"- відсутній формат блоку подорожі "Дорога: Хорватія -Австрія"

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1890]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю "Дорога 06.07.2015"
3.Звернути увагу на назву подорожі

**Фактичний результат:** Відсутній формат блоку подорожі "Дорога: Хорватія -Австрія"
**Очікуваний результат:** Присутній формат блоку подорожі "Дорога: Хорватія -Австрія"

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_48](https://user-images.githubusercontent.com/109720075/206407488-85239d5f-9239-49c1-85aa-e873623821b5.png)![Screenshot_56](https://user-images.githubusercontent.com/109720075/206490499-9931d00e-83c2-43f1-8a35-6e8cf8bc0911.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 зверніть увагу на специфікацію, відносно подорожі "Дорога"

**Comment by andry1729** [comment]
Звернув увагу
![Screenshot_56](https://user-images.githubusercontent.com/109720075/206490499-9931d00e-83c2-43f1-8a35-6e8cf8bc0911.png)
Прописав так як у вимогах. Якщо щось не так ,підкажіть як правильно це описати

**Comment by scholokov** [comment]
fixed
