### ISSUE TITLE
20150623_0711_Croatia/ Відео "2015.07.06 Road Zagreb Hungary - Pinkafeld Austria 01" подорожі"Дорога 06.07.2015"- дата подорожі в прев'ю не співпадає з датою в блокові "Легенда"

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1891]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до відео "2015.07.06 Road Zagreb Hungary - Pinkafeld Austria 01" подорожі"Дорога 06.07.2015"
3.Звернути увагу на дату подорожі

**Фактичний результат:** Дата подорожі в прев'ю не співпадає з датою в блокові "Легенда"
**Очікуваний результат:** Дата подорожі в прев'ю  співпадає з датою в блокові "Легенда" 

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_49](https://user-images.githubusercontent.com/109720075/206409502-ca4b6dd3-ceb7-4bfd-a4d9-5020a3f64a46.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 в Summary краще вказати конкретну проблему, замінивши фразу "не вірна дата"

**Comment by scholokov** [comment]
fixed date on the map
