### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі "Австрія 08.07.2015"- відсутній прапор  Австрії

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1896]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до попередньої "Австрія 08.07.2015"
3.Звернути увагу на прапор Австрії

**Фактичний результат:** Відсутній прапор  Австрії
**Очікуваний результат:** Присутній прапор  Австрії

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_54](https://user-images.githubusercontent.com/109720075/206418640-eb371f46-298a-458d-b4b1-b090f3efb051.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
![Screenshot_59](https://user-images.githubusercontent.com/109720075/206655195-70131da6-d21f-4aec-beed-3d42679ac67b.png)
баг відтворюється

**Comment by scholokov** [comment]
fixed
