### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі "Австрія 08.07.2015"- дата подорожі в прев'ю не співпадає з датою в блокові "Легенда"

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1897]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю "Австрія 08.07.2015"
3.Звернути увагу на дату подорожі

**Фактичний результат:**  Дата подорожі в прев'ю не співпадає з датою в блокові "Легенда"
**Очікуваний результат:** Дата подорожі в прев'ю  співпадає з датою в блокові "Легенда" 

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_55](https://user-images.githubusercontent.com/109720075/206419485-3a1993d1-dd22-4133-baa2-cb7c3c29e3ed.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 в Summary краще вказати конкретну проблему, замінивши фразу "не вірна дата"

**Comment by scholokov** [comment]
дату виправлено на мапі
