### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі "Tiergarten Schoenbrunn, Zoo Vienna 07.07.2015"- відсутній прапор Австрії

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1899]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю "Tiergarten Schoenbrunn, Zoo Vienna 07.07.2015"
3.Звернути увагу на прапор Австрії

**Фактичний результат:** Відсутній прапор Австрії
**Очікуваний результат:** Присутній прапор Австрії

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_68](https://user-images.githubusercontent.com/109720075/206658371-c819df65-5499-4de3-8a64-ed78f867c7f1.png)

**Comment by scholokov** [comment]
fixed
