### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі "Дорога 09.07.2015"- відсутній прапор Австрії та Угорщини

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1900]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю "Дорога 09.07.2015"
3.Звернути увагу на прапор Австрії та Угорщини

**Фактичний результат:** Відсутній прапор Австрії та Угорщини
**Очікуваний результат:** Присутній прапор Австрії та Угорщини

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_69](https://user-images.githubusercontent.com/109720075/206659992-4a6b6d21-c399-4608-b680-36c39c0602b3.png)

**Comment by scholokov** [comment]
fixed
