### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі "Дорога 09.07.2015"- відсутній формат блоку подорожі "Дорога: Австрія-Угорщина "

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1901]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю "09.07.2015"
3.Звернути увагу на назву подорожі

**Фактичний результат:** Відсутній формат блоку подорожі "Дорога:Австрія-Угорщина "
**Очікуваний результат:** Присутній формат блоку подорожі "Дорога: Австрія-Угорщина"

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_70](https://user-images.githubusercontent.com/109720075/206663411-5c5de363-9a6a-4acb-970e-6ed49e076a5d.png)![Screenshot_56](https://user-images.githubusercontent.com/109720075/206490499-9931d00e-83c2-43f1-8a35-6e8cf8bc0911.png)

**Comment by scholokov** [comment]
fixed
