### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі "Готель"- відсутній прапор Угорщини

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1905]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю "Готель",яке знаходиться під прев'ю "Дорога 09.07.2015"
3.Звернути увагу на прапор Угорщини

**Фактичний результат:** Відсутній прапор Угорщини
**Очікуваний результат:** Присутній прапор Угорщини

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_73](https://user-images.githubusercontent.com/109720075/206669846-683fa7d9-3217-4a59-a23e-8e526f094325.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_15](https://user-images.githubusercontent.com/109720075/207028971-28a5f701-ff33-4aba-b273-b0d927d93050.png)

**Comment by scholokov** [comment]
please retets
