### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі "Готель"- відсутній прапор України

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1906]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю "Готель",яке знаходиться над прев'ю "Дома"
3.Звернути увагу на прапор України

**Фактичний результат:** Відсутній прапор України
**Очікуваний результат:** Присутній прапор України

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_74](https://user-images.githubusercontent.com/109720075/206671257-a3c5564f-a907-4687-b19c-fa0c9d00925e.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_16](https://user-images.githubusercontent.com/109720075/207029584-e84e6bb2-ebf2-40c7-98af-61688a9a239d.png)

**Comment by scholokov** [comment]
fixed
