### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі "Дома"- відсутній прапор України

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1910]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю  "Дома"
3.Звернути увагу на прапор України

**Фактичний результат:** Відсутній прапор України
**Очікуваний результат:** Присутній прапор України

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_78](https://user-images.githubusercontent.com/109720075/206674576-a8db6cd8-8e9c-461c-879f-e365940ee38e.png)

**Comment by scholokov** [comment]
на цей блок прапор не потрібен
можна написати баг на дизайн, щоб було зрозуміліше
