### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю над картою та блок "Легенда"-не співпадають кінцеві дати подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1912]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Звернути увагу на кінцеві дати подорожі в прев'ю над картою та блоком "Легенда"

**Фактичний результат:** Не співпадають кінцеві дати подорожі
**Очікуваний результат:**  Кінцеві дати подорожі співпадають

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_81](https://user-images.githubusercontent.com/109720075/206725927-5e75a059-e260-4121-bda5-a96b28242a78.png)

**Comment by scholokov** [comment]
fixed
