### ISSUE TITLE
20080427_Feofania/ Прев'ю подорожі "Київська область, Київ, парк “Феофанія”"- фото прев'ю наполовину затемнене

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1914]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20080427_Feofania/
2.Звернути увагу на фото прев'ю блоку "Київська область, Київ, парк “Феофанія”"

**Фактичний результат:** Фото прев'ю наполовину затемнене
**Очікуваний результат:** Фото прев'ю чітке

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_83](https://user-images.githubusercontent.com/109720075/206732993-359c1b6e-120c-4883-bf90-11d7298450fb.png)

**Comment by scholokov** [comment]
fixed
