### ISSUE TITLE
20080427_Feofania/ Прев'ю подорожі "Київська область, Київ, парк “Феофанія”"-дата подорожі знаходиться під прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1915]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20080427_Feofania/
2.Звернути увагу на дату подорожі прев'ю "Київська область, Київ, парк “Феофанія”"

**Фактичний результат:** Дата подорожі знаходиться під прев'ю
**Очікуваний результат:** Дата подорожі знаходиться в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт) 
![Screenshot_84](https://user-images.githubusercontent.com/109720075/206733699-aa1d0c5c-1042-4db1-a89b-90c31f8e28da.png)

**Comment by scholokov** [comment]
fixed
