### ISSUE TITLE
20080427_Feofania/ Прев'ю подорожі "Інститут еволюційної екології НАН України Парк “Феофанія”"- фото прев'ю відсутнє

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1916]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20080427_Feofania/
2. Проскролити сторінку до прев'ю "Інститут еволюційної екології НАН України Парк “Феофанія”"
3.Звернути увагу на фото прев'ю блоку "Інститут еволюційної екології НАН України Парк “Феофанія”"

**Фактичний результат:** Фото прев'ю відсутнє
**Очікуваний результат:** Фото прев'ю присутнє

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_85](https://user-images.githubusercontent.com/109720075/206734724-3e0153bc-0dde-4071-937b-5cfc52784057.png)

**Comment by scholokov** [comment]
fixed
