### ISSUE TITLE
20080427_Feofania/ Прев'ю подорожі "Інститут еволюційної екології НАН України Парк “Феофанія”"- відсутня дата подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1917]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20080427_Feofania/
2.Проскролити сторінку до прев'ю "Інститут еволюційної екології НАН України Парк “Феофанія”"
3.Звернути увагу на дату подорожі

**Фактичний результат:** Відсутня дата подорожі
**Очікуваний результат:** Присутня дата подорожі 

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_86](https://user-images.githubusercontent.com/109720075/206735368-0b670beb-68ed-443d-8508-ab0110158e02.png)

**Comment by scholokov** [comment]
fixed
