### ISSUE TITLE
20080427_Feofania/ В прев'ю подорожі"Інститут еволюційної екології НАН України Парк “Феофанія”"-відсутній прапор України

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1918]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20080427_Feofania/
2.Проскролити сторінку до прев'ю"Інститут еволюційної екології НАН України Парк “Феофанія” "
3.Звернути увагу на прапор України в прев'ю

**Фактичний результат:** Відсутній прапор України в прев'ю
**Очікуваний результат:** Присутній прапор України в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_87](https://user-images.githubusercontent.com/109720075/206736305-f0a49e76-4fd5-4a6b-81f1-e2adb6265e13.png)

**Comment by scholokov** [comment]
fixed
