### ISSUE TITLE
20080427_Feofania/ Фотогалерея подорожі "Інститут еволюційної екології НАН України Парк “Феофанія”"-при натисканні стрілки для перегляду в  LightBox слідуючого зображення,фото не відображається

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1919]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20080427_Feofania/
2. Проскролити сторінку до фотогалереї  подорожі "Інститут еволюційної екології НАН України Парк “Феофанія”"
3. Клікнути  на перше зображення
4. Зображення завантажилось в LightBox
5. Клікнути на стрілочку з права
6.Звернути увагу на зображення 

**Фактичний результат:** Фото не відображається в LightBox
**Очікуваний результат:** Фото відображається  в LightBox

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_88](https://user-images.githubusercontent.com/109720075/206740007-dc309447-7418-47a2-ad6b-47f495a3bd92.png)
![Screenshot_91](https://user-images.githubusercontent.com/109720075/206740011-8ee08d43-3064-478c-9ae5-75c98e0f3910.png)
![Screenshot_90](https://user-images.githubusercontent.com/109720075/206740041-e51a2ce0-bd68-402f-843c-0c38e32edae5.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 розділіть будь ласка даний баг репорт на 2 окремих

**Comment by scholokov** [comment]
fixed
