### ISSUE TITLE
20080427_Feofania/ Фотогалерея подорожі "Інститут еволюційної екології НАН України Парк “Феофанія”"-нумерація зображення не відповідає розташуванню в галереї

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1920]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20080427_Feofania/
2. Проскролити сторінку до фотогалереї подорожі "Інститут еволюційної екології НАН України Парк “Феофанія”"
3. Клікнути на перше зображення
4.Звернути увагу на нумерацію зображення  

**Фактичний результат:** Нумерація зображення не відповідає розташуванню в галереї
**Очікуваний результат:** Нумерація зображення  відповідає розташуванню в галереї

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_92](https://user-images.githubusercontent.com/109720075/206741121-27240d26-1dd0-4d32-a35a-064fa35fd4a5.png)

**Comment by scholokov** [comment]
fixed
