### ISSUE TITLE
0080427_Feofania/ Фотогалерея подорожі "Інститут еволюційної екології НАН України Парк “Феофанія”"-ключ layout =mosaic

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1921]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20080427_Feofania/
2. Проскролити сторінку до фотогалереї подорожі "Інститут еволюційної екології НАН України Парк “Феофанія”"
3.Відкрити панель розробника
4.Натиснути ctrl+shift+c і клікнути на зображення
5.Знайти data-photonic-query="columns=auto&layout=mosaic
6.Звернути увагу на Ключ layout

**Фактичний результат:** Ключ layout =mosaic
**Очікуваний результат:** Ключ layout=random

**Додаткова інформація :** https://github.com/scholokov/long-travel-2/wiki/2.5-Travel.FotoGallery
**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_17](https://user-images.githubusercontent.com/109720075/207033495-005432c2-39ce-428a-b4e3-61fe785506cb.png)
![Screenshot_18](https://user-images.githubusercontent.com/109720075/207036272-de48e6c9-6e4d-44a1-90ce-e8579d537cda.png)

**Comment by scholokov** [comment]
напевно тут неправильний тип галереї
як перевірити написано у вимогах

**Comment by DmytroMarkulych** [comment]
@andry1729 https://github.com/scholokov/long-travel-2/wiki/2.5-Travel.FotoGallery

**Comment by andry1729** [comment]
@DmytroMarkulych  Я й написав так як у вимогах. Посніть,будь ласка, що не так

**Comment by scholokov** [comment]
fixed
