### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі "Hotel Delminivm, Zagreb, Croatia"- дата подорожі в прев'ю 04.08.2015

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1922]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю "Hotel Delminivm, Zagreb, Croatia"
3.Звернути увагу на дату подорожі

**Фактичний результат:** Дата подорожі в прев'ю 04.08.2015
**Очікуваний результат:** Дата подорожі в прев'ю 04.07.2015

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_11](https://user-images.githubusercontent.com/109720075/206916558-3d199d93-fc06-4c3d-88e3-2e5ba8ddaa1c.png)
![Screenshot_12](https://user-images.githubusercontent.com/109720075/206916560-d8437fa8-9439-4e7b-8d41-88fd88dfaff3.png)

**Comment by scholokov** [comment]
дата виправлена на мапі

**Comment by DmytroMarkulych** [comment]
@andry1729 Варто завести дефект по самому превю

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_26](https://user-images.githubusercontent.com/109720075/209466978-3d954716-0d75-4903-af0b-9e3a02f883c2.png)

**Comment by scholokov** [comment]
please retest
