### ISSUE TITLE
20150623_0711_Croatia/ Прев'ю подорожі "Stadthotel & Restaurant Pinkafeld, Austria "- дата подорожі в прев'ю 06-09.09.2015

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#1923]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20150623_0711_Croatia/
2.Проскролити сторінку до прев'ю "Stadthotel & Restaurant Pinkafeld, Austria "
3.Звернути увагу на дату подорожі

**Фактичний результат:** Дата подорожі в прев'ю 06-09.09.2015
**Очікуваний результат:** Дата подорожі в прев'ю 06-09.07.2015

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_13](https://user-images.githubusercontent.com/109720075/206916710-cc498602-349f-4cd6-9154-6dd29cd79f41.png)
![Screenshot_14](https://user-images.githubusercontent.com/109720075/206916794-fac3c633-980a-445e-955e-1ba043c0cf4e.png)

**Comment by scholokov** [comment]
виправлено на мапі

**Comment by DmytroMarkulych** [comment]
@andry1729 тоді варто завести ще один дефект на саме превю

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_27](https://user-images.githubusercontent.com/109720075/209467012-b7d61a92-3e55-4a3b-9fae-05a7dca1f32e.png)

**Comment by scholokov** [comment]
please retest
