### ISSUE TITLE
20210926_mashrooms/ В preview  немає дати подорожі 

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#1966]
Передумови:
Відкрити https://test.long-travel.live/20210926_mashrooms/
Кроки для відтворення:

1. Зверніть увагу, що  в preview немає дати подорожі

Фактичний результат: В preview немає дати подорожі 
Очікуваний результат: В preview є дати подорожі 

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версия 107.0.5304.122
![image](https://user-images.githubusercontent.com/113175298/207142243-c0fd151c-6d15-41a8-9055-8b76cffa77f3.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
