### ISSUE TITLE
20201025_vedmy/ в другому preview назва подорожі не співпадає є назві у верхньому preview

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#1985]
Передумови:
Відкрити  https://test.long-travel.live/20201025_vedmy/#gallery%5Bphotonic-google-album-1%5D/AE29bMETQdcezF5idA29fUy9T5m0EfcPdF-fpn2Fah4c2ZP2vkikcQw_FXgGbNnqNkKrWDQD4h9-hWEIQGtMdjJs3rHDrBwbFA/

Кроки для відтворення:
1. Зверніть увагу на назву подорожі в верхньому та нижному preview

Фактичний результат:  в другому preview назва подорожі не співпадає є назві  у верхньому preview
Очікуваний результат:  в другому preview назва подорожі співпадає є назві  у верхньому preview

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версия 107.0.5304.122
![ПРЕВЮ 2](https://user-images.githubusercontent.com/113175298/207340528-7f27d2a7-566c-4bd9-a169-54e0daad41f0.png)

**Comment by scholokov** [comment]
а вона і не повинна співпадати
у нас є вимоги до назви, де і прописано якою вона має бути
