### ISSUE TITLE
20170128_konotop/ в preview немає прапора України

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#1988]
Передумови:
Відкрити https://test.long-travel.live/20170128_konotop/
Кроки для відтворення:

1. Зверніть увагу що в previwe немає прапора України
 
Фактичний результат: в preview немає прапора України
Очікуваний результат: в preview є прапор України

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версия 107.0.5304.122
![конотоп прапор](https://user-images.githubusercontent.com/113175298/207364089-9c3e83f8-742c-40a6-9dda-efd1893d014d.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk вкажіть будь ласка прапор якої саме країни

**Comment by Nadiyk** [comment]
Виправила

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
