### ISSUE TITLE
20160814_24_shadsk # 159 - В путешествии отсутствует блок Дорога: Шацк-Київ

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#204]
**Steps to reproduce:**

1. Открыть страницу https://long-travel.live/20160814_24_shadsk/
2. Сравнить наличие блоков с https://legacy.long-travel.live/blog.php?article=20160814_24_Shads

**Actual result:**
В путешествии отсутствует блок  Дорога Шацк-Киев

**Expected result:**
В путешествии присутствуют блок Дорога Шацк-Киев

![Inkedchrome_WyKZxY0RzM1_LI](https://user-images.githubusercontent.com/86321831/139596447-26b4e9af-d7d7-42f5-8d1f-38bf0f883b0f.jpg)

**Environment:**
Windows 10, Google Chrome v. 94.0.4606.81

**Comment by yanadiya** [comment]
Создан на основании бага #200

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
