### ISSUE TITLE
20160814_24_shadsk # 159 - Формат даты видео 14.08.2016 Київ-Світязь не соответствует требованиям

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#205]
**Steps to reproduce:**

1. Открыть страницу https://long-travel.live/20160814_24_shadsk/
2. Обратить внимание на формат даты видео Київ-Світязь

**Actual result:**
Формат даты **14.08.2016** Київ-Світязь **не соответствует** требованиям

**Expected result:**
Формат даты **2016.08.14** Київ-Світязь **соответствует** требованиям

![image](https://user-images.githubusercontent.com/86321831/139596996-f93ee8bb-5dce-48b9-80bc-07b33e1f8fb4.png)

**Environment:**
Windows 10, Google Chrome v. 94.0.4606.81

**Comment by yanadiya** [comment]
заведен на основании #202

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
