### ISSUE TITLE
20210917_19_lviv/ Блок "Легенда"- відсутня пройдена відстань від Family Apartments Dorobok, Lviv до Ресторан Голодний Микола, Lviv

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2051]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Звернути увагу на пройдену відстань від  Family Apartments Dorobok, Lviv до Ресторан Голодний Микола, Lviv в  блокові "Легенда"

**Фактичний результат:** Відсутня пройдена відстань від  Family Apartments Dorobok, Lviv до Ресторан Голодний Микола, Lviv
**Очікуваний результат:** Присутня пройдена відстань від Kyiv,  Family Apartments Dorobok, Lviv до Ресторан Голодний Микола, Lviv

**Додаткова інформація:** https://github.com/scholokov/long-travel-2/wiki/2.6-Travel.Map

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_62](https://user-images.githubusercontent.com/109720075/207583634-93c4158d-3603-4652-a2fc-59a6d6914374.png)
![Screenshot_64](https://user-images.githubusercontent.com/109720075/207584402-e75ac11a-820c-40d3-b059-284ab7bfc423.png)

**Comment by scholokov** [comment]
fixed
