### ISSUE TITLE
20210917_19_lviv/ Блок "Легенда"- відсутня пройдена відстань від Ресторан Голодний Микола, Lviv до Cat Cafe, Lviv

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2052]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Звернути увагу на пройдену відстань від Ресторан Голодний Микола, Lviv до Cat Cafe, Lviv в  блокові "Легенда"

**Фактичний результат:** Відсутня пройдена відстань від Ресторан Голодний Микола, Lviv до Cat Cafe, Lviv
**Очікуваний результат:** Присутня пройдена відстань від  Ресторан Голодний Микола, Lviv до Cat Cafe, Lviv

**Додаткова інформація:** https://github.com/scholokov/long-travel-2/wiki/2.6-Travel.Map

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_62](https://user-images.githubusercontent.com/109720075/207583634-93c4158d-3603-4652-a2fc-59a6d6914374.png)
![Screenshot_65](https://user-images.githubusercontent.com/109720075/207584998-7aec0e82-8243-4158-b2fe-a540252d11e8.png)

**Comment by scholokov** [comment]
fixed
