### ISSUE TITLE
20210917_19_lviv/ Блок "Легенда"- відсутня пройдена відстань від Cat Cafe, Lviv до Ресторан Айвенго, Ровно

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2053]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Звернути увагу на пройдену відстань від Cat Cafe, Lviv до Ресторан Айвенго, Ровно в  блокові "Легенда"

**Фактичний результат:** Відсутня пройдена відстань від Cat Cafe, Lviv до Ресторан Айвенго, Ровно
**Очікуваний результат:** Присутня пройдена відстань від Kyiv, Cat Cafe, Lviv до Ресторан Айвенго, Ровно

**Додаткова інформація:** https://github.com/scholokov/long-travel-2/wiki/2.6-Travel.Map

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_62](https://user-images.githubusercontent.com/109720075/207583634-93c4158d-3603-4652-a2fc-59a6d6914374.png)
![Screenshot_66](https://user-images.githubusercontent.com/109720075/207586076-32486560-b52f-4f4f-b600-c97cd4277455.png)

**Comment by scholokov** [comment]
fixed
