### ISSUE TITLE
20210917_19_lviv/ Блок "Легенда"- відсутня пройдена відстань від Ресторан Айвенго, Ровно до Kyiv, Ukraine

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2054]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Звернути увагу на пройдену відстань від Ресторан Айвенго, Ровно до Kyiv, Ukraine в  блокові "Легенда"

**Фактичний результат:** Відсутня пройдена відстань від Ресторан Айвенго, Ровно до Kyiv, Ukraine
**Очікуваний результат:** Присутня пройдена відстань від Ресторан Айвенго, Ровно до Kyiv, Ukraine

**Додаткова інформація:** https://github.com/scholokov/long-travel-2/wiki/2.6-Travel.Map

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_62](https://user-images.githubusercontent.com/109720075/207583634-93c4158d-3603-4652-a2fc-59a6d6914374.png)
![Screenshot_67](https://user-images.githubusercontent.com/109720075/207586925-baf6c0b2-b2fc-454c-b996-2f7a5767d95e.png)

**Comment by scholokov** [comment]
fixed
