### ISSUE TITLE
20210917_19_lviv/ Блок "Легенда"- відсутня дата подорожі Family Apartments Dorobok, Lviv

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2055]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Звернути увагу на дату подорожі Family Apartments Dorobok, Lviv

**Фактичний результат:** Відсутня дата подорожі Family Apartments Dorobok, Lviv
**Очікуваний результат:** Присутня дата подорожі Family Apartments Dorobok, Lviv

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_68](https://user-images.githubusercontent.com/109720075/207588556-8ceda31a-f518-4104-a8c7-5056cc01d7e6.png)

**Comment by scholokov** [comment]
це ок
дата = попередній, тому не відображається
