### ISSUE TITLE
20210917_19_lviv/ Блок "Легенда"- відсутня дата подорожі Ресторан Голодний Микола, Lviv

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2056]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Звернути увагу на дату подорожі Ресторан Голодний Микола, Lviv в  блокові "Легенда"

**Фактичний результат:** Відсутня дата подорожі Ресторан Голодний Микола, Lviv
**Очікуваний результат:** Присутня дата подорожі Ресторан Голодний Микола, Lviv

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_69](https://user-images.githubusercontent.com/109720075/207589027-23b294c3-fba9-4d74-b6e0-68009fd53b6f.png)

**Comment by scholokov** [comment]
це ок
дата = попередній, тому не відображається
