### ISSUE TITLE
20210917_19_lviv/ Блок "Легенда"- відсутня дата подорожі Cat Cafe, Lviv

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2057]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Звернути увагу на дату подорожі Cat Cafe, Lviv в  блокові "Легенда"

**Фактичний результат:** Відсутня дата подорожі Cat Cafe, Lviv
**Очікуваний результат:** Присутня дата подорожі Cat Cafe, Lviv

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_70](https://user-images.githubusercontent.com/109720075/207589671-0bee7198-d8f8-465e-8247-e48e4598a429.png)

**Comment by scholokov** [comment]
це ок
дата = попередній, тому не відображається
