### ISSUE TITLE
20210917_19_lviv/ Блок "Легенда"- відсутня дата подорожі Ресторан Айвенго, Ровно

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2058]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Звернути увагу на дату подорожі Ресторан Айвенго, Ровно в  блокові "Легенда"

**Фактичний результат:** Відсутня дата подорожі Ресторан Айвенго, Ровно
**Очікуваний результат:** Присутня дата подорожі Ресторан Айвенго, Ровно

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_71](https://user-images.githubusercontent.com/109720075/207590094-038a9834-ca3e-4790-9367-8fa3e6d27b1b.png)

**Comment by scholokov** [comment]
це ок
дата = попередній, тому не відображається
