### ISSUE TITLE
20160814_24_shadsk # 159 - Формат даты видео 15.08.2016 Світязь не соответствует требованиям

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#206]
**Steps to reproduce:**

1. Открыть страницу https://long-travel.live/20160814_24_shadsk/
2. Обратить внимание на формат даты видео 15.08.2016 Світязь

**Actual result:**
Формат даты 15.08.2016 Світязь не соответствует требованиям

**Expected result:**
Формат даты 2016.08.15 Світязь соответствует требованиям

![image](https://user-images.githubusercontent.com/86321831/139597299-9750d0ac-eaf7-41df-bbe3-e6a3b2d54127.png)

**Environment:**
Windows 10, Google Chrome v. 94.0.4606.81

**Comment by yanadiya** [comment]
заведен на основании #202

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
