### ISSUE TITLE
20210508_12months - Header - Structural block "Прев'ю" - Structural block "Назва подорожі" is displays "Демидів"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#2064]
**Steps of reproducing:**
1. Open https://test.long-travel.live/20210508_12months/
2. Pay attention to Structural block "Назва подорожі"

**Expected Result:**
Structural block "Назва подорожі" is displays "Парк XII місяців"

**Actual Result:**
Structural block "Назва подорожі" is displays "Демидів"

**Environment:**
Windows 10, Chrome 108.0.5359.99 (64 bit)
Android 8.1.0, Chrome 108.0.5359.79
![Демидів, Київська область, Україна – Long-Travel - Google Chrome 14 12 2022 17_47_31](https://user-images.githubusercontent.com/95171672/207648093-381090a6-7c6a-4784-a9c2-0a877b81fe15.png)
![photo_2022-12-14_18-08-06](https://user-images.githubusercontent.com/95171672/207648123-6e81681a-721b-4b8b-bd56-4428dfbb71e7.jpg)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
verified. bug isn't reproducing
