### ISSUE TITLE
20210510_stariy_solvin/ 2nd travel's preview, (Дорога Київ - Старий Солотвин) - date mis font  (Open Sans Regular)

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#2065]
Steps:

1) Open page https://test.long-travel.live/20210510_stariy_solvin/
2) Scroll the page down to 2nd preview
3) Pay attention to travel's preview date (10.05.2021)
4) Open dev.tools
5)  Сheck font of the date 

Actual Result: font used - Open Sans Regular

Expected Result: font used - Rubik

Link to Figma https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?t=eLS2ploOlpeBlCPN-0

![Screenshot_4](https://user-images.githubusercontent.com/114935450/210792483-77ef5c10-6fe6-4a9a-8803-6d0ae34f56f0.png)

**Comment by scholokov** [comment]
fied

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
