### ISSUE TITLE
20210917_19_lviv/ Блок "Легенда"- дата Kyiv, Ukraine Dec 4, 2022

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2066]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Звернути увагу на дату Kyiv, Ukraine

**Фактичний результат:** Дата Kyiv, Ukraine -Dec 4, 2022
**Очікуваний результат:** Дата Kyiv, Ukraine -Sept 19, 2022

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_72](https://user-images.githubusercontent.com/109720075/207653319-8bc2bffb-0241-4f5a-b87a-d116f7b34782.png)

**Comment by scholokov** [comment]
це ок
дата = попередній, тому не відображається

**Comment by andry1729** [comment]
Не зрозумів ,зверху Kyiv, Ukraine Dec 4, 2022 дату не можна змінити?
