### ISSUE TITLE
20210917_19_lviv/ Відсутній прапор України в прев'ю "Дорога  Київ- Львів 17.09.2021"

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2067]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Проскролити сторінку до фото прев'ю "Дорога  Київ- Львів 17.09.2021"
3.Звернути увагу на прапор України в прев'ю "Дорога  Київ- Львів 17.09.2021"

**Фактичний результат:** Відсутній прапор України в прев'ю
**Очікуваний результат:** Присутній прапор України в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_73](https://user-images.githubusercontent.com/109720075/207654640-b7f2f918-4b4c-464e-ba69-7b35717115ac.png)

**Comment by scholokov** [comment]
fixed
