### ISSUE TITLE
20210917_19_lviv/ Блок "Легенда"- Ресторан Айвенго, Ровно-назва міста російською мовою

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2068]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Звернути увагу на назву міста Ресторану "Айвенго"в блокові "Легенда"

**Фактичний результат:** Ровно-назва міста російською мовою
**Очікуваний результат:** Рівне-назва міста українською  мовою

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_74](https://user-images.githubusercontent.com/109720075/207656029-569b8ba3-fbc4-4767-8022-a357e12f3798.png)
![Screenshot_75](https://user-images.githubusercontent.com/109720075/207656036-e070e876-6fb9-4083-9715-4971e916f3e2.png)

**Comment by scholokov** [comment]
fixed
