### ISSUE TITLE
20210917_19_lviv/ Фото прев'ю подорожі"Львів 2021"- дата 18-19.09.2021

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2069]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Звернути увагу на дату в фото прев'ю подорожі"Львів 2021"

**Фактичний результат:** Дата подорожі"Львів 2021"- 18-19.09.2021
**Очікуваний результат:** Дата подорожі"Львів 2021"- 17-19.09.2021

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_76](https://user-images.githubusercontent.com/109720075/207657561-6725b9aa-cca9-4f48-ac65-face0e06b2ef.png)

**Comment by scholokov** [comment]
fixed
