### ISSUE TITLE
20160814_24_shadsk # 159 - Формат даты видео 15.08.2016 Світязь-Київ не соответствует требованиям

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#207]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20160814_24_shadsk/
2. Обратить внимание на формат даты видео 15.08.2016 Світязь-Київ

**Actual result:**
Формат даты **15.08.2016** Світязь-Київ **не соответствует** требованиям

**Expected result:**
Формат даты **2016.08.15** Світязь-Київ **соответствует** требованиям

![image](https://user-images.githubusercontent.com/86321831/139597454-d5e09172-c3ce-4062-bd31-d79e0e09ef67.png)

**Environment:**
Windows 10, Google Chrome v. 94.0.4606.81

**Comment by yanadiya** [comment]
заведен на основании #202

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
