### ISSUE TITLE
20210917_19_lviv/ Фото прев'ю подорожі"Львів 2021"- присутня дата у назві міста подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2070]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Звернути увагу на фото прев'ю подорожі"Львів 2021"

**Фактичний результат:** Присутня дата у назві міста подорожі
**Очікуваний результат:** Відсутня дата у назві міста подорожі

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_77](https://user-images.githubusercontent.com/109720075/207658858-15ef8276-f99a-4ac2-826f-c64d47431209.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
баг відтворюється
![Screenshot_103](https://user-images.githubusercontent.com/109720075/208295975-4063dafd-a22f-4d02-bb12-07addfe45ce0.png)

**Comment by scholokov** [comment]
назва формується з вимог
https://github.com/scholokov/long-travel-2/wiki/4.2-Travels.List
