### ISSUE TITLE
20210917_19_lviv/ Фото прев'ю подорожі"Family Apartments Dorobok"- Hotel знаходиться над фото прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2072]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Проскролити сторінку до  прев'ю "Family Apartments Dorobok"
3.Звернути увагу на  фото прев'ю подорожі"Family Apartments Dorobok" 

**Фактичний результат:** Hotel знаходиться над фото прев'ю
**Очікуваний результат:** Hotel знаходиться в фото прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_81](https://user-images.githubusercontent.com/109720075/207844844-c78af69b-ca6c-4a92-89f3-b096f6eaa764.png)

**Comment by scholokov** [comment]
fixed
