### ISSUE TITLE
20210917_19_lviv/ Блок прев'ю подорожі"Family Apartments Dorobok"-відсутнє фото прев'ю подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2073]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Проскролити сторінку до  прев'ю "Family Apartments Dorobok"
3.Звернути увагу на фото прев'ю подорожі  "Family Apartments Dorobok"

**Фактичний результат:** Відсутнє фото прев'ю подорожі
**Очікуваний результат:** Присутнє фото прев'ю подорожі

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_82](https://user-images.githubusercontent.com/109720075/207845534-a4792ea7-31a8-4be3-8c95-129d0a574e8a.png)

**Comment by scholokov** [comment]
fixed
