### ISSUE TITLE
20210917_19_lviv/ Блок прев'ю подорожі"Family Apartments Dorobok"-відсутня дата подорожі в фото прев'ю 

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2074]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Проскролити сторінку до  прев'ю "Family Apartments Dorobok"
3.Звернути увагу на фото прев'ю подорожі  "Family Apartments Dorobok"

**Фактичний результат:** Відсутня дата подорожі в фото прев'ю 
**Очікуваний результат:** Присутня дата подорожі в фото прев'ю 

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_83](https://user-images.githubusercontent.com/109720075/207846229-9f50b255-2e97-49a5-b0f7-6b1702e5977a.png)

**Comment by scholokov** [comment]
fixed
