### ISSUE TITLE
20210917_19_lviv/  Прев'ю подорожі "Family Apartments Dorobok"- відсутній прапор України

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2076]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Проскролити сторінку до прев'ю "Family Apartments Dorobok"
3.Звернути увагу на прапор України в  фото прев'ю "Family Apartments Dorobok"

**Фактичний результат:** Відсутній прапор України
**Очікуваний результат:** Присутній прапор України

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_84](https://user-images.githubusercontent.com/109720075/207846881-2fbae272-75c6-4273-8be5-eea0cd3ea51c.png)

**Comment by scholokov** [comment]
fixed
