### ISSUE TITLE
20210917_19_lviv/ Блок прев'ю подорожі"Львів 18-19.09.2021"-відсутній прапор України

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2078]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Проскролити сторінку до  прев'ю "Львів 18-19.09.2021"
3.Звернути увагу на прапор України в  фото прев'ю "Львів 18-19.09.2021"

**Фактичний результат:** Відсутній прапор України
**Очікуваний результат:** Присутній прапор України

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_86](https://user-images.githubusercontent.com/109720075/207848671-78d112e6-2a7c-40be-bfff-f462d41022e2.png)

**Comment by scholokov** [comment]
fixed
