### ISSUE TITLE
20210917_19_lviv/ Блок прев'ю подорожі"Ресторан Голодний Микола"-відсутнє фото прев'ю подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2079]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Проскролити сторінку до прев'ю "Ресторан Голодний Микола"
3.Звернути увагу на фото прев'ю подорожі "Ресторан Голодний Микола"

**Фактичний результат:** Відсутнє фото прев'ю подорожі
**Очікуваний результат:** Присутнє фото прев'ю подорожі

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_87](https://user-images.githubusercontent.com/109720075/207849184-39439f93-542c-499c-a572-66422b99ebf2.png)

**Comment by scholokov** [comment]
fixed
