### ISSUE TITLE
20210917_19_lviv/ Блок прев'ю подорожі"Ресторан Голодний Микола"-відсутній прапор України

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2080]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Проскролити сторінку до прев'ю "Ресторан Голодний Микола"
3.Звернути увагу на прапор України в фото прев'ю "Ресторан Голодний Микола"

**Фактичний результат:** Відсутній прапор України
**Очікуваний результат:** Присутній прапор України

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_88](https://user-images.githubusercontent.com/109720075/207849620-903f2c64-0525-4c59-91c4-2a2e2535966b.png)

**Comment by scholokov** [comment]
fixed

**Comment by andry1729** [comment]
Баг відтворюється
![Screenshot_102](https://user-images.githubusercontent.com/109720075/208295737-d85dd1a6-3e7a-40ea-8cd2-c1ca51640815.png)

**Comment by scholokov** [comment]
fixed
