### ISSUE TITLE
20210917_19_lviv/ Блок прев'ю подорожі"Ресторан Голодний Микола"-відсутня дата подорожі в фото прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2081]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Проскролити сторінку до прев'ю "Ресторан Голодний Микола"
3.Звернути увагу на фото прев'ю подорожі "Ресторан Голодний Микола"

**Фактичний результат:** Відсутня дата подорожі в фото прев'ю
**Очікуваний результат:** Присутня дата подорожі в фото прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_89](https://user-images.githubusercontent.com/109720075/207850028-bf0bbcc0-e208-471e-9cf6-7d4a6db8e5d0.png)

**Comment by scholokov** [comment]
fixed
