### ISSUE TITLE
20210917_19_lviv/ Блок прев'ю подорожі"Cat Cafe"-відсутнє фото прев'ю подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2082]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Проскролити сторінку до прев'ю "Cat Cafe"
3.Звернути увагу на фото прев'ю подорожі "Cat Cafe"

**Фактичний результат:** Відсутнє фото прев'ю подорожі
**Очікуваний результат:** Присутнє фото прев'ю подорожі

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_90](https://user-images.githubusercontent.com/109720075/207850535-ecbfff75-b7db-4817-86ec-9ed06246b70d.png)

**Comment by scholokov** [comment]
fixed
