### ISSUE TITLE
20210917_19_lviv/ Блок прев'ю подорожі"Cat Cafe"-відсутня дата подорожі в фото прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2083]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Проскролити сторінку до прев'ю "Cat Cafe"
3.Звернути увагу на фото прев'ю подорожі "Cat Cafe"

**Фактичний результат:** Відсутня дата подорожі в фото прев'ю
**Очікуваний результат:** Присутня дата подорожі в фото прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_91](https://user-images.githubusercontent.com/109720075/207850979-c0fe4808-024f-4c1c-8c3f-38501e4ea51b.png)

**Comment by scholokov** [comment]
fixed
