### ISSUE TITLE
20210917_19_lviv/ Блок прев'ю подорожі"Cat Cafe"-відсутній прапор України

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2084]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Проскролити сторінку до прев'ю "Cat Cafe"
3.Звернути увагу на прапор України в фото прев'ю "Cat Cafe"

**Фактичний результат:** Відсутній прапор України
**Очікуваний результат:** Присутній прапор України

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_92](https://user-images.githubusercontent.com/109720075/207851501-f54efc0b-cd15-44f8-8aa3-30fda8e62ee7.png)

**Comment by scholokov** [comment]
fixed
