### ISSUE TITLE
20210917_19_lviv/ Блок прев'ю подорожі"Дорога Львів – Київ"-відсутнє фото прев'ю подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2085]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Проскролити сторінку до прев'ю "Дорога Львів – Київ"
3.Звернути увагу на фото прев'ю подорожі "Дорога Львів – Київ"

**Фактичний результат:** Відсутнє фото прев'ю подорожі
**Очікуваний результат:** Присутнє фото прев'ю подорожі

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_93](https://user-images.githubusercontent.com/109720075/207852083-8c613324-9f8c-4377-9e1b-9f91932f9e74.png)

**Comment by scholokov** [comment]
fixed
