### ISSUE TITLE
20210917_19_lviv/ Блок прев'ю подорожі"Дорога Львів – Київ"-відсутня дата подорожі в фото прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2086]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Проскролити сторінку до прев'ю "Дорога Львів – Київ"
3.Звернути увагу на фото прев'ю подорожі "Дорога Львів – Київ"

**Фактичний результат:** Відсутня дата подорожі в фото прев'ю
**Очікуваний результат:** Присутня дата подорожі в фото прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_94](https://user-images.githubusercontent.com/109720075/207852607-fcc40652-b0ff-4908-a169-9bf000fb6efc.png)

**Comment by scholokov** [comment]
fixed
