### ISSUE TITLE
20210917_19_lviv/ Блок прев'ю подорожі"Дорога Львів – Київ"-відсутній прапор України

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2087]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Проскролити сторінку до прев'ю "Дорога Львів – Київ"
3.Звернути увагу на прапор України в фото прев'ю "Дорога Львів – Київ"

**Фактичний результат:** Відсутній прапор України
**Очікуваний результат:** Присутній прапор України

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_95](https://user-images.githubusercontent.com/109720075/207853075-221e398c-c978-4d49-bd31-9f2559fbf0cf.png)

**Comment by scholokov** [comment]
fixed
