### ISSUE TITLE
20210917_19_lviv/ Блок прев'ю подорожі"Ресторан Айвенго Ровно"-відсутнє фото прев'ю подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2088]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Проскролити сторінку до прев'ю "Ресторан Айвенго Ровно"
3.Звернути увагу на фото прев'ю подорожі "Ресторан Айвенго Ровно"

**Фактичний результат:** Відсутнє фото прев'ю подорожі
**Очікуваний результат:** Присутнє фото прев'ю подорожі

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_96](https://user-images.githubusercontent.com/109720075/207853808-324579b4-a2dd-43d5-9633-58a0acaa53eb.png)

**Comment by scholokov** [comment]
fixed
