### ISSUE TITLE
20210917_19_lviv/ Блок прев'ю подорожі""Ресторан Айвенго Ровно"-відсутня дата подорожі в фото прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2089]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Проскролити сторінку до прев'ю "Ресторан Айвенго Ровно"
3.Звернути увагу на фото прев'ю подорожі "Ресторан Айвенго Ровно"

**Фактичний результат:** Відсутня дата подорожі в фото прев'ю
**Очікуваний результат:** Присутня дата подорожі в фото прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_97](https://user-images.githubusercontent.com/109720075/207854516-2be5ceef-677c-444a-8077-26d46bb973cb.png)

**Comment by scholokov** [comment]
fixed
