### ISSUE TITLE
20160814_24_shadsk # 159 - Название страны промежуточной точки База отдыха Свитязь, Світязь, Украина не соответствует языку страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#209]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20160814_24_shadsk/
2. В контенте страницы найти промежуточную точку База отдыха Свитязь, Світязь, Украина
3. Обратить внимание на язык страны названия промежуточной точки

**Actual result:**
Название промежуточной точки **не соответствует** языку страны - База отдыха Свитязь, Світязь, **Украина**

**Expected result:**
Название промежуточной точки **соответствует** языку страны -База отдыха Свитязь, Світязь, **Україна**

![image](https://user-images.githubusercontent.com/86321831/139597991-3e4fb395-be15-4ffd-bd87-58f5478425b9.png)

**Environment:**
Windows 10, Google Chrome v. 94.0.4606.81

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
