### ISSUE TITLE
20210917_19_lviv/ Блок прев'ю подорожі"Ресторан Айвенго Ровно"-відсутній прапор України

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2090]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Проскролити сторінку до прев'ю "Ресторан Айвенго Ровно"
3.Звернути увагу на прапор України в фото прев'ю "Ресторан Айвенго Ровно"

**Фактичний результат:** Відсутній прапор України
**Очікуваний результат:** Присутній прапор України

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_98](https://user-images.githubusercontent.com/109720075/207854973-0126f579-c970-4246-88ed-0dcd9d1cc73b.png)

**Comment by scholokov** [comment]
fixed
