### ISSUE TITLE
20210917_19_lviv/ Блок прев'ю подорожі"Ресторан Айвенго Ровно"- Ровно написано російською мовою

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2091]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210917_19_lviv/
2.Проскролити сторінку до прев'ю "Ресторан Айвенго Ровно"
3.Звернути увагу на назву міста в фото прев'ю "Ресторан Айвенго Ровно"

**Фактичний результат:** м.Ровно -написано російською мовою
**Очікуваний результат:** м.Рівне- написано українською  мовою

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_75](https://user-images.githubusercontent.com/109720075/207855677-8a1a265a-fc83-44f2-9e6d-45012bf35e9c.png)
![Screenshot_99](https://user-images.githubusercontent.com/109720075/207855702-d317852c-f10c-4acf-a76c-f61303863fb3.png)

**Comment by scholokov** [comment]
fixed
