### ISSUE TITLE
20210510_stariy_solvin/ Travel Map, Legend, detailed information button (Staryi Solotvyn - 173.4 km) - mis distance number ( 363.7)

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#2092]
Steps:

1) Open page https://test.long-travel.live/20210510_stariy_solvin/
2) Pay attention to travel map and the legend on it (Staryi Solotvyn - 173.4 km)
3) Click to button of distance (173.4 km)  to open detailed information

Actual Result: miss distance number - 363.7 

Expected Result: distance number - 173.4

![Screenshot_2](https://user-images.githubusercontent.com/114935450/207857846-1f2f8164-9278-4cc2-872f-5ed3fa21d1e6.png)

**Comment by scholokov** [comment]
але це відображається сумарна кількість пройденого шляху, за даним видом транспорту...

**Comment by MarynaChurylo** [comment]
is not a bug
