### ISSUE TITLE
20210510_stariy_solvin/ Travel Map, Legend, detailed information button (Kyiv, Ukraine - 190.3 km) - mis distance number (363.7)

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#2095]
Steps:

1) Open page https://test.long-travel.live/20210510_stariy_solvin/
2) Pay attention to travel map and the legend on it (Kyiv, Ukraine - 190.3 km)
3) Click to button of distance (190.3 km) to open detailed information

Actual Result: miss distance number - 363.7

Expected Result: distance number - 190.3

![Screenshot_2](https://user-images.githubusercontent.com/114935450/207868817-7fe3fcba-0d6c-43a3-b83e-4c7918407503.png)

**Comment by scholokov** [comment]
але це відображається сумарна кількість пройденого шляху, за даним видом транспорту...

**Comment by MarynaChurylo** [comment]
is not a bug
