### ISSUE TITLE
20210926_mashrooms/ В preview немає дати подорожі

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#2100]
Передумови :
Відкрити https://test.long-travel.live/20210926_mashrooms/

Кроки для відтворення.

1. Зверніть увагу, що в preview немає дати подорожі

Фактичний результат: В preview немає дати подорожі
Очікуваний результат: В preview є дати подорожі

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версія 107.0.5304.88
![гриби дата](https://user-images.githubusercontent.com/113175298/207942235-e4128290-518e-4efd-b8b4-56d01d4a4932.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
