### ISSUE TITLE
20210510_stariy_solvin/ Travel map, Legend - mis background-color (#f0f0f0)

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#2101]
Steps:

1) Open page https://test.long-travel.live/20210510_stariy_solvin/
2) Pay attention to travel map and the legend on it 

Actual Result: legend background-color  #f0f0f0

Expected Result:  legend background-color  #FFFFFF   5%

Link to Figma specifications https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1201%3A27&t=OCBvC8ADqRW5AEXn-0

![Screenshot_3](https://user-images.githubusercontent.com/114935450/207941959-e6e87240-f8ea-461c-ac0b-8cdfd42a917f.png)

**Comment by poroskundenys** [comment]
Сейчас нельзя поменять стили карты так как сделано на макете. Возможно в будущем можно будет.
Вот ответ поддержки TravelMap
No, at the moment you can't change the text and background colors.
It looks quite good though. So I might add a dark mode theme option with our Premium Plus offer in the future. But for now it'll stay white.

**Comment by MarynaChurylo** [comment]
technical limitation
