### ISSUE TITLE
20210926_mashrooms/ після карти немає preview

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#2102]
Передумови 
Відкрити  https://test.long-travel.live/20210926_mashrooms/
Кроки для відтворення:

1. Зверніть увагу що після карти немає preview   

Фактичний результат:  після карти немає preview
Очікуваний результат:  після карти є preview

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версия 107.0.5304.122
![після карти немає превю](https://user-images.githubusercontent.com/113175298/207949106-0fd78419-8624-4da7-b6fc-2406a5a112b9.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
