### ISSUE TITLE
20200719_belya_tsercov # 23 - Язык названия путешествия не соответствует языку страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#212]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20200719_belya_tsercov/
2. Обратить внимание на язык названия путешествия

**Actual result:**
Название путешествия **не соответствует** языку страны

**Expected result:**
Название путешествия **соответствует** языку страны

![image](https://user-images.githubusercontent.com/86321831/140622676-ebdf5b03-6e63-4d23-bf4d-db2baec29f57.png)

**Environment:**
Windows 10, Google Chrome v. 95.0.4638.69

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
