### ISSUE TITLE
20200719_belya_tsercov #23 - Размер символов даты путешествия не соответствует требованиям

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#214]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20200719_belya_tsercov/
2. Обратить внимание на размер символов даты путешествия

**Actual result:**
Размер символов даты путешествия не соответствует требованиям

**Expected result:**
Размер символов даты путешествия соответствует требованиям 

![image](https://user-images.githubusercontent.com/86321831/140623728-d4512e02-8f6f-45b9-97a4-cd40e6fb1774.png)

**Environment:**
Windows 10, Google Chrome v. 95.0.4638.69

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
