### ISSUE TITLE
20210917_19_lviv/ Блок "Легенда "подорожей -подорож розташована після подорожі"20201025_vedmy"

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2141]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/travels/
2.Проскролити в блокові "Легенда" до подорожі 20210917_19_lviv
3.Звернути увагу на розташування подорожі в блокові "Легенда"

**Фактичний результат:** Подорож розташована після подорожі"20201025_vedmy"
**Очікуваний результат:** Подорож розташована після подорожі"20210912_lazalky"

**Додаткова інформація:**https://github.com/scholokov/long-travel-2/wiki/4.2-Travels.List

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_48](https://user-images.githubusercontent.com/109720075/208255465-e0b06f4c-a39c-4a3b-9601-e95a571f1804.png)
![Screenshot_49](https://user-images.githubusercontent.com/109720075/208255467-aff3a96a-9922-46cf-bfaf-338ebebe8630.png)

**Comment by scholokov** [comment]
fixed
