### ISSUE TITLE
20070406_09_Lviv/ Прев'ю подорожі "Львів_Львівска область_Україна"- фото прев'ю наполовину затемнене

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2143]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20070406_09_Lviv/
2.Звернути увагу на фото прев'ю блоку "Львів_Львівска область_Україна"

**Фактичний результат:** Фото прев'ю наполовину затемнене
**Очікуваний результат:** Фото прев'ю чітке 

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_53](https://user-images.githubusercontent.com/109720075/208256339-04e37e9c-23b6-4af1-8929-61df76145c91.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
