### ISSUE TITLE
20200719_belya_tsercov # 23 - Формат карты не соответствует требованиям

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#215]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20200719_belya_tsercov/
2. Обратить внимание на карту

**Actual result:**
Формат карты **не соответствует** требованиям

**Expected result:**
Формат карты **соответствует** требованиям

![image](https://user-images.githubusercontent.com/86321831/140623985-2ce6b8b2-052e-4685-9577-fec3048ea95f.png)

**Environment:**
Windows 10, Google Chrome v. 95.0.4638.69

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
