### ISSUE TITLE
20200719_belya_tsercov # 23- На карте отсутствует схема путешествия с пройденным расстоянием

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#216]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20200719_belya_tsercov/
2. Обратить внимание на карту

**Actual result:**
На карте  **отсутствует** схема путешествия с пройденным расстоянием

**Expected result:**
На карте  **присутствует** схема путешествия с пройденным расстоянием

![image](https://user-images.githubusercontent.com/86321831/140624252-49626068-f285-4264-969a-a56097e1bdbd.png)

**Environment:**
Windows 10, Google Chrome v. 95.0.4638.69

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
