### ISSUE TITLE
20200719_belya_tsercov # 23 - Ошибка загрузки видео

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#217]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20200719_belya_tsercov/
2. Спуститься вниз страницы до видео

**Actual result:**
Видео **недоступно**

**Expected result:**
Видео **загружается**

![image](https://user-images.githubusercontent.com/86321831/140624568-f40995f6-9d0b-4c19-aea2-dac0609b849f.png)

**Environment:**
Windows 10, Google Chrome v. 95.0.4638.69

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
