### ISSUE TITLE
20151031_haisyn_uman/ Блок "Легенда"-Дендропарк "Софиевка", Умань- Софиевка на російській мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2175]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20151031_haisyn_uman/
2.Звернути увагу на назву подорожі "Дендропарк "Софиевка", Умань" в блокові легенда

**Фактичний результат:** Слово "Софиевка" на російській мові
**Очікуваний результат:** Слово "Софіївка" на українській  мові

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_108](https://user-images.githubusercontent.com/109720075/208300177-96ce689a-1baf-48ab-a7bf-939f2f86823d.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
