### ISSUE TITLE
20151031_haisyn_uman/ Блок прев'ю"Гайсинська ДЮСШ Гайсин, Вінницька обл., Україна 31.10.2015"-опис під подорожжю на російській мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2176]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20151031_haisyn_uman/
2.Проскролити сторінку до блоку прев'ю"Гайсинська ДЮСШ Гайсин, Вінницька обл., Україна 31.10.2015"
2.Звернути увагу на опис під  прев'ю подорожі "Гайсинська ДЮСШ Гайсин, Вінницька обл., Україна 31.10.2015"

**Фактичний результат:** Опис під подорожжю на російській мові
**Очікуваний результат:** Опис під подорожжю на українській мові

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_109](https://user-images.githubusercontent.com/109720075/208300396-2fcb216b-c3e2-4bb5-a2b4-60533fe08f50.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
