### ISSUE TITLE
20151031_haisyn_uman/Фотогалерея блоку прев'ю "Гайсинська ДЮСШ Гайсин, Вінницька обл., Україна 31.10.2015"- опис під фотогалереєю на російській мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2177]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20151031_haisyn_uman/
2.Проскролити сторінку до фотогалереї блоку прев'ю "Гайсинська ДЮСШ Гайсин, Вінницька обл., Україна 31.10.2015"
2.Звернути увагу на опис під фотогалереєю подорожі "Гайсинська ДЮСШ Гайсин, Вінницька обл., Україна 31.10.2015"

**Фактичний результат:** Опис під фотогалереєю на російській мові
**Очікуваний результат:** Опис під фотогалереєю на українській мові

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_110](https://user-images.githubusercontent.com/109720075/208300640-87bd9ed9-3f36-436e-ac77-92a3d9ed9006.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
