### ISSUE TITLE
20151031_haisyn_uman/ Блок прев'ю"Mіnі Gotel Pozitiv c.Городецьке 31.10-01.11.2015"-опис під подорожжю на російській мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2178]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20151031_haisyn_uman/
2.Проскролити сторінку до блоку прев'ю"Mіnі Gotel Pozitiv c.Городецьке 31.10-01.11.2015"
2.Звернути увагу на опис під прев'ю подорожі "Mіnі Gotel Pozitiv c.Городецьке 31.10-01.11.2015"

**Фактичний результат:** Опис під подорожжю на російській мові
**Очікуваний результат:** Опис під подорожжю на українській мові

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_111](https://user-images.githubusercontent.com/109720075/208300738-f9ab234f-af3f-4508-b484-6e2ff7df6f7a.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
