### ISSUE TITLE
20151031_haisyn_uman/ Відео "Ukraine - Uman -Sofiivka" блоку прев'ю "Дендропарк “Софіївка” Умань 01.11.2015"-відсутня дата подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2179]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20151031_haisyn_uman/
2.Проскролити сторінку до відео Ukraine - Uman -Sofiivka" з блоку прев'ю "Дендропарк “Софіївка” Умань 01.11.2015"
2.Звернути увагу на дату  відео Ukraine - Uman -Sofiivka" з блоку прев'ю "Дендропарк “Софіївка” Умань 01.11.2015"

**Фактичний результат:**  Відсутня дата подорожі
**Очікуваний результат:** Дата подорожі присутня

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_112](https://user-images.githubusercontent.com/109720075/208301095-9128421b-fff1-4ab2-b286-eba76d9f372c.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
