### ISSUE TITLE
20151031_haisyn_uman/ Відео "Ukraine - Uman -Sofiivka" блоку прев'ю "Дендропарк “Софіївка” Умань 01.11.2015"-назва подорожі на англійській мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2180]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20151031_haisyn_uman/
2.Проскролити сторінку до відео Ukraine - Uman -Sofiivka" з блоку прев'ю "Дендропарк “Софіївка” Умань 01.11.2015"
2.Звернути увагу на назву  відео Ukraine - Uman -Sofiivka" з блоку прев'ю "Дендропарк “Софіївка” Умань 01.11.2015"

**Фактичний результат:** Назва подорожі на англійській мові
**Очікуваний результат:** Назва подорожі на українській  мові

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_113](https://user-images.githubusercontent.com/109720075/208301208-beb65e18-ba43-468c-8932-00c5dfd35039.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
