### ISSUE TITLE
20170805_20_odessa # 160 - Отсутствуют даты путешествия

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#220]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20170805_20_odessa/
2. Обратить внимание на даты путешествия

**Actual result:**
Даты **отсутствуют**

**Expected result:**
Даты **присутствуют**

![image](https://user-images.githubusercontent.com/86321831/140625891-bc39d24d-097f-4a23-a339-65ff61cfc9cd.png)

**Environment:**
Windows 10, Google Chrome v. 95.0.4638.69

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
