### ISSUE TITLE
20170805_20_odessa # 160 - Отсутствует изображение превью

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#222]
Steps to reproduce:
1. Открыть страницу https://long-travel.live/
2. Найти путешествие 20170805_20_odessa
3. Обратить внимание на изображение превью

Actual result:
Изображение превью  **отсутствует**

Expected result:
Изображение превью  **присутствует**

![image](https://user-images.githubusercontent.com/86321831/140626243-79ad031e-a15c-4fcf-a801-a7fed8174e66.png)

Environment:
Windows 10, Google Chrome v. 95.0.4638.69

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
