### ISSUE TITLE
20151226_Kiev_Fashion_Park/ Блок прев'ю під картою-відсутній блок прев'ю з назвою,датою та прапором України

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2227]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20151226_Kiev_Fashion_Park/
2.Проскролити сторінку до блоку  прев'ю під картою
3.Звернути увагу на блок прев'ю під картою

**Фактичний результат:** Відсутній блок прев'ю з назвою,датою та прапором України
**Очікуваний результат:** Присутній блок прев'ю з назвою,датою та прапором України

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_46](https://user-images.githubusercontent.com/109720075/208450005-9af78b7c-3b7b-4e98-95a5-cea42188c1b6.png)

**Comment by scholokov** [comment]
fixed
