### ISSUE TITLE
20160518_22_Eger/Блок прев'ю подорожі "Ámbitus-ház Magyarország, Egerszalók 17-20.05.2016"- опис подорожі написано на російській мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2233]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20160518_22_Eger/
2.Проскролити сторінку до прев'ю "Ámbitus-ház Magyarország, Egerszalók 17-20.05.2016"
3.Звернути увагу на опис подорожі під прев'ю "Ámbitus-ház Magyarország, Egerszalók 17-20.05.2016"

**Фактичний результат:** Опис подорожі написано на російській мові
**Очікуваний результат:** Опис подорожі написано на українській мові

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_52](https://user-images.githubusercontent.com/109720075/208458319-af3029ea-61f8-46e6-80cf-9db93f885124.png)
![Screenshot_53](https://user-images.githubusercontent.com/109720075/208458340-8ff43ef3-94fa-4d67-af6d-0ea32fb71c3f.png)

**Comment by scholokov** [comment]
fixed
