### ISSUE TITLE
20170805_20_odessa # 160 - Отсутствует разделение на блоки

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#224]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20170805_20_odessa/
2. Сравнить контент страницы с https://legacy.long-travel.live/blog.php?article=20170805_20_Odessa
3. Обратить внимание на блоки путешествия

**Actual result:**
Разделение на блоки **отсутствует**

**Expected result:**
Разделение на блоки **присутствует**

![image](https://user-images.githubusercontent.com/86321831/140626483-aef759b1-435f-4d69-87cc-188dba1700f9.png)

Environment:
Windows 10, Google Chrome v. 95.0.4638.69

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
