### ISSUE TITLE
20160814_24_shadsk/ Фотогалерея блоку прев'ю подорожі"Дорога: Київ – Світязь"-тип галереї mosaic

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2258]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20160814_24_shadsk/
2.Проскролити сторінку до фотогалереї прев'ю "Дорога: Київ – Світязь"
3.Зайти в DevTools і в div знайти параметр layout
4.Звернути увагу на  параметр layout

**Фактичний результат:** Тип галереї mosaic
**Очікуваний результат:** Тип галереї random

**Додаткова інформація:** https://github.com/scholokov/long-travel-2/wiki/2.5-Travel.FotoGallery

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_79](https://user-images.githubusercontent.com/109720075/208486403-19fc6b6b-d0b1-4c7f-9edf-290ab4f749b9.png)
![Screenshot_80](https://user-images.githubusercontent.com/109720075/208486409-98e57a07-2131-4f0b-a7c2-f0c890ec7d93.png)

**Comment by scholokov** [comment]
fixed
