### ISSUE TITLE
20180428_0501_beregovo # 162 - Отсутствует превью изображение

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#226]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/
2. Найти путешествие 20180428_0501_beregovo
3. Обратить внимание на изображение превью

**Actual result:**
Изображение превью **отсутствует**

**Expected result:**
Изображение превью **присутствует**

![image](https://user-images.githubusercontent.com/86321831/140799090-5c9f81e2-e95b-4895-8506-f73213352cf6.png)

**Environment:**
Windows 10, Google Chrome v. 95.0.4638.69

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
