### ISSUE TITLE
20210814_24_sergeevka_odessa/preview header page is displayed with a blackout when loading the start page of the trip

### ISSUE THREAD

**Issue by SOlkhova** [scholokov/long-travel-2#2260]
**Steps to reproduce:**
1. Open page: https://test.long-travel.live/20210814_24_sergeevka_odessa/
2. Pay attention to the preview header page is displayed with a blackout

**Actual Result:**
1. Preview header page is displayed with a blackout

![Screenshot 2022-12-15 at 16 08 03](https://user-images.githubusercontent.com/99362773/208512183-da87332d-7cd7-40b6-8ebe-4ad309cb7b49.png)

**Expected Result:**
1. Preview header page without the dark part of the preview

![Screenshot 2022-12-15 at 16 08 21](https://user-images.githubusercontent.com/99362773/208512859-c796d412-a828-400f-8f64-a5eb28fb84bd.png)

**Comment by DmytroMarkulych** [comment]
@SOlkhova Чудово, тільки давайте винесимо скріни окремо, вже після Актуального і Очікуваного результатів

**Comment by SOlkhova** [comment]
Steps to reproduce:
1. Open page: https://test.long-travel.live/20210814_24_sergeevka_odessa/
2. Pay attention to the preview header page is displayed with a blackout


Actual Result:
1. Preview header page is displayed with a blackout

Expected Result:
1. Preview header page without the dark part of the preview

Attachment:
![Screenshot 2022-12-15 at 16 08 03](https://user-images.githubusercontent.com/99362773/209350307-3bdaa45b-0c9f-45f5-9f59-de30883d31d1.png)

![Screenshot 2022-12-15 at 16 08 21](https://user-images.githubusercontent.com/99362773/209350363-698fb453-839e-4ccf-8666-5d65b546e052.png)

**Comment by SOlkhova** [comment]
@DmytroMarkulych Дякую. Виправила.

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
@scholokov verified
