### ISSUE TITLE
20170128_konotop/  in the preview, the publication date does not meet the requirements

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#2273]
Prerequisites:
Open https://test.long-travel.live/20170128_konotop/
Steps to play:

1. Pay attention to the date in the preview

Actual result:  in the preview, the publication date does not meet the requirements
Expected result:  in the preview, the date of publication meets the requirements

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 107.0.5304.122

![data not good](https://user-images.githubusercontent.com/113175298/208716869-237cf179-62fd-496c-b919-91ace63ddb5f.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
Pass
