### ISSUE TITLE
20170128_konotop/  on a trip, after preview  not map  

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#2274]
Prerequisites:
Open https://test.long-travel.live/20170128_konotop/
Steps to play:

1.  Note that it does not map after the preview

Actual result:  after preview, no map
Expected result:  a map is displayed after the preview

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 107.0.5304.122
![after prevy](https://user-images.githubusercontent.com/113175298/208721154-6eea3c16-8558-4193-91ec-8d305677b6ae.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk давайте спробуємо переформулювати так, що не використовувати there is

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk а як щодо Expected Result?

**Comment by Nadiyk** [comment]
виправила

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
Pass
