### ISSUE TITLE
20180428_0501_beregovo # 162- Название путешествия не соответствует языку страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#228]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на название путешествия

**Actual result:**
Название путешествия - **20180428_0501_Beregovo**

**Expected result:**
Название путешествия - **Берегове**

![image](https://user-images.githubusercontent.com/86321831/140802955-42d2f08f-2e38-41d7-8a13-b5b9d599fde5.png)

**Environment:**
Windows 10, Google Chrome v. 95.0.4638.69

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
