### ISSUE TITLE
20170115_kiev_Zoo_12_month/Фото прев'ю подорожі "Зоопарк XII Месяців 15.01.2017"- граматична помилка в слові "Месяців"

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2283]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20170115_kiev_Zoo_12_month/
2.Звернути увагу на назву в фото прев'ю блоку "Зоопарк XII Месяців 15.01.2017"

**Фактичний результат:**  Граматична помилка в слові "Месяців"
**Очікуваний результат:**  Граматична помилка в слові "Місяців" відсутня

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_21](https://user-images.githubusercontent.com/109720075/209122398-7a561d01-dcaa-4f69-a8bb-d7210595dc7e.png)
![Screenshot_22](https://user-images.githubusercontent.com/109720075/209122414-d0329bf1-6535-46b2-8167-8070c5f73e87.png)

**Comment by scholokov** [comment]
fixed
