### ISSUE TITLE
20180428_0501_beregovo # 162 - Отсутствую даты путешествия

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#229]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на даты путешествия

**Actual result:**
Даты **отсутствуют**

**Expected result:**
Даты **присутствуют**

![image](https://user-images.githubusercontent.com/86321831/140811325-08e2d137-285c-4dc2-9f80-b6d516fa6f05.png)

**Environment:**
Windows 10, Google Chrome v. 95.0.4638.69

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
