### ISSUE TITLE
20170417_kiylov/ Фотогалерея блоку прев'ю подорожі"Кийлів – Пикник,17.04.2017"-тип галереї mosaic

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2295]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20170417_kiylov/
2.Проскролити сторінку до фотогалереї прев'ю "Кийлів – Пикник,17.04.2017"
3.Зайти в DevTools і в div знайти параметр layout
4.Звернути увагу на параметр layout

**Фактичний результат:** Тип галереї mosaic
**Очікуваний результат:** Тип галереї random

**Додаткова інформація:** https://github.com/scholokov/long-travel-2/wiki/2.5-Travel.FotoGallery

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт) ![Screenshot_79](https://user-images.githubusercontent.com/109720075/208486403-19fc6b6b-d0b1-4c7f-9edf-290ab4f749b9.png)
![Screenshot_34](https://user-images.githubusercontent.com/109720075/209137269-240a3712-93aa-45ad-abe2-19f8bb640c61.png)

**Comment by scholokov** [comment]
fixed
