### ISSUE TITLE
20180428_0501_beregovo # 162 - Отсутствует карта и схема с пройденным расстоянием

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#230]
**Steps to reproduce:**
1. Открыть страницуhttps://long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на карту путешествия и схему с пройденным расстоянием

**Actual result:**
Карта  и схема с пройденным расстоянием **отсутствуют**

**Expected result:**
Карта и схема с пройденным расстоянием **присутствуют**

![image](https://user-images.githubusercontent.com/86321831/140812325-cd1e75ef-6c20-4a4f-a81a-7e8a683396f2.png)

**Environment:**
Windows 10, Google Chrome v. 95.0.4638.69

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
