### ISSUE TITLE
Figma (specifications bug). Mis size of country's flag (17.33px)

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#2309]
Steps:

1) Open page https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1800%3A77&t=jtQM33PVytTXWQRa-0
2) Pay attention to county's flag size

Actual Result: width:  height: 17.33px;

Expected Result: width:  height: 18px;

![Screenshot_1](https://user-images.githubusercontent.com/114935450/209147781-72c92ed9-aaf9-4a7b-8566-2a2f87b3b432.png)

**Comment by DmytroMarkulych** [comment]
@MarynaChurylo додайте, будь ласка, тег що це дефект в документації)

**Comment by MarynaChurylo** [comment]
Виправила

**Comment by DmytroMarkulych** [comment]
@MarynaChurylo  додайте тег тут)
![image](https://user-images.githubusercontent.com/88647733/209812292-1638d039-6ee9-45fe-8b58-328da1083a92.png)

**Comment by MarynaChurylo** [comment]
Дякую, виправила

**Comment by AlonaSarapina** [comment]
fixed https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986%3A6&t=CPr15tFOt12xUh5L-1
