### ISSUE TITLE
20180428_0501_beregovo # 162 - Отсутствует разделение путешествия на блоки

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#231]
**Steps to reproduce:**
1. Открыть страницуhttps://long-travel.live/20180428_0501_beregovo/
2. Сравнить контент страницы с https://legacy.long-travel.live/blog.php?article=20180428_0501_Beregovo
3. Обратить внимание на блоки путешествия

**Actual result:**
**Отсутствует** разделение путешествия на блоки

**Expected result:**
В путешествии **присутствуют** блоки:
1. Дорога Киев-Львов
2. Ресторан "Голодний Микола"
3. Дорога Львов-Берегово
4. Отель "Ламберт"
5. Винзавод "Леанка"
6. Ужгород
7. Кафе "Cilli-Pizza"
8. Замок "Паланок"
9. Замок "Сент-Миклош"
10. Санаторий "Карпаты"
11. Железнодорожная станция
12. Мукачево
13. Ресторан "Фламинго"
 
![image](https://user-images.githubusercontent.com/86321831/140816088-f7ba626e-8910-4764-a1f8-18a4c3ac6b2a.png)

**Environment:**
Windows 10, Google Chrome v. 95.0.4638.69

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
