### ISSUE TITLE
20180428_0501_beregovo # 162 - Отсутствует видео

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#232]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. Сравнить контент страницы с https://legacy.long-travel.live/blog.php?article=20180428_0501_Beregovo
3. Обратить внимание на видео

**Actual result:**
Видео **отсутствует**

**Expected result:**
Видео **присутствует:**
1. Киев - Берегово 1
2. Киев-Берегово 2
3. Берегово-Отель "Ламберт"

![image](https://user-images.githubusercontent.com/86321831/140816840-34d7badf-8ac6-48c1-b4b5-2c6ab2a57535.png)

**Environment:**
Windows 10, Google Chrome v. 95.0.4638.69

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
