### ISSUE TITLE
20170605_kiev_mariinskiy/ Блок прев'ю подорожі"Крещатик, Мариинский парк,Киев, Украина, 05.06.2017"-відсутнє фото прев'ю подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2344]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20170605_kiev_mariinskiy/
2.Проскролити сторінку до прев'ю "Крещатик, Мариинский парк,Киев, Украина, 05.06.2017"
3.Звернути увагу на фото прев'ю подорожі "Крещатик, Мариинский парк,Киев, Украина, 05.06.2017"

**Фактичний результат:** Відсутнє фото прев'ю подорожі
**Очікуваний результат:** Присутнє фото прев'ю подорожі

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_82](https://user-images.githubusercontent.com/109720075/209204509-62133004-8825-45e5-915d-ae5233461201.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
