### ISSUE TITLE
20170625_gusintsi/ В прев'ю подорожі"Дорога – Київ – Гусинці"-відсутній прапор України

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2354]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20170625_gusintsi/
2.Проскролити сторінку до прев'ю"Дорога – Київ – Гусинці"
3.Звернути увагу на прапор України в прев'ю

**Фактичний результат:** Відсутній прапор України в прев'ю
**Очікуваний результат:** Присутній прапор України в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_93](https://user-images.githubusercontent.com/109720075/209211409-6804524b-572a-4dc4-8b22-34a4202a28a9.png)

**Comment by GNatala** [comment]
passed
