### ISSUE TITLE
20170625_gusintsi/ Блок прев'ю подорожі"Київська область, Україна,25.06.2017"-відсутнє фото прев'ю подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2356]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20170625_gusintsi/
2.Проскролити сторінку до прев'ю "Київська область, Україна,25.06.2017"
3.Звернути увагу на фото прев'ю подорожі "Київська область, Україна,25.06.2017"

**Фактичний результат:** Відсутнє фото прев'ю подорожі
**Очікуваний результат:** Присутнє фото прев'ю подорожі

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_95](https://user-images.githubusercontent.com/109720075/209289991-e0ce26e0-975f-46ef-9cc4-6d4f20000c9e.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
