### ISSUE TITLE
20170625_gusintsi # 163 - Отсутствует превью изображение

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#236]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/
2. Найти путешествие 20170625_gusintsi
3. Обратить внимание на изображение превью

**Actual result:**
Изображение превью отсутствует

**Expected result:**
Изображение превью присутствует

![image](https://user-images.githubusercontent.com/86321831/141695014-f4698911-67b6-4457-bd50-bb2c951fbd32.png)

**Environment:**
Windows 10, Google Chrome v. 95.0.4638.69

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
