### ISSUE TITLE
20170628_trahtemorov/Прев'ю подорожі "Трахтемиров"- дата подорожі,область  та назва країни знаходяться під прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2363]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20170628_trahtemorov/
2.Звернути увагу на дату подорожі ,область та назву країни блоку "Трахтемиров"

**Фактичний результат:** Дата подорожі ,область  та назва країни знаходяться під прев'ю
**Очікуваний результат:** Дата подорожі ,область  та назва країни знаходяться в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_102](https://user-images.githubusercontent.com/109720075/209295753-6ddad9aa-02d1-45f0-acb5-3fe67355c981.png)

**Comment by scholokov** [comment]
fixed
