### ISSUE TITLE
20170628_trahtemorov/ Блок "Легенда"-назва подорожі "Trakhtemyriv"написана на англійській мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2364]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20170628_trahtemorov/
2.Звернути увагу на назву подорожі "Trakhtemyriv"

**Фактичний результат:** Назва подорожі Soshnykiv написана на англійській мові
**Очікуваний результат:** Назва подорожі Сошників написана на українській мові

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_103](https://user-images.githubusercontent.com/109720075/209296249-096e64e6-8a64-48c3-9596-23f68d198a99.png)

**Comment by scholokov** [comment]
fixed
