### ISSUE TITLE
20170628_trahtemorov/ Прев'ю подорожі "Трахтемиров"- назва подорожі на російській мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2365]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20170628_trahtemorov/
2.Звернути увагу на назву подорожі в фото прев'ю блоку "Трахтемиров"

**Фактичний результат:** Назва подорожі на російській мові
**Очікуваний результат:** Назва подорожі на українській мові

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_104](https://user-images.githubusercontent.com/109720075/209296787-ed6b44e7-53c8-4c4b-ad33-b32a0046d0a7.png)

**Comment by scholokov** [comment]
fixed
