### ISSUE TITLE
20170628_trahtemorov/ Прев'ю подорожі "Подготовка 28.06.2017"- назва подорожі на російській мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2367]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20170628_trahtemorov/
2. Проскролити сторінку до прев'ю "Подготовка 28.06.2017"
3.Звернути увагу на назву подорожі в фото прев'ю блоку "Подготовка 28.06.2017"

**Фактичний результат:** Назва подорожі на російській мові
**Очікуваний результат:** Назва подорожі на українській мові

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_106](https://user-images.githubusercontent.com/109720075/209301998-8ca4bdcb-dade-43e5-a16e-94ee899dc8a8.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
An issue is reproduced.

**Фактичний результат:** Назва подорожі на російській мові
**Очікуваний результат:** Назва подорожі на українській мові

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/227924204-4a88ab7d-da61-42ed-8bb4-4b61da4d3a1e.png)
