### ISSUE TITLE
20170625_gusintsi # 163 - Название области и страны не соответствует языку страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#239]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20170625_gusintsi/
2. Обратить внимание на название области и страны

**Actual result:**
Киевская область, Украина

**Expected result:**
Київська область, Україна

![image](https://user-images.githubusercontent.com/86321831/141697042-c11e6a93-82b9-44ba-9fc4-ff9dc0cd2806.png)

**Environment:**
Windows 10, Google Chrome v. 95.0.4638.69

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
