### ISSUE TITLE
20170715_boguslav/ В прев'ю подорожі"Чайки, Богуславский район, Киевская область, Украина 15.07.2017"-відсутній прапор України

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2397]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20170715_boguslav/
2.Проскролити сторінку до прев'ю "Чайки, Богуславский район, Киевская область, Украина 15.07.2017"
3.Звернути увагу на прапор України в прев'ю

**Фактичний результат:** Відсутній прапор України в прев'ю
**Очікуваний результат:** Присутній прапор України в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_5](https://user-images.githubusercontent.com/109720075/209391807-5bc365dc-6c85-49aa-9966-a69b8268a061.png)

**Comment by DmytroMarkulych** [comment]
@andry1729 додайте будь ласка наступні атрибути 

![Image](https://user-images.githubusercontent.com/88647733/214504769-226665d4-add2-46f8-a580-46f717dd9855.png)

**Comment by scholokov** [comment]
випралено
