### ISSUE TITLE
Travels that need to be implemented 

### ISSUE THREAD

**Issue by tatianasheremet** [scholokov/long-travel-2#24]
!!! Please mark as done once the travel is implemeted !!!
                                     
List of the Travels to be implemeted: 
                                                                         
- [x] 20061028_Bila_Tserkva/
- [x] 20070406_09_Lviv/
- [x] 20071027_Uman/
- [x] 20080427_Feofania/
- [x] 20130526_Vishgorod/
- [x] 20130613_0628_Bulgaria/
- [x] 20160326_Konotop/
- [x] 20160518_22_Eger/
- [x] 20170417_Kiylov/
- [x] 20191207_08_Vinnitsa/
- [x] 20200104_07_Berlin/
- [x] 20200719_Belya_tsercov/
- [ ] 20070722_0809_Crimea/
- [x] 20091026_1102_Toronto/
- [ ] 20120827_0913_Karpathian_Crimia/
- [x] 20130721_Vitachev/
- [x] 20131019_Petrovtsi_Bitva_Za_Kiev/
- [ ] 20140616_0707_Greece/
- [x] 20140913_Kiev_Spivoche_Pole/
- [x] 20141102_10_Egypt_Hurghada/
- [x] 20150502_06_Hungary/
- [x] 20150530_Kiev_Aviation_Museum/
- [ ] 20150623_0711_Croatia/
- [x] 20150919_Kiev_Aviation_Museum/
- [x] 20151031_Haisyn_Uman/
- [x] 20151226_Kiev_Fashion_Park/
- [x] 20160618_Mezhigorie/
- [x] 20160701_24_Italy/
- [x] 20160725_0807_Odessa/
- [x] 20160814_24_Shadsk/
- [x] 20160830_Myrgorod/
- [x] 20161023_Chaiky_Aerofly/
- [x] 20170115_Kiev_Zoo_12_Month/
- [x] 20170416_Kiev_Sof_Plosha/
- [x] 20170509_Kiev_Museum_Great_Patriotic_War/
- [x] 20170513_Putivl_Kruti/
- [x] 20170521_Korosten/
- [x] 20170605_Kiev_Mariinskiy/
- [x] 20170612_Buki/
- [x] 20170625_Gusintsi/
- [x] 20170628_Trahtemorov/
- [x] 20170709_Protsiv/
- [x] 20170715_Boguslav/
- [x] 20170722_Boguslav/
- [x] 20170805_20_Odessa/
- [x] 20180204_Zhitomyr/
- [x] 20180428_0501_Beregovo/
- [x] 20180611_Kiev_Sea/
- [x] 20180624_Bila_Tserkva/
- [x] 20180708_Boguslav/
- [x] 20180721_Cherkassy/
- [x] 20180804_Piryatin_Mirgorod/
- [x] 20180819_Bucha/
- [x] 20180909_Bucha/
- [x] 20180915_Buki/
- [x] 20181014_Vinnitsa/
- [x] 20190427_Belarus_Litva/
- [x] 20190608_Boguslav/
- [x] 20190616_Korostishevsky_Kanyon/
- [x] 20190720_0811_Balcans/
- [x] 20191012_14_Dnipro/
- [x] 20200307_09_Lviv_Vinnitsa/
- [x] 20200613_Khmelnitskiy/
- [x] 20200614_Kvadrotsicly/
- [x] 20200627_29_Yuzhniy/

**Comment by scholokov** [comment]
на всяк дублирую с чата. @tatianasheremet я так понял ты их не отмечала...
20151226_Kiev_Fashion_Park
20160618_Mezhigorie
20161023_chaiky_aerofly
20170115_Kiev_Zoo_12_Month
20170416_Kiev_Sof_Plosha

**Comment by scholokov** [comment]
20170715_Boguslav

**Comment by scholokov** [comment]
20170722_Boguslav

**Comment by scholokov** [comment]
20180819_Bucha/
 20180909_Bucha/

**Comment by scholokov** [comment]
20170709_Protsiv

**Comment by scholokov** [comment]
20180915_Buki

**Comment by tatianasheremet** [comment]
All travels from the comments above were added and marked in the list. Feel free to comment with new :)

**Comment by scholokov** [comment]
20170628_Trahtemorov/

**Comment by scholokov** [comment]
20170509_Kiev_Museum_Great_Patriotic_War

**Comment by scholokov** [comment]
20170605_Kiev_Mariinskiy

**Comment by scholokov** [comment]
20180721_Cherkassy

**Comment by scholokov** [comment]
20180611_Kiev_Sea

**Comment by scholokov** [comment]
https://long-travel.live/wp-content/gallery/20180204_Zhitomyr_03_Museum/07.jpg

**Comment by scholokov** [comment]
20170521_Korosten

**Comment by scholokov** [comment]
20180624_bila_tserkva

**Comment by scholokov** [comment]
20180804_piryatin_mirgorod

**Comment by tatianasheremet** [comment]
All travels from the comments above were added and marked in the list. Feel free to comment with new @scholokov  :)

**Comment by scholokov** [comment]
20170612_buki

**Comment by scholokov** [comment]
20170513_putivl_kruti

**Comment by scholokov** [comment]
20170625_gusintsi

**Comment by scholokov** [comment]
20180428_0501_Beregovo

**Comment by scholokov** [comment]
20200307_09_Lviv_Vinnitsa

**Comment by scholokov** [comment]
20170805_20_Odessa

**Comment by scholokov** [comment]
20160814_24_shadsk

**Comment by scholokov** [comment]
20151031_Haisyn_Uman

**Comment by tatianasheremet** [comment]
All travels from the comments above were added and marked in the list. Feel free to comment with new @scholokov :)

**Comment by scholokov** [comment]
20120827_0913_Karpathian_Crimia

**Comment by scholokov** [comment]
20140616_0707_greece

**Comment by scholokov** [comment]
20150623_0711_croatia

**Comment by scholokov** [comment]
merged:
20160701_24_Italy
20160725_0807_Odessa

**Comment by scholokov** [comment]
full list

- [ ] 20061028_Bila_Tserkva/
- [ ] 20070406_09_Lviv/
- [ ] 20070722_0809_Crimea/
- [ ] 20071027_Uman/
- [ ] 20080427_Feofania/
- [ ] 20091026_1102_Toronto/
- [ ] 20120827_0913_Karpathian_Crimia/
- [ ] 20130526_Vishgorod/
- [ ] 20130613_0628_Bulgaria/
- [ ] 20130721_Vitachev/
- [ ] 20131019_Petrovtsi_Bitva_Za_Kiev/
- [ ] 20140616_0707_Greece/
- [ ] 20140913_Kiev_Spivoche_Pole/
- [ ] 20141102_10_Egypt_Hurghada/
- [ ] 20150502_06_Hungary/
- [ ] 20150530_Kiev_Aviation_Museum/
- [ ] 20150623_0711_Croatia/
- [ ] 20150919_Kiev_Aviation_Museum/
- [ ] 20151031_Haisyn_Uman/
- [ ] 20151226_Kiev_Fashion_Park/
- [ ] 20160326_Konotop/
- [ ] 20160518_22_Eger/
- [ ] 20160618_Mezhigorie/
- [ ] 20160701_24_Italy/
- [ ] 20160725_0807_Odessa/
- [ ] 20160814_24_Shadsk/
- [ ] 20160830_Myrgorod/
- [ ] 20161023_Chaiky_Aerofly/
- [ ] 20170115_Kiev_Zoo_12_Month/
- [ ] 20170128_Konotop/
- [ ] 20170416_Kiev_Sof_Plosha/
- [ ] 20170417_Kiylov/
- [ ] 20170509_Kiev_Museum_Great_Patriotic_War/
- [ ] 20170513_Putivl_Kruti/
- [ ] 20170521_Korosten/
- [ ] 20170605_Kiev_Mariinskiy/
- [ ] 20170612_Buki/
- [ ] 20170625_Gusintsi/
- [ ] 20170628_Trahtemorov/
- [ ] 20170709_Protsiv/
- [ ] 20170715_Boguslav/
- [ ] 20170722_Boguslav/
- [ ] 20170805_20_Odessa/
- [ ] 20180204_Zhitomyr/
- [ ] 20180428_0501_Beregovo/
- [ ] 20180611_Kiev_Sea/
- [ ] 20180624_Bila_Tserkva/
- [ ] 20180708_Boguslav/
- [ ] 20180721_Cherkassy/
- [ ] 20180804_Piryatin_Mirgorod/
- [ ] 20180819_Bucha/
- [ ] 20180826_Kiylov/
- [ ] 20180909_Bucha/
- [ ] 20180915_Buki/
- [ ] 20181014_Vinnitsa/
- [ ] 20190427_Belarus_Litva/
- [ ] 20190608_Boguslav/
- [ ] 20190616_Korostishevsky_Kanyon/
- [ ] 20190720_0811_Balcans/
- [ ] 20191012_14_Dnipro/
- [ ] 20191207_08_Vinnitsa/
- [ ] 20200104_07_Berlin/
- [ ] 20200307_09_Lviv_Vinnitsa/
- [ ] 20200613_Khmelnitskiy/
- [ ] 20200614_Kvadrotsicly/
- [ ] 20200627_29_Yuzhniy/
- [ ] 
- [ ] - [ ]

**Comment by scholokov** [comment]
20190720_0811_balcans

**Comment by tatianasheremet** [comment]
All travels were moved to a table [QA Travel Pages](https://docs.google.com/spreadsheets/d/19aAOFXIUy7TU0RSM40GQR8Wm2KmsW8a7x-K07hvFzRI/edit#gid=0). 
Once task for QA will be created - travels will be marked here as done

**Comment by tatianasheremet** [comment]
> full list
> 
> * [ ]  20061028_Bila_Tserkva/
> * [ ]  20070406_09_Lviv/
> * [ ]  20070722_0809_Crimea/
> * [ ]  20071027_Uman/
> * [ ]  20080427_Feofania/
> * [ ]  20091026_1102_Toronto/
> * [ ]  20120827_0913_Karpathian_Crimia/
> * [ ]  20130526_Vishgorod/
> * [ ]  20130613_0628_Bulgaria/
> * [ ]  20130721_Vitachev/
> * [ ]  20131019_Petrovtsi_Bitva_Za_Kiev/
> * [ ]  20140616_0707_Greece/
> * [ ]  20140913_Kiev_Spivoche_Pole/
> * [ ]  20141102_10_Egypt_Hurghada/
> * [ ]  20150502_06_Hungary/
> * [ ]  20150530_Kiev_Aviation_Museum/
> * [ ]  20150623_0711_Croatia/
> * [ ]  20150919_Kiev_Aviation_Museum/
> * [ ]  20151031_Haisyn_Uman/
> * [ ]  20151226_Kiev_Fashion_Park/
> * [ ]  20160326_Konotop/
> * [ ]  20160518_22_Eger/
> * [ ]  20160618_Mezhigorie/
> * [ ]  20160701_24_Italy/
> * [ ]  20160725_0807_Odessa/
> * [ ]  20160814_24_Shadsk/
> * [ ]  20160830_Myrgorod/
> * [ ]  20161023_Chaiky_Aerofly/
> * [ ]  20170115_Kiev_Zoo_12_Month/
> * [ ]  20170128_Konotop/
> * [ ]  20170416_Kiev_Sof_Plosha/
> * [ ]  20170417_Kiylov/
> * [ ]  20170509_Kiev_Museum_Great_Patriotic_War/
> * [ ]  20170513_Putivl_Kruti/
> * [ ]  20170521_Korosten/
> * [ ]  20170605_Kiev_Mariinskiy/
> * [ ]  20170612_Buki/
> * [ ]  20170625_Gusintsi/
> * [ ]  20170628_Trahtemorov/
> * [ ]  20170709_Protsiv/
> * [ ]  20170715_Boguslav/
> * [ ]  20170722_Boguslav/
> * [ ]  20170805_20_Odessa/
> * [ ]  20180204_Zhitomyr/
> * [ ]  20180428_0501_Beregovo/
> * [ ]  20180611_Kiev_Sea/
> * [ ]  20180624_Bila_Tserkva/
> * [ ]  20180708_Boguslav/
> * [ ]  20180721_Cherkassy/
> * [ ]  20180804_Piryatin_Mirgorod/
> * [ ]  20180819_Bucha/
> * [ ]  20180826_Kiylov/
> * [ ]  20180909_Bucha/
> * [ ]  20180915_Buki/
> * [ ]  20181014_Vinnitsa/
> * [ ]  20190427_Belarus_Litva/
> * [ ]  20190608_Boguslav/
> * [ ]  20190616_Korostishevsky_Kanyon/
> * [ ]  20190720_0811_Balcans/
> * [ ]  20191012_14_Dnipro/
> * [ ]  20191207_08_Vinnitsa/
> * [ ]  20200104_07_Berlin/
> * [ ]  20200307_09_Lviv_Vinnitsa/
> * [ ]  20200613_Khmelnitskiy/
> * [ ]  20200614_Kvadrotsicly/
> * [ ]  20200627_29_Yuzhniy/

20200719_Belya_tsercov - missed from this list
