### ISSUE TITLE
20170625_gusintsi # 163 - Дата путешествия и дата учетных точек не соответствует реальной дате

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#240]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20170625_gusintsi/
2. Обратить внимание на даты путешествия и даты учетных точек

**Actual result:**
Дата путешествия и учетных точек - **25.06.2018**

**Expected result:**
Дата путешествия и учетных точек - **25.06.2017**

![image](https://user-images.githubusercontent.com/86321831/141697812-6a8f4f46-c90e-44ff-aac2-1fc633063475.png)

**Environment:**
Windows 10, Google Chrome v. 95.0.4638.69

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
