### ISSUE TITLE
20170625_gusintsi # 163 - Размер символов даты учетной точки не соответствует требованиям

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#241]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20200719_belya_tsercov/
2. Обратить внимание на размер символов даты учетной точки Спасо-Преображенская церковь, Гусинцы

**Actual result:**
Размер символов даты учетной точки  - **H3**

**Expected result:**
Размер символов даты даты учетной точки - **15 рх**

![image](https://user-images.githubusercontent.com/86321831/141698423-c7440b58-e7f0-4fa2-9255-b77e7d539464.png)

**Environment:**
Windows 10, Google Chrome v. 95.0.4638.69

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
