### ISSUE TITLE
20170722_boguslav/ Відео з блоку прев'ю "Дорога Богуслав – Київ"-присутній link а не Youtube відео

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2411]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20170722_boguslav/
2.Проскролити сторінку до прев'ю "Дорога Богуслав – Київ"
3.Звернути увагу на Youtube відео

**Фактичний результат:** Присутній link а не Youtube відео
**Очікуваний результат:** Присутнє Youtube відео

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_23](https://user-images.githubusercontent.com/109720075/209424205-0e14169c-2232-44b0-8d5f-8144536e7029.png)
![Screenshot_24](https://user-images.githubusercontent.com/109720075/209424206-0faecabe-e8aa-4f5b-8a1b-6c67d03a881e.png)

**Comment by scholokov** [comment]
fixed
