### ISSUE TITLE
20171027_cherkasy/ no Ukrainian flag in the preview  

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#2414]
Prerequisites:
Open https://test.long-travel.live/20171027_cherkasy/
Steps to play:

1. Please note that there is no Ukrainian flag in the preview

Actual result: No Ukrainian flag in the preview  
Expected result: The flag of Ukraine is in the preview

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 107.0.5304.122
![черкасси прапор](https://user-images.githubusercontent.com/113175298/209446184-4fe8d28c-b4d4-4db6-a3f2-a7b2db94a24a.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
