### ISSUE TITLE
20171027_cherkasy/ no map in the journey 

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#2415]
Prerequisites:
Open https://test.long-travel.live/20171027_cherkasy/
Steps to play:

1. there is no map in the journey

Actual result: no map in the journey
Expected result: there is a map in the journey

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 107.0.5304.122
![черкаси карта](https://user-images.githubusercontent.com/113175298/209446784-e4631b01-77f3-4a94-b2ef-303208f5d5f2.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
