### ISSUE TITLE
20171027_cherkasy/ no travel date in the preview

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#2416]
Prerequisites:
Open  https://test.long-travel.live/20171027_cherkasy/
Steps to play:

1.  no travel date in the preview

Actual result:  no travel date in the preview
Expected result:  there are travel dates in the preview

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 107.0.5304.122
![черкаси дата в превю](https://user-images.githubusercontent.com/113175298/209447003-20d9a8b9-77be-40e9-9b6f-4dea89d4ae96.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
