### ISSUE TITLE
20170625_gusintsi # 163 - Название учетной точки Гусинцы не соответствует языку страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#242]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20170625_gusintsi/
2. Обратить внимание на язык учетной точки Гусинцы

**Actual result:**
Гусинцы, Киевская область, Украина

**Expected result:**
Гусинці, Київська область, Україна

![image](https://user-images.githubusercontent.com/86321831/141698658-05fe9daa-f404-4192-9fd8-6f469e03c481.png)

**Environment:**
Windows 10, Google Chrome v. 95.0.4638.69

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
