### ISSUE TITLE
20170625_gusintsi # 163 - Название учетной точки Спасо-Преображенская церковь не соответствует языку страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#243]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20170625_gusintsi/
2. Обратить внимание на язык учетной точки Спасо-Преображенская церковь

**Actual result:**
Спасо-Преображенская церковь, Гусинцы, Киевская область, Украина

**Expected result:**
Спасо-Преображенська церква, Гусинці, Київська область, Україна

![image](https://user-images.githubusercontent.com/86321831/141698921-0e7356e1-4c09-4a37-9d4f-3cb4d47cb935.png)

**Environment:**
Windows 10, Google Chrome v. 95.0.4638.69

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
