### ISSUE TITLE
20170625_gusintsi # 163 - Название блока Дорога Киев-Гусинцы не соответствует языку страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#244]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20170625_gusintsi/
2. Обратить внимание на язык блока Дорога- Киев -Гусинцы

**Actual result:**
Киев -Гусинцы

**Expected result:**
Київ-Гусинці

![image](https://user-images.githubusercontent.com/86321831/141699074-feea1208-6323-44e6-99e2-ce265793de3c.png)

**Environment:**
Windows 10, Google Chrome v. 95.0.4638.69

**Comment by scholokov** [comment]
fixed
