### ISSUE TITLE
20170625_gusintsi # 163 - Формат подписи видео не соответствует требованиям

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#245]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20170625_gusintsi/
2. Обратить внимание на формат даты видео 25.06.2017 Киев-Гусинцы

**Actual result:**
Формат даты не соответствует требованиям **25.06.2017 Киев-Гусинцы**

**Expected result:**
Формат даты соответствует требованиям **2017.06.25 Київ - Гусинці**

![image](https://user-images.githubusercontent.com/86321831/141699298-ce75a364-403d-453c-a270-df87cc6894bd.png)

**Environment:**
Windows 10, Google Chrome v. 94.0.4606.81

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
