### ISSUE TITLE
20170625_gusintsi # 163 - В схеме маршрута на карте  ошибка в названии Гусинці

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#246]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20170625_gusintsi/
2. Обратить внимание на написание учетных точек на схеме маршрута рядом с картой

**Actual result:**
Учетная точка  - Спасо-Преображенська церква, **Гисинцi**

**Expected result:**
Учетная точка  - Спасо-Преображенська церква, **Гусинцi**

![image](https://user-images.githubusercontent.com/86321831/141699737-466722c7-02b9-4d58-b7bc-26482b7fcf7c.png)

**Environment:**
Windows 10, Google Chrome v. 95.0.4638.69

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
