### ISSUE TITLE
20170625_gusintsi # 163 - На схеме путешествия неверно указано расстояние между промежуточными точками

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#247]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20170625_gusintsi/
2. На схеме путешествия рядом с картой обратить внимание на пройденное расстояние возле учетной точки **Спасо-Преображенська церква, Гусинцi**

**Actual result:**
Расстояние указано **неверно**

**Expected result:**
Расстояние указано **верно**

![image](https://user-images.githubusercontent.com/86321831/141700101-86c95256-cf0e-4e8d-bb90-cb967d2fd13a.png)

**Environment:**
Windows 10, Google Chrome v. 95.0.4638.69

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
