### ISSUE TITLE
20200307_09_Lviv_Vinnitsa The language of the name does not correspond to the country

### ISSUE THREAD

**Issue by EvheniiRadionov** [scholokov/long-travel-2#249]
Additional Information:
-Operating System: Windows 10, x64.
-Browser : Google Chrome 93.0.4577.82 (Official build), (64 bit).

**Comment by scholokov** [comment]
нет тела

**Comment by EvheniiRadionov** [comment]
Когда оформлял кот на клаву прыгнул)))

**Comment by scholokov** [comment]
ну все равно надо было либо исправить на новый либо закрыть с коментом - что открыто по ошибке

**Comment by EvheniiRadionov** [comment]
Ок, понял
