### ISSUE TITLE
20180624_bila_tserkva/ Відео"2018.06.24 - Road - Киев - Белая Церковь" подорожі “Дорога: Киев – Белая Церковь,Украина,24.06.2018"- назва відео  на російській та англійській  мові

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2502]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20180624_bila_tserkva/
2.Звернути увагу на відео"2018.06.24 - Road - Киев - Белая Церковь" подорожі “Дорога: Киев – Белая Церковь,Украина,24.06.2018"

**Фактичний результат:** Назва відео на російській та англійській мові
**Очікуваний результат:** Назва відео на українській мові

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_25](https://user-images.githubusercontent.com/109720075/209632850-acd4fc41-b657-4d40-bb75-f251a3aab1f5.png)

**Comment by scholokov** [comment]
fixed
