### ISSUE TITLE
20180708_boguslav/ В прев'ю подорожі“Чайки"-відсутній прапор України

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2530]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20180708_boguslav/
2.Звернути увагу на прапор України в прев'ю “Чайки"

**Фактичний результат:** Відсутній прапор України в прев'ю
**Очікуваний результат:** Присутній прапор України в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_53](https://user-images.githubusercontent.com/109720075/209661221-89288f7d-e66f-4e1a-9b64-ae5d82761c31.png)

**Comment by scholokov** [comment]
fixed
