### ISSUE TITLE
20160618_Mezhigorie/ 1st travel's preview, mis travel's name (Межигір’я)

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#2561]
Steps:

1) Open page https://test.long-travel.live/20160618_Mezhigorie/
2) Pay attention to 1st travel's preview

Actual Result: Межигір’я

Expected Result: Національний парк "Межигір’я"

Link to specifications https://github.com/scholokov/long-travel-2/wiki/4.2-Travels.List

![Screenshot_1](https://user-images.githubusercontent.com/114935450/209685980-1205958f-6219-49e9-880a-249717a39327.png)

**Comment by scholokov** [comment]
fixed

**Comment by MarynaChurylo** [comment]
successful
