### ISSUE TITLE
20160618_Mezhigorie/ Travels' list on the Global map - travel's name does not match specifications (20160618_Mezhigorie)

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#2562]
Steps:

1) Open page https://test.long-travel.live/travels/
2) Scroll the travels' list to travel 20160618_Mezhigorie
3) Pay attention to the NAME of travel

Actual Result:
incorrect name of the travel 20160618_Mezhigorie

Expected Result
correct name of the travel 2016.06.18 Національний парк "Межигір’я"

Link to specifications (travel's name)  https://github.com/scholokov/long-travel-2/wiki/4.2-Travels.List
Link to specifications (travel's name format) https://github.com/scholokov/long-travel-2/wiki/3.1-Maps.Global-Map-with-routs

![Screenshot_2](https://user-images.githubusercontent.com/114935450/209688492-c8fdb8ff-5e50-4bb3-a511-e61e50f685d9.png)

**Comment by scholokov** [comment]
fixed

**Comment by MarynaChurylo** [comment]
successful
