### ISSUE TITLE
 20150523_picnic_dnipro/ Travels' list on the Global map - travel's name does not match specifications (20150523_picnic_dnipro)

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#2563]
Steps:

1) Open page https://test.long-travel.live/travels/
2) Scroll the travels' list to travel 20150523_picnic_dnipro
3) Pay attention to the NAME of travel

Actual Result:
incorrect name of the travel 20150523_picnic_dnipro

Expected Result
correct name of the travel 20150523_Кийлів, Пікнік біля Дніпра

Link to specifications (travel's name)  https://github.com/scholokov/long-travel-2/wiki/4.2-Travels.List

![Screenshot_3](https://user-images.githubusercontent.com/114935450/210395655-91af405a-ee2b-4e01-983e-e2ce657c2d22.png)

**Comment by DmytroMarkulych** [comment]
@MarynaChurylo це не є дефектом, тому що назва відповідає вимогам

**Comment by MarynaChurylo** [comment]
Виправила

**Comment by scholokov** [comment]
fixed

**Comment by MarynaChurylo** [comment]
The bug is still reproduce

Actual Result: Пікнік біля Дніпра

Expected Result: Кийлів, Пікнік біля Дніпра


![Screenshot_2](https://user-images.githubusercontent.com/114935450/214850279-e73c45ee-5657-4d1c-a12e-9c5d682cf2b4.png)

**Comment by ODrobik** [comment]
irrelevant
