### ISSUE TITLE
20150523_picnic_dnipro/ Travels. Med size image with Title - unexpected element at image title (Uncategorized)

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#2565]
Steps:

1) Open page https://test.long-travel.live/travels/
2) Scroll the page down - until finding med size image with Title - Пікнік Дніпро,Україна
3) Pay attention to travel's category

Actual Result: unexpected element - Uncategorized

Expected Result: no element

![Screenshot_1](https://user-images.githubusercontent.com/114935450/209693688-1bf746b7-4ce9-4bdd-8638-9b3b016955e7.png)

**Comment by scholokov** [comment]
fixed

**Comment by MarynaChurylo** [comment]
successful
