### ISSUE TITLE
20160618_Mezhigorie/ Travels. Med size image with Title - mis travel's name (Межигір’я)

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#2566]
Steps:

1) Open page https://test.long-travel.live/travels/
2) Scroll the page down - until finding med size image with Title - Межигір’я
3) Pay attention to travel's name

Actual Result: Межигір’я

Expected Result: Національний парк "Межигір’я"

Link to specifications https://github.com/scholokov/long-travel-2/wiki/4.2-Travels.List

![Screenshot_3](https://user-images.githubusercontent.com/114935450/209694769-df691793-7348-400a-9b4d-5618ec07220c.png)

**Comment by scholokov** [comment]
fixed

**Comment by MarynaChurylo** [comment]
successful
