### ISSUE TITLE
20150523_picnic_dnipro/ Travels. Med size image with Title - mis travel's name (Пікнік Дніпро,Україна)

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#2567]
Steps:

1) Open page https://test.long-travel.live/travels/
2) Scroll the page down - until finding med size image with Title - Пікнік Дніпро,Україна
3) Pay attention to travel's name

Actual Result: Пікнік Дніпро,Україна

Expected Result: Кийлів, Пікнік біля Дніпра

Link to specifications https://github.com/scholokov/long-travel-2/wiki/4.2-Travels.List

![Screenshot_2](https://user-images.githubusercontent.com/114935450/209696686-4b1a7b1d-29aa-4139-bba4-af289209376c.png)

**Comment by scholokov** [comment]
fixed

**Comment by MarynaChurylo** [comment]
successful
