### ISSUE TITLE
20180428_0501_beregovo - Размер символов названия области не соответствует требованиям

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#271]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на размер символов названия Закарпатская область, Украина

**Actual result:**
Размер символов названия не соответствует требованиям - **15 px**

**Expected result:**
Размер символов названия соответствует требованиям - **h2**

![image](https://user-images.githubusercontent.com/86321831/143778611-3436db5a-5617-49ba-84b3-59f41a701a5b.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
