### ISSUE TITLE
20180428_0501_beregovo - Название области и страны не соответствует языку страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#272]
**Steps to reproduce:**

1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на язык названия Закарпатская область, Украина

**Actual result:**
Язык названия не соответствует языку страны - **Закарпатская область, Украина**

**Expected result:**
Язык названия соответствует языку страны - **Закарпатська область, Україна**

![image](https://user-images.githubusercontent.com/86321831/143778818-b3b04181-cd4e-41e5-bbcf-910786d7aee2.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
