### ISSUE TITLE
20180428_0501_beregovo - Размер символов даты путешествия не соответствует требованиям

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#273]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на размер символов даты путешествия

**Actual result:**
Размер символов даты путешествия - 15 рх

**Expected result:**
Размер символов даты путешествия - H3

![image](https://user-images.githubusercontent.com/86321831/143779055-28bd9ac2-aafa-49a4-a5da-0a5473316fbd.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
