### ISSUE TITLE
20180428_0501_beregovo - Название блока Дорога: Киев – Львов не соответствует языку страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#275]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на язык блока Дорога: Киев – Львов

**Actual result:**
Язык блока Дорога не соответствует языку страны - Дорога: **Киев – Львов**

**Expected result:**
Язык блока Дорога соответствует языку страны - Дорога: **Київ – Львів**

![image](https://user-images.githubusercontent.com/86321831/143780615-82624a0b-a6de-478d-abcd-81f3402feab2.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
