### ISSUE TITLE
20180428_0501_beregovo - Размер символов блока Дорога: Киев – Львов не соответствует требованиям

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#276]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на размер символов блока Дорога: Киев – Львов

**Actual result:**
Размер символов блока Дорога: Киев – Львов не соответствует требованиям - **15 px**

**Expected result:**
Размер символов блока Дорога: Киев – Львов соответствует требованиям - **Н2**

![image](https://user-images.githubusercontent.com/86321831/143781838-8c617f09-4629-41e8-adad-2c7dc553c12a.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
