### ISSUE TITLE
20180428_0501_beregovo - Размер символов даты блока Дорога: Киев – Львов не соответствует требованиям

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#277]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на размер символов даты блока Дорога: Киев – Львов

**Actual result:**
Размер символов даты Дорога: Киев – Львов - **15 рх**

**Expected result:**
Размер символов даты Дорога: Киев – Львов - **H3**

![image](https://user-images.githubusercontent.com/86321831/143782023-8a487497-f97b-4f93-9e36-75fe10624440.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
