### ISSUE TITLE
20180428_0501_beregovo - Название учетной точки Ресторан “Голодний Микола” не соответствует языку страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#278]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на язык названия города и страны учетной точки Ресторан “Голодний Микола”

**Actual result:**
Язык города и страны учетной точки не соответствует языку страны - **Львов, Украина**

**Expected result:**
Язык города и страны учетной точки не соответствует языку страны - **Львів, Україна**

![image](https://user-images.githubusercontent.com/86321831/143782380-af33f101-7407-4a72-92e0-07dcfa8ccb04.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
