### ISSUE TITLE
20180428_0501_beregovo - Размер символов даты учетной точки Ресторан "Голодний Микола" не соответствует требованиям

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#279]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на размер символов даты учетной точки Ресторан "Голодний Микола"

**Actual result:**
Размер символов даты учетной точки - **H2**

**Expected result:**
Размер символов даты учетной точки - **H3**

![image](https://user-images.githubusercontent.com/86321831/143782590-50d6c82d-9842-4d64-8659-6c85b2ff0c75.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
