### ISSUE TITLE
20180428_0501_beregovo - Название блока Дорога: Львов – Берегово не соответствует языку страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#280]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на язык блока Дорога: Львов – Берегово

**Actual result:**
Язык блока Дорога не соответствует языку страны - **Дорога: Львов – Берегово**

**Expected result:**
Язык блока Дорога соответствует языку страны - **Дорога: Львів – Берегове**

![image](https://user-images.githubusercontent.com/86321831/143782705-ecae7849-35cc-47f8-96c8-ad828fe822fa.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
