### ISSUE TITLE
20180428_0501_beregovo - Размер символов даты блока Дорога: Львов – Берегово не соответствует требованиям

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#281]
**Steps to reproduce:**
1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на размер символов даты блока Дорога: Львов – Берегово

**Actual result:**
Размер символов даты Дорога: Львов – Берегово - **15 рх**

**Expected result:**
Размер символов даты Дорога: Львов – Берегово - **H3**

![image](https://user-images.githubusercontent.com/86321831/143782864-6116b3b4-41d0-434a-a2c7-2540c1884385.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
