### ISSUE TITLE
20091026_1102_toronto/Missed preview photo in the Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#2862]
**Steps to reproduce:**

1.Open https://test.long-travel.live/20091026_1102_toronto/
2.Pay attention to the Preview block.

**Actual result:**
Preview block does not contain Preview photo
**Expected result:**
Preview block contains Preview photo

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment** 
![image](https://user-images.githubusercontent.com/101987790/210327512-5a1e35f4-09d1-4b0c-a777-c0e320c8aa5c.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed

**Comment by GNatala** [comment]
#2697
