### ISSUE TITLE
/20171027_cherkasy/  the travel date is displayed without dots in the preview

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#2863]
Prerequisites:
Open https://test.long-travel.live/20171027_cherkasy/
Steps to play:

1.  In the preview, the travel date is displayed without dots

Actual result: the travel date is displayed without dots in the preview
Expected result: the travel date is displayed with dots in the preview

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 108.0.5359.125 
![Черкаси 27 10 2017](https://user-images.githubusercontent.com/113175298/210356942-04e0f38f-84d4-499e-a08c-016f4e400f7e.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
