### ISSUE TITLE
Wiki/ 3.1 Maps.Global Map with routs/ Travel's name format (too long name's format) - 2016.06.18 Національний парк "Межигір’я"

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#2864]
Steps:

1) Open page https://test.long-travel.live/travels/
2) Scroll the travels' list to travel 2016.06.18 Національний парк "Межигір’я"
3)  Pay attention to the NAME of travel

Actual Result:
travel's name format (2016.06.18 Національний парк "Межигір’я") did not fit completely in travels' list block 

Expected Result
travel's name format (Національний парк "Межигір’я")  fit completely in travels' list block 

![Screenshot_2](https://user-images.githubusercontent.com/114935450/210381632-021dd581-4d39-4019-b3a0-bf25058811e0.png)

**Comment by scholokov** [comment]
fixed
https://github.com/scholokov/long-travel-2/wiki/3.1-Maps.Global-Map-with-routs
