### ISSUE TITLE
20150523_picnic_dnipro/ 2nd travel's preview - mis travel's name (Пікнік Дніпро)

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#2909]
Steps:

1) Open page https://test.long-travel.live/20150523_picnic_dnipro/
2) Scroll the page to the 2nd preview
3) Pay attention to the travel's name

Actual Result: Пікнік Дніпро

Expected Result: Кийлів, Пікнік біля Дніпра

Link to specifications https://github.com/scholokov/long-travel-2/wiki/4.2-Travels.List

![Screenshot_1](https://user-images.githubusercontent.com/114935450/210555621-588b4aae-0f1e-46a3-8e37-9b67904c8bac.png)

**Comment by scholokov** [comment]
але у вимогах прописане саме перше превью, а не друге

**Comment by MarynaChurylo** [comment]
It's not a bug
