### ISSUE TITLE
20160618_Mezhigorie/ 2nd travel's preview - spelling mistake (Парк - capital letter)

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#2910]
Steps:

1) Open page https://test.long-travel.live/20160618_Mezhigorie/
2) Scroll the page to the 2nd preview
3) Pay attention to the travel's name

Actual Result: Національний Парк Межигір’я  (Парк - capital letter)

Expected Result: Національний парк Межигір’я (парк - lowercase letter)

 
![Screenshot_4](https://user-images.githubusercontent.com/114935450/210557387-f681c620-d4dc-4a63-b069-525f75a7c536.png)

**Comment by scholokov** [comment]
fiixed

**Comment by MarynaChurylo** [comment]
the bug is still reproducing

**Comment by DmytroMarkulych** [comment]
@MarynaChurylo додайте будь ласка скрін

**Comment by MarynaChurylo** [comment]
Додала 
![Screenshot_1](https://user-images.githubusercontent.com/114935450/212051246-cbb788d9-620e-433d-8fc1-42b135b83c41.png)

**Comment by scholokov** [comment]
fixed

**Comment by MarynaChurylo** [comment]
successful
