### ISSUE TITLE
20160618_Mezhigorie/ 2nd travel's preview - spelling mistake (Межигір’я - no quotes)

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#2911]
Steps:

1) Open page https://test.long-travel.live/20160618_Mezhigorie/
2) Scroll the page to the 2nd preview
3) Pay attention to the travel's name

Actual Result:  Межигір’я - no quotes

Expected Result: “Межигір’я” - quotes are present

Link to specifications https://github.com/scholokov/long-travel-2/wiki/4.2-Travels.List

![Screenshot_3](https://user-images.githubusercontent.com/114935450/210559069-8f6004b9-3560-4f73-918a-45f6b59b4741.png)

**Comment by scholokov** [comment]
fixed

**Comment by MarynaChurylo** [comment]
successful
