### ISSUE TITLE
20210814_24_sergeevka_odessa/ Прев'ю подорожі "Сергіївка – Одеса"- фото прев'ю наполовину затемнене

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2937]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210814_24_sergeevka_odessa/
2.Звернути увагу на фото прев'ю блоку "Сергіївка – Одеса"

**Фактичний результат:** Фото прев'ю наполовину затемнене
**Очікуваний результат:** Фото прев'ю чітке

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_76](https://user-images.githubusercontent.com/109720075/210588030-1dc46eab-2bc2-4ff5-bc1d-054324c93179.png)

**Comment by scholokov** [comment]
fixed
