### ISSUE TITLE
20210814_24_sergeevka_odessa/ Прев'ю подорожі "Сергіївка – Одеса"-дата подорожі знаходиться під прев'ю

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2938]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210814_24_sergeevka_odessa/
2.Звернути увагу на дату подорожі  прев'ю блоку "Сергіївка – Одеса"

**Фактичний результат:** Дата подорожі знаходиться під прев'ю
**Очікуваний результат:** Дата подорожі знаходиться в прев'ю

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_77](https://user-images.githubusercontent.com/109720075/210588927-f8ac1712-458f-49bf-8ddf-254c325f6822.png)

**Comment by scholokov** [comment]
fixed
