### ISSUE TITLE
20170625_gusintsi # 163 - Блок Дорога Киев-Гусинці. Киев не соответствует языку страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#294]
**Steps to reproduce:**

1. Открыть страницу https://long-travel.live/20170625_gusintsi/
2. Обратить внимание на язык блока Дорога- Киев -Гусинці

**Actual result:**
**Киев** -Гусинці

**Expected result:**
**Київ**-Гусинці

![image](https://user-images.githubusercontent.com/86321831/144754795-9879707d-f2c1-413f-b4c2-7fad00ce5eb3.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
