### ISSUE TITLE
20210814_24_sergeevka_odessa/ Блок прев'ю"Сергіївка – Одеса"- формат дати 14-24.08.2021

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2940]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210814_24_sergeevka_odessa/
3.Звернути увагу на формат дати під блоком"Сергіївка – Одеса"

**Фактичний результат:** Формат дати 14-24.08.2021
**Очікуваний результат:** Формат дати 14.08.2021-24.08.2021

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_79](https://user-images.githubusercontent.com/109720075/210590788-42f8fca1-2f28-49e4-a530-538ba9ff8909.png)

**Comment by scholokov** [comment]
fixed
