### ISSUE TITLE
20210814_24_sergeevka_odessa/ Блок прев'ю подорожі"Сергіївка,  Одеська область,14-23.08.2021 "-відсутнє фото прев'ю подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2943]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210814_24_sergeevka_odessa/
2.Проскролити сторінку до прев'ю "Сергіївка,  Одеська область,14-23.08.2021 "
3.Звернути увагу на фото прев'ю подорожі "Сергіївка,  Одеська область,14-23.08.2021 "

**Фактичний результат:** Відсутнє фото прев'ю подорожі
**Очікуваний результат:** Присутнє фото прев'ю подорожі

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_82](https://user-images.githubusercontent.com/109720075/210593218-a0e488f6-35b1-49fb-9b78-2cd081678d99.png)

**Comment by scholokov** [comment]
fixed
