### ISSUE TITLE
20210814_24_sergeevka_odessa/ Прев'ю подорожі "Сергіївка, Одеська область,14-23.08.2021 "- відсутній прапор України

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2944]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210814_24_sergeevka_odessa/
2.Проскролити сторінку до прев'ю "Сергіївка, Одеська область,14-23.08.2021 "
3.Звернути увагу на прапор України

**Фактичний результат:** Відсутній прапор України
**Очікуваний результат:** Присутній прапор України

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_83](https://user-images.githubusercontent.com/109720075/210593963-991defbb-108d-442d-af3e-7b35dd028d7d.png)

**Comment by scholokov** [comment]
fixed
