### ISSUE TITLE
20210814_24_sergeevka_odessa/ Блок прев'ю подорожі"Океанариум,Одеса,23.08.2021"-відсутнє фото прев'ю подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2946]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210814_24_sergeevka_odessa/
2.Проскролити сторінку до прев'ю "Океанариум,Одеса,23.08.2021"
3.Звернути увагу на фото прев'ю подорожі "Океанариум,Одеса,23.08.2021"

**Фактичний результат:** Відсутнє фото прев'ю подорожі
**Очікуваний результат:** Присутнє фото прев'ю подорожі

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_85](https://user-images.githubusercontent.com/109720075/210595280-13e5acc3-416c-4c1c-a4fe-e9215aaf8eee.png)

**Comment by scholokov** [comment]
fixed
