### ISSUE TITLE
20210814_24_sergeevka_odessa/ Прев'ю подорожі "Океанариум,Одеса,23.08.2021"- назва подорожі російською мовою

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2948]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210814_24_sergeevka_odessa/
2.Проскролити сторінку до прев'ю "Океанариум,Одеса,23.08.2021"
3.Звернути увагу на назву подорожі

**Фактичний результат:** Назва подорожі російською мовою
**Очікуваний результат:** Назва подорожі українською  мовою

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_87](https://user-images.githubusercontent.com/109720075/210597256-f96c2785-3d09-4acd-9ea5-c0ff487f1fa2.png)

**Comment by scholokov** [comment]
fixed
