### ISSUE TITLE
20210814_24_sergeevka_odessa/ Блок прев'ю подорожі"Одеса,23-24.08.2021"-відсутнє фото прев'ю подорожі

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2949]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210814_24_sergeevka_odessa/
2.Проскролити сторінку до прев'ю "Одеса,23-24.08.2021""
3.Звернути увагу на фото прев'ю подорожі "Одеса,23-24.08.2021"

**Фактичний результат:** Відсутнє фото прев'ю подорожі
**Очікуваний результат:** Присутнє фото прев'ю подорожі

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_88](https://user-images.githubusercontent.com/109720075/210597858-7a4638d4-3e8c-487c-9022-0eaf37f8aa80.png)

**Comment by scholokov** [comment]
fixed
