### ISSUE TITLE
20210814_24_sergeevka_odessa/ Блок прев'ю"Одеса,23-24.08.2021"- формат дати 23-24.08.2021

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2951]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210814_24_sergeevka_odessa/
2.Прокрутити сторінку до прев'ю"Одеса,23-24.08.2021"
3.Звернути увагу на формат дати

**Фактичний результат:** Формат дати 23-24.08.2021
**Очікуваний результат:** Формат дати 23.08.2021-24.08.2021

**Середовище:**
Windows 10
Google Chrome Версія 106.0.5249.119 (Офіційне складання), (64 біт)
![Screenshot_90](https://user-images.githubusercontent.com/109720075/210598735-f75834e0-549d-4480-bf3a-e0868006c8f7.png)

**Comment by scholokov** [comment]
fixed
