### ISSUE TITLE
20210814_24_sergeevka_odessa/ Прев'ю подорожі "Дорога домой 24.08.2021"- назва подорожі російською мовою

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2953]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210814_24_sergeevka_odessa/
2.Проскролити сторінку до прев'ю "Дорога домой 24.08.2021"
3.Звернути увагу на назву подорожі

**Фактичний результат:** Назва подорожі російською мовою
**Очікуваний результат:** Назва подорожі українською мовою

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_93](https://user-images.githubusercontent.com/109720075/210600146-d6420b07-686f-42de-9839-79579c7fca25.png)

**Comment by scholokov** [comment]
fixed
