### ISSUE TITLE
20210814_24_sergeevka_odessa/ Прев'ю подорожі "Дорога домой 24.08.2021"- відсутній прапор України

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#2954]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210814_24_sergeevka_odessa/
2.Проскролити сторінку до прев'ю "Дорога домой 24.08.2021"
3.Звернути увагу на прапор України

**Фактичний результат:** Відсутній прапор України
**Очікуваний результат:** Присутній прапор України

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_92](https://user-images.githubusercontent.com/109720075/210600462-02e9b55a-8f5e-463e-96e7-f4fc8bc5295b.png)

**Comment by scholokov** [comment]
fixed
