### ISSUE TITLE
20170128_konotop/  название путешествия, в привью, отображается не в соответствии с требованиями

### ISSUE THREAD

**Issue by ghost** [scholokov/long-travel-2#2955]
Prerequisites:  
Open https://test.long-travel.live/20170128_konotop/
Steps to play: 

1. Обратить внимание на название путешествия.

Actual result: 
В привью  название путешествия отображается "20170128_konotop". 
Expected result: 
В привью актуальная название путешествия согласно требованиям "Конотоп".

Environment:  Windows 11 Professional 
Browser google chrome version 108.0.5359.125 
![photo_2023-01-04_20-52-44](https://user-images.githubusercontent.com/120852519/210630817-674f0810-1f3b-48bd-9a3c-be074232a2d1.jpg)

**Comment by DmytroMarkulych** [comment]
@GoingGoals Старайтеся не використовувати слова типу "Не правильно, не коректно, не працює і т.д", вони не приносять конкретики в суть баг репорту. В очікуваний результат додайте назву подорожі яка має бути. Інформацію можна знайти в документації

**Comment by Illia2810** [comment]
Виправлено

**Comment by DmytroMarkulych** [comment]
зверніть увагу на коментар вище

**Comment by DmitriiNasonov** [comment]
bug isn't reproduced. bug-report isn't actual
