### ISSUE TITLE
20210814_24_sergeevka_odessa/ в превью нету даты путешествия 

### ISSUE THREAD

**Issue by GoingGoals** [scholokov/long-travel-2#2956]
Передумови:
Відкрити https://test.long-travel.live/20210814_24_sergeevka_odessa/
Кроки для відтворення:

1. В превью неправильно расположена дата путешествие.

Фактичний результат: в превью нету даты путешествие 
Очікуваний результат: В превью отображается дата путешествие

Середовище: Windows 11 professionasl, brauwser google chrome Версия 108.0.5359.125
![13](https://user-images.githubusercontent.com/120852519/210633774-28822918-c64f-44c1-ae6d-5fe1e1194ca1.png)

**Comment by scholokov** [comment]
fixed

**Comment by GoingGoals** [comment]
pass
