### ISSUE TITLE
20091026_1102_toronto/ Font of the date in the Preview block does not meet  design requirements in Figma

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#2959]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20091026_1102_toronto/
2. Pay attention to the Preview block date.
3. Open DevTools.
4. Сheck font of the date.

**Actual result:**
Font: 'Open Sans', font-size: 18px
**Expected result:**
Font: 'Rubik', font-size: 18px

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/210750074-6caabad5-acf9-4981-9e4b-f7442efe6c3f.png)
![image](https://user-images.githubusercontent.com/101987790/210763627-865246e4-ad9e-458a-a675-520bcfb4a9b6.png)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
