### ISSUE TITLE
20170625_gusintsi - Год даты публикации не соответствует дате путешествия

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#296]
**Steps to reproduce:**

1. Открыть страницу https://long-travel.live/
2. Найти путешествие 20170625_gusintsi
3. Обратить внимание на год даты публикации

**Actual result:**
Год даты публикации не соответствует дате путешествия - 25.06.**2018**

**Expected result:**
Год даты публикации соответствует дате путешествия - 25.06.**2017**

![image](https://user-images.githubusercontent.com/86321831/144755235-c49e5ff8-7d4c-4ba2-8c81-9a26a65c7ce8.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
