### ISSUE TITLE
20091026_1102_toronto/ Font of the hotel name in the Hotel block does not meet  design requirements in Figma

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#2960]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20091026_1102_toronto/
2. Pay attention to the Hotel block - hotel name.
3. Open DevTools.
4. Сheck font of the hotel name.

**Actual result:**
Font: 'Open Sans', font-size: 24px
**Expected result:**
Font: 'Amazing Slab Trial', font-size: 24px

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/210752741-c7941979-b1fd-4900-b49a-12c0766e9d5d.png)
![image](https://user-images.githubusercontent.com/101987790/210762030-6a21c9c3-ef9f-465b-9951-580fd68ac855.png)

**Comment by GNatala** [comment]
#2697

**Comment by DmitriiNasonov** [comment]
checked.  Don't fixed. Font changed to Rubik. Created new bug report #3707
