### ISSUE TITLE
20091026_1102_toronto/ Font of the date in the Hotel block does not meet design requirements in Figma

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#2961]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20091026_1102_toronto/
2. Pay attention to the Hotel block - date.
3. Open DevTools.
4. Сheck font of the date.

**Actual result:**
Font: 'Open Sans', font-size: 18px
**Expected result:**
Font: 'Rubik', font-size: 18px

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/210778352-447393f1-ab03-4ec0-9f37-c50c6638527d.png)

![image](https://user-images.githubusercontent.com/101987790/210777408-ea929947-fe59-42b2-af52-b73689993b46.png)

**Comment by GNatala** [comment]
#2697

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
