### ISSUE TITLE
20091026_1102_toronto/ Font of the Logo in the header does not meet design requirements in Figma

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#2972]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20091026_1102_toronto/
2. Pay attention to the logo "Long-Travel" in the header.
3. Open DevTools.
4. Сheck font of the logo "Long-Travel".

**Actual result:**
Font: 'Open Sans', font-size: 27px
**Expected result:**
Font: 'Rubik', font-size: 36px

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://user-images.githubusercontent.com/101987790/210822266-10f73cea-6224-4fd6-8c82-17b4e227113d.png)

![image](https://user-images.githubusercontent.com/101987790/210821619-636d5df6-ccb4-47b2-b26c-a13f140a4247.png)

**Comment by scholokov** [comment]
fixed
