### ISSUE TITLE
20091026_1102_toronto/ Font of the menu element HOME in the header does not meet design requirements in Figma

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#2976]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20091026_1102_toronto/
2. Pay attention to the menu element "HOME" in the header.
3. Open DevTools.
4. Сheck font of the menu element "HOME".

**Actual result:**
Font: 'Open Sans', font-size: 18px
**Expected result:**
Font: 'Rubik', font-size: 18px

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/210841575-20d7e929-8228-4f10-b684-2d4e328223f3.png)
![image](https://user-images.githubusercontent.com/101987790/210843714-5099962c-90d1-4209-9bb3-daed6eb6f69b.png)

**Comment by GNatala** [comment]
#2697

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
