### ISSUE TITLE
20091026_1102_toronto/ Font of the menu element TRAVELS in the header does not meet design requirements in Figma

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#2977]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20091026_1102_toronto/
2. Pay attention to the menu element "TRAVELS" in the header.
3. Open DevTools.
4. Сheck font of the menu element "TRAVELS".

**Actual result:**
Font: 'Open Sans', font-size: 18px
**Expected result:**
Font: 'Rubik', font-size: 18px

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/210845121-4e5937aa-55cb-4425-9ad0-b4a731a14e30.png)
![image](https://user-images.githubusercontent.com/101987790/210844487-2046cfa5-5c2e-4f8f-a714-c65f90a8b953.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
