### ISSUE TITLE
20160618_Mezhigorie/ Travel.YoutubeVideo - missformat (2016.06.18 Межигір'я 1)

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#2978]
Steps:

1) Open page https://test.long-travel.live/20160618_Mezhigorie/
2) Scroll the page to the bottom
3) Pay attention to YoutubeVideo's name format

Actual Result: 2016.06.18 Межигір'я 1

Expected Result: 2016.06.18 Київ - Межигір'я 1

Link to specifications https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery

![Screenshot_5](https://user-images.githubusercontent.com/114935450/210847822-2ff748be-922e-4e31-9260-460df34c2fa3.png)

**Comment by scholokov** [comment]
але там 2 відео. і як їх розрізняти?

**Comment by MarynaChurylo** [comment]
Виправила
