### ISSUE TITLE
20091026_1102_toronto/ Font of the block name in the 2nd Preview block does not meet design requirements in Figma

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#2984]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20091026_1102_toronto/
2. Scroll down to the 2nd Preview block
3. Pay attention to the name of the block "Downtown-Toronto".
4. Open DevTools.
5. Сheck font of the "Downtown-Toronto" block name.

**Actual result:**
Font: 'Open Sans', font-size: 24px
**Expected result:**
Font: 'Amazing Slab Trial', font-size: 24px

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/211023621-969991e3-4490-4975-a87a-9579e0315f39.png)

![image](https://user-images.githubusercontent.com/101987790/211023309-081ad434-ab36-45a8-a9c6-b2061691b7da.png)

**Comment by DmitriiNasonov** [comment]
checked. Don't fixed. Font changed to Rubik. Created new bug report #3708
