### ISSUE TITLE
20200719_belya_tsercov # 23 - Название видео Белая Церковь-Киев не соответствует языку страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#299]
**Steps to reproduce:**

1. Открыть страницу https://long-travel.live/20200719_belya_tsercov/
2. Обратить внимание на название видео 2020.07.19 Белая Церковь - Киев

**Actual result:**
Название видео не соответствует языку страны - 2020.07.19 **Белая Церковь - Киев**

**Expected result:**
Название видео соответствует языку страны -  - 2020.07.19 **Біла Церква - Київ**

![image](https://user-images.githubusercontent.com/86321831/144755836-2a39d730-5147-44a2-8457-8ba26f57418d.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
