### ISSUE TITLE
20091026_1102_toronto/ Font of the block name in the 4th Preview block "Pumpkin Parade" does not meet design requirements in Figma

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#2999]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20091026_1102_toronto/
2. Scroll down to the 4th Preview block
3. Pay attention to the name of the block "Pumpkin Parade".
4. Open DevTools.
5. Сheck font of the "Pumpkin Parade" block name.

**Actual result:**
Font: 'Open Sans', font-size: 24px
**Expected result:**
Font: 'Amazing Slab Trial', font-size: 24px

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/211315821-3a78abec-889c-4ee3-be37-d8470aa6964d.png)
![image](https://user-images.githubusercontent.com/101987790/211023309-081ad434-ab36-45a8-a9c6-b2061691b7da.png)

**Comment by DmytroMarkulych** [comment]
@GNatala давайте перефразуємо summary щоб воно стало унікальним

**Comment by GNatala** [comment]
#2697

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
**An issue is reproduced.**

**Actual result:**
Font: 'Rubik', font-size: 24px

**Expected result:**
Font: 'Amazing Slab Trial', font-size: 24px

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64), Firefox 111.0.1

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/5842ac0d-779f-4fca-a798-45d6d1abc9d1)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/long-travel-2/assets/88647733/00317631-3366-472d-ac8b-32c4f807e633)

**Comment by GNatala** [comment]
додала

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
