### ISSUE TITLE
20200719_belya_tsercov # 23 - Отсутствует название блока Дорога

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#300]
**Steps to reproduce:**

1. Открыть страницу https://long-travel.live/20200719_belya_tsercov/
2. Спуститься до видео Белая Церковь - Киев
3. Обратить внимание на наличие блока Дорога

**Actual result:**
Название блока **Дорога: Біла Церква - Київ отсутствует**

**Expected result:**
Название блока **Дорога: Біла Церква - Київ присутствует**

![image](https://user-images.githubusercontent.com/86321831/144756448-933313f2-8cb3-42ca-aa92-595085842c11.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
