### ISSUE TITLE
20091026_1102_toronto/ Text font in the footer does not meet design requirements in Figma

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3001]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20091026_1102_toronto/
2. Scroll down to the footer.
3. Pay attention to the name of the text "2016-2023 Powered by QAX".
4. Open DevTools.
5. Сheck font of the text "2016-2023 Powered by QAX".

**Actual result:**
Font: 'Open Sans', font-size: 24px
**Expected result:**
Font: 'Rubik', font-size: 24px

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/211324538-5084f6a0-090d-490d-8cb4-d46b908ca3ad.png)
![image](https://user-images.githubusercontent.com/101987790/211326571-64f3f493-0f2c-4c43-927d-97f4e24fadb8.png)

**Comment by GNatala** [comment]
#2697

**Comment by scholokov** [comment]
fixed
