### ISSUE TITLE
20151031_haisyn_uman/ Travel's date format in the 1st Preview block does not meet design requirements in Figma

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3003]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20151031_haisyn_uman/
2. Pay attention to the Travel's date format in the Preview block.

**Actual result:**
Travel's date format 31.10-01.11.2015
**Expected result:**
Travel's date format 31.10.2015-01.11.2015

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment** 
![image](https://user-images.githubusercontent.com/101987790/211549092-cfce385f-87e0-45dc-a017-15019a13c9de.png)

**Comment by DmytroMarkulych** [comment]
@GNatala давайте перефразуємо Summary щоб воно стало унікальним

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
