### ISSUE TITLE
20151031_haisyn_uman/ Page content language is russian, not Ukrainian as required

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3004]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20151031_haisyn_uman/
2. Scroll to the content on the page.
3. Pay attention to the language of the content.

**Actual result:**
Language of the content is russian.
**Expected result:**
Language of the content is Ukrainian.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment** 
![image](https://user-images.githubusercontent.com/101987790/211551374-f1b5bed7-d03f-452f-9cc8-ca4e01622499.png)
![image](https://user-images.githubusercontent.com/101987790/211551577-d9f54b42-f6a3-4bb8-9513-e1085ce57676.png)
![image](https://user-images.githubusercontent.com/101987790/211551729-c68a9d5e-2171-4b30-ab1e-dbab85f90572.png)

**Comment by DmytroMarkulych** [comment]
@GNatala давайте в Summary вкажемо в чому конкретно дефект

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
