### ISSUE TITLE
20210814_24_sergeevka_odessa/ Прев'ю подорожі "Сергіївка, Одеська область,14.08.2021-23.08.2021"- присутні два прапори України

### ISSUE THREAD

**Issue by andry1729** [scholokov/long-travel-2#3007]
**Кроки відтворення:**
1.Відкрити сторінку https://test.long-travel.live/20210814_24_sergeevka_odessa/
2.Проскролити сторінку до прев'ю "Сергіївка, Одеська область,14.08.2021-23.08.2021"
3.Звернути увагу на прапори України

**Фактичний результат:** Присутні два прапори України
**Очікуваний результат:** Присутній прапор України

**Середовище:**
Windows 10
Google Chrome Версія 108.0.5359.95 (Офіційне складання), (64 біт)
![Screenshot_2](https://user-images.githubusercontent.com/109720075/211660572-cf35a615-053a-4389-a9e2-b9508a150185.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
