### ISSUE TITLE
20150523_picnic_dnipro/ 2nd travel's preview, travel's name - misregion (Дніпропетровська область)

### ISSUE THREAD

**Issue by MarynaChurylo** [scholokov/long-travel-2#3008]
Steps:

1) Open page https://test.long-travel.live/20150523_picnic_dnipro/
2) Scroll the page to the 2nd preview
3) Pay attention to the travel's name

Actual Result: Дніпропетровська область

Expected Result: Київська область

![Screenshot_2](https://user-images.githubusercontent.com/114935450/211805259-1fe47d7b-a8c7-42a2-8f23-3de83f2886e5.png)

**Comment by scholokov** [comment]
fixed

**Comment by MarynaChurylo** [comment]
successful
