### ISSUE TITLE
20151031_haisyn_uman/ Element "Link" to production in the Map Legend is missed

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3009]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20151031_haisyn_uman/
2. Scroll to the Map of travel.
3. Pay attention to the Legend.

**Actual result:**
There is no element "Link" to production is the end of list of waypoints.
**Expected result:**
Element "Link" to production is the end of list of waypoints.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment** 
![image](https://user-images.githubusercontent.com/101987790/211840752-18d2a7ec-7111-4724-bf82-32d9805092ec.png)
![image](https://user-images.githubusercontent.com/101987790/211840216-336a5afb-150a-4028-99f9-b90b689f6f28.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
