### ISSUE TITLE
20200719_belya_tsercov # 23 - Отсутствует название области и страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#301]
**Steps to reproduce:**

1. Открыть страницу https://long-travel.live/20200719_belya_tsercov/
2.Обратить внимание на наличие названия области и страны на странице путешествия

**Actual result:**
Название области и страны отсутствует

**Expected result:**
Название области и страны присутствует

![image](https://user-images.githubusercontent.com/86321831/144756668-2129ed17-d3f9-429f-8f2d-53559f5e0388.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
not fixed
![image](https://user-images.githubusercontent.com/86321831/144928896-810c3a76-b32b-4485-9102-0fd329ee6dfc.png)

**Comment by scholokov** [comment]
fixed

**Comment by scholokov** [comment]
please retest

**Comment by yanadiya** [comment]
проверено
