### ISSUE TITLE
20151031_haisyn_uman/ Preview foto in the Map Legend is missed

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3010]
*Steps to reproduce:**

1. Open https://test.long-travel.live/20151031_haisyn_uman/
2. Scroll to the Map of travel.
3. Pay attention to the Legend.

**Actual result:**
There is no Preview foto in the Legend of the Map.
**Expected result:**
Preview foto is in the Legend of the Map.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment** 
![image](https://user-images.githubusercontent.com/101987790/211843690-9293e434-26bb-4def-835f-2b3ac436acb3.png)

![image](https://user-images.githubusercontent.com/101987790/211842439-d91499e4-e297-4963-a2c1-35f9d9e62f45.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
