### ISSUE TITLE
20151031_haisyn_uman/  YoutubeVideo's date format does not meet the requirements

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3012]
Steps to reproduce:**

1. Open https://test.long-travel.live/20151031_haisyn_uman/
2. Scroll to the Travel.YoutubeVideo.
3. Play the Travel.YoutubeVideo.
4. Pay attention to the YoutubeVideo's date format.

**Actual result:**
YoutubeVideo's date format is 01.11.2015
**Expected result:**
YoutubeVideo's date format is 2015.11.01

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment** 
![image](https://user-images.githubusercontent.com/101987790/212048432-ad558d46-27bf-4e4d-9065-36e9f9b8e1e0.png)
![image](https://user-images.githubusercontent.com/101987790/212047880-48723502-2339-4f1b-86c5-0e685fe2bb54.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
