### ISSUE TITLE
20151031_haisyn_uman/ Font of text "2016-2023 Powered by QAX" in the footer does not meet design requirements in Figma

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3013]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20151031_haisyn_uman/
2. Scroll down to the footer.
3. Pay attention to the name of the text "2016-2023 Powered by QAX".
4. Open DevTools.
5. Сheck font of the text "2016-2023 Powered by QAX".

**Actual result:**
Font: 'Open Sans', font-size: 24px
**Expected result:**
Font: 'Rubik', font-size: 24px

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/212553750-5b021529-e142-4319-8bf8-7f26a89971b0.png)

![image](https://user-images.githubusercontent.com/101987790/211326571-64f3f493-0f2c-4c43-927d-97f4e24fadb8.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
