### ISSUE TITLE
20151031_haisyn_uman/ Font of the "Дата публікації 26.10.2009" in the end of the page does not meet design requirements in Figma

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3014]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20151031_haisyn_uman/
2. Scroll down to the end of the page.
3. Pay attention to the "Дата публікації 26.10.2009".
4. Open DevTools.
5. Сheck font of the "Дата публікації 26.10.2009".

**Actual result:**
Font: 'Open Sans', font-size: 24px
**Expected result:**
Font: 'Rubik', font-size: 24px

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/212554193-4139cec4-c33c-4bf5-b49e-9326dff497e4.png)
![image](https://user-images.githubusercontent.com/101987790/210804887-44a87c07-b940-4845-832c-f3eb86387778.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
