### ISSUE TITLE
20151031_haisyn_uman/ Font 'Open Sans' of the Logo "Long-Travel" in the header does not meet design requirements in Figma

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3015]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20151031_haisyn_uman/
2. Pay attention to the logo "Long-Travel" in the header.
3. Open DevTools.
4. Сheck font of the logo "Long-Travel".

**Actual result:**
Font: 'Open Sans', font-size: 27px
**Expected result:**
Font: 'Rubik', font-size: 36px

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://user-images.githubusercontent.com/101987790/212555430-9bf75918-21fe-4b10-a568-929ee10d6eed.png)
![image](https://user-images.githubusercontent.com/101987790/212555738-1eb9e41f-c884-4b80-85c9-5d75212b34b8.png)

**Comment by DmytroMarkulych** [comment]
@GNatala давайте переіменуємо summary таким чином, що воно стало унікальним

**Comment by DmytroMarkulych** [comment]
@GNatala давайте, ще додамо атрибути Severity, Priority, Component
![image](https://user-images.githubusercontent.com/88647733/213202868-bfaa6a2c-bc74-4694-aca7-0f1d75d4e5f2.png)

**Comment by DmytroMarkulych** [comment]
@GNatala Priority виставляється РМ, і призначене для пріорітизації дефекту.

**Comment by GNatala** [comment]
@DmytroMarkulych Дякую, Priority прибрала.

**Comment by poroskundenys** [comment]
готово

**Comment by GNatala** [comment]
перевірено
