### ISSUE TITLE
20151031_haisyn_uman/ Spelling mistake in the word "біль " in 1st block of content on the page

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3016]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20151031_haisyn_uman/
2. Scroll down to the 1st block of content on the page.
4. Pay attention to the sentence: "Періодично зустрічаються ділянки з біль поганим покриттям." 
Espessialy word:    **біль** 

**Actual result:**
Періодично зустрічаються ділянки з **біль** поганим покриттям.

**Expected result:**
Періодично зустрічаються ділянки з **більш** поганим покриттям.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/212557933-5f0cd4ee-6635-4f57-85f4-7e95bef8a508.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
