### ISSUE TITLE
20151031_haisyn_uman/ Font of the menu element "TRAVELS" in the header does not meet design requirements in Figma

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3018]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20151031_haisyn_uman/
2. Pay attention to the menu element "TRAVELS" in the header.
3. Open DevTools.
4. Сheck font of the menu element "TRAVELS".

**Actual result:**
Font: 'Open Sans', font-size: 18px
**Expected result:**
Font: 'Rubik', font-size: 18px

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/212739138-01d84948-402a-4b46-b2e8-eaf916a0ecd6.png)

![image](https://user-images.githubusercontent.com/101987790/210844487-2046cfa5-5c2e-4f8f-a714-c65f90a8b953.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
