### ISSUE TITLE
20151031_haisyn_uman/ Font 'Open Sans' of the menu element "HOME" in the header does not meet design requirements in Figma

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3019]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20151031_haisyn_uman/
2. Pay attention to the menu element "HOME" in the header.
3. Open DevTools.
4. Сheck font of the menu element "HOME".

**Actual result:**
Font: 'Open Sans', font-size: 18px
**Expected result:**
Font: 'Rubik', font-size: 18px

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/212740245-3da91ec8-8141-4a53-9910-c078350302ec.png)

![image](https://user-images.githubusercontent.com/101987790/210843714-5099962c-90d1-4209-9bb3-daed6eb6f69b.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
