### ISSUE TITLE
20200719_belya_tsercov # 23 - Лишний контент на странице

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#302]
**Steps to reproduce:**

1. Открыть страницу https://long-travel.live/20200719_belya_tsercov/
2. Проскроллить страницу ниже карты
3. Обратить внимание на контент, присутствующий под картой

**Actual result:**
Контент **присутствует - 350km**

**Expected result:**
Контент **отсутствует**

![image](https://user-images.githubusercontent.com/86321831/144757041-bbd9b11e-04e2-42fe-9dae-fa98f4c66d9e.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
