### ISSUE TITLE
20130908_tropical_park/Різні дати публікації сторінки подорожі на продакшен і на тестовій версії продукту

### ISSUE THREAD

**Issue by Natashaarduino** [scholokov/long-travel-2#3023]
**Передумови:**
Зайти на сторінку подорожі за посиланням
[https://test.long-travel.live/20130908_tropical_park/]

**Кроки для відтворення:**

1. Знайти на сторінці подорожі мапу.
2. На мапі подорожі знайти активний елемент "Link".
3. Натиснути на кнопку "Link".
4. На сторінці, що відкрилася, знайти дату публікації.
5. Перевірити дату публікації сторінки подорожі на продакшен і на тестовій версії продукту.

*Очікуваний результат:
Дати публікації сторінки подорожі на продакшен і на тестовій версії продукту однакові.

*Фактичний результат:
Різні дати публікації сторінки подорожі на продакшен і на тестовій версії продукту.

*Середовище:
ОС Windows 10 Pro
Браузер Google Chrome версія 108.0.5359.126 (64 біт)
![Screenshot_8](https://user-images.githubusercontent.com/96045169/212767693-57133c1b-6e7c-4b92-8321-024d7e244479.png)

**Comment by DmytroMarkulych** [comment]
@Natashaarduino 
Тестове середовище тестуємо згідно документації та дизайну

**Comment by DmitriiNasonov** [comment]
canceled
