### ISSUE TITLE
20151031_haisyn_uman/ Font 'Open Sans' of the block name in the 1st Preview block does not meet design requirements in Figma

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3026]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20151031_haisyn_uman/
2. Pay attention to the 1st Preview block name.
3. Open DevTools.
4. Сheck font of the block name.

**Actual result:**
Font: 'Open Sans', font-size: 18px
**Expected result:**
Font: 'Amazing Slab Trial', font-size: 24px

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/213203320-c206d5b3-d86e-4bb1-aeb4-47fb41073ece.png)

![image](https://user-images.githubusercontent.com/101987790/211023309-081ad434-ab36-45a8-a9c6-b2061691b7da.png)

**Comment by DmytroMarkulych** [comment]
@GNatala давайте ще додамо теги: severity, issue type, component

**Comment by DmytroMarkulych** [comment]
@GNatala Priority виставляється РМ, і призначене для пріорітизації дефекту.

**Comment by GNatala** [comment]
@DmytroMarkulych Дякую, Priority прибрала. Додавала його по вашій рекомендації від 18.01.2022 - "давайте, ще додамо атрибути Severity, Priority, Component". Виправляю.

**Comment by DmytroMarkulych** [comment]
@GNatala Це була невелика перевірка)

**Comment by GNatala** [comment]
@DmytroMarkulych Дякую. Хитро. А, підкажіть, будь ласка, в теоріі кажуть, Priority виставляє PM, Severity - QA. А на попередній дошці все це виставляли QA. Чому так було заведено?

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
**An issue is reproduced.**

**Actual result:**
Font: 'Open Sans', font-size: 18px

**Expected result:**
Font: 'Amazing Slab Trial', font-size: 24px

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64), Firefox 111.0.1

**Attachment:**


![Image](https://github.com/scholokov/long-travel-2/assets/101987790/4256abff-872e-4603-9061-dce2534452f2)

**Comment by scholokov** [comment]
not actual according to new design

**Comment by GNatala** [comment]
not actual
