### ISSUE TITLE
20151031_haisyn_uman/ Font 'Open Sans' of  the "Гайсин, Вінницька обл., Україна" in the 2nd Preview block does not meet design requirements in Figma

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3028]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20151031_haisyn_uman/
2. Pay attention to the 2nd Preview block  "Гайсин, Вінницька обл., Україна".
3. Open DevTools.
4. Сheck font of the "Гайсин, Вінницька обл., Україна".

**Actual result:**
Font: 'Open Sans', font-size: 18px
**Expected result:**
Font: 'Amazing Slab Trial', font-size: 18px

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/213423219-e183a6c3-5bd9-488b-bf1e-0229e16f97d4.png)
![image](https://user-images.githubusercontent.com/101987790/213423420-1086c128-7037-4e40-9ecd-4cd4dbd6d4de.png)

**Comment by DmytroMarkulych** [comment]
@GNatala Priority виставляється РМ, і призначене для пріорітизації дефекту.

**Comment by GNatala** [comment]
@DmytroMarkulych Дякую, Priority прибрала.

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
**An issue is reproduced.**

**Actual result:**
Font: 'Rubik', font-size: 18px

**Expected result:**
Font: '**Amazing Slab Trial'**, font-size: 18px

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64), Firefox 111.0.1

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/99261349-41ac-48e0-9f16-81006c5ed0d1)

**Comment by scholokov** [comment]
not actual according to new design

**Comment by GNatala** [comment]
not actual
