### ISSUE TITLE
20151031_haisyn_uman/ Mis font 'Open Sans' of the block name in the 2nd Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3029]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20151031_haisyn_uman/
2. Pay attention to the 2nd Preview block name.
3. Open DevTools.
4. Сheck font of the block name.

**Actual result:**
Font: 'Open Sans', font-size: 24px
**Expected result:**
Font: 'Amazing Slab Trial', font-size: 24px

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/213479835-7f2b5646-2678-448b-aca1-112de75dc9d0.png)

![image](https://user-images.githubusercontent.com/101987790/211023309-081ad434-ab36-45a8-a9c6-b2061691b7da.png)

**Comment by DmytroMarkulych** [comment]
@GNatala Priority виставляється РМ, і призначене для пріорітизації дефекту. І давайте зробимо summary більш кнікальним, уникнувши фрази "не відповідає вимогам..."

**Comment by GNatala** [comment]
@DmytroMarkulych Дякую, Priority прибрала. Summary змінила.

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
**An issue is reproduced.**

**Actual result:**
Font: 'Rubik', font-size: 24px

**Expected result:**
Font: '**Amazing Slab Trial'**, font-size: 24px

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64), Firefox 111.0.1

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/cce95859-0056-4bc0-84c3-845bf9d167a5)

**Comment by poroskundenys** [comment]
готово

**Comment by GNatala** [comment]
перевірено
