### ISSUE TITLE
20180428_0501_beregovo # 162 - Дата публикации не соответствует стартовой дате путешествия

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#303]
**Steps to reproduce:**

1. Открыть страницу https://long-travel.live/
2. Найти путешествие 20180428_0501_beregovo
3. Обратить внимание на дату публикации

**Actual result:**
Дата публикации не соответствует стартовой дате путешествия - 01.05.2018

**Expected result:**
Дата публикации не соответствует стартовой дате путешествия -28.04.2018

![image](https://user-images.githubusercontent.com/86321831/144757297-1ad14149-9493-4be9-9fd8-6bfacac019ed.png)
**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
Fixed

**Comment by yanadiya** [comment]
проверено
