### ISSUE TITLE
20150502_06_hungary/ Missing preview photo in map legend

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3034]
Steps to Reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to on the map, in the travel list find "Kotedzhne Mistechko Oazys Karpat, Polyana"

Actual Result:
There is no photo preview under the mark "Kotezhne Mistechko Oazys Karpat, Polyana"

Expected Result:
There is a photo preview under the mark "Kotezhne Mistechko Oazys Karpat, Polyana"

Environments:
MacBook Pro 13, Chrome 108.0.5359.124 (x86_64)

Attachments:
<img width="1438" alt="Screenshot 2023-01-19 at 21 27 11" src="https://user-images.githubusercontent.com/89859006/213541738-7e15b9a8-e3f9-46e2-9515-332a71f04d9d.png">

![Screenshot-2023-01-19-at-21 28 11](https://user-images.githubusercontent.com/89859006/213542466-2856c091-4106-4068-934e-c87837022be4.jpg)

**Comment by DmytroMarkulych** [comment]
@k335x 
1. В Summary давайте прибиремо фразу "There is..." подібні фрази не вказують на конкретний елемент. Краще її замінити щось по типу "Відсутнє фото ... (і вказати конкретно де)". Теж стосується очікуваного та актуального результатів. 
2. В кроках для відтворення останнім кроком вказуйте "Pay attention to.." і назву блоку або елемента в якому присутній дефект.
3. Після кроків для відтворення варто вказувати спочатку Actual Result, а тоді вже Expected Result. Таким чином, відразу після кроків для відтворення ми вказуємо "Що не так" і після того "Як має бути".
4. Додайте будь ласка атрибути в баг репорт:

![Image](https://user-images.githubusercontent.com/88647733/214140005-72c90260-be8e-426a-9948-d98b2623d7f5.png)

**Comment by k335x** [comment]
@DmytroMarkulych  все виправив, дякую

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
@scholokov Доброго дня, ось [лінк](https://github.com/scholokov/long-travel-2/issues/3035) на баг який ви виправили

**Comment by DmytroMarkulych** [comment]
@k335x після ретесту просто вказуємо чи дефект відтворюється і якщо відтворюється то додаємо скрін. Це стосується саме даного дефекту

**Comment by k335x** [comment]
@DmytroMarkulych  баг відтворюється
<img width="1313" alt="Screenshot 2023-02-02 at 15 44 36" src="https://user-images.githubusercontent.com/89859006/216341747-5d3a75bc-94f3-4c96-9d4d-ca1b57d8ecad.png">

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
@scholokov баг відтворюється

**Comment by scholokov** [comment]
на скріні видне фото. не зрозуміло в чому проблема

**Comment by k335x** [comment]
incorrect bug

**Comment by k335x** [comment]
an error in the requirements
