### ISSUE TITLE
20150502_06_hungary/ Missing preview photo in map legend

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3035]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to on the map, in the travel list find  "Hotel Palma, Nyírbátor, Hungary"
  
Actual result:
Map Legend is missing a preview photo.
Expected result:
Preview photo is in the Legend of the Map.

Environment:
MacBook Pro 13, Google Chrome 108.0.5359.124 (Official Build) (x86_64)

Attachment:
<img width="1437" alt="Screenshot 2023-01-20 at 13 38 53" src="https://user-images.githubusercontent.com/89859006/213686757-4f9d92e2-3817-4a22-ae30-fb30fb0fdaf7.png">

![Screenshot-2023-01-19-at-21 28 11](https://user-images.githubusercontent.com/89859006/213686806-e24dbac4-b71d-4103-b11e-cc6baeedc432.jpg)

**Comment by DmytroMarkulych** [comment]
@k335x давайте ще із Actual result прибиремо there is

**Comment by k335x** [comment]
@DmytroMarkulych виправив, дякую

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
@scholokov passed
