### ISSUE TITLE
20151031_haisyn_uman/ Mis font 'Open Sans' of the date in the Hotel block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3036]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20151031_haisyn_uman/
2. Pay attention to the Hotel block - date.
3. Open DevTools.
4. Сheck font of the date.

**Actual result:**
Font: 'Open Sans', font-size: 18px
**Expected result:**
Font: 'Rubik', font-size: 18px

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/213711856-f89a8379-99e9-412d-accd-64b794767341.png)

![image](https://user-images.githubusercontent.com/101987790/210777408-ea929947-fe59-42b2-af52-b73689993b46.png)

**Comment by DmytroMarkulych** [comment]
@GNatala Priority виставляється РМ, і призначене для пріорітизації дефекту. І давайте зробимо summary більш кнікальним, уникнувши фрази "не відповідає вимогам..."

**Comment by GNatala** [comment]
@DmytroMarkulych Дякую, Priority прибрала. Summary змінила.

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
