### ISSUE TITLE
20151031_haisyn_uman/ Mis date format "31.10-01.11.2015" in the Hotel block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3037]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20151031_haisyn_uman/
2. Pay attention to the Date format in the Hotel block.

**Actual result:**
Travel's date format 31.10-01.11.2015
**Expected result:**
Travel's date format 31.10.2015-01.11.2015

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment** 
![image](https://user-images.githubusercontent.com/101987790/213752781-81f87d2b-bd25-4299-abc5-b9c79c655bbe.png)
![image](https://user-images.githubusercontent.com/101987790/213754992-2e422156-bf60-4cba-a5fe-3a59240427e8.png)

**Comment by DmytroMarkulych** [comment]
@GNatala 
1.Priority виставляється РМ, і призначене для пріорітизації дефекту. 
2.І давайте зробимо summary більш унікальним, уникнувши фрази "не відповідає вимогам..."
3. Швидше за все, що цей дефект буде відтворюватися на всіх платформах

**Comment by GNatala** [comment]
@DmytroMarkulych Дякую, Priority прибрала. Summary змінила.

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
