### ISSUE TITLE
20150502_06_hungary/ The photo is missing in the legend of the map "Zoo, Debrecen, Hungary".

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3039]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to on the map, in the travel list find  "Zoo, Debrecen, Hungary"

Actual result:
The photo is missing in the legend of the map "Zoo, Debrecen, Hungary".

Expected result:
There is a photo in the legend of the map "Zoo, Debrecen, Hungary".

Environment:
MacBook Pro 13, Google Chrome 108.0.5359.124 (Official Build) (x86_64)

Attachment:

<img width="1435" alt="Screenshot 2023-01-20 at 19 05 58" src="https://user-images.githubusercontent.com/89859006/213760531-06d7be11-b00b-461c-8938-10384fbe324e.png">

![Screenshot-2023-01-19-at-21 28 11](https://user-images.githubusercontent.com/89859006/213760309-8830e96c-d514-4667-a397-d3b9f7a8340c.jpg)

**Comment by DmytroMarkulych** [comment]
@k335x 
1. Давайте приберемо фразу "There is.."  з Actual Result 
2. Перевірте чи цей дефект відтворюється на інших девайсах, швидше за все що це так

**Comment by k335x** [comment]
@DmytroMarkulych баг відтворюється на всіх девайсах, виправив, дякую

**Comment by k335x** [comment]
@DmytroMarkulych можливо, але якщо опиратися на тз то повинно бути фото

**Comment by DmytroMarkulych** [comment]
@k335x так, але summary варто зробити унікальним

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
@scholokov баг відтворюється
<img width="1312" alt="Screenshot 2023-02-08 at 09 56 33" src="https://user-images.githubusercontent.com/89859006/217468854-ae163376-3196-41cd-878f-9ac63da13a27.png">

**Comment by k335x** [comment]
an error in the requirements
