### ISSUE TITLE
20180428_0501_beregovo # 162 - Название видео в блоке Дорога: Київ – Львів не соответствует языку страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#304]
**Steps to reproduce:**

1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. В блоке Дорога: Київ – Львів обратить внимание на название видео

**Actual result:**
Название видео в блоке Дорога: Київ – Львів **не соответствует** языку страны - 2018.04.28 **Киев - Берегово 1**

**Expected result:**
Название видео в блоке Дорога: Київ – Львів **соответствует** языку страны - 2018.04.28 **Київ - Берегове 1**

![image](https://user-images.githubusercontent.com/86321831/144758298-b66823b9-7c0e-4c1e-8ced-759c28cdfaf9.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
not fixed

![image](https://user-images.githubusercontent.com/86321831/145689306-2b797765-0ae3-44bb-8c41-75d563dd4887.png)

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
