### ISSUE TITLE
20150502_06_hungary/ Points of interest are connected to an intermediate point by non-dotted lines

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3045]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Scroll to the Map of travel.
  3. Note the route from Hotel Palma, Nyírbátor, Hungary to Zoo, Debrecen, Hungary

Actual result:
  Route from Hotel Palma, Nyirbator, Hungary to Zoo, Debrecen, Hungary following the marked solid line.

Expected result:
  The route from Hotel Palma, Nyirbator, Hungary to the Zoo, Debrecen, Hungary along the marked dotted line.

Environment:
MacBook Pro 13, Google Chrome 108.0.5359.124 (Official Build) (x86_64)

Attachment:
<img width="1435" alt="Screenshot 2023-01-20 at 19 25 28" src="https://user-images.githubusercontent.com/89859006/213764461-0a92b0e2-43cc-4a6e-88fe-fa9bda917887.png">

<img width="1437" alt="Screenshot 2023-01-20 at 19 26 25" src="https://user-images.githubusercontent.com/89859006/213764530-d2df97b7-2d9f-43f4-8c6e-a61c58a071f1.png">

**Comment by DmytroMarkulych** [comment]
@k335x додайте додаткові атрибути (включаючи type issue, Severity, Device, Component)
![image](https://user-images.githubusercontent.com/88647733/214143644-e426d3ad-ebff-4ea5-a5fd-6d3248a38d89.png)

**Comment by k335x** [comment]
@DmytroMarkulych виправив, дякую

**Comment by DmytroMarkulych** [comment]
@k335x швидше за все цей дефект відтвориться і на інших девайсах. Зверніть будь ласка на це увагу

**Comment by k335x** [comment]
@DmytroMarkulych так, баг відтворюється на всіх девайсах, дякую

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
@scholokov passed
