### ISSUE TITLE
20150502_06_hungary/ The layout key "layout=mosaic" is false

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3046]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Scroll to the grid photo
  3. Open to DevTools

Actual result:
  The layout key "layout=mosaic" is false

Expected result:
  The layout key "layout=mosaic" has a value

Environment:
MacBook Pro 13, Google Chrome 108.0.5359.124 (Official Build) (x86_64)

<img width="1440" alt="Screenshot 2023-01-23 at 15 32 42" src="https://user-images.githubusercontent.com/89859006/214054721-32172057-4e2e-4ac5-80c6-829770f22ded.png">

<img width="951" alt="Screenshot 2023-01-23 at 15 36 16" src="https://user-images.githubusercontent.com/89859006/214054746-dc7a6dd5-c5bc-4e47-af61-c5255b97f521.png">

**Comment by DmytroMarkulych** [comment]
@k335x додайте додаткові атрибути (включаючи type issue, Severity, Device, Component)
![image](https://user-images.githubusercontent.com/88647733/214143644-e426d3ad-ebff-4ea5-a5fd-6d3248a38d89.png)

**Comment by k335x** [comment]
@DmytroMarkulych виправив, дякую

**Comment by DmytroMarkulych** [comment]
@k335x 
1. В Summary не варто використовувати слова та фрази, типу "invalide" так як вони не дають конкретики. Краще вказуйте на пряму на проблему

**Comment by k335x** [comment]
@DmytroMarkulych виправив, дякую

**Comment by DmytroMarkulych** [comment]
@k335x що Ви маєте на увазі під "false"?

**Comment by k335x** [comment]
@DmytroMarkulych має хибне значення (тобто неправильне)

**Comment by k335x** [comment]
@DmytroMarkulych  виправив, дякую

**Comment by scholokov** [comment]
стосовно якої саме галереї цей опис?

**Comment by k335x** [comment]
@scholokov  галерея відносить до блоку прев'ю "Киев Украина – Nyírbátor Hungary"
<img width="1439" alt="Screenshot 2023-02-08 at 10 09 15" src="https://user-images.githubusercontent.com/89859006/217471976-359c6039-3368-49f7-aae7-3aa90973adc0.png">

**Comment by scholokov** [comment]
fixed

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
@scholokov  bug reproduce 
Замість ключа "mosaic" повинен бути ключ "random"
<img width="1314" alt="Screenshot 2023-02-08 at 11 32 03" src="https://user-images.githubusercontent.com/89859006/217490638-23e32e39-7644-406d-a8d9-6f03a86b0a5e.png">

**Comment by scholokov** [comment]
please retest

**Comment by k335x** [comment]
passed
