### ISSUE TITLE
20150502_06_hungary/ When clicking on the scroll arrows in LightBox, the photo is not displayed

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3047]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Scroll to the photo
  3. Click on the photo
  4. Try flipping through the photo

Actual result:
When clicking on the scroll arrows in LightBox, the photo is not displayed

Expected result:
When clicking on the scroll arrows in LightBox, the photo displayed

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1438" alt="Screenshot 2023-01-23 at 15 58 22" src="https://user-images.githubusercontent.com/89859006/214059148-474168ba-a0b4-4c2f-8cfd-d0bf8b684f0c.png">

<img width="1438" alt="Screenshot 2023-01-23 at 16 00 29" src="https://user-images.githubusercontent.com/89859006/214059978-45c15a5d-90bf-446f-801d-44059a836f30.png">

**Comment by DmytroMarkulych** [comment]
@k335x додайте додаткові атрибути (включаючи type issue, Severity, Device, Component)
![image](https://user-images.githubusercontent.com/88647733/214143644-e426d3ad-ebff-4ea5-a5fd-6d3248a38d89.png)

**Comment by DmytroMarkulych** [comment]
@k335x Старайтеся не використовувати фрази типу doesn't work, так як це не дає конкретики. Краще вказати що саме не відбувається

**Comment by k335x** [comment]
@DmytroMarkulych все виправив, дякую

**Comment by DmytroMarkulych** [comment]
@k335x 
Давайте перефразуємо Summary таким чином щоб воно відповідало на 3 питання: Де? Що? Коли?

**Comment by k335x** [comment]
@DmytroMarkulych виправив, дякую

**Comment by DmytroMarkulych** [comment]
@k335x Summary вийшло гарним, давайте ще додамо подібних  деталей в Actual, Expected Results

**Comment by k335x** [comment]
@DmytroMarkulych змінив Results, дякую

**Comment by scholokov** [comment]
please retest
