### ISSUE TITLE
20150502_06_hungary/ The name of the traffic object is not specified

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3048]
Steps to reproduce:

1. Open: https://test.long-travel.live/20150502_06_hungary/
2.  Scroll to the "02.05.2015"

Actual result:
The name of the traffic object is not specified

Expected result:
The name of the traffic object is specified

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1437" alt="Screenshot 2023-01-23 at 16 16 40" src="https://user-images.githubusercontent.com/89859006/214062854-f133f663-83ca-43a0-8432-37c96a8b0357.png">

<img width="1436" alt="Screenshot 2023-01-23 at 16 17 17" src="https://user-images.githubusercontent.com/89859006/214062874-a74652ab-434e-4470-a906-438e04aa3dc0.png">

**Comment by DmytroMarkulych** [comment]
@k335x додайте додаткові атрибути (включаючи type issue, Severity, Device, Component)
![image](https://user-images.githubusercontent.com/88647733/214143644-e426d3ad-ebff-4ea5-a5fd-6d3248a38d89.png)

**Comment by k335x** [comment]
@DmytroMarkulych виправив, дякую

**Comment by DmytroMarkulych** [comment]
@k335x Швидше за все, що цей дефект відтворюється на всіх девайсах

**Comment by k335x** [comment]
@DmytroMarkulych так, дякую

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
@scholokov passed
