### ISSUE TITLE
20150502_06_hungary/ The link to the hotel "Отель Оазис Карпат" is missing in the preview block "Поляна, Украина" 

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3049]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Scroll to the title "Отель Оазис Карпат"
  
Actual result:
The link to the hotel "Отель Оазис Карпат" is missing in the preview block "Поляна, Украина" 

Expected result:
In the block "Поляна, Украина" a link to the hotel "Отель Оазис Карпат" has been inserted

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1431" alt="Screenshot 2023-01-23 at 16 40 44" src="https://user-images.githubusercontent.com/89859006/214068678-47fe749d-8e6c-44ba-b228-76fd0c94fe9a.png">

<img width="1025" alt="Screenshot 2023-01-23 at 16 41 31" src="https://user-images.githubusercontent.com/89859006/214068695-aad0e409-2cbf-4dca-bd3d-3f9090eae5a5.png">

**Comment by DmytroMarkulych** [comment]
@k335x додайте додаткові атрибути (включаючи type issue, Severity, Device, Component)
![image](https://user-images.githubusercontent.com/88647733/214143644-e426d3ad-ebff-4ea5-a5fd-6d3248a38d89.png)

**Comment by k335x** [comment]
@DmytroMarkulych виправив, дякую

**Comment by DmytroMarkulych** [comment]
@k335x
1. Давайте не будемо використовувати фрази типу "There is..". 
Приклад: Де?- В блоці "Назва блока" Що? - відстутній лінк на готель "Назва готелю"
2. Швидше за все цей дефект відтворюється на всіх девайсах

**Comment by k335x** [comment]
@DmytroMarkulych виправив, дякую

**Comment by DmytroMarkulych** [comment]
@k335x зверніть увагу на приклад для оформлення summary в пункті 1

**Comment by k335x** [comment]
@DmytroMarkulych виправив, дякую

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
@scholokov passed
