### ISSUE TITLE
20180428_0501_beregovo # 162 - Название видео в блоке Дорога: Львів – Берегове не соответствует языку страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#305]
**Steps to reproduce:**

1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. В блоке Дорога: Львів – Берегове обратить внимание на название видео

**Actual result:**
Название видео в блоке Дорога: Львів – Берегове **не соответствует** языку страны - 2018.04.28 **Киев - Берегово 2**

**Expected result:**
Название видео в блоке Дорога: Львів – Берегове **соответствует** языку страны - 2018.04.28 **Київ - Берегове 2**

![image](https://user-images.githubusercontent.com/86321831/144758476-85e93398-b81d-44b2-b42b-9a40c696e89c.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
not fixed

![image](https://user-images.githubusercontent.com/86321831/145689399-82c1e2ca-0cf4-4457-afa6-a959abff823e.png)

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
