### ISSUE TITLE
20150502_06_hungary/ No time period is specified in the preview

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3051]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview "Nyírbátor – Debrecen – Polyana"

Actual result:
No time period is specified in the preview

Expected result:
The preview shows the time period

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1436" alt="Screenshot 2023-01-23 at 17 20 43" src="https://user-images.githubusercontent.com/89859006/214079089-894b94ad-333e-4fe4-b8be-40db56afe3ce.png">

<img width="928" alt="Screenshot 2023-01-23 at 17 22 27" src="https://user-images.githubusercontent.com/89859006/214079147-4cbf0ac5-b885-45e7-8b87-9ca2db590d44.png">

**Comment by k335x** [comment]
@DmytroMarkulych виправив, дякую

**Comment by DmytroMarkulych** [comment]
@k335x 
1. В кроках для відтворення вказуємо в наказовій формі. 
Приклад: Клікнути на кнопку..
2. Швидше за все що цей дефект відтворюється на всіх девайсах

**Comment by k335x** [comment]
@DmytroMarkulych  виправив, дякую

**Comment by k335x** [comment]
passed
