### ISSUE TITLE
20150530_kiev_aviation_museum/ Name of waypoint in the map's legend is in russian language

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3052]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20150530_kiev_aviation_museum/
2. Pay attention to the text of the name of the waypoint "Музей Авиации" of the Legend Map block.

**Actual result:**
Name of the waypoint "Музей Авиации" 
**Expected result:**
Name of the waypoint "Музей Авіації"

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/214304838-ab0121ee-849b-4336-83ed-86f24f023825.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
[#2993](https://github.com/scholokov/long-travel-2/issues/2993)

**Comment by tatianasheremet** [comment]
@GNatala 
Hi! Please leave here any comment regarding the current status of the issue.
Still in progress/not actual/ any other.
If no comment is added, the issue will be moved to the "To do" list.

Thank you!

**Comment by GNatala** [comment]
passed
