### ISSUE TITLE
20150530_kiev_aviation_museum/ Extra element "preview" in the map's legend 

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3053]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20150530_kiev_aviation_museum/
2. Pay attention to the text after preview foto in the Legend Map block.

**Actual result:**
The extra element "preview" is in the map's legend
**Expected result:**
The extra element "preview" does not appear in the map's legend

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/214365067-5529a1af-9476-442b-aa6d-597e95186a8b.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed

**Comment by GNatala** [comment]
[#2993](https://github.com/scholokov/long-travel-2/issues/2993)
