### ISSUE TITLE
20150502_06_hungary/ The route is not specified in the "02.05.2015" preview block

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3054]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "05.02.2015"

Actual Result:
The route is not specified in the "02.05.2015" preview block

Expected result:
The route is indicated in the "02.05.2015" preview block

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1437" alt="Screenshot 2023-01-25 at 03 19 47" src="https://user-images.githubusercontent.com/89859006/214458726-287eef0a-d2fa-4727-9735-1e8fa3f6a91d.png">

<img width="1022" alt="Screenshot 2023-01-25 at 03 20 44" src="https://user-images.githubusercontent.com/89859006/214458740-4091bdb9-4c14-4ebd-9714-9cafac5aef04.png">

**Comment by DmytroMarkulych** [comment]
@k335x 
1. Швидше за все цей дефект відтворюється на всіх девайсах
2. Давайте перефразуємо summary таким чином, щоб воно відповідало на питання Де? Що? Коли?

**Comment by k335x** [comment]
@DmytroMarkulych виправив, дякую

**Comment by DmytroMarkulych** [comment]
@k335x додайте назву блоку в summary

**Comment by k335x** [comment]
@DmytroMarkulych  виправив, дякую

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
@scholokov passed
