### ISSUE TITLE
20150502_06_hungary/ The route is not specified in the preview block "05.06.2015"

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3055]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "06.05.2015"
  
Actual Result:
The route is not specified in the preview block "05.06.2015"

Expected result:
The route is indicated in the preview block "05.06.2015"

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1318" alt="Screenshot 2023-01-25 at 03 29 18" src="https://user-images.githubusercontent.com/89859006/214460051-bb4e5657-b6bd-4fb8-8657-9333f3a54fd9.png">

<img width="1022" alt="Screenshot 2023-01-25 at 03 20 44" src="https://user-images.githubusercontent.com/89859006/214460028-c32c73b7-d48a-4a71-bf0b-a9957f29e386.png">

**Comment by DmytroMarkulych** [comment]
@k335x

Швидше за все цей дефект відтворюється на всіх девайсах
Давайте перефразуємо summary таким чином, щоб воно відповідало на питання Де? Що? Коли?

**Comment by k335x** [comment]
@DmytroMarkulych виправив, дякую

**Comment by DmytroMarkulych** [comment]
@k335x додайте назву блоку в  summary

**Comment by k335x** [comment]
@DmytroMarkulych виправив, дякую

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
@scholokov passed
