### ISSUE TITLE
20150502_06_hungary/ The preview block "Nyírbátor, Hungary" has no hotel name listed

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3056]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "Nyírbátor, Hungary"
 
Actual Result:
The preview block "Nyírbátor, Hungary" has no hotel name listed

Expected result:
The "Nyírbátor, Hungary" preview box has the hotel name listed

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1311" alt="Screenshot 2023-01-25 at 03 38 40" src="https://user-images.githubusercontent.com/89859006/214461119-5e2eec58-e36d-4859-91a6-86be7c05bb75.png">

**Comment by DmytroMarkulych** [comment]
@k335x

Швидше за все цей дефект відтворюється на всіх девайсах
Давайте перефразуємо summary таким чином, щоб воно відповідало на питання Де? Що? Коли?

**Comment by k335x** [comment]
@DmytroMarkulych  виправив, дякую

**Comment by DmytroMarkulych** [comment]
@k335x давайте додамо деталей в бег репорт, щоб зробити його більш унікальним

**Comment by k335x** [comment]
@DmytroMarkulych змінив Summary, Results, дякую

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
@scholokov passed
