### ISSUE TITLE
20150502_06_hungary/ The country's name is not written in the language of the country

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3057]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "Украина, Венгрия"
  
Actual Result:
The country's name is not written in the language of the country

Expected result:
The country's name is written in the language of the country

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1308" alt="Screenshot 2023-01-25 at 03 47 28" src="https://user-images.githubusercontent.com/89859006/214462454-84e3f5df-930c-4082-9abb-1800f0a10545.png">

<img width="1313" alt="Screenshot 2023-01-25 at 03 48 13" src="https://user-images.githubusercontent.com/89859006/214462495-9bb85660-a812-47d2-b9db-5b20c10420e4.png">

**Comment by DmytroMarkulych** [comment]
@k335x

Швидше за все цей дефект відтворюється на всіх девайсах

**Comment by k335x** [comment]
@DmytroMarkulych так, дякую

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
@scholokov passed
