### ISSUE TITLE
20150502_06_hungary/ The preview block "Середне, Украина" has the name of the country written in a different language

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3058]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "Середне, Украина"
 
Actual Result:
The preview block "Середне, Украина" has the name of the country written in a different language

Expected result:
The preview block "Середне, Украина" has the name of the country written in the language of the country

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1310" alt="Screenshot 2023-01-25 at 03 54 31" src="https://user-images.githubusercontent.com/89859006/214463229-4c6569bc-b969-4b70-8e73-461992137dd0.png">

<img width="1307" alt="Screenshot 2023-01-25 at 03 55 09" src="https://user-images.githubusercontent.com/89859006/214463240-34b57b55-f08d-428e-9f16-2fddfc0004cf.png">

**Comment by DmytroMarkulych** [comment]
@k335x

Швидше за все цей дефект відтворюється на всіх девайсах. І додамо тег компонент

**Comment by k335x** [comment]
@DmytroMarkulych баг відтворюється на всіх девайсах, дякую

**Comment by DmytroMarkulych** [comment]
@k335x давайте додамо деталей в бег репорт, щоб зробити його більш унікальним

**Comment by k335x** [comment]
@DmytroMarkulych змінив Summary, Results, дякую

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
@scholokov passed
