### ISSUE TITLE
20150502_06_hungary/  The name of the hotel is not in the language of the country

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3059]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "Отель Оазис Карпат"

Actual Result:
The name of the hotel is not in the language of the country

Expected result:
The name of the hotel is indicated in the language of the country

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1310" alt="Screenshot 2023-01-25 at 04 08 40" src="https://user-images.githubusercontent.com/89859006/214464816-4e7c4333-50ec-4806-98df-ab56311b925f.png">

**Comment by DmytroMarkulych** [comment]
@k335x

Швидше за все цей дефект відтворюється на всіх девайсах

**Comment by k335x** [comment]
@DmytroMarkulych баг відтворюється на всіх девайсах, дякую

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
passed
