### ISSUE TITLE
20180428_0501_beregovo # 162 -Размер символов промежуточной точки Отель "Ламберт" не соответствует требованиям

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#306]
**Steps to reproduce:**

1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на размер символов промежуточной точки Отель "Ламберт"

**Actual result:**
Размер символов промежуточной точки Отель "Ламберт" - **Н1**

**Expected result:**
Размер символов промежуточной точки Отель "Ламберт" - **Н2**

![image](https://user-images.githubusercontent.com/86321831/144758950-afed87cf-47f4-4b3d-8047-3b9edaafba05.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
