### ISSUE TITLE
20150502_06_hungary/ The preview shadow does not match the site layout

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3060]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "Nyírbátor – Debrecen – Поляна"
  
Actual Result:
The preview shadow does not match the site layout

Expected result:
The shadow of the preview matches the layout of the site

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1313" alt="Screenshot 2023-01-25 at 04 17 26" src="https://user-images.githubusercontent.com/89859006/214465837-e4de4aac-2346-4f74-8e8c-dfead7ac089e.png">

<img width="682" alt="Screenshot 2023-01-25 at 04 17 17" src="https://user-images.githubusercontent.com/89859006/214465846-77c11176-2aca-4939-83c4-e4d5fda44ef8.png">

**Comment by DmytroMarkulych** [comment]
@k335x

Швидше за все цей дефект відтворюється на всіх девайсах

**Comment by k335x** [comment]
@DmytroMarkulych так, дякую

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
@scholokov  passed
