### ISSUE TITLE
20150502_06_hungary/ In the "Nyírbátor – Debrecen – Поляна" preview block, the trip date is not specified

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3061]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "Nyírbátor – Debrecen – Поляна"
  
Actual Result:
In the "Nyírbátor – Debrecen – Поляна" preview block, the trip date is not specified

Expected result:
In the "Nyírbátor – Debrecen – Поляна" preview block, the date of the trip is indicated

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1305" alt="Screenshot 2023-01-25 at 04 23 37" src="https://user-images.githubusercontent.com/89859006/214466676-383fc826-a8d6-4235-a30e-456936c63f2d.png">

<img width="818" alt="Screenshot 2023-01-25 at 04 24 15" src="https://user-images.githubusercontent.com/89859006/214466685-8ea8070e-b759-4847-94ce-c39185a5238d.png">

**Comment by DmytroMarkulych** [comment]
@k335x

Швидше за все цей дефект відтворюється на всіх девайсах

**Comment by k335x** [comment]
@DmytroMarkulych баг відтворюється на всіх девайсах, дякую

**Comment by DmytroMarkulych** [comment]
@k335x давайте додамо деталей в бег репорт, щоб зробити його більш унікальним

**Comment by k335x** [comment]
@DmytroMarkulych змінив Summary, Results, дякую

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
@scholokov passed
