### ISSUE TITLE
20150502_06_hungary/ The preview does not match the layout of the site

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3062]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "Украина, Венгрия"
  
Actual Result:
The preview does not match the layout of the site

Expected result:
The preview matches the layout of the site

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1310" alt="Screenshot 2023-01-25 at 04 32 09" src="https://user-images.githubusercontent.com/89859006/214467723-978feb9f-27a6-46a3-a241-a7e7e96f85e2.png">

<img width="815" alt="Screenshot 2023-01-25 at 04 32 50" src="https://user-images.githubusercontent.com/89859006/214467736-ff692d7b-838b-4d86-847b-3676df48697a.png">

**Comment by DmytroMarkulych** [comment]
@k335x

Швидше за все цей дефект відтворюється на всіх девайсах

**Comment by k335x** [comment]
@DmytroMarkulych так, дякую

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
@scholokov passed
