### ISSUE TITLE
20150502_06_hungary/ In the preview block, the date format is not the same as the site layout

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3063]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "02-06.05.2015"
 
Actual Result:
The date format does not match the site layout

Expected result:
The date format matches the site layout

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1315" alt="Screenshot 2023-01-25 at 04 37 53" src="https://user-images.githubusercontent.com/89859006/214468453-05afcd33-fbaa-422f-952d-c32376f771fc.png">

<img width="814" alt="Screenshot 2023-01-25 at 04 39 04" src="https://user-images.githubusercontent.com/89859006/214468473-9170b472-3e2c-4e22-b043-6e39c2c43647.png">

**Comment by DmytroMarkulych** [comment]
@k335x

Швидше за все цей дефект відтворюється на всіх девайсах
Давайте перефразуємо summary таким чином, щоб воно відповідало на питання Де? Що? Коли?

**Comment by k335x** [comment]
@DmytroMarkulych баг відтворюється на всіх девайсах, виправив Summaru, дякую

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
@scholokov passed
