### ISSUE TITLE
20150502_06_hungary/ The design of the "05.02.2015" preview block does not match the site layout

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3064]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "02.05.2015"

Actual Result:
The design of the "05.02.2015" preview block does not match the site layout

Expected result:
The design of the "05.02.2015" preview block matches the site layout

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1307" alt="Screenshot 2023-01-25 at 04 46 22" src="https://user-images.githubusercontent.com/89859006/214469399-c6f7dfa1-bede-4238-a4f0-bdc652eb5c22.png">

<img width="830" alt="Screenshot 2023-01-25 at 04 47 43" src="https://user-images.githubusercontent.com/89859006/214469405-9a2bfcd8-02ac-44fd-ba1b-326fcc982eee.png">

**Comment by DmytroMarkulych** [comment]
@k335x

Швидше за все цей дефект відтворюється на всіх девайсах
Давайте перефразуємо summary таким чином, щоб воно відповідало на питання Де? Що? Коли?

**Comment by k335x** [comment]
@DmytroMarkulych баг відтворюється на всіх девайсах, виправив Summary, дякую

**Comment by DmytroMarkulych** [comment]
@k335x давайте додамо деталей в бег репорт, щоб зробити його більш унікальним

**Comment by k335x** [comment]
@DmytroMarkulych  змінив Summary, Results, дякую

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
passed
