### ISSUE TITLE
20150502_06_hungary/ The design of the "Nyírbátor, Hungary" preview block does not match the site layout

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3065]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "Nyírbátor, Hungary"

Actual Result:
The design of the "Nyírbátor, Hungary" preview block does not match the site layout

Expected result:
The design of the "Nyírbátor, Hungary" preview block matches the site layout

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1313" alt="Screenshot 2023-01-25 at 04 49 44" src="https://user-images.githubusercontent.com/89859006/214469858-f6a25b16-e55c-42e8-ad2a-f0b8c9923b16.png">

<img width="660" alt="Screenshot 2023-01-25 at 04 51 41" src="https://user-images.githubusercontent.com/89859006/214469874-e139a3d3-dcf2-4db6-b178-24135e0100d8.png">

**Comment by DmytroMarkulych** [comment]
@k335x

Швидше за все цей дефект відтворюється на всіх девайсах
Давайте перефразуємо summary таким чином, щоб воно відповідало на питання Де? Що? Коли?

**Comment by k335x** [comment]
@DmytroMarkulych баг відтворюється на всіх девайсах, виправив Summaru, дякую

**Comment by DmytroMarkulych** [comment]
@k335x давайте додамо деталей в бег репорт, щоб зробити його більш унікальним

**Comment by DmytroMarkulych** [comment]
@k335x давайте додамо деталей в бег репорт, щоб зробити його більш унікальним

**Comment by k335x** [comment]
@DmytroMarkulych  змінив Summary, Results, дякую

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
passed
