### ISSUE TITLE
20150502_06_hungary/ The block preview "Hungary" is not the same as the layout of the site

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3067]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "Hungary"

Actual Result:
The preview does not match the layout of the site

Expected result:
The preview matches the layout of the site

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1309" alt="Screenshot 2023-01-25 at 04 59 45" src="https://user-images.githubusercontent.com/89859006/214470847-33fec10f-3384-4789-836b-887455f492fb.png">

<img width="660" alt="Screenshot 2023-01-25 at 05 00 14" src="https://user-images.githubusercontent.com/89859006/214470867-afcd6a48-799c-4d5e-808d-2456fc63e075.png">

**Comment by DmytroMarkulych** [comment]
@k335x

Швидше за все цей дефект відтворюється на всіх девайсах
Давайте перефразуємо summary таким чином, щоб воно відповідало на питання Де? Що? Коли? додаючи назву блоків в summary

**Comment by k335x** [comment]
@DmytroMarkulych баг відтворюється на всіх девайсах, виправив Summary, дякую

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
passed
