### ISSUE TITLE
20150502_06_hungary/ In the preview block "Hungary" is not the name of the park

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3068]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "Hungary"

Actual Result:
The name of the park in the preview is not reproduced

Expected result:
Reproduced the name of the park in the preview

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1309" alt="Screenshot 2023-01-25 at 05 04 39" src="https://user-images.githubusercontent.com/89859006/214471521-2f5bf028-0b4e-41e0-80e1-72295417d67b.png">

**Comment by DmytroMarkulych** [comment]
@k335x

Швидше за все цей дефект відтворюється на всіх девайсах
Давайте перефразуємо summary таким чином, щоб воно відповідало на питання Де? Що? Коли? додаючи назву блоків в summary

**Comment by k335x** [comment]
@DmytroMarkulych баг відтворюється на всіх девайсах, виправив Summary, дякую

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
passed
