### ISSUE TITLE
20150502_06_hungary/ The design of the preview block "Debrecen, Hungary" is not the same as the layout of the site

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3069]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "Debrecen, Hungary"

Actual Result:
The design of the preview block "Debrecen, Hungary" is not the same as the layout of the site

Expected result:
The design of the preview block "Debrecen, Hungary" is the same as the layout of the site

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1303" alt="Screenshot 2023-01-25 at 05 10 02" src="https://user-images.githubusercontent.com/89859006/214471887-e0379f99-4749-4418-b09a-6c5ad579fb62.png">

<img width="706" alt="Screenshot 2023-01-25 at 05 10 45" src="https://user-images.githubusercontent.com/89859006/214471898-013d17f3-548a-4306-88ba-4dc6ce25da62.png">

**Comment by DmytroMarkulych** [comment]
@k335x

Швидше за все цей дефект відтворюється на всіх девайсах
Давайте перефразуємо summary таким чином, щоб воно відповідало на питання Де? Що? Коли? додаючи назву блоків в summary

**Comment by k335x** [comment]
@DmytroMarkulych  баг відтворюється на всіх девайсах, виправив Summary, дякую

**Comment by DmytroMarkulych** [comment]
@k335x давайте додамо деталей в бег репорт, щоб зробити його більш унікальним

**Comment by k335x** [comment]
@DmytroMarkulych змінив Summary, Results, дякую

**Comment by k335x** [comment]
passed
