### ISSUE TITLE
20180428_0501_beregovo # 162 - Название города и страны промежуточной точки Отель "Ламберт" не соответствует языку страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#307]
**Steps to reproduce:**

1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на название города и страны промежуточной точки Отель "Ламберт"

**Actual result:**
Название города и страны промежуточной точки Отель "Ламберт" **не соответствует** языку страны - **Берегово, Украина**

**Expected result:**
Название города и страны промежуточной точки Отель "Ламберт" **соответствует** языку страны - **Берегове, Україна**

![image](https://user-images.githubusercontent.com/86321831/144761250-31bbc6a9-b700-4774-9e1b-c34c9d6e89b7.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
