### ISSUE TITLE
20150502_06_hungary/ The name of the zoo is missing in the "Debrecen, Hungary" preview block

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3070]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "Debrecen, Hungary"

Actual Result:
The name of the zoo in the preview is not reproduced

Expected result:
Reproduced the name of the zoo in the preview

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1299" alt="Screenshot 2023-01-25 at 05 15 21" src="https://user-images.githubusercontent.com/89859006/214472321-8bf5836b-a388-46e9-a545-2d39d910c49d.png">

**Comment by DmytroMarkulych** [comment]
@k335x

Швидше за все цей дефект відтворюється на всіх девайсах
Давайте перефразуємо summary таким чином, щоб воно відповідало на питання Де? Що? Коли? додаючи назву блоків в summary

**Comment by k335x** [comment]
@DmytroMarkulych баг відтворюється на всіх девайсах, виправив Summary, дякую

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
passed
