### ISSUE TITLE
20150502_06_hungary/ The design of the "Середне, Украина" preview block does not match the layout of the site

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3071]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "Середне, Украина"

Actual Result:
The design of the "Середне, Украина" preview block does not match the layout of the site

Expected result:
The design of the "Середне, Украина" preview block matches the layout of the site

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1304" alt="Screenshot 2023-01-25 at 05 18 10" src="https://user-images.githubusercontent.com/89859006/214472759-392ffc2d-4120-4ced-a71b-ef4e9977d461.png">

<img width="756" alt="Screenshot 2023-01-25 at 05 18 53" src="https://user-images.githubusercontent.com/89859006/214472775-c2a2663a-9a67-440e-81f2-d71d2b475cef.png">

**Comment by DmytroMarkulych** [comment]
@k335x

Швидше за все цей дефект відтворюється на всіх девайсах
Давайте перефразуємо summary таким чином, щоб воно відповідало на питання Де? Що? Коли? додаючи назву блоків в summary

**Comment by k335x** [comment]
@DmytroMarkulych баг відтворюється на всіх девайсах, виправив Summaru, дякую

**Comment by DmytroMarkulych** [comment]
@k335x давайте додамо деталей в бег репорт, щоб зробити його більш унікальним

**Comment by k335x** [comment]
@DmytroMarkulych змінив Summary, Results, дякую

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
passed
