### ISSUE TITLE
20150502_06_hungary/ The style of the preview block "Отель Оазис Карпат" is not the same as the layout of the site

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3072]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "Отель Оазис Карпат"

Actual Result:
The style of the preview block "Отель Оазис Карпат" is not the same as the layout of the site

Expected result:
The style of the "Отель Оазис Карпат" preview block matches the layout of the site.

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1305" alt="Screenshot 2023-01-25 at 05 21 36" src="https://user-images.githubusercontent.com/89859006/214473098-a8f64c92-1ed4-40fb-8866-e2cfcdf36ebb.png">

<img width="700" alt="Screenshot 2023-01-25 at 05 22 06" src="https://user-images.githubusercontent.com/89859006/214473108-b7a8bcc1-f1a9-4166-a9fa-fe45ec9bf12f.png">

**Comment by DmytroMarkulych** [comment]
@k335x

Швидше за все цей дефект відтворюється на всіх девайсах
Давайте перефразуємо summary таким чином, щоб воно відповідало на питання Де? Що? Коли? додаючи назву блоків в summary

**Comment by k335x** [comment]
@DmytroMarkulych баг відтворюється на всіх девайсах, виправив Summaru, дякую

**Comment by DmytroMarkulych** [comment]
@k335x давайте додамо деталей в бег репорт, щоб зробити його більш унікальним

**Comment by k335x** [comment]
@DmytroMarkulych змінив Results, дякую

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
passed
