### ISSUE TITLE
20150530_kiev_aviation_museum/ Name of preview in the map's legend is in russian language

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3074]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20150530_kiev_aviation_museum/
2. Pay attention to the name of the preview foto in the map's legend.

**Actual result:**
The name of the preview in the map's legend is "Музей Авиации"
**Expected result:**
The name of the preview in the map's legend is "Музей Авіації"

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/214809757-eb8cbac9-7db2-4d02-879a-44a12e575a26.png)

**Comment by DmytroMarkulych** [comment]
@GNatala Давайте ще додамо Type issue

**Comment by GNatala** [comment]
додала

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
[#2993](https://github.com/scholokov/long-travel-2/issues/2993)
