### ISSUE TITLE
20150623_0711_croatia/ no flag of Ukraine in the preview

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3075]
Prerequisites:
Open  https://test.long-travel.live/20150623_0711_croatia/#gallery[photonic-google-album-1]/AE29bME21KcaaVuGqAgKpOQPI-m1AsH-W9Ub9kwoSOokTfTHmtO6MY8ZCGfS_SSNOxGwBBdXoV926uRWf6NV3xljFaMONa5OyQ/
Steps to play:

1. Scrol to the end of the page
2. Please note that there is no flag of Ukrainein the "Дома" previwe

Actual result:  no flag of Ukraine in the preview
Expected result: The flag of Ukraine is in the preview 

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 107.0.5304.122
![Home Ukr](https://user-images.githubusercontent.com/113175298/214840448-5163de2d-85b6-4a78-b65e-01fd3bcb9ffa.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk не забуваємо про атрибути 

![Image](https://user-images.githubusercontent.com/88647733/214900915-d75e6de3-ada3-47c8-9273-cfd7afbfde9f.png)

**Comment by Nadiyk** [comment]
виправила

**Comment by scholokov** [comment]
у вимогах написано, що цей блок не повинен містити флаг
