### ISSUE TITLE
20150502_06_hungary/ In the "Hungary" preview block, the name of the country is not written in the language of the country

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3077]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "Hungary"
 
Actual Result:
In the "Hungary" preview block, the name of the country is not written in the language of the country

Expected result:
In the "Hungary" preview block, the country name is written in the country's language

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1305" alt="Screenshot 2023-01-27 at 17 55 41" src="https://user-images.githubusercontent.com/89859006/215130620-1c32077d-1854-4de0-a7a9-ee104e46de4d.png">

<img width="1294" alt="Screenshot 2023-01-27 at 17 56 24" src="https://user-images.githubusercontent.com/89859006/215130649-c22faccc-d34d-47bf-b815-a1d2ac84361b.png">

**Comment by DmytroMarkulych** [comment]
@k335x давайте додамо деталей в бег репорт, щоб зробити його більш унікальним

**Comment by k335x** [comment]
@DmytroMarkulych виправив, дякую

**Comment by k335x** [comment]
passed
