### ISSUE TITLE
Prepare testing data for Travels page   

### ISSUE THREAD

**Issue by ABatalov** [scholokov/long-travel-2#3079]
We need to create test data to implement Travels page:  
 https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=3131%3A34&t=0mfkKfgP0utp0rkJ-0

**Comment by ABatalov** [comment]
After this task we can star implementation: 
https://github.com/scholokov/long-travel-2/issues/3078

**Comment by scholokov** [comment]
done
