### ISSUE TITLE
20180428_0501_beregovo # 162 - Название видео в блоке Отель "Ламберт" на соответствует языку страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#308]
**Steps to reproduce:**

1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. В блоке Отель "Ламберт" обратить внимание на название видео

**Actual result:**
Название видео в блоке Отель "Ламберт" не соответствует языку страны - 2018.05.01 **Берегово** - Отель Ламберт

**Expected result:**
Название видео в блоке Отель "Ламберт" соответствует языку страны - 2018.05.01 **Берегове** - Отель Ламберт

![image](https://user-images.githubusercontent.com/86321831/144762224-09eb3148-9ff9-427e-8fc7-a7cf485dc050.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
