### ISSUE TITLE
20180428_0501_beregovo # 162 - Название города и страны промежуточной точки Винзавод “Леанка” не соответствует языку страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#309]
**Steps to reproduce:**

1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на название города и страны промежуточной точки Винзавод “Леанка”

**Actual result:**
Название города и страны промежуточной точки Винзавод “Леанка” не соответствует языку страны - **Середне, Украина**

**Expected result:**
Название города и страны промежуточной точки Винзавод “Леанка” соответствует языку страны - **Середнє, Україна**

![image](https://user-images.githubusercontent.com/86321831/144762365-d8ee6377-874a-489d-9c14-f1efe0ac24a8.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
