### ISSUE TITLE
20150502_06_hungary/ In the block that opens the menu on the map "20150502_06_Hungary" the name of the country is not written in the language of the country

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3091]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the map "20150502_06_Hungary"
  
Actual Result:
In the block that opens the menu on the map "20150502_06_Hungary" the name of the country is not written in the language of the country

Expected result:
In the block that opens the menu on the map "20150502_06_Hungary" the name of the country is written in the language of the country

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1294" alt="Screenshot 2023-01-31 at 13 26 37" src="https://user-images.githubusercontent.com/89859006/215747885-09549388-82b9-4315-ac48-19e9f4bbe63e.png">

<img width="948" alt="Screenshot 2023-01-31 at 13 27 15" src="https://user-images.githubusercontent.com/89859006/215747934-4ddce2bc-e2b5-445e-8603-d952705a31be.png">

**Comment by DmytroMarkulych** [comment]
@k335x давайте додамо деталей в бег репорт, щоб зробити його більш унікальним

**Comment by k335x** [comment]
@DmytroMarkulych виправив, дякую

**Comment by scholokov** [comment]
у вимогах прописано формування назви

**Comment by k335x** [comment]
incorrect bug
