### ISSUE TITLE
20150502_06_hungary/ Font 'Open Sans' of the Logo "Long-Travel" in the header does not meet design requirements in Figma

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3092]
Steps to reproduce:

  1. Open: https://www.test.long-travel.live/20150502_06_hungary
  2. Pay attention to the logo "Long-Travel" in the header.
  3. Open DevTools.
  4. Сheck font of the logo "Long-Travel".
 
 Actual result:
Font: 'Open Sans', font-size: 27px

 Expected result:
Font: 'Rubik', font-size: 36px

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1301" alt="Screenshot 2023-01-31 at 13 58 50" src="https://user-images.githubusercontent.com/89859006/215754239-bcb1951e-343a-4195-a89c-e263165dafde.png">

<img width="1303" alt="Screenshot 2023-01-31 at 13 59 22" src="https://user-images.githubusercontent.com/89859006/215754249-b1aa30ba-7da1-47e9-addb-7b1011a92960.png">

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
