### ISSUE TITLE
20150502_06_hungary/ On the page "Nyírbátor – Debrecen – Поляна" "LightBox" opens after opening the page

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3093]
Steps to reproduce:

  1. Open: https://www.test.long-travel.live/20150502_06_hungary

Actual result:
On the page "Nyírbátor – Debrecen – Поляна" "LightBox" opens after opening the page

Expected result:
The "Nyírbátor – Debrecen – Поляна" page opens

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.119 (Official Build) (x86_64)

Attachment:

https://user-images.githubusercontent.com/89859006/215758629-b69f75ca-b1ae-4e80-9faa-7a4e998b9ddd.mp4

**Comment by DmytroMarkulych** [comment]
@k335x давайте сформулюємо summary наступним чином
**Де?** - На сторінці "_Назва сторінки_" **Що?** - відкривається "LightBox" **Коли?** - після відкриття сторінки

**Comment by k335x** [comment]
@DmytroMarkulych  виправив, дякую
