### ISSUE TITLE
20160326_konotop The connection is not confidential.

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3095]
Pre-conditions:
Open  https://www.test.long-travel.live/20160326_konotop 

Steps to reproduce:
1.Pay attention to the URL.

Actual result:
The connection is not confidential.

Expected result:
Page with travel is opened.

Environment:
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

Attachment:
![link](https://user-images.githubusercontent.com/123729744/216274319-c0b6cc40-b7f4-4b51-ac25-ef88e61b24c8.png)

**Comment by DmytroMarkulych** [comment]
@OlhaHutsman він активний але не конфідеційний

**Comment by OlhaHutsman** [comment]
@DmytroMarkulych  Edited
