### ISSUE TITLE
20151226_kiev_fashion_park/ Name of the city "Kyiv" is in english in the 1st Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3096]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20151226_kiev_fashion_park/
2. Scroll down to the 1st Preview block 
3. Pay attention to the name of the city "Kyiv"

**Actual result:**
Name of the city is "Kyiv" 
**Expected result:**
Name of the city is "Київ" 

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment** 
![image](https://user-images.githubusercontent.com/101987790/216396193-0404d95d-ca0f-41f6-b33a-d8bd66a749f7.png)

![image](https://user-images.githubusercontent.com/101987790/216297842-7f997344-3889-47bb-a925-ae84be4b55fb.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed

**Comment by GNatala** [comment]
#3081
