### ISSUE TITLE
20150623_0711_croatia The link opens as dangerouse

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3097]
Prerequisites:
Open https://test.long-travel.live/20150623_0711_croatia
Steps to play:

1. Pay attention to the URL

Actual result:  The link opens as dangerous
Expected result: The link opens without an error

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 107.0.5304.122
![лінк](https://user-images.githubusercontent.com/113175298/216299358-988f0d9f-b0b2-4488-b88b-2dad0baf17ef.jpg)

**Comment by DmytroMarkulych** [comment]
@Nadiyk  він відкривається, але бразузер його детектить як не захищений)

**Comment by Nadiyk** [comment]
corrected it
