### ISSUE TITLE
20160326_konotop Letter "к" is missed in word "конотопсьої" in preview

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3098]
**Pre-conditions:**
Open https://test.long-travel.live/20160326_konotop

**Steps to reproduce:**

1.Scroll down to the bottom of the page.
2.Read the text of preview.
3.Letter "к" is missed in word "конотопсьої".

**Actual result:**

The word is  "конотопсьої".

**Expected result:**
 
The word is  "конотопської".

**Environment:**

Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**

![grammar](https://user-images.githubusercontent.com/123729744/216360877-7d99f2c0-b270-470e-841b-258910d7eb4f.png)

**Comment by scholokov** [comment]
fixed

**Comment by OlhaHutsman** [comment]
@scholokov перевірено
