### ISSUE TITLE
20160326_konotop no flag in preview

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3099]
**Pre-conditions:**
Open https://test.long-travel.live/20160326_konotop

**Steps to reproduce:**
1.Scroll down to the bottom of the page.
2.Find preview.
3.Pay attention that there is no flag of Ukraine in the middle of  the right side of preview.

**Actual result:**
There is no flag of Ukraine in the middle of the right side of preview.

**Expected result:**
There is flag of Ukraine in the middle of  the right side of preview.

**Environment:**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**![no flag](https://user-images.githubusercontent.com/123729744/216363856-fcc467d9-b57b-4953-ae30-af752897c1dd.png)**

**Comment by DmytroMarkulych** [comment]
@OlhaHutsman досить якісно оформлений баг репорт. Так тримати )
Але в останньому кроці для відтворення бажано писати "Pay attention to ...", для того щоб вказувати на місце де  є проблема

**Comment by OlhaHutsman** [comment]
@DmytroMarkulych  Edited.

**Comment by scholokov** [comment]
fixed

**Comment by OlhaHutsman** [comment]
@scholokov  перевірено
