### ISSUE TITLE
 The photo of the preview is not displayed on the home page

### ISSUE THREAD

**Issue by Hranovskyu-Dmutro** [scholokov/long-travel-2#31]
Steps:
1. open site ;
2. pay attention to the travel preview ("Вытачов","Миргород,"Болград – Слънчев Бряг – București – Саврань").

Actual result :
Photo preview is not displayed on the travel homepage:("Вытачов","Миргород,"Болград – Слънчев Бряг – București – Саврань")
Expected result:
Photo previews are displayed on all trips on the home page.

Screenshot: https://skr.sh/s990yJa1BhR?a
Additional Information: 
-Operating System: windows 10, x64
-browser : Google Chrome 91.0.4472.164

**Comment by scholokov** [comment]
fixed

**Comment by Hranovskyu-Dmutro** [comment]
previews of new trips are not displayed on new trips: https://skr.sh/s9FZ6G97r8d?a
