### ISSUE TITLE
20180428_0501_beregovo # 162 - Размер символов даты промежуточной точки Винзавод “Леанка” не соответствует требованиям

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#310]
**Steps to reproduce:**

1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на размер символов даты промежуточной точки Винзавод “Леанка”

**Actual result:**
Размер символов даты промежуточной точки Винзавод “Леанка” - **Н2**

**Expected result:**
Размер символов даты промежуточной точки Винзавод “Леанка” - **Н3**

![image](https://user-images.githubusercontent.com/86321831/144762505-1f29ef13-4055-43aa-8173-b38fd02a9b25.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
