### ISSUE TITLE
20160326_konotop the name of Travel is not matching the ID of Travel

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3100]
**Pre-conditions:**
Open https://test.long-travel.live/20160326_konotop

**Steps to reproduce:**

1.Find preview.
2.Pay attention to the name of travel is Конотопський ДЮСШ and it  is not matching the ID of Travel according the Travels.list in Wiki.

Actual result:
The name of travel is:
Конотопський ДЮСШ

Expected result:
Конопська ДЮСШ (according to the [requirement ](https://github.com/scholokov/long-travel-2/wiki/4.2-Travels.List))
**Environment:**

Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**

![name](https://user-images.githubusercontent.com/123729744/216366413-02c51234-7fe8-465d-867b-32f56cd7c231.png)
![name2](https://user-images.githubusercontent.com/123729744/216366451-db57aad2-0767-47bd-be5f-4e2f6099537a.png)

**Comment by DmytroMarkulych** [comment]
@OlhaHutsman досить якісно оформлений баг репорт. Так тримати )
Але в останньому кроці для відтворення бажано писати "Pay attention to ...", для того щоб вказувати на місце де є проблема

**Comment by OlhaHutsman** [comment]
@DmytroMarkulych  Edited.

**Comment by scholokov** [comment]
Actual result:
The name of travel is not matching the ID of Travel according
the Travels.list in Wiki.

Expected result:
The name of travel is matching the ID of Travel according
the Travels.list in Wiki.

Якщо вам точно відомо, який має бути експект результат, має сенс його писати. цим ви прискорюєте розробку.
можнаписати наприклад у такому форматі:
Actual result:
некоректна назва

Expected result:
коректна назва (звісно такому то документу, за такою то лінкою)

**Comment by OlhaHutsman** [comment]
@scholokov Edired. В попередньому варіанті було додано 2 attachments, де вказано, яка назва повинна бути згідно вимог і, яка є в actual result.

**Comment by scholokov** [comment]
суто технічно - було правильно. але ж наша ціль, не просто зробили "правильно", але і максимально "ефективно", тобто щоб наш баг максимально бистро виправили :)

**Comment by scholokov** [comment]
приклад:

Actual result:
The name of travel is Конотопський ДЮСШ and it is not matching the ID of Travel according
the Travels.list in Wiki.

Expected result:
The name of travel is Конопська ДЮСШ as it is according the Travels.list in Wiki.

суто технічно, все є. але якщо, наприклад, написати у такому форматі:

Actual result:
The name of travel is: 
Конотопський ДЮСШ  

Expected result:
Конопська ДЮСШ (according to the [requirement ](https://github.com/scholokov/long-travel-2/wiki/4.2-Travels.List)

чи не буде навіть перевіряти потім це простіше? :)

**Comment by OlhaHutsman** [comment]
@scholokov  Ок, зрозуміла. Дякую. Edited.

**Comment by scholokov** [comment]
fixed

**Comment by OlhaHutsman** [comment]
Пеевірено
