### ISSUE TITLE
20160326_konotop Grammar mistake -the word is written with a small letter

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3101]
**Pre-conditions:**
Open https://test.long-travel.live/20160326_konotop

**Steps to reproduce:**

1.Scroll down to the bottom of the page.
2.Find  preview.
3.Pay attention to the word  "конотопсьої". It  is written with a small letter **"к"**

**Actual result:**

The word  "конотопсьої" is written with a small letter.

**Expected result:**

The word  "конотопсьої" is written with a capital **"К"**

**Environment:**

Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![конотопської](https://user-images.githubusercontent.com/123729744/216373264-11788dbc-2a43-4245-b7c8-01683ae98adc.png)

**Comment by DmytroMarkulych** [comment]
@OlhaHutsman 
В останньому кроці для відтворення бажано писати "Pay attention to ...", для того щоб вказувати на місце де є проблема

**Comment by OlhaHutsman** [comment]
@DmytroMarkulych Edited

**Comment by scholokov** [comment]
fixed

**Comment by OlhaHutsman** [comment]
@scholokov первірено
