### ISSUE TITLE
20160326_konotop The word "сумської" is written with a small letter "с" in preview

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3102]
**Pre-conditions:**
Open https://test.long-travel.live/20160326_konotop

**Steps to reproduce:**

1.Scroll down to the bottom of the page.
2.Find preview.
3.Pay attention to the word "сумської".It  is written with a small letter "с"

**Actual result:**

The word "сумської" is written with a small letter.

**Expected result:**

The word "сумської" is written with a capital "С"

**Environment:**

Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![сумської](https://user-images.githubusercontent.com/123729744/216374550-3c88d495-6988-4f64-a357-599a9f1da136.png)

**Comment by DmytroMarkulych** [comment]
@OlhaHutsman 
В останньому кроці для відтворення бажано писати "Pay attention to ...", для того щоб вказувати на місце де є проблема

**Comment by OlhaHutsman** [comment]
@DmytroMarkulych Edited.

**Comment by scholokov** [comment]
fixed

**Comment by OlhaHutsman** [comment]
@scholokov перевірено
