### ISSUE TITLE
20151226_kiev_fashion_park/ Name of the Travel in the Preview block "Kyiv Fashion Park" does not match the name of the Travel in 4.2 Travels.List

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3103]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20151226_kiev_fashion_park/
2. Scroll down to the Preview block 
3. Pay attention to the name of the Travel in the Preview block "Kyiv Fashion Park"  

**Actual result:**
Name of the Travel in the Preview block "Kyiv Fashion Park"  
**Expected result:**
Name of the Travel in the Preview block "Парк сучасної скульптури та інсталяції "Kiev Fashion Park""

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment** 
![image](https://user-images.githubusercontent.com/101987790/216398923-d1d168df-9caa-4475-bd3c-6baf0f37c531.png)

![image](https://user-images.githubusercontent.com/101987790/216395646-23428a02-dbb9-4bdd-ab6f-d6715d3da9da.png)

**Comment by scholokov** [comment]
fixed
