### ISSUE TITLE
20151226_kiev_fashion_park/ Photo auto-player shows only the first photo from the gallery

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3104]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20151226_kiev_fashion_park/
2. Scroll down to the 1st photo gallery.
3. Open the first photo.
4. Press ![image](https://user-images.githubusercontent.com/101987790/212685688-9e484f9b-6b43-427f-9116-0263d3e9e7e3.png) auto player button.

**Actual result:**
The auto-player shows only the first photo.
**Expected result:**
The auto-player shows the next photos.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

[2023.02.02-16_03_54.webm](https://user-images.githubusercontent.com/101987790/216401586-86adcea0-08a6-4b01-b27e-4e2caf5f761b.webm)

**Comment by GNatala** [comment]
#3081

**Comment by scholokov** [comment]
please retest
