### ISSUE TITLE
20151031_haisyn_uman/ Missed region "Черкаська область" in the Hotel block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3106]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20151031_haisyn_uman/
2. Scroll down to the Hotel block.
3. Pay attention to the city name "с.Городецьке".

**Actual result:**
City name, region "с.Городецьке"
**Expected result:**
City name, region "с.Городецьке, Черкаська область"

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)
![image](https://user-images.githubusercontent.com/101987790/216416744-22bf745e-2f17-4260-9849-4bf5b7053920.png)
![image](https://user-images.githubusercontent.com/101987790/216415311-ffa892ea-f5c8-447c-a464-13ecf89c4669.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
