### ISSUE TITLE
20161023_chaiky_aerofly/ Spelling mistake in the word "Aeroflay" in the name of waypoint of the Legend Map block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3108]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20161023_chaiky_aerofly/
2. Pay attention to the name of the waypoint of the Legend Map block.

**Actual result:**
The name of the waypoint of the Legend Map block is "Aeroflay"
**Expected result:**
The name of the waypoint of the Legend Map block is "Aerofly"

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/216952309-36b432ce-2b31-40a0-855b-53eb454031f1.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
