### ISSUE TITLE
20180428_0501_beregovo # 162 - Название страны промежуточной точки Ужгород не соответствует языку страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#311]
**Steps to reproduce:**

1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на название страны промежуточной точки Ужгород

**Actual result:**
Название страны промежуточной точки Ужгород не соответствует языку страны - **Украина**

**Expected result:**
Название страны промежуточной точки Ужгород соответствует языку страны - **Україна**

![image](https://user-images.githubusercontent.com/86321831/144762707-ad589566-7f76-4da2-a20a-fc66682b3b4b.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
