### ISSUE TITLE
20161023_chaiky_aerofly/ Extra element "Chaiky" in the map's legend

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3110]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20161023_chaiky_aerofly/
2. Pay attention to the text after preview foto in the Legend Map block.

**Actual result:**
The extra element "Chaiky" is in the map's legend
**Expected result:**
The extra element "Chaiky" does not appear in the map's legend

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/217046618-c0460f5f-b988-4e75-9b3d-dcf1f080e47a.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
