### ISSUE TITLE
20161023_chaiky_aerofly/ Name "Аэротруба" of the 1st Preview block is in russian language

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3112]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20161023_chaiky_aerofly/
2. Scroll to the 1st Preview block.
3. Pay attention to the name of the block.

**Actual result:**
Name of the 1st Preview block is "Аэротруба".
**Expected result:**
Name of the 1st Preview block is "Аеротруба".

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment** 
![image](https://user-images.githubusercontent.com/101987790/217056933-fcb84fa0-ee22-4b79-85a6-e871d357e85d.png)

**Comment by GNatala** [comment]
#3088

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
