### ISSUE TITLE
20161023_chaiky_aerofly/ Name of the city, region, country "Чайки, Киевская область, Украина" in the 1st Preview block is in russian language

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3113]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20161023_chaiky_aerofly/
2. Scroll down to the 1st Preview block 
3. Pay attention to the name of the city, region and country "Чайки, Киевская область, Украина"

**Actual result:**
Name of the city, region and country is "Чайки, Киевская область, Украина"
**Expected result:**
Name of the city, region and country is "с.Чайки, Київська область, Україна" 

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment** 
![image](https://user-images.githubusercontent.com/101987790/217059554-3c085362-b88a-40ae-8374-0d24c34adf0a.png)

![image](https://user-images.githubusercontent.com/101987790/216297842-7f997344-3889-47bb-a925-ae84be4b55fb.png)

**Comment by GNatala** [comment]
#3088

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
