### ISSUE TITLE
20161023_chaiky_aerofly/ Mis font 'Open Sans' of the Logo "Long-Travel" in the header 

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3114]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20161023_chaiky_aerofly/
2. Pay attention to the logo "Long-Travel" in the header.
3. Open DevTools.
4. Сheck font of the logo "Long-Travel".

**Actual result:**
Font: 'Open Sans', font-size: 27px
**Expected result:**
Font: 'Rubik', font-size: 36px

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://user-images.githubusercontent.com/101987790/217063353-60509959-bc54-470c-a70e-d4d322967bab.png)

![image](https://user-images.githubusercontent.com/101987790/212555738-1eb9e41f-c884-4b80-85c9-5d75212b34b8.png)

**Comment by GNatala** [comment]
#3088

**Comment by scholokov** [comment]
fixed
