### ISSUE TITLE
20160326_konotop No preview photo in the legend of the map

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3115]
**Pre-conditions:**
Open https://test.long-travel.live/20160326_konotop

**Steps to reproduce:**

1.Scroll down to the map of travel.
2.Find Legend in the right side of the page.
2.Pay attention to the absence of preview photo in the legend of the map. 

**Actual result:**
No preview photo in the legend of the map.

**Expected result:**
Preview photo is in the legend of the Map .

**Additional information :**
https://github.com/scholokov/long-travel-2/wiki/2.6-Travel.Map

**Environment:**

Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![no photo re](https://user-images.githubusercontent.com/123729744/217475523-218c15db-260d-4c0d-aefd-414e0c833bfe.png)
![photo legend re](https://user-images.githubusercontent.com/123729744/217475549-8f125b0a-270f-4173-9683-be109beb90f1.png)

**Comment by DmytroMarkulych** [comment]
@OlhaHutsman перефразуйте summary, actual, expected results таким чином, щою уникнути фразу "there is"/

**Comment by OlhaHutsman** [comment]
@DmytroMarkulych  Edited

**Comment by scholokov** [comment]
fixed

**Comment by OlhaHutsman** [comment]
@scholokov Перевірено
