### ISSUE TITLE
20160326_konotop The real size of flag in preview doesn't match the size in Figma

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3116]
**Pre-conditions:**
Open https://test.long-travel.live/20160326_konotop

**Steps to reproduce:**

1.Find preview.
2.Pay attention to the size of flag in the right side of preview.

**Actual result:**

The size of flag in preview is 26 × 18 px

**Expected result:**

The size of flag in preview is 26 × 17.33 px 

**Additional information:**  
according to the https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1201%3A2459&t=wcP9iMpIsNQu9DCX-0

**Environment:**

Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![size flag 1](https://user-images.githubusercontent.com/123729744/217480535-ccc69a2e-b007-43d3-815a-969cef54679c.png)
![flag size](https://user-images.githubusercontent.com/123729744/217480567-f49a511a-e67d-42fd-8416-5e5c19ba1cb0.png)

**Comment by DmytroMarkulych** [comment]
@OlhaHutsman в expected result можна винести лінку на фігму як окремий пункт типу Додаткова інформація

**Comment by OlhaHutsman** [comment]
@DmytroMarkulych  Edited

**Comment by scholokov** [comment]
the issue in the requirements. it is already fixed in Figma. please retest

**Comment by OlhaHutsman** [comment]
@scholokov  Retested.The size of flag in preview is 26 × 18 px according Figma.
