### ISSUE TITLE
20150502_06_hungary/ The preview block "Киев Украина – Nyírbátor Hungary" has the name of the country/city written in a different language

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3117]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "Киев Украина – Nyírbátor Hungary"
  
Actual Result:
The preview block "Киев Украина – Nyírbátor Hungary" has the name of the country/city written in a different language

Expected result:
In the preview block "Киев Украина – Nyírbátor Hungary" the name of the country/city is written in the language

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1310" alt="Screenshot 2023-02-08 at 12 44 14" src="https://user-images.githubusercontent.com/89859006/217508497-eb9d27bf-4fa3-4c19-93b5-8ed4b5ec3f50.png">
<img width="1307" alt="214463240-34b57b55-f08d-428e-9f16-2fddfc0004cf" src="https://user-images.githubusercontent.com/89859006/217508598-f01cab19-8275-42a2-b25a-b688af069bf7.png">

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
passed
