### ISSUE TITLE
20150502_06_hungary/ The preview block "Отель Оазис Карпат" has the name of the hotel written in a different language

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3118]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "Отель Оазис Карпат"

Actual Result:
The preview block "Отель Оазис Карпат" has the name of the hotel written in a different language

Expected result:
The preview block "Отель Оазис Карпат" has the name of the country written in the language of the country

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1312" alt="Screenshot 2023-02-08 at 12 53 54" src="https://user-images.githubusercontent.com/89859006/217510786-a1a3241c-3eb6-4ca4-bb53-5b3cabc88801.png">
<img width="1307" alt="214463240-34b57b55-f08d-428e-9f16-2fddfc0004cf" src="https://user-images.githubusercontent.com/89859006/217510792-c30f1fb4-a0ae-4de0-b39c-df7225afe6e9.png">

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
passed
