### ISSUE TITLE
20150502_06_hungary/ The preview block "Поляна, Украина" has the name of the country written in a different language

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3119]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "Поляна, Украина"

Actual Result:
The preview block "Поляна, Украина" has the name of the country written in a different language

Expected result:
The preview block "Поляна, Украина" has the name of the country written in the language of the country

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1312" alt="Screenshot 2023-02-08 at 13 08 37" src="https://user-images.githubusercontent.com/89859006/217513363-0a239991-0a70-4a97-a7a6-599354b7a0e1.png">
<img width="1307" alt="214463240-34b57b55-f08d-428e-9f16-2fddfc0004cf" src="https://user-images.githubusercontent.com/89859006/217512569-6d004260-cb75-43b6-9fed-a48821a29ba0.png">

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
passed
