### ISSUE TITLE
20180428_0501_beregovo # 162 - Размер символов даты промежуточной точки Ужгород не соответствует требованиям

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#312]
**Steps to reproduce:**

1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на размер символов даты промежуточной точки Ужгород

**Actual result:**
Размер символов даты промежуточной точки Ужгород - **Н2**

**Expected result:**
Размер символов даты промежуточной точки Ужгород - **Н3**

![image](https://user-images.githubusercontent.com/86321831/144762929-b7ef9e8a-5bc4-4f75-8264-83b12c44b39a.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
not fixed
![image](https://user-images.githubusercontent.com/86321831/144931069-107091d4-596e-42e8-9b84-a00f1469ecac.png)

**Comment by scholokov** [comment]
fixed

**Comment by scholokov** [comment]
если баг возвращаем, то и статус стоит менять :)

**Comment by scholokov** [comment]
please retest

**Comment by yanadiya** [comment]
проверено
