### ISSUE TITLE
20150502_06_hungary/ The preview block "Поляна Украина – Киев Украина" has the name of the country/city written in a different language

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3120]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "Поляна Украина – Киев Украина"

Actual Result:
The preview block "Поляна Украина – Киев Украина" has the name of the country/city written in a different language

Expected result:
The preview block "Поляна Украина – Киев Украина" has the name of the country/city written in a language country

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1311" alt="Screenshot 2023-02-08 at 13 11 01" src="https://user-images.githubusercontent.com/89859006/217514219-285e9367-058b-43d8-9797-7c67fde0f3eb.png">
<img width="1307" alt="214463240-34b57b55-f08d-428e-9f16-2fddfc0004cf" src="https://user-images.githubusercontent.com/89859006/217514234-f3eefa52-6e17-4026-8c43-43de305de828.png">

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
passed
