### ISSUE TITLE
20150502_06_hungary/ The travel page has an extra "Debrecen, Hungary" preview block with no styling

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3121]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "Debrecen, Hungary" no styling

Actual Result:
The travel page has an extra "Debrecen, Hungary" preview block with no styling

Expected result:
The travel page has one preview block "Debrecen, Hungary"

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1306" alt="Screenshot 2023-02-08 at 13 27 14" src="https://user-images.githubusercontent.com/89859006/217517202-4ed6f32a-5fba-4126-b1cc-52dede067d13.png">

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
passed
