### ISSUE TITLE
20150502_06_hungary/ The travel page has an extra "Середнє, Україна" preview block with no styling

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3122]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "Середнє, Україна" no styling

Actual Result:
The travel page has an extra "Середнє, Україна" preview block with no styling

Expected result:
The travel page has one preview block "Середнє, Україна"

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1313" alt="Screenshot 2023-02-08 at 13 31 36" src="https://user-images.githubusercontent.com/89859006/217518149-6be692b0-a3e3-4e7c-8494-51fd153aa61d.png">

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
passed
