### ISSUE TITLE
20150502_06_hungary/ The travel page has an extra "Поляна, Україна" preview block with no styling

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3123]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "Поляна, Україна" no styling

Actual Result:
The travel page has an extra "Поляна, Україна" preview block with no styling

Expected result:
The travel page has one preview block "Поляна, Україна"

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1312" alt="Screenshot 2023-02-08 at 13 33 38" src="https://user-images.githubusercontent.com/89859006/217518721-675220a6-73da-4e93-b9ef-7a0f132f73fc.png">

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
passed
