### ISSUE TITLE
20150502_06_hungary/ The travel page has an extra "06.05.2015" preview block with no styling

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3124]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "06.05.2015" no styling

Actual Result:
The travel page has an extra "06.05.2015" preview block with no styling

Expected result:
The travel page has one preview block "06.05.2015"

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1316" alt="Screenshot 2023-02-08 at 13 36 49" src="https://user-images.githubusercontent.com/89859006/217519414-a84559d9-7aa6-4cfd-a0db-1227b96b72e2.png">

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
passed
