### ISSUE TITLE
20150502_06_hungary/ Extra "03.05.2015" preview block with no styles on travel page

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3125]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the preview block "03.05.2015" no styling

Actual Result:
The travel page has an extra "03.05.2015" preview block with no styling

Expected result:
The travel page has one preview block "03.05.2015"

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1314" alt="Screenshot 2023-02-08 at 13 40 25" src="https://user-images.githubusercontent.com/89859006/217520454-ab798fc6-8f68-4cdb-a972-51e2ac6befcd.png">

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
passed
