### ISSUE TITLE
In the technical documentation on the page "2.6 Travel.Map" in the item "2.8 Должна бути присутнім превью фото" the photo must be under each item in legedny or not

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3126]
Steps to reproduce:

  1. Open: https://github.com/scholokov/long-travel-2
  2. Click on the tab "Wiki"
  3. Click on the page "2.6 Travel.Map"
  4. Pay attention per point "2.8 Должна бути присутнім превью фото"

Actual Result:
In the technical documentation on the page "2.6 Travel.Map" in the item "2.8 Должна бути присутнім превью фото" the photo must be under each item in legend or not

Expected result:
In the technical documentation on the page "2.6 Travel.Map" in the item "2.8 Должна бути присутнім превью фото" it is specifically stated that there must be a photo under each item in the legend

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1320" alt="Screenshot 2023-02-08 at 14 03 55" src="https://user-images.githubusercontent.com/89859006/217524722-1993ddf9-dd98-4e3c-9da5-82a87461a506.png">

**Comment by scholokov** [comment]
оновлено
https://github.com/scholokov/long-travel-2/wiki/4.4-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%9C%D0%B0%D0%BF%D0%B0

**Comment by GNatala** [comment]
passed
