### ISSUE TITLE
20180428_0501_beregovo # 162 -Размер символов промежуточной точки Кафе Chilli-Pizza не соответствует требованиям

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#313]
**Steps to reproduce:**

1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на размер символов промежуточной точки Кафе Chilli-Pizza

**Actual result:**
Размер символов промежуточной точки Кафе Chilli-Pizza - **15px**

**Expected result:**
Размер символов промежуточной точки Кафе Chilli-Pizza - **Н2**

![image](https://user-images.githubusercontent.com/86321831/144763698-ca6f2d0d-e61c-481f-a4d7-6f3d4864a0d4.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
