### ISSUE TITLE
/20150623_0711_croatia/  The date format is incorrect 23.06.-11

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3130]
Prerequisites:
Open https://test.long-travel.live/20150623_0711_croatia/
Steps to reproduce:

1.  Pay attention to the date form in the preview

Actual result: 23.06-11
Expected result: 23.06.2015

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 107.0.5304.122

![-](https://user-images.githubusercontent.com/113175298/219000323-5a73beb5-257b-46c4-81ff-c0714727872e.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk додайте будь ласка Actual Expected results

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk і ще зверніть увагу на Steps for reproduce

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk така ж помилка як в цьому баг репорті https://github.com/users/scholokov/projects/4/views/9?pane=issue&itemId=20549961

**Comment by Nadiyk** [comment]
"Кроки для відтворення" виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk тут дефект не в розділових знаках, а в форматі дати, і тому , що пропущено 2015 для "23.06.2015"

**Comment by Nadiyk** [comment]
Виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk а Summary?)

**Comment by Nadiyk** [comment]
виправила

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
