### ISSUE TITLE
 /20150623_0711_croatia/  Invalid date format 23.06-11.07.2015

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3131]
Prerequisites:
Open https://test.long-travel.live/20150623_0711_croatia/
Steps to play:

1. Invalid date format 23.06-11.07.2015

Actual result: Invalid date format 23.06-11.07.2015
Expected result: The date format is correct  23.06.2015-11.07.2015

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 107.0.5304.122
![прочирк -](https://user-images.githubusercontent.com/113175298/219007705-688fe600-3a60-461d-8310-8008e77f0026.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk тут мається на увазі що подорож була з 23.06 по 11.07 2015 року.

**Comment by Nadiyk** [comment]
у фігмі 
![figma](https://user-images.githubusercontent.com/113175298/219118098-d90f181f-db5b-491d-b7bf-9a0a21397fa7.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk тоді тут проблема не з символом, а з форматом дати

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk якщо судити по Expected Result то подорож тривала з 23.06.11 по 07.2015 цілих 4 роки?

**Comment by Nadiyk** [comment]
ми говорими про формат дати, а тревалість подорожі це вже інше питання. Чи я не права?

**Comment by DmytroMarkulych** [comment]
@Nadiyk Давайте, ще раз порівняємо те що у нас є фактично на сторінці і те що є в Figma, але уважно)

**Comment by Nadiyk** [comment]
Дмитро я запуталась) я маю на увазі що це неправельно "23.06-11.07.2015", повинно бути "23.06.11 - 07.2015"

**Comment by DmytroMarkulych** [comment]
@Nadiyk має бути 23.06.2015-11.07.2015

**Comment by Nadiyk** [comment]
виправила

**Comment by Nadiyk** [comment]
"Кроки для відтворення" виправила

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
