### ISSUE TITLE
20170115_kiev_Zoo_12_month/ Spelling mistake in the word "Київска" in the 1st Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3132]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170115_kiev_Zoo_12_month/
2. Scroll down to the 1st Preview block.
3. Pay attention to the word "Київска" in the 1st Preview block.

**Actual result:**
The word in the 1st Preview block is written "**Київска**" 

**Expected result:**
The word in the 1st Preview block is written "**Київська**" 

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/219011032-0dfcb9eb-4fe4-444e-a36d-d7b36199902d.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
