### ISSUE TITLE
20150502_06_hungary/ Photo block "Hotel Palma" has the layout key "layout=mosaic"

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3134]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the photo block "Hotel Palma"
  3. Scroll to the grid photo
  4. Open to DevTools
 
Actual result:
Photo block "Hotel Palma" has the layout key "layout=mosaic"

Expected result:
Photo block "Hotel Palma" has the layout key "layout=random"

Environment:
MacBook Pro 13, Google Chrome 108.0.5359.124 (Official Build) (x86_64)

<img width="1310" alt="Screenshot 2023-02-16 at 11 36 27" src="https://user-images.githubusercontent.com/89859006/219332960-05c45f2c-7aeb-4833-ad16-12423f5d1c4c.png">
<img width="963" alt="Screenshot 2023-02-16 at 11 53 53" src="https://user-images.githubusercontent.com/89859006/219332976-19dec610-0015-4683-9c49-b3eda6b27897.png">

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
passed
