### ISSUE TITLE
20150502_06_hungary/ Photo block "Debrecen" has the layout key "layout=mosaic"

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3135]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the photo block "Debrecen"
  3. Scroll to the grid photo
  4. Open to DevTools
 
Actual result:
Photo block "Hotel Palma" has the layout key "layout=mosaic"

Expected result:
Photo block "Debrecen" has the layout key "layout=random"

Environment:
MacBook Pro 13, Google Chrome 108.0.5359.124 (Official Build) (x86_64)

<img width="1312" alt="Screenshot 2023-02-16 at 11 37 59" src="https://user-images.githubusercontent.com/89859006/219333978-49884a6c-1c9d-4fb1-be2a-83a92326aa4d.png">
<img width="963" alt="Screenshot 2023-02-16 at 11 53 53" src="https://user-images.githubusercontent.com/89859006/219333991-530b1257-4a1a-4dba-bc90-2c6964790887.png">

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
passed
