### ISSUE TITLE
/20150623_0711_croatia/ Trip name error "Полянак"

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3136]
Prerequisites:
Open https://test.long-travel.live/20150623_0711_croatia/
Steps to play:

1. Trip name error "Полянак"

Actual result:  Trip name error "Полянак"
Expected result: There is no mistake in the word  "Поляна"

Environment: Windows 10 Pro Operating
system:
Browser:  Microsoft Edge
Версія 110.0.1587.46  
![polana](https://user-images.githubusercontent.com/113175298/219332380-e3e32ae4-51dd-4098-a935-3502af10ac54.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk в Expected можна вказати назву яка має бути по факту

**Comment by Nadiyk** [comment]
виправила
