### ISSUE TITLE
20150502_06_hungary/ Photo block "Debrecen Zoo and Amusement Park" has the layout key "layout=mosaic"

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3137]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the photo block "Debrecen Zoo and Amusement Park"
  3. Scroll to the grid photo
  4. Open to DevTools

Actual result:
Photo block "Debrecen Zoo and Amusement Park" has the layout key "layout=mosaic"

Expected result:
Photo block "Debrecen Zoo and Amusement Park" has the layout key "layout=random"

Environment:
MacBook Pro 13, Google Chrome 108.0.5359.124 (Official Build) (x86_64)

<img width="1314" alt="Screenshot 2023-02-16 at 11 39 13" src="https://user-images.githubusercontent.com/89859006/219334737-148aae56-9e92">
<img width="963" alt="Screenshot 2023-02-16 at 11 53 53" src="https://user-images.githubusercontent.com/89859006/219334750-80ff47b2-c00b-40d1-827f-c830755bafd4.png">
-46e1-8a24-48279ddf15bb.png">

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
passed
