### ISSUE TITLE
20150502_06_hungary/ Photo block "Готель Оазис Карпат" has the layout key "layout=mosaic"

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3139]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the photo block "Готель Оазис Карпат"
  3. Scroll to the grid photo
  4. Open to DevTools

Actual result:
Photo block "Готель Оазис Карпат" has the layout key "layout=mosaic"

Expected result:
Photo block "Готель Оазис Карпат" has the layout key "layout=random"

Environment:
MacBook Pro 13, Google Chrome 108.0.5359.124 (Official Build) (x86_64)

<img width="1307" alt="Screenshot 2023-02-16 at 11 40 47" src="https://user-images.githubusercontent.com/89859006/219336814-40a4c8ad-a5c9-4f2f-a3d6-39b76895df02.png">
<img width="963" alt="Screenshot 2023-02-16 at 11 53 53" src="https://user-images.githubusercontent.com/89859006/219336836-4b7669e7-16d7-42c9-b828-1d4a3fe370d5.png">

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
passed
