### ISSUE TITLE
20180428_0501_beregovo # 162 - Название страны промежуточной точки Кафе Chilli-Pizza не соответствует языку страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#314]
**Steps to reproduce:**

1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на название страны промежуточной точки Кафе Chilli-Pizza

**Actual result:**
Название страны промежуточной точки Кафе Chilli-Pizza не соответствует языку страны - **Украина**

**Expected result:**
Название страны промежуточной точки Кафе Chilli-Pizza соответствует языку страны - **Україна**

![image](https://user-images.githubusercontent.com/86321831/144763956-df93fcbf-5119-4379-9877-f76bb7b08ad0.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
