### ISSUE TITLE
20150502_06_hungary/ Photo block "Поляна Україна – Київ Україна" has the layout key "layout=mosaic"

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3140]
Steps to reproduce:

  1. Open: https://test.long-travel.live/20150502_06_hungary/
  2. Pay attention to the photo block "Поляна Україна – Київ Україна"
  3. Scroll to the grid photo
  4. Open to DevTools

Actual result:
Photo block "Поляна Україна – Київ Україна" has the layout key "layout=mosaic"

Expected result:
Photo block "Поляна Україна – Київ Україна" has the layout key "layout=random"

Environment:
MacBook Pro 13, Google Chrome 108.0.5359.124 (Official Build) (x86_64)

<img width="1310" alt="Screenshot 2023-02-16 at 11 41 42" src="https://user-images.githubusercontent.com/89859006/219337657-0bb1ecac-6b61-495b-9531-f419c83d8395.png">
<img width="963" alt="Screenshot 2023-02-16 at 11 53 53" src="https://user-images.githubusercontent.com/89859006/219337663-db12414e-13ed-4aaf-b8cf-62021d80d32b.png">

**Comment by scholokov** [comment]
fixed

**Comment by k335x** [comment]
passed
