### ISSUE TITLE
20161023_chaiky_aerofly/ Name of the travel "20161023_Chaiky_Aerofly" in the Map with routes in the header does not match the name of the Travel in 4.2 Travels.List

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3144]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20161023_chaiky_aerofly/
2. Pay attention to the Map with routes in the header.
3. Pay attention to the name of the current travel in the dropdown list.

**Actual result:**
Name of the current travel is "20161023_Chaiky_Aerofly"

**Expected result:**
Name of the current travel is "Аеротруба "Aerofly""

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![Image](https://user-images.githubusercontent.com/101987790/219360132-5b5d2c06-1f69-4a91-afe3-00c22ca9fd8c.png)

**Comment by GNatala** [comment]
#3088

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
