### ISSUE TITLE
/20150623_0711_croatia/ У блоці "Пагонія Велнес & Конференція  " не відкривається LightBox після натискання на фото в галереї..

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3145]
Prerequisites:
Open https://test.long-travel.live/20150623_0711_croatia/#gallery[photonic-google-album-1]/AE29bMFG3r8oqwCHBCD5Y8upuPjhfMQjnEI7NGQrF4l_HA7pjFJeMTtpXGaVLIa7wkZnQSnNzG_dplj_KdwqU3YSfZeraMQkuA/
Steps to play:

1. Scroll to the section "Пагонія Велнес & Конференція"
2.  Click on the first photo in the gallery
3.  Click the right arrow to go to the next photo

Actual result:  The arrow to advance the photo does not work
Expected result:  The arrow to advance the photo works

Environment: Windows 10 Pro Operating
system:
Browser:  Version 110.0.1587.46

https://user-images.githubusercontent.com/113175298/219389108-b9e5c805-0a74-44ab-b5de-d452042fc93c.mp4

**Comment by DmytroMarkulych** [comment]
@Nadiyk Actual result:
Expected result:

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk 
Кнопки насправді тут немає, але те, що фото не відкривається це факт. Давайте відкриємо вимоги, знайдемо як має себе поводити зображення після клікання на нього (там має відкриватися одна крута штука). І сформуємо Summary таким чином, щоб воно відповідало на питання Де? Що? Коли?

**Comment by Nadiyk** [comment]
виправила

**Comment by DmytroMarkulych** [comment]
@Nadiyk А якщо ми перефразуємо SUmmary таким чином: В блоці "Пагоні..." не відкривається  LightBox  після клікання на фото в галереї.. Я думаю, що це буде максимально інформативно

**Comment by Nadiyk** [comment]
виправила

**Comment by scholokov** [comment]
please retest

**Comment by Nadiyk** [comment]
Pass
