### ISSUE TITLE
/20150623_0711_croatia/ Error in the word  "Полянак"

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3146]
Prerequisites:
Open https://test.long-travel.live/20150623_0711_croatia/#gallery[photonic-google-album-1]/AE29bMFG3r8oqwCHBCD5Y8upuPjhfMQjnEI7NGQrF4l_HA7pjFJeMTtpXGaVLIa7wkZnQSnNzG_dplj_KdwqU3YSfZeraMQkuA/
Steps to play:

1. Pay attention to the name of the trip in "Полянак"

Actual result:  Error in the word "Полянак"
Expected result: the trip name "Поляна"

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 107.0.5304.122
![Поляна 2](https://user-images.githubusercontent.com/113175298/219401729-f7fef5a7-59a6-4290-b3dc-74b20be475ff.png)

**Comment by DmytroMarkulych** [comment]
@Nadiyk можна не вживати фразу "there is"

**Comment by Nadiyk** [comment]
виправила

**Comment by scholokov** [comment]
ви при тестуванні користуєтесь автоматичним перекладом. і тому у вас відображається некоректна інформація. вимкніть, будь ласка, переклад
