### ISSUE TITLE
20161023_chaiky_aerofly/ Photo gallery auto-player shows only the first photo 

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3147]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20161023_chaiky_aerofly
2. Scroll down to the Photo gallery.
3. Open the first photo.
4. Press ![image](https://user-images.githubusercontent.com/101987790/212685688-9e484f9b-6b43-427f-9116-0263d3e9e7e3.png) auto player button.

**Actual result:**
The auto-player shows only the first photo.

**Expected result:**
The auto-player shows the next photos.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

[screencast-bpconcjcammlapcogcnnelfmaeghhagj-2023.02.17-09_36_12.webm](https://user-images.githubusercontent.com/101987790/219581342-63de90e8-bac2-421b-b173-308d0120fcf2.webm)

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
