### ISSUE TITLE
20180428_0501_beregovo # 162 -Размер символов города и страны промежуточной точки Кафе Chilli-Pizza не соответствует требованиям

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#315]
**Steps to reproduce:**

1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на размер символов города и страны промежуточной точки Кафе Chilli-Pizza

**Actual result:**
Размер символов города и страны промежуточной точки Кафе Chilli-Pizza - **15px**

**Expected result:**
Размер символов города и страны промежуточной точки Кафе Chilli-Pizza - **Н2**

![image](https://user-images.githubusercontent.com/86321831/144764139-a274dab9-5f1f-42b1-9302-f7e7327ec69f.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
