### ISSUE TITLE
Create regression tests 

### ISSUE THREAD

**Issue by ABatalov** [scholokov/long-travel-2#3150]
For QA team please create regression test and check lists in TestRail. 
We need to check all website:  
- [ ] Home page 
- [ ] Maps on Home page 
- [ ] Header of Home page 
- [ ] Footer of Home page 
- [ ] Travels page 
- [ ] Each travel (list of all travels:  https://github.com/scholokov/long-travel-2/wiki/4.2-Travels.List) 
- [ ] Map on Travels page 
- [ ] Foot and Header of Travel page

**Comment by ABatalov** [comment]
@scholokov , please check task

**Comment by GNatala** [comment]
Regression checklist: https://qaxcampqa.testrail.io/index.php?/suites/view/43&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=475

**Comment by GNatala** [comment]
Regression test run: https://qaxcampqa.testrail.io/index.php?/runs/view/104&group_by=cases:section_id&group_order=asc

**Comment by Nadiyk** [comment]
https://qaxcampqa.testrail.io/index.php?/suites/view/50&group_by=cases:section_id&group_order=asc&display_deleted_cases=0

**Comment by ABatalov** [comment]
@scholokov - could I move this task to the done?
