### ISSUE TITLE
В розділі "2.1 Travel.YoutubeVideo Gallery" інформація російською мовою

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3154]
Prerequisites:
Open  https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery
Steps to reproduce:

1. Звеніть увагу, в розділі 1.1 інформація російською мовою

Actual result:  1.1 інформація російською мовою
Expected result:  1.1 інформація українською мовою

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104 
![Вимоги на русс](https://user-images.githubusercontent.com/113175298/220111186-d0690d8d-4910-4b54-942f-6e5757d0b78c.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
