### ISSUE TITLE
 In the section "2.1 Travel.YoutubeVideo Gallery" there are words in Russian in the description

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3155]
Prerequisites:
Open https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery
Steps to reproduce:

1.  Please note that there is a Russian word in section 1.2

Actual result:  there are words in Russian in the description
Expected result: Description of section 1.2 in Ukrainian

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104     
![рос вимоги 2](https://user-images.githubusercontent.com/113175298/220112912-e04b2e21-b2ff-42ed-9b9d-512f66f463fe.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
