### ISSUE TITLE
In the section "2.1 Travel.YoutubeVideo Gallery", subsection 1.3 is in Russian

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3156]
Prerequisites:
Open https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery
Steps to reproduce:

1. In the section "2.1 Travel.YoutubeVideo Gallery", subsection 1.3 is in Russian

 
Actual result:  In the section "2.1 Travel.YoutubeVideo Gallery", subsection 1.3 is in Russian
Expected result: Description of section 1.3 in Ukrainian

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104

![1 3 вимоги росс](https://user-images.githubusercontent.com/113175298/220115934-1e9a8f89-8d2f-4ba6-b8d7-235062f48e23.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
