### ISSUE TITLE
  In the section "2.1 Travel.YoutubeVideo Gallery" subsection 1.3 in Russian

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3157]
Prereguister:
Open https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery
Steps to reproduce:

1. Please note that in "2.1 Travel.YoutubeVideo Gallery" subsection 1.3.1 is in Russian

Actual result:  In the section "2.1 Travel.YoutubeVideo Gallery" subsection 1.3 in Russian
Expected result: Description of section 1.3.1 in Ukrainian

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версія 110.0.5481.104

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
