### ISSUE TITLE
20170115_kiev_Zoo_12_month/ Spelling mistake in the word "Месяців" in the Map with routes in the header

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3158]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170115_kiev_Zoo_12_month/
2. Pay attention to the Map with routes in the header.
3. Pay attention to the name of the current travel in the dropdown list.

**Actual result:**
Name of the current travel is "Зоопарк XII Месяців"

**Expected result:**
Name of the current travel is "Зоопарк XII Місяців"

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/220285205-88ed881d-127d-4c38-9373-80891a7b41c3.png)

**Comment by GNatala** [comment]
https://github.com/scholokov/long-travel-2/issues/3089

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
