### ISSUE TITLE
20170115_kiev_Zoo_12_month/ In the map's legend is an extra element "Зоопарк XII Месяцев, Демидов"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3159]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170115_kiev_Zoo_12_month/
2. Pay attention to the Map block.
3. Pay attention to the text after preview foto in the map's legend.

**Actual result:**
The extra element "Зоопарк XII Месяцев, Демидов" is in the map's legend

**Expected result:**
The extra element "Зоопарк XII Месяцев, Демидов" does not appear in the map's legend

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/220345762-bb1fd74d-f0f2-4af4-bb6c-029dcd128dbd.png)

**Comment by GNatala** [comment]
https://github.com/scholokov/long-travel-2/issues/3089

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
