### ISSUE TITLE
20180428_0501_beregovo # 162 - Размер символов даты промежуточной точки Кафе Chilli-Pizza не соответствует требованиям

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#316]
**Steps to reproduce:**

1. Открыть страницу https://long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на размер символов даты промежуточной точки Кафе Chilli-Pizza

**Actual result:**
Размер символов даты промежуточной точки Кафе Chilli-Pizza - **15px**

**Expected result:**
Размер символов даты промежуточной точки Кафе Chilli-Pizza - **Н3**

![image](https://user-images.githubusercontent.com/86321831/144764262-a46fef71-ba39-46a7-b9a7-00f2f76ba1d1.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
