### ISSUE TITLE
20160326_konotop Width of the map is 809.6px  and height of the map is 570px.

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3163]
**Pre-conditions:**
Open https://test.long-travel.live/20160326_konotop

**Steps to reproduce:**
1. Scroll down to the map of the travel.
2. Pay attention to the widtht and height of the map.

**Actual result:**
Width of the map is 809.6px  and height of the map is 570px.

**Expected result:**
Width of the map is 700px  and height of the map is 520px

**Environment:**

Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![j0cm9Ih2mq](https://user-images.githubusercontent.com/123729744/220377383-94b51763-db09-4656-9001-ce9ad17a281d.png)

**Comment by DmytroMarkulych** [comment]
@OlhaHutsman Розмір деяких елементів буде різним для різних розширень екранів. Одним із вірних рішень буде, дивитися розміри елементів згідно того розміру екрану під який зроблений дизайн

**Comment by OlhaHutsman** [comment]
@DmytroMarkulych  у мене 1920px, згідно вимог -  https://github.com/scholokov/long-travel-2/wiki   це вірне розширення. Що робити в такому випадку?

**Comment by DmytroMarkulych** [comment]
@OlhaHutsman просто закрийте дефект
