### ISSUE TITLE
20150523_picnic_dnipro/ In the 2nd Preview block is missed city name "Кийлів"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3167]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20150523_picnic_dnipro/
2. Scroll down to the 2nd Preview block.
3. Pay attention to the city name in the 2nd Preview block.

**Actual result:**
The city name is missed in the  2nd Preview block.

**Expected result:**
The city name is  "**Кийлів**" in the  2nd Preview block.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/220561272-56bb38bf-e6e9-4d22-83c2-40fb047e1693.png)

**Comment by GNatala** [comment]
https://github.com/scholokov/long-travel-2/issues/2992

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
