### ISSUE TITLE
20160326_konotop Button "TOPIC" is not displayed in the right side of the header.

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3168]
**Pre-conditions:**
Open https://test.long-travel.live/20160326_konotop

**Steps to reproduce:**

1.Find header.
2.Pay attention to the right side of the header-button "TOPIC" is not displayed.

**Actual result:**
Button "TOPIC" is not displayed in the right side of the header.

**Expected result:**
Button "TOPIC" is displayed in the right side of the header.

**Environment:**

Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**

![69f2EaciNf](https://user-images.githubusercontent.com/123729744/221897966-e862e742-7e35-4475-9290-20cfff3627c6.png)

**Comment by scholokov** [comment]
дизайн у фігмі не являється функціональними вимогами. тобто ми не можемо сказати, що данний розділ має бути, суто виходячи з фігми

**Comment by OlhaHutsman** [comment]
@scholokov  edited
