### ISSUE TITLE
In the section 11.Global.Search a Russian word is used "Поиск"

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3169]
Preregister:
Open: https://github.com/scholokov/long-travel-2/wiki/1.1-Global.Search
Steps to reproduce:

1.  Pay attention to the word "Поиск"

Actual result:  In section 11.Global.Search a Russian word s used "Поиск"
Expected result:  In section  11.Global.Search Ukraine words used "Пошук"

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версія 110.0.5481.104
![1 1 глобал](https://user-images.githubusercontent.com/113175298/220610504-a526f58f-42bf-4119-8533-e8a37b29770a.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
