### ISSUE TITLE
In section 11.Global.Search a Russian words used

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3171]
Preregister:
Open: https://github.com/scholokov/long-travel-2/wiki/1.1-Global.Search
Steps to reproduce:

1. Pay attention to the word 1.2

Actual result: In section 11.Global.Search a Russian word s used
Expected result: In section 11.Global.Search Ukraine words used

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версія 110.0.5481.104
![1 2 dryh](https://user-images.githubusercontent.com/113175298/220613079-c471c784-7110-4363-8277-1d6043d85627.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
