### ISSUE TITLE
 In section 11.Global.Search a Russian word s used

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3172]
Preregister:
Open: https://github.com/scholokov/long-travel-2/wiki/1.1-Global.Search
Steps to reproduce:

1. Pay attention to the word 1.3

Actual result: In section 11.Global.Search a Russian word s used
Expected result: In section 11.Global.Search Ukraine words used

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версія 110.0.5481.104
![1 3 glob](https://user-images.githubusercontent.com/113175298/220614038-f7420342-c86d-454c-b42a-b28b8091cf1b.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
