### ISSUE TITLE
 In section 1.2 Travel. YoutubeVideo Gallery uses Russian words

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3173]
Prereguister:
Open https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery
Steps to reproduce:

1.  Pay attention to the description of section 1.3
 
Actual result:  In section 1.2 Travel. YoutubeVideo Gallery uses Russian words
Expected result:  In section 1.2 Travel. YoutubeVideo Gallery uses Ukrainian words

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версія 110.0.5481.104
![2 1 trevel](https://user-images.githubusercontent.com/113175298/220617541-b26597fa-3400-400a-9671-c53b1ec41be6.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
мені здається що було б правельніше "Початковий пункт виїзду і -  кінцевий пункт приїзду", чи я неправа?

**Comment by Nadiyk** [comment]
pass
