### ISSUE TITLE
In  section 2.2 Travel.Category word "Категорії" described in Russian

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3174]
Preregister:
Open:  https://github.com/scholokov/long-travel-2/wiki/2.2-Travel.Category
Steps to reproduce:

1. Pay attention to the word

Actual result:  In section 2.2 Travel.Category word "Категорії" described in Russian
Expected result:  In section 2.2 Travel.Category word "Категорії" described in Ukrainian

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версія 110.0.5481.104
![2 2 Category](https://user-images.githubusercontent.com/113175298/220624377-a54d2f63-a290-4d45-84b6-8019c6b222ab.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
the bug is reproduced
![image](https://user-images.githubusercontent.com/113175298/221847920-fd37766a-24b8-4501-94dd-69e1015dfd54.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
