### ISSUE TITLE
20151031_haisyn_uman/ Name of the travel "20151031_haisyn_uman" in the Map with routes in the header does not match the name of the Travel in 4.2 Travels.List

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3175]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20151031_haisyn_uman/
2. Pay attention to the Map with routes in the header.
3. Pay attention to the name of the current travel in the dropdown list.

**Actual result:**
Name of the current travel is "**20151031_haisyn_uman**"

**Expected result:**
Name of the current travel is "**Гайсин - Умань**"

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/220657166-a85b00d9-1f8d-4d86-b460-7c161e2ee3ab.png)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
