### ISSUE TITLE
20160618_mezhigorie/ Font of the "Дата публікації: 18.06.2016" in the end of the page does not meet design requirements in Figma

### ISSUE THREAD

**Issue by k335x** [scholokov/long-travel-2#3177]
Steps to reproduce:

  1. Open to [link](https://www.test.long-travel.live/20160618_mezhigorie)
  2. Scroll to "Дата публікації: 18.06.2016"
  3. Open to DevTools

Actual Result:
Font of the "Дата публікації: 18.06.2016" in the end of the page does not meet design requirements in Figma

Expected result:
The block "Publication data: 18.06.2016" has the font "Rubik"

Environment:
MacBook Pro 13, Google Chrome 109.0.5414.87 (Official Build) (x86_64)

Attachment:
<img width="1305" alt="Screenshot 2023-02-22 at 17 09 22" src="https://user-images.githubusercontent.com/89859006/220665629-e0b810a6-8856-4e75-8d72-86486c713cfb.png">
<img width="1304" alt="Screenshot 2023-02-22 at 17 05 21" src="https://user-images.githubusercontent.com/89859006/220665647-97ab22a4-e6f9-4a6a-925b-4d07912fef21.png">

**Comment by scholokov** [comment]
please retest

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
