### ISSUE TITLE
2.5 Travel.FotoGallery page description "1. Общее" described in Russian

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3178]
Prerequisites:
Open  https://github.com/scholokov/long-travel-2/wiki/2.5-Travel.FotoGallery
Steps to reproduce:

1. Pay attention to the description  "1. Общее"

Actual result: 2.5 Travel.FotoGallery page description "1. Общее" described in Russian
Expected result:  2.5 Travel.FotoGallery page description "1. Общее" description in Ukrainian

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104 
![общее](https://user-images.githubusercontent.com/113175298/220934841-3e1d3968-ef88-4faf-97d4-7b821b7fa327.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
