### ISSUE TITLE
In the section "Галерея" item 1.2 in Russian

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3180]
Prerequisites:
Open https://github.com/scholokov/long-travel-2/wiki/2.5-Travel.FotoGallery
Steps to reproduce:

1. Pey attention to the description of section 1.2

Actual result: In the section "Галерея" item 1.2 in Russian
Expected result: In the section "Галерея" item 1.2 in Ukrainian

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104 
 
![Galery 1 2](https://user-images.githubusercontent.com/113175298/220944951-5e0b6855-bd41-4a1f-96ec-536f68cfe35b.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
