### ISSUE TITLE
Section 2.2 in the gallery in Russian

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3181]
Prerequisites:
Open: https://github.com/scholokov/long-travel-2/wiki/2.5-Travel.FotoGallery
Steps to reproduce:

1. Pay attention to section 2.2 in the gallery 

Actual result:  Section 2.2 in the gallery in Russian
Expected result: Section 2.2 in the gallery in Ukrainian

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104 
![GalereyTredtl 2 2](https://user-images.githubusercontent.com/113175298/220946107-8b00ef06-aaa5-46ed-affd-e206c84cfdfa.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
