### ISSUE TITLE
Chapter 2.3 is described in Russian  Travel.FotoGallery 

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3182]
Prerequisites:
Open: https://github.com/scholokov/long-travel-2/wiki/2.5-Travel.FotoGallery
Steps to reproduce:

1. Please refer to section 2.3

Actual result:  Chapter 2.3 is described in Russian
Expected result:  Chapter 2.3 is described in Ukraine

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104 
![2 3 GaleryFoto](https://user-images.githubusercontent.com/113175298/220954671-49084178-4a52-4f21-a26a-0203adebd2c4.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
