### ISSUE TITLE
В URL немає кода подорожі

### ISSUE THREAD

**Issue by Ovololeg** [scholokov/long-travel-2#3184]
Передумови:
Відкрити: https://test.long-travel.live/konotop/
Кроки для відтворення:

1. Зверніть увагу на відсутність коду в URL

Фактичний результат: В URL немає кода подорожі.
Очікуваний результат: В URL є код подорожі - https://test.long-travel.live/20160326_Konotop/

Середовище: Windows 10 Pro
Операційна система: Google Chrome Версия 110.0.5481.105
![chrome_XsSyRWyugn](https://user-images.githubusercontent.com/126007553/221151439-801b993a-fca1-4d96-8009-7481172868fb.png)

**Comment by DmytroMarkulych** [comment]
@Ovololeg 
1. Додайте в Очікуваний результат, який код має бути. Для того щоб баг репорт був максомально інформативний

**Comment by Ovololeg** [comment]
Виправив

**Comment by GNatala** [comment]
не є актуальним, вже виправлено
