### ISSUE TITLE
/konotop/ Немає прапора в превью 

### ISSUE THREAD

**Issue by Ovololeg** [scholokov/long-travel-2#3185]
Передумови:
Відкрити: https://test.long-travel.live/konotop/
Кроки для відтворення:

Зверніть увагу на відсутність прапора в превью

Фактичний результат: Немає прапора в превью 
Очікуваний результат: Є прапора України зправа в превью 

Середовище: Windows 10 Pro
Операційна система: Google Chrome Версия 110.0.5481.105
![chrome_sfeTyEFgPj](https://user-images.githubusercontent.com/126007553/221153783-5fcd140a-d857-439d-b0a1-287aaf538396.png)

**Comment by DmytroMarkulych** [comment]
@Ovololeg 
1. В очікуваному результаті вкажіть конкретно що має бути

**Comment by DmitriiNasonov** [comment]
bug-report isn't actual
