### ISSUE TITLE
Немає зображення на превью

### ISSUE THREAD

**Issue by Ovololeg** [scholokov/long-travel-2#3189]
Передумови:
Відкрити: https://test.long-travel.live/konotop/
Кроки для відтворення:

Зверніть увагу на відсутність зображення на превью

Фактичний результат: Немає зображення на превью
Очікуваний результат: Є зображення на превью
![chrome_I6ddIsUNEO](https://user-images.githubusercontent.com/126007553/221576503-20700676-1f3e-4f6a-b7b9-e51f4a51df54.png)

Середовище: Windows 10 Pro
Операційна система: Google Chrome Версия 110.0.5481.105
![YtAgIhAJSB](https://user-images.githubusercontent.com/126007553/221191697-4cfc097c-70b3-4388-a098-5e915459d7dd.png)

**Comment by DmytroMarkulych** [comment]
@Ovololeg 
1. В очікуваному результаті вкажіть конкретно що має бути 
2. Перед summary вкажіть про яку саме сторінку йдеться мова

**Comment by Ovololeg** [comment]
Виправив

**Comment by DmitriiNasonov** [comment]
bug-report isn't actual
