### ISSUE TITLE
 /20200814_15_serhiivka/ Немає зображення в прев'ю .

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3190]
Передумови:
Відкрити https://test.long-travel.live/20200814_15_serhiivka/
Кроки для відтворення: 
1. Зверніть увагу, що в прев'ю немає початкового зображення.

Фактичний результат: 
Немає зображення в прев'ю .

Очікуваний результат: 
В прев'ю є фото з подорожі  .

Середовище: Windows 10 ,версія 22 Н 2, Операційна
система:
Браузер: Google Chrome Version 110.0.5481.177

![2023-02-26_17h58_51](https://user-images.githubusercontent.com/125903734/221421666-6947049a-dafe-4d7c-bb3b-aee6e39f35cb.png)

**Comment by DmytroMarkulych** [comment]
@ViktoriaZamkova Додайте додаткову інформацію про очікуваний результат

**Comment by ViktoriaZamkova** [comment]
Дописала.
