### ISSUE TITLE
20160326_konotop In the header the font of text "Long-Travel" is "Open Sans".

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3191]
**Pre-conditions:**
Open https://test.long-travel.live/20160326_konotop

**Steps to reproduce:**
1. Find header at the top of the Travel page.
2. Pay attention to the font of text "Long-Travel".

**Actual result:**
In the header the font of text "Long-Travel" is "Open Sans".

**Expected result:**
In the header the font of text "Long-Travel" is "Rubik".

**Environment:**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![VFNv8QcsyI](https://user-images.githubusercontent.com/123729744/221519748-a268d572-383a-4b60-a07a-a0957dc527e7.png)

**Comment by DmytroMarkulych** [comment]
@OlhaHutsman Priority QA не виставляє, його виставляє представник менеджменту (продукт овнер, аналітик, проджект менеджер і т.д)

**Comment by OlhaHutsman** [comment]
@DmytroMarkulych  edited
