### ISSUE TITLE
/20200814_15_serhiivka/ Відсутня карта подорожі Київ - Сергіївка .

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3193]
Передумови:
Відкрити https://test.long-travel.live/20200814_15_serhiivka/

Кроки для відтворення:
Звернути увагу на прев'ю- відсутня карта подорожі Київ - Сергіївка.

Фактичний результат:
Немає загальної карти подорожі в прев'ю .

Очікуваний результат:
В прев'ю є карта з подорожі .

Середовище: Windows 10 ,версія 22 Н 2, Операційна
система:
Браузер: Google Chrome Version 110.0.5481.177

![Image](https://user-images.githubusercontent.com/125903734/222435176-b7614e12-293a-4834-be12-05c26788f605.png)

**Comment by DmytroMarkulych** [comment]
@ViktoriaZamkova Зверніть будь ласка увагу на опис дефекту, Summary  говорить про одне, а опис про інше

**Comment by ViktoriaZamkova** [comment]
Переписала,дякую.

**Comment by DmytroMarkulych** [comment]
@ViktoriaZamkova І ще скріншот зробимо таким чином, щоб він не показував превю, а місце де має бути карта

**Comment by ViktoriaZamkova** [comment]
замінила скріншот

**Comment by scholokov** [comment]
fixed

**Comment by ViktoriaZamkova** [comment]
checked
