### ISSUE TITLE
/20200814_15_serhiivka/ In travel "Київ - Сергіївка" travel name must be in Ukrainian.

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3194]
Steps to reproduce:
Open https://test.long-travel.live/20200814_15_serhiivka/

Actual result:
20200814_15_serhiivka

Expected result: 
Київ - Сергіївка

Environment: 
Windows 10 Pro , 21H2  
Brouser: Google Chrome Version 110.0.5481.177

![2023-02-28_16h46_12](https://user-images.githubusercontent.com/125903734/221889972-50f3a740-d42b-4bc6-aefd-2b3b044beadf.png)

**Comment by DmytroMarkulych** [comment]
@ViktoriaZamkova 
1. Стараємося забути слова типу "не коректно, не працює і т.д" вони не несуть ніякої корисної інформації. Найкращою практикою буде будувати Summary таким чином, щоб воно відповідало на 3 питання: Де? Що? Коли? 
2. Також це стосується актуального та очікуваного результатів
3. Не забуває проставляти атрибути 

![Image](https://user-images.githubusercontent.com/88647733/221898773-57c764b3-5082-49f7-bb0b-e5cd34681b1e.png)

**Comment by ViktoriaZamkova** [comment]
Дякую, виправила.

**Comment by DmytroMarkulych** [comment]
@ViktoriaZamkova в Summary присутнє слово "incorrect"

**Comment by scholokov** [comment]
на чому базується експектід?
є окремі вимоги на назву подорожі
https://github.com/scholokov/long-travel-2/wiki/4.2-Travels.List


в ідеалі подібні баги писати у такому форматі:
Actual result:
20200814_15_serhiivka

Expected result:
Сергіївка (according to requirements: https://github.com/scholokov/long-travel-2/wiki/4.2-Travels.List)

у такому випадку ні в кого не виникне питання :)

**Comment by ViktoriaZamkova** [comment]
Дякую! Виправила.

**Comment by scholokov** [comment]
fixed

**Comment by ViktoriaZamkova** [comment]
checked
