### ISSUE TITLE
 In Russian described "Повинні"  in section 2.8 Travel.Map  

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3195]
Preregister:
Open: https://github.com/scholokov/long-travel-2/wiki/2.6-Travel.Map
Steps to reproduce:

1. Pay attention to the word  "Повинні"

Actual result: In section 2.8 Travel.Map  "Повинні" described in Russian
Expected result: In section 2.8 Travel.Category word "Категорії" described in Ukrainian

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версія 110.0.5481.104
![dol;na](https://user-images.githubusercontent.com/113175298/221945187-8ec6bc1c-079c-45a6-bf97-fe516c0cf5ed.png)

**Comment by scholokov** [comment]
fixed
