### ISSUE TITLE
20150919_kiev_aviation_museum/The name of travel in the Preview block "Державний музей авіації" does not match the name of Travel in 4.2 Travels.List#2995

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3196]
Steps to reproduce:
1. Open https://test.long-travel.live/20150919_kiev_aviation_museum/
2. Scroll down to the Preview block
3. Pay attention to the name of travel in the Preview block "Державний музей авіації"

Actual result:
The name of travel in the Preview block "Державний музей авіації"

Expected result:
The name of travel in the Preview block "Державний музей авіації осінь 2015"

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://user-images.githubusercontent.com/123776698/221981942-b47a20c7-878c-414c-87b1-5ca6a652e1a6.png)

**Comment by DmytroMarkulych** [comment]
@ODrobik давайте додамо атрибути в баг репорт

![Image](https://user-images.githubusercontent.com/88647733/222243344-9875c209-45db-4762-a503-7b44b1519bef.png)

**Comment by ODrobik** [comment]
Виправлено

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
@scholokov **Passed**

**Comment by ODrobik** [comment]
#2995
