### ISSUE TITLE
20160326_konotop The color of the text in the Legend of the Map is #FFFFFF.

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3198]
**Pre-conditions:**
Open https://test.long-travel.live/20160326_konotop

**Steps to reproduce:**

1.Find the Legend of the Map on the Travel page.
2.Pay attention to the color of the text .

**Actual result:**
The color of the text in the Legend of the Map is  rgb (51,51,51).

**Expected result:**
The color of the text in the Legend of the Map is  FFFFFF.

**Environment:**

Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![4ld4PAp9jd](https://user-images.githubusercontent.com/123729744/222065739-18462dc8-4d2f-4a38-9db4-b14d61795563.png)

**Comment by DmytroMarkulych** [comment]
@OlhaHutsman не забуваємо про атрибути баг репорту

**Comment by OlhaHutsman** [comment]
@DmytroMarkulych  edited
