### ISSUE TITLE
Grammatiical error in the word "Тєги"

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3201]
Preregister:
Open: https://github.com/scholokov/long-travel-2/wiki/2.8-Travel.Tags
Steps to reproduce:

1. Pay attention to the word ''Теги''
 
Actual result: Grammatical error in the word "Тєги"
Expected result: No grammatical errors in the word 

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версія 110.0.5481.104
![tehu](https://user-images.githubusercontent.com/113175298/222129584-17a5b222-c8d0-4b52-8f03-0666e39b64cd.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
Pass
