### ISSUE TITLE
In section 2.8 Travel.Tags ''1.3'' described in Rusian

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3203]
Preregister:
Open: https://github.com/scholokov/long-travel-2/wiki/2.8-Travel.Tags
Steps to reproduce:

1. Pay attention to the word in section "1.3"

Actual result: In section 2.8 Travel.Tags ''1.3'' described in Rusian
Expected result: In section 2.8 Travel. Tags ''1.3'' is the word described in Ukrainian

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версія 110.0.5481.104
![1 3 TEGSpage](https://user-images.githubusercontent.com/113175298/222133905-43858bde-f851-4021-91d9-e8f85edb34de.png)

**Comment by scholokov** [comment]
приведений лінк, не збігається з актуальним

**Comment by DmytroMarkulych** [comment]
приведений лінк, не збігається з актуальним

**Comment by Nadiyk** [comment]
виправила

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
