### ISSUE TITLE
2.8 Travel.URL  uses Russian words

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3205]
Prereguister:
Open https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery
Steps to reproduce:

1. Pay attention to the description of section 2.8

Actual result: In section 2.8   Travel.URL   uses Russian words
Expected result: In section 2.8  Travel.URL   uses Ukrainian words

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Версія 110.0.5481.104
![image](https://user-images.githubusercontent.com/113175298/222784788-16ff5acd-cb0a-4f90-89ee-b04fb86b3614.png)

**Comment by scholokov** [comment]
виправлено

**Comment by Nadiyk** [comment]
Pass
