### ISSUE TITLE
/20200814_15_serhiivka/ In travel " Київ - Сергіївка" video title in English.

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3206]
Steps to reproduce:
Open https://test.long-travel.live/20200814_15_serhiivka/

Actual result:
20.08.14 Киев - Сергеевка

Expected result:
Київ - Сергіївка

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177

![2023-03-01_17h32_03](https://user-images.githubusercontent.com/125903734/222428431-2f47af46-f6ef-42e1-af07-4e8d0b19b449.png)

**Comment by DmytroMarkulych** [comment]
@ViktoriaZamkova давайте ще додамо скріншот

**Comment by scholokov** [comment]
fixed
