### ISSUE TITLE
/20061028_bila_tserkva/ In the Preview no general photo of the travel.

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3207]
Steps to reproduce:
Open https://test.long-travel.live/20061028_bila_tserkva/

Actual result:
Missing general photo of the travel in the preview

Expected result:
A photo of the travel is present

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177

![2023-03-01_18h07_41](https://user-images.githubusercontent.com/125903734/222237251-17df0d7c-571f-4012-ac2f-3333c3b5aa94.png)

**Comment by scholokov** [comment]
про яку саме подорож ведеться розмова?
приведіть буд ласка ID

**Comment by DmytroMarkulych** [comment]
![Image](https://user-images.githubusercontent.com/88647733/222953640-0d75e3c6-e4e2-442a-9077-b7f5904b9b13.png)
