### ISSUE TITLE
20150919_kiev_aviation_museum/ The name of waypoint in the map's legend is in russian language

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3208]
Steps to reproduce:
    1. Open https://test.long-travel.live/20150919_kiev_aviation_museum/
    2. Pay attention to the name of waypoint "Музей Авиации, Kyiv, Ukraine" of the Legend Map block.

Actual result:
The name of waypoint "Музей Авиации, Kyiv, Ukraine "

Expected result:
The name of waypoint "Музей Авіації, Kyiv, Ukraine"

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![Легенда_Рос](https://user-images.githubusercontent.com/123776698/222557810-fa1c0dd3-f726-4cf4-8d63-b2cfdf5b5110.png)

**Comment by DmytroMarkulych** [comment]
@ODrobik хороша робота!) Але давайте ще додамо один атрибут 

![Image](https://user-images.githubusercontent.com/88647733/222718733-aaea6d5c-ca22-4f75-8aef-26c791f35c09.png)

**Comment by ODrobik** [comment]
@DmytroMarkulych Виправлено

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
passed
#2995
