### ISSUE TITLE
/20200814_15_serhiivka/ There is no description of the travel Київ - Сергіївка in body

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3209]
Steps to reproduce:
Open https://test.long-travel.live/20200814_15_serhiivka/
Scroll to the bottom of the page 

Actual result:
There is no description of the travel

Expected result:
Description of the travel befor date of publication

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.178 

![2023-03-03_13h42_48](https://user-images.githubusercontent.com/125903734/222713822-6dddd3d3-30ac-4161-bfcc-1a010950e8dd.png)

**Comment by scholokov** [comment]
стосовно яких вимог баг заведено?
