### ISSUE TITLE
/20171027_cherkasy/  In the Preview no general photo of the travel.

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3212]
Steps to reproduce:
Open https://test.long-travel.live/20171027_cherkasy/

Actual result:
Missing general photo of the travel in the preview

Expected result:
A photo of the travel is present

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177

![2023-03-03_15h58_25](https://user-images.githubusercontent.com/125903734/222738838-bb61eb79-8f34-4c67-b03e-a95af7c98a95.png)

**Comment by scholokov** [comment]
fixed

**Comment by ViktoriaZamkova** [comment]
checked
