### ISSUE TITLE
/20171027_cherkasy/ In the description of the map of Київ - Черкаси the distance between the cities is not written.

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3213]
Steps to reproduce:
Open 
https://test.long-travel.live/20171027_cherkasy/

Actual result:
The distance between the cities is not specified

Expected result:
the distance between the cities is written

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177

![2023-03-03_16h19_46](https://user-images.githubusercontent.com/125903734/222744284-9ae2fd7a-4248-4856-997b-277304d02a25.png)

**Comment by scholokov** [comment]
fixed

**Comment by ViktoriaZamkova** [comment]
checked
