### ISSUE TITLE
In section  5. Механізм роботи прев'ю та фото, is a grammatical error

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3214]
Prerequisites:
Open: https://github.com/scholokov/long-travel-2/wiki/2.5-Travel.FotoGallery
Steps to reproduce:

1. Spin the page to chapter 5
2. Note the grammatical error in 2 paragraphs

Actual result: In section  5. Механізм роботи прев'ю та фото, is a grammatical error
Expected result: In section  5. Механізм роботи прев'ю та фото, is no grammatical error

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104  
![крапка кома](https://user-images.githubusercontent.com/113175298/222742737-a722866f-cd61-47a4-8510-b7f80e7219ec.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
the bug is reproduced
![image](https://user-images.githubusercontent.com/113175298/223776721-15a37716-8b86-4b9f-9d21-c4dafbc5b7bf.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
Pass
