### ISSUE TITLE
In   section  3 Maps.Structure are Russian words  

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3215]
Prerequisites:
Open: https://github.com/scholokov/long-travel-2/wiki/3-Maps.Structure
Steps to reproduce:

1. Pay attention to the description

Actual result:  In section  3 Maps. Structure are Russian words 
Expected result: In section  3 Maps. Structure is Ukrainian  words 

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104     
![мапСтруктур 1](https://user-images.githubusercontent.com/113175298/223123547-f4590d5a-4232-495b-b52a-5f2b03017c0f.png)

**Comment by scholokov** [comment]
fixed
