### ISSUE TITLE
20160326_konotop At the top of the Travel page the 1st preview position is relative.

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3217]
**Pre-conditions:**
Open https://test.long-travel.live/20160326_konotop

**Steps to reproduce:**

1.Find 1st preview at  the top of the Travel page.
2.Pay attention to the position of the 1st preview.

**Actual result:**
The 1st preview position is relative.

**Expected result:**
The 1st preview position is absolute.

**Environment:**

Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![YUkmmnmOEu](https://user-images.githubusercontent.com/123729744/223144883-8785f88b-c035-4696-9655-31f631bc048c.png)

**Comment by scholokov** [comment]
absolute - мається на увазі, що елемент буде зафіксований, тобто при скролі - він буде лишатися на своєму місці
на це параментр на фігмі не звертаємо увагу

**Comment by OlhaHutsman** [comment]
@scholokov з яким коментарем в такому випадку закривати баг?

**Comment by scholokov** [comment]
наприклад:
"не є багом"

**Comment by scholokov** [comment]
і перекидати у кансел

**Comment by OlhaHutsman** [comment]
Not a bug
