### ISSUE TITLE
In 3.2 Maps.Global Map with countries, section 1.1 is descraibed in Russian

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3218]
Prerequisites:
Open:https://github.com/scholokov/long-travel-2/wiki/3.2-Maps.Global-Map-with-countries
Steps to reproduce:

1. Pay attention to the description of section 1.1

Actual result:  In 3.2 Maps.Global Map with countries, section 1.1 is described in Russian
Expected result: In 3.2 Maps.Global Map with countries, section 1.1 is described in Ukrainian

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104     
![with countries 1 1](https://user-images.githubusercontent.com/113175298/223145848-23d5fd96-f2bf-4489-b0cd-11820f07b453.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
