### ISSUE TITLE
In 3.2 Maps.Global Map with countries, section 1.2 is described in Russian

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3219]
Prerequisites:
Open: https://github.com/scholokov/long-travel-2/wiki/3.2-Maps.Global-Map-with-countries
Steps to reproduce:

1. Pay attention to the description of section 1.2

Actual result: In 3.2 Maps.Global Map with countries, section 1.2 is described in Russian
Expected result: In 3.2 Maps.Global Map with countries, section 1.2 is described in Ukrainian

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104
![1 2 countries](https://user-images.githubusercontent.com/113175298/223147038-2707e975-a108-44f8-9931-281de8f838ca.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
