### ISSUE TITLE
/20171027_cherkasy/ The date in the map legend does not match the date of travel.

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3221]
Steps to reproduce:

1. Open https://test.long-travel.live/20171027_cherkasy/.
2. Pay attention to the map legend.

Actual result:
Jan 2, 2023 

Expected result:
Okt 27, 2017

Environment:
Windows 10 Pro , 21H2

Brouser: Google Chrome Version 110.0.5481.177

![2023-03-07_13h30_40](https://user-images.githubusercontent.com/125903734/223410620-f2bb773c-247f-48bd-8d31-bb3c4913a346.png)

**Comment by scholokov** [comment]
fixed

**Comment by ViktoriaZamkova** [comment]
checked
