### ISSUE TITLE
/20171027_cherkasy/ No actual travel link in map legend.

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3222]
Steps to reproduce:

Open https://test.long-travel.live/20171027_cherkasy/.
Pay attention to the map legend.

Actual result:
No link in map legend.

Expected result:
There is an actual link in the map legend.

Environment:
Windows 10 Pro , 21H2

Brouser: Google Chrome Version 110.0.5481.177
![2023-03-07_13h55_28](https://user-images.githubusercontent.com/125903734/223415587-e5d3d988-4529-479f-9c1a-141692c5227e.png)

![2023-03-07_13h54_03](https://user-images.githubusercontent.com/125903734/223414915-5887d741-ef05-4f27-b012-7bb20f3cb184.png)

**Comment by scholokov** [comment]
fixed

**Comment by ViktoriaZamkova** [comment]
checked
