### ISSUE TITLE
/20171027_cherkasy/ The travel video is untitled.

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3223]
Steps to reproduce:
1. Open https://test.long-travel.live/20171027_cherkasy/
2. Scroll down to the video

Actual result:
The travel video is untitled

Expected result:
first video - 2017.10.27 Київ- Черкаси  
second video - 2017.10.27  Черкаси - Київ

Environment:
Windows 10 Pro , 21H2

Brouser: Google Chrome Version 111.0.5563.65

![2023-03-08_12h32_27](https://user-images.githubusercontent.com/125903734/223690063-479dda5e-cdce-4786-8043-274a3335c9c3.png)

![2023-03-08_12h33_54](https://user-images.githubusercontent.com/125903734/223691597-b1adfdf7-4b94-40ad-b6c8-40deed8c7f84.png)

**Comment by scholokov** [comment]
fixed

**Comment by ViktoriaZamkova** [comment]
checked
