### ISSUE TITLE
/20171027_cherkasy/ The date of publication is not identical to the date of travel.

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3224]
Steps to reproduce:

1. Open https://test.long-travel.live/20171027_cherkasy/
2. Scroll down to the publication date.

Actual result:
08.11.2022

Expected result:
27.10.2017

Environment:
Windows 10 Pro , 21H2

Brouser: Google Chrome Version 111.0.5563.65

![2023-03-08_12h52_08](https://user-images.githubusercontent.com/125903734/223694352-fbdb242d-4e3d-4be7-a996-f60faac0604f.png)

![2023-03-08_12h54_00](https://user-images.githubusercontent.com/125903734/223694717-e823c218-3ba8-4cfc-8957-6a8e1d79710f.png)

**Comment by scholokov** [comment]
fixed

**Comment by ViktoriaZamkova** [comment]
checked
