### ISSUE TITLE
/20171027_cherkasy/No name section "road" in travel Черкаси.

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3240]
Steps to reproduce:
1.Open https://test.long-travel.live/20171027_cherkasy/
2. Scroll down to the video.

Actual result:
No name section "road"

Expected result:
Дорога: Київ - Черкаси 
 27.10.2017
(https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986%3A6&t=jNFh815uWZqa5QBr-0)

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177

![2023-03-09_14h09_52](https://user-images.githubusercontent.com/125903734/224020879-f0bbfc1c-e738-4f1c-8333-4e6997ff9d83.png)

![2023-03-09_13h25_16](https://user-images.githubusercontent.com/125903734/224020923-003f6e97-385f-4273-9d2a-9872c76b4524.png)

**Comment by scholokov** [comment]
fixed

**Comment by ViktoriaZamkova** [comment]
checked
