### ISSUE TITLE
/20171027_cherkasy/  No photos on the trip Черкаси 2017 on the page https://test.long-travel.live/travels/

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3241]
Steps to reproduce:
1.Open  https://test.long-travel.live/travels/
2. Scroll down to the travel Черкаси 2017

Actual result:
There is no travel photo above the header

Expected result:
Photo of the trip above the title

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177 

![2023-03-09_13h14_30](https://user-images.githubusercontent.com/125903734/224026115-ddad2717-351b-4059-8620-06da226ddfce.png)

**Comment by DmytroMarkulych** [comment]
@ViktoriaZamkova давайте перефразуємо Summary таким чином, щоб не використовувати There is.. 
І додамо атрибут Component в баг репорт

**Comment by ViktoriaZamkova** [comment]
@DmytroMarkulych Дякую, виправила.

**Comment by DmytroMarkulych** [comment]
@ViktoriaZamkova Якщо у нас мова йде про сторінку "travels" то не потрібно вказувати cherkasy в summary

**Comment by ViktoriaZamkova** [comment]
verified
