### ISSUE TITLE
/piryativ-mirgorod/ No travel photo above travel title in travel Пирятив – Миргород

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3242]
Steps to reproduce:
1. Open https://test.long-travel.live/travels/
2. Get down to travel Пирятив – Миргород

Actual result:
There is no travel photo above the header

Expected result:
The travel is present photo above the travel header

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177

![2023-03-09_14h50_50](https://user-images.githubusercontent.com/125903734/224028482-c9620288-cd1f-49f1-94ed-abf0f0dfd37d.png)

**Comment by DmytroMarkulych** [comment]
@ViktoriaZamkova давайте додамо атрибут Component в баг репорт

**Comment by ViktoriaZamkova** [comment]
додала

**Comment by ViktoriaZamkova** [comment]
@DmytroMarkulych виправила

**Comment by scholokov** [comment]
подорож відсутня у листі
https://github.com/scholokov/long-travel-2/wiki/4.2-Travels.List
була видалена
