### ISSUE TITLE
/piryativ-mirgorod/ Typo in city name in the preview

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3243]
Steps to reproduce:
1. Open https://test.long-travel.live/piryativ-mirgorod/  
2. Pay attention to the spelling of the city of Пирятив

Actual result:
Пирятив- Миргород

Expected result:
Пирятин -Миргород

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177

![2023-03-09_15h12_01](https://user-images.githubusercontent.com/125903734/224033739-13bdb724-0b3e-45e1-b6ce-bc6299045a34.png)

![2023-03-09_15h15_28](https://user-images.githubusercontent.com/125903734/224034564-147764db-43d9-4498-b8d7-0290cda1cd1b.png)

**Comment by DmytroMarkulych** [comment]
@ViktoriaZamkova старайтеся не використовувати слова типу incorrectly і тому подібні

**Comment by scholokov** [comment]
подорож відсутня у листі
https://github.com/scholokov/long-travel-2/wiki/4.2-Travels.List
була видалена
