### ISSUE TITLE
/piryativ-mirgorod/ No travel date near travel name

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3244]
Steps to reproduce:

1. Open https://test.long-travel.live/piryativ-mirgorod/
2. Pay attention to the travel name

Actual result:
No travel date near travel name

Expected result:
Пирятин -Миргород
04.11.2022

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177 

![2023-03-09_15h24_30](https://user-images.githubusercontent.com/125903734/224036556-781f682d-c520-476a-80d5-4a91a4b4c5f6.png)

**Comment by scholokov** [comment]
виправлено
це була некоректна подорож, тобто вона була відсутня у повному списку
https://github.com/scholokov/long-travel-2/wiki/4.2-Travels.List
була видалена
