### ISSUE TITLE
Grammatical error in last name  Godovanets

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3246]
Prerequisites:
Open: https://github.com/scholokov/long-travel-2/wiki/3.3-Team-page
Steps to reproduce:

1. Scroll to the section  Quality assurance:
2. QA_Nadiy Godovanets

Actual result: Nadiy Godovanets
Expected result: Nadiy Hodovanets

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104
![Hodovanets](https://user-images.githubusercontent.com/113175298/224068200-2be2b3c3-3d57-40db-8cb8-d711c30a28fc.png)

**Comment by scholokov** [comment]
fixed
