### ISSUE TITLE
/20170128_konotop/ Trip name does not meet requirements

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3247]
Steps to reproduce:

1.Open https://test.long-travel.live/20170128_konotop/
2. Pay attention to the name of the trip

Actual result:
20170128_konotop

Expected result:
Конотоп (https://github.com/scholokov/long-travel-2/wiki/4.2-Travels.List)

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177
![2023-03-10_13h02_01](https://user-images.githubusercontent.com/125903734/224300889-902b5f1e-48a6-45cb-bbb9-b8eeb4e037c8.png)

**Comment by scholokov** [comment]
fixed

**Comment by ViktoriaZamkova** [comment]
checked
