### ISSUE TITLE
/20170128_konotop/ The travel date does not match the date in the map legend

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3248]
Steps to reproduce:

1.Open https://test.long-travel.live/20170128_konotop/
2.Pay attention on map legend

Actual result:
Dec 25, 2022

Expected result:
Jan 28, 2017

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177
![2023-03-10_13h22_16](https://user-images.githubusercontent.com/125903734/224303801-211dde5f-031b-442f-b3e0-32d591d6871a.png)

**Comment by scholokov** [comment]
fixed

**Comment by ViktoriaZamkova** [comment]
checked
