### ISSUE TITLE
20150919_kiev_aviation_museum/In the Legend of the Map is the extra element "Museum" 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3249]
Steps to reproduce:
1. Open https://test.long-travel.live/20150919_kiev_aviation_museum/
2. Scroll down to the Legend of the Map
3. Pay attention to the text after preview foto in the Legend of the Map

Actual Result:
The extra element "Museum" is in the Legend of the Map

Expected Result:
The extra element "Museum" does not appear in the Legend of the Map

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![Присутній елемент_легенда_Map](https://user-images.githubusercontent.com/123776698/224304106-7ff6512c-8f56-4553-b878-49b9de989fab.png)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
passed

**Comment by ODrobik** [comment]
#2995
