### ISSUE TITLE
/20170128_konotop/ The distance between cities is not indicated in the map legend

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3250]
Steps to reproduce:

1.Open https://test.long-travel.live/20170128_konotop/
2.Pay attention on map legend

Actual result:
The distance is indicated near Konotop 259.3 km (from Kyiv to Konotop)

Expected result:
The distance is indicated near Konotop and Kyiv (km between cities)

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177

![2023-03-10_14h06_44](https://user-images.githubusercontent.com/125903734/224313795-703c2cfb-d91d-4abb-ae39-d13308c6f3fb.png)

![2023-03-10_14h05_50](https://user-images.githubusercontent.com/125903734/224313826-f7144fa4-d655-418f-8df2-a9e5bb4a674c.png)

**Comment by DmytroMarkulych** [comment]
@ViktoriaZamkova Давайте скріни додамо до Attachment та напишемо актуальний та очікуваний результати

**Comment by ViktoriaZamkova** [comment]
@DmytroMarkulych виправила

**Comment by ViktoriaZamkova** [comment]
verified
