### ISSUE TITLE
/20170128_konotop/ No design in the road section

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3254]
Steps to reproduce:

1.Open https://test.long-travel.live/20170128_konotop/
2.Pay attention on road section

Actual result:
No design in the road section

Expected result:
The design meets the requirements

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177

![2023-03-10_15h17_32](https://user-images.githubusercontent.com/125903734/224326378-94b4238c-1c72-4d79-9da7-9d6adc16a20c.png)

![2023-03-10_14h59_08](https://user-images.githubusercontent.com/125903734/224326394-1457abe4-5d0b-482f-ac77-e4c55e6c86d8.png)

**Comment by scholokov** [comment]
fixed

**Comment by ViktoriaZamkova** [comment]
15.03 22.35 No design in the road section.

**Comment by ViktoriaZamkova** [comment]
No design in the road section 

![2023-03-15_22h25_19](https://user-images.githubusercontent.com/125903734/225436404-e5136419-ce29-4c3d-a0c8-0a842c8654af.png)

**Comment by scholokov** [comment]
fixed

**Comment by ViktoriaZamkova** [comment]
the error is repeated

![2023-03-21_13h26_16](https://user-images.githubusercontent.com/125903734/226593231-6d9c1f3a-0438-415a-a9f6-befdad805818.png)

**Comment by DmitriiNasonov** [comment]
canceled. bug-report isn't actual
