### ISSUE TITLE
/20170128_konotop/ Travel name written in English

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3255]
Steps to reproduce:

1. Open https://test.long-travel.live/20170128_konotop/
2. Pay attention on video of the travel

Actual result:
 28.01.2017 01 Kiev- Konotop

Expected result:
28.01.2017 01 Київ - Конотоп

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177
![2023-03-10_15h40_14](https://user-images.githubusercontent.com/125903734/224330725-fa32099c-1f8a-4070-8ad7-ac5ddcee2a14.png)

![2023-03-10_15h43_35](https://user-images.githubusercontent.com/125903734/224331568-35fa5566-30ec-4076-8fc9-6ab838029db3.png)

**Comment by scholokov** [comment]
fixed
