### ISSUE TITLE
/20170128_konotop/ The travel publication date does not match the travel date

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3256]
Steps to reproduce:

1. Open https://test.long-travel.live/20170128_konotop/
2. Pay attention ondate publication of the travel

Actual result:
31.10.2022

Expected result:
2017.01.28

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177

![2023-03-10_16h50_15](https://user-images.githubusercontent.com/125903734/224346804-205b0b41-8644-43d5-a181-7cce0afb622f.png)

**Comment by scholokov** [comment]
fixed

**Comment by ViktoriaZamkova** [comment]
checked
