### ISSUE TITLE
20160710_0807_italy_odessa/The names of Lviv and Kyiv are in English

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3259]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the block: Road Lviv - Kyiv.
3. Pay attention to the names of Lviv and Kyiv in the left side of the block.

**Actual result:**
The names of Lviv and Kyiv are in English

**Expected result:**
The names of Lviv and Kyiv must be in Ukrainian

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/224512273-b17cb016-ba08-4a0a-91e1-8b4bc1cd696a.png)

![Image](https://user-images.githubusercontent.com/125134112/224448526-ab4ba5c3-ab8f-4724-a4e7-664268192130.png)

**Comment by DmytroMarkulych** [comment]
@prokopenkoga1977 
1. Summary описує проблему, тобто в нашому випадку, ми маємо вказати, що назва міст на англійській мові (тобто фактичний результат)
2. Атрибут Priority QA не виставляє, його ставить PM

**Comment by prokopenkoga1977** [comment]
Виправив

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
