### ISSUE TITLE
20160710_0807_italy_odessa/The size of the flag of Ukraine in the block Preparation for Odessa is 16x11

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3260]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the block: Preparation for Odessa.
3. Pay attention to the size of the flag of Ukraine in the right side of the block.

**Actual result:**
The size of the flag of Ukraine is 16x11 px

**Expected result:**
The size of the flag of Ukraine is 28x18 px

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Graphical requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=344%3A13&t=Z9tJ803tdjqTWnmE-0

![Image](https://user-images.githubusercontent.com/125134112/224511715-2bc2356f-d8ef-411c-97d8-078752d041c2.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/224511916-bc37d6e5-f361-45dc-8ed7-0fadfa9d5c05.png)

**Comment by DmytroMarkulych** [comment]
@prokopenkoga1977 
1. Додайте будь ласка посилання на специфікацію (у нашому випадку дизайн)
2. Атрибут Priority QA не виставляє, його ставить PM
3. Скріншот робиться всієї сторінки із виділенням проблеми. Приклад: 

![Image](https://user-images.githubusercontent.com/88647733/224487804-8aaa3c7f-98ff-4b71-9706-a5650c57287c.png)

**Comment by scholokov** [comment]
please retest

**Comment by DmitriiNasonov** [comment]
canceled. bug-report isn't an actual
