### ISSUE TITLE
20170722_boguslav/ The preview doesn't have picture

### ISSUE THREAD

**Issue by p4elobrek** [scholokov/long-travel-2#3263]
Prerequisites: 
Open https://test.long-travel.live/20170722_boguslav/
Steps to reproduce:

1. Pay attention to the preview picture

Actual result: The preview doesn't have picture
Expected result: The preview have picture
Environment: Windows 10 Home
system:
Browser: Google Chrome Version 110.0.5481.178
![1 issue](https://user-images.githubusercontent.com/123786969/224550101-4b94a071-c32d-404f-b152-49af5c2301da.JPG)

**Comment by DmytroMarkulych** [comment]
@p4elobrek 
1. В Summary ви вказуєте "pictures"- але там має бути одне фото
2. Виправіть будь ласка граматичні помилки в Actual Expected results

**Comment by p4elobrek** [comment]
pass
