### ISSUE TITLE
20170722_boguslav/ The travel date is missing in the preview

### ISSUE THREAD

**Issue by p4elobrek** [scholokov/long-travel-2#3264]
Prerequisites:
Open https://test.long-travel.live/20170722_boguslav/

Steps to reproduce:
1. Pay attention  to the date in preview

Actual result: The travel date is missing in the preview
Expected result: The travel date is in the preview

Environment: Windows 10 Home
system:
Browser: Google Chrome Version 110.0.5481.178
![1 issue](https://user-images.githubusercontent.com/123786969/224550791-bc7e52bc-593c-4a4d-b3e0-69d0705c4945.JPG)

**Comment by DmytroMarkulych** [comment]
@p4elobrek Давайте перефразуємо summary, actual, expected results таким чином, щоб не вживати  there are

**Comment by DmytroMarkulych** [comment]
@p4elobrek В Summary ми описуємо саму проблему (це швидше актуальний результат ніж очікуваний).

**Comment by scholokov** [comment]
fixed

**Comment by p4elobrek** [comment]
pass
