### ISSUE TITLE
20170722_boguslav/ Inscription above and below the map in Russian

### ISSUE THREAD

**Issue by p4elobrek** [scholokov/long-travel-2#3265]
Prerequisites:
Open https://test.long-travel.live/20170722_boguslav/

Steps to reproduce:

1. Pay attention to the Inscription above and below the map

Actual result: Inscription above and below the map in Russian
Expected result: Inscription above and below the map in Ukrainian

Environment: Windows 10 Home
system:
Browser: Google Chrome Version 110.0.5481.178

![2 issue](https://user-images.githubusercontent.com/123786969/224557642-e4fed2ef-bb78-46c3-8a6d-434bc33d4856.JPG)

**Comment by p4elobrek** [comment]
![image](https://user-images.githubusercontent.com/123786969/224557736-a9870681-f687-43da-8658-f08d33f533b0.png)
Це мій девайс, писати що це десктоп чи таблет?

**Comment by DmytroMarkulych** [comment]
@p4elobrek цей дефект буде відтворюватися на всіх девайсах. Ви можете це перевірити за допомогою DevTools

**Comment by p4elobrek** [comment]
ок

**Comment by DmytroMarkulych** [comment]
@p4elobrek скріншот знаходиться в середині Очікуваног результату

**Comment by scholokov** [comment]
fixed

**Comment by p4elobrek** [comment]
pass
