### ISSUE TITLE
20170722_boguslav/ The publication date correspond to the start date of the trip

### ISSUE THREAD

**Issue by TetianaSulima** [scholokov/long-travel-2#3266]
Prerequisites:
Open https://test.long-travel.live/20170722_boguslav/
Steps to reproduce:

1. Scroll down to the footer

2. Pay attention to the Publication date

Actual result: The publication date doesn't correspond to the start date of the trip 03.08.2021
Expected result: The publication date correspond to the start date of the trip 22.07.2012

Specification: https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0

Environment: Windows 10 Home
system:
Browser: Google Chrome Version 110.0.5481.178

![image](https://user-images.githubusercontent.com/123786969/224558553-d0e55c38-bae6-4226-98e5-abc7587d4380.png)

**Comment by DmytroMarkulych** [comment]
@p4elobrek Краще не використовувати слова типу not correct, incorrect і т.д. Краще вкажіть фактично що представлено на сторінці. Теж стосується Actual Expected results. Якщо у вас є доступ до специфікації, то краще на її основі вкажіть конкретну інформацію

**Comment by DmytroMarkulych** [comment]
![Image](https://user-images.githubusercontent.com/88647733/225010227-1ad96979-3d22-4bf9-96d7-2ca45ca17efe.png)

**Comment by p4elobrek** [comment]
![image](https://user-images.githubusercontent.com/123786969/226944727-e04460d3-6964-40c6-8298-e0ee0a129d82.png)

рік забули поміняти

**Comment by DmytroMarkulych** [comment]
@p4elobrek Додайте посилання на специфікацію де вказано як має вказуватися дата публікації

**Comment by scholokov** [comment]
fixed

**Comment by TetianaSulima** [comment]
![image](https://user-images.githubusercontent.com/123786969/230241253-5fd6f74f-c751-4a76-9f66-c96a2e290d08.png)

**Comment by DmytroMarkulych** [comment]
@tatianasheremet Краще вказати, що дефект відтворюється

**Comment by TetianaSulima** [comment]
дефект відтворюється

**Comment by TetianaSulima** [comment]
Bug reprodused

Expected result: The publication date correspond to the start date of the trip 22.07.2012

![image](https://user-images.githubusercontent.com/123786969/232839779-9f02f96d-815a-4d41-936d-c738c876e000.png)

**Comment by scholokov** [comment]
@TetianaSulima 
якщо додаєте коментар, не забувайте змінювати статус :)

**Comment by scholokov** [comment]
виправлено
