### ISSUE TITLE
/konotop/ The travel title the does not meet the requirements

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3272]
Steps to reproduce:

1.Open https://test.long-travel.live/konotop/
2.Chek the travel title

Actual result:
Конотопський ДЮСШ

Expected result:
Конотоп 

Attachments:
https://github.com/scholokov/long-travel-2/wiki/4.2-Travels.List

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177

![2023-03-13_15h46_59](https://user-images.githubusercontent.com/125903734/224720642-07c99383-1814-4f42-9f65-1fd73ec44c1b.png)

![2023-03-13_15h38_03](https://user-images.githubusercontent.com/125903734/224718172-201febb5-fd21-4ade-aa9d-8d18a7889ffc.png)

**Comment by ViktoriaZamkova** [comment]
додала розділ Attachments

**Comment by scholokov** [comment]
please retest on the correct travel:
https://test.long-travel.live/20170128_konotop/

current link is wrong and was deleted
https://test.long-travel.live/konotop/

**Comment by ViktoriaZamkova** [comment]
verified
