### ISSUE TITLE
/konotop/  No photos of the trip in the preview

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3273]
Steps to reproduce:

1.Open https://test.long-travel.live/konotop/
2.Chek the Preview

Actual result:
No photos of the trip in the preview

Expected result:
Photo of the trip in the preview

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177

![2023-03-13_15h56_31](https://user-images.githubusercontent.com/125903734/224723190-ab2760a4-2934-4d76-8017-b1194caaef01.png)

**Comment by scholokov** [comment]
please retest on the correct travel:
https://test.long-travel.live/20170128_konotop/

current link is wrong and was deleted
https://test.long-travel.live/konotop/

**Comment by ViktoriaZamkova** [comment]
verified
