### ISSUE TITLE
20160710_0807_italy_odessa/The locality name of the hotel Kopa is missed in the block "Готель Копа"

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3274]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the block Hotel Kopa (Готель Копа).

3. Pay attention to the absence of a locality name of the hotel Kopa in the left side of the block.

**Actual result:**
The locality name of the hotel Kopa is missed.

**Expected result:**
The locality name of the hotel Kopa must be in the block "Готель Копа"

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/2.4-Travel.Standard-Blocks#hotel

![Image](https://user-images.githubusercontent.com/125134112/224725659-c25f6f49-94a1-480e-84d0-3d0db6a7d3bc.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/224726748-7f55608c-2e73-499e-9690-ed49d4b4170d.png)

**Comment by scholokov** [comment]
fixed
