### ISSUE TITLE
/konotop/ Placement of the text does not meet the requirements

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3277]
Steps to reproduce:
1.Open https://test.long-travel.live/konotop/
2.Chek the Preview

Actual result:
In the preview is the text of the  Конотопський ДЮСШ

Expected result:
In the preview is the text of the Конотоп, Сумская область, Украина  28.01.2017 

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177

![2023-03-13_16h17_05](https://user-images.githubusercontent.com/125903734/224728411-107ddba9-59bb-44a2-96f2-3487fc700585.png)

**Comment by DmytroMarkulych** [comment]
![Image](https://user-images.githubusercontent.com/88647733/224733770-790105bc-6e29-43ea-9df3-b43be7f6d024.png)

**Comment by scholokov** [comment]
please retest on the correct travel:
https://test.long-travel.live/20170128_konotop/

current link is wrong and was deleted
https://test.long-travel.live/konotop/

**Comment by ViktoriaZamkova** [comment]
verified
