### ISSUE TITLE
/20211029_0911_portugal/  The trip name does not meet the requirements

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3278]
Steps to reproduce:

1.Open https://test.long-travel.live/20211029_0911_portugal/
2.Chek the Preview

Actual result:
Lisboa – Penhas da Saúde – Porto – Lisboa-29.10-09.11.2021

Expected result:
Lisboa - Aveiro - Porto - Nazare

Attachments:
https://github.com/scholokov/long-travel-2/wiki/4.2-Travels.List

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177

![2023-03-13_16h30_07](https://user-images.githubusercontent.com/125903734/224731951-41dfe877-f8f1-4d2c-a31a-325f4d0973ae.png)

![2023-03-13_16h31_48](https://user-images.githubusercontent.com/125903734/224732462-d4ca8674-0f40-4f02-ac2f-e48432fdbdfb.png)

**Comment by DmytroMarkulych** [comment]
@ViktoriaZamkova лінку на специфікацію винесіть як додаткова інформація

**Comment by ViktoriaZamkova** [comment]
додала розділ Attachments

**Comment by ViktoriaZamkova** [comment]
verified
