### ISSUE TITLE
/20211029_0911_portugal/ No country flag in the preview

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3281]
Steps to reproduce:

1.Open https://test.long-travel.live/20211029_0911_portugal/
2.Chek the Preview

Actual result:
No country flag in the preview

Expected result:
The flag of Portugal in the preview on the right

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177
![2023-03-13_16h38_01](https://user-images.githubusercontent.com/125903734/224751149-3c7fd228-6551-43e1-8a9a-3a470414333a.png)

**Comment by scholokov** [comment]
fixed

**Comment by ViktoriaZamkova** [comment]
verified
