### ISSUE TITLE
20170722_boguslav/ Missing link in the map legend

### ISSUE THREAD

**Issue by p4elobrek** [scholokov/long-travel-2#3282]
Prerequisites:
Open https://test.long-travel.live/20170722_boguslav/
Steps to reproduce:

1. Pay attention to the map legend.   
 
Actual result: Missing link in the map legend
Expected result: An active element Link  present in the map legend

Environment: Windows 10 Home
system:
Browser: Google Chrome Version 110.0.5481.178

![b1](https://user-images.githubusercontent.com/123786969/224858047-2098ff8f-2acd-4ac3-a04e-be8c12f2b704.png)

**Comment by DmytroMarkulych** [comment]
@p4elobrek Можна не вказувати Must, просто констатувати що лінка є в легенді

**Comment by scholokov** [comment]
fixed

**Comment by p4elobrek** [comment]
pass
