### ISSUE TITLE
20170715_boguslav/ Missing picture in the preview 

### ISSUE THREAD

**Issue by TetianaSulima** [scholokov/long-travel-2#3285]
Prerequisites:
Open https://test.long-travel.live/20170715_boguslav/
Steps to reproduce:

1. Pay attention to the preview picture

Actual result: The picture in the preview 
Expected result: Missing picture in the preview 

Environment: Windows 10 Home
system:
Browser: Google Chrome Version 110.0.5481.178

![image](https://user-images.githubusercontent.com/123786969/224873541-c99009ab-a795-424a-ae14-4a6a7cca6335.png)

**Comment by DmytroMarkulych** [comment]
@p4elobrek Давай перефразуємо Summary щоб воно відповідало на питання Де? Що? Коли?

**Comment by scholokov** [comment]
fixed

**Comment by p4elobrek** [comment]
![image](https://user-images.githubusercontent.com/123786969/226969383-ff9f7164-4430-40a2-9cd9-f18fde43a4fa.png)

картинка дуже темна та зливається з фоном

**Comment by scholokov** [comment]
нова помилка не відповідає початковій. потрібен новий баг

**Comment by scholokov** [comment]
якщо є сумніви, завжди можна спитати :)
