### ISSUE TITLE
20160710_0807_italy_odessa/The locality name of the hotel Patria is missed in the block "Hotel Patria"

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3291]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the block Hotel Patria.

3. Pay attention to the absence of a locality name of the hotel Patria in the left side of the block.

**Actual result:**
The locality name of the hotel Patria is missed.

**Expected result:**
The locality name of the hotel Patria must be in the block "Hotel Patria"

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/2.4-Travel.Standard-Blocks#hotel

![Image](https://user-images.githubusercontent.com/125134112/224984113-c118b021-740e-4c61-9a8c-79b6dc323c29.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/224985187-7d2a474b-62a2-46e8-890e-2d2bb3709327.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
