### ISSUE TITLE
20160710_0807_italy_odessa/The hotel visit date in the block Hotel Patria is missed

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3293]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the block Hotel Patria.

3. Pay attention to the hotel visit date in the left side of the block.

**Actual result:**
The hotel visit date in the block Hotel Patria is missed.

**Expected result:**
The hotel visit date in the block Hotel Patria must be.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/2.4-Travel.Standard-Blocks#hotel

![Image](https://user-images.githubusercontent.com/125134112/224990622-72926a1d-4843-4087-bb68-79873d297664.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/224990776-926c2676-8c94-4aa8-9b62-c77b0cdf3f92.png)

**Comment by prokopenkoga1977** [comment]
@scholokov @ABatalov The bug is not fixed. The date format of travel date must be DD.MM.YYYY-DD.MM.YYYY. Actual result: DD.MM.-DD.MM.YYYY


![Image](https://user-images.githubusercontent.com/125134112/226473022-73b42bc6-d6dc-4598-bbdd-444aeef6a34e.png)

**Comment by scholokov** [comment]
поточна помилка не відповідає попередній. це має бути новий баг

**Comment by prokopenkoga1977** [comment]
Ok. I closed this bug report and will create a new one.
