### ISSUE TITLE
20160710_0807_italy_odessa/The size of the flag of Ukraine in the block: Hotel Patria is 16x11

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3294]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the block Hotel Patria.
3. Pay attention to the size of the flag of Ukraine in the right side of the bloc

**Actual result:**
The size of the flag of Ukraine is 16x11 px
**Expected result:**
The size of the flag of Ukraine is 28x18 px

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Graphical requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=344%3A13&t=Z9tJ803tdjqTWnmE-0

![Image](https://user-images.githubusercontent.com/125134112/224991742-1fe80f08-ff16-4f13-b552-064a6615305f.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/224994024-4abcf990-89b1-45bf-9587-406dca0a5600.png)

**Comment by DmytroMarkulych** [comment]
@prokopenkoga1977 

![Image](https://user-images.githubusercontent.com/88647733/225017340-9c0ff7e9-e9ad-441a-abaf-8388c2e28311.png)

трішки поїхало

**Comment by prokopenkoga1977** [comment]
Виправив

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
