### ISSUE TITLE
20171027_cherkasy The flag of Ukraine is not represented in the right side of the 3rd preview

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3295]
**Pre-conditions:**
Open https://test.long-travel.live/20171027_cherkasy/

**Steps to reproduce:**

1.Find 3st preview.
2.Pay attention to the absence of the flag of Ukraine in the right side of the 3rd preview.

**Actual result:**
The flag of Ukraine is not represented in the right side of the 3rd preview

**Expected result:**
The flag of Ukraine is represented in the right side of the 3rd preview according [requirements](https://github.com/scholokov/long-travel-2/wiki/2.3-Travel.Content).

**Environment:**

Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![llTFuVugm0](https://user-images.githubusercontent.com/123729744/225228930-0f16c3fc-5b10-4157-bd61-46a061a5d891.png)

**Comment by scholokov** [comment]
fixed
