### ISSUE TITLE
20171027_cherkasy The date format of the 2nd Travel.YoutubeVideo  is DD.ММ.YYYY

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3297]
**Pre-conditions:**
Open https://test.long-travel.live/20171027_cherkasy/

**Steps to reproduce:**

1.Find Travel.YoutubeVideo Gallery.
2. Pay attantion to the  date format.

**Actual result:**
The date format of the 2nd  Travel.YoutubeVideo  is DD.ММ.YYYY

**Expected result:**
The date format of the 2nd Travel.YoutubeVideo  is YYYY.ММ.DD according [requirements.](https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery)

**Environment:**

Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![NfAK1Czjt6](https://user-images.githubusercontent.com/123729744/225235673-649afc9f-0c81-4675-9b8b-87a8f7047498.png)

**Comment by scholokov** [comment]
fixed

**Comment by OlhaHutsman** [comment]
@scholokov verified
