### ISSUE TITLE
20171027_cherkasy Multi tag "traveling by car" is not reproduced.

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3300]
**Pre-conditions:**
Open https://test.long-travel.live/20171027_cherkasy/

**Steps to reproduce:**

1.Scroll down to the bottom of the Travel page.
2.Pay attention- multi tag "traveling by car" is not reproduced on the Travel page.

**Actual result:**
Multi tag "traveling by car" is not reproduced.

**Expected result:**
Multi tag "traveling by car" is reproduced .

**Environment:**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![K24znIvUV3](https://user-images.githubusercontent.com/123729744/225242939-0af3425f-441b-4354-a38d-d323c2c305b7.png)

**Comment by DmytroMarkulych** [comment]
@OlhaHutsman і лінку на специфікацію приберемо із очікуваного результату

**Comment by OlhaHutsman** [comment]
@DmytroMarkulych  edited
