### ISSUE TITLE
20160710_0807_italy_odessa/The travel date in Lyman (Лиман) block is missed

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3303]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to Lyman block (Лиман).

3. Pay attention to the absence of the travel date in the left side of the block.

**Actual result:**
The travel date in Lyman block is missed

**Expected result:**
The travel date in Lyman block must be present

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/2.4-Travel.Standard-Blocks#village

![Image](https://user-images.githubusercontent.com/125134112/225282219-c714e377-6299-48cf-9868-a3974f35e4bb.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/225283229-e4a7914a-eff0-4999-9da3-5ec857da4e33.png)

**Comment by DmytroMarkulych** [comment]
@prokopenkoga1977 Давайте перефразуємо Expected result, щоб він став більш зрозумілішим

**Comment by prokopenkoga1977** [comment]
Виправив

**Comment by prokopenkoga1977** [comment]
Ok. I'm closing this bug report and I'll create a new one.
