### ISSUE TITLE
20160710_0807_italy_odessa/The name of Black Sea is in Russian

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3305]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the block: Black Sea (Чорне море).
3. Pay attention to the name of Black Sea in the left side of the block.

**Actual result:**
The name of Black Sea is in Russian

**Expected result:**
The name of Black Sea must be in Ukrainian

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/1.2-Global.Language

![Image](https://user-images.githubusercontent.com/125134112/225289791-e5b25d14-c248-4f86-988b-0b0049288d34.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/225290850-57562e25-66a5-4628-b88d-f5f17bbe2b35.png)

**Comment by scholokov** [comment]
fixed

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
