### ISSUE TITLE
20160710_0807_italy_odessa/The travel date in the block Black Sea (Чорне море) is "27.07.-06.08.2016"

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3306]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the block Black Sea (Чорне море).

3. Pay attention to the travel date in the left side of the block.

**Actual result:**
The travel date  in the block Black Sea (Чорне море) is "27.07.-06.08.2016"

**Expected result:**
The travel date in the block Black Sea (Чорне море) must be "27.07.2016-06.08.2016"

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/2.4-Travel.Standard-Blocks#beach

![Image](https://user-images.githubusercontent.com/125134112/225293296-559825bf-e30f-47ce-8e90-196df4b7a82f.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/225293449-16bfbad5-b90f-4405-99e6-bf35897e2ccb.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
