### ISSUE TITLE
20160710_0807_italy_odessa/The size of the flag of Ukraine in the block: Black Sea (Чорне море) is 16x11

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3308]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the block Black Sea (Чорне море).
3. Pay attention to the size of the flag of Ukraine in the right side of the block.

**Actual result:**
The size of the flag of Ukraine is 16x11 px

**Expected result:**
The size of the flag of Ukraine is 28x18 px

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Graphical requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=344%3A13&t=Z9tJ803tdjqTWnmE-0

![Image](https://user-images.githubusercontent.com/125134112/225297784-8fcc3edb-3198-48ec-a059-c5a1640269b8.png)

**Attachments:**

![Image](https://user-images.githubusercontent.com/125134112/225298995-99897183-4e3e-4b97-97dd-d5ed72aaf6fe.png)

**Comment by scholokov** [comment]
fixed
