### ISSUE TITLE
20160710_0807_italy_odessa/The travel date of the video Sergiivka-Kyiv is 07.08.2016

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3312]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the block "Roud Sergiivka-Kyiv".

3. Pay attention to the travel date of the video.

**Actual result:**
The travel date of the video Sergiivka-Kyiv is 07.08.2016

**Expected result:**
The travel date of the video Sergiivka-Kyiv must be 2016.08.07

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery

![Image](https://user-images.githubusercontent.com/125134112/225599373-3ceaa9e8-711c-4eca-b6bc-f64b04d37fbd.png)

**Attachments:**

![Image](https://user-images.githubusercontent.com/125134112/225600215-47a8f446-0634-4dae-852f-2b0ff37d94fd.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
@scholokov @ABatalov The bug is not fix


![Image](https://user-images.githubusercontent.com/125134112/226393645-0d33c618-a681-4117-84c4-d349b2f954f1.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
