### ISSUE TITLE
20150919_kiev_aviation_museum/ In the map with routes in the List of travel does not match the name of the travel in 4.2 Travels.List

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3315]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20150919_kiev_aviation_museum/
2. Pay attention to the name of travel in the drop-down list.

**Actual Result:**
The name of travel is "20150919_Kiev_Aviation_Museum"

**Expected Result:**
The name of travel is "Державний музей авіації осінь 2015"

**Environment:**
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

**Attachment:**
![назва_список_карта](https://user-images.githubusercontent.com/123776698/225663132-7d7239ef-f644-491c-a969-e753feef151d.png)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
#2995
