### ISSUE TITLE
/20220124_0128_netherlands/ The name of the trip does not match the documentation

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3317]
Steps to reproduce:

1.Open https://test.long-travel.live/20220124_0128_netherlands/
2.Chek the travel tittle

Actual result:
Eindhoven – Den Haag – Amsterdam – Eindhoven
24.01.2022-28.01.2022

Expected result:
Eindhoven - Den Haag - Amsterdam
24.01.2022 - 28.01.2022

Attachment:
https://github.com/scholokov/long-travel-2/wiki/4.2-Travels.List

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177
![2023-03-17_23h16_22](https://user-images.githubusercontent.com/125903734/226057416-53b251d9-788b-4b69-b3ec-8df5a2fe0d23.png)

**Comment by scholokov** [comment]
fixed
