### ISSUE TITLE
20150919_kiev_aviation_museum/In the 2nd Preview block of travel is the extra element "Україна"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3318]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20150919_kiev_aviation_museum/
2. Scroll down to the 2nd Preview block of travel
3. Pay attention to the structure of the 2nd Preview block

**Actual Result:**
The extra element "Україна" is in the 2nd Preview block of travel

Expected Result:
The extra element "Україна" does not appear in the 2nd Preview block of travel

**Environment:**
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

**Attachment:**
![structura](https://user-images.githubusercontent.com/123776698/226089520-add54514-177c-4868-b03c-385044cef15b.png)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
passed

**Comment by ODrobik** [comment]
#2995
