### ISSUE TITLE
20160710_0807_italy_odessa/The travel name of the fifth video gallery of Black Sea block is in English

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3324]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the block "Black Sea".

3. Pay attention to the travel name of the fifth video.

**Actual result:**
The travel name of the fifth videoof Black Sea block is in English

**Expected result:**
The travel name of the fifth video of Black Sea block must be in Ukrainian (Сергіївка, Атракціон 2)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery

![Image](https://user-images.githubusercontent.com/125134112/226325008-65385c8f-a6c9-4514-8212-956e1a630c75.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/226326416-ed3b76de-fed3-4582-9947-186e3d67701c.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
