### ISSUE TITLE
20160710_0807_italy_odessa/The travel name of the sixth video gallery of Black Sea block is in English

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3325]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the block "Black Sea".

3. Pay attention to the travel name of the sixth video.

**Actual result:**
The travel name of the sixth video of Black Sea block is in English

**Expected result:**
The travel name of the fifth video of Black Sea block must be in Ukrainian (Сергіївка, Паром)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery

![Image](https://user-images.githubusercontent.com/125134112/226327972-7abed246-7ca1-420f-b6e1-d48b7f26043a.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/226328900-c1cd57b3-4aa0-4cde-8551-bc9298ee4fc9.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
