### ISSUE TITLE
20160710_0807_italy_odessa/The date format of the seventh video gallery of Black Sea block is 03.08.2016 (DD.MM.YYYY)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3326]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the block "Black Sea".

3. Pay attention to the date format of the seventh video.

**Actual result:**
The date format of the seventh video gallery of Black Sea block is 03.08.2016 (DD.MM.YYYY)

**Expected result:**
The date format of the seventh video gallery of Black Sea block must be 2016.08.03. (YYYY.MM.DD.)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery

![Image](https://user-images.githubusercontent.com/125134112/226334785-f053dabd-6246-4c20-b211-435718d6bc02.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/226335781-1f99d012-aabf-4f3e-9f44-84232fb39bbb.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
