### ISSUE TITLE
20160710_0807_italy_odessa/The size of the flag of Ukraine of "Welcome to fairy tale" block is 16x11

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3327]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to "Welcome to fairy tale" block.
3. Pay attention to the size of the flag of Ukraine in the right side of the block.

**Actual result:**
The size of the flag of Ukraine is 16x11 px
**Expected result:**
The size of the flag of Ukraine is 28x18 px

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Graphical requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=344%3A13&t=Z9tJ803tdjqTWnmE-0

![Image](https://user-images.githubusercontent.com/125134112/226571051-5dd35ede-a987-4c2f-af72-f00e7a4569b7.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/226572911-559d7939-347a-4ad5-aef1-54749adfb294.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
