### ISSUE TITLE
20160710_0807_italy_odessa/The travel name of "Welcome to fairy tale" (Добро пожаловать в сказку) is in Russian

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3328]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to "Welcome to fairy tale" block.
3. Pay attention to the travel name of the block in the left side.

**Actual result:**
The travel name is in Russian (Добро пожаловать в сказку).

**Expected result:**
The travel name of the block must be in Ukrainian

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/1.2-Global.Language

![Image](https://user-images.githubusercontent.com/125134112/226576410-ee536968-4032-4bbd-9a90-d189a6958c8d.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/226576995-f232ac43-c95c-4735-a223-ed2f749d5f60.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
