### ISSUE TITLE
20160710_0807_italy_odessa/The locality name of the park "Welcome to fairy tale" is missed

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3329]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to "Welcome to fairy tale" block.

3. Pay attention to the absence of a locality name of the park "Welcome to fairy tale" in the left side of the block.

**Actual result:**
The locality name of the park "Welcome to fairy tale" is missed.

**Expected result:**
The locality name of the park "Welcome to fairy tale" must be in "Welcome to fairy tale" block.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/2.4-Travel.Standard-Blocks#park

![Image](https://user-images.githubusercontent.com/125134112/226579441-dc485575-75c7-45b7-8507-55564ebc9bec.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/226579667-3239d94a-d4f1-4961-85ea-11c4020932b2.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
