### ISSUE TITLE
20171027_cherkasy  The flag of Ukraine is not reproduced in the right side  of the 2nd block "Дорога".

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3330]
**Pre-conditions:**
Open https://test.long-travel.live/20171027_cherkasy/

**Steps to reproduce:**

1.Find 2nd block "Дорога".
2.Pay attention to the absence of the flag of Ukraine in the right side  of the 2nd block "Дорога".

**Actual result:**
The flag of Ukraine is not reproduced in the right side  of the 2nd block "Дорога".

**Expected result:**
The flag of Ukraine is in the right side  of the 2nd block "Дорога" according [requirements](https://github.com/scholokov/long-travel-2/wiki/2.3-Travel.Content).

**Environment:**

Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![n3sB0awW1F](https://user-images.githubusercontent.com/123729744/226704491-b7d5c89b-1149-4c81-92a9-b2477f38f717.png)

**Comment by scholokov** [comment]
fixed

**Comment by OlhaHutsman** [comment]
@scholokov verified
