### ISSUE TITLE
/20220124_0128_netherlands/ No travel date and country flag in the Preparation section

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3331]
Steps to reproduce:
1.Open https://test.long-travel.live/20220124_0128_netherlands/
2.Chek the Preparation section

Actual result:
No travel date and country flag in the Preparation section

Expected result:
The date of the trip is under the name, the flag is on the right

Attachment:
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?t=0fRipzc5LkXGV8MI-0

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177
![2023-03-21_23h42_14](https://user-images.githubusercontent.com/125903734/226748670-dce5a232-f1a9-4800-810d-5ec97e01b91a.png)
![2023-03-21_23h41_00](https://user-images.githubusercontent.com/125903734/226748732-672d394c-54ae-4431-8ef8-754a232c0b2b.png)

**Comment by scholokov** [comment]
проблема у тому що, дизайн не відповідає вимогам
https://github.com/scholokov/long-travel-2/wiki/2.4-Travel.Standard-Blocks
можна створити баги на дизайн
