### ISSUE TITLE
20160710_0807_italy_odessa/The flag of Ukraine is missed in the Road Kyiv-Nyirbator block

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3332]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the Road Kyiv-Nyirbator block.

3. Pay attention to the absence of the flag of Ukraine in the right side of the block.

**Actual result:**
The flag of Ukraine is missed in the Road Kyiv-Nyirbator block.

**Expected result:**
The flag of Ukraine must be in the Road Kyiv-Nyirbator block.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/2.-Travel.Structure

![Image](https://user-images.githubusercontent.com/125134112/226871924-74262a42-19bd-41f6-b70d-a753ae6c6448.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/226876295-d6e1712e-3d34-402f-b525-d392e4164dfe.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
