### ISSUE TITLE
20160710_0807_italy_odessa/The name of the settlements in the first line of Road Kyiv-Nyirbator block

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3333]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the Road Kyiv-Nyirbator block.

3. Pay attention to the name of the settlements in the left side of the block.

**Actual result:**
The name of the settlements in the first line of the block.

**Expected result:**
The name of the settlements must be in the second line.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/2.4-Travel.Standard-Blocks#road

![Image](https://user-images.githubusercontent.com/125134112/226879864-eb541aa9-2376-4d49-8fff-1a7034cd1fda.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/226880753-19a80619-dd38-4d88-8830-62f8d1836194.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
