### ISSUE TITLE
20160710_0807_italy_odessa/The travel name of the video gallery of Road Kyiv-Nyirbator is in English

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3334]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the Road Kyiv-Nyirbator block.

3. Pay attention to the travel name of the video gallery.

**Actual result:**
The travel name of the video gallery of the Road Kyiv-Nyirbator is in English

**Expected result:**
The travel name of the video gallery of the Road Kyiv-Nyirbator must bein the language of the respective country (Kyiv - in Ukrainian; Nyirbator - in Hungarian)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery

![Image](https://user-images.githubusercontent.com/125134112/226883446-5080ed1e-4d2d-4fae-bbe6-a8a287ad52af.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/226884294-4f6e04b7-9e23-42d6-94a5-bb752266f219.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
