### ISSUE TITLE
20160710_0807_italy_odessa/The travel name of the second video gallery of Road Kyiv-Nyirbator is in English

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3336]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the Road Kyiv-Nyirbator block.

3. Pay attention to the travel name of the second video gallery.

**Actual result:**
The travel name of the second video gallery of the Road Kyiv-Nyirbator is in English

**Expected result:**
The travel name of the second video gallery of the Road Kyiv-Nyirbator must be in the language of the respective country (Kyiv - in Ukrainian; Nyirbator, Hungary - in Hungarian)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery

![Image](https://user-images.githubusercontent.com/125134112/226888586-63d4f4a0-174a-45d5-8905-011c394f8207.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/226889673-f8ba447b-2e0b-4c51-a26f-00545525e4db.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
