### ISSUE TITLE
20160710_0807_italy_odessa/The date format of the first video gallery of the Road Kyiv-Nyirbator is 10.07.2016 (DD.MM.YYYY)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3338]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the Road Kyiv-Nyirbator block.

3. Pay attention to the date format of the first video gallery.

**Actual result:**
The date format of the first video gallery of the Road Kyiv-Nyirbator is 10.07.2016 (DD.MM.YYYY)

**Expected result:**
The date format of the first video gallery of the Road Kyiv-Nyirbator must be 2016.07.10. (YYYY.MM.DD.)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery

![Image](https://user-images.githubusercontent.com/125134112/226891905-02d34b3d-eb3c-4021-b076-3306fe615113.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/226892028-e61d285a-37e0-4c1b-b745-9633aebda17d.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
