### ISSUE TITLE
20160710_0807_italy_odessa/The date format of the second video gallery of the Road Kyiv-Nyirbator is 10.07.2016 (DD.MM.YYYY)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3339]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the Road Kyiv-Nyirbator block.

3. Pay attention to the date format of the second video gallery.

**Actual result:**
The date format of the second video gallery of the Road Kyiv-Nyirbator is 10.07.2016 (DD.MM.YYYY)

**Expected result:**
The date format of the second video gallery of the Road Kyiv-Nyirbator must be 2016.07.10. (YYYY.MM.DD.)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery

![Image](https://user-images.githubusercontent.com/125134112/226893323-87ad8dcf-1bf1-47f6-952b-7914b45fd77b.png)

**Attachment:** 

![Image](https://user-images.githubusercontent.com/125134112/226893077-bfdef237-41ac-4c50-b6bc-bb47dbca49eb.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
