### ISSUE TITLE
wiki/2.4-Travel.Standard-Blocks in the table same name of columns

### ISSUE THREAD

**Issue by TetianaSulima** [scholokov/long-travel-2#3340]
Prerequisites:
Open https://github.com/scholokov/long-travel-2/wiki/2.4-Travel.Standard-Blocks

Steps to reproduce:

1. Pay attention to the name of columns

Actual result: Same name of columns
Expected result: Different name of columns

Environment: Windows 10 Home
system:
Browser: Google Chrome Version 110.0.5481.178

![image](https://user-images.githubusercontent.com/123786969/227079758-b83ea8de-8129-479a-b06d-c798108c98f9.png)

**Comment by p4elobrek** [comment]
> @p4elobrek Власне це не дефект

А що?
