### ISSUE TITLE
wiki/2.4-Travel.Standard-Blocks in the table have name in English

### ISSUE THREAD

**Issue by TetianaSulima** [scholokov/long-travel-2#3341]
Prerequisites:
Open https://github.com/scholokov/long-travel-2/wiki/2.4-Travel.Standard-Blocks

Steps to reproduce:

1. Pay attention to the name of tables

Actual result: name of tables in English
Expected result: name of tables in Ukrainian

Environment: Windows 10 Home
system:
Browser: Google Chrome Version 110.0.5481.178

![image](https://user-images.githubusercontent.com/123786969/227081514-ae9ae110-eef5-47e5-baa3-cb14d50caea3.png)

**Comment by DmytroMarkulych** [comment]
@p4elobrek швидше за все це не є дефектом

**Comment by TetianaSulima** [comment]
то закривати баг?
