### ISSUE TITLE
20170722_boguslav/ Extra inscription before ''Дорога" block

### ISSUE THREAD

**Issue by TetianaSulima** [scholokov/long-travel-2#3342]
Prerequisites:
Open https://test.long-travel.live/20170722_boguslav/

Steps to reproduce:
1. Pay attention to the extra inscription "Дорога Київ – Богуслав" before ''Дорога" block

Actual result: Extra inscription "Дорога Київ – Богуслав" before ''Дорога" block
Expected result: No inscription  before  ''Дорога" block

Specification :
 https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0

system:
Browser: Google Chrome Version 110.0.5481.178

![image](https://user-images.githubusercontent.com/123786969/227084680-8aa37f51-ba45-4791-8868-60a34ae0cc4b.png)

**Comment by DmytroMarkulych** [comment]
@p4elobrek додайте лінку на специфікацію
