### ISSUE TITLE
20171027_cherkasy The text in the legend of the maps is in English.

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3347]
**Pre-conditions:**
Open https://test.long-travel.live/20171027_cherkasy/

**Steps to reproduce:**

1.Find the Legend of the map in the right side of the page.
2.Pay aatention to the language of the text in the legend of the map.

**Actual result:**
The text in the legend of the maps is in English.

**Expected result:**
The text in the legend of the maps is in Ukrainian according [requirements](https://github.com/scholokov/long-travel-2/wiki/1.2-%D0%9C%D0%BE%D0%B2%D0%B0)

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![d0sMZ6ko5v](https://user-images.githubusercontent.com/123729744/227705177-939cd6fc-08d3-4d62-a3b5-a6b6e02308cf.png)

**Comment by scholokov** [comment]
виправлено

**Comment by OlhaHutsman** [comment]
@scholokov verified
