### ISSUE TITLE
20160710_0807_italy_odessa/The link to Palm Spa Hotel is missed in Palm Spa Hotel block

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3351]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to Palm Spa Hotel block.

3. Pay attention to the absence of a link to the hotel in the left side of the block.

**Actual result:**
The link to Palm Spa Hotel is missed.

**Expected result:**
The link to Palm Spa Hotel must be in Palm Spa Hotel block.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.3-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%A1%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D1%96-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8#hotel

![Image](https://user-images.githubusercontent.com/125134112/227920368-5c2a49ad-bee5-471c-975f-f061f8f0fe42.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/227920983-85595b0e-34f6-4f18-89db-39f0419e7bce.png)

**Comment by scholokov** [comment]
виправлено
