### ISSUE TITLE
20160710_0807_italy_odessa/The link to Hotel-Pension Melcher is missed in Hotel-Pension Melcher block

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3353]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to Hotel-Pension Melcher block.

3. Pay attention to the absence of a link to the hotel in the left side of the block.

**Actual result:**
The link to Hotel-Pension Melcher is missed.

**Expected result:**
The link to Hotel-Pension Melcher must be in Hotel-Pension Melcher block.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements**: https://github.com/scholokov/long-travel-2/wiki/4.3-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%A1%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D1%96-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8#hotel

![Image](https://user-images.githubusercontent.com/125134112/227926388-b0a18209-2587-4037-a5ee-710d7be3accd.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/227928259-ec487fc8-e0c7-420f-9212-647e32b8d620.png)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
