### ISSUE TITLE
20160710_0807_italy_odessa/The travel date in Hotel-Pension Melcher block is "11.-13.07.2016" (DD.-DD.MM.YYYY)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3354]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to Palm Spa Hotel block.

3. Pay attention to the travel date in the left side of the block.

**Actual result:**
The travel date in Hotel-Pension Melcher block is "11.-13.07.2016" (DD.-DD.MM.YYYY)

**Expected result:**
The travel date in  Hotel-Pension Melcher  block must be "11.07.2016-13.07.2016" (DD.MM.YYYY-DD.MM.YYYY)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.3-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%A1%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D1%96-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8#hotel

![Image](https://user-images.githubusercontent.com/125134112/227929174-e2662d20-bf56-4d5f-841f-85aa87a03eae.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/227929266-030f653f-d0cd-456a-92ee-e278412e4a8c.png)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
