### ISSUE TITLE
Ім'я подорожі має бути у такому форматі: [Ім'я подорожі] приклад: Portugal in Wiki 3.2

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3357]
**Pre-conditions:**
Open https://github.com/scholokov/long-travel-2/wiki/3.2-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%93%D0%BB%D0%BE%D0%B1%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0-%D0%BA%D0%B0%D1%80%D1%82%D0%B0-%D0%B7-%D0%BC%D0%B0%D1%80%D1%88%D1%80%D1%83%D1%82%D0%B0%D0%BC%D0%B8

**Steps to reproduce:**

1.Find point 1.2.
2.Pay attention to the absence of all necessary information.

**Actual result:**
Ім'я подорожі має бути у такому форматі:
[Ім'я подорожі]
приклад: Portugal

**Expected result:**
Ім'я подорожі має бути у такому форматі:
YYYY.MM.DD [Ім'я подорожі]
for example: 2021.10.29-11.10 Portugal

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

Attachment:
![UJvmg30PiP](https://user-images.githubusercontent.com/123729744/228456415-fb669bfa-7c11-42e5-943b-25a52bcd9425.png)

**Comment by scholokov** [comment]
виправлено

**Comment by OlhaHutsman** [comment]
@scholokov verified
