### ISSUE TITLE
Requirement 1.3 is repeated in 4.3 in Wiki 3.2

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3358]
**Pre-conditions:**
Open https://github.com/scholokov/long-travel-2/wiki/3.2-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%93%D0%BB%D0%BE%D0%B1%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0-%D0%BA%D0%B0%D1%80%D1%82%D0%B0-%D0%B7-%D0%BC%D0%B0%D1%80%D1%88%D1%80%D1%83%D1%82%D0%B0%D0%BC%D0%B8

**Steps to reproduce:**

1.Find point 1.3. and 4.3
2.Pay attention 1.3 and 4.3 are the same requirements.

**Actual result:**
Requirement 1.3 is repeated in 4.3

**Expected result:**
Requirement 1.3 isn't repeated in 4.3

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![WeSGz9opZn](https://user-images.githubusercontent.com/123729744/228458169-310aa27c-0773-4831-8467-aa88d59bf710.png)

**Comment by scholokov** [comment]
виправлено

**Comment by OlhaHutsman** [comment]
@scholokov    1.4=4.2

**Comment by scholokov** [comment]
fixed

**Comment by OlhaHutsman** [comment]
@scholokov verified
