### ISSUE TITLE
Requirement 2.2 is  incomplete in Wiki 3.2

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3359]
**Pre-conditions:**
Open https://github.com/scholokov/long-travel-2/wiki/3.2-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%93%D0%BB%D0%BE%D0%B1%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0-%D0%BA%D0%B0%D1%80%D1%82%D0%B0-%D0%B7-%D0%BC%D0%B0%D1%80%D1%88%D1%80%D1%83%D1%82%D0%B0%D0%BC%D0%B8

**Steps to reproduce:**

1.Find point 2.2
2.Pay attention it is not clear where exactly the colors should be different.

**Actual result:**
Requirement is  incomplete

**Expected result:**
Requirement is  complete

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![colors](https://user-images.githubusercontent.com/123729744/228460983-21f5dbc0-ae61-4af9-863b-6b536f79487d.png)

**Comment by scholokov** [comment]
виправлено

**Comment by OlhaHutsman** [comment]
@scholokov  verified
