### ISSUE TITLE
/travels/ Travel  20201025_vedmy is not in the requirements

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3361]
Steps to reproduce:
1.Open https://test.long-travel.live/travels/
2.Chek the travel 20201025_vedmy

Actual result:
Travel  20201025_vedmy on the page

Expected result:
Travel not on the page( travel is not in the requirements)

Attachment:
https://github.com/scholokov/long-travel-2/wiki/3.1-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%9F%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177

![2023-03-29_14h50_49](https://user-images.githubusercontent.com/125903734/228526904-c1431d38-2bf5-4014-ae7c-57c5b5230f29.png)

**Comment by scholokov** [comment]
додано у вимоги

**Comment by ViktoriaZamkova** [comment]
verified
