### ISSUE TITLE
20150919_kiev_aviation_museum/PhotoGallery, LightBox photo is not displayed when you click the arrow to scroll through the photo

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3362]
Steps to reproduce:
1. Open https://test.long-travel.live/20150919_kiev_aviation_museum/
2. Scroll down to PhotoGallery
3. Click on 1st photo to open LightBox
4. Click on the arrow on the right
5. Pay attention to the image

Actual Result: the photo is not displayed in the LightBox
Expected Result: the photo is displayed in the LightBox

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://user-images.githubusercontent.com/123776698/228658194-2f0ce611-b7fc-4339-8d53-86680e0e5f33.png)

**Comment by ODrobik** [comment]
#2995

**Comment by scholokov** [comment]
please retest
