### ISSUE TITLE
20170709_protsiv/The name of travel in the Preview block "Процев,Киевская область, Украина" does not match the name of Travel in 3.1 Подорожі. Перелік

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3363]
Steps to reproduce:
        1. Open https://test.long-travel.live/20170709_protsiv/
        2. Scroll down to the Preview block
        3. Pay attention to the name of travel in the Preview block "Процев,Киевская область, Украина"

Actual result:
The name of travel in the Preview block "Процев,Киевская область, Украина"

Expected result:
The name of travel in the Preview block "Проців"

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://user-images.githubusercontent.com/123776698/228669238-c580dc01-45af-483e-88ea-5a75bb723457.png)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
@scholokov verified
