### ISSUE TITLE
20170715_boguslav/  The preview picture half closed with a black translucent background

### ISSUE THREAD

**Issue by TetianaSulima** [scholokov/long-travel-2#3364]
Prerequisites:
Open https://test.long-travel.live/20170715_boguslav/
Steps to reproduce:

1. Pay attention to the preview picture

Actual result: The picture  preview half closed with a black translucent background.

Expected result: The picture in the preview  is good quality and doesn't blends into the background.

https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=3531-33&t=aEEjlnSNEvANRwb8-0

Environment: Windows 10 Home
system:
Browser: Google Chrome Version 110.0.5481.178

![image](https://user-images.githubusercontent.com/123786969/229139280-54df9702-c007-440a-9ad5-57be488be529.png)

![image](https://user-images.githubusercontent.com/123786969/228938660-fe782679-79a9-4fb6-9802-7a08955dcf09.png)

**Comment by DmytroMarkulych** [comment]
Додайте деталей в баг репорт

**Comment by TetianaSulima** [comment]
![image](https://user-images.githubusercontent.com/123786969/228936514-13308a87-3e94-4eef-99ce-fe38958ffd39.png)
Сьогодні взагалі так показує.  
додати новий скрін та preview half closed with a black translucent background  ??

**Comment by DmytroMarkulych** [comment]
@TetianaSulima а як щодо Summary?

**Comment by DmytroMarkulych** [comment]
@TetianaSulima давайте скріншоти винесимо в кінець баг репорту, прибравши їх із Actual Result

**Comment by TetianaSulima** [comment]
а я послухала запис Дениса що скріни до Actual Result)))

**Comment by TetianaSulima** [comment]
![image](https://user-images.githubusercontent.com/123786969/230254049-27c6141c-acfd-44d5-b346-dc514343928e.png)

**Comment by scholokov** [comment]
fixed
