### ISSUE TITLE
20160710_0807_italy_odessa/The flag of Austria is missed in the Road Nyírbátor – Drobollach block

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3365]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the Road Nyírbátor – Drobollach block.

3. Pay attention to the absence of the flag of Austria in the right side of the block.

**Actual result:**
The flag of Austria is missed.

**Expected result:**
The flag of Austria must be in the Road Nyírbátor – Drobollach block.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.3-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%A1%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D1%96-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8#road

![Image](https://user-images.githubusercontent.com/125134112/228827347-b0bbe301-87f8-4d22-bcc7-11e5d69e7afb.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/228828111-f430c5a5-92bd-461f-a1b6-1ef7897f958c.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
