### ISSUE TITLE
20160710_0807_italy_odessa/The travel name of the video gallery of Road Nyirbator - Drobolach block is in English

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3366]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the Road  Nyirbator - Drobolach block.

3. Pay attention to the travel name of the video gallery.

**Actual result:**
The travel name of the video gallery of the  Nyirbator - Drobolach block is in English

**Expected result:**
The travel name of the video gallery of the  Nyirbator - Drobolach block must bein the language of the respective country (Hungary - in Hungarian; Austria - in German)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery

![Image](https://user-images.githubusercontent.com/125134112/228832238-38289bdd-7d3e-4abb-adf3-b31a08caf344.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/228833338-9fa2dd36-2d50-447b-8457-c894650e132b.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
@scholokov @ABatalov 
no fixed. Austria must be in German - Österreich


![Image](https://user-images.githubusercontent.com/125134112/229742695-d200e42e-faa6-4c2d-a88d-6ccac60acab0.png)

**Comment by scholokov** [comment]
please retest according to changes in requirements:
https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

**Comment by prokopenkoga1977** [comment]
Passed
