### ISSUE TITLE
20160710_0807_italy_odessa/The travel name of the video gallery of Road Nyirbator - Drobolach block is Hungary-Austria

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3367]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the Road Nyirbator - Drobolach block.

3. Pay attention to the travel name of the video gallery.

**Actual result:**
The travel name of the video gallery of Road Nyirbator - Drobolach block is Hungary-Austria

**Expected result:**
The travel name of the video gallery of Road Nyirbator - Drobolach block must be Nyirbator - Drobolach

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery

![Image](https://user-images.githubusercontent.com/125134112/228836150-563e3491-5bbd-4706-8d67-7dc54bcce90f.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/228836389-d65ee2a9-7817-4a9d-bbe8-73e43bd10393.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
