### ISSUE TITLE
wiki/ The page "4.2. Подорож. Превью" the word "Превью"  is in russian language

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3369]
Steps to reproduce:

1. Open: https://github.com/scholokov/long-travel-2/wiki/4.2.-Подорож.-Превью
2. Pay attention to the page "4.2. Подорож. Превью"
3. Pay attention to the words "Превью"

Actual Result: the word "Превью" is in russian language
Expected Result: the word "Прев'ю" is in ukrainian language

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://user-images.githubusercontent.com/123776698/228952520-eb4f32b3-e36c-435b-8e19-514a60ca7d7b.png)

**Comment by DmytroMarkulych** [comment]
@ODrobik Вийшов загальний баг репорт, без деталей. Давайте замінимо фразу "has spelling mistake.." на фактично що ми маємо і що має бути

**Comment by ODrobik** [comment]
@[DmytroMarkulych](https://github.com/DmytroMarkulych) виправлено

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
@scholokov Створено новий схожий баг #3382
