### ISSUE TITLE
20170709_protsiv/ In the Preview block of Travel, background options of the photo does not meet design requirements in Figma

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3370]
Steps to reproduce:
1. Open https://test.long-travel.live/20170709_protsiv/
2. Scroll down to the Preview block
3. Pay attention to the photo in the Preview block 

Actual result:
the photo does not match the requirements for the appearance

Expected result:
the photo does match the requirements for the appearance

Requirements: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1800-77&t=OkGTBddNoN4czsYH-0

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://user-images.githubusercontent.com/123776698/229167334-4e2984c0-ad2f-43e2-b742-be781193f7f0.png)

**Comment by DmytroMarkulych** [comment]
@ODrobik Давайте в баг репорті, загальні фрази ( the requirements for the appearance) замінимо на точні дані які у нас є на сайті та дизайні

**Comment by ODrobik** [comment]
@[DmytroMarkulych](https://github.com/DmytroMarkulych) виправлено

**Comment by ODrobik** [comment]
#3235

**Comment by scholokov** [comment]
please retest

**Comment by ODrobik** [comment]
verified
