### ISSUE TITLE
20170709_protsiv/In the map with routes in the List of travel does not match the name of the travel in 3.1 Подорожі. Перелік

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3371]
Steps to reproduce:
1. Open https://test.long-travel.live/20170709_protsiv/
2. Pay attention to the name of travel in the drop-down list.

Actual Result:
The name of travel is "20170709_Protsiv"

Expected Result:
The name of travel is "Проців"

Requirements: 
> https://github.com/scholokov/long-travel-2/wiki/4.1.-Подорож.-Контент
> https://github.com/scholokov/long-travel-2/wiki/3.1-Подорожі.-Перелік

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80 

Attachment:
![image](https://user-images.githubusercontent.com/123776698/229341504-b31b95ac-7943-44de-8e9b-c8236d1c0d7a.png)

**Comment by ODrobik** [comment]
#3235

**Comment by ODrobik** [comment]
@scholokov додано лінки на вимоги

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
@scholokov issue still exists
![image](https://user-images.githubusercontent.com/123776698/230996146-e7b93cdc-1c61-4188-a430-4281a254e497.png)

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
@scholokov verified
