### ISSUE TITLE
20160710_0807_italy_odessa/The date format of the first video gallery of the Road Nyirbator - Drobolach block is 11.07.2016 (DD.MM.YYYY)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3372]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the Road Nyirbator - Drobolach block.

3. Pay attention to the date format of the first video gallery.

**Actual result:**
The date format of the first video gallery of the Road Nyirbator - Drobolach block is 11.07.2016 (DD.MM.YYYY)

**Expected result:**
The date format of the first video gallery of the Road Nyirbator - Drobolach block must be 2016.07.11 (YYYY.MM.DD)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements**: https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery

![Image](https://user-images.githubusercontent.com/125134112/229463225-6a9c6696-6e07-4de3-95e4-ea6e9d37e1d8.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/229465173-5b04de99-bac8-4c35-b6fa-5bff483b1ac7.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
