### ISSUE TITLE
20160710_0807_italy_odessa/The date format of the fifth video gallery of the Road Nyirbator - Drobolach block is 2016.07 (YYYY.MM.)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3376]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the Road Nyirbator - Drobolach block.

3. Pay attention to the date format of the fifth video gallery.

**Actual result:**
The date format of the fifth video gallery of the Road Nyirbator - Drobolach block is 2016.07 (YYYY.MM.)

**Expected result:**
The date format of the fifth video gallery of the Road Nyirbator - Drobolach block must be 2016.07.11 (YYYY.MM.DD)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery

![Image](https://user-images.githubusercontent.com/125134112/229472993-d90799f1-77f0-4bd4-bc27-1dce16df4ad3.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/229473642-1313a2a8-9965-42fe-bcfa-d608a20b5b90.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
