### ISSUE TITLE
20160710_0807_italy_odessa/The travel name of the first video gallery of Road Nyirbator - Drobolach block is Hungary-Austria 1/2 Hungary

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3377]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the Road Nyirbator - Drobolach block.

3. Pay attention to the travel name of the first video gallery.

**Actual result:**
The travel name of the first video gallery of Road Nyirbator - Drobolach block is Hungary-Austria 1/2 Hungary

**Expected result:**
The travel name of the first video gallery of Road Nyirbator - Drobolach block must be Nyirbator - Drobolach 1/2 Hungary (Hungary must be in Hungarian)

**Environment**:
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery

![Image](https://user-images.githubusercontent.com/125134112/229477480-08f7362c-c05c-4d05-9ce1-ad728c2eedf1.png)

![Image](https://user-images.githubusercontent.com/125134112/229480683-e3730c18-1313-40d3-bd72-9376c285bbb5.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/229478226-4771da8b-077a-4aa9-8fec-80d956946dd8.png)

**Comment by prokopenkoga1977** [comment]
@scholokov @ABatalov 
no fixed. Austria must be in German - Österreich


![Image](https://user-images.githubusercontent.com/125134112/229746109-9cb9e096-e11c-4441-aac0-5ff460c7c29b.png)

**Comment by scholokov** [comment]
please retest according to changes in requirements:
https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

**Comment by prokopenkoga1977** [comment]
Passed
