### ISSUE TITLE
20160710_0807_italy_odessa/The travel name of the second video gallery of Road Nyirbator - Drobolach block is Hungary-Austria 2/2 Austria

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3378]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the Road Nyirbator - Drobolach block.

3. Pay attention to the travel name of the second video gallery.

**Actual result:**
The travel name of the second video gallery of Road Nyirbator - Drobolach block is Hungary-Austria 2/2 Austria

**Expected result:**
The travel name of the second video gallery of Road Nyirbator - Drobolach block must be Nyirbator - Drobolach 2/2 Austria (Austria must be in German)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery

![Image](https://user-images.githubusercontent.com/125134112/229479488-7fb647d4-ccdb-4f3c-8f7a-2cbae7f87bb9.png)

![Image](https://user-images.githubusercontent.com/125134112/229479546-8c97837e-aa3a-4bd8-84db-89786878dae9.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/229480118-d0446ece-3ccb-48e1-8dbf-ae37870896a2.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
@scholokov @ABatalov 
no fixed. Hungary must be in Hungarian, Austria must be in German


![Image](https://user-images.githubusercontent.com/125134112/229747203-3ab2a808-9f73-48e9-ad29-a87889a12978.png)

**Comment by scholokov** [comment]
please retest according to changes in requirements:
https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

**Comment by prokopenkoga1977** [comment]
Passed
