### ISSUE TITLE
20160710_0807_italy_odessa/The travel name of the third video gallery of Road Nyirbator - Drobolach block is Hungary, Budapest 3.3

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3379]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the Road Nyirbator - Drobolach block.

3. Pay attention to the travel name of the third video gallery.

**Actual result:**
The travel name of the third video gallery of Road Nyirbator - Drobolach block is Hungary, Budapest 3.3

**Expected result:**
The travel name of the third video gallery of Road Nyirbator - Drobolach block must be is Nyirbator - Drobolach, Budapest 3.3 (Budapest must be in Hungarian)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery

![Image](https://user-images.githubusercontent.com/125134112/229481557-b3b8d2f3-852e-495f-9943-3d813db07837.png)

![Image](https://user-images.githubusercontent.com/125134112/229481610-0ac3a46c-d5df-4359-9ce8-8fa1249d00ef.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/229482231-00992043-0950-42bf-90a9-0382632da353.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
