### ISSUE TITLE
20160710_0807_italy_odessa/The travel name of the fourth video gallery of Road Nyirbator - Drobolach block is Hungary, Budapest 2.3

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3380]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the Road Nyirbator - Drobolach block.

3. Pay attention to the travel name of the fourth video gallery.

**Actual result:**
The travel name of the fourth video gallery of Road Nyirbator - Drobolach block is Hungary, Budapest 2.3

**Expected result:**
The travel name of the fourth video gallery of Road Nyirbator - Drobolach block must be is Nyirbator - Drobolach, Budapest 2.3 (Budapest must be in Hungarian)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery

![Image](https://user-images.githubusercontent.com/125134112/229483248-86ef2191-6889-45d7-b729-f843335f8046.png)

![Image](https://user-images.githubusercontent.com/125134112/229483329-9e4cac84-432f-4d68-a78b-c5864cb483e4.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/229483919-b1d59f24-33ee-498c-b7d3-38aa27289269.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
