### ISSUE TITLE
20160710_0807_italy_odessa/The travel name of the fifth video gallery of Road Nyirbator - Drobolach block is Hungary, Budapest 1.3

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3381]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the Road Nyirbator - Drobolach block.

3. Pay attention to the travel name of the fifth video gallery.

**Actual result:**
The travel name of the fifth video gallery of Road Nyirbator - Drobolach block is Hungary, Budapest 1.3

**Expected result:**
The travel name of the fifth video gallery of Road Nyirbator - Drobolach block must be is Nyirbator - Drobolach, Budapest 1.3 (Budapest must be in Hungarian)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/2.1-Travel.YoutubeVideo-Gallery

![Image](https://user-images.githubusercontent.com/125134112/229484752-2685cc22-6f1c-45d7-8d4a-a06af7d9adc4.png)

![Image](https://user-images.githubusercontent.com/125134112/229484789-8130755a-2478-4ab2-ae27-f7c3aa59de0c.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/229485257-485f1d48-0809-461d-9e36-d2fb2139f3de.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
