### ISSUE TITLE
wiki/ The page "4.2. Подорож. Превью" the word "Превью" is in russian language

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3382]
Steps to reproduce:

1. Open: [https://github.com/scholokov/long-travel-2/wiki/4.2.-Подорож.-Превью](https://github.com/scholokov/long-travel-2/wiki/4.2.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%9F%D1%80%D0%B5%D0%B2%D1%8C%D1%8E)
2. Pay attention to the header of page "4.2. Подорож. Превью"

Actual Result: the word "Превью" is in russian language
Expected Result: the word "Прев'ю" is in ukrainian language

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://user-images.githubusercontent.com/123776698/229763170-e507c6af-eac6-4ee4-9ca1-aaf6ec86bb30.png)

**Comment by DmytroMarkulych** [comment]
@ODrobik пронумеруйте кроки для відтворення та зверніть уваги що у Вас повторюється двічі "Pay attention to.."

**Comment by DmytroMarkulych** [comment]
![Image](https://user-images.githubusercontent.com/88647733/229874732-d7898aef-5365-4c90-bab4-20ea5a304186.png)

**Comment by ODrobik** [comment]
@DmytroMarkulych виправлено

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
@scholokov verified https://github.com/scholokov/long-travel-2/wiki/4.2.-Подорож.-Прев'ю
