### ISSUE TITLE
20170612_buki/PhotoGallery-LightBox photo is not displayed when clicking on the arrow to go to the next photo

### ISSUE THREAD

**Issue by WANteddddd** [scholokov/long-travel-2#3383]
Steps to reproduse:
1. Open https://www.test.long-travel.live/20170612_buki
2. Scroll down to PhotoGallery
3.Click on photo to open LightBox
4.Click on the arrow on the right
5.Pay attention to the image

Actual result: the photo is not displayed in the LightBox
Expected result:  the photo is displayed in the LightBox

Environment: Windows 10 ITSC (x64)
Browser: Google Chrome Version 110.0.5481.178

Attachment:
![image](https://user-images.githubusercontent.com/119532002/230048877-a0c2866e-b247-498b-b798-e0a9afe39d78.png)
![image](https://user-images.githubusercontent.com/119532002/230049585-d4ba55df-ce74-4656-8461-0c6cb5d42861.png)

**Comment by DmytroMarkulych** [comment]
@WANteddddd додайте будь ласка наступні атрибути

![Image](https://user-images.githubusercontent.com/88647733/230162267-951608a1-8638-4755-bb93-6f864038220e.png)

**Comment by WANteddddd** [comment]
@DmytroMarkulych Атрибути додав.

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
