### ISSUE TITLE
/travels/ Trip name doesn`t meet the requirements

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3384]
Steps to reproduce:
1.Open https://test.long-travel.live/travels/
2.Chek the travel name 20201025_vedmy

Actual result:
20201025_vedmy

Expected result:
"Лиса Гора" - Коктейль бар

Attachment:

https://github.com/scholokov/long-travel-2/wiki/3.1-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%9F%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177

![2023-04-05_13h06_43](https://user-images.githubusercontent.com/125903734/230053927-8e2b4616-d769-4524-895d-c5ca790362cb.png)
![2023-04-05_13h05_39](https://user-images.githubusercontent.com/125903734/230053949-7a5f05ec-7952-4868-b4bb-54a5eb7c7d9d.png)

**Comment by scholokov** [comment]
виправлено

**Comment by ViktoriaZamkova** [comment]
checked
