### ISSUE TITLE
20170805_20_odessa no photo in prevew

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3385]
Prerequisites:
Open:  https://test.long-travel.live/20170805_20_odessa/#gallery[photonic-google-album-1]/AE29bMFYmd1lGtJ3gtf3k2TUVnHxuDsm4XrV5PfrQ1laKx7HF5unb6DAG6z5wJjUPAn7N4WAJL8nRpHwzbUp4nJ6RGQenNR-Ug/
Steps to reproduce:

1. Please note that there is no photo in the preview after the video

Actual result: no photo in preview
Expected result: Is a photo in the preview

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104   
![Odes-prew](https://user-images.githubusercontent.com/113175298/230053870-2467fcad-5926-4bb0-988d-fa10141ede7d.png)

**Comment by Nadiyk** [comment]
#3238

**Comment by scholokov** [comment]
виправлено

**Comment by Nadiyk** [comment]
Pass
