### ISSUE TITLE
/20201025_vedmy/ Travel date does not meet the requirements

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3387]
Steps to reproduce:
1.Open https://test.long-travel.live/20201025_vedmy/
2.Chek the travel date

Actual result:
25.10.2021

Expected result:
25.10.2020

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 112.0.5615.50
![2023-04-05_13h37_15](https://user-images.githubusercontent.com/125903734/230057903-e549c971-9e36-4583-b3e9-aa9953d17570.png)

**Comment by DmytroMarkulych** [comment]
@ViktoriaZamkova на скільки я знаю, то в місяці максимально 31 день

**Comment by ViktoriaZamkova** [comment]
Дякую)

**Comment by scholokov** [comment]
виправлено

**Comment by ViktoriaZamkova** [comment]
checked
