### ISSUE TITLE
20150919_Kiev_Aviation_Museum/In the Preview block "Державний музей авіації осінь 2015" of travel the size of the flag of Ukraine is 26x17.33 px

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3388]
Steps to reproduce:
1. Open https://test.long-travel.live/20150919_Kiev_Aviation_Museum/
2. Scroll down to the Preview block "Державний музей авіації осінь 2015"
3. Pay attention to the size of the flag of Ukraine 

Actual result:  the size of the flag of Ukraine is 26x17.33 px

Expected result: the size of the flag of Ukraine is 26x18 px

Requirements: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-7&t=zNYPaOfE0Mu2cemL-0

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment
![image](https://user-images.githubusercontent.com/123776698/230216252-82b9016b-aaf2-485e-8c46-0aef1f79520c.png)

**Comment by ODrobik** [comment]
#2995

**Comment by GNatala** [comment]
passed
