### ISSUE TITLE
20160710_0807_italy_odessa/The date format of the video gallery of Hotel-Pension Melcher block is 2016.07 (YYYY.MM)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3391]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the video gallery of Hotel-Pension Melcher block.

3. Pay attention to the date format of the video gallery.

**Actual result:**
The date format of the video gallery of Hotel-Pension Melcher block is 2016.07 (YYYY.MM)

**Expected result:**
The date format of the video gallery of Hotel-Pension Melcher block must be 2016.07.11-2016.07.13(YYYY.MM.DD-YYYY.MM.DD)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:**https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://user-images.githubusercontent.com/125134112/230351094-78cef50f-ff08-46aa-b0aa-d0b85cd7841c.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/230350672-dc3b0549-c6a3-4668-ac4f-bd3a19f39706.png)

**Comment by scholokov** [comment]
please retest according to changes in requirements:
https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

**Comment by prokopenkoga1977** [comment]
@scholokov @ABatalov 
no fixed The date format must be in format YYYY.MM.DD


![Image](https://user-images.githubusercontent.com/125134112/231810868-59a3d522-88fb-4aed-b3f3-270a57318dcb.png)



![Image](https://user-images.githubusercontent.com/125134112/231811207-fd8cc678-6986-43fb-88f5-965d165a45ff.png)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
