### ISSUE TITLE
20160710_0807_italy_odessa/The date format of the second video gallery of Hotel-Pension Melcher block is 2016.07 (YYYY.MM)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3393]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the video gallery of Hotel-Pension Melcher block.

3. Pay attention to the date format of the second video gallery.

**Actual result:**
The date format of the second video gallery of Hotel-Pension Melcher block is 2016.07 (YYYY.MM)

**Expected result:**
The date format of the second video gallery of Hotel-Pension Melcher block must be 2016.07.11-2016.07.13(YYYY.MM.DD-YYYY.MM.DD)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:**https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://user-images.githubusercontent.com/125134112/230353840-cc2f5ab8-2238-40df-9eaa-4497180a5862.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/230354433-e706c12b-9913-4199-8f32-a05658496ac3.png)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
