### ISSUE TITLE
20160710_0807_italy_odessa/The travel name of the first video gallery of Hotel-Pension Melcher block is Austria Drobollah Faaker Sea-Hotel in English

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3395]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the video gallary of Hotel-Pension Melcher block.

3. Pay attention to the travel name of the first video gallery.

**Actual result:**
The travel name of the first video gallery of Hotel-Pension Melcher block is **Austria** Drobollah Faaker **Sea**-Hotel in English

**Expected result:**
The travel name of the first video gallery of Hotel-Pension Melcher block must be **Österreich** Drobollah Faaker **See**-Hotel in German

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://user-images.githubusercontent.com/125134112/230357469-946eaf5e-438c-414d-90c1-8e6b3502a29c.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/230358037-5ba0f9bb-aa80-48e9-9acb-042773d96e68.png)

**Comment by scholokov** [comment]
виправлено згідно нових вимог

**Comment by prokopenkoga1977** [comment]
Passed
