### ISSUE TITLE
20170805_20_odessa/ No image in the preview

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3398]
Prerequisites:
Open:  https://test.long-travel.live/20170805_20_odessa/
Steps to reproduce:

1. Please note there is no image in the preview after the video

Actual result:  No image in the preview
Expected result: Is the image in the preview

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104
![Od-pr](https://user-images.githubusercontent.com/113175298/230391674-3a4dd44f-47ed-42da-b7bb-041195785d71.png)

**Comment by scholokov** [comment]
fixed

**Comment by Nadiyk** [comment]
pass
