### ISSUE TITLE
20170605_kiev_mariinskiy/  Name of travel is in Russian

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3399]
**Pre-conditions:**
Open https://test.long-travel.live/20170605_kiev_mariinskiy/

**Steps to reproduce:**
1.Find 1st preview
2.Pay attention to the name of the travel.

**Actual result:**
Name of travel is in Russian

**Expected result:**
Name of travel is in Ukrainian

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![mDhORUtwGm](https://user-images.githubusercontent.com/123729744/230421272-fe5d527b-2cc4-4913-9931-5fbb675b02e2.png)

**Comment by scholokov** [comment]
fixed

**Comment by OlhaHutsman** [comment]
@scholokov verified
