### ISSUE TITLE
20170605_kiev_mariinskiy/ The date of the travel is not represented in the preview.

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3400]
**Pre-conditions:**
Open https://test.long-travel.live/20170605_kiev_mariinskiy/

**Steps to reproduce:**
1.Find 1st preview
2.Pay attention to the absence of the date of the travel.

**Actual result:**
The date of the travel is not represented in the preview.

**Expected result:**
The date of the travel is represented in the preview.

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0

**Attachment:**
![g2zrYFNmVG](https://user-images.githubusercontent.com/123729744/230546118-aeb06975-3dd1-478c-b4fb-85b03e985fab.png)

**Comment by scholokov** [comment]
fixed

**Comment by OlhaHutsman** [comment]
@scholokov verified
