### ISSUE TITLE
20170605_kiev_mariinskiy/ The name of the travel is Крещатик, Мариинский парк,Киев, Украина

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3402]
**Pre-conditions:**
Open https://test.long-travel.live/20170605_kiev_mariinskiy/

**Steps to reproduce:**
1.Find 1st preview
2.Pay attention to the name of the travel.

**Actual result:**
The name of the travel is Крещатик, Мариинский парк,Киев, Украина

**Expected result:**
The name of the travel is Хрещатик - Маріїнський парк

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/3.1-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%9F%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA

Attachment:
![s0UHOSc2Oz](https://user-images.githubusercontent.com/123729744/230548665-0be4f04b-906f-4593-8e36-f72a75b25fd4.png)

**Comment by scholokov** [comment]
Actual result:
The name of the travel is Крещатик, Мариинский парк,Киев, Украина

Expected result:
The name of the travel is Хрещатик - Маріїнський парк

при таких описах краще писати у форматі:
Actual result:
The name of the travel is: 
Крещатик, Мариинский парк,Киев, Украина

Expected result:
The name of the travel is:
Хрещатик - Маріїнський парк

**Comment by scholokov** [comment]
виправлено
