### ISSUE TITLE
20170605_kiev_mariinskiy/The photo on the 1st preview has an extra layer on it.

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3403]
**Pre-conditions:**
Open https://test.long-travel.live/20170605_kiev_mariinskiy/

**Steps to reproduce:**
1.Find 1st preview
2.Pay attention to the design of the of the 1st preview of the travel.

**Actual result:**
The photo on the 1st preview has an extra layer on it.

**Expected result:**
The photo on the 1st preview hasn't  an extra layer on it.

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Additional information:**
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1201-27&t=MTgIM0PHfUJloD2N-0

**Attachment:**
![7](https://user-images.githubusercontent.com/123729744/230549897-d6974047-3743-4b27-bf12-d9b75b7d1327.png)

**Comment by scholokov** [comment]
виправлено

**Comment by OlhaHutsman** [comment]
@scholokov verified
