### ISSUE TITLE
20170605_kiev_mariinskiy/There is an extra  text above the  map.

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3404]
**Pre-conditions:**
Open https://test.long-travel.live/20170605_kiev_mariinskiy/

**Steps to reproduce:**
1.Find 1st preview
2.Pay attention to the text above the  map.

**Actual result:**
There is an extra  text above the  map.

**Expected result:**
There is  not  an extra  text above the  map.

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0

Attachment:
![o1R9WDcV8g](https://user-images.githubusercontent.com/123729744/230550718-28e85d13-edfd-4725-b213-e85d269f4fa6.png)

**Comment by scholokov** [comment]
виправлено

**Comment by OlhaHutsman** [comment]
@scholokov verified
