### ISSUE TITLE
20170625_gusintsi/ Is no travel date in preview

### ISSUE THREAD

**Issue by Nadiyk** [scholokov/long-travel-2#3405]
Prerequisites:
Open: https://test.long-travel.live/20170625_gusintsi/
Steps to reproduce:

1. Please note that there is no travel date in the preview

Actual result: Is no travel date in the preview
Expected result:  Is the travel date in the preview

Environment: Windows 10 Pro Operating
system:
Browser: Google Chrome Version 110.0.5481.104 
![гусениці дата](https://user-images.githubusercontent.com/113175298/230611626-c02da594-e214-4094-9300-ccc12e401ce8.png)

**Comment by scholokov** [comment]
виправлено

**Comment by Nadiyk** [comment]
Pass
