### ISSUE TITLE
20170709_protsiv/ Under the Preview block "Проців" of the travel are the extra elements "Киевская область, Украина" and "09.07.2017"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3407]
Steps to Reproduce:
1. Open https://test.long-travel.live/20170709_protsiv/
2. Pay attention to the text under the Preview block "Проців"

Actual Result: The extra elements "Киевская область, Украина" and "09.07.2017" are under the Preview block "Проців"

Expected Result: The extra elements "Киевская область, Украина" and "09.07.2017" are not appear under the Preview block "Проців"

Requirements: https://github.com/scholokov/long-travel-2/wiki/4.-Подорож.-Структура

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachments:
![image](https://user-images.githubusercontent.com/123776698/230630770-47e650b6-b6cc-4270-b8db-7f20c5962ce6.png)

**Comment by ODrobik** [comment]
#3235

**Comment by DmytroMarkulych** [comment]
![Image](https://user-images.githubusercontent.com/88647733/230761915-59e7c6c2-36c9-4000-bd5d-958bbd877453.png)

**Comment by ODrobik** [comment]
@DmytroMarkulych виправлено

**Comment by ODrobik** [comment]
@scholokov verified
