### ISSUE TITLE
20170605_kiev_mariinskiy/ The  flag of Ukraine is not represented  in 2nd preview.

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3408]
**Pre-conditions:**
Open https://test.long-travel.live/20170605_kiev_mariinskiy/

**Steps to reproduce:**
1.Find 2nd preview
2.Pay attention to the abcense of the flag of Ukraine.

**Actual result:**
The  flag of Ukraine is not represented  in 2nd preview.

**Expected result:**
The  flag of Ukraine is  in 2nd preview.

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0

**Attachment:**
![0aMkdvJtY2](https://user-images.githubusercontent.com/123729744/230705320-5138ba90-2e4b-4997-8824-1439c199585c.png)

**Comment by scholokov** [comment]
fixed

**Comment by OlhaHutsman** [comment]
@scholokov verified
