### ISSUE TITLE
20170605_kiev_mariinskiy/ The date of travel is represented under 2nd preview.

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3409]
**Pre-conditions:**
Open https://test.long-travel.live/20170605_kiev_mariinskiy/

**Steps to reproduce:**
1.Find 2nd preview
2.Pay attention to the date of travel under preview.

**Actual result:**
The date of travel is represented under 2nd preview.

**Expected result:**
The date of travel is represented in 2nd preview.

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0

**Attachment:**
![XD7Fb0DYHz](https://user-images.githubusercontent.com/123729744/230705513-a44a8ee9-0d2d-47a7-8f80-a06c39000374.jpg)

**Comment by scholokov** [comment]
fixed

**Comment by OlhaHutsman** [comment]
@scholokov verified
