### ISSUE TITLE
20170605_kiev_mariinskiy/The text in the legend of the map is in Russian

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3411]
**Pre-conditions:**
Open https://test.long-travel.live/20170605_kiev_mariinskiy/

**Steps to reproduce:**
1.Find the legend of the map
2.Pay attention to the text in the legend of the map.

**Actual result:**
The text in the legend of the map is in Russian

**Expected result:**
The text in the legend of the map is in Ukrainian

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

 **Additional information**
https://github.com/scholokov/long-travel-2/wiki/4.4-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%9C%D0%B0%D0%BF%D0%B0

Attachment:
![lK2py0O1qO](https://user-images.githubusercontent.com/123729744/230792447-225c8350-4cf2-4811-bf85-28574495528e.png)

**Comment by scholokov** [comment]
виправлено

**Comment by OlhaHutsman** [comment]
@scholokov verified
