### ISSUE TITLE
20170605_kiev_mariinskiy/The date of the travel is under the preview

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3414]
**Pre-conditions:**
Open https://test.long-travel.live/20170605_kiev_mariinskiy/

**Steps to reproduce:**
1.Find 2nd preview
2.Pay attention to the date  of the travel.

**Actual result:**
The date of the travel is under the preview

**Expected result:**
The date of the travel is in the  preview

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Attachment:**
![DGR6otdlBd](https://user-images.githubusercontent.com/123729744/230835747-9719044d-5449-4cdc-b812-151308858363.jpg)

**Comment by scholokov** [comment]
fixed

**Comment by OlhaHutsman** [comment]
@scholokov verified
