### ISSUE TITLE
20170416_kiev_sof_plosha/ Missed element "Link" to production in the Map's legend

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3416]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170416_kiev_sof_plosha/
2. Scroll down to the Map of travel.
3. Pay attention to the Legend.

**Actual result:**
There is no element "Link" to production is the end of list of waypoints.

**Expected result:**
Element "Link" to production is the end of list of waypoints.

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.4-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%9C%D0%B0%D0%BF%D0%B0

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/231229277-431ea088-6fb7-45ec-9daa-aa5b277331cd.png)

**Comment by GNatala** [comment]
#3226

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
passed
