### ISSUE TITLE
20170416_kiev_sof_plosha/ Name of the Travel in the Preview block does not match the name of the Travel in wiki/3.1-Подорожі.-Перелік

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3418]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170416_kiev_sof_plosha/
2. Pay attention to the name of the Travel in the Preview block.

**Actual result:**
The name of the Travel in the Preview block is "Софиевская Площадь"

**Expected result:**
The name of the Travel in the Preview block is "Софиївска Площа - Фестиваль писанок"

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/3.1-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%9F%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/231239591-c5566049-0c97-48c2-9d2c-6e55b6d9473b.png)

**Comment by GNatala** [comment]
https://github.com/scholokov/long-travel-2/issues/3226

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
