### ISSUE TITLE
wiki/3.1-Подорожі.-Перелік/ Spelling mistake in the word "Софиївска" in the name of Travel

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3419]
**Steps to reproduce:**

1. Open: https://github.com/scholokov/long-travel-2/wiki/3.1-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%9F%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA
2. Pay attention to item 32  name "Софиївска Площа - Фестиваль писанок".

**Actual Result:** 
Name of the travel is "**Софиївска** Площа - Фестиваль писанок"

**Expected Result:** 
Name of the travel is "**Софійська** Площа - Фестиваль писанок"

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/231250055-1319f13a-02b4-4ca4-9bb7-996b443c46e4.png)

**Comment by scholokov** [comment]
виправлено
