### ISSUE TITLE
20170709_protsiv/In the Legend of the Map does not appear the preview photo

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3421]
Steps to reproduce:
1. Open https://test.long-travel.live/20170709_protsiv/
2. Scroll down to the Legend of the Map
3. Pay attention to the Legend of the Map

Actual Result: The preview photo does not appear in the Legend of the Map

Expected Result: The preview photo is in the Legend of the Map

Requirements: [https://github.com/scholokov/long-travel-2/wiki/4.4-Подорож.-Мапа](https://github.com/scholokov/long-travel-2/wiki/4.4-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%9C%D0%B0%D0%BF%D0%B0)

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://user-images.githubusercontent.com/123776698/231286720-65d8528e-8243-41c5-87f2-301525dc1eea.png)

**Comment by ODrobik** [comment]
#3235

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
@scholokov verified
