### ISSUE TITLE
20151031_Haisyn_Uman/The description of the travel the font type is "Open Sans"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3427]
Steps to reproduce:

1. Open https://test.long-travel.live/20151031_Haisyn_Uman/
2. Open DevTools
3. Pay attention to the font of the travel description

Actual Result: the font type is "Open Sans"
Expected Result: the font type is "Rubik"

Requirements: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-7&t=1gVCfJmfWGybYai5-0

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://user-images.githubusercontent.com/123776698/232087815-408cb71f-aff8-49a3-a895-be529aa077aa.png)

**Comment by ODrobik** [comment]
#3080

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
