### ISSUE TITLE
wiki/ The page "Home" the link "Oпис" of the Main menu does not display the necessary information

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3428]
Steps to reproduce:

1. Open: https://github.com/scholokov/long-travel-2/wiki
2. Click on the tab "Wiki"
3. Click on the page "Home"
4. Click on the link "Опис" of the main menu
5. Pay attention to the page

Actual Result: the link does not display the necessary information
Expected Result: the link displays the necessar information

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://user-images.githubusercontent.com/123776698/232093409-b51eb5c1-989c-4fc5-bfd6-6bb5c3130328.png)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
@scholokov verified
