### ISSUE TITLE
wiki/ The page "Home" the link "Oпис" of the "Головна (сторінка)" does not display the necessary information

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3439]
Steps to reproduce:
1. Open: https://github.com/scholokov/long-travel-2/wiki
2. Click on the tab "Wiki"
3. Click on the page "Home"
4. Click on the link "Опис" of the Головна (сторінка)
5. Pay attention to the page

Actual Result: the link does not display the necessary information
Expected Result: the link displays the necessary information

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://user-images.githubusercontent.com/123776698/232459562-119bb696-de7b-4686-854d-a992242618df.png)

**Comment by scholokov** [comment]
ну суто технічно з лінками там все гаразд. просто немає вимог на сторінку :)

**Comment by ODrobik** [comment]
не є помилкою
