### ISSUE TITLE
20150919_Kiev_Aviation_Museum/In the header  of the menu the Font of the element "Home" is Open Sans

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3440]
Steps to reproduce:
1. Open https://test.long-travel.live/20150919_Kiev_Aviation_Museum/
2. Pay attention to the element "Home" in the header.
3. Open DevTools.
4. Сheck font of the "Home".

Actual result: the font is "Open Sans"
Expected result: the font is "Rubik"

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:

![image](https://user-images.githubusercontent.com/123776698/232463335-0563bd21-f920-4e5f-ab1c-0b0f9d72e15c.png)

**Comment by scholokov** [comment]
fixed
