### ISSUE TITLE
20160710_0807_italy_odessa/The travel name of the video gallery of Road Nyirbator - Drobolach block is Magyarország-Austria (Magyarország in Hungarian)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3441]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the Road Nyirbator - Drobolach block.

3. Pay attention to the travel name of the video gallery.

**Actual result:**
The travel name of the video gallery of Road Nyirbator - Drobolach block is Magyarország-Austria (Magyarország in Hungarian)

**Expected result:**
The travel name of the video gallery of Road Nyirbator - Drobolach block must be Hungary-Austria (Magyarország must be in English - Hungary)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://user-images.githubusercontent.com/125134112/232471631-340ce19b-5626-4e37-89cb-517c3d6a4050.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/232474178-5a71de79-30df-4fb5-b17e-ad74ddc953cf.png)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
