### ISSUE TITLE
20160710_0807_italy_odessa/The travel name of the fourth video gallery of Road Nyirbator - Drobolach block is Magyarország, Budapest 2.3 (Magyarország in Hungarian)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3444]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the Road Nyirbator - Drobolach block.

3. Pay attention to the travel name of the fourth video gallery.

**Actual result:**
The travel name of the fourth video gallery of Road Nyirbator - Drobolach block is Magyarország, Budapest 2.3 (Magyarország in Hungarian)

**Expected result:**
The travel name of the fourth video gallery of Road Nyirbator - Drobolach block must be Hungary, Budapest 2.3 (Magyarország must be in English)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://user-images.githubusercontent.com/125134112/232480419-92cad551-9fe2-4a81-9d59-811799826bc1.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/232481477-183090fc-3b15-485a-a4c1-37bd349fbe5b.png)

**Comment by scholokov** [comment]
виправлено
