### ISSUE TITLE
20150523_picnic_dnipro/In the Global map the Travel list the name of the travel  is "Пікнік біля Дніпра"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3446]
Steps to reproduce:
1. Open page https://test.long-travel.live/travels/
2. Scroll down to the Travel list of travel 20150523_picnic_dnipro
3. Pay attention to the NAME of travel

Actual Result: the name of the travel is "Пікнік біля Дніпра"
Expected Result: the name of the travel is "2015.05.23 Кийлів, Пікнік біля Дніпра"

Requirements: [https://github.com/scholokov/long-travel-2/wiki/3.-Подорожі](https://github.com/scholokov/long-travel-2/wiki/3.2-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%93%D0%BB%D0%BE%D0%B1%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0-%D0%BA%D0%B0%D1%80%D1%82%D0%B0-%D0%B7-%D0%BC%D0%B0%D1%80%D1%88%D1%80%D1%83%D1%82%D0%B0%D0%BC%D0%B8)

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://user-images.githubusercontent.com/123776698/233046035-0d05187c-a4cd-4b73-a193-2bb42bee2156.png)

**Comment by scholokov** [comment]
назва подорожі має формуватися за цим документом:
https://github.com/scholokov/long-travel-2/wiki/3.2-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%93%D0%BB%D0%BE%D0%B1%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0-%D0%BA%D0%B0%D1%80%D1%82%D0%B0-%D0%B7-%D0%BC%D0%B0%D1%80%D1%88%D1%80%D1%83%D1%82%D0%B0%D0%BC%D0%B8

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
