### ISSUE TITLE
20170605_kiev_mariinskiy/ The font-family of the text is Open-Sans

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3450]
**Pre-conditions:**
Open https://test.long-travel.live/20170605_kiev_mariinskiy/

**Steps to reproduce:**
1.Find header
2.Pay attention to the font-family of the text  "Long-Travel".

**Actual result:**
The font-family of the text is Open-Sans

**Expected result:**
The font-family of the text  is Rubic

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Additional information**
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1201-27&t=GpuU0ZV9qDZeBl3R-0

**Attachment:**
![7YQpCziwJf](https://user-images.githubusercontent.com/123729744/232748871-a2a9d65c-6ef7-421f-834a-9566f4438f10.png)

**Comment by scholokov** [comment]
fixed
