### ISSUE TITLE
20170605_kiev_mariinskiy/ The font-family of the text is Open-Sans

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3451]
**Pre-conditions:**
Open https://test.long-travel.live/20170605_kiev_mariinskiy/

**Steps to reproduce:**
1.Find 1st preview
2.Pay attention to the font-family of the text.

**Actual result:**
The font-family of the text is Open-Sans

**Expected result:**
The font-family of the text is Amazing Slab Trial

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Additional information**
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1201-27&t=GpuU0ZV9qDZeBl3R-0

**Attachment:**
![HEGau12pcE](https://user-images.githubusercontent.com/123729744/232749983-52df893f-c393-4b70-ae46-66cc21b37c7b.png)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
canceled. bug-report isn't actual
