### ISSUE TITLE
20170416_kiev_sof_plosha/ An Extra element  "Софиевская площадь, Киев" in the Map's legend 

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3453]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170416_kiev_sof_plosha/
2. Scroll down to the Map of travel.
3. Pay attention to the text after the preview foto in the map's legend.

**Actual result:**
An extra element "Софиевская площадь, Киев" after the preview foto is in the map's legend.

**Expected result:**
An extra element "Софиевская площадь, Киев" after the preview foto does not appear in the map's legend.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/233006004-4f1f30dc-4355-4dfe-a621-0ba38201f825.png)

**Comment by GNatala** [comment]
https://github.com/scholokov/long-travel-2/issues/3226

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
passed
