### ISSUE TITLE
20170416_kiev_sof_plosha/ Name of the city in the 2-nd preview is in russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3454]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170416_kiev_sof_plosha/
2. Scroll down to the 2-nd preview.
3. Pay attention to the name of the city.

**Actual result:**
Name of the city "Киев" in the 2-nd preview is in russian.

**Expected result:**
Name of the city "Киів" in the 2-nd preview is in Ukrainian.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/233014761-bf636829-4c16-4d95-b7d0-356e4034ed81.png)

**Comment by GNatala** [comment]
https://github.com/scholokov/long-travel-2/issues/3226

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
