### ISSUE TITLE
20160710_0807_italy_odessa/The city name block (Drobollach) includes country (Austria)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3455]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the block: Drobollach.
3. Pay attention to the city name block.

**Actual result:**
The city name block (Drobollach) includes country (Austria)

**Expected result:**
The city ​​block name includes city only.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.3-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%A1%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D1%96-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8#%D0%BC%D1%96%D1%81%D1%82%D0%BE

![Image](https://user-images.githubusercontent.com/125134112/233018350-4be16fc2-3662-43b5-b9d6-1a91ebe261a9.png)

**Attachment:** 

![Image](https://user-images.githubusercontent.com/125134112/233019212-2dd17970-2658-4de9-aeca-9e1b842662b1.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
