### ISSUE TITLE
20170416_kiev_sof_plosha/ Name of the 3-rd preview is in russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3456]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170416_kiev_sof_plosha/
2. Scroll down to the 3-rd preview.
3. Pay attention to the name of the 3-rd preview.

**Actual result:**
Name of the 3-rd preview "Софиевская колокольня" is in russian.

**Expected result:**
Name of the 3-rd preview "Дзвіниця Софійського собору" is in Ukrainian.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/233021349-16b3f266-517e-450e-bcb2-dbedfaf6e080.png)

**Comment by GNatala** [comment]
#3226

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
