### ISSUE TITLE
20160710_0807_italy_odessa/The travel date in Drobollach block is "11.-13.07.2016" (DD.-DD.MM.YYYY)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3457]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to Drobollach block.

3. Pay attention to the travel date in the left side of the block.

**Actual result:**
The travel date in Drobollach block is "11.-13.07.2016" (DD.-DD.MM.YYYY)

**Expected result:**
The travel date in Drobollach block must be "11.07.2016-13.07.2016" (DD.MM.YYYY-DD.MM.YYYY)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.3-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%A1%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D1%96-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8#%D0%BC%D1%96%D1%81%D1%82%D0%BE

![Image](https://user-images.githubusercontent.com/125134112/233022049-2aa1a4e3-5009-4cd6-b7f3-7a2a5bd5e7d9.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/233383826-e3150e3f-5037-4115-bf1d-f55613dd5b24.png)

**Comment by DmytroMarkulych** [comment]
@prokopenkoga1977 Скріншот краще робити всієї сторінки і на ньому виділяти баг

**Comment by prokopenkoga1977** [comment]
Passed
