### ISSUE TITLE
20170416_kiev_sof_plosha/ Name of the city in the 3-rd preview is in russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3458]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170416_kiev_sof_plosha/
2. Scroll down to the 3-rd preview.
3. Pay attention to the name of the city.

**Actual result:**
Name of the city "Киев" in the 3-rd preview is in russian.

**Expected result:**
Name of the city "Киів" in the 3-rd preview is in Ukrainian.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://user-images.githubusercontent.com/101987790/233023007-8864ac50-0b16-473b-8254-470dbee55e3e.png)

**Comment by GNatala** [comment]
#3226

**Comment by scholokov** [comment]
fixed
