### ISSUE TITLE
20160710_0807_italy_odessa/The date format of the video gallery of Austria block is 12.07.2016 (DD.MM.YYYY)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3459]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to Austria block.

3. Pay attention to the date format of the video gallery.

**Actual result:**
The date format of the video gallery of Austria block is 12.07.2016 (DD.MM.YYYY)

**Expected result:**
The date format of the video gallery of Austria block must be 2016.07.12 (YYYY.MM.DD)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://user-images.githubusercontent.com/125134112/233050629-5f5b3725-e5ed-431e-a73c-f7490497f51d.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/233381437-d57c11cd-75b4-4920-803a-420be50a4431.png)

**Comment by DmytroMarkulych** [comment]
@prokopenkoga1977 Скріншот краще робити всієї сторінки (разом із URL) і на ньому виділяти баг

**Comment by prokopenkoga1977** [comment]
@DmytroMarkulych виправив

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
