### ISSUE TITLE
20160710_0807_italy_odessa/The date format of the first video gallery of Austria block is 12.07.2016 (DD.MM.YYYY)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3460]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to Austria block.

3. Pay attention to the date format of the first video gallery.

**Actual result:**
The date format of the frst video gallery of Austria block is 12.07.2016 (DD.MM.YYYY)

**Expected result:**
The date format of the first video gallery of Austria block must be 2016.07.12 (YYYY.MM.DD)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://user-images.githubusercontent.com/125134112/233054497-d653f3c0-5aff-4bae-96a7-967035dcd342.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/233380610-e9c26f04-e577-450b-a0e6-2a4e0c2242b5.png)

**Comment by DmytroMarkulych** [comment]
@prokopenkoga1977 Скріншот краще робити всієї сторінки і на ньому виділяти баг

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
