### ISSUE TITLE
20160710_0807_italy_odessa/The date format of the secod video gallery of Austria block is 2016.07. (YYYY.MM.)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3461]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to Austria block.

3. Pay attention to the date format of the second video gallery.

**Actual result:**
The date format of the secod video gallery of Austria block is 2016.07. (YYYY.MM.)

**Expected result:**
The date format of the second video gallery of Austria block must be 2016.07.12 (YYYY.MM.DD)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://user-images.githubusercontent.com/125134112/233056767-4b1cdefa-3547-4385-950c-fc734030f92e.png)

**Attachment:** 

![Image](https://user-images.githubusercontent.com/125134112/233380333-9beedcb1-af21-4ccd-bce2-9c2f61237284.png)

**Comment by prokopenkoga1977** [comment]
@DmytroMarkulych виправив

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
