### ISSUE TITLE
/travels/ Travel name Київ - Сергіївка not meet the requirements

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3462]
Steps to reproduce:
1.Open https://test.long-travel.live/travels/
2.Chek the travel titlle  Київ - Сергіївка

Actual result:
Київ- Сергіївка

Expected result:
Сергіївка

Attachment:
https://github.com/scholokov/long-travel-2/wiki/3.1-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%9F%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177
![2023-04-19_15h14_50](https://user-images.githubusercontent.com/125903734/233074706-7f20e840-0f0a-47c5-803e-ff06180cfb24.png)

**Comment by scholokov** [comment]
fixed

**Comment by ViktoriaZamkova** [comment]
verified
