### ISSUE TITLE
/travels/ Travel date in travel “Лиса Гора” – Коктейль бар not meet the requirements

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3464]
Steps to reproduce:
1.Open https://test.long-travel.live/travels/
2.Chek the travel date in travel “Лиса Гора” – Коктейль бар

Actual result:
16.10.21

Expected result:
25.10.2020

Attachment:
https://github.com/scholokov/long-travel-2/wiki/3.1-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%9F%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177
![2023-04-19_16h33_30](https://user-images.githubusercontent.com/125903734/233092965-7a9bcee7-7689-4c7f-9324-99cb8d6f1d50.png)

**Comment by DmytroMarkulych** [comment]
![Image](https://user-images.githubusercontent.com/88647733/233341005-f2114484-ba68-477f-86eb-0c7aa5a4465a.png)

**Comment by ViktoriaZamkova** [comment]
corrected

**Comment by ViktoriaZamkova** [comment]
verified
