### ISSUE TITLE
/20210516_lazalky/  Travel date in travel Парк “Совки” not meet the requirements

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3465]
Steps to reproduce:
1.Open https://test.long-travel.live/travels/
2.Chek the travel date in travel Парк “Совки”

Actual result:
04.10.2021

Expected result:
16.05.2021

Attachment:
https://github.com/scholokov/long-travel-2/wiki/3.1-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%9F%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177

![2023-04-19_16h41_44](https://user-images.githubusercontent.com/125903734/233094603-01d58873-2b28-4a1e-bbe6-966b5db9b015.png)

**Comment by scholokov** [comment]
додайте буд ласка айді подорожі

**Comment by ViktoriaZamkova** [comment]
corrected

**Comment by scholokov** [comment]
виправлено

**Comment by ViktoriaZamkova** [comment]
verified
