### ISSUE TITLE
20190720_0811_balcans - Body - The logical block "Hotel: Apartments Dan Mija Romania 20.07.2019 – 23.07.2019" is missing a preview

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3468]
**Steps of reproducing:**
1.  Open https://www.long-travel.live/20190720_0811_balcans/
2.  Scroll to logical block "Hotel: Apartments Dan Mija Romania 20.07.2019 – 23.07.2019" at Body
3. Pay attention to the location of the preview of the logical block "Hotel: Apartments Dan Mija Romania 20.07.2019 – 23.07.2019" 

**Actual Result**
Preview is missing

**Expected Result**
Preview is present

**Additional information**
Required preview type: Hotel
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 112.0.5615.138 (64 bit)
Android 8.1.0, Chrome 112.0.5615.48
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 19 04 2023 16_42_11](https://user-images.githubusercontent.com/95171672/233105655-c0e834d6-1221-474f-9b76-6fe6be6945a5.png)
![photo_2023-04-19_17-22-42](https://user-images.githubusercontent.com/95171672/233105667-77db9c05-0edb-45c2-904c-6cb729667363.jpg)

**Comment by scholokov** [comment]
виправлено

**Comment by DmitriiNasonov** [comment]
перевірено. помилка не відтворюється
