### ISSUE TITLE
20150919_Kiev_Aviation_Museum/In the Global map is missing route

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3473]
Steps to reproduce:
1. Open https://test.long-travel.live/travels/
2. Choose the travel "Державний музей авіації осінь 2015" in the travel list 
3. Pay attention to the Global Map

Actual Result: In the Global map is missing route
Expected Result: In the Global map is present route

Requirements: https://github.com/scholokov/long-travel-2/wiki/3.2-Подорожі.-Глобальна-карта-з-маршрутами

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://user-images.githubusercontent.com/123776698/233664563-ee68485d-cb58-444f-8aa9-864a6c021fce.png)

**Comment by ODrobik** [comment]
#2995

**Comment by scholokov** [comment]
але то не ті вимоги. ось по тому розділу (по саме цій помилці пункт 2.6):
https://github.com/scholokov/long-travel-2/wiki/4.4-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%9C%D0%B0%D0%BF%D0%B0
