### ISSUE TITLE
20170612_buki-Header-Spelling error "Буцький каньон"

### ISSUE THREAD

**Issue by WANteddddd** [scholokov/long-travel-2#3474]
Steps of reproducing:
1. Open https://www.test.long-travel.live/20170612_buki
2. Pay attention to the preview
Espessialy word: "каньон"

Actual result: "Буцький каньон"

Expected result: "Буцький каньйон"

Environment:
Windows 10 ITSC (x64),
Google Chrome v 108.0.5359.125 (x64)

Attachment:

![2023_04_21_23_03_58_](https://user-images.githubusercontent.com/119532002/233725361-b0c932f8-55e5-4d9f-aa27-4600fd0fb649.png)

**Comment by scholokov** [comment]
fixed

**Comment by WANteddddd** [comment]
Перевірив
