### ISSUE TITLE
20170612_buki-Legend-Spelling error "Букский каньон"

### ISSUE THREAD

**Issue by WANteddddd** [scholokov/long-travel-2#3475]
Steps of reproducing:

1. Open https://www.test.long-travel.live/20170612_buki
2. Pay attention to the Legend

Actual result: "Букский каньон"

Expected result: "Буцький каньйон"

Environment:
Windows 10 ITSC (x64),
Google Chrome v 108.0.5359.125 (x64)

Attachment:

![2023_04_21_23_15_39_](https://user-images.githubusercontent.com/119532002/233728521-283f34ba-1df9-49ae-9036-28b966089461.png)

**Comment by scholokov** [comment]
fixed

**Comment by WANteddddd** [comment]
Перевірив
