### ISSUE TITLE
20170612_buki-Global map-Spelling error "Букский каньон"

### ISSUE THREAD

**Issue by WANteddddd** [scholokov/long-travel-2#3477]
Steps of reproducing:

1. Open https://test.long-travel.live/travels/
2. On Global map find a travel in legend
3. Pay attention to the Legend

Actual result: "Букский каньон"

Expected result: "Буцький каньйон"

Environment:
Windows 10 ITSC (x64),
Google Chrome v 108.0.5359.125 (x64)

Attachment:

![2023_04_21_23_37_23_](https://user-images.githubusercontent.com/119532002/233730275-8ce4c0d1-941e-4d35-afcd-e81633c07bb5.png)

**Comment by scholokov** [comment]
fixed

**Comment by WANteddddd** [comment]
Перевірив
