### ISSUE TITLE
Travels-Spelling error "Буцький каньон"

### ISSUE THREAD

**Issue by WANteddddd** [scholokov/long-travel-2#3478]
Steps of reproducing:

1. Open https://test.long-travel.live/travels/
2. Scroll down and find travel "Буцький каньон"
3. Pay attention to the name travel

Actual result: "Буцький каньон"

Expected result: "Буцький каньйон"

Environment:
Windows 10 ITSC (x64),
Google Chrome v 108.0.5359.125 (x64)

Attachment:
Link to travel: https://test.long-travel.live/20170612_buki/

![2023_04_21_23_41_58_NVIDIA_GeForce_Overlay](https://user-images.githubusercontent.com/119532002/233732107-2dbccce4-6322-42bd-84cf-16ca02243c0d.png)

**Comment by scholokov** [comment]
будь ласка додайте аййді подорожі

**Comment by WANteddddd** [comment]
Додав.

**Comment by WANteddddd** [comment]
Перевірив
