### ISSUE TITLE
20190720_0811_balcans - Body - The logical block "Hotel: Apartments Dan Mija" is missing a preview

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3479]
**Steps of reproducing:**
1.  Open https://www.long-travel.live/20190720_0811_balcans/
2.  Scroll to logical block "Hotel: Apartments Dan Mija" at Body
3. Pay attention to the location of the preview of the logical block "Hotel: Apartments Dan Mija" 

**Actual Result**
Preview is missing

**Expected Result**
Preview is present

**Additional information**
Required preview type: Hotel
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 112.0.5615.138 (64 bit)
Android 8.1.0, Chrome 112.0.5615.48
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 22 04 2023 16_59_59](https://user-images.githubusercontent.com/95171672/233789429-c25006db-77e9-4822-ad4e-0e62f01c8719.png)
![photo_2023-04-22_16-58-03](https://user-images.githubusercontent.com/95171672/233789430-331f163e-fdc2-4465-a6e0-e06bdec3bf6e.jpg)

**Comment by scholokov** [comment]
виправлено

**Comment by DmitriiNasonov** [comment]
перевірено. помилка не відтворюється
