### ISSUE TITLE
20190720_0811_balcans - Body - The logical block "Transfagarasan Road" is missing a preview

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3480]
**Steps of reproducing:**
1.  Open https://www.long-travel.live/20190720_0811_balcans/
2.  Scroll to logical block "Transfagarasan Road" at Body
3. Pay attention to the location of the preview of the logical block "Transfagarasan Road" 

**Actual Result**
Preview is missing

**Expected Result**
Preview is present

**Additional information**
Required preview type: Road
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 112.0.5615.138 (64 bit)
Android 8.1.0, Chrome 112.0.5615.48
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 22 04 2023 17_04_12](https://user-images.githubusercontent.com/95171672/233789735-9ded6e8f-b8c1-4e03-83c4-e1231d71e151.png)
![photo_2023-04-22_17-04-51](https://user-images.githubusercontent.com/95171672/233789738-8dc998b8-c0f6-48c1-9736-aac7af86d488.jpg)

**Comment by scholokov** [comment]
виправлено

**Comment by DmitriiNasonov** [comment]
перевірено. помилка не відтворюється
