### ISSUE TITLE
20190720_0811_balcans - Body - The logical block "Salina Turda" is missing a preview

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3481]
**Steps of reproducing:**
1.  Open https://www.long-travel.live/20190720_0811_balcans/
2.  Scroll to logical block "Salina Turda" at Body
3. Pay attention to the location of the preview of the logical block "Salina Turda" 

**Actual Result**
Preview is missing

**Expected Result**
Preview is present

**Additional information**
Required preview type: Cave
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 112.0.5615.138 (64 bit)
Android 8.1.0, Chrome 112.0.5615.48
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 22 04 2023 17_11_44](https://user-images.githubusercontent.com/95171672/233790386-9b2c7bad-dd95-495c-a653-90b4da649ed0.png)
![photo_2023-04-22_17-21-29](https://user-images.githubusercontent.com/95171672/233790389-d03046fd-7310-4524-8f91-d2234cc84676.jpg)

**Comment by scholokov** [comment]
виправлено
