### ISSUE TITLE
20190720_0811_balcans - Body - The logical block "Road: Medias – Targu Jiu, Transalpina Road" is missing a preview

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3482]
**Steps of reproducing:**
1.  Open https://www.long-travel.live/20190720_0811_balcans/
2.  Scroll to logical block "Road: Medias – Targu Jiu, Transalpina Road" at Body
3. Pay attention to the location of the preview of the logical block "Road: Medias – Targu Jiu, Transalpina Road" 

**Actual Result**
Preview is missing

**Expected Result**
Preview is present

**Additional information**
Required preview type: Road
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 112.0.5615.138 (64 bit)
Android 8.1.0, Chrome 112.0.5615.48
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 22 04 2023 17_29_40](https://user-images.githubusercontent.com/95171672/233790782-62533627-c2a8-4e5b-a755-01866b0e2280.png)
![photo_2023-04-22_17-28-09](https://user-images.githubusercontent.com/95171672/233790784-8ff0e941-4b60-49f8-a563-f6bf45f32428.jpg)

**Comment by scholokov** [comment]
виправлено

**Comment by DmitriiNasonov** [comment]
перевірено. помилка не відтворюється
