### ISSUE TITLE
20190720_0811_balcans - Body - The logical block "Hotel: Pensiunea Jacqueline" is missing a preview

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3483]
**Steps of reproducing:**
1.  Open https://www.long-travel.live/20190720_0811_balcans/
2.  Scroll to logical block "Hotel: Pensiunea Jacqueline" at Body
3. Pay attention to the location of the preview of the logical block "Hotel: Pensiunea Jacqueline" 

**Actual Result**
Preview is missing

**Expected Result**
Preview is present

**Additional information**
Required preview type: Hotel
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 112.0.5615.138 (64 bit)
Android 8.1.0, Chrome 112.0.5615.48
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 22 04 2023 17_32_30](https://user-images.githubusercontent.com/95171672/233790955-b7941c9a-a217-40f6-92f8-0af2cf0ddf69.png)
![photo_2023-04-22_17-34-09](https://user-images.githubusercontent.com/95171672/233790956-6223fe8b-ebb7-4540-aa9d-39ce1754a4ba.jpg)

**Comment by scholokov** [comment]
виправлено

**Comment by DmitriiNasonov** [comment]
перевірено. помилка не відтворюється
