### ISSUE TITLE
20190720_0811_balcans - Body - The logical block "Hotel: Orasac" is missing a preview

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3485]
**Steps of reproducing:**
1.  Open https://www.long-travel.live/20190720_0811_balcans/
2.  Scroll to logical block "Hotel: Orasac" at Body
3. Pay attention to the location of the preview of the logical block "Hotel: Orasac" 

**Actual Result**
Preview is missing

**Expected Result**
Preview is present

**Additional information**
Required preview type: Hotel
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 112.0.5615.138 (64 bit)
Android 8.1.0, Chrome 112.0.5615.48
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 22 04 2023 17_42_49](https://user-images.githubusercontent.com/95171672/233791502-c5aec6d8-05bb-4d80-a378-af30beef3590.png)
![photo_2023-04-22_17-47-26](https://user-images.githubusercontent.com/95171672/233791505-4deb0f39-a93a-4892-8520-dc3fc199ece7.jpg)

**Comment by scholokov** [comment]
fixed
