### ISSUE TITLE
20170709_protsiv/In the Preview block "Проців" of travel the size of the flag of Ukraine is 26x17.33 px

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3486]
Steps to reproduce:
1. Open https://test.long-travel.live/20170709_protsiv/
2. Scroll down to the Preview block "Проців"
3. Pay attention to the size of the flag of Ukraine

Actual result: the size of the flag of Ukraine is 26x17.33 px
Expected result: the size of the flag of Ukraine is 26x18 px

Requirements: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-7&t=zNYPaOfE0Mu2cemL-0

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment
![image](https://user-images.githubusercontent.com/123776698/233791671-c002817d-fae5-404e-b798-0964f9eb2d7d.png)

**Comment by ODrobik** [comment]
#3235

**Comment by scholokov** [comment]
please retest

**Comment by ODrobik** [comment]
is not relevant
