### ISSUE TITLE
20190720_0811_balcans - Body - The logical block "Belgrade" is missing a preview

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3487]
**Steps of reproducing:**
1.  Open https://www.long-travel.live/20190720_0811_balcans/
2.  Scroll to logical block "Belgrade" at Body
3. Pay attention to the location of the preview of the logical block "Belgrade" 

**Actual Result**
Preview is missing

**Expected Result**
Preview is present

**Additional information**
Required preview type: City
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 112.0.5615.138 (64 bit)
Android 8.1.0, Chrome 112.0.5615.48
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 22 04 2023 17_54_48](https://user-images.githubusercontent.com/95171672/233791876-24a2c5c8-7e1c-4357-84b0-2bf19235af7f.png)
![photo_2023-04-22_17-50-05](https://user-images.githubusercontent.com/95171672/233791878-79262764-c2e4-4a94-a0ae-0d58eb551f9e.jpg)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
verified. bug is reproducing
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 24 04 2023 17_50_34](https://user-images.githubusercontent.com/95171672/234034127-4496369f-d79d-48a1-adb3-e84aef1113ba.png)
![photo_2023-04-24_17-51-24](https://user-images.githubusercontent.com/95171672/234034150-75f2f34e-caf6-4ebb-9a53-424f0eee708a.jpg)

**Comment by scholokov** [comment]
виправлено

**Comment by DmitriiNasonov** [comment]
checked. Bug isn't reproduced
