### ISSUE TITLE
20190720_0811_balcans - Body - The logical block "Museum of Illusions" is missing a preview

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3488]
**Steps of reproducing:**
1.  Open https://www.long-travel.live/20190720_0811_balcans/
2.  Scroll to logical block "Museum of Illusions" at Body
3. Pay attention to the location of the preview of the logical block "Museum of Illusions" 

**Actual Result**
Preview is missing

**Expected Result**
Preview is present

**Additional information**
Required preview type: Museum
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 112.0.5615.138 (64 bit)
Android 8.1.0, Chrome 112.0.5615.48
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 22 04 2023 17_58_11](https://user-images.githubusercontent.com/95171672/233792212-8effcb5f-b63b-43d1-8aab-5a9a0c34e42a.png)
![photo_2023-04-22_17-59-19](https://user-images.githubusercontent.com/95171672/233792215-6a6d07dd-87e1-41b4-89da-7f7b9e4a4228.jpg)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
verified. bug isn't reproducing
