### ISSUE TITLE
20190720_0811_balcans - Body - The logical block "Road: Belgrade Serbia – Skopje Makedonia" is missing a preview

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3489]
**Steps of reproducing:**
1.  Open https://www.long-travel.live/20190720_0811_balcans/
2.  Scroll to logical block "Road: Belgrade Serbia – Skopje Makedonia" at Body
3. Pay attention to the location of the preview of the logical block "Road: Belgrade Serbia – Skopje Makedonia" 

**Actual Result**
Preview is missing

**Expected Result**
Preview is present

**Additional information**
Required preview type: Road
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 112.0.5615.138 (64 bit)
Android 8.1.0, Chrome 112.0.5615.48
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 22 04 2023 18_05_10](https://user-images.githubusercontent.com/95171672/233792373-bcb1a73b-cab4-4255-84a3-99395ffde3c0.png)
![photo_2023-04-22_18-05-19](https://user-images.githubusercontent.com/95171672/233792375-da521709-ac1d-41ef-b3f9-0dc6f5897982.jpg)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
verified. bug isn't reproducing
