### ISSUE TITLE
20190720_0811_balcans - Body - The logical block "Road: Makedonia – Albania" is missing a preview

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3492]
**Steps of reproducing:**
1.  Open https://www.long-travel.live/20190720_0811_balcans/
2.  Scroll to logical block "Road: Makedonia – Albania" at Body
3. Pay attention to the location of the preview of the logical block "Road: Makedonia – Albania" 

**Actual Result**
Preview is missing

**Expected Result**
Preview is present

**Additional information**
Required preview type: Road
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 112.0.5615.138 (64 bit)
Android 8.1.0, Chrome 112.0.5615.48
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 22 04 2023 18_25_31](https://user-images.githubusercontent.com/95171672/233793196-b6d7c5b4-34e7-48ca-9fd8-65e461f00493.png)
![photo_2023-04-22_18-26-14](https://user-images.githubusercontent.com/95171672/233793197-521ce5b8-e792-473f-a452-4f1f043a6183.jpg)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
verified. bug isn't reproducing
