### ISSUE TITLE
20190720_0811_balcans - Body - The logical block "Hotel: Appartamentto Giallo" is missing a preview

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3493]
**Steps of reproducing:**
1.  Open https://www.long-travel.live/20190720_0811_balcans/
2.  Scroll to logical block "Hotel: Appartamentto Giallo" at Body
3. Pay attention to the location of the preview of the logical block "Hotel: Appartamentto Giallo" 

**Actual Result**
Preview is missing

**Expected Result**
Preview is present

**Additional information**
Required preview type: Hotel
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 112.0.5615.138 (64 bit)
Android 8.1.0, Chrome 112.0.5615.48
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 22 04 2023 18_32_03](https://user-images.githubusercontent.com/95171672/233793506-de234de3-b542-41f3-8045-76d2d8bac388.png)
![photo_2023-04-22_18-34-18](https://user-images.githubusercontent.com/95171672/233793510-19de8496-ee92-4c21-b696-ad7377a88652.jpg)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
verified. bug isn't reproducing
