### ISSUE TITLE
/20170521_korosten/ Travel name Коростень  doesn`t meet the requirements.

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3495]
Steps to reproduce:
1.Open https://test.long-travel.live/20170521_korosten/
2.Chek the Preview

Actual result:
Коростень

Expected result:
Коростень - Військово-історичний комплекс "Скеля" - Парк імені Островського

Attachment:
https://github.com/scholokov/long-travel-2/wiki/3.1-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%9F%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 110.0.5481.177

![2023-04-23_23h11_11](https://user-images.githubusercontent.com/125903734/233863327-d1920ef3-3700-4f05-aec8-13e5ab868748.png)

![2023-04-23_16h44_54](https://user-images.githubusercontent.com/125903734/233862857-ed4ce66a-0cf6-4912-a3d3-2a460a9d3633.png)

**Comment by scholokov** [comment]
виправлено

**Comment by ViktoriaZamkova** [comment]
verified
