### ISSUE TITLE
20170605_kiev_mariinskiy/The country is represented by text and flag

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3496]
**Pre-conditions:**
Open https://test.long-travel.live/20170605_kiev_mariinskiy/

**Steps to reproduce:**
1.Find 2nd preview
2.Pay attention to the representance of the country.

**Actual result:**
The country is represented by text and flag

**Expected result:**
The country is represented by  flag

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Additional information**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0

**Attachment:**
![o1VvcnIsqE](https://user-images.githubusercontent.com/123729744/233920250-1a4b33a8-af87-42d8-adb8-e48ef032e18e.png)

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
