### ISSUE TITLE
20170605_kiev_mariinskiy/The name of city is in Russian.

### ISSUE THREAD

**Issue by OlhaHutsman** [scholokov/long-travel-2#3497]
**Pre-conditions:**
Open https://test.long-travel.live/20170605_kiev_mariinskiy/

**Steps to reproduce:**
1.Find 2nd preview
2.Pay attention to the language of the text of the  city.

**Actual result:**
The name of city is in Russian.

**Expected result:**
The name of city is in Ukrainian.

**Environment**
Windows 10 Pro (x64)
Google Chrome v 109.0.5414.120 (x64)

**Additional information**
https://github.com/scholokov/long-travel-2/wiki/1.2-%D0%9C%D0%BE%D0%B2%D0%B0

**Attachment:**
![VGAgaY2rET](https://user-images.githubusercontent.com/123729744/233921439-039d5010-0e41-47a9-b09d-4ca09404535d.png)

**Comment by GNatala** [comment]
перевірено
