### ISSUE TITLE
20190720_0811_balcans - Body - The logical block "Road: Albania – Montenegro" is missing a preview

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3501]
**Steps of reproducing:**
1.  Open https://test.long-travel.live/20190720_0811_balcans/#gallery[photonic-google-album-1]/AE29bMHjEa2F0qTw3ywHf2_Ml5mMVsGxrPSif3TawL5jd7MQoTNxpssvph1PO1VvdU3UqFn4xFcC7E6KGA9uxij5S-q9hIJewg/
2.  Scroll to logical block "Road: Albania – Montenegro" at Body
3. Pay attention to the location of the preview of the logical block "Road: Albania – Montenegro" 

**Actual Result**
Preview is missing

**Expected Result**
Preview is present

**Additional information**
Required preview type: Road
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 112.0.5615.138 (64 bit)
Android 8.1.0, Chrome 112.0.5615.135
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 24 04 2023 18_30_15](https://user-images.githubusercontent.com/95171672/234044686-4a6b6685-9991-43fd-a8c4-b052b69c47e0.png)
![photo_2023-04-24_18-30-34](https://user-images.githubusercontent.com/95171672/234044697-1bfe9b13-c419-4865-aa6b-8807a8b317a9.jpg)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. Bug isn't reproduced
