### ISSUE TITLE
20190720_0811_balcans - Body - The logical block "Llogara Pass" is missing a preview

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3502]
**Steps of reproducing:**
1.  Open https://test.long-travel.live/20190720_0811_balcans/#gallery[photonic-google-album-1]/AE29bMHjEa2F0qTw3ywHf2_Ml5mMVsGxrPSif3TawL5jd7MQoTNxpssvph1PO1VvdU3UqFn4xFcC7E6KGA9uxij5S-q9hIJewg/
2.  Scroll to logical block "Llogara Pass" at Body
3. Pay attention to the location of the preview of the logical block "Llogara Pass" 

**Actual Result**
Preview is missing

**Expected Result**
Preview is present

**Additional information**
Required preview type: Mountain
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 112.0.5615.138 (64 bit)
Android 8.1.0, Chrome 112.0.5615.135
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 24 04 2023 18_34_53](https://user-images.githubusercontent.com/95171672/234045837-896a3ffd-5326-4e14-8074-b529fb8077f9.png)
![photo_2023-04-24_18-35-16](https://user-images.githubusercontent.com/95171672/234045846-92910ec2-7b66-4bb3-96d6-83e4503f7b85.jpg)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. Bug isn't reproduced
