### ISSUE TITLE
20190720_0811_balcans - Body - The logical block "Albania Tirana" is missing a preview

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3503]
**Steps of reproducing:**
1.  Open https://test.long-travel.live/20190720_0811_balcans/#gallery[photonic-google-album-1]/AE29bMHjEa2F0qTw3ywHf2_Ml5mMVsGxrPSif3TawL5jd7MQoTNxpssvph1PO1VvdU3UqFn4xFcC7E6KGA9uxij5S-q9hIJewg/
2.  Scroll to logical block "Albania Tirana" at Body
3. Pay attention to the location of the preview of the logical block "Albania Tirana" 

**Actual Result**
Preview is missing

**Expected Result**
Preview is present

**Additional information**
Required preview type: Metropolis
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 112.0.5615.138 (64 bit)
Android 8.1.0, Chrome 112.0.5615.135
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 24 04 2023 18_38_58](https://user-images.githubusercontent.com/95171672/234047588-d370f5fe-2a01-4de3-aa75-3759b9f0019f.png)
![photo_2023-04-24_18-41-44](https://user-images.githubusercontent.com/95171672/234047599-4da2ed43-48a8-4391-836a-f1041bc8fbb3.jpg)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. Bug isn't reproduced
