### ISSUE TITLE
Travels/Global map/In block "Legend"/20170612_buki/Preview photo is missed

### ISSUE THREAD

**Issue by WANteddddd** [scholokov/long-travel-2#3507]
Steps to reproducing:
1. Open https://test.long-travel.live/travels/
2. Search the travel "20170612_buki"
3. Pay attention to the photo preview

Actual result:
photo is missing

Expected result:
the photo is present

Environment:
Windows 10 ITSC (x64),
Google Chrome v 108.0.5359.125 (x64)

Attachment:
![2023_04_24_19_02_56_](https://user-images.githubusercontent.com/119532002/234111482-fc2bd071-f8b5-4c91-b9ce-1849b70cb19a.png)

**Comment by DmytroMarkulych** [comment]
@WANteddddd Summary повинно відповідати на питання: Де? Що? Коли?

**Comment by WANteddddd** [comment]
Змінив

**Comment by DmytroMarkulych** [comment]
@WANteddddd Зробіть будь ласка більш обширніше summary з більшею кількістю деталей

**Comment by WANteddddd** [comment]
Змінив

**Comment by scholokov** [comment]
fixedd

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
