### ISSUE TITLE
20170612_buki-Body-Logical block "Дорога Буки - Київ "-Video date format 06.12.2017

### ISSUE THREAD

**Issue by WANteddddd** [scholokov/long-travel-2#3509]
Steps to reproducing:

1. Open https://www.test.long-travel.live/20170612_buki
2. Scroll to the block "Дорога Буки-Київ"
3. Pay attention in the caption of the video

Actual result:
12.06.2017

Expected result:
2017.06.12

Environment:
Windows 10 ITSC (x64),
Google Chrome v 108.0.5359.125 (x64)

Attachment:
![2023_04_24_19_52_24_20170612_buki_3232_Andrii_Danylenko_TestRail](https://user-images.githubusercontent.com/119532002/234115399-d2e99050-0b88-4a8a-a63c-5457a3b79b68.png)
![2023_04_24_19_50_54_](https://user-images.githubusercontent.com/119532002/234115550-f1469a27-e594-40ab-8d3c-1110250fcdaa.png)

**Comment by DmytroMarkulych** [comment]
@WANteddddd При формуванні Summary не використовуйте слова типу "not correct" та подібні ним.

**Comment by WANteddddd** [comment]
В Summary відповів на питання де? що? коли? ,правильно написано?

**Comment by DmytroMarkulych** [comment]
@WANteddddd 
Якщо говорити про даний дефект як приклад, то можна сформулювати наступним чином:
Де? - В блоці "Дорога Буки-Київ" Що?- формат дати відео 12.06.2017 

В даному випадку можна упустити "Коли?", тому що ми не робимо ніяких кліків на елементи сайту.

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
