### ISSUE TITLE
20160710_0807_italy_odessa/The date format of the first video gallery of Road Drobollach - Italy block is 13.07.2016 (DD.MM.YYYY)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3513]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to Road Drobollach - Italy block.

3. Pay attention to the date format of the first video gallery.

**Actual result:**
The date format of the first video gallery of Road Drobollach - Italy block is 13.07.2016 (DD.MM.YYYY)

**Expected result:**
The date format of the first video gallery of Road Drobollach - Italy block must be 2016.07.13. (YYYY.MM.DD.)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://user-images.githubusercontent.com/125134112/234211074-c137e344-98cb-4655-b743-f454c2de7dac.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/234226177-7c3e1344-e14e-4fea-8249-c0ad6bbcebb2.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
