### ISSUE TITLE
20150919_Kiev_Aviation_Museum/The Home page the Photo is not displayed

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3515]
Steps to reproduce
1. Open https://test.long-travel.live
2. Pay attention to the photo in the Home page

Actual result:  the photo is not displayed
Expected result: the photo is displayed

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://user-images.githubusercontent.com/123776698/234252373-f14b9af3-b26d-4eb4-8b4c-47f77e09bbd8.png)

**Comment by ODrobik** [comment]
#2995

**Comment by scholokov** [comment]
please retest

**Comment by ODrobik** [comment]
verified
