### ISSUE TITLE
20180204_zhitomyr / Missed preview photo in the block "Дорога - Киев - Житомир"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3519]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20180204_zhitomyr
2. Pay attention to the absence of the photo in the block "Дорога - Киев - Житомир".

**Actual result:**
Preview photo is not displayed in the block "Дорога - Киев - Житомир".

**Expected result:**
Preview photo is displayed in the block "Дорога - Киев - Житомир".

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/234584568-1fdeee2d-0169-41b3-b8b4-8e9670059cba.png)

**Comment by GNatala** [comment]
https://github.com/scholokov/long-travel-2/issues/3431

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
