### ISSUE TITLE
20180204_zhitomyr / Ukranian flag is missed in the 1st Preview 

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3520]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20180204_zhitomyr
2. Pay attention to the absence Ukranian flag is missed in the 1st Preview.

**Actual result:**
Ukranian flag is missed in the 1st Preview.

**Expected result:**
Ukranian flag is displayed the 1st Preview..

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/234587200-d5812c5a-b7be-45aa-8c37-ad817b7a35f7.png)

**Comment by GNatala** [comment]
#3431

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
