### ISSUE TITLE
20180204_zhitomyr / Missed preview photo in the block "Варенична. Балувана Галя"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3521]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20180204_zhitomyr
2. Pay attention to the absence of the photo in the block "Варенична. Балувана Галя".

**Actual result:**
Preview photo is not displayed in the block "Варенична. Балувана Галя".

**Expected result:**
Preview photo is displayed in the block "Варенична. Балувана Галя".

**Additional information**
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/234593497-1d6b52b1-b4d6-4e22-8df0-4114946ed1fc.png)

**Comment by GNatala** [comment]
#3431

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
