### ISSUE TITLE
20180204_zhitomyr / Missed preview photo in the block "Музей космонавтики імені Сергія Павловича Корольова"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3523]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20180204_zhitomyr
2. Pay attention to the absence of the photo in the block "Музей космонавтики імені Сергія Павловича Корольова".

**Actual result:**
Preview photo is not displayed in the block "Музей космонавтики імені Сергія Павловича Корольова".

**Expected result:**
Preview photo is displayed in the block "Музей космонавтики імені Сергія Павловича Корольова".

**Additional information**
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/234597433-358f4777-0565-4120-801c-d76a4b4e6c30.png)

**Comment by GNatala** [comment]
#3431

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
