### ISSUE TITLE
wiki/ The page "3.2-Подорожі.-Глобальна-карта-з-маршрутами" is spelling mistake in the word "виборорі"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3526]
Steps to reproduce:
1. Open: https://github.com/scholokov/long-travel-2/wiki/3.2-Подорожі.-Глобальна-карта-з-маршрутами
2. Pay attention to the word "виборорі" 

Actual Result: the word "виборорі"
Expected Result: the word "виборі"

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://user-images.githubusercontent.com/123776698/234709800-bbc58106-b2bf-4fcb-bd7a-b563a0efaa60.png)

**Comment by scholokov** [comment]
виправлено
