### ISSUE TITLE
20150919_Kiev_Aviation_Museum/In the Global map the Drop-down list of the travel the name of the travel is "Державний музей авіації осінь 2015"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3527]
Steps to reproduce:

1. Open page https://test.long-travel.live/travels/
2. Scroll down to the Travel drop-down list of travel 20150919_Kiev_Aviation_Museum
3. Pay attention to the NAME of travel

Actual Result:  Name of the travel is "Державний музей авіації осінь 2015"
Expected Result: Name of the travel is "2015.09.19 Державний музей авіації осінь 2015"

Requirements: https://github.com/scholokov/long-travel-2/wiki/3.2-Подорожі.-Глобальна-карта-з-маршрутами

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://user-images.githubusercontent.com/123776698/234847415-10f78420-0ec4-41f7-ba17-30bb689f9073.png)

**Comment by ODrobik** [comment]
#2995

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
