### ISSUE TITLE
/20210508_12months/  Travel Зоопарк "XII Месяців" 2021 has an error in name

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3528]
Steps to reproduce:
1.Open https://github.com/scholokov/long-travel-2/wiki/3.1-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%9F%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA
2.Chek the travel name   084 20210508_12months

Actual result:
Зоопарк "XII Месяців" 2021

Expected result:
Зоопарк "XII Місяців" 2021

Attachment:
https://github.com/scholokov/long-travel-2/wiki/3.1-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%9F%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 112.0.5615.138
![2023-04-27_14h35_24](https://user-images.githubusercontent.com/125903734/234850463-539a0af2-0a9b-4f34-9542-34a0cbde8fe4.png)

**Comment by scholokov** [comment]
виправлено

**Comment by ViktoriaZamkova** [comment]
verified
