### ISSUE TITLE
20160710_0807_italy_odessa/The link to Hotel – Residence Domus, Rimini is missed in Hotel – Residence Domus, Rimini block

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3529]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to Hotel – Residence Domus, Rimini block.

3. Pay attention to the absence of a link to the hotel in the left side of the block.

**Actual result:**
The link to Hotel – Residence Domus, Rimini is missed 

**Expected result:**
The link to Hotel – Residence Domus, Rimini must be in Hotel – Residence Domus, Rimini block 

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.3-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%A1%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D1%96-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8#hotel
![Image](https://user-images.githubusercontent.com/125134112/234855964-8f4f1c82-63bd-49fc-93f5-6143d84397ad.png)
**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/234856857-57080371-d6e3-461e-961c-7d7b6c9e7df4.png)

**Comment by scholokov** [comment]
fixed
