### ISSUE TITLE
/20210508_12months/ Travel name Парк XII місяців  doesn`t meet with requirements

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3530]
Steps to reproduce:
1.Open https://test.long-travel.live/travels/
2.Chek the travel Парк XII місяців 

Actual result:
Парк XII місяців 

Expected result:
Зоопарк "XII Місяців"

Attachment:
https://github.com/scholokov/long-travel-2/wiki/3.1-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%9F%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 112.0.5615.138

![2023-04-27_14h54_22](https://user-images.githubusercontent.com/125903734/234857276-a65953a5-420a-4d0c-a5ff-7b58595e3730.png)

**Comment by scholokov** [comment]
fixed

**Comment by ViktoriaZamkova** [comment]
verified
