### ISSUE TITLE
20160710_0807_italy_odessa/The travel date in Hotel – Residence Domus, Rimini block is "14.-20.07.2016" (DD.-DD.MM.YYYY)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3531]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to  Hotel – Residence Domus, Rimini block.

3. Pay attention to the travel date in the left side of the block.

**Actual result:**
The travel date in  Hotel – Residence Domus, Rimini block is "14.-20.07.2016" (DD.-DD.MM.YYYY)

**Expected result:**
The travel date in  Hotel – Residence Domus, Rimini block must be "14.07.2016-20.07.2016" (DD.MM.YYYY-DD.MM.YYYY)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.3-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%A1%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D1%96-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8#hotel

![Image](https://user-images.githubusercontent.com/125134112/234860305-26272e0b-7716-4282-affa-cde37947147b.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/234860975-3aba7fc7-7d9b-4745-a578-0bd9859794df.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
