### ISSUE TITLE
20170709_protsiv/In the Legend of the Map is an extra element "Protsiv" 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3532]
Steps to reproduce:

1. Open https://test.long-travel.live/20170709_protsiv/
2. Scroll down to the Legend of the Map
3. Pay attention to the text after preview foto in the Legend of the Map

Actual Result:  An extra element "Protsiv" is in the Legend of the Map
Expected Result: An extra element "Protsiv" does not appear in the Legend of the Map

Requirements: https://github.com/scholokov/long-travel-2/wiki/4.4-Подорож.-Мапа

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://user-images.githubusercontent.com/123776698/235189234-d33e7bd8-3113-4cd1-b0ff-42ea6804f0f9.png)

**Comment by ODrobik** [comment]
#3235

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
