### ISSUE TITLE
20190720_0811_balcans - Body - The logical block "Road: Montenegro – Bosnia and Herzegovina" is missing a preview

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3534]
**Steps of reproducing:**
1.  Open https://test.long-travel.live/20190720_0811_balcans/#gallery[photonic-google-album-1]/AE29bMHjEa2F0qTw3ywHf2_Ml5mMVsGxrPSif3TawL5jd7MQoTNxpssvph1PO1VvdU3UqFn4xFcC7E6KGA9uxij5S-q9hIJewg/
2.  Scroll to logical block "Road: Montenegro – Bosnia and Herzegovina" at Body
3. Pay attention to the location of the preview of the logical block "Road: Montenegro – Bosnia and Herzegovina" 

**Actual Result**
Preview is missing

**Expected Result**
Preview is present

**Additional information**
Required preview type: Road
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 112.0.5615.138 (64 bit)
Android 8.1.0, Chrome 112.0.5615.135

![Image](https://user-images.githubusercontent.com/95171672/235473735-43916b49-1f08-45f8-aee7-fa89235bd9fe.png)

![photo_2023-05-01_18-02-25](https://user-images.githubusercontent.com/95171672/235473126-877b986d-7bf2-4cd7-a939-f31b27b5303c.jpg)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
