### ISSUE TITLE
20190720_0811_balcans - Body - Logical block name "Hotel: Apartment Gubec" is #222222 (Dark grey)

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3538]
**Steps of reproducing:**
Open https://www.long-travel.live/20190720_0811_balcans/
Sctoll to logical block "Croatia"
Pay attention to the color of the text "Hotel: Apartment Gubec" above the text "Croatia"

**Actual Result**
Color of the text "Hotel: Apartment Gubec" is #222222

**Expected Result**
Color of the text "Hotel: Apartment Gubec" is #FFFFFF

**Additional information**
The text "Hotel: Apartment Gubec" blends in with the color of the site. To see it, you need to select this text with the left mouse button or look closely
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1201-2459&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 112.0.5615.138 (64 bit)
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 02 05 2023 17_49_04](https://user-images.githubusercontent.com/95171672/235702564-2cda2f34-cc44-4a1d-acf4-ea15de6cb856.png)

![DevTools - test long-travel live_20190720_0811_balcans_ 01 05 2023 18_56_51](https://user-images.githubusercontent.com/95171672/235482937-f49a9d13-221f-4a54-aa8b-8bdb17160cc1.png)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
