### ISSUE TITLE
20190720_0811_balcans - Body - Logical block name "Osijec Croatia" is #222222 (Dark grey)

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3539]
**Steps of reproducing:**
1. Open https://www.long-travel.live/20190720_0811_balcans/
2. Scroll to the second logical block "Croatia" (which is without a booking link)
3. Pay attention to the color of the text "Osijec Croatia" above the text "Croatia"

**Actual Result**
Color of the text "Osijec Croatia" is #222222

**Expected Result**
Color of the text "Osijec Croatia" is #FFFFFF

**Additional information**
The text "Osijec Croatia" blends in with the color of the site. To see it, you need to select this text with the left mouse button or look closely
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1201-2459&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 112.0.5615.138 (64 bit)
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 02 05 2023 17_27_45](https://user-images.githubusercontent.com/95171672/235701343-f3c68432-35a4-4014-aaff-e1e5e8851a99.png)
![DevTools - test long-travel live_20190720_0811_balcans_ 02 05 2023 17_24_48](https://user-images.githubusercontent.com/95171672/235701363-d7d39a53-7a52-4024-a4fd-ed05ab3bb2a3.png)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
