### ISSUE TITLE
20190720_0811_balcans - Body - Logical block name "Road: Croatia – Hungary" is #222222 (Dark grey)

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3540]
**Steps of reproducing:**
Open https://www.long-travel.live/20190720_0811_balcans/
Sctoll to logical block "Croatia Hungary"
Pay attention to the color of the text "Road: Croatia – Hungary" above the text "Croatia Hungary"

**Actual Result**
Color of the text "Road: Croatia – Hungary" is #222222

**Expected Result**
Color of the text "Road: Croatia – Hungary" is #FFFFFF

**Additional information**
The text "Road: Croatia – Hungary" blends in with the color of the site. To see it, you need to select this text with the left mouse button or look closely
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1201-2459&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 112.0.5615.138 (64 bit)
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 02 05 2023 17_52_08](https://user-images.githubusercontent.com/95171672/235704304-8ed5b37d-b675-49f4-bc7b-4c6a0db01791.png)
![DevTools - test long-travel live_20190720_0811_balcans_ 02 05 2023 17_52_26](https://user-images.githubusercontent.com/95171672/235704317-f27139ad-09e7-467f-8acc-dba549a9c751.png)

**Comment by scholokov** [comment]
виправлено

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
