### ISSUE TITLE
/20170521_korosten/ Travel name doesn`t meet with requirements .

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3541]
Steps to reproduce:
1.Open https://test.long-travel.live/20170521_korosten/
2.Chek the Preview

Actual result:
Коростень – Військово-історичний комплекс “Скеля” – Парк імені Островського
21.05.2017

Житомирська область, Украина
21.05.2017

Expected result:
Коростень – Військово-історичний комплекс “Скеля” – Парк імені Островського
Житомирська область
21.05.2017

Attachment:
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-7&t=DcyFpzLX1uEPkEEn-0

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 112.0.5615.138
![2023-05-02_21h50_42](https://user-images.githubusercontent.com/125903734/235759525-ef117ea3-13fc-4c6c-9349-84ff68adcb51.png)

**Comment by scholokov** [comment]
у даному прикладі краще написати:
Extra words:
Житомирська область, Украина
21.05.2017

**Comment by scholokov** [comment]
виправлено

**Comment by ViktoriaZamkova** [comment]
verified
