### ISSUE TITLE
20180204_zhitomyr / Extra element text "Украина 04.02.2018" is under the 1st Preview

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3544]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20180204_zhitomyr
2. Pay attention to the text under the 1st Preview block.

**Actual result:**
Extra element text "Украина 04.02.2018" is under the 1st Preview.

**Expected result:**
There is no text "Украина 04.02.2018" under the 1st Preview.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/235850479-6fa0d3a9-09ca-4b87-a2b1-fa72fb67d805.png)

**Comment by GNatala** [comment]
#3431

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
