### ISSUE TITLE
20180204_zhitomyr / Missed preview photo in the block "Дорога-Житомир-Киев 04.02.2018"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3545]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20180204_zhitomyr
2. Pay attention to the absence of the photo in the block "Дорога-Житомир-Киев 04.02.2018".

**Actual result:**
Preview photo is not displayed in the block "Дорога-Житомир-Киев 04.02.2018".

**Expected result:**
Preview photo is displayed in the block "Дорога-Житомир-Киев 04.02.2018".

**Additional information**
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/235853298-056f40dd-edb4-4163-a9c6-8e8cd4f30a1a.png)

**Comment by GNatala** [comment]
#3431

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
