### ISSUE TITLE
20180204_zhitomyr /  The travel publication date does not match the travel date

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3547]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20180204_zhitomyr/
2. Pay attention to the date of publication of the travel.

**Actual result:**
The travel publication date is 02.09.2021.

**Expected result:**
The travel publication date is 04.02.2018.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/235856027-9e8704d9-7530-490c-a984-43f19ed3a7a0.png)

**Comment by scholokov** [comment]
виправлено
