### ISSUE TITLE
20180204_zhitomyr / Name of the 1st video "Киев-Житомир" is russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3548]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20180204_zhitomyr
2. Pay attention to the name of the 1st video "Киев-Житомир".

**Actual result:**
Name of the 1st video "Киев-Житомир" is russian.

**Expected result:**
Name of the 1st video "Київ-Житомир" is Ukranian.

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://user-images.githubusercontent.com/101987790/235861153-1fe50f1a-6c85-4f7a-ac78-13536f180f4e.png)

**Comment by GNatala** [comment]
#3431

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
