### ISSUE TITLE
20160710_0807_italy_odessa/The travel date of the video Italy shops of the Italy block is missed

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3549]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the video Italy shops of the Italy block.

3. Pay attention to the name of the video. The travel date is missed.

**Actual result:**
The travel date of the video Italy shops of the Italy block is missed

**Expected result:**
The travel date of the video Italy shops of the Italy block must be

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://user-images.githubusercontent.com/125134112/235870529-ec90f7eb-b5d2-4779-af0d-6cc017c4ffe3.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/235880711-1c1eff6c-b60b-457c-ba35-e8b4d8573c4c.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
