### ISSUE TITLE
20160710_0807_italy_odessa/The date format of the video gallery Italy Rimini of Italy block is 18.07.2016 (DD.MM.YYYY)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3550]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the video gallary Italy Rimini.

3. Pay attention to the date format of the video gallery.

**Actual result:**
The date format of the video gallery Italy Rimini of Italy block is 18.07.2016 (DD.MM.YYYY)

**Expected result:**
The date format of the video gallery Italy Rimini of Italy block must be 2016.07.18 (YYYY.MM.DD.)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://user-images.githubusercontent.com/125134112/235882444-0b9096d1-a9f0-4135-b559-30eb94d2c74c.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/235883703-3780c3f0-30c7-4ed8-8620-8638c5efd877.png)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
