### ISSUE TITLE
20160710_0807_italy_odessa/The date format of the first video gallery Italy Rimini of Italy block is 18.07.2016 (DD.MM.YYYY)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3551]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the first video gallary Italy Rimini.

3. Pay attention to the date format of the first video gallery.

**Actual result:**
The date format of the first video gallery Italy Rimini of Italy block is 18.07.2016 (DD.MM.YYYY)

**Expected result:**
The date format of the first video gallery Italy Rimini of Italy block must be 2016.07.18 (YYYY.MM.DD.)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://user-images.githubusercontent.com/125134112/235884832-13004e36-5f32-4c68-a9a9-50732fc375a4.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/235885354-c04c5bc6-2312-4e53-9c8b-50dd2520c953.png)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
