### ISSUE TITLE
20160710_0807_italy_odessa/The date format of the second video gallery Italy Rimini of Italy block is 17.07.2016 (DD.MM.YYYY)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3553]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the second video gallary Italy Rimini.

3. Pay attention to the date format of the second video gallery.

**Actual result:**
The date format of the second video gallery Italy Rimini of Italy block is 17.07.2016 (DD.MM.YYYY)

**Expected result:**
The date format of the second video gallery Italy Rimini of Italy block must be 2016.07.17 (YYYY.MM.DD.)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://user-images.githubusercontent.com/125134112/235889562-0b1a21f4-b208-440a-92ca-89a91f11566d.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/235890008-8b88db11-ed30-4b08-aaed-81ef06a7794e.png)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
