### ISSUE TITLE
20160710_0807_italy_odessa/The date format of the third video gallery Italy Rimini of Italy block is 15.07.2016 (DD.MM.YYYY)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3555]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the video gallary Italy Rimini.

3. Pay attention to the date format of the video gallery.

**Actual result:**
The date format of the third video gallery Italy Rimini of Italy block is 15.07.2016 (DD.MM.YYYY)

**Expected result:**
The date format of the third video gallery Italy Rimini of Italy block must be 15.07.2016 (DD.MM.YYYY)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://user-images.githubusercontent.com/125134112/235890785-d5bd2c28-5a93-49a8-a3cc-d1422a9ec678.png)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/235891349-43d85618-0068-41ca-b11d-032ba5370cf0.png)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
