### ISSUE TITLE
20150919_Kiev_Aviation_Museum/In The Global Map the Legend is missing

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3556]
Steps to reproduce:

1. Open page https://test.long-travel.live/20150919_Kiev_Aviation_Museum/
2. Pay attention to the Global Map

Actual Result: In the Global map the Legend is missing 
Expected Result: In the Global map the Legend is present 

Requirements: https://github.com/scholokov/long-travel-2/wiki/3.2-Подорожі.-Глобальна-карта-з-маршрутами

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://user-images.githubusercontent.com/123776698/235894662-b03bcb83-824c-47ce-b901-129f95097db4.png)

**Comment by ODrobik** [comment]
#2995

**Comment by scholokov** [comment]
у вимогах йдеться саме про глобальну мапу. а на скрині - вже взята сама подорож

**Comment by ODrobik** [comment]
@scholokov виправлено

**Comment by ODrobik** [comment]
Не є помилкою
