### ISSUE TITLE
20150919_Kiev_Aviation_Museum/In the Youtube Gallery the Format of Name video is "2015.09.19 Київ - Виставка літаків 01"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3557]
Steps to reproduce:

1. Open https://test.long-travel.live/20150919_Kiev_Aviation_Museum/
2. Scroll down to the Youtube Gallery
3. Pay attention to the Name of the video 

Actual Result: Name video is "2015.09.19 Київ - Виставка літаків 01"
Expected Result: Name video is "2015.09.19 Виставка літаків 01"

Requirements: https://github.com/scholokov/long-travel-2/wiki/4.6-Подорож.-Youtube-Галереї

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/e8466d18-b91d-4b70-bf9f-106992bcdccc)

**Comment by ODrobik** [comment]
#2995

**Comment by scholokov** [comment]
виправлено вимоги

**Comment by ODrobik** [comment]
виправлено згідно редагованих вимог
![image](https://github.com/scholokov/long-travel-2/assets/123776698/7c98fe08-6513-4fb0-9ec6-48e7c5c2ae3b)

**Comment by ODrobik** [comment]
поправлено скрин згідно нових деталей  у вимогах

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
