### ISSUE TITLE
20150919_Kiev_Aviation_Museum/Youtube Gallery - Playlist - Name of the video is in Russian

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3558]
Steps to reproduce:

1. Open https://test.long-travel.live/20150919_Kiev_Aviation_Museum/
2. Scroll down to the Youtube Gallery
3. Pay attention to the Name of the video in the Playlist 

Actual Result: the Name of the video is in Russian
Expected Result: the Name of the video is in Ukrainian

Requirements: https://github.com/scholokov/long-travel-2/wiki/4.6-Подорож.-Youtube-Галереї

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://user-images.githubusercontent.com/123776698/236187928-74ae005e-68d9-4139-bfbc-64e41c93d8d0.png)

**Comment by ODrobik** [comment]
#2995

**Comment by scholokov** [comment]
виправлено
