### ISSUE TITLE
20160710_0807_italy_odessa/The fourth video gallery Italy Rimini of Italy block does not match travel.

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3559]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the video gallary Italy Rimini.

3. Pay attention to the fourth video gallery.

**Actual result:**
The fourth video gallery Italy Rimini of Italy block does not match travel. This video is stream of Mark Feigin.

**Expected result:**
This video gallery must have Italy travel video.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/236219578-18be3a9f-0ce8-4b4c-8fc6-8ce2b59514c5.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
