### ISSUE TITLE
20160710_0807_italy_odessa/The sixth video gallery Italy Rimini of Italy block does not match travel.

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3561]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the video gallary Italy Rimini.

3. Pay attention to the sixth video gallery.

**Actual result:**
The sixth video gallery Italy Rimini of Italy block does not match travel. This video is from YouTube channel Shelterman.

**Expected result:**
This video gallery must have Italy travel video.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Attachment:**

![Image](https://user-images.githubusercontent.com/125134112/236238950-8421a883-7869-4c45-8e5b-35a60e1924bb.png)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
