### ISSUE TITLE
20160710_0807_italy_odessa/The travel date in Italy beach block is "15.-18.07.2016" (DD.-DD.MM.YYYY)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3564]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to Italy beach block.

3. Pay attention to the travel date in the left side of the block.

**Actual result:**
The travel date in Italy beach block is "15.-18.07.2016" (DD.-DD.MM.YYYY)

**Expected result:**
The travel date in Italy beach block must be "15.07.2016-18.07.2016" (DD.MM.YYYY-DD.MM.YYYY)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.3-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%A1%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D1%96-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8#beach

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/daedf461-fcaa-441f-9e4e-3443c576f70f)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/e43019a5-814b-494a-b5de-23ce48f7e96f)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
@scholokov @tatianasheremet no fixed 

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/750ce44c-d92c-4c8b-9ffe-c8b7ab0103c8)

**Comment by prokopenkoga1977** [comment]
Passed
