### ISSUE TITLE
20160710_0807_italy_odessa/The travel name of Italy beach block is in Ukrainian

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3565]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to Italy beach block.

3. Pay attention to the travel name in the left side of the block.

**Actual result:**
The travel name of Italy beach block is in Ukrainian

**Expected result:**
The travel name of Italy beach block must be in Italian

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/1.2-%D0%9C%D0%BE%D0%B2%D0%B0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/8d800d7e-6100-4b34-9d3a-9febe4f3df2d)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/00423840-30db-4858-a957-48df4b4c77ae)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
@scholokov @tatianasheremet no fixed 

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/d6a49185-359b-4ad9-8c38-6ccfcab3d5a6)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
