### ISSUE TITLE
20160710_0807_italy_odessa/The travel date of the fifth video gallery of Italy, Rimini Beach is missing

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3568]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the third video gallary Italy Rimini Beach.

3. Pay attention to the name of the third video gallery.

**Actual result:**
The travel date of the fifth video gallery of Italy, Rimini Beach is missing

**Expected result:**
The travel date of the fifth video gallery of Italy, Rimini Beach must be

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:**https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/73c2b19e-2af0-4691-a911-17236034b87a)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/b5b292fd-477d-4719-a33b-786f976dfe9d)

**Comment by scholokov** [comment]
fixed
