### ISSUE TITLE
20160710_0807_italy_odessa/The travel date of the sixth video gallery of Italy, Rimini Beach is missing

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3569]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the sixth video gallary Italy Rimini Beach.

3. Pay attention to the name of the sixth video gallery.

**Actual result:**
The travel date of the sixth video gallery of Italy, Rimini Beach is missing

**Expected result:**
The travel date of the sixth video gallery of Italy, Rimini Beach must be

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:**https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/0e2c58c2-b35b-46d6-91a5-7cc26ff0b81a)

**Attachments:**
![Image](https://github.com/scholokov/long-travel-2/assets/125134112/00241f74-c184-4baf-ab8d-0e6c8ec4a5a0)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
