### ISSUE TITLE
20160710_0807_italy_odessa/The travel date of the seventh video gallery of Italy, Rimini Beach is missing

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3570]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the seventh video gallary Italy Rimini Beach.

3. Pay attention to the name of the seventh video gallery.

**Actual result:**
The travel date of the seventh video gallery of Italy, Rimini Beach is missing

**Expected result:**
The travel date of the seventh video gallery of Italy, Rimini Beach must be

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:**https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/14540479-605c-47ae-b359-b7fcd2d4912b)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/b02516ad-cb4d-459c-b78f-b50d73ba82b9)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
