### ISSUE TITLE
20160710_0807_italy_odessa/The travel date of the eigth video gallery of Italy, Rimini Beach is missing

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3571]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the eigth video gallary Italy Rimini Beach.

3. Pay attention to the name of the eigth video gallery.

**Actual result:**
The travel date of the eigth video gallery of Italy, Rimini Beach is missing

**Expected result:**
The travel date of the eigth video gallery of Italy, Rimini Beach must be

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:**https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/723fe04b-852c-48aa-9a5f-4be26ee52d28)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/d2511be7-c4fa-4694-bb1a-7fe375e8abe9)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
