### ISSUE TITLE
20190720_0811_balcans - Body - Logical block name "Hotel: Palma" is #222222 (Dark grey)

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3572]
**Steps of reproducing:**
Open https://test.long-travel.live/20190720_0811_balcans/
Sctoll to logical block "Hungary" (where present Booking link)
Pay attention to the color of the text "Hotel: Palma" above the text "Hungary"

**Actual Result**
Color of the text "Hotel: Palma" is #222222

**Expected Result**
Color of the text "Hotel: Palma" is #FFFFFF

**Additional information**
The text "Hotel: Palma" blends in with the color of the site. To see it, you need to select this text with the left mouse button or look closely
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1201-2459&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 113.0.5672.93 (64 bit)
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 10 05 2023 16_24_37](https://github.com/scholokov/long-travel-2/assets/95171672/b54746c4-7588-4cc4-b3f4-6656ffa58354)
![DevTools 10 05 2023 16_24_54](https://github.com/scholokov/long-travel-2/assets/95171672/5f0981de-4f8b-4784-afb9-bb91c8c173b4)

**Comment by scholokov** [comment]
fixed
