### ISSUE TITLE
20190720_0811_balcans - Body - Logical block name "Nyírbátor Hungary" is #222222 (Dark grey)

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3573]
**Steps of reproducing:**
Open https://test.long-travel.live/20190720_0811_balcans/
Sctoll to logical block "Hungary"
Pay attention to the color of the text "Nyírbátor Hungary" above the text "Hungary"

**Actual Result**
Color of the text "Nyírbátor Hungary" is #222222

**Expected Result**
Color of the text "Nyírbátor Hungary" is #FFFFFF

**Additional information**
The text "Nyírbátor Hungary" blends in with the color of the site. To see it, you need to select this text with the left mouse button or look closely
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1201-2459&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 113.0.5672.93 (64 bit)
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 10 05 2023 16_34_45](https://github.com/scholokov/long-travel-2/assets/95171672/f5556525-102a-4586-b5a3-35b532aa3f81)
![DevTools - test long-travel live_20190720_0811_balcans_ 10 05 2023 16_34_52](https://github.com/scholokov/long-travel-2/assets/95171672/e783067f-4aa3-42af-999c-089208cfc52f)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
