### ISSUE TITLE
20190720_0811_balcans - Body - Logical block name "Road: Hungary – Ukraine" is #222222 (Dark grey)

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3574]
**Steps of reproducing:**
Open https://test.long-travel.live/20190720_0811_balcans/
Sctoll to logical block "Hungary Ukraine"
Pay attention to the color of the text "Road: Hungary – Ukraine" above the text "Hungary Ukraine"

**Actual Result**
Color of the text "Road: Hungary – Ukraine" is #222222

**Expected Result**
Color of the text "Road: Hungary – Ukraine" is #FFFFFF

**Additional information**
The text "Road: Hungary – Ukraine" blends in with the color of the site. To see it, you need to select this text with the left mouse button or look closely
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1201-2459&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 113.0.5672.93 (64 bit)
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 10 05 2023 16_41_49](https://github.com/scholokov/long-travel-2/assets/95171672/76da5947-c10c-400d-bd45-03c93b331663)
![DevTools - test long-travel live_20190720_0811_balcans_ 10 05 2023 16_41_58](https://github.com/scholokov/long-travel-2/assets/95171672/eabc1d27-5897-4599-9882-1a42a0629e78)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducedc
