### ISSUE TITLE
20190720_0811_balcans - Body - Logical block name "Road: Богородчаны – Киев" is #222222 (Dark grey)

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3576]
**Steps of reproducing:**
Open https://test.long-travel.live/20190720_0811_balcans/
Sctoll to logical block "Ukraine" 
Pay attention to the color of the text "Road: Богородчаны – Киев" above the text "Ukraine"

**Actual Result**
Color of the text "Road: Богородчаны – Киев" is #222222

**Expected Result**
Color of the text "Road: Богородчаны – Киев" is #FFFFFF

**Additional information**
The text "Road: Богородчаны – Киев" blends in with the color of the site. To see it, you need to select this text with the left mouse button or look closely
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1201-2459&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 113.0.5672.93 (64 bit)
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 10 05 2023 16_57_36](https://github.com/scholokov/long-travel-2/assets/95171672/49fcb8a3-8ca6-4fcd-a665-b7ea72461186)
![DevTools - test long-travel live_20190720_0811_balcans_ 10 05 2023 16_57_42](https://github.com/scholokov/long-travel-2/assets/95171672/fb5cd32c-1b2c-4c52-b51b-1c82ca460ced)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
