### ISSUE TITLE
/20210305_07_odessa/ Travel name doesn`t meet with requirements

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3577]
Steps to reproduce:
1.Open https://test.long-travel.live/20210305_07_odessa/
2.Chek the Preview

Actual result:
Одеса

Expected result:
Одеса 2021

Attachment:
https://github.com/scholokov/long-travel-2/wiki/3.1-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%9F%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 113.0.5672.92

![2023-05-10_16h40_23](https://github.com/scholokov/long-travel-2/assets/125903734/97ff2d90-dd7e-4084-8a3d-556cba5f8f82)

**Comment by scholokov** [comment]
fixed

**Comment by ViktoriaZamkova** [comment]
verified
