### ISSUE TITLE
20150919_Kiev_Aviation_Museum/The URL of the trip ID is "20150919_Kiev_Aviation_Museum"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3579]
Steps to Reproduce:

1. Open page: https://test.long-travel.live/20150919_Kiev_Aviation_Museum/
2. Pay attention to the URL of the trip

Actual Result: the trip ID is "20150919_Kiev_Aviation_Museum"
Expected Result: the trip ID is "20150919_kiev_aviation_museum"

Requirements: 
https://github.com/scholokov/long-travel-2/wiki/4.7-Подорож.-URL
https://github.com/scholokov/long-travel-2/wiki/3.1-Подорожі.-Перелік

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachments:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/fdefad1d-8733-4cc5-b6ba-2e1e09d5d1aa)

**Comment by ODrobik** [comment]
#2995

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified by link **https://test.long-travel.live/20150919_kiev_aviation_museum/**
