### ISSUE TITLE
20150919_Kiev_Aviation_Museum/In the Global map the Travel list the name of the travel is "Проців"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3580]
Steps to reproduce:

1. Open page https://test.long-travel.live/travels/
2. Scroll down to the travel "Проців" on the Travel list 
3. Pay attention to the NAME of travel

Actual Result: the name of the travel is "Проців"
Expected Result: the name of the travel is "2017.07.09 Проців"

Requirements: https://github.com/scholokov/long-travel-2/wiki/3.2-Подорожі.-Глобальна-карта-з-маршрутами

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/0a16802d-b2d5-42f9-9f5d-8ee72bf82cc8)

**Comment by ODrobik** [comment]
#3235

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
Verified
