### ISSUE TITLE
20160710_0807_italy_odessa/The travel date of the video of San Marino is missing

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3582]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the video San Marino.

3. Pay attention to the name of the video.

**Actual result:**
The travel date of the video of San Marino is missing

**Expected result:**
The travel date of the video of San Marino must be

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:**https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/7f9dedbd-0069-409e-972f-ad40030ed7a4)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/07f254b0-39a0-4445-b161-da66f38c5b54)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
