### ISSUE TITLE
20160710_0807_italy_odessa/The date format of the second video San Marino of San Marino block is 17.07.2016 (DD.MM.YYYY)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3583]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the second video San Marino.

3. Pay attention to the date format of the second video.

**Actual result:**
The date format of the second video San Marino of San Marino block is 17.07.2016 (DD.MM.YYYY)

**Expected result:**
The date format of the second video San Marino of San Marino block must be 2016.07.17 (YYYY.MM.DD.)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements**: https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/07c9fd15-2e6c-4cc5-b2bf-5190cf95b51c)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/77031b78-a224-478d-8a62-b4422b39ee8b)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
