### ISSUE TITLE
20160710_0807_italy_odessa/The videos of San Marino block are posted as separate videos, not a video gllery

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3584]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the videos of San Marino block.

3. Pay attention to the videos. 

**Actual result:**
The videos of San Marino block are posted as separate videos, not a video gllery.

**Expected result:**
The videos of San Marino block must be posted as video gallary.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/704de63a-40b1-4e48-95b9-16684b30702e)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/0e9801c3-a932-41ca-9ff8-4981a4ca1fc2)

**Comment by scholokov** [comment]
це різні відео за типом. Одне з реєстратора, інше звичайне. Щоб уникнути конфліктності у блоку - додав короткий опис кожному

**Comment by prokopenkoga1977** [comment]
Passed
