### ISSUE TITLE
20190720_0811_balcans - Header - Preview - Croatia's flag is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3585]
**Steps of reproducing:**
1.  Open https://test.long-travel.live/20190720_0811_balcans/
2. Pay attention to the presence of the Croatian flag in the preview

**Actual Result**
Croatia's flag is missing

**Expected Result**
Croatia's flag is present

**Additional information**
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 113.0.5672.93 (64 bit)
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 16 05 2023 19_27_10](https://github.com/scholokov/long-travel-2/assets/95171672/b57dd3c4-532e-47cb-9fa8-54bef8d98a4f)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduced
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 29 05 2023 13_51_44](https://github.com/scholokov/long-travel-2/assets/95171672/1b4b44d6-3db2-4b1f-8bec-e3c16026b3fd)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
