### ISSUE TITLE
20180204_zhitomyr / Name of the 1st Road block "Дорога – Киев – Житомир" doesn`t meet with requirements

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3586]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20180204_zhitomyr
2. Pay attention to the 1st video Road block "Дорога – Киев – Житомир".

**Actual result:**
Дорога – Киев – Житомир
04.02.2018

**Expected result:**
Дорога: Київ – Житомир
04.02.2018

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.3-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%A1%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D1%96-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/dda0a7fd-53a9-4755-bd3f-cbdf284ba24a)

**Comment by GNatala** [comment]
https://github.com/scholokov/long-travel-2/issues/3431

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
