### ISSUE TITLE
20180204_zhitomyr / Ukranian flag is missed in the block "Варенична. Балувана Галя"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3590]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20180204_zhitomyr
2. Scroll down to the block "Варенична. Балувана Галя"
3. Pay attention to the absence of the Ukranian flag in the block's right side.

**Actual result:**
Ukranian flag is missed in the block "Варенична. Балувана Галя".

**Expected result:**
Ukranian flag is displayed in the block "Варенична. Балувана Галя".

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%A1%D1%82%D1%80%D1%83%D0%BA%D1%82%D1%83%D1%80%D0%B0

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/dbb04ff7-16ab-45da-9fe3-13e219006604)

**Comment by GNatala** [comment]
#3431

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
