### ISSUE TITLE
20180204_zhitomyr / Names of the cities in the legend of the map are in English

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3592]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20180204_zhitomyr
2. Pay attention to the names of the cities in the legend of the map.

**Actual result:**
Names of the cities "Kyiv" and "Zhytomyr" in the legend of the map are in English.

**Expected result:**
Names of the cities "Київ" and "Житомир" in the legend of the map are in Ukranian.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.4-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%9C%D0%B0%D0%BF%D0%B0

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/35296b67-02d2-4195-be38-6e739767d450)

**Comment by GNatala** [comment]
#3431

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
