### ISSUE TITLE
20190720_0811_balcans - Body - Preview of "Road: Киев Украина – Medias Romania"  - Flags of Ukraine and Romania is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3593]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Road: Киев Украина – Medias Romania" block
3. Pay attention to the presence of the Ukraine and Romania flags in the preview

**Actual Result**
Ukraine and Romania flags is missing

**Expected Result**
Ukraine and Romania flags is present

**Additional information**
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 113.0.5672.93 (64 bit)
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 17 05 2023 16_10_34](https://github.com/scholokov/long-travel-2/assets/95171672/2422b532-e829-41bd-8d7f-e0daa21ce614)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
