### ISSUE TITLE
20190720_0811_balcans - Body - Preview of "Belgrade" block - Serbia's flag is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3601]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Belgrade" block
3. Pay attention to the presence of the Serbia's flag in the preview

**Actual Result**
Serbia's flag is missing

**Expected Result**
Serbia's flag is present

**Additional information**
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 113.0.5672.127 (64 bit)
![Charlotte AMV - Back to Life - YouTube - Google Chrome 17 05 2023 17_32_03](https://github.com/scholokov/long-travel-2/assets/95171672/4ad90056-c151-4fda-855c-abd2b5d9c476)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
