### ISSUE TITLE
20160710_0807_italy_odessa/The date format of the video Italy Miniatures Shops of Italy Miniatures block is 16.07.2016 (DD.MM.YYYY)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3602]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the video Italy Miniatures Shops.

3. Pay attention to the date format of the video.

**Actual result:**
The date format of the video Italy Miniatures Shops of Italy Miniatures block is 16.07.2016 (DD.MM.YYYY)

**Expected result:**
The date format of the video Italy Miniatures Shops of Italy Miniatures block must be 2016.07.16 (YYYY.MM.DD)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/97a1db45-bd61-4d4b-bf77-fd3165e0fb9d)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/29d7d641-ef50-4b93-9e4f-9cc056ac4aa2)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
