### ISSUE TITLE
20160710_0807_italy_odessa/The date format of the first video gallery Italy - Austria - Germany is 20.07.2016 (DD.MM.YYYY)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3605]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the first video gallery Italy - Austria - Germany.

3. Pay attention to the date format of the first video gallery.

**Actual result:**
The date format of the first video gallery Italy - Austria - Germany is 20.07.2016 (DD.MM.YYYY)

**Expected result:**
The date format of the first video gallery Italy - Austria - Germany must be 2016.07.20 (YYYY.MM.DD)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/b1a0b43f-fc56-48ce-9bb7-eb67b90d8205)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/dcfc06f9-a90e-464d-95e1-d9b02174230e)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
