### ISSUE TITLE
20160710_0807_italy_odessa/The name format of the first video gallery Italy - Germany is Italy - Austria - Germany

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3610]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the first video gallery Italy - Germany.

3. Pay attention to the name format of the first video gallery.

**Actual result:**
The name format of the first video gallery Italy - Germany is Italy - Austria - Germany.

**Expected result:**
The name format of the first video gallery must be Italy - Germany (starting point of departure - final point of departure).

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/51035a70-af60-4d53-9407-3effc512b7d2)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/2bebe802-6473-4247-a0b8-78ae1fda3810)

**Comment by scholokov** [comment]
оновлено вимоги 1.3.0

**Comment by prokopenkoga1977** [comment]
Passed
