### ISSUE TITLE
20160710_0807_italy_odessa/The name format of the second video gallery Italy - Germany is Italy - Austria - Germany

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3611]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the second video gallery Italy - Germany.

3. Pay attention to the name format of the second video gallery.

**Actual result:**
The name format of the second video gallery Italy - Germany is Italy - Austria - Germany.

**Expected result:**
The name format of the second video gallery must be Italy - Germany (starting point of departure - final point of departure).

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

 **Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/0807581a-e0b3-4b04-991c-340eb6751784)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/38674a46-fc1c-4a0f-83b4-edb812c82258)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
@scholokov @tatianasheremet  no fixed

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/95e75b04-87d3-4075-b2ae-83f3a2ad1a1f)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
