### ISSUE TITLE
20160710_0807_italy_odessa/The name format of the fourth video gallery Italy - Germany is alps 2 07 Road 20.07

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3613]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the fourth video gallery Italy - Germany.

3. Pay attention to the name format of the fourth video gallery.

**Actual result:**
The name format of the fourth video gallery Italy - Germany is alps 2 07 Road 20.07

**Expected result:**
The name format of the fourth video gallery must be Italy - Germany (starting point of departure - final point of departure), because it's a road.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements: https:**//github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/92b43dda-a5e2-4eac-b8d6-c957e965dcb9)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/72eb0123-0a21-4f9c-8580-4954f4388a65)

**Comment by scholokov** [comment]
відео підлягає під пункт 1.3.1

**Comment by prokopenkoga1977** [comment]
Passed
