### ISSUE TITLE
20160710_0807_italy_odessa/The name format of the fifth video gallery Italy - Germany is alps 07 Road 20.07

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3614]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the fifth video gallery Italy - Germany.

3. Pay attention to the name format of the fifth video gallery.

**Actual result:**
The name format of the fifth video gallery Italy - Germany is alps 2 07 Road 20.07

**Expected result:**
The name format of the fifth video gallery must be Italy - Germany (starting point of departure - final point of departure), because it's a road.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/ea72a385-2096-4148-89b1-da3af9015e73)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/48e921e6-cfe9-4aaa-8c53-d0816d823179)

**Comment by prokopenkoga1977** [comment]
@scholokov @tatianasheremet no fixed

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/1770061a-3c90-4157-9a0e-1d8aa8078c90)

**Comment by scholokov** [comment]
відео підлягає під пункт 1.3.1

**Comment by prokopenkoga1977** [comment]
Passed
