### ISSUE TITLE
20160710_0807_italy_odessa/The date format of the fourth video gallery Italy - Germany is 20.07 (DD.MM.)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3615]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the fourth video gallery Italy - Germany.

3. Pay attention to the date format of the fourth video gallery.

**Actual result:**
The date format of the fourth video gallery Italy - Germany is 20.07 (DD.MM.)

**Expected result:**
The date format of the fourth video gallery Italy - Germany must be 2016.07.20 (YYYY.MM.DD.)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/16a8b0fd-d88e-45f1-94a1-2419c3f7ee0a)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/fc1e0c73-6084-4f6c-b851-143e7e167812)

**Comment by scholokov** [comment]
fixed
