### ISSUE TITLE
wiki/The Page"4.4 Подорож. Мапа" the block "Легенда" does not display the necessary information about the location "Link"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3617]
Steps to reproduce:

1. Open: https://github.com/scholokov/long-travel-2/wiki
2. Click on the page "4.4 Подорож. Мапа"
3. Pay attention to the block "Легенда" on the Map

Actual Result: the page "4.4 Подорож. Мапа" **does not display** the necessary information about the location "Link"
Expected Result: the page "4.4 Подорож. Мапа" **displays** the necessary information about the location "Link"

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:

![image](https://github.com/scholokov/long-travel-2/assets/123776698/3e2045ea-658b-4f5f-93e4-566d353b1937)

![image](https://github.com/scholokov/long-travel-2/assets/123776698/c123df95-cdee-4bbb-890b-d33e2b65e665)

**Comment by scholokov** [comment]
додано
https://github.com/scholokov/long-travel-2/wiki/4.4-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%9C%D0%B0%D0%BF%D0%B0

**Comment by ODrobik** [comment]
перевірено за посиланням https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6#12-%D0%BC%D0%B0%D0%BF%D0%B0 та шляхом "4. Подорож-->Мапа -->пункт 1.2.2.7
