### ISSUE TITLE
20150919_Kiev_Aviation_Museum/In the Preview block the Name of travel the Font-family is "Open Sans" and the Font-size is 18px

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3618]
Steps to reproduce:

1. Open page https://test.long-travel.live/20150919_Kiev_Aviation_Museum/
2. Pay attention to the Name In the Preview block
3. Open DevTools
4. Сheck the font-family and the Font-size for the Name In the Preview block

Actual Result: Font-family is "Open Sans" and the Font-size is 18px
Expected Result: Font-family is 'Amazing Slab Trial' and the Font-size is 24px

Requirements: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-7&t=k25SEYQtSXkR02I5-0

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/7fe2585e-4895-424b-9978-ac316007a8a7)

**Comment by ODrobik** [comment]
#2995

**Comment by scholokov** [comment]
please retest

**Comment by ODrobik** [comment]
verified
