### ISSUE TITLE
20190720_0811_balcans - Body - Preview of "Road: Belgrade Serbia – Skopje Makedonia" block - Serbia and Makedonia flags is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3621]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Road: Belgrade Serbia – Skopje Makedonia" block
3. Pay attention to the presence of the Serbia and Makedonia flags in the preview

**Actual Result**
Serbia and Makedonia flags is missing

**Expected Result**
Serbia and Makedonia flags is present

**Additional information**
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 113.0.5672.127 (64 bit)
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 19 05 2023 15_56_16](https://github.com/scholokov/long-travel-2/assets/95171672/cc7c05f0-9783-4664-9705-37dc585ad99f)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
