### ISSUE TITLE
20190720_0811_balcans - Body - Preview of "Road: Albania – Montenegro" block - Albania and Montenegro flags is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3627]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Road: Albania – Montenegro" block
3. Pay attention to the presence of the Albania and Montenegro flags in the preview

**Actual Result**
Albania and Montenegro flags is missing

**Expected Result**
Albania and Montenegro flags is present

**Additional information**
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 113.0.5672.127 (64 bit)
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 19 05 2023 16_45_33](https://github.com/scholokov/long-travel-2/assets/95171672/24f99aba-0799-4185-936b-12183334f504)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
