### ISSUE TITLE
20190720_0811_balcans - Body - Preview of "Albania Tirana" block - Albania's flag is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3629]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Albania Tirana" block
3. Pay attention to the presence of the Albania's flag in the preview

**Actual Result**
Albania's flag is missing

**Expected Result**
Albania's flag is present

**Additional information**
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 113.0.5672.127 (64 bit)
![New Issue · scholokov_long-travel-2 - Google Chrome 19 05 2023 17_02_21](https://github.com/scholokov/long-travel-2/assets/95171672/a55339c4-a81f-42e1-8141-d4b7fb2bd304)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
