### ISSUE TITLE
20190720_0811_balcans - Body - Preview of "Hotel: Apartments Palma" block - Montenegro's flag is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3630]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Hotel: Apartments Palma" block
3. Pay attention to the presence of the Montenegro's flag in the preview

**Actual Result**
Montenegro's flag is missing

**Expected Result**
Montenegro's flag is present

**Additional information**
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 113.0.5672.127 (64 bit)
![New Issue · scholokov_long-travel-2 - Google Chrome 19 05 2023 17_17_52](https://github.com/scholokov/long-travel-2/assets/95171672/5a8ff196-4f39-407c-b3e1-0f42f50b9b5b)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
