### ISSUE TITLE
20190720_0811_balcans - Body - Preview of "Road: Montenegro – Bosnia and Herzegovina" block - Montenegro and "Bosnia and Herzegovina" flags is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3633]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Road: Montenegro – Bosnia and Herzegovina" block
3. Pay attention to the presence of the Montenegro and "Bosnia and Herzegovina" flags in the preview

**Actual Result**
Montenegro and "Bosnia and Herzegovina" flags is missing

**Expected Result**
Montenegro and "Bosnia and Herzegovina" flags is present

**Additional information**
"Bosnia and Herzegovina" it's name of one country
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 113.0.5672.127 (64 bit)
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 19 05 2023 17_26_56](https://github.com/scholokov/long-travel-2/assets/95171672/bbb3660e-d18b-445f-bb06-5120f4ea1d92)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
