### ISSUE TITLE
wiki/The page "4.4 Подорож. Мапа" the word "превью" is in russian language

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3637]
Steps to reproduce:

1. Open: https://github.com/scholokov/long-travel-2/wiki/4.4-Подорож.-Мапа
2. Pay attention to the page "4.4 Подорож. Мапа"

Actual Result: the word **"превью"** is in russian language
Expected Result: the word **"прев'ю"** is in ukrainian language

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/cd44c711-523e-4525-86b9-4beaf6869ee0)

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
