### ISSUE TITLE
20141102_10_egypt_hurghada/ photos in not show in the LightBox

### ISSUE THREAD

**Issue by Aleksandrkobets99** [scholokov/long-travel-2#3645]
Steps to reproduce:

1. Open link: https://test.long-travel.live/20141102_10_egypt_hurghada/
2. Find any kind photo in the section Egypt trip
3. Press on the photo
4. Click on the left
5. Click on the right

Actual result: Next and previous photos don't show. The date don't change 
Expected result: All photos should show and date should change 

Requirements: https://github.com/scholokov/long-travel-2/wiki/4.5-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%A4%D0%BE%D1%82%D0%BE%D0%B3%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

Environment:
Windows 10 Home
Google Chrome v 113.0.5672.127

Attachment:
Screenshot 1
1. Open any photo
2. Look at the number
3. Click on the right
![screen1](https://github.com/scholokov/long-travel-2/assets/126480322/9d962a8c-6620-4709-82a3-a4fedc525afe)

Screenshot 2
1. Look at the number
2. Click on the left
![screen2](https://github.com/scholokov/long-travel-2/assets/126480322/e115bc7d-1b1f-4a65-aaf8-a251ccd02192)

**Comment by DmytroMarkulych** [comment]
@Aleksandrkobets99 
1. При написанні Summary відповідаємо на питання "Де?, Що?, Коли?". Та назву блоку якого стосується дефект
2. Не забуваємо назву блоку "Кроки для відтворення"
3. Додаємо скріншот
4. Прописуємо всі необхідні атрибути
5. Додаємо посилання на специфікацію


![Image](https://github.com/scholokov/long-travel-2/assets/88647733/d2ea1d39-a64a-46f4-beb6-afefe529a39c)

**Comment by DmytroMarkulych** [comment]
@Aleksandrkobets99 
1. Скріншот краще робити всієї сторінки що було видно URL 
2. Priority виставляє проджект менеджер, ми як QA цей атрибут не заповняємо

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
