### ISSUE TITLE
wiki/The page "4.4 Подорож. Мапа" the word "Link" is English language

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3650]
**Steps to reproduce:**

1. Open: https://github.com/scholokov/long-travel-2/wiki/4.4-Подорож.-Мапа
2. Pay attention to the page "4.4 Подорож. Мапа"

**Actual Result:** the word "Link" is English language
**Expected Result:** the phrase "Відкрити подорож" is Ukrainian language

**Environment:**
Windows 10 Pro (x64),
Opera v 96.0.4693.80

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/123776698/7633e4a1-4fe5-428f-8648-605158d3489a)

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
