### ISSUE TITLE
20150919_Kiev_Aviation_Museum/The Text at the bottom of the page the Font-family is "Open Sans"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3651]
Steps to reproduce:

1. Open page https://test.long-travel.live/20150919_Kiev_Aviation_Museum/
2. Pay attention to the Text at the bottom of the page
3. Open DevTools
4. Сheck the font-family and the Font-size for the Text at the bottom of the page

Actual Result: Font-family is "Open Sans" 
Expected Result: Font-family is 'Rubik' 

Requirements: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-7&t=k25SEYQtSXkR02I5-0

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/3819ff3e-ec38-43b9-b6bf-2d3b52dace3e)

**Comment by ODrobik** [comment]
#2995

**Comment by scholokov** [comment]
please retest

**Comment by ODrobik** [comment]
verified
