### ISSUE TITLE
20160710_0807_italy_odessa/The travel date in Hotel – Ringhotel Die Gams, Beilngries block is "20.-22.07.2016" (DD.-DD.MM.YYYY)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3652]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to Hotel – Ringhotel Die Gams, Beilngries block.

3. Pay attention to the travel date in the left side of the block.

**Actual result:**
The travel date in Hotel – Ringhotel Die Gams, Beilngries block is "20.-22.07.2016" (DD.-DD.MM.YYYY)

**Expected result:**
The travel date in Hotel – Ringhotel Die Gams, Beilngries block must be "20.07.2016-22.07.2016" (DD.MM.YYYY-DD.MM.YYYY)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.3-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%A1%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D1%96-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8#hotel

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/014a4620-2846-4b06-8981-d32899080d20)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/9d3e3d13-477b-4b76-8243-c8dd328e7f3c)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
@scholokov @tatianasheremet no fixed 

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/cd09b216-7bc3-4a33-be21-dc4907f06052)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
