### ISSUE TITLE
20160710_0807_italy_odessa/The link to Hotel – Ringhotel Die Gams, Beilngries  is missed in Hotel – Ringhotel Die Gams, Beilngries block

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3653]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to Hotel – Ringhotel Die Gams, Beilngries block.

3. Pay attention to the absence of a link to the hotel in the left side of the block.

**Actual result:**
The link to Hotel – Ringhotel Die Gams, Beilngries is missed.

**Expected result:**
he link to Hotel – Ringhotel Die Gams, Beilngries must be in Hotel – Ringhotel Die Gams, Beilngries block.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.3-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%A1%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D1%96-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8#hotel

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/d64e189c-467e-464a-8e68-b8ff38f036ec)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/a33481af-4d8b-4727-8932-9c930581d084)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
