### ISSUE TITLE
20180204_zhitomyr / Word "Киев" in the name of the 2nd Road block "Дорога Житомир – Киев" is in russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3654]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20180204_zhitomyr
2. Pay attention to the 2nd Road block "Дорога Житомир – Киев".

**Actual result:**
Word "Киев" in the name of the 2nd Road block "Дорога  Житомир – **Киев" is in russian**

**Expected result:**
Word "Київ" in the name of the 2nd Road block "Дорога  Житомир – ****Київ"** is in Ukrainian**

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/1.2-%D0%9C%D0%BE%D0%B2%D0%B0

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/75e13515-ff4d-4e1a-a85c-1d2f287dbd24)

**Comment by GNatala** [comment]
#3431

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
