### ISSUE TITLE
20160710_0807_italy_odessa/The date format of the video gallery Germany - Poland of Road Beilngries – Krakow block is 22.07.2016 (DD.MM.YYYY)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3658]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the video gallery Germany - Poland of Road Beilngries – Krakow block.
3. Pay attention to the date format of the video gallery.

**Actual result:**
The date format of the video gallery Germany - Poland of Road Beilngries – Krakow block is 22.07.2016 (DD.MM.YYYY)

**Expected result:**
The date format of the video gallery Germany - Poland of Road Beilngries – Krakow block must be 2016.07.22 (YYYY.MM.DD)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/f72a6acb-7ea6-4cdc-813f-69f42ad362cf)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/740e0951-6639-4e4d-874e-a038f9924433)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
