### ISSUE TITLE
20160710_0807_italy_odessa/The name format of the third video gallery Germany - Poland of Road Beilngries – Krakow is Poland Road 07 Road 20.07

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3662]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the third video gallery Germany - Poland of Road Beilngries – Krakow. 

3. Pay attention to the name format of the third video gallery Germany - Poland of Road Beilngries – Krakow. 

**Actual result:**
The name format of the third video gallery Germany - Poland of Road Beilngries – Krakow is Poland Road 07 Road 20.07

**Expected result:**
The name format of the third video gallery must be Germany - Poland (starting point of departure - final point of departure), because it's a road (for example Germany - Poland  3 Poland)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/b041d848-977c-4f9d-a62d-6c54287dc255)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/a4baf428-45e6-479d-b4ac-34c9d581c687)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
