### ISSUE TITLE
20150919_kiev_aviation_museum/PhotoGallery, LightBox photo is not displayed when you click the button "Play" 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3663]
Steps to reproduce:

1. Open https://test.long-travel.live/20150919_kiev_aviation_museum/
2. Scroll down to PhotoGallery
3. Click on 1st photo to open LightBox
4. Click on the button "Play" 
5. Pay attention to the photo

Actual Result: the photo is not displayed in the LightBox
Expected Result: the photo is displayed in the LightBox

Environment:
Windows 10 Pro (x64),
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/ad7a55bb-06fc-478b-9ed8-4f5c0c35b6a8)

**Comment by ODrobik** [comment]
#2995

**Comment by ODrobik** [comment]
1 bug reports about Wiki - created.
Map block, Standart block and Footer of the travel have been tested.
Time wasted:1 hour 15 min

**Comment by scholokov** [comment]
please retest

**Comment by ODrobik** [comment]
is not relevant
