### ISSUE TITLE
wiki/The page "4. Подорож. Структура" the item numbers are the same

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3664]
Steps to reproduce:

1. Open:https://github.com/scholokov/long-travel-2/wiki/4.-Подорож.-Структура
2. Pay attention to the page "4. Подорож. Структура"

Actual Result: the item numbers are the same
Expected Result: the item numbers are different

Environment:
Windows 10 Pro (x64),
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/c2c3ddc5-9202-4704-b18c-4aaac50ef1e4)

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
