### ISSUE TITLE
20150919_kiev_aviation_museum/In the Preview block of travel across Ukraine the information about the City, Region is missing

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3665]
Steps to reproduce:

1. Open https://test.long-travel.live/20150919_kiev_aviation_museum/
2. Scroll down to the Preview block of travel
3. Pay attention to the structure of the Preview block

Actual Result: the information about the City, Region is missing
Expected Result: the information about the City, Region is present

Requirements: https://github.com/scholokov/long-travel-2/wiki/4.-Подорож.-Структура

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/d7329a50-ffa6-4fe8-a19b-4764ba792572)

**Comment by ODrobik** [comment]
#2995

**Comment by scholokov** [comment]
please add images

**Comment by ODrobik** [comment]
the line for displaying information about the City, Region is missing in FIGMA and on the SITE
![image](https://github.com/scholokov/long-travel-2/assets/123776698/b3051dae-f9da-4b31-9d03-58d42b47f0c8)

**Comment by scholokov** [comment]
але ти ссилаєся на вимоги до типових блоків, а на скріні у тебя превью подорожі....

**Comment by ODrobik** [comment]
не є актуальним
