### ISSUE TITLE
20190720_0811_balcans - Body - Preview of "Road: Bosnia and Herzegovina – Croatia" block - Flags of Bosnia and Herzegovina, Croatia is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3667]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Road: Bosnia and Herzegovina – Croatia" block
3. Pay attention to the presence of the flag of Bosnia and Herzegovina in the preview

**Actual Result**
Flags of Bosnia and Herzegovina, Croatia is missing

**Expected Result**
Flags of Bosnia and Herzegovina, Croatia is present

**Additional information**
"Bosnia and Herzegovina" it's name of one country
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 113.0.5672.127 (64 bit)
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 29 05 2023 12_40_36](https://github.com/scholokov/long-travel-2/assets/95171672/25b1fd00-f04f-4732-bff0-43067094f019)

**Comment by scholokov** [comment]
виправлено

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
