### ISSUE TITLE
20190720_0811_balcans - Body - Preview of "Osijec Croatia" block - Flag of Croatia is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3669]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Osijec Croatia" block
3. Pay attention to the presence of the flag of Croatia in the preview

**Actual Result**
Flag of Croatia is missing

**Expected Result**
Flag of Croatia is present

**Additional information**
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 113.0.5672.127 (64 bit)
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 29 05 2023 13_10_02](https://github.com/scholokov/long-travel-2/assets/95171672/98efbeaf-bf50-41eb-aa47-4486c481e229)

**Comment by scholokov** [comment]
виправлено

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
