### ISSUE TITLE
20190720_0811_balcans - Body - Preview of "Готель Palma" block - Flag of Hungary is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3671]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Готель Palma" block
3. Pay attention to the presence of the flag of Hungary in the preview

**Actual Result**
Flag of Hungary is missing

**Expected Result**
Flag of Hungary is present

**Additional information**
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 113.0.5672.127 (64 bit)
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 29 05 2023 13_26_29](https://github.com/scholokov/long-travel-2/assets/95171672/f149e13b-895a-4b14-9a03-2c234e3cffe6)

**Comment by scholokov** [comment]
виправлено

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
