### ISSUE TITLE
20190720_0811_balcans - Body - Preview of "Nyírbátor Hungary" block - Flag of Hungary is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3672]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Nyírbátor Hungary" block
3. Pay attention to the presence of the flag of Hungary in the preview

**Actual Result**
Flag of Hungary is missing

**Expected Result**
Flag of Hungary is present

**Additional information**
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 113.0.5672.127 (64 bit)
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 29 05 2023 13_31_01](https://github.com/scholokov/long-travel-2/assets/95171672/7ea65c2a-a7fe-4004-9c63-b65258c3b430)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
