### ISSUE TITLE
20190720_0811_balcans - Body - Preview of "Road: Hungary – Ukraine" block - Flags of Hungary and Ukraine is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3673]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Road: Hungary – Ukraine" block
3. Pay attention to the presence of the flags of Hungary and Ukraine in the preview

**Actual Result**
Flags of Hungary and Ukraine is missing

**Expected Result**
Flags of Hungary and Ukraine is present

**Additional information**
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 113.0.5672.127 (64 bit)
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 29 05 2023 13_34_41](https://github.com/scholokov/long-travel-2/assets/95171672/eed56227-7678-4a3c-b3e4-83813f8c07ac)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
