### ISSUE TITLE
20190720_0811_balcans - Body - Preview of "Road: Богородчаны – Киев" block - Flag of Ukraine is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3675]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Road: Богородчаны – Киев" block
3. Pay attention to the presence of the flag of Ukraine in the preview

**Actual Result**
Flag of Ukraine is missing

**Expected Result**
Flag of Ukraine is present

**Additional information**
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 113.0.5672.127 (64 bit)
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 29 05 2023 13_45_21](https://github.com/scholokov/long-travel-2/assets/95171672/7d3870d8-8fa2-4e7d-9b07-5e102f8dd9f1)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
