### ISSUE TITLE
20160710_0807_italy_odessa/The date format of the first video gallery Road Poland - Ukraine is 23.07.2016 (DD.MM.YYYY)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3680]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the first video gallery Road Poland - Ukraine.

3. Pay attention to the date format of the first video gallery.

**Actual result:**
The date format of the first video gallery Road Poland - Ukraine is 23.07.2016 (DD.MM.YYYY)

**Expected result:**
The date format of the first video gallery Road Poland - Ukraine must be 2016.07.23 (YYYY.MM.DD)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.6-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-Youtube-%D0%93%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/38865c39-aa5e-4463-b4a2-36b0d6ff082b)

Attachments:

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/e30a2322-ff20-4416-b2ca-72f9ba9bdfe1)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
