### ISSUE TITLE
20160710_0807_italy_odessa/The size of the flag of Ukraine in the Road Krakow-Lviv is 16x11

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3682]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the Road Krokow - Lviv block.
3. Pay attention to the size of the flag of Ukraine in the right side of the block.

**Actual result:**
The size of the flag of Ukraine in the Road Krakow-Lviv is 16x11

**Expected result:**
The size of the flag of Ukraine is 36x24 px

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Graphical requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1800-77&mode=design&t=o6dZMValz0qH0YSW-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/75ca96c3-34b0-4079-9248-dc73fe51a6d8)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/3fc1ec76-7107-4caa-9788-8ef1961cf750)

**Comment by scholokov** [comment]
please retest

**Comment by prokopenkoga1977** [comment]
@scholokov 
changed the bug report in accordance with the new requirements

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
