### ISSUE TITLE
20160710_0807_italy_odessa/The flag of Poland is missing in the Road Krakow-Lviv block

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3683]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the Road Krokow - Lviv block.
3. Pay attention to the absence of the flag of Poland in the right side of the block.

**Actual result:**
The flag of Poland is missing in the Road Krakow-Lviv block.
**Expected result:**
The flag of Poland is present in the Road Krakow-Lviv block.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Graphical requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1800-77&mode=design&t=o6dZMValz0qH0YSW-0
https://github.com/scholokov/long-travel-2/blob/main/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv.md

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/0ad278ea-c609-4bd7-9550-8de9b03a2493)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/6e42e135-7aee-43bf-89e8-93784dafe204)

**Comment by scholokov** [comment]
please retest

**Comment by prokopenkoga1977** [comment]
@scholokov changed the bug report in accordance with the new requirements

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
