### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region-Wrong language in the travel description

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#3686]
**Steps to playback:**
1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Scroll to the trip description

**Actual result:**
The description is written in Russian

**Expected result:** 
The description of the trip is written in Ukrainian

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126 
![текст має бути українською мовою](https://github.com/scholokov/long-travel-2/assets/132911639/b037b5ff-4532-4f3e-adf2-970d57c9f098)

**Comment by DmytroMarkulych** [comment]
@Artem-16 
1. Старайтеся не використовувати "incorrect" в Summary
2. Додайте атрибути баг репорту: 


![Image](https://github.com/scholokov/long-travel-2/assets/88647733/753ed6c4-9888-4da9-8e21-3a57647a8176)

**Comment by Artem-16** [comment]
що саме fixed?
