### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - Untrue travel translation in the search menu

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#3687]
**Steps to playback:**
1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Search menu

**Actual result:**
The name of the trip in the translation does not match the name in the search

**Expected result:**
The name of the trip in the translation matches the name in the search

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126

**![не вірний переклад](https://github.com/scholokov/long-travel-2/assets/132911639/2efe4ca8-f48b-4be6-944c-02ec3dea5dff)**

**Comment by DmytroMarkulych** [comment]
@Artem-16 
1. Не використовуйте слова типу incorrect в Summary
2. Додайте атрибути баг репорту 

![Image](https://github.com/scholokov/long-travel-2/assets/88647733/df6e7935-952b-420d-8330-28c4d404b551)

**Comment by scholokov** [comment]
назва у превью формується з цього документу:
https://github.com/scholokov/long-travel-2/wiki/3.1-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%9F%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA

назва подорожі на мапі формується по принципу (пункт 1.2):
https://github.com/scholokov/long-travel-2/wiki/3.2-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%93%D0%BB%D0%BE%D0%B1%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0-%D0%BA%D0%B0%D1%80%D1%82%D0%B0-%D0%B7-%D0%BC%D0%B0%D1%80%D1%88%D1%80%D1%83%D1%82%D0%B0%D0%BC%D0%B8

**Comment by Artem-16** [comment]
1.Вибачте, але як користувач я не як не знайду с таким перекладом подорож "Шацькі Озера" .
2. За вимогами "Ім'я подорожі має відповідати імені подорожі". Ім'я "shadck" ну не як не відповідає вимогам.
![вимоги1](https://github.com/scholokov/long-travel-2/assets/132911639/70b22335-18f5-47d2-b8cd-d4f705ac7f82)

3. Ось приклад з вимог де подорож "mezhigorie" або "myrgorod" можна зрозуміти і знайти ці подорожі
![вимоги 3](https://github.com/scholokov/long-travel-2/assets/132911639/cb5da40a-ccf2-4dcd-91cc-089683816f7d)

**Comment by scholokov** [comment]
для цього є сенс використовувати "айді" подорожі
у вашому випадку це "20160814_24_shadsk"
тобто це права частина URL
і вже маючи його, шукати по документу:
<img width="743" alt="image" src="https://github.com/scholokov/long-travel-2/assets/22824947/26a7542b-9cf6-4881-bd84-3724bf660a7e">

**Comment by Artem-16** [comment]
Я як користувач сайту зайду і буду шукати подорож по назві ну не як по "id", бо в мене нема можливості взнати "id".

**Comment by scholokov** [comment]
ну миж зараз кажемо саме про "перевірку", а не те, як себе буде вести користувач сайту.
тобто є сутність - подорож. вона унікалізується саме по айді.
а вже назва є  характеристикою подорожі, а не її первинною частиною.
після перевірки і виправлення, вже кінцевий користувач зможе користуватися пошуком і шукати цю подорож за назвою, але у нас наразі етап саме розробки

**Comment by Artem-16** [comment]
Зрозуміло.
Дякую за пояснення)
то що мені робити з цим репортом?

**Comment by scholokov** [comment]
ну простіше мабуть цей баг закрити і відкриті нові
бо там же по факту назви неправильні в обох місцях :))))
тобто це буде 2 баги

**Comment by scholokov** [comment]
по правильному, на всіх реалтних проектах - помилки, "які НЕ будуть виправлятися" завжи закриває лише автор. це робиться тому, що автору дається шанс "відстояти" свою точку зору. і лише якщо він "згоден" з цим рішенням, він закриває баг з відміткою, наприклад "not an issue", або, часні випадки: "було створено 2 баги такі то" і переводиться у статус "Canceled". там знаходяться баги, які НЕ були виправлені, щоб усім було зрозуміло.
тому так, краще якщо це зробите ви

**Comment by Artem-16** [comment]
Дякую

**Comment by Artem-16** [comment]
#3086
