### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region-The name of the trip was translated with an error

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#3689]
**Steps to playback:**
1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Scroll to the trip description

**Actual result:**
The description is written in Russian

**Expected result:**
The description of the trip is written in Ukrainian

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![текст має бути українською мовою 1](https://github.com/scholokov/long-travel-2/assets/132911639/6af53aac-0a91-4619-bfea-25d924ad8bba)

**Comment by DmytroMarkulych** [comment]
@Artem-16

1. Старайтеся не використовувати "Incorrect" в описі баг репорту.
2. Після "Кроків для відтворення" має йти Actual Result
3. Додайте атрибути в баг репорт


![Image](https://github.com/scholokov/long-travel-2/assets/88647733/7b399e07-5021-4638-b943-aad96ee38c7d)

**Comment by Artem-16** [comment]
Вибачте мені, а як вірно написати? Бо мій рівень англійської не такий сильний

**Comment by DmytroMarkulych** [comment]
@Artem-16 виправили вірно. Просто констатуємо факти що є і що має бути.

**Comment by scholokov** [comment]
fixed

**Comment by Artem-16** [comment]
#3086
