### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region-The slideshow is not playing

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#3690]
**Steps to playback:**
1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Go down to the photos
3. Open the photo
4. Start the slide show

**Actual result:**
The slideshow is not playing

**Expected result:**
Show photos with a slideshow

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126

https://github.com/scholokov/long-travel-2/assets/132911639/107c656e-cb74-4dfc-8e25-0bec881cde57

**Comment by DmytroMarkulych** [comment]
@Artem-16

1. Після "Кроків для відтворення" має йти Actual Result

**Comment by scholokov** [comment]
функціонал слайд шоу прибраний
