### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region-Manual photo viewing does not work

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#3691]
**Steps to playback:**
1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Go down to the photos
3. Open the photo
4. Click the arrow to the right 

**Actual result:**
Manually viewing photos is not working

**Expected result:**
View photos in manual mode

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126

https://github.com/scholokov/long-travel-2/assets/132911639/9e7e4460-0204-4e14-ad6d-bbbf22ba7df5

**Comment by DmytroMarkulych** [comment]
@Artem-16

1. Старайтеся не використовувати "does not work" в описі баг репорту.
2. Після "Кроків для відтворення" має йти Actual Result
3. Додайте атрибути в баг репорт


![Image](https://github.com/scholokov/long-travel-2/assets/88647733/7b399e07-5021-4638-b943-aad96ee38c7d)

**Comment by Artem-16** [comment]
#3086

**Comment by scholokov** [comment]
fixed
