### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region-In trip search, the map changes, not the trip description

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#3692]
**Steps to playback:**
1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Search for a trip
3. Choose a trip

**Actual result:**
In the search, the map changes, and the description remains unchanged

**Expected result:**
In the search, the map and the description of the trip change

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126

https://github.com/scholokov/long-travel-2/assets/132911639/0cca5998-0b6e-4295-98dd-c69893d995eb

![Пошук Шацьки озера](https://github.com/scholokov/long-travel-2/assets/132911639/30d49eb7-4c35-4112-8583-06d1be1899f8)
![Пошук Озера](https://github.com/scholokov/long-travel-2/assets/132911639/cdd6ca27-e51e-44aa-b6bf-20c1db397f5c)

**Comment by DmytroMarkulych** [comment]
@Artem-16

1. Після "Кроків для відтворення" має йти Actual Result
2. Додайте атрибути в баг репорт


![Image](https://github.com/scholokov/long-travel-2/assets/88647733/7b399e07-5021-4638-b943-aad96ee38c7d)

**Comment by scholokov** [comment]
1. навіть якщо є відео, краще все рівно додавати скріншот, щоб як мінімум було зрозуміло про який елемент іде мова

**Comment by Artem-16** [comment]
Яку ще додати інформацію?

**Comment by Artem-16** [comment]
#3086
