### ISSUE TITLE
20160710_0807_italy_odessa/The flag of Ukraine is present in the block Preparation (Підготовка)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3694]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the Praparation block.

3. Pay attention to the presence of the flag of Ukraine on the right side of the block.

**Actual result:**
The flag of Ukraine is present in the block Preparation (Підготовка)

**Expected result:**
The flag in the preparation block must be absent.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.3-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%A1%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D1%96-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8#preparation

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/59b14a41-a3c4-4716-b11c-069ee7cf3ebd)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/a258b8da-e6e5-4964-8b43-e33e87767ba5)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
