### ISSUE TITLE
20170709_protsiv/ In the Legend of the Map the name of the active element is "Link"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3695]
Steps to reproduce:

1. Open https://test.long-travel.live/20170709_protsiv/
2. Scroll down to the Legend of the Map
3. Pay attention to the the name of the active element

Actual Result: the name of the active element is **"Link"**
Expected Result: the name of the active element is **"Відкрити подорож"**

Requirements: https://github.com/scholokov/long-travel-2/wiki/4.4-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%9C%D0%B0%D0%BF%D0%B0

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/67b666ca-b7d7-4575-abc5-51a67669d310)

**Comment by ODrobik** [comment]
#3235

**Comment by scholokov** [comment]
виправлено
