### ISSUE TITLE
20150919_kiev_aviation_museum/ In the Legend of the Map the Name of the active element is "Link"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3696]
Steps to reproduce:

1. Open https://test.long-travel.live/20150919_kiev_aviation_museum/
2. Scroll down to the Legend of the Map
3.  Pay attention to the the name of the active element

Actual Result: the name of the active element is **"Link"**
Expected Result: the Name of the active element is **"Відкрити подорож"**

Requirements: https://github.com/scholokov/long-travel-2/wiki/4.4-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6.-%D0%9C%D0%B0%D0%BF%D0%B0

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/ad79979f-3991-47e2-8a8f-6a8ca44639d4)

**Comment by ODrobik** [comment]
#2995

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
