### ISSUE TITLE
20190720_0811_balcans - Loading GIF not disappearing after loading travel page

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3698]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Wait for the page to finish loading
3. Pay attention to the loading gif in the center of the screen

**Actual Result**
Loading GIF not disappearing after loading travel page

**Expected Result**
Loading GIF disappearing after loading travel page

**Additional information**
Figma link: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=IYAAGWg7ciWGWCZg-0

**Enviroments**
Windows 10, Chrome 114.0.5735.110 (64 bit)
Android 8.1.0, Chrome 114.0.5735.58
![Курси – QAX Camp - Google Chrome 06 06 2023 14_55_56](https://github.com/scholokov/long-travel-2/assets/95171672/405535b2-b06a-4038-9f3d-955596075eb8)
![photo_2023-06-06_15-22-16](https://github.com/scholokov/long-travel-2/assets/95171672/f864fbce-b253-45cd-8307-e87b1473d053)

**Comment by DmitriiNasonov** [comment]
#233

**Comment by DmitriiNasonov** [comment]
Yes, I check it for these indicators
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 11 06 2023 17_27_02](https://github.com/scholokov/long-travel-2/assets/95171672/f12dc886-506e-4123-b0a2-22053beeb982)
![photo_2023-06-11_17-33-06](https://github.com/scholokov/long-travel-2/assets/95171672/31723543-50ae-4061-b4f5-0da56d098f50)

**Comment by DmytroMarkulych** [comment]
@DmitriiNasonov перевірте краще через Devtools  чи немає запитів в статусі pending

**Comment by DmitriiNasonov** [comment]
status "pending" is out
![DevTools - test long-travel live_20190720_0811_balcans_ 13 06 2023 16_54_40](https://github.com/scholokov/long-travel-2/assets/95171672/14e1ca26-8427-49d3-a326-762311e719e3)

**Comment by scholokov** [comment]
please retest

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
