### ISSUE TITLE
20190720_0811_balcans - Body - "Road: Киев Украина – Medias Romania" block - Photos in the body belong to another structure block

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3703]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Road: Киев Украина – Medias Romania" block
3. Pay attention to photos in the body

**Actual Result**
Photos in the body belong to another structure block

**Expected Result**
Photos in the body belong to this structure block

**Enviroments**
Windows 10, Chrome 114.0.5735.110 (64 bit)
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 06 06 2023 16_27_40](https://github.com/scholokov/long-travel-2/assets/95171672/16a7769e-4100-45da-b98b-42418a69f37d)

**Comment by DmitriiNasonov** [comment]
#233

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
