### ISSUE TITLE
20190720_0811_balcans - Body - "Hotel: Apartments Dan Mija" block - Photos in the body belong to another structure block

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3704]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Hotel: Apartments Dan Mija" block
3. Pay attention to photos in the body

**Actual Result**
Photos in the body belong to another structure block

**Expected Result**
Photos in the body belong to this structure block

**Enviroments**
Windows 10, Chrome 114.0.5735.110 (64 bit)
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 06 06 2023 16_45_38](https://github.com/scholokov/long-travel-2/assets/95171672/d2bc58b8-96d9-4ce8-baa5-6e9bffffce9c)

**Comment by DmitriiNasonov** [comment]
#233

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
