### ISSUE TITLE
20170709_protsiv/PhotoGallery, clicked on the Arrow to Scroll the photo LightBox is not displayed

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3705]
Steps to Reproduce:

1. Open https://test.long-travel.live/20170709_protsiv/
2. Scroll down to PhotoGallery
3. Click on 1st photo to open LightBox
4. Click on the arrow on the right
5. Pay attention to the photo

Actual Result: the photo LightBox is not displayed
Expected Result: the photo LightBox is displayed

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/05a6e6b8-c06c-40cf-8480-e6ba2edc881c)

**Comment by ODrobik** [comment]
#3235

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
