### ISSUE TITLE
wiki/The page "4. Подорож" the word "превью" is in russian language

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3706]
Steps to reproduce:

1. Open: https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6
2. Pay attention to the word "превью" on the page "4. Подорож"

Actual Result: the word "превью" is in russian language
Expected Result: the word "прев'ю" is in ukrainian language

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/7684c183-d212-41e0-a58e-4fcb9fb13554)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
veriefed
