### ISSUE TITLE
20091026_1102_toronto - "Best Western Primrose Hotel" structure block - Font-family of the structure block name is "Rubik"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3707]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20091026_1102_toronto/
2. Scroll to "Best Western Primrose Hotel" structure block
3. Open DevTools.
4. Сheck font-family of the "Best Western Primrose Hotel" structure block name

**Actual result:**
Rubik

**Expected result:**
Amazing Slab Trial

**Additional information**
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-7&t=NGl13yTcDDJcfrhB-0

**Environment:**
Windows 10, Chrome 114.0.5735.110 (64 bit)
![DevTools - test long-travel live_20091026_1102_toronto_ 07 06 2023 11_56_33](https://github.com/scholokov/long-travel-2/assets/95171672/38c28759-69aa-470d-8544-8d12ddd6e727)

**Comment by scholokov** [comment]
please retest

**Comment by DmitriiNasonov** [comment]
Checked. bug isn't reproduced
