### ISSUE TITLE
20091026_1102_toronto - "Downtown-Toronto" structure block - Font-family of the structure block name is "Rubik"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3708]
**Steps to reproduce:**
1. Open https://test.long-travel.live/20091026_1102_toronto/
2. Scroll to "Downtown-Toronto" structure block
3. Open DevTools.
4. Сheck font-family of the "Downtown-Toronto" structure block name

**Actual result:**
Rubik

**Expected result:**
Amazing Slab Trial

**Additional information**
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-7&t=NGl13yTcDDJcfrhB-0

**Environment:**
Windows 10, Chrome 114.0.5735.110 (64 bit)
![DevTools - test long-travel live_20091026_1102_toronto_ 07 06 2023 12_27_31](https://github.com/scholokov/long-travel-2/assets/95171672/469d5615-8c88-4d7b-903a-97858a40358d)

**Comment by scholokov** [comment]
please retest
