### ISSUE TITLE
20091026_1102_toronto - "CN Tower" structure block - Font-family of the structure block name is "Rubik"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3709]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20091026_1102_toronto/
2. Scroll to "CN Tower" structure block
3. Open DevTools.
4. Сheck font-family of the "CN Tower" structure block name

**Actual result:**
Rubik

**Expected result:**
Amazing Slab Trial

**Additional information**
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-7&t=NGl13yTcDDJcfrhB-0

**Environment:**
Windows 10, Chrome 114.0.5735.110 (64 bit)
![DevTools - test long-travel live_20091026_1102_toronto_ 07 06 2023 12_34_41](https://github.com/scholokov/long-travel-2/assets/95171672/d959443a-4993-4f55-a2df-3d99e827a307)

**Comment by scholokov** [comment]
please retest

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
