### ISSUE TITLE
20170709_protsiv/ The Standard block does not meet the requirements

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3719]
Steps to Reproduce:

1. Open https://test.long-travel.live/20170709_protsiv/
2. Pay attention to the structure Standard block 

Actual Result: the Standard block does not meet the requirements
Expected Result: the Standard block meets the requirements

Requirements: https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6#13-%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D0%B8%D0%B9-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/efaa3391-be9d-4f55-b7c1-ab454c2ec2fb)

**Comment by ODrobik** [comment]
#3235

**Comment by scholokov** [comment]
fixed
