### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - Travel date not in the cauldron in header

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#3721]
**Steps to playback:**
1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Pay attention to the data in the Header

**Actual result:**
The date of travel is above the map

**Expected result:**
Under the inscription "Shatsk Lakes" there is a date
![дата хедер](https://github.com/scholokov/long-travel-2/assets/132911639/63f979a9-ae48-45cc-b8c7-ee0dd391ed85)
![хедер](https://github.com/scholokov/long-travel-2/assets/132911639/39ed7075-fa3f-406e-abb0-4bbdc78b2029)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![дата має бути в хедері](https://github.com/scholokov/long-travel-2/assets/132911639/4a87a681-2372-4c1e-921e-99395726a356)

**Comment by DmytroMarkulych** [comment]
@Artem-16 
Не можу відтворити баг по Кроках для відтворення. Відкриваю лінку, і далі просто хедер. Можливо деталі допоможуть?

**Comment by DmytroMarkulych** [comment]
Зверніть увагу на попередній коментар. Просто додайте степи для відтворення дефекту

**Comment by DmytroMarkulych** [comment]
"pay attention to the data in the Header" - в хедері є багато елементів, краще вказувати на який саме звертаємо увагу

**Comment by scholokov** [comment]
fixed

**Comment by Artem-16** [comment]
#3086
