### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - The endpoint is displayed as a droplet

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#3722]
**Steps to playback:**
1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Pay attention to map

**Actual result:**
The endpoint is displayed as a droplet

**Expected result:**
The endpoint is displayed with a round icon
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6#122-%D0%BC%D0%B0%D1%80%D1%88%D1%80%D1%83%D1%82-%D0%BF%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96
![круглий значок](https://github.com/scholokov/long-travel-2/assets/132911639/2f431dac-d944-4ea3-a612-d5f6ffdd2933)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![Точка а не крапля](https://github.com/scholokov/long-travel-2/assets/132911639/8dd4f194-7c1e-4773-b8c0-a55d5000ace7)

**Comment by DmytroMarkulych** [comment]
@Artem-16
Не можу відтворити баг по Кроках для відтворення. Відкриваю лінку, і далі просто карта. Можливо деталі допоможуть?
Додайте посилання на специфікацію

**Comment by Artem-16** [comment]
Скоріше за все це не баг а фіча додатку "Travel Map" але вимогах написано має бути круглим )

**Comment by DmytroMarkulych** [comment]
Давайте ще раз перевіримо вимоги та додамо їх до баг репорту. Якщо так має бути то ми просто закриємо дефект, якщо ж ні, тоді це баг

**Comment by Artem-16** [comment]
Я додав скрін шот з вимог як має бути... Чи якось по інакшому треба зробити це?

**Comment by scholokov** [comment]
у такому випадку ще гарно додавати лінку на вимоги

**Comment by scholokov** [comment]
@Artem-16

**Comment by Artem-16** [comment]
Додав лінку

**Comment by scholokov** [comment]
виправлено у вимогах. пункт пункт 1.2.2.2
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6
