### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - Missing link to trips in the right panel under the route

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#3723]
**Steps to playback:**
1. Open https://www.test.long-travel.live/20160814_24_shadsk
2.Pay attention to the link in map

**Actual result:**
No link to travel

**Expected result:**
Link to the trip
![вимога лінка](https://github.com/scholokov/long-travel-2/assets/132911639/c95024b2-6255-42cd-85d0-1b25568317a3)
![скрін лінка](https://github.com/scholokov/long-travel-2/assets/132911639/136a6f16-c3e5-4ae7-9691-792097835dfd)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![лінка відсутня](https://github.com/scholokov/long-travel-2/assets/132911639/85472c22-bab9-4464-a2e8-85e577651d2d)

**Comment by DmytroMarkulych** [comment]
@Artem-16
Не можу відтворити баг по Кроках для відтворення. Відкриваю лінку, і далі просто карта в лівому краю. Можливо деталі допоможуть?

**Comment by DmytroMarkulych** [comment]
@Artem-16 в останій крок додайте Pay attention to map . Що допоможе підказати на що звертати увагу

**Comment by scholokov** [comment]
fixed
