### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - There is no photo for the trip in the right panel under the route

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#3724]
**Steps to playback:**
1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Pay attention to photo in map

**Actual result:**
No travel photo available

**Expected result:**
Photo of the trip is present
![вимога фото карта](https://github.com/scholokov/long-travel-2/assets/132911639/e68fc1e6-ffc7-49bb-a95c-dc3a2d43a2a7)
![скрін фото мапа](https://github.com/scholokov/long-travel-2/assets/132911639/29af2ba9-d55e-4dbe-bedf-da7496705b28)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![відсутнє фото пдорожі](https://github.com/scholokov/long-travel-2/assets/132911639/49f918ab-96b5-4f26-93c6-fe732e2b021d)

**Comment by DmytroMarkulych** [comment]
@Artem-16 в останій крок додайте Pay attention to photo in map . Що допоможе підказати на що звертати увагу

**Comment by Artem-16** [comment]
Дякую за підказку)))

**Comment by scholokov** [comment]
fixed

**Comment by Artem-16** [comment]
#3086
