### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - Slideshow plays a partial photo

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#3725]
**Steps to playback:**
1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Scroll to the photo gallery
3. Play the photo
4. On the displayed photo in the upper right corner, click the "Play" button

**Actual result:**
Slideshow plays a single photo

**Expected result:**
Slideshow plays all photos

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![слайд шоу не робить](https://github.com/scholokov/long-travel-2/assets/132911639/28a1acf1-e850-4704-80b3-57c551ce4448)
![слайд шоу перегортає одне фото](https://github.com/scholokov/long-travel-2/assets/132911639/f3ca6d29-1a24-4c0a-b4b0-9e0aba13950d)

**Comment by Artem-16** [comment]
#3086

**Comment by scholokov** [comment]
функціонал слайд шоу прибраний
