### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - The date and description of the trip are missing above the video

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#3727]
**Steps to playback:**
1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Scroll down to the bottom of the video

**Actual result:**
There is no date or description of the trip above the video

**Expected result:**
Above the video, there are dates and a description of the trip

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![дата і опис подорожі відстуні](https://github.com/scholokov/long-travel-2/assets/132911639/8ccedbba-7bba-4d5b-ab07-bff7b0a67a9e)

**Comment by scholokov** [comment]
fixed

**Comment by Artem-16** [comment]
#3086
