### ISSUE TITLE
20190720_0811_balcans - Header - Travel name is "20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3756]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Pay attention to travel name

**Actual Result**
Travel name is "20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine"

**Expected Result**
Travel name is "Балкани"

**Additional information**
(Entry number is 061) https://github.com/scholokov/long-travel-2/wiki/3.1-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%9F%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA

**Enviroments**
Windows 10, Chrome 114.0.5735.110 (64 bit)
Android 8.1.0, Chrome 114.0.5735.61
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 11 06 2023 19_11_54](https://github.com/scholokov/long-travel-2/assets/95171672/c02355c9-f40f-4d9b-bc1e-06debbcd87a2)
![photo_2023-06-11_19-12-05](https://github.com/scholokov/long-travel-2/assets/95171672/8fd00511-9492-4a2c-9fbb-4a8a74342b4f)

**Comment by DmitriiNasonov** [comment]
bug-report fixed

**Comment by DmitriiNasonov** [comment]
#233

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
