### ISSUE TITLE
20160618_mezhigorie/Mezhyhirya National Park - Cannot skip to the next photo in manual mode

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#3757]
**Steps to playback:**

1. Open https://www.test.long-travel.live/20160618_mezhigorie
2. Scroll to photo galleries
3. Open photography
4. Click on the arrow to the right

**Actual result:**
Fails to skip to the next photo

**Expected result:**
Moves to the next photo

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![межигіря фото](https://github.com/scholokov/long-travel-2/assets/132911639/ae33a9ee-c90f-40e3-a99c-462a8eaae601)
![межигіря фото 2](https://github.com/scholokov/long-travel-2/assets/132911639/165866d1-4ab9-423a-ae03-5575726cab2a)

**Comment by Artem-16** [comment]
#3084

**Comment by scholokov** [comment]
fixed
