### ISSUE TITLE
20160618_mezhigorie/Mezhyhirya National Park - Photo gallery slideshow does not play

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#3758]
**Steps to playback:**

1. Open https://www.test.long-travel.live/20160618_mezhigorie
2. Scroll to photo galleries
3. Open photography
4. Press the slideshow play button

**Actual result:**
Can't play a slideshow

**Expected result:**
Slideshow is playing

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![Межигір’я слайдшоу](https://github.com/scholokov/long-travel-2/assets/132911639/eb955d36-ed90-4ab4-8a6b-68298d6524d2)
![Межигіря слайдшоу 2](https://github.com/scholokov/long-travel-2/assets/132911639/58586156-cfc5-429b-8026-64d7fc9d52af)

**Comment by Artem-16** [comment]
#3084

**Comment by scholokov** [comment]
функціонал слайд шоу прибраний
