### ISSUE TITLE
20160618_mezhigorie/Mezhyhirya National Park - Clicking on the link opens a journey without photo galleries

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#3779]
**Steps to playback:**
1. Open https://www.test.long-travel.live/20160618_mezhigorie
2.  Scroll to the map with the route
3. Click on the travel link
4. Follow the link
5. Scroll to the photo gallery

**Actual result:**
No photo gallery

**Expected result:**
There are photo galleries

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![лінка Мижегіря](https://github.com/scholokov/long-travel-2/assets/132911639/ab549234-c1f3-472d-80b3-c82a223455b8)
![лінка Мижегіря 2](https://github.com/scholokov/long-travel-2/assets/132911639/1d2a5348-9574-40f8-ab31-ceb05378f018)

**Comment by DmytroMarkulych** [comment]
Швидше за все тут справа не в лінку, а тих фото по факту немає

**Comment by Artem-16** [comment]
Але вони повинні бути..По логіці при переходу по лінку ти маєш попадати на подорож з повним описом фото галерей і відео

**Comment by scholokov** [comment]
згідно вимог лінка має вести на прод. а на проді стара версія цієї сторінки. коли оновимо прод буде все ок. наразі головне що лінка веде у правильне місце

**Comment by Artem-16** [comment]
ок. зрозумів))

**Comment by Artem-16** [comment]
#3084
