### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - Date format is false 2016.08.15

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#3781]
**Steps to playback:**

1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Scroll to the travel block "Svityaz"
3. Pay attention to the block

**Actual result:**
Date format is false 2016.08.15

**Expected result:**
Date format 15.08.2016
![вимоги дата](https://github.com/scholokov/long-travel-2/assets/132911639/f7f36ba2-ffc9-4070-993e-82b79af04c7f)
![блок дата](https://github.com/scholokov/long-travel-2/assets/132911639/95914bd9-dfba-4a40-8d74-89cc7ed1e1e9)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![формат дати не вірний](https://github.com/scholokov/long-travel-2/assets/132911639/d9d8bcbd-da72-4d73-a613-285855e428dd)

**Comment by DmytroMarkulych** [comment]
Не використовуйте слова bad, correct, wrong.. вказуйте замість них фактично що маємо

**Comment by DmytroMarkulych** [comment]
напишіть будь ласка фактичний формат дати який ми маємо

**Comment by scholokov** [comment]
fixed

**Comment by Artem-16** [comment]
#3086
