### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - Missing block

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#3782]
**Steps to playback:**

1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Scroll to the travel  Road: Svityaz - Kyiv

**Actual result:**
- No "standard block" for travel "Road: Svityaz - Kyiv"
- The flag of Ukraine is not displayed in the upper right corner of the block
- Only one date is displayed under the travel name

**Expected result:**
- "Standard block" for travel is present "Road: Svityaz - Kyiv"
- The flag of Ukraine is displayed in the upper right corner of the block
- The start and end dates of the trip are displayed under the trip name

![вимога блоку ](https://github.com/scholokov/long-travel-2/assets/132911639/df83f6ad-4b1e-4d9b-a562-26378ed19288)
![блок подорожі](https://github.com/scholokov/long-travel-2/assets/132911639/f65aaf7b-12ea-4b3a-88c3-d8bd7f82a745)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![відсутній блок подорожі](https://github.com/scholokov/long-travel-2/assets/132911639/3538158f-13c5-4e38-ac9f-fb2eb0bdae08)

**Comment by DmytroMarkulych** [comment]
Додайте деталей в баг репорт, назву блоку де він пропущений і що там пропущено

**Comment by scholokov** [comment]
fixed

**Comment by Artem-16** [comment]
Відсутній прапор "України" в правому верхньому куті
Відсутня дата подорожі в форматі "14.08.2016 - 24.08.2016"

**Comment by scholokov** [comment]
please retest

**Comment by Artem-16** [comment]
#3086
