### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - The block is not properly designed

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#3783]
**Steps to playback:**

1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Scroll to the travel block Road: Kyiv - Svityaz
3. Pay attention to the block

**Actual result:**
The block is not properly designed

**Expected result:**
The block meets the requirements
![вимога блоку ](https://github.com/scholokov/long-travel-2/assets/132911639/177a0ad7-85e2-4dbe-89f6-0032b737194e)
![блок подорожі](https://github.com/scholokov/long-travel-2/assets/132911639/e3f43dbc-32b0-46f9-80aa-ff537310f498)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![від сутня картинка і флаг](https://github.com/scholokov/long-travel-2/assets/132911639/a02101b4-67fd-48fd-9f1f-fed209e27ef3)

**Comment by DmytroMarkulych** [comment]
не використовуйте будь ласка слова correct. Просто вказуйте фактично що має бути

**Comment by scholokov** [comment]
fixed

**Comment by Artem-16** [comment]
Відсутній прапор  "України" в правому верхньому куті 
Відсутня дата подорожі в форматі "14.08.2016 - 24.08.2016"

**Comment by DmytroMarkulych** [comment]
додайте скріншот до коментаря

**Comment by Artem-16** [comment]
Відсутня дата подорожі в форматі "14.08.2016 - 24.08.2016"
![data ozero](https://github.com/scholokov/long-travel-2/assets/132911639/603c9722-9924-4109-8907-f818f5b0056c)

**Comment by scholokov** [comment]
незрозумілий коментар, що мається на увазі?

**Comment by Artem-16** [comment]
Як написано в вимогах має бути початкова дата і кінцева дата подорожі. 
![data vimogi](https://github.com/scholokov/long-travel-2/assets/132911639/99ac27da-7b1b-4327-b1ad-efcb2e39568a)

**Comment by scholokov** [comment]
але там написано що 3-й рядок може бути написаний  у двох форматах - 3а та 3b. тобто коли є одна чи 2 дати

**Comment by Artem-16** [comment]
В мому розумінні  "3а" це формат дати коли подорож проходить за один день туди та назад.  
А "3b" це формат дати коли подорож проходить більше ніж за один день. Як в мому випадку подорож проходила з "14.08.2016 - 24.08.2016"
В Figma показано тільки один варіант "3b"
![дата фігма](https://github.com/scholokov/long-travel-2/assets/132911639/124fa111-55d5-47d1-8d99-8c021490239f)

**Comment by scholokov** [comment]
фігма - то лише про дизайн. там відображено яким чином все має виглядати. 
а за інформацію відповідають функціональні вимоги

**Comment by Artem-16** [comment]
Тоді як я розумію вимоги то "3а" це формат дати подорожі яка проходить за один день а "3b" це формат дати подорожі яка проходить більше ніж один день..Відповідно в мене в стандартному блоці дата повинна бути вказана за вимогами "3b". Як що я вірно розумію вимоги.)

**Comment by scholokov** [comment]
ну ми ж наразі говоримо не взагалі про всю подорож (тобто у верхньому загальному блоці - дати має бути 2), а говоримо лише про блок переміщення з пункту А в пункт Б, яке було за 1 день, і тобто має бути одна дата

**Comment by Artem-16** [comment]
То ді в нас дату від точки А в точку В, вказуємо тільки в хедері, а в інших блоках тільки одна дата в яку проходила сама подорож... Ну тоді треба так і написати в вимогах, бо трохи не зрозуміло коли використовується "3а" а коли "3b".

**Comment by scholokov** [comment]
ну просто не можна виключати ситуацію, коли переміщення займе більше одного дня. можна саме про це додати коментар

**Comment by Artem-16** [comment]
Я зрозумів як що в описі подорожі вказано що подорож від точки А в точку В, зайняла один день томи ставимо одну дату як що більше то відповідно дві дати. Вірно?

**Comment by scholokov** [comment]
так. 
ще глянь на вимоги
чи тепер стало зрозуміліше?
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

**Comment by Artem-16** [comment]
Супир. Так краще зрозуміло. Дякую)

**Comment by Artem-16** [comment]
#3086
