### ISSUE TITLE
20190720_0811_balcans - Body - "Hotel: Apartments Dan Mija" block - Body - Video and/or photo gallery missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3785]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Hotel: Apartments Dan Mija" block
3. Pay attention to content in the body

**Actual Result**
Video and/or photo gallery missing

**Expected Result**
Video and/or photo gallery present

**Enviroments**
Windows 10, Chrome 114.0.5735.110 (64 bit)
Android 8.1.0, Chrome 114.0.5735.61
![Image](https://github.com/scholokov/long-travel-2/assets/95171672/61cd7501-4a96-4edf-8491-a92755b68cd2)
![photo_2023-06-13_17-30-41](https://github.com/scholokov/long-travel-2/assets/95171672/e3b9ed74-7402-46aa-886f-9a297e65646b)

**Comment by DmitriiNasonov** [comment]
#233

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduced
![Балкани – Long-Travel - Google Chrome 20 06 2023 19_38_23](https://github.com/scholokov/long-travel-2/assets/95171672/f6270d29-b757-4c45-8440-edd758719118)
![photo_2023-06-20_19-38-30](https://github.com/scholokov/long-travel-2/assets/95171672/0e040827-5297-407c-b236-5014b7f1fdec)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduced
![Балкани – Long-Travel - Google Chrome 28 06 2023 12_05_48](https://github.com/scholokov/long-travel-2/assets/95171672/636890bf-66a1-44ad-b765-da6a01239be4)
![photo_2023-06-28_12-12-38](https://github.com/scholokov/long-travel-2/assets/95171672/f400d8d9-7aac-458f-875e-3ec1b7615e62)

**Comment by DmitriiNasonov** [comment]
checked. fixed partly. bug is reproduced at phone. created new bug report
