### ISSUE TITLE
20190720_0811_balcans - Body - "Hotel: Pensiunea Jacqueline" block - Body - Video and/or photo gallery missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3786]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Hotel: Pensiunea Jacqueline" block
3. Pay attention to content in the body

**Actual Result**
Video and/or photo gallery missing

**Expected Result**
Video and/or photo gallery present

**Enviroments**
Windows 10, Chrome 114.0.5735.110 (64 bit)
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 13 06 2023 17_47_13](https://github.com/scholokov/long-travel-2/assets/95171672/224ee152-98af-4de0-8452-166d2f085389)

**Comment by DmitriiNasonov** [comment]
#233

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduced
![Балкани – Long-Travel - Google Chrome 20 06 2023 19_42_03](https://github.com/scholokov/long-travel-2/assets/95171672/d06f3b45-8ad8-4c13-93a6-4b7c96997a52)
![photo_2023-06-20_19-42-37](https://github.com/scholokov/long-travel-2/assets/95171672/ceb05a35-62a2-4e4b-9ed7-1b4bdc83668c)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduced
![Балкани – Long-Travel - Google Chrome 28 06 2023 12_30_33](https://github.com/scholokov/long-travel-2/assets/95171672/245a6229-e558-46ac-a649-4333672683f5)

**Comment by scholokov** [comment]
please retest

**Comment by DmitriiNasonov** [comment]
retested. bug isn't reproduce
