### ISSUE TITLE
20190720_0811_balcans - Body - "Hotel: Orasac" block - Body - Video and/or photo gallery missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3787]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Hotel: Orasac" block
3. Pay attention to content in the body

**Actual Result**
Video and/or photo gallery missing

**Expected Result**
Video and/or photo gallery present

**Enviroments**
Windows 10, Chrome 114.0.5735.110 (64 bit)
Android 8.1.0, Chrome 114.0.5735.61
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 13 06 2023 18_13_42](https://github.com/scholokov/long-travel-2/assets/95171672/17394cb1-4448-4704-a970-9b3dcf67192c)
![photo_2023-06-13_18-14-08](https://github.com/scholokov/long-travel-2/assets/95171672/935163dc-d998-42ce-8d86-dde2746b01e1)

**Comment by DmitriiNasonov** [comment]
#233

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduced
![Балкани – Long-Travel - Google Chrome 20 06 2023 19_44_57](https://github.com/scholokov/long-travel-2/assets/95171672/a4dc13ed-4bea-4d33-9513-b2bed7737b30)
![photo_2023-06-20_19-45-17](https://github.com/scholokov/long-travel-2/assets/95171672/b5431c94-a47c-449a-974e-eb8aab12f4f4)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
