### ISSUE TITLE
20190720_0811_balcans - Body - "Belgrade" block - Photos in the body belong to another structure block

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3788]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Belgrade" block
3. Pay attention to photos in the body

**Actual Result**
Photos in the body belong to another structure block

**Expected Result**
Photos in the body belong to this structure block

**Enviroments**
Windows 10, Chrome 114.0.5735.110 (64 bit)
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 13 06 2023 18_34_45](https://github.com/scholokov/long-travel-2/assets/95171672/8606995a-cf0d-423f-92fc-dd47183e2f8f)

**Comment by DmitriiNasonov** [comment]
#233

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
