### ISSUE TITLE
20190720_0811_balcans - Body - "Hotel: Alexandar Central Apartments" block - Body - Video and/or photo gallery missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3789]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Hotel: Alexandar Central Apartments" block
3. Pay attention to content in the body

**Actual Result**
Video and/or photo gallery missing

**Expected Result**
Video and/or photo gallery present

**Enviroments**
Windows 10, Chrome 114.0.5735.110 (64 bit)
Android 8.1.0, Chrome 114.0.5735.61
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 13 06 2023 18_38_17](https://github.com/scholokov/long-travel-2/assets/95171672/5211630b-d01a-4f76-89ad-0905222b7b90)
![photo_2023-06-13_18-38-37](https://github.com/scholokov/long-travel-2/assets/95171672/4bfddc8b-7f6f-4331-aa75-ce6ca26bfdfb)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduce partially. created a new bug report
