### ISSUE TITLE
20190720_0811_balcans - Body - "Road: Makedonia – Albania" block - Photos in the body belong to another structure block

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3791]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Road: Makedonia – Albania" block
3. Pay attention to photos in the body

**Actual Result**
Photos in the body belong to another structure block

**Expected Result**
Photos in the body belong to this structure block

**Enviroments**
Windows 10, Chrome 114.0.5735.110 (64 bit)
Android 8.1.0, Chrome 114.0.5735.61
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 13 06 2023 18_57_19](https://github.com/scholokov/long-travel-2/assets/95171672/59c4b09d-73b4-4570-9bab-078500daa3ac)
![photo_2023-06-13_18-57-34](https://github.com/scholokov/long-travel-2/assets/95171672/704197b5-719a-4666-8d50-9856035f2c28)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduce partially. created a new bug report
