### ISSUE TITLE
20160710_0807_italy_odessa/The video name Lviv - Kiev is in English

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3792]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/

2. Scroll down to the video Lviv - Kiev of the  Road Lviv - Kyiv block.
3. Pay attention to the video name.

**Actual result:**
The video name Lviv - Kiev is in English

**Expected result:**
The video name Lviv - Kiev must be in Ukrainian

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/c02961b1-e344-4b99-9b86-b3cd4d6ce5ed)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/15f14c49-54e8-4d41-9969-485dc5e03fe2)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
