### ISSUE TITLE
20160710_0807_italy_odessa/The travel Italy-Odessa (20160710_0807_italy_odessa) is missed in Global map

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3793]
**Steps to retroduce:**

1. Open https://test.long-travel.live/travels/

2. Scroll down to Global map, travel list on the right side of the map.

3. Pay attention to the absence of the travel 20160710_0807_italy_odessa in the travel list.

**Actual result:**
The travel Italy-Odessa (20160710_0807_italy_odessa) is missed in Global map

**Expected result:**
The travel Italy-Odessa (20160710_0807_italy_odessa) must be in the travel list of Global map.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/3.2-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%93%D0%BB%D0%BE%D0%B1%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0-%D0%BA%D0%B0%D1%80%D1%82%D0%B0-%D0%B7-%D0%BC%D0%B0%D1%80%D1%88%D1%80%D1%83%D1%82%D0%B0%D0%BC%D0%B8

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/4caae6b8-d85c-43c5-9f59-4675beebe641)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/75d6746e-0f8c-4ac6-a629-12cd62bca335)

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/064b3fec-5d60-4e35-b545-c7a9d680fab2)

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/b7756afb-272c-4e28-81fd-dd00ac2aef5b)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/long-travel-2/assets/88647733/4632c0ac-44e7-4bda-b8c7-f5258b448c46)

**Comment by prokopenkoga1977** [comment]
виправив

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
