### ISSUE TITLE
20170417_kiylov/The design of header of the Farm Kiylov Askania block is missed

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3794]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170417_kiylov/

2. Scroll down to the Farm Kiylov Askania block.

3. Pay attention to the header.

**Actual result:**
The design of header of the Farm Kiylov Askania block is missed.

**Expected result:**
The design of header of the Farm Kiylov Askania must be according Figma (ZOO block) 

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-2459&t=VJyanGxRi3eGzAbN-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/a98a3f2e-13c8-44bb-ac8c-1f5bfec75942)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/4d1dd0ba-0506-468c-802c-778beb95fbe0)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
