### ISSUE TITLE
20170417_kiylov/The flag of Ukraine is missed in the Farm Kiylov Askania block

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3795]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170417_kiylov/

2. Scroll down to the Farm Kiylov Askania block.

3. Pay attention to the absence of a flag of Ukraine in the right side of the block.

**Actual result:**
The flag of Ukraine is missed in the Farm Kiylov Askania block.

**Expected result:**
The flag of Ukraine must be in the right side of the block.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/2f2fbad4-b694-4f92-8bb9-99bbe0410e61)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/3db1e11c-da86-41fc-ad87-6976d863e41c)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
