### ISSUE TITLE
20170417_kiylov/The size of the text 17.04.2017 is 22px

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3796]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170417_kiylov/

2. Scroll down to the Farm Kiylov Askania block.

3. Pay attention to the size of the text 17.04.2017.

**Actual result:**
The size of the text 17.04.2017 is 22px

**Expected result:**
The size of the text 17.04.2017 must be 18px

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-2459&t=VJyanGxRi3eGzAbN-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/ddc50497-9861-4a90-82c1-4e8ec308d8d7)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/748c35c0-da79-41a8-8382-6e56feb68d1b)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
