### ISSUE TITLE
20170417_kiylov/The size of the text  Кийлівська Асканія is 18px

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3797]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170417_kiylov/

2. Scroll down to the Farm Kiylov Askania block.

3. Pay attention to the size of the text Кийлівська Асканія.

**Actual result:**
The size of the text  Кийлівська Асканія is 18px

**Expected result:**
The size of the text  Кийлівська Асканія must be 24px

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-2459&t=VJyanGxRi3eGzAbN-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/aaac8872-2467-4038-886a-9cc35623c4fb)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/d2a59467-8865-42a9-b9cb-4d64bc2e6744)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
