### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - The size of the text "Shatski Ozera, Volyn region" is 18px

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#3798]
**Steps to playback:**

1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Scroll down to the "Shatski Ozera, Volyn region" block.
3. Pay attention to the size of the text "Shatski Ozera, Volyn region"

**Actual result:**
The size of the text "Shatski Ozera, Volyn region" is 18px

**Expected result:**
The size of the text "Shatski Ozera, Volyn region" must be 24px
![флагма дорога](https://github.com/scholokov/long-travel-2/assets/132911639/3306d584-b1af-41a3-a01d-493fe0094553)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![Розмір Баг](https://github.com/scholokov/long-travel-2/assets/132911639/b454db12-c0aa-4825-a314-2a29d208505a)

**Comment by scholokov** [comment]
порівнююється не з тим шаблоном. треба відкривати сторінку Travel page у фігма

**Comment by Artem-16** [comment]
#3086

**Comment by scholokov** [comment]
please retest
