### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - The line height of the text "14.08.2016" is 27px

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#3800]
**Steps to playback:**

1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Scroll down to the "Road: Kyiv - Svityaz" block.
3. Pay attention to the line height of the text "14.08.2016"

**Actual result:**
The line height of the text "14.08.2016" is 27px

**Expected result:**
The line height of the text "14.08.2016" must be 21.33px
![Дорога висота вимоги](https://github.com/scholokov/long-travel-2/assets/132911639/9642da34-7432-4f0f-bb56-4ede46ee8655)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![Дорога висота баг](https://github.com/scholokov/long-travel-2/assets/132911639/23597de0-3655-4368-acd2-c10794aefbb6)

**Comment by DmytroMarkulych** [comment]
виглядає як дефект дизайну

**Comment by Artem-16** [comment]
Так це дефект дизайну. 
То мені треба змінити Labels - Bug на Desing?

**Comment by scholokov** [comment]
на висоту рядку немає сенсу дивитися
якщо цікаве саме відстань між двома рядками, це можна заміряти. або до яких небуть інших об'єктів.
з точки зору характеристик саме шрифту є сенс звертати увагу на:
Font, Weight, Size, Color

**Comment by Artem-16** [comment]
Зрозуміло. То цей баг я перевожу в "Canceled"?

**Comment by Artem-16** [comment]
#3086
