### ISSUE TITLE
20141102_10_egypt_hurghada/ The next and previous photos don't display in the LightBox of the section "El Gouna"

### ISSUE THREAD

**Issue by Aleksandrkobets99** [scholokov/long-travel-2#3801]
**Steps to reproduce:**
1. Open page: https://test.long-travel.live/20141102_10_egypt_hurghada/
2. Find section "El Gouna" in the body of page
3. Press on the photo
4. Click on the left 
5. Click on the right

**Actual result:** The next and previous photos don't display. The date don't change
**Expected result:** The photos is display. The date is change

**Requirements:**https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

**Environment:**
Windows 10 Home
Google Chrome v 113.0.5672.127

**Attachment:**
![s0](https://github.com/scholokov/long-travel-2/assets/126480322/835c719d-dc2a-4595-8215-73b8eeb5c421)
![s1](https://github.com/scholokov/long-travel-2/assets/126480322/ba820f6c-f973-4520-a31f-deb46c99e5b3)
![s2](https://github.com/scholokov/long-travel-2/assets/126480322/6f7a1d95-6f53-41e9-9ae3-c983a2023057)
![s3](https://github.com/scholokov/long-travel-2/assets/126480322/f0f339de-2ebd-4e07-aef9-7a39a6dcdd0f)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
