### ISSUE TITLE
20141102_10_egypt_hurghada/ The next and previous photos don't display in the LightBox of the section "Synbad Navy Museum, Synbad Submarine"

### ISSUE THREAD

**Issue by Aleksandrkobets99** [scholokov/long-travel-2#3802]
**Steps to reproduce:**
1. Open page: https://test.long-travel.live/20141102_10_egypt_hurghada/
2. Find section "Synbad Navy Museum, Synbad Submarine" in the body of page
3. Press on the photo
4. Click on the left 
5. Click on the right

**Actual result:** The next and previous photos don't display. The date don't change
**Expected result:** The photos is display. The date is change

**Requirements:**https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

**Environment:**
Windows 10 Home
Google Chrome v 113.0.5672.127

**Attachment:**
![s4](https://github.com/scholokov/long-travel-2/assets/126480322/e037c607-fed5-4bf3-b057-da830f50f912)
![s5](https://github.com/scholokov/long-travel-2/assets/126480322/ab3ddc37-81aa-48f4-960e-3aa9b05f169e)
![s6](https://github.com/scholokov/long-travel-2/assets/126480322/7388aa05-8d89-4046-a58c-e7a25f2680a4)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
