### ISSUE TITLE
20170805_20_odessa/The photos don't display in the section "Одеса"

### ISSUE THREAD

**Issue by Aleksandrkobets99** [scholokov/long-travel-2#3809]
**Steps to reproduce:**
1. Open page: https://test.long-travel.live/20170805_20_odessa/
2. Find section "Одеса" in the body of travel
3. Press on the photo
4. Click on the right 
5. Click on the left

**Actual result:** The photos don't display in the section "Одеса". The number don't change 
**Expected result:** The photos display in the section "Одеса". The number is change 

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

**Environment:**
Windows 10 Home
Google Chrome v 113.0.5672.127

**Attachment:**
![odesa1](https://github.com/scholokov/long-travel-2/assets/126480322/4e0ae704-04f7-445d-aa5b-aac725f0ec2f)
![odesa2](https://github.com/scholokov/long-travel-2/assets/126480322/1cd1872f-1360-4e97-a316-897734cfcdde)
![odesa3](https://github.com/scholokov/long-travel-2/assets/126480322/c2de7d16-d0c3-4ce4-a11f-788798c17a0b)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
