### ISSUE TITLE
20170805_20_odessa/The photos don't display in the section "Дорога"

### ISSUE THREAD

**Issue by Aleksandrkobets99** [scholokov/long-travel-2#3810]
**Steps to reproduce:**
1. Open page: https://test.long-travel.live/20170805_20_odessa/
2. Find section "Дорога" in the body of travel
3. Press on the photo
4. Click on the right 
5. Click on the left

**Actual result:** The photos don't display in the section "Дорога". The number don't change 
**Expected result:** The photos display in the section "Дорога". The number is change 

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

**Environment:**
Windows 10 Home
Google Chrome v 113.0.5672.127

**Attachment:**
![r1](https://github.com/scholokov/long-travel-2/assets/126480322/5f1d1613-c050-4a8b-a1ce-753f9c469643)
![r2](https://github.com/scholokov/long-travel-2/assets/126480322/d4f70eb8-0212-475f-b397-aaab9f07b20b)
![r3](https://github.com/scholokov/long-travel-2/assets/126480322/6f97bc49-1fa7-4b7b-8ab9-427098c7d444)

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
