### ISSUE TITLE
20170417_kiylov/The name of the first video gallery Страусина ферма is in russian

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3815]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170417_kiylov/

2. Scroll down to the first video gallery of the Farm Kiylov Askania block.

3. Pay attention to the name of the first video gallery.

**Actual result:**
The name of the first video gallery Страусина ферма is in russian

**Expected result:**
The name of the first video gallery Страусина ферма is in Ukrainian

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:**https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/b04d0aba-a751-4396-adfb-2e1717492c7a)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/8bec0059-ad24-47c1-bc80-38b7233fac77)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
