### ISSUE TITLE
20170417_kiylov/The name of the third video gallery Страусина ферма is in russian

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3817]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170417_kiylov/

2. Scroll down to the third video gallery of the Farm Kiylov Askania block.

Pay attention to the name of the third video gallery.

**Actual result:**
The name of the third video gallery Страусина ферма is in russian

**Expected result:**
The name of the third video gallery Страусина ферма is in Ukrainian

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:**https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/565ac153-9a39-4519-924b-1e31529e6067)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/0ce12985-522c-426c-b430-bcf5579710c6)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
