### ISSUE TITLE
20170417_kiylov/The name of the fifth video gallery Страусина ферма is in russian

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3819]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170417_kiylov/

2. Scroll down to the fifth video gallery of the Farm Kiylov Askania block.

3. Pay attention to the name of the fifth video gallery.

**Actual result:**
The name of the fifth video gallery Страусина ферма is in russian

**Expected result:**
The name of the fifth video gallery Страусина ферма is in Ukrainian

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:**https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/f5d9a832-9704-4b72-90c4-a5653948653b)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/92b0f275-1ff1-4bd2-97e2-30f9077f16bc)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
