### ISSUE TITLE
20170417_kiylov/The name of the eighth video gallery Страусина ферма is in russian

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3822]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170417_kiylov/

2. Scroll down to the eighth video gallery of the Farm Kiylov Askania block.

3. Pay attention to the name of the eighth video gallery.

**Actual result:**
The name of the eighth video gallery Страусина ферма is in russian

**Expected result:**
The name of the eighth video gallery Страусина ферма is in Ukrainian

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:**https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/d346a1b8-eb36-4ffa-8bd5-ac36131d0709)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/3a4000ff-b126-4a1a-93f6-104fcb6b1b8f)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
