### ISSUE TITLE
20170417_kiylov/The name of the twentieth video gallery Страусина ферма is in russian

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3834]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170417_kiylov/

2. Scroll down to the twentieth video gallery of the Farm Kiylov Askania block.

3. Pay attention to the name of the twentieth video gallery.

**Actual result:**
The name of the twentieth video gallery Страусина ферма is in russian

**Expected result:**
The name of the twentieth video gallery Страусина ферма is in Ukrainian

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:**https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/686b8b8c-af5f-40d9-b8eb-0de8fa28d087)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/d03eaf13-691f-42b7-9d8b-f67af6eb6d56)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
