### ISSUE TITLE
0190720_0811_balcans - Body - "Hotel: Apartments Palma" - Body - Video and/or photo gallery missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3842]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Hotel: Apartments Palma" block
3. Pay attention to content in the body

**Actual Result**
Video and/or photo gallery missing

**Expected Result**
Video and/or photo gallery present

**Enviroments**
Windows 10, Chrome 114.0.5735.134 (64 bit)
![20190720_0811_Romania_Serbia_Makedonia_Albania_Montenegro_Bosnia and Herzegovina_Croatia_Hungary_Ukraine – Long-Travel - Google Chrome 20 06 2023 18_10_12](https://github.com/scholokov/long-travel-2/assets/95171672/b6af5326-20f9-4757-89e1-7df3ac75c3dd)

**Comment by DmitriiNasonov** [comment]
#233

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
