### ISSUE TITLE
20190720_0811_balcans - Body - "Road: Albania – Montenegro" block - Photo in the body belong to another structure block 

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3843]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Road: Albania – Montenegro" block
3. Pay attention to photo in the body

**Actual Result**
Photo in the body belong to another structure block

**Expected Result**
Photo in the body belong to this structure block

**Enviroments**
Android 8.1.0, Chrome 114.0.5735.131
![photo_2023-06-20_18-26-05](https://github.com/scholokov/long-travel-2/assets/95171672/cd32430e-ced8-4323-8209-72f83693a42a)

**Comment by DmitriiNasonov** [comment]
#233

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced

**Comment by scholokov** [comment]
please retest

**Comment by DmitriiNasonov** [comment]
retested. bug isn't reproduced
