### ISSUE TITLE
20190720_0811_balcans - Body - "Road: Bosnia and Herzegovina – Croatia" block - Photos in the body belong to another structure block

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3846]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Road: Bosnia and Herzegovina – Croatia" block
3. Pay attention to photos in the body

**Actual Result**
Photos in the body belong to another structure block

**Expected Result**
Photos in the body belong to this structure block

**Enviroments**
Android 8.1.0, Chrome 114.0.5735.131
![photo_2023-06-20_18-51-53](https://github.com/scholokov/long-travel-2/assets/95171672/01592692-6b90-456f-ac3c-c2522d34890f)

**Comment by DmitriiNasonov** [comment]
#233

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
