### ISSUE TITLE
20190720_0811_balcans - Body - "Road: Croatia – Hungary" block - Photos in the body belong to another structure block

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3847]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Road: Croatia – Hungary" block
3. Pay attention to photos in the body

**Actual Result**
Photos in the body belong to another structure block

**Expected Result**
Photos in the body belong to this structure block

**Enviroments**
Android 8.1.0, Chrome 114.0.5735.131
![photo_2023-06-20_19-02-29](https://github.com/scholokov/long-travel-2/assets/95171672/60b26f61-fc56-4e91-ac1d-c70f3e51da9b)

**Comment by DmitriiNasonov** [comment]
#233

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
