### ISSUE TITLE
20190720_0811_balcans - Body - "Готель Амбер" - Body - Video and/or photo gallery missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3848]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Готель Амбер" block
3. Pay attention to content in the body

**Actual Result**
Video and/or photo gallery missing

**Expected Result**
Video and/or photo gallery present

**Enviroments**
Android 8.1.0, Chrome 114.0.5735.131
![photo_2023-06-20_19-18-31](https://github.com/scholokov/long-travel-2/assets/95171672/2b94d050-1e3b-45c6-9c0d-808bdb7d5d9e)

**Comment by DmitriiNasonov** [comment]
#233

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
