### ISSUE TITLE
20190720_0811_balcans - Body - "Hotel: Alexandar Central Apartments" block - Body - Video and/or photo gallery missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3849]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Hotel: Alexandar Central Apartments" block
3. Pay attention to content in the body

**Actual Result**
Video and/or photo gallery missing

**Expected Result**
Video and/or photo gallery present

**Enviroments**
Android 8.1.0, Chrome 114.0.5735.131
![photo_2023-06-20_19-55-06](https://github.com/scholokov/long-travel-2/assets/95171672/3b5aea8a-1276-489f-b564-836b176c8277)

**Comment by DmitriiNasonov** [comment]
#233

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduced
![photo_2023-06-28_13-34-32](https://github.com/scholokov/long-travel-2/assets/95171672/4bd9b834-3567-4350-a983-78f113b4df36)

**Comment by scholokov** [comment]
please retest

**Comment by DmitriiNasonov** [comment]
retested. bug isn't reproduced
