### ISSUE TITLE
20190720_0811_balcans - Body - "Road: Makedonia – Albania" block - Photos in the body belong to another structure block 

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3850]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Road: Makedonia – Albania" block
3. Pay attention to photos in the body

**Actual Result**
Photos in the body belong to another structure block

**Expected Result**
Photos in the body belong to this structure block

**Enviroments**
Windows 10, Chrome 114.0.5735.131 (64 bit)
![Балкани – Long-Travel - Google Chrome 20 06 2023 20_08_56](https://github.com/scholokov/long-travel-2/assets/95171672/32740ede-8901-4e11-8a79-b5b2831a912d)

**Comment by DmitriiNasonov** [comment]
#233

**Comment by DmitriiNasonov** [comment]
#3791

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
