### ISSUE TITLE
/20191012_14_dnipro/ The trip name not meet with requirements.

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3856]
Steps to reproduce:
1. Open https://test.long-travel.live/20191012_14_dnipro/
2. Check the trip name

Actual result:
Днепр

Expected result:
Дніпро

Attachment:
https://github.com/scholokov/long-travel-2/wiki/3.1-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%9F%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 112.0.5615.138

![Screenshot_4](https://github.com/scholokov/long-travel-2/assets/125903734/2510c393-bc40-4056-90a3-0bbeecf8eb13)

**Comment by scholokov** [comment]
fixed

**Comment by ViktoriaZamkova** [comment]
checked
