### ISSUE TITLE
/20191012_14_dnipro/ Preview not meet with requirements in Дніпро travel 

### ISSUE THREAD

**Issue by ViktoriaZamkova** [scholokov/long-travel-2#3857]
Steps to reproduce:
1.Open trip https://test.long-travel.live/20191012_14_dnipro/
2. Check date of travel

Actual result:
Date of travel under Preview

Expected result:
Date of travel in preview and under travel name

Attachment:
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-6&t=MYUdH7V6K8rsq30T-0

Environment:
Windows 10 Pro , 21H2
Brouser: Google Chrome Version 112.0.5615.138

![image](https://github.com/scholokov/long-travel-2/assets/125903734/d28f5aa3-87ac-4360-b2da-89d6469a7b20)
![image](https://github.com/scholokov/long-travel-2/assets/125903734/7cf2f1fd-3e43-454e-9b19-289fc3591cbb)

**Comment by scholokov** [comment]
fixed

**Comment by ViktoriaZamkova** [comment]
checked
