### ISSUE TITLE
wiki/The page "4. Подорож" in the part "Дата публікації" the word "Фомат"  is from a spelling error

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3859]
**Steps to reproduce:**
1. Open page https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6
2. Open item "Дата публікації"
3. Pay attention to the number of item 1.4.1 in the part "Дата публікації" 

**Actual Result:** the word **"Фомат"  is from** a spelling error
**Expected Result:** the word **"Формат"  is  without** a spelling error

**Environment:**
Windows 10 Pro,
Opera v 96.0.4693.80

**Attachment**:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/14cc2127-b8ca-45f9-bd8a-945afcae1781)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
