### ISSUE TITLE
wiki/The page "4. Подорож" in the part "1.3 Стандартний блок(и)" the point 1.3.5 "Текстовий опис" is missing

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3860]
Steps to reproduce:
1. Open page https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6
2. Scroll down to the part "1.3 Стандартний блок(и)"
3. Pay attention to the point 1.3.5 "Текстовий опис"

Actual Result: the point 1.3.5 "Текстовий опис" is **missing**
Expected Result: the point 1.3.5 "Текстовий опис" is **present**

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/c12e80d1-6309-48a1-8195-55d9632c20fe)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
