### ISSUE TITLE
20170417_kiylov/The flag of Ukraine is missed in the Kiylov Picnic block

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3861]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170417_kiylov/

2. Scroll down to the Kiylov Picnic block.

3. Pay attention to the absence of a flag of Ukraine in the right side of the block.

**Actual result:**
The flag of Ukraine is missed in the Kiylov Picnic block.

**Expected result:**
The flag of Ukraine must be in the right side of the block.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/de518c0f-12e4-4275-9519-41775ae2cf48)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/60fa5e2c-8cad-449c-9a03-adf3e9c95c27)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
