### ISSUE TITLE
20170417_kiylov/The design of header of the Kiylov Picnic block is missed

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3862]
**Steps to retroduce:**
1. Open https://test.long-travel.live/20170417_kiylov/

2. Scroll down to the Kiylov Picnic block.

3. Pay attention to the header.

**Actual result:**
The design of header of the Kiylov Picnic block is missed.

**Expected result:**
The design of header of the Kiylov Picnic must be according Figma (ZOO block)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-2459&t=VJyanGxRi3eGzAbN-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/1cde0567-ca98-4c82-9fab-3e30d25c6bdc)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/2755820d-60a1-48fa-b451-fa96e0748f45)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
