### ISSUE TITLE
Requirements/Trere are no requirements for a picnic block

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3863]
**Steps to retroduce:**
1. Open: https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6#13-%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D0%B8%D0%B9-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8
2. Pay attention to the list of the standard blocks.

**Actual result:**
Trere are no requirements for a picnic block
**Expected result:**
Requirements for a picnic block should be

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/5dfbbda8-f76e-43ef-89bf-bc4944d75d5e)

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/c235dd0a-60e4-4256-9cc9-fb6f442b7c18)

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/c4a4e616-cb9b-4db2-8f01-7418a0572c33)

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/4986fe86-f7f0-4169-abd2-db264e352f0b)

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/24c436c5-b571-4527-8420-a6e840978624)

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/d4c66cac-42af-45d9-9f22-b57af3f5730d)

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/e626a0b7-6764-4627-b54f-1d7fb16b253a)

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/7d15c7c1-6e16-40e8-a2b9-5951a85d0d35)

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/a7ac40e9-2ca4-4d7e-9779-f919259ee293)

**Comment by DmytroMarkulych** [comment]
додайте, будь ласка, скріншот

**Comment by prokopenkoga1977** [comment]
додав

**Comment by prokopenkoga1977** [comment]
Passed
