### ISSUE TITLE
20170417_kiylov/The size of the text Кийлів - Пікнік is 18px

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3864]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170417_kiylov/

2. Scroll down to the Kiylov Picnic block.

3. Pay attention to the size of the text Кийлів - Пікнік.

**Actual result:**
The size of the text Кийлів - Пікнік is 18px

**Expected result:**
The size of the text Кийлів - Пікнік must be 24px

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-2459&t=VJyanGxRi3eGzAbN-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/1a05a1b2-50aa-4869-bc7b-b0ea3bd4bfd8)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/1333a525-4e22-4f51-90d1-e1e746c7698b)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
