### ISSUE TITLE
20170417_kiylov/The title text "Пикник" of the Kiylov-Picnic block is in russion

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3865]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170417_kiylov/

2. Scroll down to theKiylov-Picnic block.

3. Pay attention to the title text "Пикник".

**Actual result:**
The title text "Пикник" of the Kiylov-Picnic block is in russion

**Expected result:**
The title text "Пикник" of the Kiylov-Picnic block is in Ukrainian

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/2a7acf17-aa35-4081-a5eb-8ff470ecbb16)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/long-travel-2/assets/88647733/99c9f007-5ee8-4a22-9a4f-83aaa22828a0)

**Comment by prokopenkoga1977** [comment]
Виправив

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
