### ISSUE TITLE
20170417_kiylov/Photo gallery of the Kiylov Picnic block/The photos are not displayed when clicking next arrow

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3869]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170417_kiylov/

2. Scroll down to the Kiylov Picnic block.

3. Pay attention to the photo gallery.

**Actual result:**
The photos are not displayed when clicking next arrow

**Expected result:**
The photos should be displayed when clicking next arrow

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/baa0a911-061c-4be8-b5ad-9aed8c1e55c8)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
