### ISSUE TITLE
20170722_boguslav/The name of the video Kyiv - Chaiyki is in russian

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3871]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170722_boguslav/

2. Scroll down to the video Kyiv - Chaiyki.

3. Pay attention to the name of the video.

**Actual result:**
The name of the video Kyiv - Chaiyki is in russian

**Expected result:**
The name of the video Kyiv - Chaiyki is in Ukrainian
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6#133-%D0%B3%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%8F-%D0%B7-%D1%84%D0%BE%D1%82%D0%BE-%D1%82%D0%B0-%D0%B2%D1%96%D0%B4%D0%B5%D0%BE

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/0e40caa2-b3d8-4340-9c69-75b8ccaf2b79)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/17f901ec-2b42-4c13-8239-3478ea94ac81)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
