### ISSUE TITLE
20170722_boguslav/The date format of the video Chaiyki - Kyiv is 22.07.2017 (DD.MM.YYYY)

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3872]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170722_boguslav/

2. Scroll down to the video Chaiyki - Kyiv.

3. Pay attention to the date format of the video.

**Actual result:**
The date format of the video Chaiyki - Kyiv is 22.07.2017 (DD.MM.YYYY)

**Expected result:**
The date format of the video Chaiyki - Kyiv must be 2017.07.22 (YYYY.MM.DD)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6#133-%D0%B3%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%8F-%D0%B7-%D1%84%D0%BE%D1%82%D0%BE-%D1%82%D0%B0-%D0%B2%D1%96%D0%B4%D0%B5%D0%BE

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/eeb5194d-9c8d-4fa7-b833-ebe505cfb45a)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/cbc45692-5805-4e5d-a23f-bcb0760ac695)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
