### ISSUE TITLE
20170722_boguslav/The name of the video Chaiyki - Kyiv is in russian

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3873]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170722_boguslav/

2. Scroll down to the video Chaiyki - Kyiv.

3. Pay attention to the name of the video.

**Actual result:**
The name of the video Chaiyki - Kyiv is in russian

**Expected result:**
The name of the video Chaiyki - Kyiv is in Ukrainian
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6#133-%D0%B3%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%8F-%D0%B7-%D1%84%D0%BE%D1%82%D0%BE-%D1%82%D0%B0-%D0%B2%D1%96%D0%B4%D0%B5%D0%BE

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/8830e6a7-4a44-4873-ad57-0a1e08c1a78b)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/eb9dbcb0-bf67-46bf-87f0-539b2c030797)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
