### ISSUE TITLE
20170722_boguslav/The weight of the text Київ - Богуслав of the Road Kyiv - Boguslav block is 500

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3875]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170722_boguslav/

2. Scroll down to the Road Kyiv - Boguslav block.

3. Pay attention to the weight of the text Київ - Богуслав

**Actual result:**
The weight of the text Київ - Богуслав of the Road Kyiv - Boguslav block is 500

**Expected result:**
The weight of the text Київ - Богуслав of the Road Kyiv - Boguslav block is 700

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements**: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-2459&mode=design&t=fawvURV5RoS1q2bj-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/71947aab-6e12-497a-b6e2-86be316335db)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/eaede887-b4ff-486b-8c95-32f63ff69e5c)

**Comment by scholokov** [comment]
should be retested after
https://github.com/scholokov/long-travel-2/issues/3883

**Comment by prokopenkoga1977** [comment]
Passed
