### ISSUE TITLE
20170722_boguslav/The size of the text Київ - Богуслав of the Road Kyiv - Boguslav block is 18px

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3876]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170722_boguslav/

2. Scroll down to the Road Kyiv - Boguslav block.

3. Pay attention to the size of the text Київ - Богуслав

**Actual result:**
The size of the text Київ - Богуслав of the Road Kyiv - Boguslav block is 18px

**Expected result:**
The size of the text Київ - Богуслав of the Road Kyiv - Boguslav block is 24px

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-2459&mode=design&t=fawvURV5RoS1q2bj-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/6aa051bf-c584-4abd-a50c-b665aed11a02)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/9a5f16d6-edeb-488c-b2e0-82852ab7fe9b)

**Comment by scholokov** [comment]
should be retested after
https://github.com/scholokov/long-travel-2/issues/3883
