### ISSUE TITLE
20170722_boguslav/The size of the text Богуслав - Київ of the Road Boguslav - Kyiv block is 18px

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3878]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170722_boguslav/

2. Scroll down to the Road Boguslav - Kyiv block.

3. Pay attention to the size of the text Богуслав - Київ 

**Actual result:**
The size of the text Богуслав - Київ of the Road Boguslav - Kyiv block is 18px

**Expected result:**
The size of the text Богуслав - Київ of the Road Boguslav - Kyiv block is 24px

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-2459&mode=design&t=fawvURV5RoS1q2bj-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/88333f80-56d2-44ba-856d-29758d711222)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/af0115de-be2a-425f-b8ad-a5b54bdee87c)

**Comment by scholokov** [comment]
should be retested after:

**Comment by scholokov** [comment]
https://github.com/scholokov/long-travel-2/issues/3883

**Comment by prokopenkoga1977** [comment]
Passed
