### ISSUE TITLE
Figma - Travel page - Preview - Displaying of flags isn't adapted to the phone screen

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3881]
**Steps of reproducing**
1. Open https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-27&mode=design&t=KdbD3h8X5PTQILhu-0
2. Pay attention to the example of displaying flags

**Actual Result**
Display of flags isn't adapted to the phone screen

**Expected Result**
Display of flags adapted to the phone screen

**Enviroments**
Windows 10, Chrome 114.0.5735.199 (64 bit)
![Long-Travel – Figma - Google Chrome 28 06 2023 11_21_24](https://github.com/scholokov/long-travel-2/assets/95171672/ace3abd4-5763-49c4-bb27-860df4af8127)

**Comment by scholokov** [comment]
please retest

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduced
![Long-Travel – Figma - Google Chrome 23 08 2023 12_56_37](https://github.com/scholokov/long-travel-2/assets/95171672/099a7073-3313-4dfb-901f-e649cd2ae275)
![Long-Travel – Figma - Google Chrome 23 08 2023 12_57_53](https://github.com/scholokov/long-travel-2/assets/95171672/d3e9f4fa-b5e9-4dc2-a93f-17787a24a212)

**Comment by scholokov** [comment]
на цьому блоці зображується як саме мають відображатися прапорці, при різній їх кількості. але там окремо є зображення і розміри прапорців на всіх системах

**Comment by DmitriiNasonov** [comment]
canceled
