### ISSUE TITLE
20190720_0811_balcans - Body - "Hotel: Apartments Dan Mija" block - Body - Video and/or photo gallery missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3882]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll to "Hotel: Apartments Dan Mija" block
3. Pay attention to content in the body

**Actual Result**
Video and/or photo gallery missing

**Expected Result**
Video and/or photo gallery present

**Enviroments**
Android 8.1.0, Chrome 114.0.5735.131
![photo_2023-06-28_12-38-28](https://github.com/scholokov/long-travel-2/assets/95171672/5db9ede5-fc41-4358-b50c-55fbb91a1b14)

**Comment by DmitriiNasonov** [comment]
#233

**Comment by DmitriiNasonov** [comment]
#3785

**Comment by scholokov** [comment]
please retest

**Comment by DmitriiNasonov** [comment]
retested. bug isn't reproduce
