### ISSUE TITLE
20160830_Myrgorod / Extra text "Украина 30.08.2016" after Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3884]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20160830_Myrgorod/
2. Pay attention to the text "Украина 30.08.2016" after Preview block.

**Actual Result:** 
There is "Украина 30.08.2016" after Preview block.

**Expected Result:** 
There is no "Украина 30.08.2016" after Preview block.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/2c8843b6-a0f6-4926-aff0-2a607316d426)
![image](https://github.com/scholokov/long-travel-2/assets/101987790/4cba9cd6-8fa6-427b-a608-5e45fee3c897)

**Comment by GNatala** [comment]
#1352

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
