### ISSUE TITLE
20160830_Myrgorod / Names of the cities in the legend of the map are in English

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3888]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20160830_Myrgorod
2. Pay attention to the names of the cities in the legend of the map.

**Actual result:**
Names of the cities "Kyiv" and "Myrhorod" in the legend of the map are in English.

**Expected result:**
Names of the cities "Київ" and "Миргород" in the legend of the map are in Ukranian.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/ddc0aadc-ab13-4b27-a1e7-7da18dfa8f49)

**Comment by GNatala** [comment]
#1352

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
