### ISSUE TITLE
20160830_Myrgorod / Preview photo is absent in the Legend of the map

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3891]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20160830_Myrgorod/
2. Scroll down to the Legend of the Map.
3. Pay attention to the absence of the Preview photo.

**Actual Result:** 
Preview photo is absent in the Legend of the map.

**Expected Result:** 
Preview photo is present in the Legend of the map.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/735d6386-16cd-42fe-ab64-1f3c6a3eae1b)

**Comment by GNatala** [comment]
#1352

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
