### ISSUE TITLE
20160830_Myrgorod/ Page content language is russian, not Ukrainian as required 

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3894]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20160830_Myrgorod
2. Scroll to the content on the page.
3. Pay attention to the language of the content.

**Actual result:**
Language of the content is russian.

**Expected result:**
Language of the content is Ukrainian.

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/1.2-%D0%9C%D0%BE%D0%B2%D0%B0

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment** 
![image](https://github.com/scholokov/long-travel-2/assets/101987790/ae092e25-660a-4123-8df8-4b068d481ef3)

**Comment by GNatala** [comment]
#1352

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
