### ISSUE TITLE
20160830_Myrgorod/ Publication date 30.08.2016 does not match the travel date

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3895]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20160830_Myrgorod
2. Scroll to the Publication date.

**Actual result:**
Publication date is 30.08.2016.

**Expected result:**
Publication date is 11.07.2021.

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6#14-%D0%B4%D0%B0%D1%82%D0%B0-%D0%BF%D1%83%D0%B1%D0%BB%D1%96%D0%BA%D0%B0%D1%86%D1%96%D1%97

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment** 
![image](https://github.com/scholokov/long-travel-2/assets/101987790/81687352-4775-4bd9-b063-0f44e1013180)

**Comment by GNatala** [comment]
#1352

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
