### ISSUE TITLE
20160830_Myrgorod/ The name of the video Kiev-Myrhorod is in English

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3896]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20160830_Myrgorod
2. Scroll to the 1-st video.
3. Pay attention to the language of the name of the video.

**Actual result:**
The name of the video Kiev-Myrhorod is in English.

**Expected result:**
The name of the video Київ-Миргород is in Ukrainian.

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6#134-youtube-%D0%B3%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment** 
![image](https://github.com/scholokov/long-travel-2/assets/101987790/bfe45df9-6c09-4fa8-869f-bb3b1df022e5)

**Comment by GNatala** [comment]
#1352

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
