### ISSUE TITLE
20170709_protsiv/In the Preview block of the Standart block the travel is not the Name of travel and Flag of country

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3897]
Steps to Reproduce:

1. Open page: https://test.long-travel.live/20170709_protsiv/
2. Pay attention to the Preview block of the Standart block

Actual Result: In the Preview block  is not Name of travel and Flag of country
Expected Result: In the Preview block  is not Name of travel and Flag of country

Requirements:https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6#13-%D1%81%D1%82%D0%B0%D0%BD%D0%B4%D0%B0%D1%80%D1%82%D0%BD%D0%B8%D0%B9-%D0%B1%D0%BB%D0%BE%D0%BA%D0%B8

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachments:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/077b5bc1-936d-4156-ae74-3f1f71163cc2)

**Comment by ODrobik** [comment]
#3235

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
