### ISSUE TITLE
20170709_protsiv/In the Preview block, the city and region are written in Russian

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3898]
**Steps to Reproduce:**

1. Open page: https://test.long-travel.live/20170709_protsiv/
2. Pay attention to the Preview of the Standart block

**Actual Result:** In the Preview block the city and region are written in Russian "Процев, Киевская область"
**Expected Result:** In the Preview block the city and region are written in Ukrainian "Проців, Київська область"

**Requirements:**https: https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6#2-%D0%B7%D0%B0%D0%B3%D0%B0%D0%BB%D1%8C%D0%BD%D1%96-%D0%B2%D0%B8%D0%BC%D0%BE%D0%B3%D0%B8

**Environment:**
Windows 10 Pro,
Opera v 96.0.4693.80

**Attachments:**
![image](https://github.com/scholokov/long-travel-2/assets/123776698/eb1891a5-4d7c-4523-8a9b-3fbc5d98a6b6)

**Comment by ODrobik** [comment]
#3235

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
