### ISSUE TITLE
wiki/The page "4. Подорож" - part "1.3 Стандартний блок(и)" - point 1.3.4.1.4 the word "Яккщо" is written with a spelling error

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3899]
Steps to reproduce:

1. Open page https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6
2. Scroll down to the part "1.3 Стандартний блок(и)"
3. Pay attention to the point 1.3.4.1.4

Actual Result: in the point 1.3.4.1.4 the word "Яккщо" is written **with** a spelling error
Expected Result: in the point 1.3.4.1.4 the word "Якщо" is written **without** a spelling error

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/6380baeb-c6c1-4862-823c-1e397b13f785)

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
