### ISSUE TITLE
20160830_Myrgorod/ The date format of the video Київ-Миргород is 30.08.2016 (DD.MM.YYYY) 

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3902]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20160830_Myrgorod
2. Scroll to the 1-st video Київ-Миргород.
3. Pay attention to the date format of the video.

**Actual result:**
The date format of the video Київ-Миргород is 30.08.2016 (DD.MM.YYYY) 

**Expected result:**
The date format of the video Київ-Миргород is 2016.08.30 (YYYY.MM.DD)

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6#134-youtube-%D0%B3%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment** 
![image](https://github.com/scholokov/long-travel-2/assets/101987790/75ca94d9-7166-439d-9a75-7556668ced17)

**Comment by GNatala** [comment]
#1352

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
