### ISSUE TITLE
20170709_protsiv/The name of the block "Дорога обратно" does not correspond to the name in the types of standard blocks

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3903]
Steps to reproduce:

1. Open page https://test.long-travel.live/20170709_protsiv/
2. Pay attention to the name of the block "Дорога обратно"

Actual Result: The name of the block "Дорога обратно" does not correspond 
Expected Result: The name of the block "Дорога обратно" corresponds

Requirements: https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6#2-%D0%B7%D0%B0%D0%B3%D0%B0%D0%BB%D1%8C%D0%BD%D1%96-%D0%B2%D0%B8%D0%BC%D0%BE%D0%B3%D0%B8

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/04266ad1-623f-4408-baac-5f844849522b)

**Comment by ODrobik** [comment]
#3235

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
