### ISSUE TITLE
GitHub Wiki - 4.Подорож - Мапа - Clause 1.2.2.8 - No clarification as to which point of interest or waypoint the preview should be located

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3904]
**Steps of reproducing**
1. Open https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6
2. Scroll to Clause 1.2.2.8

**Actual Result**
No clarification as to which point of interest or waypoint the preview should be located

**Expected Result**
Clarifications are provided as to which point of interest or waypoint the preview should be located

**Enviroments**
Windows 10, Chrome 114.0.5735.199 (64 bit)
![4  Подорож · scholokov_long-travel-2 Wiki - Google Chrome 02 07 2023 17_10_01](https://github.com/scholokov/long-travel-2/assets/95171672/9e2b48bd-7b0f-4024-a1dd-997e485a4710)

**Comment by scholokov** [comment]
виправлено
додано новий пункт
1.2.2.8.4

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
