### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - There is no "Standard block" - "Lake Svityaz"

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#3907]
**Steps to playback:**

1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Scroll - "Lake Svityaz"

**Actual result:**
- There is no "Standard block" - "Lake Svityaz"

**Expected result:**
- There is a "Standard block" - "Lake Svityaz"

![фігма озеро](https://github.com/scholokov/long-travel-2/assets/132911639/85354863-b88f-42d5-8ff5-78bce36a347a)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![Баг озеро](https://github.com/scholokov/long-travel-2/assets/132911639/790483c1-d40a-44ef-ac60-c9aa6a4bbe19)

**Comment by DmytroMarkulych** [comment]
Виглядає як 3 окремі баги

**Comment by Artem-16** [comment]
Чому як 3 окремі баги?
Ви самі мені писали, щоб я розписував що саме не вистачає в стандартному блоці.
Я описав)

**Comment by DmytroMarkulych** [comment]
так, але у нас вийшло 3 актуальних і очікуваних результати

![Image](https://github.com/scholokov/long-travel-2/assets/88647733/2a4df0a4-2625-4488-a411-d35bf75d9f85)

**Comment by scholokov** [comment]
виправлено

**Comment by Artem-16** [comment]
Відсутній прапор України в правому куті блоку
Відсутня дата подорожі

**Comment by Artem-16** [comment]
#3086

**Comment by DmytroMarkulych** [comment]
додайте будь ласка скріншот

**Comment by Artem-16** [comment]
Відсутній прапор України в правому куті блоку
Відсутня дата подорожі
![Озеро](https://github.com/scholokov/long-travel-2/assets/132911639/c1ac18ca-14a1-480f-8bab-bde882e1fc64)

**Comment by scholokov** [comment]
виправлено
