### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - There is no "Standard block" - "Svityaz recreation center"

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#3908]
**Steps to playback:**

1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Scroll - "Svityaz recreation center"

**Actual result:**
- There is no "Standard block" - "Svityaz recreation center"

**Expected result:**
- There is a "Standard block" - "Svityaz recreation center"

![фігма хотел](https://github.com/scholokov/long-travel-2/assets/132911639/0ddefdc5-a313-44c3-9457-3f9ea39df593)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![Bag  База відпочинку](https://github.com/scholokov/long-travel-2/assets/132911639/52ab48d7-dfa0-4e3e-a300-d92de4ba87fd)

**Comment by DmytroMarkulych** [comment]
Виглядає як 3 окремі баги

**Comment by Artem-16** [comment]
Чому як 3 окремі баги?
Ви самі мені писали, щоб я розписував що саме не вистачає в стандартному блоці.
Я описав)

**Comment by DmytroMarkulych** [comment]
Але у нас є 3 Актальних та очікуваних результати

**Comment by Artem-16** [comment]
Добре давайте так)

**Comment by scholokov** [comment]
виправлено

**Comment by Artem-16** [comment]
Відсутній прапор України в правому куті блоку
Відсутня дата подорожі

**Comment by Artem-16** [comment]
#3086

**Comment by DmytroMarkulych** [comment]
додайте будь ласка скріншот

**Comment by Artem-16** [comment]
Відсутній прапор України в правому куті блоку
Відсутня дата подорожі
![База відпочинку](https://github.com/scholokov/long-travel-2/assets/132911639/001b7adc-9782-4ad6-b32b-f82811dc163e)

**Comment by scholokov** [comment]
виправлено
