### ISSUE TITLE
20160830_Myrgorod/ Missed Ukrainian flag in the preview "Дорога Миргород-Київ"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3909]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20160830_Myrgorod
2. Scroll to the preview "Дорога Миргород-Київ".
3. Pay attention to the absence of the Ukrainian flag.

**Actual result:**
Ukrainian flag is missed in the preview "Дорога Миргород-Київ".

**Expected result:**
Ukrainian flag is present in the preview "Дорога Миргород-Київ".

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment** 
![image](https://github.com/scholokov/long-travel-2/assets/101987790/e87d432d-a73a-4b53-b2ca-c70fb48227f4)

![image](https://github.com/scholokov/long-travel-2/assets/101987790/cd9a7a96-321a-4cce-af6e-dba2283d1e28)

**Comment by GNatala** [comment]
#1352

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
