### ISSUE TITLE
20180428_0501_beregovo - Название промежуточной точки Замок Сент-Миклош не соответствует языку страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#391]
**Steps to reproduce:**

1. Открыть страницу https://test.long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на название промежуточной точки Замок Сент-Миклош

**Actual result:**
Название промежуточной точки не соответствует языку страны - Замок Сент-**Миклош**

**Expected result:**
Название промежуточной точки соответствует языку страны - Замок Сент-**Міклош**

![image](https://user-images.githubusercontent.com/86321831/145689918-f936a79d-a5cd-4c73-94e7-cca49c644620.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
