### ISSUE TITLE
20160830_Myrgorod/ An Extra element "Myrgorod" in the Map's legend

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3910]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20160830_Myrgorod/
2. Scroll down to the Map of travel.
3. Pay attention to the text after the preview foto in the map's legend.

**Actual result:**
An extra element "Myrgorod" is after the preview photo in the map's legend.

**Expected result:**
An extra element "Myrgorod" does not appear after the preview photo in the map's legend.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/9c353b02-455b-42f3-afa1-dbbeda9e799b)

**Comment by GNatala** [comment]
#1352

**Comment by scholokov** [comment]
випрвлено

**Comment by GNatala** [comment]
перевірено
