### ISSUE TITLE
Балкани - Map - A waypoint "Hotel: Orasac, Belgrad, Serbia" and a point of interest "Museum of Illusions, Belgrade, Serbia" are connected by a red dotted line

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3911]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll block "Маршрут подорожі" to the waypoint "Hotel: Orasac, Belgrad, Serbia"
3. Click on it

**Actual Result**
A waypoint "Hotel: Orasac, Belgrad, Serbia" and a point of interest "Museum of Illusions, Belgrade, Serbia" are connected by a RED dotted line

**Expected Result**
A waypoint "Hotel: Orasac, Belgrad, Serbia" and a point of interest "Museum of Illusions, Belgrade, Serbia" are connected by a BLUE dotted line

**Additional information**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

**Enviroments**
Windows 10, Chrome 114.0.5735.199 (64 bit)
Android 8.1.0, Chrome 114.0.5735.131
![Балкани – Long-Travel - Google Chrome 03 07 2023 18_55_31](https://github.com/scholokov/long-travel-2/assets/95171672/b304f520-406e-4b3f-8c5f-37565659eb8a)
![photo_2023-07-04_18-34-14](https://github.com/scholokov/long-travel-2/assets/95171672/10e490b6-38f0-4f9d-aa0c-8c86862533e4)

**Comment by DmitriiNasonov** [comment]
#233

**Comment by scholokov** [comment]
колір залежить від типу транспорту. зліва є легенда, яка пояснює це

**Comment by DmitriiNasonov** [comment]
canceled. created the new bug report: #3971

**Comment by DmitriiNasonov** [comment]
#3971

**Comment by DmitriiNasonov** [comment]
#233
