### ISSUE TITLE
20160830_Myrgorod/ Missed Road block "Дорога Київ-Миргород"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3912]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20160830_Myrgorod
2. Scroll to the 1-st video.
3. Pay attention to the absence of the Road block "Дорога Київ-Миргород" before the 1-st video.

**Actual result:**
Missed Road block "Дорога Київ-Миргород" with preview.

**Expected result:**
Missed Road block "Дорога Київ-Миргород" with preview is present before the 1-st video.

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment** 
![image](https://github.com/scholokov/long-travel-2/assets/101987790/cf49ecc8-5b75-4d0e-9834-39dcd3f894bd)

**Comment by GNatala** [comment]
#1352

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
