### ISSUE TITLE
20160830_Myrgorod/ The name of the travel in the Global Map is 20160830_Myrgorod (YYYYMMDD)

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3913]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20160830_Myrgorod/

2. Scroll down to the Global Map.

3. Pay attention to the name of the travel "20160830_Myrgorod".

**Actual result:**
The name of the travel in the Global Map is 20160830_Myrgorod (YYYYMMDD)

**Expected result:**
The name of the travel in the Global Map is 2016.08.30 Миргород (YYYY.MM.DD)

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/3.2-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%93%D0%BB%D0%BE%D0%B1%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0-%D0%BA%D0%B0%D1%80%D1%82%D0%B0-%D0%B7-%D0%BC%D0%B0%D1%80%D1%88%D1%80%D1%83%D1%82%D0%B0%D0%BC%D0%B8

**Attachment:**

![image](https://github.com/scholokov/long-travel-2/assets/101987790/8fd62635-fb29-4828-bd42-56c5ed256f4c)

**Comment by GNatala** [comment]
#1352

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
