### ISSUE TITLE
Балкани - The waypoint "Belgrade, Serbia" isn't marked on the map, but it is present as a structural block

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#3914]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190720_0811_balcans/
2. Scroll block "Маршрут подорожі" to the waypoint "Hotel: Orasac, Belgrad, Serbia"
3. Pay attention to the presence of the structural block "Belgrade, Serbia" above it
4. Scroll to structure block "Belgrade, Serbia"
5. Pay attention to its presence

**Actual Result**
The waypoint "Belgrade, Serbia" isn't marked on the map, but it is present as a structural block

**Expected Result**
The waypoint "Belgrade, Serbia" is marked on the map and is present as a structural block 
                                                                              OR
The waypoint "Belgrade, Serbia" isn't marked on the map and is missing as a structural block 

**Enviroments**
Windows 10, Chrome 114.0.5735.199 (64 bit)
Android 8.1.0, Chrome 114.0.5735.196
![Балкани – Long-Travel - Google Chrome 05 07 2023 15_52_20](https://github.com/scholokov/long-travel-2/assets/95171672/131dd4ed-3a8c-46b3-b9d7-dcd241a33ed3)
![Балкани – Long-Travel - Google Chrome 05 07 2023 17_14_15](https://github.com/scholokov/long-travel-2/assets/95171672/27bdcd58-a336-4ba1-b818-3f9c32003ccd)
![photo_2023-07-05_16-29-30](https://github.com/scholokov/long-travel-2/assets/95171672/9bc4ad4c-57de-48f9-bd18-88a60a2c9049)
![photo_2023-07-05_17-14-30](https://github.com/scholokov/long-travel-2/assets/95171672/75825a9f-3b12-4ac0-8406-63d983d2d9da)

**Comment by scholokov** [comment]
точка у Белграді є. не впевнений що має бути ще одна

**Comment by DmitriiNasonov** [comment]
canceled
