### ISSUE TITLE
20180428_0501_beregovo - Название населенного пункта промежуточной точки Замок Сент-Миклош не соответствует языку страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#392]
**Steps to reproduce:**

1. Открыть страницу https://test.long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на название населенного пункта промежуточной точки Замок Сент-Миклош

**Actual result:**
Название населенного пункта промежуточной точки не соответствует языку страны - **Чинадиево**

**Expected result:**
Название населенного пункта промежуточной точки соответствует языку страны - **Чинадійово**

![image](https://user-images.githubusercontent.com/86321831/145690057-c007cae6-81b9-426a-9e1c-1e9a3105357f.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
