### ISSUE TITLE
/20151031_haisyn_uman/ Немає зображення прев'ю 

### ISSUE THREAD

**Issue by SulymaIhor** [scholokov/long-travel-2#3921]
**Передумови:**
**Відкрити** https://test.long-travel.live/20151031_haisyn_uman/
**Кроки для відтворення:** 

1. Звернути увагу, що прев'ю немає зображення

**Фактичний результат:** немає зображення прев'ю 

**Очікуваний результат:** є зображення прев'ю 

**Середовище:** 
**Система:** Windows 10 Pro
**Браузер:** Google Chrome Версія 114.0.5735.199
![image](https://github.com/scholokov/long-travel-2/assets/122620802/45f03841-ff96-43b0-912a-40db683ad904)

**Comment by SulymaIhor** [comment]
#3080

**Comment by SulymaIhor** [comment]
#3925

**Comment by SulymaIhor** [comment]
#3927

**Comment by SulymaIhor** [comment]
#3928

**Comment by SulymaIhor** [comment]
#3929

**Comment by SulymaIhor** [comment]
#3930

**Comment by DmytroMarkulych** [comment]
В Актуальному і Очікуваному результатах не потрібно вказувати частину URL стоірнки

**Comment by SulymaIhor** [comment]
#3080

**Comment by scholokov** [comment]
виправлено

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
