### ISSUE TITLE
/20130908_tropical_park/ При кліканні на наступне фото не працює кнопка(>) для перегляду фото 

### ISSUE THREAD

**Issue by RDuma43** [scholokov/long-travel-2#3924]
Передумови:
Відкрити : https://test.long-travel.live/20130908_tropical_park/#gallery[photonic-google-album-1]/AE29bMH8xEtkdMMGlZNOgK1LtKVQPRBD77cR1ovyeCqQziztTzybE0vQPtvL_-8UAaRt_BR056oFBjtBG3BXdlb1l_i0IhGMhw/
Кроки для відтворення: 

1. Відкрийте перше фото
2. Клікнічь на кнопку для перегортання фото (>)
3. Зверніть увагу,що наступне фото не відкривається

Фактичний результат: При кліканні на наступне фото не працює кнопка(>) для перегляду фото 

Очікуваний результат: При кліканні на наступне фото  працює кнопка(>) для перегляду фото 
Середовище: Windows 10 Pro
система: 
Браузер: Google Chrome Версія 114.0.5735.199 (Офіційне складання) (64-розрядна версія)
![BAG 1](https://github.com/scholokov/long-travel-2/assets/138390187/71c2baeb-18cb-4654-a030-fa04809eb85f)

**Comment by RDuma43** [comment]
[#2986](https://github.com/scholokov/long-travel-2/issues/2986)

**Comment by DmytroMarkulych** [comment]
В Актуальному і Очікуваному результатах не потрібно вказувати частину URL сторінки

**Comment by RDuma43** [comment]
Виправила

**Comment by RDuma43** [comment]
Кнопка працює
