### ISSUE TITLE
/20151031_haisyn_uman/ розмір прапору в заголовку Mіnі Gotel Pozitiv 16х11px

### ISSUE THREAD

**Issue by SulymaIhor** [scholokov/long-travel-2#3925]
**Передумови:**
Відкрити https://test.long-travel.live/20151031_haisyn_uman/
**Кроки для відтворення:**
1. Звернути увагу на розмір знаку прапора в заголовках

**Фактичний результат:**  розмір прапору в заголовку Mіnі Gotel Pozitiv 16х11px

**Очікуваний результат:** розмір прапору в заголовках 26х18px

**Середовище:**
**Система:** Windows 10 Pro
**Браузер:** Google Chrome Версія 114.0.5735.199
![image](https://github.com/scholokov/long-travel-2/assets/122620802/c23b4311-888b-440e-ad40-59f7747e6109)
![image](https://github.com/scholokov/long-travel-2/assets/122620802/10148cf1-8f76-4687-85d9-c2a37c2671b7)
![image](https://github.com/scholokov/long-travel-2/assets/122620802/741d737d-f9f4-47e1-9b3f-2d6029466b9d)
![image](https://github.com/scholokov/long-travel-2/assets/122620802/cf07553d-b77f-49be-a958-0f35f8357a07)

**Comment by DmytroMarkulych** [comment]
В Актуальному і Очікуваному результатах не потрібно вказувати частину URL сторінки

**Comment by DmytroMarkulych** [comment]
вкажіть будь ласка конкретні розміри прапора, які є і які мають бути

**Comment by SulymaIhor** [comment]
#3080

**Comment by DmytroMarkulych** [comment]
px?

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
