### ISSUE TITLE
 20170605_kiev_mariinskiy

### ISSUE THREAD

**Issue by tatianasheremet** [scholokov/long-travel-2#3926]
!!! ANY FEATURE CAN BE CHECKED SEVERAL TIMES BY DIFFERENT TESTERS !!!

List of the ready features:

 Filling of the travel page
 Title
 Photo that describes the travel
 Map on the page of the travel
 Photos on the page of the travel
 Search function
 Map
https://www.test.long-travel.live/20170605_kiev_mariinskiy

**Comment by tatianasheremet** [comment]
This issue was created instead of #3231

**Comment by DmitriiNasonov** [comment]
Testing completed
