### ISSUE TITLE
/20151031_haisyn_uman/ фото не змінюється в галереї при спробі зміни за допомогою стрілок вправо/вліво, з'являється чорний екран

### ISSUE THREAD

**Issue by SulymaIhor** [scholokov/long-travel-2#3927]
**Передумови:**
Відкрити https://test.long-travel.live/20151031_haisyn_uman/
**Кроки для відтворення:**
1. Опуститися вниз сторінки до галереї фото Дендропарк “Софіївка”
2. ЛКМ по будь-якому фото з галереї
3. За допомогою стрілок вправо/вліво (не на клавіатурі) перейти на попереднє/наступне фото

**Фактичний результат:** фото не змінюється в галереї при спробі зміни за допомогою стрілок вправо/вліво, з'являється чорний екран

**Очікуваний результат:** з'являється відповідно попереднє/наступне фото

**Середовище:**
**Система:** Windows 10 Pro
**Браузер:** Google Chrome Версія 114.0.5735.199
**Відтворення багу:** не завжди, через певний час знаходження на сторінці, баг зникає
![image](https://github.com/scholokov/long-travel-2/assets/122620802/1a61f103-8a5f-4d09-a85e-5d4b7130274e)
![image](https://github.com/scholokov/long-travel-2/assets/122620802/15b69dbb-9a6b-4512-be19-8dc8f60f1273)

**Comment by DmytroMarkulych** [comment]
В Актуальному і Очікуваному результатах не потрібно вказувати частину URL сторінки

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/long-travel-2/assets/88647733/a02363fa-6dd2-42b7-8917-39afd28ae5cb)

**Comment by SulymaIhor** [comment]
чесно кажу, нічого не робив і в мене все заповнено, глянь, будь-ласка, ще раз

**Comment by SulymaIhor** [comment]
#3080

**Comment by DmytroMarkulych** [comment]
Summary краще сфорувати за принципом Де? Що? Коли? 
Приклад.: В подорожі "Умань" фото не перемикаються після клікання на стрілки

Каунтер номеру фото це вже інший дефект. Який швидше за все залежить від того що фото не премикаються. На нього варто звернути увагу після фіксу перемикання фото

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
