### ISSUE TITLE
20180428_0501_beregovo - Название города промежуточной точки ресторан Фламинго не соответствует языку страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#393]
**Steps to reproduce:**

1. Открыть страницу https://test.long-travel.live/20180428_0501_beregovo/
2. Обратить внимание на название города промежуточной точки ресторан Фламинго

**Actual result:**
Название города промежуточной точки не соответствует языку страны - **Ровно**

**Expected result:**
Название города промежуточной точки соответствует языку страны - **Рівне**

![image](https://user-images.githubusercontent.com/86321831/145690358-ffe2609a-44b8-452c-aea4-5202749ac37d.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
