### ISSUE TITLE
/20151031_haisyn_uman/ Гайсин - Умань не має дати подорожі

### ISSUE THREAD

**Issue by SulymaIhor** [scholokov/long-travel-2#3935]
**Передумови:**
Відкрити https://test.long-travel.live/20151031_haisyn_uman/
**Кроки для відтворення:**
1. відкрити список подорожей
2. звернути увагу на Гайсин - Умань

**Фактичний результат:** Гайсин - Умань не має дати подорожі

**Очікуваний результат:** рядок має дату подорожі перед назвою (20151031_haisyn_uman)

**Середовище:**
**Система:** Windows 10 Pro
**Браузер:** Google Chrome Версія 114.0.5735.199
![image](https://github.com/scholokov/long-travel-2/assets/122620802/ff4e8f85-bb9e-4b41-a4bf-a7a7a14e6351)
![image](https://github.com/scholokov/long-travel-2/assets/122620802/7af353f5-b324-4a15-b5e1-b4eb8d066cf3)

**Comment by DmytroMarkulych** [comment]
Додайте посилання на документацію. І якщо є можливість дізнатися конкретно яка має бути дата, то було б добре додати її

**Comment by SulymaIhor** [comment]
#3080

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
