### ISSUE TITLE
/20151031_haisyn_uman/ розмір та шрифт тексту Гайсинська ДЮСШ 18рх "Open Sans"

### ISSUE THREAD

**Issue by SulymaIhor** [scholokov/long-travel-2#3936]
**Передумови:**
Відкрити https://test.long-travel.live/20151031_haisyn_uman/
Відкрити DevTools
**Кроки для відтворення:**
1. Звернути увагу на шрифт тексту Гайсинська ДЮСШ

**Фактичний результат:** Шрифт 18рх "Open Sans"

**Очікуваний результат:** Шрифт 24px "Amazing Slab Trial"

**Середовище:**
**Система:** Windows 10 Pro
**Браузер:** Google Chrome Версія 114.0.5735.199
![image](https://github.com/scholokov/long-travel-2/assets/122620802/98001010-acac-4dfe-a533-193f65055e21)
![image](https://github.com/scholokov/long-travel-2/assets/122620802/030bfd90-e4a2-45e9-b0dc-94160e4b8923)

**Comment by DmytroMarkulych** [comment]
Додайте посилання на документацію в баг репорт. 
Зробіть скріншот таким чином щоб було видно всю сторінку

**Comment by SulymaIhor** [comment]
#3080

**Comment by scholokov** [comment]
please retest

**Comment by ODrobik** [comment]
is not relevant
