### ISSUE TITLE
/20151031_haisyn_uman/ перед негативним відгуком який позначено "-" два пусті рядки, перед "+" їх немає

### ISSUE THREAD

**Issue by SulymaIhor** [scholokov/long-travel-2#3937]
**Передумови:**
Відкрити https://test.long-travel.live/20151031_haisyn_uman/
**Кроки для відтворення:**
1. звернути увагу в описі готелю на відступи між рядками

**Фактичний результат:** перед негативним відгуком який позначено "-" два пусті рядки, перед "+" їх немає, порушена симетрія

**Очікуваний результат:** текст написаний з однаковим відступом між рядками

**Середовище:**
**Система:** Windows 10 Pro
**Браузер:** Google Chrome Версія 114.0.5735.199
![image](https://github.com/scholokov/long-travel-2/assets/122620802/c3bac5ff-a58c-4b15-b42e-2b0f9cfbf258)

**Comment by DmytroMarkulych** [comment]
Давайте напишемо Summary таким чином що воно відповідало на питання Де? Що? Коли? та перед summary вкажіть частину сторінки
Додайте скріншот та посилання на документацію

**Comment by SulymaIhor** [comment]
#3080

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
