### ISSUE TITLE
/20130908_tropical_park/ Не працює перша зліва кнопка в правому верхньому куті фото

### ISSUE THREAD

**Issue by RDuma43** [scholokov/long-travel-2#3939]
Передумови:
Відкрити : [https://test.long-travel.live/20130908_tropical_park/#gallery[photonic-google-album-1]/AE29bMH8xEtkdMMGlZNOgK1LtKVQPRBD77cR1ovyeCqQziztTzybE0vQPtvL_-8UAaRt_BR056oFBjtBG3BXdlb1l_i0IhGMhw/](https://test.long-travel.live/20130908_tropical_park/#gallery%5Bphotonic-google-album-1%5D/AE29bMH8xEtkdMMGlZNOgK1LtKVQPRBD77cR1ovyeCqQziztTzybE0vQPtvL_-8UAaRt_BR056oFBjtBG3BXdlb1l_i0IhGMhw/)
Кроки для відтворення:

1 .Відкрийте друге фото.
2. Клікніть на кнопку для перегляду слайду.

3. Зверніть увагу, що вона не запускає перегляд  слайдів коректно.

Фактичний результат: При кліканні на кнопку не запускається перегляд слайдів.

Очікуваний результат: При кліканні на кнопку запускається перегляд слайдів.
Середовище: Windows 10 Pro
система:
Браузер: Google Chrome Версія 114.0.5735.199 (Офіційне складання) (64-розрядна версія)
![bag 3](https://github.com/scholokov/long-travel-2/assets/138390187/1af3b4cd-23aa-46ff-a205-f7e284d48a66)

**Comment by DmytroMarkulych** [comment]
Давайте замість фрази "Не працює" вкажемо конкретну дію

**Comment by scholokov** [comment]
функціонал слайд шоу прибраний

**Comment by ODrobik** [comment]
перевірено
