### ISSUE TITLE
20180428_0501_beregovo - Фото не отображаются в LightBox

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#394]
**Steps to reproduce:**

1. Открыть страницу https://test.long-travel.live/20180428_0501_beregovo/
2. В любом блоке путешествия найти фотогалерею
3. Кликнуть по любому превью фото 

**Actual result:**
Фото в LightBox **не отображается**

**Expected result:**
Фото в LightBox **отображается**

![image](https://user-images.githubusercontent.com/86321831/145692401-cf10defb-0ac4-449e-acbf-3c77f9683985.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
can't reproduce
please retest

**Comment by yanadiya** [comment]
закрыт, как неактуальный
