### ISSUE TITLE
20200719_belya_tsercov - Название области и страны путешествия не соответствует языку страны

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#395]
**Steps to reproduce:**

1. Открыть страницу https://test.long-travel.live/20200719_belya_tsercov/
2. Обратить внимание на название области и страны путешествия

**Actual result:**
Название области и страны не соответствует языку страны - **Киевская область, Украина**

**Expected result:**
Название области и страны соответствует языку страны - **Київська область, Україна**

![image](https://user-images.githubusercontent.com/86321831/145718404-ce8d0a03-bc3c-43f1-8a4e-a14886b6686e.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
