### ISSUE TITLE
20180611_Kiev_Sea/The title text "Киевское водохранилище (Киевское море)" of the header is in russian

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3951]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20180611_kiev_sea/

2. Scroll down to the header.

3. Pay attention to the title text "Киевское водохранилище (Киевское море)".

**Actual result:**
The title text "Киевское водохранилище (Киевское море)" of the header is in russian

**Expected result:**
The title text "Київське водосховище (Київське море)" of the header is in Ukrainian

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/1.2-%D0%9C%D0%BE%D0%B2%D0%B0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/2b649764-ed14-4ac5-84ee-42dd520fa39c)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/b9b53a22-bfb6-4b67-9895-adf8c9690573)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
