### ISSUE TITLE
20180611_Kiev_Sea/The size of the text Київське водосховище (Київське море) is 18px

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3953]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20180611_kiev_sea/

2. Scroll down to the header.

3. Pay attention to the title text "Київське водосховище (Київське море)".

**Actual result:**
The size of the text Київське водосховище (Київське море) is 18px

**Expected result:**
The size of the text Київське водосховище (Київське море) is 24px

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-2459&mode=design&t=JDbdeJqV7YGwpwCa-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/0f5f2b40-df77-49c6-9f4b-54cbfc4610f6)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/5c3e192a-ed65-432d-8973-cde689b534dd)

**Comment by scholokov** [comment]
please retest

**Comment by prokopenkoga1977** [comment]
Passed
