### ISSUE TITLE
20180708_boguslav/Block travel not exact size(DevTool)

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#3954]
**Steps to reproduce:**

**1.** Open page <https://www.test.long-travel.live/20180708_boguslav>
**2.** Scroll to header block"Богуслав"
**3.** Open console in DevTools.

**Actual result:**
Header block size("header-opacity") = "1250x31".

**Expected result:**
Header block size("header-opacity") = "1250x58".

**Environment:**
MacBook/macOS Ventura 13.5/Safari Version 16.6 (18615.3.12.11.2)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/3018fd66-1f9b-4468-82a7-a713ba08a12c)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/318a8b4a-727b-44b5-81d2-39631a2f872b)

**Comment by DmytroMarkulych** [comment]
це два різні елементи

**Comment by SerhiiBurdieiev** [comment]
На скрінах елементі однакові. В другому скріні просто зроблено виправлення розмірів для наглядності.

**Comment by scholokov** [comment]
виправлено
