### ISSUE TITLE
20170521_korosten / Name of the city "Kyiv" in the map's legend is in English

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3957]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170521_korosten
2. Pay attention to the name of the city "Kyiv" in the map's legend.

**Actual result:**
The name of the city "Kyiv" in the map's legend is in English.

**Expected result:**
The name of the city "Kyiv" in the map's legend is in Ukrainian.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/4bae2eb9-3f49-4ea1-b62e-5631cd98ea15)

**Comment by GNatala** [comment]
#3230

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
