### ISSUE TITLE
20170521_korosten / Extra text "Дорога – Киев – Коростень" after map block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3960]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170521_korosten/
2. Pay attention to the text "Дорога – Киев – Коростень" after map block.

**Actual Result:** 
There is "Дорога – Киев – Коростень" after map block.

**Expected Result:** 
There is no "Дорога – Киев – Коростень" after map block.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

**Attachment:**

![image](https://github.com/scholokov/long-travel-2/assets/101987790/0c9c3365-d99c-4f9e-a75c-14a0c6d24749)

**Comment by GNatala** [comment]
#3230

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
