### ISSUE TITLE
20180708_boguslav/Language of the city, region and country in Russian,not Ukrainian as it should be.

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#3961]
**Steps to reproduce:**

**1.** Open page https://www.test.long-travel.live/20180708_boguslav
**2.** Scroll through all block names

**Actual result:**
Language city, region and country Russian.

**Expected result:**
Language city, region and country Ukrainian.

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/56e309e6-030a-4950-ac59-9d9717e51417)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/3927871b-3216-4981-9bfc-328569fd320f)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/7a0c26e5-3da9-449a-ba7a-2d2355afc304)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/c522846d-7fb4-4613-8940-4874543faaf6)

**Environment:**
MacBook/macOS Ventura 13.5/Safari Version 16.6 (18615.3.12.11.2)

**Comment by scholokov** [comment]
виправлено

**Comment by SerhiiBurdieiev** [comment]
The language from Russian to Ukrainian has not changed.



![Image](https://github.com/scholokov/long-travel-2/assets/108996909/84d3ccf9-657a-42ef-b7a7-b3c878082996)
![Image](https://github.com/scholokov/long-travel-2/assets/108996909/2c3f5ef4-7c08-4b60-8115-2b31905c0cf2)

**Comment by scholokov** [comment]
виправлено
