### ISSUE TITLE
/20151031_haisyn_uman/ розмір шрифту заголовку Long-Travel 27рх 

### ISSUE THREAD

**Issue by SulymaIhor** [scholokov/long-travel-2#3967]
**Передумови:**
Відкрити https://test.long-travel.live/20151031_haisyn_uman/
**Кроки для відтворення:**
1. звернути увагу на заголовок Long-Travel

**Фактичний результат:** font-size: 27px;

**Очікуваний результат:** font-size: 36px;

**Середовище:**
**Система:** Windows 10 Pro
**Браузер:** Google Chrome Версія 114.0.5735.199
![image](https://github.com/scholokov/long-travel-2/assets/122620802/1f5629b2-3445-4ba1-98c4-87b999283611)
![image](https://github.com/scholokov/long-travel-2/assets/122620802/23f6fe08-e4e1-4256-a52b-122d6bbfe3b8)

**Comment by SulymaIhor** [comment]
#3080

**Comment by scholokov** [comment]
please retest
