### ISSUE TITLE
20180428_0501_beregovo - Фотогалерея промежуточной точки Отель Ламберт не соответствует legacy

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#397]
**Steps to reproduce:**

1. Открыть страницу https://test.long-travel.live/20180428_0501_beregovo/
2. Найти промежуточную точку Отель "Ламберт"
3. Сравнить фотогалерею с аналогичным контентом на https://legacy.long-travel.live/blog.php?article=20180428_0501_Beregovo

**Actual result:**
Фотогалерея промежуточной точки Отель "Ламберт" **не соответствует** аналогичному контенту legacy

**Expected result:**
Фотогалерея промежуточной точки Отель "Ламберт" **соответствует** аналогичному контенту legacy

![image](https://user-images.githubusercontent.com/86321831/145719517-faad0882-b13f-4dc9-b4fa-1245a7c56fdd.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
