### ISSUE TITLE
20180611_Kiev_Sea/The title text "Киевское водохранилище (Киевское море) Киевская область" of the header is in russian

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3972]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20180611_kiev_sea/

2. Scroll down to the "Киевское водохранилище (Киевское море) Киевская область" block.

3. Pay attention to the title text "Киевское водохранилище (Киевское море) Киевская область".

**Actual result:**
The title text "Киевское водохранилище (Киевское море) Киевская область" of the header is in russian,

**Expected result:**
The title text "Киевское водохранилище (Киевское море) Киевская область" of the header is in Ukrainian.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/1.2-%D0%9C%D0%BE%D0%B2%D0%B0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/176284c2-a51d-4899-9f10-d413e10ecb1d)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/99458dc0-3df0-45e5-adbb-09131a5cae30)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
