### ISSUE TITLE
20180611_Kiev_Sea/The flag of Ukraine is missed in the "Киевское водохранилище (Киевское море) Киевская область" block

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3973]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20180611_kiev_sea/

2. Scroll down to the "Киевское водохранилище (Киевское море) Киевская область" block.

3. Pay attention to the absence of a flag of Ukraine in the right side of the block.

**Actual result:**
The flag of Ukraine is missed in the "Киевское водохранилище (Киевское море) Киевская область" block.

**Expected result:**
The flag of Ukraine must be in the right side of the block.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/4819a1c2-4299-4c89-938f-2bf765fc75ff)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/21342477-731e-48c5-9c4b-8927940ca522)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
