### ISSUE TITLE
20180611_Kiev_Sea/The travel data is missed in the "Киевское водохранилище (Киевское море) Киевская область" block

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3974]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20180611_kiev_sea/

2. Scroll down to the "Киевское водохранилище (Киевское море) Киевская область" block.

3. Pay attention to the absence of a travel data in the left side of the block.

**Actual result:**
The travel data is missed in the "Киевское водохранилище (Киевское море) Киевская область" block

**Expected result:**
The travel data must be in the left side of the block.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/8231438f-26ed-4550-8ee1-056530b9cf5d)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/195a91d3-2d25-439a-b152-48862710fcf2)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
