### ISSUE TITLE
Requirements/Point 3.2 - 1.2 An explanation of the date of travel is missed in the name of travel

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3977]
**Steps to retroduce:**
1. Open https://github.com/scholokov/long-travel-2/wiki/3.2-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%93%D0%BB%D0%BE%D0%B1%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0-%D0%BA%D0%B0%D1%80%D1%82%D0%B0-%D0%B7-%D0%BC%D0%B0%D1%80%D1%88%D1%80%D1%83%D1%82%D0%B0%D0%BC%D0%B8
2.  Scroll down to the point 1.2
3. Pay attention to the absence of an explanation of what the travel date should be in the title.

**Actual result:**
An explanation of the date of travel is missed in the name of travel

**Expected result:**
An explanation of the date of travel should be in the name of travel. The date of the travel is the start date of the travel. 

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/7986676e-7565-4cd9-b044-e0386f48cd63)

**Comment by scholokov** [comment]
додані наступні вимоги до формування назви подорожі на глобальній мапі:
1.2.1 та 1.2.2

**Comment by prokopenkoga1977** [comment]
Passed
