### ISSUE TITLE
20180611_Kiev_Sea/The text "Киевская область, Украина" is extra information of the preview

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3978]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20180611_kiev_sea/

2. Scroll down to the text "Киевская область, Украина" of the preview of the travel

3. Pay attention to the text "Киевская область, Украина".

**Actual result:**
The text "Киевская область, Украина" is extra information of the preview.

**Expected result:**
The text "Киевская область, Украина" should be missing.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6#134-youtube-%D0%B3%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/01c2ef42-68e3-44d5-a3b3-6a8dcf5dfc17)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/05e921c1-45d1-4f69-aa9e-2ea76ea5403f)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
