### ISSUE TITLE
20180611_Kiev_Sea/The icon automobile is extra information of the preview

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3979]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20180611_kiev_sea/

2. Scroll down to the preview of the travel

3. Pay attention to the icon of automobile in the right side.

**Actual result:**
The icon automobile is extra information of the preview.

**Expected result:**
The icon automobile should be missing.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6#134-youtube-%D0%B3%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/4db77ef3-9ca6-4066-a5be-bb465d7c4187)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/cfe39d09-c7a6-450f-8cac-5e78ab277df3)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
