### ISSUE TITLE
20180611_Kiev_Sea/The text "Вечерняя поездка после работы. Отличное место для релакса после рабочего дня. Людей минимум. Недалеко от города. Ближе к лесу очень много мошек." is in russian

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3980]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20180611_kiev_sea/

2. Scroll down to the "Київське водосховище (Київське море)" block.

3. Pay attention to the text "Вечерняя поездка после работы. Отличное место для релакса после рабочего дня. Людей минимум. Недалеко от города. Ближе к лесу очень много мошек."

**Actual result:**
The text "Вечерняя поездка после работы. Отличное место для релакса после рабочего дня. Людей минимум. Недалеко от города. Ближе к лесу очень много мошек." is in russian

**Expected result:**
The text "Вечерняя поездка после работы. Отличное место для релакса после рабочего дня. Людей минимум. Недалеко от города. Ближе к лесу очень много мошек." is in Ukrainian.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/1.2-%D0%9C%D0%BE%D0%B2%D0%B0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/89ec587b-ec00-4853-b2ec-ace4c1c46e1b)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/415c38e4-18d8-4319-8720-6d7c049b19ca)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
