### ISSUE TITLE
wiki/The page "4. Подорож"  does not specify the necessary information, in which language the video author's signature should be

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3985]
Steps to reproduce:
1. Open: https://github.com/scholokov/long-travel-2/wiki
2. Click on the page "4. Подорож"
3. Pay attention to the page "4. Подорож"

Actual Result: the page does not specify the necessary information, in which language the video author's signature should be
Expected Result: the page specifys the necessary information

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/b31e0965-8cf2-4d8b-ba31-a209a2207046)

**Comment by scholokov** [comment]
додано пункт
1.3.4.1.5

**Comment by ODrobik** [comment]
перевірено
