### ISSUE TITLE
20170709_protsiv/In the Standart block "Дорога" the flag of the travel is missing 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#3986]
Steps to reproduce:
1. Open page https://test.long-travel.live/20170709_protsiv/
2. Pay attention to the the Standart block "Дорога" 

Actual Result: the flag of the travel is **missing** 
Expected Result: the flag of the travel is **present**

Requirements: https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/f9444ff3-b14d-4986-a2e0-4b94ac786b3a)

**Comment by ODrobik** [comment]
#3235

**Comment by scholokov** [comment]
вииправлено

**Comment by ODrobik** [comment]
перевірено
