### ISSUE TITLE
20180611_Kiev_Sea/The name of the video "Kiev - Kiev Sea" is in English

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3988]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20180611_kiev_sea/

2. Scroll down to the video "Kiev - Kiev Sea".

3. Pay attention to the name of the video.

**Actual result:**
The name of the video "Kiev - Kiev Sea" is in English

**Expected result:**
The name of the video "Kiev - Kiev Sea" is in Ukrainian

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6#134-youtube-%D0%B3%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/f7e668fc-4b37-4cb3-a8ed-080f4c556dab)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/6ef0ddc1-467e-47cc-820d-550ede0a09d0)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
