### ISSUE TITLE
20180611_Kiev_Sea/The date of publication is 02.09.2021

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#3989]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20180611_kiev_sea/

2. Scroll down to the date of publication.

3. Pay attention to the date of publication.

**Actual result:**
The date of publication is 02.09.2021

**Expected result:**
The date of publication is 11.06.2018

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6#14-%D0%B4%D0%B0%D1%82%D0%B0-%D0%BF%D1%83%D0%B1%D0%BB%D1%96%D0%BA%D0%B0%D1%86%D1%96%D1%97

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/f4ab64bd-ac93-4b53-ac52-f3990882b5f7)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/c808d84b-1d3e-4e60-80ed-da08e48ce08e)

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/06760235-be0a-48ad-b0b5-a00a3fab3a0b)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
