### ISSUE TITLE
20180428_0501_beregovo - Фотогалерея промежуточной точки Кафе “Chilli-Pizza” не соответствует legacy

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#399]
**Steps to reproduce:**

1. Открыть страницу https://test.long-travel.live/20180428_0501_beregovo/
2. Найти промежуточную точку Кафе “Chilli-Pizza”
3. Сравнить фотогалерею с аналогичным контентом на https://legacy.long-travel.live/blog.php?article=20180428_0501_Beregovo

**Actual result:**
Фотогалерея промежуточной точки Кафе “Chilli-Pizza” **не соответствует** аналогичному контенту legacy

**Expected result:**
Фотогалерея промежуточной точки Кафе “Chilli-Pizza” **соответствует** аналогичному контенту legacy

![image](https://user-images.githubusercontent.com/86321831/145719874-67188842-5cb1-41c8-90c3-1552a4a60997.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
