### ISSUE TITLE
20170521_korosten / Missed 3-rd Preview block "Житомирская область, Украина 21.05.2017

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3992]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170521_korosten/
2. Pay attention to the absence of the 3-rd Preview block "Житомирская область, Украина 21.05.2017".

**Actual result:**
Missed 3-rd Preview block "Житомирская область, Украина 21.05.2017".

**Expected result:**
3-rd Preview block "Житомирская область, Украина 21.05.2017" is present.

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment** 
![image](https://github.com/scholokov/long-travel-2/assets/101987790/9c6dd8cb-1552-4d63-b60c-fd3a8069e6a3)

**Comment by GNatala** [comment]
#3230

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
