### ISSUE TITLE
20170521_korosten / Missed Road block "Дорога – Коростень – Киев"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3993]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170521_korosten/
2. Scroll down to the last photo.
3. Pay attention to the absence of the Road block "Дорога – Коростень – Киев" before the last photo.

**Actual result:**
Missed Road block "Дорога – Коростень – Киев" with preview.

**Expected result:**
Road block "Дорога – Коростень – Киев" with preview is present the last photo.

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment** 
![image](https://github.com/scholokov/long-travel-2/assets/101987790/170ae958-70d9-4b72-b936-ca0aefd21c70)

**Comment by GNatala** [comment]
#3230

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
