### ISSUE TITLE
20170521_korosten / The publication date is 02.09.2021

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3994]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170521_korosten/
2. Scroll down to the date of publication.
3. Pay attention to the date of publication.

**Actual result:**
 The publication date is 02.09.2021

**Expected result:**
 The publication date is 21.05.2017

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6#14-%D0%B4%D0%B0%D1%82%D0%B0-%D0%BF%D1%83%D0%B1%D0%BB%D1%96%D0%BA%D0%B0%D1%86%D1%96%D1%97

**Attachments:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/146077f5-6e88-409f-bdc9-631ef2f90309)

**Comment by GNatala** [comment]
#3230

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
