### ISSUE TITLE
20170521_korosten / The date format of the video Киев-Коростень is 21.05.2017 (DD.MM.YYYY) 

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#3995]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170521_korosten/
2. Scroll to the 1-st video Киев-Коростень.
3. Pay attention to the date format of the video.

**Actual result:**
The date format of the video Киев-Коростень is 21.05.2017 (DD.MM.YYYY) 

**Expected result:**
The date format of the video Киев-Коростень is 2017.05.21 (YYYY.MM.DD)

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6#134-youtube-%D0%B3%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%97

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment** 
![image](https://github.com/scholokov/long-travel-2/assets/101987790/0d9f8776-384f-49e0-941e-b4721750f86d)

**Comment by GNatala** [comment]
#3230

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
