### ISSUE TITLE
20170521_korosten / Missed Ukrainian flag in the preview "Дорога  Киев - Коростень "

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4000]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170521_korosten
2. Scroll to the preview "Дорога  Киев - Коростень ".
3. Pay attention to the absence of the Ukrainian flag.

**Actual result:**
Ukrainian flag is missed in the preview "Дорога  Киев - Коростень".

**Expected result:**
Ukrainian flag is present in the preview "Дорога  Киев - Коростень ".

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment** 
![image](https://github.com/scholokov/long-travel-2/assets/101987790/733cc6d2-fcfc-40e7-89e3-cd4b9f05d037)

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
