### ISSUE TITLE
"Хрещатик – Маріїнський парк" - Name of the standart block "Крещатик, Мариинский парк" is written in Russian

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4001]
**Steps of reproducing**
1. Open https://test.long-travel.live/20170605_kiev_mariinskiy/
2. Scroll to "Крещатик, Мариинский парк" standart block
3. Pay attention to the name

**Actual Result**
Name of the standart block "Крещатик, Мариинский парк" is written in Russian

**Expected Result**
Name of the standart block "Крещатик, Мариинский парк" is written in Ukrainian

**Additional information**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

**Enviroments**
Windows 10, Chrome 115.0.5790.99 (64 bit), Firefox 115.0.2 (64 bit)
Android 8.1.0, Chrome 114.0.5735.196, Firefox 115.2.0 
![Хрещатик – Маріїнський парк – Long-Travel - Google Chrome 19 07 2023 16_58_25](https://github.com/scholokov/long-travel-2/assets/95171672/bc299227-6fae-44a9-915a-3dec989b5883)
![photo_2023-07-19_17-03-34](https://github.com/scholokov/long-travel-2/assets/95171672/29e48312-7c9e-430f-8850-c836da1325eb)
![Хрещатик – Маріїнський парк – Long-Travel — Mozilla Firefox 19 07 2023 16_58_29](https://github.com/scholokov/long-travel-2/assets/95171672/e52e8b27-9ecc-4083-b28c-172924cbd809)
![photo_2023-07-19_17-03-37](https://github.com/scholokov/long-travel-2/assets/95171672/57184ea6-2f97-40f7-831f-2455dffd8d10)

**Comment by DmitriiNasonov** [comment]
#3926

**Comment by scholokov** [comment]
виправлено
