### ISSUE TITLE
"Хрещатик – Маріїнський парк" - Type of the standart block "Крещатик, Мариинский парк" is "Entertainment"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4002]
**Steps of reproducing**
1. Open https://test.long-travel.live/20170605_kiev_mariinskiy/
2. Scroll to standart block "Крещатик, Мариинский парк"

**Actual Result**
Type of the standart block "Крещатик, Мариинский парк" is "Entertainment"

**Expected Result**
Type of the standart block "Крещатик, Мариинский парк" is "Park"

**Additional information**
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-6&mode=design&t=mhQYtxKdbZnba812-0

**Enviroments**
Windows 10, Chrome 115.0.5790.99 (64 bit), Firefox 115.0.2 (64 bit)
Android 8.1.0, Chrome 114.0.5735.196, Firefox 115.2.0 
![New Issue · scholokov_long-travel-2 - Google Chrome 19 07 2023 17_13_21](https://github.com/scholokov/long-travel-2/assets/95171672/06a1a0e4-f185-4b35-b69b-02a2badf17a6)
![photo_2023-07-19_17-13-28](https://github.com/scholokov/long-travel-2/assets/95171672/3c9c7f14-b789-407e-b421-448e814e2940)
![Хрещатик – Маріїнський парк – Long-Travel — Mozilla Firefox 19 07 2023 17_13_14](https://github.com/scholokov/long-travel-2/assets/95171672/ae6868f1-42da-4de6-881d-b8942fbc8075)
![photo_2023-07-19_17-13-31](https://github.com/scholokov/long-travel-2/assets/95171672/46db4c78-f611-4121-8f05-9c2bca869d92)

**Comment by DmitriiNasonov** [comment]
#3926

**Comment by scholokov** [comment]
виправлено

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
