### ISSUE TITLE
"Хрещатик – Маріїнський парк" - Devtools - Error "Failed to load resource: the server responded with a status of 403 ()" is present

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4003]
**Steps of reproducing**
1. Open https://test.long-travel.live/20170605_kiev_mariinskiy/
2. Open Console in DevTools

**Actual Result**
Error "Failed to load resource: the server responded with a status of 403 ()" is present

**Expected Result**
Error "Failed to load resource: the server responded with a status of 403 ()" is missing

**Enviroments**
Windows 10, Chrome 115.0.5790.99 (64 bit)
![Screenshot 19 07 2023 17_25_37](https://github.com/scholokov/long-travel-2/assets/95171672/dae78160-73cd-4da1-be09-9a115ccf9d9a)

**Comment by scholokov** [comment]
при яких умовах виникає?

**Comment by DmitriiNasonov** [comment]
bug isn't reproduced
