### ISSUE TITLE
"Хрещатик – Маріїнський парк" - Devtools - Error "GET (link) 403" is present

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4004]
**Steps of reproducing**
1. Open https://test.long-travel.live/20170605_kiev_mariinskiy/
2. Open Console in DevTools

**Actual Result**
Error "GET (link) 403" is present

**Expected Result**
Error "GET (link) 403" is missing

**Enviroments**
Windows 10, Chrome 115.0.5790.99 (64 bit)
![DevTools - test long-travel live_20170605_kiev_mariinskiy_ 19 07 2023 17_30_52](https://github.com/scholokov/long-travel-2/assets/95171672/a3a2c333-ffba-4ed1-98a6-0de7c76f8ce8)

**Comment by DmitriiNasonov** [comment]
#3926

**Comment by scholokov** [comment]
при яких умовах?

**Comment by DmitriiNasonov** [comment]
bug isn't reproduced
