### ISSUE TITLE
20170612_buki/The format of the travel name "Буцький каньйон" is "travel name"

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4009]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170612_buki/

2. Scroll down to the Global Map.

3. Pay attention to the format of the travel name.

**Actual result:**
The format of the travel name "Буцький каньйон" is "travel name"

**Expected result:**
The format of the travel name "Буцький каньйон" is YYYY.MM.DD "travel name" (2017.06.12 Буцький каньйон)

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/3.2-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%93%D0%BB%D0%BE%D0%B1%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0-%D0%BA%D0%B0%D1%80%D1%82%D0%B0-%D0%B7-%D0%BC%D0%B0%D1%80%D1%88%D1%80%D1%83%D1%82%D0%B0%D0%BC%D0%B8

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/cf6a6181-465b-4969-b746-ee237897bcee)

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/70db484f-e8ea-401a-99bc-1c4c506dea63)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
