### ISSUE TITLE
20180428_0501_beregovo - Фотогалерея промежуточной точки Замок “Паланок” не соответствует legacy

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#401]
**Steps to reproduce:**

1. Открыть страницу https://test.long-travel.live/20180428_0501_beregovo/
2. Найти промежуточную точку Замок “Паланок”
3. Сравнить фотогалерею с аналогичным контентом на https://legacy.long-travel.live/blog.php?article=20180428_0501_Beregovo

**Actual result:**
Фотогалерея промежуточной точки Замок “Паланок” **не соответствует** аналогичному контенту legacy

**Expected result:**
Фотогалерея промежуточной точки Замок “Паланок” **соответствует** аналогичному контенту legacy

![image](https://user-images.githubusercontent.com/86321831/145720057-0c8c2a6a-59b7-4a8f-9e9a-065cd113efaf.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
not fixed

![image](https://user-images.githubusercontent.com/86321831/145726496-69dce511-a174-441f-a110-e5038c331325.png)

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
