### ISSUE TITLE
/20130721_Vitachev/ Назва подорожі прописано російською мовою

### ISSUE THREAD

**Issue by TetianaKap** [scholokov/long-travel-2#4015]
Передумови:
Відкрити https://long-travel.live/20130721_Vitachev/ 

Кроки для відтворення:
1. Зверніть увагу що назва подорожі прописана російською

Фактичний результат: Назва подорожі прописано російською мовою
Очікуваний результат: Назва подорожі повинна бути українською мовою
Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Version 115.0.5790.102
![Баг 1](https://github.com/scholokov/long-travel-2/assets/139850564/b23a3b74-a65d-4d5d-b984-779d46cfd837)

**Comment by TetianaKap** [comment]
#1186

**Comment by Nadiyk** [comment]
привіт

**Comment by TetianaKap** [comment]
я виправила

**Comment by scholokov** [comment]
виправлено

**Comment by Illia2810** [comment]
перевірено
