### ISSUE TITLE
/20130721_Vitachev/ В Preview подорожі  відсутня дата подорожі

### ISSUE THREAD

**Issue by TetianaKap** [scholokov/long-travel-2#4016]
Передумови:
Відкрити https://test.long-travel.live/20130721_Vitachev/
Кроки для відтворення:
1.Зверніть уваги, що в Preview подорожі немає дати подорожі

Фактичний результат: Відсутня дата подорожі в Preview подорожі
Очікуваний результат: Повинна бути вказана дата в Preview подорожі 21.07.2013

Середовище: Windows 10 Pro Операційна
система:
Браузер: Google Chrome Version 115.0.5790.102
![баг 2](https://github.com/scholokov/long-travel-2/assets/139850564/869a28de-d3c8-4422-ae6a-d7854143c4b7)

![Image](https://github.com/scholokov/long-travel-2/assets/101987790/9f9358ca-caab-4b47-b218-a2a8779c535c)

![Image](https://github.com/scholokov/long-travel-2/assets/101987790/5071e476-58fa-4b98-b67f-93b42cc126e9)

**Comment by TetianaKap** [comment]
#1186

**Comment by DmytroMarkulych** [comment]
додайте конкретно яка дата має бути в подорожі

**Comment by GNatala** [comment]
додала

**Comment by DmytroMarkulych** [comment]
Summary описує як має бути а не як є насправді

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
Баг відтворюється.

**Фактичний результат:** Відсутня дата подорожі в Preview подорожі
**Очікуваний результат:** Повинна бути вказана дата в Preview подорожі 21.07.2013

![image](https://github.com/scholokov/long-travel-2/assets/101987790/641728c1-7e04-40d8-b23e-3dd2f64f47e5)

**Comment by scholokov** [comment]
а ви точно на правильному інвайроменті дивитесь? :)

**Comment by GNatala** [comment]
Точно, дивлюсь не там де треба. 
Перевірено
