### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - Road "Kyiv - Svityaz" video size  is not 628x353 

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#4025]
**Steps to playback:**

1. Open  https://www.test.long-travel.live/20160814_24_shadsk
2. Scroll down to Road "Kyiv - Svityaz"
3. Pay attention to the video Road "Kyiv - Svityaz"

**Actual result:**
Video size  is not 628x353

**Expected result:**
Video size   1280x670
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=5000%3A61&mode=dev
![вимоги відео](https://github.com/scholokov/long-travel-2/assets/132911639/dbfd8561-0e36-4bf0-b7a2-0e2d3ca4a76a)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![баг відео 1](https://github.com/scholokov/long-travel-2/assets/132911639/b2f113d4-dcc6-49b6-8b54-a14cff14ca09)

**Comment by Artem-16** [comment]
#3086

**Comment by scholokov** [comment]
буд ласка повтори тестування з очищеним кешом

**Comment by Artem-16** [comment]
Очистив кеш, але те саме розмір відео без змін

**Comment by scholokov** [comment]
спробуй у приватному режимі.

**Comment by Artem-16** [comment]
ок

**Comment by Artem-16** [comment]
Без змін в приватному режимі
в браузері сафарі теж саме

**Comment by scholokov** [comment]
почистив кеш на стороні сервера. має бути ок

**Comment by Artem-16** [comment]
Так змінилося, але розмір все одно не такий як в фігме

**Comment by scholokov** [comment]
супер.
тепер можна скласти баг не те, що неправильний розмір. 
а на те що по різному відображаться:
- ютуб відео
- ютуб галерея
і саме галерея виглядає ок, а от ютуб ні

**Comment by Artem-16** [comment]
тоді я ці баг що завів закриваю і відкриваю нові?
