### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - Lake "Svityaz" Video size is not 834x447

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#4027]
**Steps to playback:**

1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Scroll down Recreation center "Svityaz"
3. Pay attention to the video of Lake "Svityaz"

**Actual result:**
Video size is not 834x447

**Expected result:**
Video size 1280x670
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=5000%3A61&mode=dev
![вимоги відео](https://github.com/scholokov/long-travel-2/assets/132911639/709ae0d3-1d12-4768-8f0d-408d3375c874)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![баг відео 3](https://github.com/scholokov/long-travel-2/assets/132911639/d3df6bf1-26f8-4668-ba5d-45a45adac950)

**Comment by Artem-16** [comment]
#3086

**Comment by scholokov** [comment]
скоріш за все розміри брались при завуженому вікні
тобто коли визиваєш дев тул, він з'їдає частину екрану. а коли треба заміряти об'єкт з великою шириною це може бути принципово. як варіант рішення - дев тулз виводити знизу, а не справа
