### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - Road "Svityaz" video size is not 628x353

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#4029]
**Steps to playback:** 

1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Scroll down to Road "Svityaz" 
3. Pay attention to the video Road "Svityaz" 

**Actual result:**
Video size is not 628x353

**Expected result:**
Video size 1280x670
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=5000%3A61&mode=dev
![вимоги відео](https://github.com/scholokov/long-travel-2/assets/132911639/1a954492-76d4-464d-ba2b-c10931e28be7)

Environment:
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![баг відео 4](https://github.com/scholokov/long-travel-2/assets/132911639/4acab26f-5f2e-4870-9e6e-840e2432f68f)

**Comment by Artem-16** [comment]
#3086

**Comment by scholokov** [comment]
please clear cache and retest
