### ISSUE TITLE
20180428_0501_beregovo - Фотогалерея промежуточной точки Замок “Сент-Міклош” не соответствует legacy

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#403]
**Steps to reproduce:**

1. Открыть страницу https://test.long-travel.live/20180428_0501_beregovo/
2. Найти промежуточную точку Замок “Сент-Міклош”
3. Сравнить фотогалерею с аналогичным контентом на https://legacy.long-travel.live/blog.php?article=20180428_0501_Beregovo

**Actual result:**
Фотогалерея промежуточной точки Замок “Сент-Міклош” **не соответствует** аналогичному контенту legacy

**Expected result:**
Фотогалерея промежуточной точки Замок “Сент-Міклош” **соответствует** аналогичному контенту legacy

![image](https://user-images.githubusercontent.com/86321831/145720629-9dbb8498-ac01-4416-a6af-98f936510a75.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
