### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - Road "Svityaz - Kyiv" video size is not 628x353

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#4030]
**Steps to playback:**

1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Scroll down to Road "Svityaz - Kyiv"
3. Pay attention to the video Road "Svityaz - Kyiv"

**Actual result:**
Video size is not 628x353

**Expected result:**
Video size 1280x670
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=5000%3A61&mode=dev
![вимоги відео](https://github.com/scholokov/long-travel-2/assets/132911639/d0516d10-3a69-4cdd-b210-b52ae41d3e65)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![баг відео 5](https://github.com/scholokov/long-travel-2/assets/132911639/ce1b9db4-31cb-449c-98af-66d6471d7276)

**Comment by Artem-16** [comment]
#3086

**Comment by scholokov** [comment]
please clear cache and retest

**Comment by scholokov** [comment]
почистив кеш на стороні сервера. має бути ок
