### ISSUE TITLE
20160830_Myrgorod/ Ukrainian flag size in the Preview block is 27x18

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4031]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20160830_Myrgorod/
2. Pay attention to the Ukrainian flag size in the Preview block.

**Actual result:**
Ukrainian flag size in the Preview block is 27x18

**Expected result:**
Ukrainian flag size in the Preview block is 36x24

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/wiki/3.2-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%93%D0%BB%D0%BE%D0%B1%D0%B0%D0%BB%D1%8C%D0%BD%D0%B0-%D0%BA%D0%B0%D1%80%D1%82%D0%B0-%D0%B7-%D0%BC%D0%B0%D1%80%D1%88%D1%80%D1%83%D1%82%D0%B0%D0%BC%D0%B8

**Attachment:**

![image](https://github.com/scholokov/long-travel-2/assets/101987790/ca8802f3-7ef8-489c-963d-203692368233)

**Comment by GNatala** [comment]
#1352

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
**An issue is reproduced.**

**Actual result:**
Ukrainian flag size in the Preview block is 27x18

**Expected result:**
Ukrainian flag size in the Preview block is 36x24

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/c11060d1-811c-4c69-8d5b-fada2c32a2be)

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
