### ISSUE TITLE
20170521_korosten / Missed Ukrainian flag in the preview "Коростень – Військово-історичний комплекс “Скеля” – Парк імені Островського"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4034]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170521_korosten
2. Scroll to the preview "Коростень – Військово-історичний комплекс “Скеля” – Парк імені Островського".
3. Pay attention to the absence of the Ukrainian flag.

**Actual result:**
Ukrainian flag is missed in the preview "Коростень – Військово-історичний комплекс “Скеля” – Парк імені Островського".

**Expected result:**
Ukrainian flag is present in the preview "Коростень – Військово-історичний комплекс “Скеля” – Парк імені Островського".

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment** 
![image](https://github.com/scholokov/long-travel-2/assets/101987790/08f24ed4-f32f-47dd-81cf-e8ba87f7c486)
![image](https://github.com/scholokov/long-travel-2/assets/101987790/320125dd-ce96-4832-8b1c-118f4661b9d2)

**Comment by GNatala** [comment]
#3230

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
