### ISSUE TITLE
20170521_korosten / Missed Ukrainian flag in the preview "Древлянский парк, Коростень"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4035]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170521_korosten
2. Scroll to the preview "Древлянский парк, Коростен".
3. Pay attention to the absence of the Ukrainian flag.

**Actual result:**
Ukrainian flag is missed in the preview "Древлянский парк, Коростен".

**Expected result:**
Ukrainian flag is present in the preview "Древлянский парк, Коростен".

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment** 
![image](https://github.com/scholokov/long-travel-2/assets/101987790/d3f30277-bdc6-41fd-ae77-8c1dab7b4733)

**Comment by GNatala** [comment]
#3230

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
