### ISSUE TITLE
20170521_korosten / Extra text "Житомирская область, Украина 21.05.2017" after the 1-st video

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4037]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170521_korosten/
2. Pay attention to the text"Житомирская область, Украина 21.05.2017" after the 1-st video.

**Actual Result:** 
There is text "Житомирская область, Украина 21.05.2017" after the 1-st video.

**Expected Result:** 
There is no text "Житомирская область, Украина 21.05.2017" after the 1-st video.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/8d507516-1098-4094-afb1-c038a4104c8c)

**Comment by GNatala** [comment]
#3230

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
