### ISSUE TITLE
20170709_protsiv/Standart block - Preview block of travel the size of the flag of Ukraine is 26x18px

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4038]
Steps to reproduce:
1. Open https://test.long-travel.live/20170709_protsiv/
2. Scroll down to the Preview block "Проців"
3. Pay attention to the size of the flag of Ukraine

Actual result: the size of the flag of Ukraine is 26x18 px
Expected result: the size of the flag of Ukraine is 36x24 px

Requirements: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1800%3A41&mode=dev

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment
![image](https://github.com/scholokov/long-travel-2/assets/123776698/9ad05dd3-14a0-4f90-bf86-0aae1b6f0b38)

**Comment by ODrobik** [comment]
#2995

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
