### ISSUE TITLE
20150919_kiev_aviation_museum/Standart block - Preview block the size of the flag of Ukraine is 26x18px

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4039]
Steps to reproduce:
1. Open https://test.long-travel.live/20150919_kiev_aviation_museum/
2. Scroll down to the Preview block of the Standart block of the travel
3. Pay attention to the size of the flag of Ukraine

Actual result: the size of the flag of Ukraine is 26x18 px
Expected result: the size of the flag of Ukraine is 36x24 px

Requirements: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1800%3A41&mode=dev

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment
![image](https://github.com/scholokov/long-travel-2/assets/123776698/68ba22ec-020e-4db7-8c74-0e73f124d5ed)

**Comment by ODrobik** [comment]
#2995

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
