### ISSUE TITLE
20180428_0501_beregovo - Фотогалерея промежуточной точки Санаторий “Карпаты” не соответствует legacy

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#405]
**Steps to reproduce:**

1. Открыть страницу https://test.long-travel.live/20180428_0501_beregovo/
2. Найти промежуточную точку Санаторий “Карпаты”
3. Сравнить фотогалерею с аналогичным контентом на https://legacy.long-travel.live/blog.php?article=20180428_0501_Beregovo

**Actual result:**
Фотогалерея промежуточной точки Санаторий “Карпаты” **не соответствует** аналогичному контенту legacy

**Expected result:**
Фотогалерея промежуточной точки Санаторий “Карпаты” **соответствует** аналогичному контенту legacy

![image](https://user-images.githubusercontent.com/86321831/145721446-2039df21-a545-4edd-ab5c-569ac8e3f8c1.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
not fixed

![image](https://user-images.githubusercontent.com/86321831/145726711-d7d7ff38-2a61-45dd-960b-6b45ce35b418.png)

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
