### ISSUE TITLE
20130613_0628_Bulgaria/Block travel not exact size(DevTool)

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#4054]
**Steps to reproduce:**

**1.** Open page <https://test.long-travel.live/20130613_0628_Bulgaria/>
**2.** Scroll to header block "Болград – Слънчев бряг – București – Саврань"
**3.** Open console in DevTools.

**Actual result:**
Header block size = "1280x80".

**Expected result:**
Header block size = "1280x117".

**Environment:**
MacBook/macOS Sonoma 14/Safari Version 17.0 (19616.1.20.11.3)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/5273eb1b-b358-4f56-90c4-d2c1bcceb523)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/561accf6-9661-4128-a355-fa2032deb6c9)

**Comment by scholokov** [comment]
виправлено
