### ISSUE TITLE
20130613_0628_Bulgaria/Permanent download icon on the travel page.

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#4056]
**Steps to reproduce:**

Open page <https://test.long-travel.live/20130613_0628_Bulgaria/>

**Actual result:**
There is a download icon on the page

**Expected result:**
There is no download icon on the page

**Environment:**
MacBook/macOS Sonoma 14/Safari Version 17.0 (19616.1.20.11.3)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/d3dd470c-fc58-4535-98d3-a209a7ad1004)

**Comment by SerhiiBurdieiev** [comment]
Changed.

**Comment by scholokov** [comment]
оптимізовано
