### ISSUE TITLE
20180428_0501_beregovo - Фотогалерея промежуточной точки Железнодорожная станция не соответствует legacy

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#406]
**Steps to reproduce:**

1. Открыть страницу https://test.long-travel.live/20180428_0501_beregovo/
2. Найти промежуточную точку Железнодорожная станция
3. Сравнить фотогалерею с аналогичным контентом на https://legacy.long-travel.live/blog.php?article=20180428_0501_Beregovo

**Actual result:**
Фотогалерея промежуточной точки Железнодорожная станция **не соответствует** аналогичному контенту legacy

**Expected result:**
Фотогалерея промежуточной точки Железнодорожная станция **соответствует** аналогичному контенту legacy

![image](https://user-images.githubusercontent.com/86321831/145721871-ff86809f-8b85-4c76-8dec-ca9ba6f55cbf.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
