### ISSUE TITLE
20170521_korosten / Name of the Road block "Дорога Киев – Коростень" is written in russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4060]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170521_korosten/
2. Pay attention to the Road block "Дорога Киев – Коростень".

**Actual Result:** 
Name of the Road block "Дорога Киев – Коростень" is written in russian.

**Expected Result:** 
Name of the Road block "Дорога Київ – Коростень" is written in Ukrainian.

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/1.2-%D0%9C%D0%BE%D0%B2%D0%B0

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/801f48c4-2512-4915-8186-4487ec9e3af5)

**Comment by GNatala** [comment]
#3230

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
