### ISSUE TITLE
20170521_korosten / Name of the Road block "Дорога – Коростень – Киев" is written in russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4061]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170521_korosten/
2. Pay attention to the Road block "Дорога – Коростень – Киев".

**Actual Result:** 
Name of the Road block "Дорога – Коростень – Киев" is written in russian.

**Expected Result:** 
Name of the Road block "Дорога – Коростень – Київ" is written in Ukrainian.

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/1.2-%D0%9C%D0%BE%D0%B2%D0%B0

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/21ce4c2b-a7fb-4801-912d-035466d44421)

**Comment by GNatala** [comment]
#3230

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
passed
