### ISSUE TITLE
20170612_buki/The size of the flag of Ukraine in the preview Butsky canyon is 25x18

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4064]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170612_buki/

2. Scroll down to the preview Butsky canyon.

3. Pay attention to the size of the flag of Ukraine.

**Actual result:**
The size of the flag of Ukraine is 25x18

**Expected result:**
The size of the flag of Ukraine is 36x24

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-2459&mode=design&t=L5eIVbIijAz6skm8-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/8d484f41-8a37-444d-8f4b-6b5bfa7cfe2c)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/109c32fe-9403-44c7-ab80-fa71a17b5a41)

**Comment by scholokov** [comment]
некоректні заміри
буд ласка повторіть тест

**Comment by scholokov** [comment]
некоректні заміри знову ж таки
подивіться в загальний чат тревелу. я писав саме про це

**Comment by prokopenkoga1977** [comment]
Passed
