### ISSUE TITLE
20170612_buki/The size of the flag of Ukraine in the block Road Kyiv Buky is 26x18

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4065]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170612_buki/

2. Scroll down to the block Road Kyiv Buky.

3. Pay attention to the size of the flag of Ukraine.

**Actual result:**
The size of the flag of Ukraine is 26x18

**Expected result:**
The size of the flag of Ukraine is 36x24

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-2459&mode=design&t=L5eIVbIijAz6skm8-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/e7a936da-1989-42af-bc5b-ca184a07c0e1)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/b3088603-469c-4230-a398-7fe508c3b949)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
