### ISSUE TITLE
20170612_buki/The size of the flag of Ukraine in the block Road Buky Kyiv is 26x18

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4068]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170612_buki/

2. Scroll down to the block Road Buky Kyiv.

3. Pay attention to the size of the flag of Ukraine.

**Actual result:**
The size of the flag of Ukraine is 26x18

**Expected result:**
The size of the flag of Ukraine is 36x24

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-2459&mode=design&t=L5eIVbIijAz6skm8-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/b0343acc-c041-4d7a-9c9b-ee7c667a6b4f)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/5eacde21-80c9-4cb0-adf7-86bd8e80d038)

**Comment by scholokov** [comment]
виправлено

**Comment by prokopenkoga1977** [comment]
Passed
