### ISSUE TITLE
20170521_korosten / Name of the Preview "Коростень – “Скеля” – Древлянский парк" is written in russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4069]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170521_korosten/
2. Pay attention to the Preview "Коростень – “Скеля” – Древлянский парк".

**Actual Result:** 
Name of the Preview "Коростень – “Скеля” – Древлянский парк" is written in russian.

**Expected Result:** 
Name of the Preview "Коростень – “Скеля” – **Древлянський** парк" is written in Ukrainian.

**Additional information:**
https://github.com/scholokov/long-travel-2/wiki/1.2-%D0%9C%D0%BE%D0%B2%D0%B0

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/f5947fd1-4157-4ed0-881c-7088ae7b4f54)

**Comment by GNatala** [comment]
#3230

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
passed
