### ISSUE TITLE
20170513_putivl_kruti/The name of travel in the Preview block does not match the name of Travel in the requirements of clause 3.1 Подорожі. Перелік

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4073]
Steps to reproduce:
1. Open https://test.long-travel.live/20170513_putivl_kruti/
2. Scroll down to the Preview block
3. Pay attention to the name of travel in the Preview block 

Actual result: The name of travel in the Preview block "Путивль Сумська область – Крути Чернігівська область-Україна"
Expected result: The name of travel in the Preview block "Путивль-Крути"

Requirements:https://github.com/scholokov/long-travel-2/wiki/3.1-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%9F%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/c2629769-b423-425e-989c-49ef95a7affc)

**Comment by ODrobik** [comment]
#3229

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
