### ISSUE TITLE
20180428_0501_beregovo - Фотогалерея промежуточной точки Ресторан “Фламинго” не соответствует legacy

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#408]
**Steps to reproduce:**

1. Открыть страницу https://test.long-travel.live/20180428_0501_beregovo/
2. Найти промежуточную точку Ресторан “Фламинго”
3. Сравнить фотогалерею с аналогичным контентом на https://legacy.long-travel.live/blog.php?article=20180428_0501_Beregovo

**Actual result:**
Фотогалерея промежуточной точки Ресторан “Фламинго” **не соответствует** аналогичному контенту legacy

**Expected result:**
Фотогалерея промежуточной точки Ресторан “Фламинго” **соответствует** аналогичному контенту legacy

![image](https://user-images.githubusercontent.com/86321831/145722303-c96cfc48-1565-4612-9dbf-a00cc0b762e0.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
