### ISSUE TITLE
20180428_0501_beregovo - Фотогалерея блока Трофеи не соответствует legacy

### ISSUE THREAD

**Issue by yanadiya** [scholokov/long-travel-2#409]
**Steps to reproduce:**

1. Открыть страницу https://test.long-travel.live/20180428_0501_beregovo/
2. Найти блок Трофеи
3. Сравнить фотогалерею с аналогичным контентом на https://legacy.long-travel.live/blog.php?article=20180428_0501_Beregovo

**Actual result:**
Фотогалерея блока Трофеи **не соответствует** аналогичному контенту legacy

**Expected result:**
Фотогалерея блока Трофеи **соответствует** аналогичному контенту legacy

![image](https://user-images.githubusercontent.com/86321831/145722531-20363c96-fb40-4556-9006-68538bc9c8c2.png)

**Environment:**
Windows 10, Google Chrome v. 96.0.4664.45

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
присутствуют фотографии, не относящиеся к путешествию и блоку Трофеи

![image](https://user-images.githubusercontent.com/86321831/145726957-4e7f5aa0-541f-4c21-b964-a206a7163b14.png)

**Comment by scholokov** [comment]
fixed

**Comment by yanadiya** [comment]
проверено
