### ISSUE TITLE
20170513_putivl_kruti/In the Preview block the Period of the time is missing

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4092]
Steps to reproduce:
1. Open https://test.long-travel.live/20170513_putivl_kruti/
2. Scroll down to the Preview block
3. Pay attention to the Period of the time in the Preview block

Actual result: the Period of the time is missing
Expected result: the Period of the time is present

Requirements: https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6#12-%D0%BC%D0%B0%D0%BF%D0%B0

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/bf8119df-13a4-4098-8b79-eeceb540328b)

**Comment by ODrobik** [comment]
#3229

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
