### ISSUE TITLE
20200918_20_kharkiv Назва подорожі "Харків" розміщенна неправильно у правому куті прев'ю 

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4098]
Передумови:
Відкрити: https://test.long-travel.live/20200918_20_kharkiv/

Кроки для відтворення:
1. Зверніть увагу на прев'ю
2. Неправильно розміщена назва подорожі

Фактичний результат: назва подорожі "Харків" розміщенна неправильно у правому куті прев'ю 
Очікуваний результат: назва подорожі "Харків" розміщена в лівому куті прев ю

Середовище: Windows 10 Pro Операційна
система
Браузер: Google Chrome Version 110.0.5481.104
![Баг 01](https://github.com/scholokov/long-travel-2/assets/140165683/4750dea5-5f13-42fb-b0d1-0af92caa3953)

**Comment by irunabychkovska** [comment]
#4091

**Comment by scholokov** [comment]
буд ласка повторіть тестування з чистим кешом та куками

**Comment by irunabychkovska** [comment]
Баг відтворюється в режимі інкогніто.
![Screenshot_1](https://github.com/scholokov/long-travel-2/assets/140165683/34fc6f82-7121-468e-8693-1b1ded30a4b8)

**Comment by scholokov** [comment]
виправлено
