### ISSUE TITLE
20200918_20_kharkiv Зайвий URL  у полі прев' ю справа.

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4100]
Передумови:

Відкрити:
https://test.long-travel.live/20200918_20_kharkiv/

Кроки для відтворення:
1. Зверніть увагу на поле  прев'ю справа
2. присутній зайвий URL

Фактичний результат: 
в полі прев'ю присутній зайвий URL

Очікуваний результат: 
в полі прев'ю немає URL

Вимоги : https://github.com/scholokov/long-travel-2/blob/main/Requirements/Requirements.md

https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-27&mode=design&t=A7rqXA5xryD0LZqG-0

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![Баг 02](https://github.com/scholokov/long-travel-2/assets/140165683/be82d253-3365-4858-80e9-dcab72473419)

**Comment by irunabychkovska** [comment]
#4100

**Comment by irunabychkovska** [comment]
![Баг 02](https://github.com/scholokov/long-travel-2/assets/140165683/5cfe71d0-67ba-4d34-8c85-b9408f1c8b43)

**Comment by DmytroMarkulych** [comment]
Давайте скріншот розмістимо під Очікуваний результатом, а не на початку опису

**Comment by irunabychkovska** [comment]
Виправлено.

**Comment by DmytroMarkulych** [comment]
Вимоги після Очікуваного результату додайте будь ласка

**Comment by irunabychkovska** [comment]
Виправлено.

**Comment by scholokov** [comment]
виправлено
