### ISSUE TITLE
20200918_20_kharkiv В LightBox фото не перемикаються після клікання на стрілки.

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4103]
Передумови:

Відкрити: https://test.long-travel.live/20200918_20_kharkiv/#gallery[photonic-google-album-1]/AE29bMG5_2gwa7vL84OVb9yw-qn5vOTpN66HK94HQYfex9_2tOq6HouCeqo2gx3jzedcbHuRA24SJZhxC3suz8Kn_MTbEb8pjg/

Кроки для відтворення:
1.Прокрутити сторінку нижче карти.
2.Відкрити перше фото.
3.Натиснути стрілку вправо.
4.Натиснути стрілку вліво.

Фактичний результат: 
Фото не перемикаються після клікання на стрілки

Очікуваний результат: 
Фото перемикаються після клікання на стрілки

Вимоги : https://github.com/scholokov/long-travel-2/blob/main/Requirements/Requirements.md

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![Баг 05і](https://github.com/scholokov/long-travel-2/assets/140165683/93f05e71-506d-4598-b58d-7d65c8a93b1c)

**Comment by irunabychkovska** [comment]
#4091

**Comment by DmytroMarkulych** [comment]
Перед Summary додайте ID подорожі
Давайте перефразуємо Summary таким чином, щоб воно відповідало на питання Де? Що? Коли?

**Comment by DmytroMarkulych** [comment]
1. Давайте використаємо правило для Summary Де? Що? Коли? 
Приклад: В LightBox фото не перемикаються після клінкання на стрілки. 

2. Актуальний та очікувані результати можна написати наспуним чином:
Актуальний: Фото не перемикаються після клікання на стрілки
Очікуваний: Фото перемикаються після клікання на стрілки

3. Додайте посилання на документацію

**Comment by irunabychkovska** [comment]
Дякую, виправлено.

**Comment by DmytroMarkulych** [comment]
Додайте вимоги після очікуваного результату

**Comment by irunabychkovska** [comment]
Виправлено.

**Comment by scholokov** [comment]
виправлено

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
