### ISSUE TITLE
20200918_20_kharkiv Число переглянутих і непереглянутих фото у лівому верхньому куті не змінюється коли перегортати фото.

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4104]
Передумови:
Відкрити: 
https://test.long-travel.live/20200918_20_kharkiv/#gallery[photonic-google-album-1]/AE29bMG5_2gwa7vL84OVb9yw-qn5vOTpN66HK94HQYfex9_2tOq6HouCeqo2gx3jzedcbHuRA24SJZhxC3suz8Kn_MTbEb8pjg/

Кроки для відтворення:
1. відкрити фото
2. натиснути стрілку вправо
Фактичний результат: 
у лівому куті  не змінюється число переглянутих фото і через слеш, кількість непереглянутих

Очікуваний результат: 
у лівому куті з явиться число переглянутих фото і через слеш, кількість непереглянутих

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![Баг 06і](https://github.com/scholokov/long-travel-2/assets/140165683/5d1ad7bc-73ce-46df-add8-f5aacb6bb742)

**Comment by irunabychkovska** [comment]
#4091

**Comment by DmytroMarkulych** [comment]
1. Давайте перефразуємо Summary таким чином щоб воно відповідало на питання: Де? Що? Коли

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
