### ISSUE TITLE
20200918_20_kharkiv Дата подорожі розміщена під блоком прев'ю.

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4105]
Передумови:

Відкрити:
 https://test.long-travel.live/20200918_20_kharkiv/#gallery[photonic-google-album-1]/AE29bMFoYwoikkY0kd7GO1W_zAZ32Gm1ofJyAEPNQ7apGBloCJ5pu9ocJvs9TdTXKWUQxwhlBoC54SpP-gozeJcBSlauDnzUsA/

Кроки для відтворення:
1. Звернути увагу де розміщена дата

Фактичний результат: 
дата розташована нижче прев'ю зліва

Очікуваний результат: 
дата розташована  в блоці прев'ю зліва

 Вимоги : https://github.com/scholokov/long-travel-2/blob/main/Requirements/4.travel/travel.md

https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-27&mode=design&t=A7rqXA5xryD0LZqG-0

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![Баг 07](https://github.com/scholokov/long-travel-2/assets/140165683/e1b23cb5-dbee-46de-9ad8-b4e0fae18704)

**Comment by irunabychkovska** [comment]
#4091

**Comment by DmytroMarkulych** [comment]
Давайте сформуємо Summary таким чином щоб воно відповідало на питання Де? Що? КОли? 
Приклад: Дата подорожі розміщена під блоком прев'ю.

**Comment by DmytroMarkulych** [comment]
1. Немає такого блоку як "попереднього"
2. В очікуваному результаті, не поле, а блок
3. Додайте посилання на документацію

**Comment by irunabychkovska** [comment]
Виправлено.

**Comment by DmytroMarkulych** [comment]
Додайте вимоги після очікуваного результату

**Comment by irunabychkovska** [comment]
Виконано.

**Comment by scholokov** [comment]
виправлено

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
