### ISSUE TITLE
20200918_20_kharkiv Фото  міста  подорожі відсутнє на карті праворуч в маршруті.

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4106]
Передумови:

Відкрити:
https://test.long-travel.live/20200918_20_kharkiv/#gallery[photonic-google-album-1]/AE29bMFoYwoikkY0kd7GO1W_zAZ32Gm1ofJyAEPNQ7apGBloCJ5pu9ocJvs9TdTXKWUQxwhlBoC54SpP-gozeJcBSlauDnzUsA/

Кроки для відтворення:
1. Звернути увагу на карту справа, в маршруті немає фото міста подорожі.

Фактичний результат: 
відсутнє фото міста подорожі.

Очікуваний результат:  зображено фото міста подорожі.

 https://github.com/scholokov/long-travel-2/blob/main/Requirements/4.travel/travel.md

https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-27&mode=design&t=A7rqXA5xryD0LZqG-0

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![Баг 08і](https://github.com/scholokov/long-travel-2/assets/140165683/d5077666-02cc-4a21-bbb3-739b56424941)

**Comment by irunabychkovska** [comment]
#4091

**Comment by DmytroMarkulych** [comment]
Додайте посилання на документацію в опис баг репорту

**Comment by irunabychkovska** [comment]
Виправлено
![СКРІН ФІГМА 2](https://github.com/scholokov/long-travel-2/assets/140165683/3904789e-6fd9-471f-b609-d075ae5f3cec)

**Comment by DmytroMarkulych** [comment]
Це не передумова, це Вимоги:

**Comment by DmytroMarkulych** [comment]
Додайте вимоги після очікуваного результату

**Comment by irunabychkovska** [comment]
Виправлено.

**Comment by scholokov** [comment]
виконано

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
