### ISSUE TITLE
20200918_20_kharkiv Розірване підкреслення у назві блоку з фото

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4107]
Передумови: 

Відкрити: 
https://test.long-travel.live/20200918_20_kharkiv/#gallery%5Bphotonic-google-album-1%5D/AE29bMG5_2gwa7vL84OVb9yw-qn5vOTpN66HK94HQYfex9_2tOq6HouCeqo2gx3jzedcbHuRA24SJZhxC3suz8Kn_MTbEb8pjg/

Кроки для відтворення:
1. Звернути увагу на назву прев'ю перед блоком з фото 

Фактичний результат:  підкреслення назви розірвано

Очікуваний результат: 
підкреслення назви  без розриву.

Вимоги: https://github.com/scholokov/long-travel-2/blob/main/Requirements/4.travel/travel.md

https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-27&mode=design&t=A7rqXA5xryD0LZqG-0

Середовище: Windows 10  Операційна
система:

Браузер: Google Chrome Version 110.0.5481.104

![Баг 09](https://github.com/scholokov/long-travel-2/assets/140165683/3a0d0bdf-75c4-4748-87bf-aa9d1b7b6686)

**Comment by irunabychkovska** [comment]
#4091

**Comment by DmytroMarkulych** [comment]
Додайте посилання на документацію в опис баг репорту

**Comment by irunabychkovska** [comment]
![figma вимоги](https://github.com/scholokov/long-travel-2/assets/140165683/db2111d5-db7e-4b95-85a3-8f6ff713a4a3)

**Comment by DmytroMarkulych** [comment]
Вимоги варто писати не в передумови, а окремим блоком: Вимоги

**Comment by irunabychkovska** [comment]
Дякую, виправлено.

**Comment by DmytroMarkulych** [comment]
Додайте вимоги після очікуваного результату

**Comment by irunabychkovska** [comment]
Виправлено.

**Comment by DmytroMarkulych** [comment]
І воно не розірване, бо так відображається підкреслювання лінки)

**Comment by irunabychkovska** [comment]
візуально розірвано, має бути суцільне підкреслення, чи ні?

**Comment by scholokov** [comment]
ні, це такий дизайн. тобто все ок  :)

**Comment by irunabychkovska** [comment]
дякую, зрозуміло

**Comment by DmitriiNasonov** [comment]
bug-report is canceled
