### ISSUE TITLE
20170612_buki/The type of  a photo gallery of the block "Butsky canyon. Buky" is random

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4109]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170612_buki/

2. Scroll down to the block Butsky canyon. Buky.

3. Pay attention to the type of a photo gallery.

**Actual result:**
The type of  a photo gallery of the block "Butsky canyon. Buky" is random.

**Expected result:**
The type of  a photo gallery of the block "Butsky canyon. Buky" is mosaic

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/blob/main/Requirements/4.travel/travel.md#133-%D0%B3%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%8F-%D0%B7-%D1%84%D0%BE%D1%82%D0%BE-%D1%82%D0%B0-%D0%B2%D1%96%D0%B4%D0%B5%D0%BE

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/900e4d04-4c6a-4529-ae10-25e17c47323f)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/58e1e2c4-254f-4900-ab74-9a04078fd853)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
