### ISSUE TITLE
20170612_buki/The type of a photo gallery of the block "Road Buky - Kyiv" is random

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4110]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170612_buki/

2. Scroll down to the block Road Buky - Kyiv.

3. Pay attention to the type of a photo gallery.

**Actual result:**
The type of a photo gallery of the block "Road Buky - Kyiv" is random

**Expected result:**
The type of a photo gallery of the block "Road Buky - Kyiv" is mosaic

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/blob/main/Requirements/4.travel/travel.md#133-%D0%B3%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%8F-%D0%B7-%D1%84%D0%BE%D1%82%D0%BE-%D1%82%D0%B0-%D0%B2%D1%96%D0%B4%D0%B5%D0%BE

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/b44f5f96-fc2b-4127-9264-aa71414499f7)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/79af0146-093b-4d0f-a30a-62a8e81cd31d)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
