### ISSUE TITLE
20200918_20_kharkiv Кнопка "Відобразити галерею" не відображається після завантаження першої галереї .

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4118]
Передумови:

Відкрити: https://test.long-travel.live/20200918_20_kharkiv/#gallery[photonic-google-album-1]/AE29bMEUijXWcXHCUmqaIaNkbkmdxpsxd70_lmv3uIUcUvBkChGdxZILbRxWd20wwN4vfSQ9he2z56pO0NF4xTHyH9soDtYktQ/

Кроки для відтворення: 
1. прогорнути завантажені фото першого блоку Галерея
2. натиснути кнопку "Відобразити галерею"

Фактичний результат: завантажились всі фото  відразу

Очікуваний результат: 
після другого прев'ю фото, відображається кнопка  "Відобразити галерею"

Вимоги: https://github.com/scholokov/long-travel-2/blob/main/Requirements/4.travel/travel.md

https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-27&mode=design&t=A7rqXA5xryD0LZqG-0
 
Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![Screenshot_9](https://github.com/scholokov/long-travel-2/assets/140165683/81130cdf-13d5-4d23-b4bf-1879ff6eccc4)

![Screenshot_10](https://github.com/scholokov/long-travel-2/assets/140165683/5f5781d1-ef19-4351-bfde-0129aa2ac99d)

**Comment by irunabychkovska** [comment]
#4091

**Comment by DmytroMarkulych** [comment]
Додайте посилання на вимоги після Очікуваного результату

**Comment by irunabychkovska** [comment]
Виправлено.

**Comment by scholokov** [comment]
виправлено
