### ISSUE TITLE
20200918_20_kharkiv Відсутній прапор України у прев'ю фото ліворуч.

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4119]
Передумови:

Відкрити: 
https://test.long-travel.live/20200918_20_kharkiv/#gallery[photonic-google-album-1]/AE29bMEUijXWcXHCUmqaIaNkbkmdxpsxd70_lmv3uIUcUvBkChGdxZILbRxWd20wwN4vfSQ9he2z56pO0NF4xTHyH9soDtYktQ/

Кроки для відтворення:
1. Прогорнути сторінку до першого прев'ю фото
2. Звернути увагу на  блок прев'ю ліворуч

Фактичний результат: 
відсутній прапор України

Очікуваний результат: 
зображений прапор

Вимоги: 
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-27&mode=design&t=A7rqXA5xryD0LZqG-0

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![Screenshot_11](https://github.com/scholokov/long-travel-2/assets/140165683/410c1582-c22a-4f25-83d7-834b3077ec55)

![Screenshot_12](https://github.com/scholokov/long-travel-2/assets/140165683/44b22522-1328-4854-bc70-00082d12bb8f)

**Comment by irunabychkovska** [comment]
#4091

**Comment by irunabychkovska** [comment]
Виправлено.

**Comment by scholokov** [comment]
виправлено

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
