### ISSUE TITLE
20130613_0628_Bulgaria/Error(Invalid argument supplied for foreach) of travel page.

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#4120]
**Steps to reproduce:**
Open page <https://test.long-travel.live/20130613_0628_Bulgaria/>

**Actual result:**
Error and large window size of travel page title

**Expected result:**
No Error and Normal Window Size Travel Page Header

**Environment:**
MacBook/macOS Sonoma 14/Safari Version 17.0 (19616.1.24.11.3)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/ed9e3909-4ec7-4080-9e39-aad7420d09d0)

**Comment by SerhiiBurdieiev** [comment]
The title was changed.

**Comment by scholokov** [comment]
виправлено

**Comment by SerhiiBurdieiev** [comment]
Error remained unchanged.

**Comment by DmytroMarkulych** [comment]
додайте скрін до коментаря, що баг відтворюється
