### ISSUE TITLE
20170722_boguslav/The text "Чайки, Богуславський район, Київська область, Україна. 22.07.2017" is dublicated information

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4121]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170722_boguslav/
2. Scroll down to below the global map.
3. Pay attention to the text "Чайки, Богуславський район, Київська область, Україна. 22.07.2017".

**Actual result:**
The text "Чайки, Богуславський район, Київська область, Україна. 22.07.2017" is dublicated information

**Expected result:**
The text "Чайки, Богуславський район, Київська область, Україна. 22.07.2017" is missing

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/852f062b-9712-4116-adc4-232d5747ef27)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
