### ISSUE TITLE
/20200627_29_yuzhniy/ The PHP`s Error message is displayed in the page header

### ISSUE THREAD

**Issue by dimdim1978** [scholokov/long-travel-2#4123]
1. Open the page https://test.long-travel.live/20200627_29_yuzhniy/
2. Pay attention at the header

Actual result:
   The page header HAS PHP`s error message

Expected result:
    The page header HAS NO PHP`s error message

Reproduction:Always

Environment: Win 11 (x64) Browsers: Opera One(version: 101.0.4843.33) 
                                                            Edge version 115.0.1901.200 
                                                            Firefox 116.0.2 
                                                            Chrome 115.0.5790.171

P.S. Because of the error the header is having incorrect view 

![Image](https://github.com/scholokov/long-travel-2/assets/117273408/822c6428-d839-4694-97c2-7ff86212f43b)

**Comment by DmytroMarkulych** [comment]
Додайте скрін в кінці баг репорту
