### ISSUE TITLE
20170722_boguslav/The text "Богуславський район, Київська область, Україна." need move to the previewis dublicated information

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4125]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20170722_boguslav/
2. Scroll down to the preview.
3. Pay attention to the text "Чайки, Богуславський район, Київська область, Україна. 22.07.2017".

**Actual result:**
The preview text is "Чайки. 22.07.2017".

**Expected result:**
The preview text is "Чайки, Богуславський район, Київська область, Україна. 22.07.2017". The text "Чайки, Богуславський район, Київська область, Україна. 22.07.2017" beetwen preview and global map is missing.

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://github.com/scholokov/long-travel-2/blob/main/Requirements/4.travel/travel.md

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/ab713a53-3619-4264-b3b6-318ec67b619f)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/616166ad-3b7d-4e38-9e97-3d4bebdf7d90)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
