### ISSUE TITLE
20170521_korosten / Photo gallery's type of the block "Військово-історичний комплекс “Скеля”" is random

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4133]
**Steps to reproduce:**
1. Open https://test.long-travel.live/20170521_korosten/
2. Scroll down to the block "Військово-історичний комплекс “Скеля”".
3. Pay attention to the type of photo gallery.

**Actual result:**
Photo gallery's type of the block "Військово-історичний комплекс “Скеля”" is random.

**Expected result:**
Photo gallery's type of the block "Військово-історичний комплекс “Скеля”"  is mosaic.

**Requirements:** https://github.com/scholokov/long-travel-2/blob/main/Requirements/4.travel/travel.md#133-%D0%B3%D0%B0%D0%BB%D0%B5%D1%80%D0%B5%D1%8F-%D0%B7-%D1%84%D0%BE%D1%82%D0%BE-%D1%82%D0%B0-%D0%B2%D1%96%D0%B4%D0%B5%D0%BE

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://github.com/scholokov/long-travel-2/assets/101987790/b3ae8930-01dc-43e0-b1ff-67cebcd03ebb)

**Comment by GNatala** [comment]
#3230

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
