### ISSUE TITLE
20170521_korosten /  Text in the name of the block "Військово-історичний комплекс “Скеля”, Коростень Житомирская область, Украина" is written in russian 

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4135]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170521_korosten/
2. Pay attention to the block "Військово-історичний комплекс “Скеля”, Коростень Житомирская область, Украина".

**Actual Result:** 
The name of the city, region "Коростень Житомирская область, Украина" is written in russian.

**Expected Result:** 
The name of the city, region "Коростень Житомирская область, Украина" is written in Ukrainian.

**Additional information:**
https://github.com/scholokov/long-travel-2/blob/main/Requirements/1.overall/language.md

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/5d671631-a92d-480b-9975-32879c1805c6)

**Comment by GNatala** [comment]
#3230

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
