### ISSUE TITLE
20170521_korosten / Name of the Videos is in English in block "Військово-історичний комплекс “Скеля”"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4136]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170521_korosten/
2. Pay attention to the name of the Videos is in English in block "Військово-історичний комплекс “Скеля”".

**Actual result:**
Name of the Videos is in English in block "Військово-історичний комплекс “Скеля”"

**Expected result:**
**Name of the Videos is in Ukrainian** in block "Військово-історичний комплекс “Скеля”"

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/a2c24b40-79b3-47aa-a232-2ad82a025934)

**Comment by GNatala** [comment]
#3230

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/long-travel-2/assets/88647733/5a29e4eb-3725-43e2-9eb4-61d843a2f0a0)

**Comment by GNatala** [comment]
Дякую, виправила

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
