### ISSUE TITLE
https://test.long-travel.live/ При натисканні на відвідувану країну сторінка з переліком подорожей, в яких згадана дана країна, не відкривається.

### ISSUE THREAD

**Issue by BohdanaProtsyk** [scholokov/long-travel-2#4144]
Передумови: https://github.com/scholokov/long-travel-2/blob/main/Requirements/home/map-politic.md

Відкрити: https://test.long-travel.live

Кроки для відтворення:
1. Зверніть увагу на  карту відвідуваних країн.
2.  Натисніть на країні Боснія і Герцеговина, що позначена блакитним кольором.

Фактичний результат: При натисканні на відвідувану країну Боснія і Герцеговина сторінка з переліком подорожей, в яких згадана дана країна, не відкривається.
Очікуваний результат: При натисканні на відвідувану країну Боснія і Герцеговина сторінка з переліком подорожей, в яких згадана дана країна, відкривається.

Середовище: Windows Операційна
система: 11 Home
Браузер: Google Chrome Version 115.0.5790.111 (Офіційне складання) (64-розрядна версія)

![баг10](https://github.com/scholokov/long-travel-2/assets/137249772/10af3522-0318-4720-935c-fdae7b2036c6)

**Comment by BohdanaProtsyk** [comment]
#4082

**Comment by DmytroMarkulych** [comment]
Давайте вкажемо конкретно яка країна

**Comment by BohdanaProtsyk** [comment]
виправила
