### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - Road "Kyiv - Svityaz" flag width26 height18

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#4145]
**Steps to playback:**

1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Scroll to the standard block of the road "Kyiv - Svityaz"
3. Pay attention to the flag

**Actual result:**
flag width26 height18

**Expected result:**
flag width36 height24
![фігма прапор width36рх height24рх](https://github.com/scholokov/long-travel-2/assets/132911639/9415726b-c979-4c7b-ab4f-da9ff665f91f)

Environment:
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![прапор Київ - Світязь 26 баг](https://github.com/scholokov/long-travel-2/assets/132911639/5b117114-be99-4d44-85fc-d068fed1c4fd)

**Comment by Artem-16** [comment]
#3086

**Comment by scholokov** [comment]
виправлено
