### ISSUE TITLE
Create decomposition in Miro 

### ISSUE THREAD

**Issue by ABatalov** [scholokov/long-travel-2#4146]
We need to create decomposition of our project Long Travel in Miro. 

You can use this sample from our Widiq project: 

![image-20230804-120515](https://github.com/scholokov/long-travel-2/assets/72439798/e79805c7-6b48-4f60-b0ec-440fce8abf8b)
![image-20230805-122949](https://github.com/scholokov/long-travel-2/assets/72439798/16f6f494-4bb4-46d9-9917-a1e8876f2cc3)

**Comment by ODrobik** [comment]
https://miro.com/app/board/uXjVMutfGFY=/
![image](https://github.com/scholokov/long-travel-2/assets/123776698/557cd641-6058-4a5e-9ed3-5a726849d64b)

**Comment by DmitriiNasonov** [comment]
https://miro.com/app/board/uXjVM7AGm_s=/?share_link_id=879397833847
![Mind Maps, Visual Workspace for Innovation - Google Chrome 11 10 2023 14_17_38](https://github.com/scholokov/long-travel-2/assets/95171672/3e26962c-9fd0-4de5-97cc-33a84a570904)

**Comment by DmitriiNasonov** [comment]
task completed
