### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - Photo gallery road "Kyiv - Svityaz"  value key layout=random

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#4147]
**Steps to playback:**

1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Scroll to down
3. Photo gallery road "Kyiv - Svityaz"
4. Open dev tools

**Actual result:**
Value key layout=random

**Expected result:**
Value key layout=mosaic
![Вимоги фотогалерея](https://github.com/scholokov/long-travel-2/assets/132911639/32bddd12-c6cb-4704-896c-6545a4ee0f86)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![фото галерея перша](https://github.com/scholokov/long-travel-2/assets/132911639/0ccc9781-2b65-47a2-adf2-3c5ed4460a72)

**Comment by Artem-16** [comment]
#3086

**Comment by DmytroMarkulych** [comment]
Додайте деталей в Summary

**Comment by scholokov** [comment]
виправлено
