### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - Slideshow road "Kyiv - Svityaz"

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#4148]
**Steps to playback:**

1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Scroll to down
3. Photo gallery road "Kyiv - Svityaz"
4. Open photo
5. In the upper left corner, click the "Play" button

**Actual result:**
 The slideshow displays the first and second photos

**Expected result:**
Slideshow  display all photos

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![дорога київ - світязь слайдшоу](https://github.com/scholokov/long-travel-2/assets/132911639/afff8f96-d92e-4884-91bd-f25e0c6dca14)
![дорога київ - свитязь слайдшоу 2](https://github.com/scholokov/long-travel-2/assets/132911639/c49c495d-1608-4b7c-bffb-cf4e4636c262)

**Comment by Artem-16** [comment]
#3086

**Comment by DmytroMarkulych** [comment]
додайте деталей в баг репорт
