### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - Lake "Svityaz" flag width26 height18

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#4149]
**Steps to playback:**

1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Scroll to the standard block of the Lake "Svityaz"
3. Pay attention to the flag

**Actual result:**
flag width26 height18

**Expected result:**
flag width36 height24
![фігма прапор width36рх height24рх](https://github.com/scholokov/long-travel-2/assets/132911639/4d91c0f6-4b06-4204-b8ed-6329d986f4f7)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![Озеро прапор 26рх](https://github.com/scholokov/long-travel-2/assets/132911639/f007d82f-c459-44c1-b489-2c1f301288f5)

**Comment by Artem-16** [comment]
#3086

**Comment by scholokov** [comment]
виправлено
