### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - Slideshow Lake Svityaz shows not all photos

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#4150]
**Steps to playback:**

1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Scroll to down
3. Photo gallery Lake "Svityaz"
4. Open photo
5. In the upper left corner, click the "Play" button

**Actual result:**
The slideshow displays the first and second photos

**Expected result:**
Slideshow display all photos

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![озеро слайдшоу](https://github.com/scholokov/long-travel-2/assets/132911639/51c7e690-963e-4f9e-b6d9-20ef1aae1b0d)
![озеро слайдшоу 2](https://github.com/scholokov/long-travel-2/assets/132911639/15d5ce37-a28f-4533-8cc0-690528a93473)

**Comment by Artem-16** [comment]
#3086

**Comment by DmytroMarkulych** [comment]
Додайте деталей в баг репорт та summary

**Comment by scholokov** [comment]
please retest
