### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - Photo gallery Lake "Svityaz" value key layout=random

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#4151]
**Steps to playback:**

1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Scroll to down
3. Photo gallery Lake "Svityaz"
4. Open dev tools

**Actual result:**
Value key layout=random

**Expected result:**
Value key layout=mosaic
![Вимоги фотогалерея](https://github.com/scholokov/long-travel-2/assets/132911639/6b293def-e84e-48fa-b891-3a5f3771139b)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![фото галерея два](https://github.com/scholokov/long-travel-2/assets/132911639/009e8b25-df0d-4e32-84a7-9e5ee61d9780)

**Comment by Artem-16** [comment]
#3086

**Comment by DmytroMarkulych** [comment]
Додайте деталей в баг репорт та summary

**Comment by scholokov** [comment]
виправлено
