### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region - Slideshow recreation center "Svityaz"

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#4154]
**Steps to playback:**

1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Scroll to down
3. Photo gallery recreation center "Svityaz"
4. Open photo
5. In the upper left corner, click the "Play" button

**Actual result:**
Slideshow fails to display all photos

**Expected result:**
Slideshow to display all photos

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![база відпочинку слайдшоу](https://github.com/scholokov/long-travel-2/assets/132911639/ee0b2b63-9ef7-4261-9678-1204d5db6557)
![база слайдшоу 2](https://github.com/scholokov/long-travel-2/assets/132911639/f96da784-4af3-40be-bea2-75c06204aba3)

**Comment by scholokov** [comment]
функціонал слайд шоу прибраний
