### ISSUE TITLE
GitHub Projects - Travel - Task/Issue - "Component" - Component "Цікаві місця" is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4157]
**Steps of reproducing**
1. Open https://github.com/users/scholokov/projects/4/views/3
2. Open any issue or task
3. Click to "Component" block

**Actual Result**
Component "Цікаві місця" is missing

**Expected Result**
Component "Цікаві місця" is present

**Additional information**
https://test.long-travel.live/places/

**Enviroments**
Windows 10, Chrome 115.0.5790.171 (64 bit)
![Figma - Design of the _Цікаві місця_ page is missing · Travel - Google Chrome 09 08 2023 15_59_45](https://github.com/scholokov/long-travel-2/assets/95171672/5330b75c-1bfb-4bfa-8621-34aec17d1619)

**Comment by DmitriiNasonov** [comment]
#4129

**Comment by scholokov** [comment]
додано

**Comment by DmitriiNasonov** [comment]
Checked. bug isn't reproduced
