### ISSUE TITLE
20170513_putivl_kruti/In the Preview block the text "Warning: Invalid argument supplied for foreach() in /home/qaxcamp/long-travel.live/test/wp-content/themes/mts_myblog/single.php on line 44"is present

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4160]
Steps to reproduce:

1. Open https://test.long-travel.live/20170513_putivl_kruti/
2. Scroll down to the Preview block
3. Pay attention to the Text in the Preview block

Actual result: the text "Warning: Invalid argument supplied for foreach() in /home/qaxcamp/long-travel.live/test/wp-content/themes/mts_myblog/single.php on line 44" is present
Expected result: the text "Warning: Invalid argument supplied for foreach() in /home/qaxcamp/long-travel.live/test/wp-content/themes/mts_myblog/single.php on line 44" is missing

Requirements:https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1201%3A41&mode=dev

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/47d31cf9-7718-4bea-9356-af77a033c2c4)

**Comment by ODrobik** [comment]
#3229

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/long-travel-2/assets/88647733/9d101013-387d-4260-8a1f-e5afae3f6906)

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
