### ISSUE TITLE
20170513_putivl_kruti/Under the preview block, the lines of text are present 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4161]
Steps to reproduce:
1. Open https://test.long-travel.live/20170513_putivl_kruti/
2. Scroll down to the Preview block
3. Pay attention to the Text under  the Preview block

Actual result: the lines of text are present  under  the Preview block
Expected result: the lines of text are missing  under  the Preview block

Requirements:https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=1201%3A41&mode=dev

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/e96f1d2f-29b7-468b-80cc-0150a4e24fdd)

**Comment by ODrobik** [comment]
#3229

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/long-travel-2/assets/88647733/5af54242-c70f-49b9-ac48-ee762cd57e6f)

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
