### ISSUE TITLE
20160710_0807_italy_odessa/ unclear link in preview

### ISSUE THREAD

**Issue by BondarAnatolii** [scholokov/long-travel-2#4165]
Pre-conditions:
Open: https://test.long-travel.live/20160710_0807_italy_odessa/

Steps to reproduce:
Open the page

Actual result:
Unclear link in preview "Warning: Invalid argument supplied for foreach() in /home/qaxcamp/long-travel.live/test/wp-content/themes/mts_myblog/single.php on line 44"

Expected result:
There must be no links in the preview

Environment:
system: Windows 10 Home
Browser: Firefox 116.0.2 (64-bit)

Attachment:
![01](https://github.com/scholokov/long-travel-2/assets/88820108/2602fa09-b3be-4a88-a08d-1a668d312935)

**Comment by DmytroMarkulych** [comment]
Атрибут Priority виставляє PM

**Comment by BondarAnatolii** [comment]
Зрозумів. Надалі це поле не буду заповнювати.

**Comment by scholokov** [comment]
fixed
