### ISSUE TITLE
Achievement - Сheck the student's personal progress on the achievements page

### ISSUE THREAD

**Issue by ABatalov** [scholokov/long-travel-2#4169]
We need to check the student's personal progress on the achievements page.
Please check availability of requirements, functional compliance and design compliance.

Environment: https://www.qax-camp.com.ua/ach-travel/ 

Requirements: https://github.com/scholokov/qax-portal-2/wiki/8.0-%D0%90%D1%87%D1%96%D0%B2%D0%BA%D0%B8

![259967357-55441d02-5dce-450a-a8af-3e55489c819a](https://github.com/scholokov/long-travel-2/assets/72439798/5f22467e-0d6f-4765-bcc3-70073b6e6849)

**Comment by Illia2810** [comment]
перевірено
