### ISSUE TITLE
20201010_11_brech - Header - Unclear link

### ISSUE THREAD

**Issue by BondarAnatolii** [scholokov/long-travel-2#4171]
Pre-conditions:
Open: https://test.long-travel.live/20201010_11_brech/

Steps to reproduce:
Open the page

Actual result:
Unclear link in preview "Warning: Invalid argument supplied for foreach() in /home/qaxcamp/long-travel.live/test/wp-content/themes/mts_myblog/single.php on line 44"

Expected result:
There must be no links in the preview

Environment:
system: Windows 10 Home
Browser: Firefox 116.0.2 (64-bit)

Attachment:
![Image](https://github.com/scholokov/long-travel-2/assets/88820108/b593c2dc-c9d2-4085-820c-270737b52ec9)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/long-travel-2/assets/88647733/a5b3739b-748c-458d-a8aa-26bc996666bb)

**Comment by DmytroMarkulych** [comment]
Priority виставляє PM, а не QA

**Comment by BondarAnatolii** [comment]
Добре. Зрозумів на рахунок Priority

**Comment by scholokov** [comment]
виконано

**Comment by BondarAnatolii** [comment]
перевірено
