### ISSUE TITLE
20201010_11_brech - Header - The name of the trip contains an restricted symbol "underscore"

### ISSUE THREAD

**Issue by BondarAnatolii** [scholokov/long-travel-2#4172]
Pre-conditions:
Open: https://test.long-travel.live/20201010_11_brech/

Steps to reproduce:
Open the page

Actual result:
The name of the trip contains an restricted symbol "underscore"  
"Бречь_Чернігівська область_Україна"

Expected result:
The trip name must not contain an underscore character

Environment:
System: Windows 10 Home
Browser: Firefox 116.0.2 (64-bit)

Attachment:
![Image](https://github.com/scholokov/long-travel-2/assets/88820108/02d7613a-c003-423c-a2e9-fa6e0cc70cbb)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/long-travel-2/assets/88647733/0b77bb77-a1d9-49c7-9c45-e50f566c7663)

**Comment by BondarAnatolii** [comment]
Need help filling out the data fields correctly?

**Comment by BondarAnatolii** [comment]
Updated requested information

**Comment by DmytroMarkulych** [comment]
Priority виставляє РМ а не QA

**Comment by scholokov** [comment]
виконано

**Comment by BondarAnatolii** [comment]
перевірено
