### ISSUE TITLE
20180708_boguslav/Error(Invalid argument supplied for foreach) of travel page.

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#4176]
**Steps to reproduce: **
Open page <https://test.long-travel.live/20180708_boguslav/>

**Actual result:**
 Error and large window size of travel page title

**Expected result: **
No Error and Normal Window Size Travel Page Header

**Environment: **
MacBook/macOS Sonoma 14/Safari Version 17.0 (19616.1.26.11.3)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/9fdd17d1-6a2e-4059-a33e-02c34a833457)

**Comment by scholokov** [comment]
виправлено
