### ISSUE TITLE
20200814_15_serhiivka Відсутня дата під назвою подорожі у прев'ю

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4180]
Передумови:
Відкрити: 
https://test.long-travel.live/20200814_15_serhiivka/

Кроки для відтворення:
1. Звернути увагу на дату 

Фактичний результат: 
під назвою подорожі відсутня дата 

Очікуваний результат: 
Відображається дата під назвою подорожі: 14-15.08.2020

Вимоги:  
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-6&mode=design&t=NET2wWepYqBTnAEw-0

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![сергіївка1](https://github.com/scholokov/long-travel-2/assets/140165683/55697e37-5e57-4d1c-989c-25fc46238808)

**Comment by irunabychkovska** [comment]
#4088

**Comment by DmytroMarkulych** [comment]
Додайте будь ласка точну дату в очікуваний результат. її можна знайти в специфікації

**Comment by irunabychkovska** [comment]
Виправлено.

**Comment by scholokov** [comment]
виконано

**Comment by ODrobik** [comment]
виправлено
