### ISSUE TITLE
20200814_15_serhiivka Не відображається фото в прев'ю на задньому плані

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4181]
Передумови:
Відкрити:
 https://test.long-travel.live/20200814_15_serhiivka/

Кроки для відтворення:
1. Звернути увагу на відображення фото в превю

Фактичний результат: 
Фото не відображається

Очікуваний результат:
фото відображається

Вимоги: 
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-6&mode=design&t=w1jm2gyadboms1lE-0

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![Сергіївка2](https://github.com/scholokov/long-travel-2/assets/140165683/1cd2681f-f0cb-48b0-a249-613695b2577d)

**Comment by irunabychkovska** [comment]
#4088

**Comment by scholokov** [comment]
виконано

**Comment by ODrobik** [comment]
виправлено
