### ISSUE TITLE
20200814_15_serhiivka Тег автомобіля не відображаються у лівому куті прев'ю

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4182]
Передумови:
Відкрити: 
https://test.long-travel.live/20200814_15_serhiivka/

Кроки для відтворення:
Звернути увагу на розміщення тега

Фактичний результат: 
тег автомобіля не відображається у лівому верхньому куті прев'ю

Очікуваний результат:
тег автомобіля відображаються у лівому верхньому куті прев'ю

Вимоги: 
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-6&mode=design&t=69acJjx2reWRA3YY-0

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![сергіївка 4](https://github.com/scholokov/long-travel-2/assets/140165683/4dd74cbc-8821-4033-a934-3a2c165406e8)

**Comment by DmytroMarkulych** [comment]
Вкажіть які саме теги

**Comment by irunabychkovska** [comment]
Виправлено.

**Comment by scholokov** [comment]
виконано

**Comment by ODrobik** [comment]
виправлено
