### ISSUE TITLE
20200814_15_serhiivka Зайвий URL у блоці прев'ю

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4183]
Передумови:
Відкрити:
https://test.long-travel.live/20200814_15_serhiivka/

Кроки для відтворення:
1. Звернути увагу на зайвий URL у превю

Фактичний результат: 
відображається URL

Очікуваний результат:
не відображається  URL

Вимоги:
 https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-6&mode=design&t=z8YYYM7hoR481GIC-0

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![Сергіївка 5](https://github.com/scholokov/long-travel-2/assets/140165683/da879e0b-a343-49d8-a5c0-5f702032b8e8)

**Comment by irunabychkovska** [comment]
#4088

**Comment by DmytroMarkulych** [comment]
рев'ю?

**Comment by irunabychkovska** [comment]
прев'ю

**Comment by scholokov** [comment]
виконано

**Comment by ODrobik** [comment]
виправлено
