### ISSUE TITLE
20201010_11_brech - Header - Trip name is "Бречь"

### ISSUE THREAD

**Issue by BondarAnatolii** [scholokov/long-travel-2#4187]
Pre-conditions:
Open: https://test.long-travel.live/20201010_11_brech/

Steps to reproduce:
Open the page

Actual result:
Trip name is "Бречь"
https://github.com/scholokov/long-travel-2/wiki/3.1-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%9F%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA 

Expected result:
Name should be "Бреч"

Environment:
system: Windows 10 Home
Browser: Firefox 116.0.2 (64-bit)

Attachment:
![03](https://github.com/scholokov/long-travel-2/assets/88820108/84796a0f-dc8d-47b5-b12d-299de42d1cec)

**Comment by DmytroMarkulych** [comment]
Давайте не будемо використовувати слово  wrong, а замінимо його на більш конкретне.
Атрибут Priority виставляється РМ а не QA

**Comment by BondarAnatolii** [comment]
Замінив слово  wrong на incorrect 
Прийняв до уваги і обнулив поле Priority

**Comment by DmytroMarkulych** [comment]
Якщо ми напишемо: Name trip is "Бречь" - то в такому формулюванні все зрозуміло що тут не так і що не коректно

**Comment by DmytroMarkulych** [comment]
без incorrect та wrong

**Comment by scholokov** [comment]
fixed

**Comment by BondarAnatolii** [comment]
перевірено
