### ISSUE TITLE
20201010_11_brech - Trip name is "Бречь" in the broswer title tab

### ISSUE THREAD

**Issue by BondarAnatolii** [scholokov/long-travel-2#4188]
Pre-conditions:
Open: https://test.long-travel.live/20201010_11_brech/

Steps to reproduce:
Open the page

Actual result:
Trip name is "Бречь" in the broswer title tab 
https://github.com/scholokov/long-travel-2/wiki/3.1-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6%D1%96.-%D0%9F%D0%B5%D1%80%D0%B5%D0%BB%D1%96%D0%BA

Expected result:
Name in the title tab should be "Бреч"

Environment:
system: Windows 10 Home
Browser: Firefox 116.0.2 (64-bit)

Attachment:
![04](https://github.com/scholokov/long-travel-2/assets/88820108/026d0f61-02df-4d18-acb9-3ac0ddbee031)

**Comment by DmytroMarkulych** [comment]
Давайте замінимо слово wrong на конкретне що маємо по факту
Атрибут Priority виставляється РМ а не QA

**Comment by BondarAnatolii** [comment]
Згоден - Incorrect name думаю буде більш правильним.
Прийняв до уваги і даю слово більше не заповнювати поле Priority

**Comment by DmytroMarkulych** [comment]
ми можемо вказати точну назву замість слів wrong та incorrect

**Comment by BondarAnatolii** [comment]
Оновив інформацію стосовно назви міста

**Comment by scholokov** [comment]
fixed

**Comment by BondarAnatolii** [comment]
verified
