### ISSUE TITLE
20201010_11_brech Trip name contains restricted "underscore" character in browser title tab

### ISSUE THREAD

**Issue by BondarAnatolii** [scholokov/long-travel-2#4189]
Pre-conditions:
Open: https://test.long-travel.live/20201010_11_brech/

Steps to reproduce:
Open the page

Actual result:
The name of the trip contains an restricted symbol "underscore" in title tab
"Бречь_Чернігівська область_Україна"

Expected result:
The trip name must not contain an underscore character

Environment:
System: Windows 10 Home
Browser: Firefox 116.0.2 (64-bit)

Attachment:
![05](https://github.com/scholokov/long-travel-2/assets/88820108/909b8220-0ed8-4c97-a77d-1dbf1fa00d59)

**Comment by DmytroMarkulych** [comment]
Атрибут Priority виставляється РМ а не QA

**Comment by BondarAnatolii** [comment]
Добре. Прибрав параметр Priority

**Comment by BondarAnatolii** [comment]
перевірено
