### ISSUE TITLE
20201010_11_brech Gallery-Video-Rotated 90 degrees to the right when playing video

### ISSUE THREAD

**Issue by BondarAnatolii** [scholokov/long-travel-2#4190]
Pre-conditions:
Open: https://test.long-travel.live/20201010_11_brech/

Steps to reproduce:
1) Open the page
2) Scroll down to the second gallery on the page
3) Open the second video in gallery
4) Pay attention to video orientation

Actual result:
Video in the gallery is played with Portrait orientation
Reproduces only with this video

Expected result:
Video in the gallery are played with Landscape orientation

Environment:
system: Windows 10 Home
Browser: Firefox 116.0.2 (64-bit)

Attachment:
![06](https://github.com/scholokov/long-travel-2/assets/88820108/e5d536c7-8773-4de5-9c68-7c0e1e030037)

https://github.com/scholokov/long-travel-2/assets/88820108/13e4f7df-e27c-4729-bbaf-b25cff2e0961

**Comment by scholokov** [comment]
20201010_11_brech Video in the gallery are played rotated 90 degrees to the right #4190
орієнтація неправильна тільки коли "програється", чи одразу коли відкривається. з бага це незрозуміло

**Comment by scholokov** [comment]
чому саме "Open second video". на першому все ок? тобто проблема глобальна чи тільки у другому відео?

**Comment by scholokov** [comment]
коли фото чи відео отак відкривається - цей режим називається LightBox

**Comment by scholokov** [comment]
20201010_11_brech Video in the gallery are played rotated 90 degrees to the right

тайтл для більш прискоренного сприйняття можна переробити у вигляд:
20201010_11_brech - Galley - Video - Rotated 90 degrees to the right

буде коротше і скоріше сприймається

**Comment by scholokov** [comment]
треба проставляти спринт
<img width="917" alt="image" src="https://github.com/scholokov/long-travel-2/assets/22824947/827502b9-acd5-4ab7-8c58-1d2ce2221e31">

**Comment by scholokov** [comment]
Actual result:
Video in the gallery are played rotated 90 degrees to the right when playing video

Expected result:
Video in the gallery are played with normal orientation

у даному випадку не зрозуміле поняття "normal oriented"
має бути описано як саме (наприклад використовуючи вертикально чи горизонтально. чи ще краще - Landscape and Portrait Orientation

**Comment by scholokov** [comment]
"video sizes as for shorts on Youtube" - оця фраза якась незрозуміла

**Comment by BondarAnatolii** [comment]
пробую підібрати потрібний опис для цього відео, але поки виходить не дуже

**Comment by scholokov** [comment]
Actual result:
Video in the gallery is played with **Portrait** orientation 
Reproduces only with this video

Expected result:
Video in the gallery are played with **Landscape** orientation

**Comment by scholokov** [comment]
1. Open the page
2. Scroll down to the second gallery on the page
3. Open the second video in gallery
4. Pay attention to video orientation

**Comment by DmytroMarkulych** [comment]
Атрибут Priority виставляється РМ а не QA

**Comment by BondarAnatolii** [comment]
Добре. Обнулив параметр Priority

**Comment by scholokov** [comment]
fixed

**Comment by BondarAnatolii** [comment]
verified
