### ISSUE TITLE
20130613_0628_Bulgaria/Language of the city, region and country in Russian,not Ukrainian as it should be.

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#4191]
**Steps to reproduce:**

**1.** Open page <https://test.long-travel.live/20130613_0628_Bulgaria/>
**2.** Scroll through all block names

**Actual result:**
Language city, region and country Russian.

**Expected result:**
Language city, region and country Ukrainian.

**Environment:**
MacBook/macOS Ventura 14/Safari Version 17 (19616.1.26.11.3)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/4c05691c-7219-4d9e-abcd-3ce48984b584)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/d3773953-9de9-4104-ad4a-d6959b1a2fcc)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/55809645-4de2-403a-860f-8d9a33a079ce)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/aa553ded-5590-46ff-8ea0-cbf08ad9a3a3)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/79ca5815-5654-4366-ac17-be3023ea31c4)

**Comment by scholokov** [comment]
fixed
