### ISSUE TITLE
20160814_24_shadsk/Shatski Ozera, Volyn region – Header missing travel tags

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#4192]
**Steps to playback:**

1. Open https://www.test.long-travel.live/20160814_24_shadsk
2. Pay attention to the header

**Actual result:**
Header missing travel tags

**Expected result:**
Header travel tags are present
![теги](https://github.com/scholokov/long-travel-2/assets/132911639/2ad9e2a6-27c3-4873-94ab-8237d5052735)

Environment:
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![тегі](https://github.com/scholokov/long-travel-2/assets/132911639/58c2fcd1-6e8b-46c4-9a9a-e7d0a1cd9bf6)

**Comment by Artem-16** [comment]
#3086

**Comment by scholokov** [comment]
please retest

**Comment by Artem-16** [comment]
напис "warning" прибрали але тег подорожі відсутній

**Comment by scholokov** [comment]
fixed
