### ISSUE TITLE
0170521_korosten/ Extra text "Warning: Invalid argument supplied for foreach() in /home/qaxcamp/long-travel.live/test/wp-content/themes/mts_myblog/single.php on line 44" is in the Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4197]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170521_korosten/
2. Pay attention to the Extra text "Warning: Invalid argument supplied for foreach() in /home/qaxcamp/long-travel.live/test/wp-content/themes/mts_myblog/single.php on line 44" in the Preview block

**Actual result:**
Extra text "Warning: Invalid argument supplied for foreach() in /home/qaxcamp/long-travel.live/test/wp-content/themes/mts_myblog/single.php on line 44" is in the Preview block.

**Expected result:**
Extra text "Warning: Invalid argument supplied for foreach() in /home/qaxcamp/long-travel.live/test/wp-content/themes/mts_myblog/single.php on line 44" is absent in the Preview block.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/d59b879c-d6d1-48e1-8795-78b0c406ceed)

**Comment by GNatala** [comment]
#3230

**Comment by DmytroMarkulych** [comment]
Атрибут Priority виставляє PM

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
