### ISSUE TITLE
20160830_Myrgorod / Extra text "Warning: Invalid argument supplied for foreach() in /home/qaxcamp/long-travel.live/test/wp-content/themes/mts_myblog/single.php on line 44" is in the Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4198]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20160830_Myrgorod/
2. Pay attention to the Extra text "Warning: Invalid argument supplied for foreach() in /home/qaxcamp/long-travel.live/test/wp-content/themes/mts_myblog/single.php on line 44" in the Preview block

**Actual result:**
Extra text "Warning: Invalid argument supplied for foreach() in /home/qaxcamp/long-travel.live/test/wp-content/themes/mts_myblog/single.php on line 44" is in the Preview block.

**Expected result:**
Extra text "Warning: Invalid argument supplied for foreach() in /home/qaxcamp/long-travel.live/test/wp-content/themes/mts_myblog/single.php on line 44" is absent in the Preview block.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/a3239869-3e7a-45a5-a1ef-b44db7768545)

**Comment by GNatala** [comment]
#1352

**Comment by DmytroMarkulych** [comment]
Priority виставляє PM

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
