### ISSUE TITLE
20170513_putivl_kruti/In the Map block, the active element "Відкрити подорож"  is missing

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4200]
Steps to reproduce:
1. Open https://test.long-travel.live/20170513_putivl_kruti/
2. Scroll down to the Map block
3. Pay attention to the section after the information about the Travel Route

Actual result: the active element "Відкрити подорож"  is **missing**
Expected result: the active element "Відкрити подорож"  is **present**

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/77480fc1-4d80-4d87-b603-ed935c395c7e)

**Comment by ODrobik** [comment]
#3229

**Comment by scholokov** [comment]
виправлено
