### ISSUE TITLE
"Цікаві місця" - Preview of standard block "Браття наші менші" has the type "castle"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4201]
**Steps of reproducing**
1. Open https://test.long-travel.live/places/
2. Scroll to block "Браття наші менші"

**Actual Result**
Preview of standard block "Браття наші менші" has the type "castle"

**Expected Result**
Preview of standard block "Браття наші менші" has the type "animals"

**Additional information**
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-6&mode=design&t=UHbdZRhwXoLmtOjs-0

**Enviroments**
Windows 10, Chrome 116.0.5845.97 (64 bit), Firefox 116.0.2 (64 bit)
Android 8.1.0, Chrome 115.0.5790.166, Firefox 116.0.2
![Цікаві місця – Long-Travel - Google Chrome 16 08 2023 16_29_01](https://github.com/scholokov/long-travel-2/assets/95171672/2c402d1d-42f9-42ab-9b1f-6c51fa92f65f)
![Цікаві місця – Long-Travel — Mozilla Firefox 16 08 2023 16_22_57](https://github.com/scholokov/long-travel-2/assets/95171672/f8cc4d30-0226-4f8b-8b3a-2e8e747a82c8)
![photo_2023-08-16_16-29-15](https://github.com/scholokov/long-travel-2/assets/95171672/0a23c474-e299-40b1-bc38-406ffb7a64ab)
![photo_2023-08-16_16-29-19](https://github.com/scholokov/long-travel-2/assets/95171672/18d3fb4a-1e48-4c5d-ad48-3a56c544feb7)

**Comment by DmitriiNasonov** [comment]
#4129

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/long-travel-2/assets/88647733/83a7a11c-84c1-47b7-b1fc-744e0d5ce559)

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
