### ISSUE TITLE
20170513_putivl_kruti/In the Map block, the Preview Photo is missing 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4202]
Steps to reproduce:

1. Open https://test.long-travel.live/20170513_putivl_kruti/
2. Scroll down to the Map block
3. Pay attention to the section the information about the Travel Route

Actual result: the Preview Photo is **missing** 
Expected result: the Preview Photo is **present**

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/8994f1fb-fed1-4598-a670-811f04b46f8f)

**Comment by ODrobik** [comment]
#3229

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
