### ISSUE TITLE
20170513_putivl_kruti/In the Map block, the Names of the Сities are in English

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4203]
Steps to reproduce:

1. Open https://test.long-travel.live/20170513_putivl_kruti/
2. Scroll down to the Map block
3. Pay attention to the section the information about the Travel Route

Actual result: the Names of the Сities are in English
Expected result: the Names of the Сities are in Ukrainian

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel

Environment:
Windows 10 Pro (x64),
Google Chrome v 110.0.5481.105 (x64)

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/d00ba411-ba5b-47aa-81cd-ae18f2683189)

**Comment by ODrobik** [comment]
#3229

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
