### ISSUE TITLE
20170513_putivl_kruti/ Under the Map, the Standard block "Дорога" does not meet the requirements

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4204]
Steps to reproduce:

1. Open https://test.long-travel.live/20170513_putivl_kruti/
2. Pay attention to the structure block Under the Map

Actual Result: the Standard block  "Дорога" does not meet the requirements
Expected Result: the Standard block  "Дорога" meets the requirements

Requirements: https://github.com/scholokov/long-travel-2/wiki/4.-%D0%9F%D0%BE%D0%B4%D0%BE%D1%80%D0%BE%D0%B6

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/51bc199a-365b-4d47-a538-97c3a33251a3)

**Comment by ODrobik** [comment]
#3229

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
