### ISSUE TITLE
wiki/The Page"Подорож - шаблонована сторінка" the link "Стандартних блоках" does not display the necessary information 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4205]
Steps to reproduce:

1. Open: https://qax.gitbook.io/qax-travel/requirements/4.travel
2. Click on the page "Подорож - шаблонована сторінка"
3. Pay attention to the block "Стандартний блок(и)" on the page

Actual Result: the link "Стандартних блоках" does not display the necessary information 
Expected Result: the link "Стандартних блоках" displays the necessary information 

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/88ca9597-ad9a-403c-8528-54242170b215)

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено відповідно за лінкою https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i
