### ISSUE TITLE
20180708_boguslav/Type of photo gallery travel not mosaic.

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#4209]
**Steps to reproduce:**

**1.** Open page <https://test.long-travel.live/20180708_boguslav/>
**2.** Scroll to photo gallery.
**3.** Go to DevTools and to "div" find  parameter "layout"
**4.** Pay attention to a parameter "layout"

**Actual result:**
 Type photo gallery "layout=random"

**Expected result:**
Type photo gallery "layout=mosaic"

**Additional information:**
<https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i>

**Environment:**
MacBook/macOS Sonoma 14/Safari Version 17.0 (19616.1.26.11.3)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/0ea45913-54be-458c-bc05-e6921cb466e4)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/ca9ffb26-0f75-4dda-a19d-7027227166e0)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/c1faf3b0-7195-4a8d-8fac-70757552297c)

**Comment by scholokov** [comment]
виправлено
