### ISSUE TITLE
20200814_15_serhiivka Відсутня фотографія праворуч від карти при перегляді маршруту

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4210]
Передумови:

Відкрити: https://test.long-travel.live/20200814_15_serhiivka/

Кроки для відтворення:
1. Звернути увагу на фото нижче маршруту

Фактичний результат: 
Фото міста подорожі не відображається

Очікуваний результат:
Відображається фото міста подорожі

Вимоги: 
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-6&mode=design&t=cgm1iX4zHahSjByT-0

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![20200814_15_serhiivka](https://github.com/scholokov/long-travel-2/assets/140165683/5d686d68-7dfb-4b1e-b5d4-9d39dca16586)

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
перевірено
