### ISSUE TITLE
20170513_putivl_kruti/ The image is displayed in the Preview block of the trip

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4217]
Steps to reproduce:
1. Open https://test.long-travel.live/20170513_putivl_kruti/
2. Pay attention to the Preview block of the trip

Actual Result: The image is displayed in the Preview block of the trip
Expected Result: The image is not displayed in the Preview block of the trip

Requirements: https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-6&mode=design&t=y0aS9ZW2QzegAS47-0

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/4a74d1f0-029a-4250-bcff-f98a4142da18)

**Comment by ODrobik** [comment]
#3229

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
