### ISSUE TITLE
20130613_0628_Bulgaria/Flags of Romania and Bulgaria travel previews are not the exact size.

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#4221]
**Steps to reproduce:**

**1.** Open page <https://test.long-travel.live/20130613_0628_Bulgaria/>
**2.** Scroll to header block"Болград – Слънчев бряг – București – Саврань"
**3.** Open console in DevTools

**Actual result:**
 Flag sizes of Romania and Bulgaria = 26px x 24px

**Expected result:**
Flag sizes of Romania and Bulgaria = 36px x 24px

**Environment:**
MacBook/macOS Sonoma 14/Safari Version 17.0 (19616.1.26.11.3)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/61eba6ed-4052-4f27-984a-383748b3f04e)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/699188a1-4d60-4c57-abc6-4657e43a9fbe)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/d355553d-84be-4342-bc91-61db371ed593)

**Comment by scholokov** [comment]
виправлено
