### ISSUE TITLE
20180708_boguslav/In the block preview of the trip unnecessary graphic element

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#4222]
**Steps to reproduce:**
**1.** Open page <https://test.long-travel.live/20180708_boguslav/>
**2.** Scroll to header block "Чайки 2018"
**3.** Open console in DevTools

**Actual result:**
 Is displayed graphic element "Vector.png"

**Expected result:**
Graphic element "Vector.png" not be displayed

**Environment:**
MacBook/macOS Sonoma 14/Safari Version 17.0 (19616.1.26.11.3)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/0c1801ae-fbab-49d4-b50e-5874ba97cc13)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/bdffac86-b76a-4d27-b8f1-05569d232bad)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/5404cc26-63fe-4375-8f38-ac4b8680af05)

**Comment by scholokov** [comment]
виправлено
