### ISSUE TITLE
20160618_mezhigorie - Block National Park "Mezhyhirya" flag width26 height18

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#4224]
**Steps to playback:**

1. Open https://test.long-travel.live/20160618_mezhigorie/
2. Scroll to the standard block of the National Park "Mezhyhirya"
3. Pay attention to the flag

**Actual result:**
flag width26 height18

**Expected result:**
flag width36 height24
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=4997%3A393&mode=dev
![фігма прапор width36рх height24рх](https://github.com/scholokov/long-travel-2/assets/132911639/32772e9a-d9e5-4186-a0b8-358e2729985d)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![баг прапор](https://github.com/scholokov/long-travel-2/assets/132911639/1b2ff3a5-2fdc-4877-a531-37bae833d2e1)

**Comment by Artem-16** [comment]
#3084

**Comment by scholokov** [comment]
виправлено
