### ISSUE TITLE
20160618_mezhigorie - Photo gallery National Park "Mezhyhirya" value key layout=random 

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#4225]
**Steps to playback:**

1. Open https://test.long-travel.live/20160618_mezhigorie/
2. Scroll to down
3. Photo gallery National Park "Mezhyhirya"
4. Open dev tools

**Actual result:**
Value key layout=random

**Expected result:**
Value key layout=mosaic
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i
![Вимоги фотогалерея](https://github.com/scholokov/long-travel-2/assets/132911639/13906500-29b6-400f-8d29-f7235ba0c5c2)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![межегіря баг фото](https://github.com/scholokov/long-travel-2/assets/132911639/8319f898-a1ef-43b6-b6d1-29d39dc8bd1b)

**Comment by Artem-16** [comment]
#3084

**Comment by scholokov** [comment]
виправлено
