### ISSUE TITLE
20160618_mezhigorie - Header missing travel tags 

### ISSUE THREAD

**Issue by Artem-16** [scholokov/long-travel-2#4226]
**Steps to playback:**

1. Open https://test.long-travel.live/20160618_mezhigorie/
2. Pay attention to the header

**Actual result:**
Header missing travel tags

**Expected result:**
Header travel tags are present
![теги](https://github.com/scholokov/long-travel-2/assets/132911639/e6582394-3fd2-4251-89fd-cc3876ab0da7)

**Environment:**
macOS Catalina 10.15.7 - Google Chrome Версія 113.0.5672.126
![баг теги](https://github.com/scholokov/long-travel-2/assets/132911639/c4136583-432c-405f-82a5-cadf3967d690)

**Comment by Artem-16** [comment]
#3084

**Comment by scholokov** [comment]
виправлено
