### ISSUE TITLE
"Цікаві місця" page - The font name of any block is "Rubik"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4231]
**Steps of reproducing**
1. Open https://test.long-travel.live/places/
2. Check font name from any block

**Actual Result**
The font name of any block is "Rubik"

**Expected Result**
The font name of any block is "Amazing Slab Trial"

**Additional information**
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-7&mode=design&t=i6pPIcPhdptJiUaj-0

**Enviroments**
Windows 10, Chrome 116.0.5845.111 (64 bit)
![Цікаві місця – Long-Travel - Google Chrome 23 08 2023 14_53_11](https://github.com/scholokov/long-travel-2/assets/95171672/cb8c68ab-7ede-42f0-9a79-bb83167d4920)

**Comment by DmitriiNasonov** [comment]
#4129

**Comment by scholokov** [comment]
please retest

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
