### ISSUE TITLE
20170521_korosten / Name of the Video's playlist "2017.05.21 Korosten - Bunker" is written in English

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4233]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170521_korosten/
2. Scroll down to the "2017.05.21 Коростень - Бункер 1" video.
3. Click on the "1/6" in the upper right corner of the video.
4. Pay attention to the name of the Video's playlist "2017.05.21 Korosten - Bunker".

**Actual Result:** 
Name of the Video's playlist "2017.05.21 Korosten - Bunker" is written in English.

**Expected Result:** 
Name of the Video's playlist "2017.05.21 Korosten - Bunker" is written  in Ukrainian.

**Additional information:**
https://github.com/scholokov/long-travel-2/blob/1b4372f79dcd98f145e67cb1ee512cc04f01af84/requirements/4.travel/struktura/standartnii-blok-i/README.md

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://github.com/scholokov/long-travel-2/assets/101987790/5c34097f-40be-4a87-89fa-5e3f953a8933)
![image](https://github.com/scholokov/long-travel-2/assets/101987790/8cc04748-c120-45dc-90af-c17a375c345b)

**Comment by GNatala** [comment]
#3230

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
