### ISSUE TITLE
20170521_korosten / Tag is missed in the Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4235]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170521_korosten/
2. Pay attention to the  absence of  tags in the Preview block

**Actual result:**
Tags are missed in the Preview block.

**Expected result:**
Tags are present in the Preview block.

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/2a988872-f01a-4612-b363-361c4f07db2a)
![image](https://github.com/scholokov/long-travel-2/assets/101987790/8894f243-ba02-4a5f-8632-876f163659a9)

**Comment by GNatala** [comment]
#3230

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
