### ISSUE TITLE
20170513_putivl_kruti/ The 2nd Standard "Дорога" block does not meet the requirements

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4236]
Steps to reproduce:
1. Open https://test.long-travel.live/20170513_putivl_kruti/
2. Pay attention to the structure Standard block after 1-st "Дорога" block

Actual Result: The 2nd Standard "Дорога" block does not meet the requirements
Expected Result: The 2nd Standard "Дорога" block is meet the requirements

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/991108cf-3598-4b15-8696-bb5edbeea235)

**Comment by ODrobik** [comment]
#3229

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
@scholokov  Issue is still

![image](https://github.com/scholokov/long-travel-2/assets/123776698/3894a9be-1dce-4efe-9a08-c806ccf67f29)

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
