### ISSUE TITLE
Create regression tests

### ISSUE THREAD

**Issue by ABatalov** [scholokov/long-travel-2#4237]
For QA team please create regression tests and check lists in TestRail. 

We need to check all website:  
- [x] Home page 
- [x] Maps on Home page 
- [x] Header on Home page 
- [x] Footer on Home page 
- [x] Travels page 
- [x] Each travel list of all travels: https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list
- [x] Map on Travels page 
- [x] Foot and Header on Travel page

**Comment by GNatala** [comment]
https://qaxcampqa.testrail.io/index.php?/suites/view/90&group_by=cases:section_id&group_order=asc&display_deleted_cases=0&group_id=1797

**Comment by ODrobik** [comment]
verified
