### ISSUE TITLE
20200814_15_serhiivka Зайвий тег автомобіля праворуч біля прапора України

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4238]
Передумови:

Відкрити:
https://test.long-travel.live/20200814_15_serhiivka/

Кроки для відтворення:
1. Звернути увагу на тег праворуч прапора України

Фактичний результат: 
Відображається тег автомобіля праворуч прапора України

Очікуваний результат:
Не відображається зайвий тег праворуч Прапора України

Вимоги: 
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-6&mode=design&t=3V5fZoeEHyhASEuB-0

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104
![зайвий тег](https://github.com/scholokov/long-travel-2/assets/140165683/0e2ba520-a32e-4bc5-8cb9-02b75c7fca98)

**Comment by irunabychkovska** [comment]
#4088

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
