### ISSUE TITLE
wiki/ Pages: "Requirements" - "Цікаві місця", in the point "5.3 is written the word "Превью"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4239]
Steps to Reproduce:
1. Open: https://qax.gitbook.io/qax-travel/requirements/places
2. Scroll down to the point "5.3"
3. Pay attention to the point "5.3" on the page

Actual Result: in the point "5.3 is written the word "Превью"подорожі"
Expected Result: in the point "5.3 is written the word "Прев'ю"

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/a391cf64-f7a9-4f86-b87f-aa2b5ce18344)

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
