### ISSUE TITLE
20190720_0811_balcans Не потрібний URL у верхній частині  прев'ю 

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4242]
Передумови:

Відкрити: 
https://test.long-travel.live/20190720_0811_balcans/

Кроки для відтворення:
1. Переглянути прев'ю у верхній частині

Фактичний результат: 
відображається зайвий URL у прев'ю

Очікуваний результат:
не відображається  URL у прев'ю

Вимоги: 
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-6&mode=design

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![Балкани 1](https://github.com/scholokov/long-travel-2/assets/140165683/4b1f8110-c36a-4338-8095-05509ef2de1a)

**Comment by irunabychkovska** [comment]
#4076

**Comment by scholokov** [comment]
виправлено

**Comment by Illia2810** [comment]
перевірено
