### ISSUE TITLE
20190720_0811_balcans Відображається зразу більше одного блоку з фотографіями при перегляді фотогалереї

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4248]
Передумови:

Відкрити:
https://test.long-travel.live/20190720_0811_balcans/

Кроки для відтворення:
Прогорнути до кінця сторінки з фотографіями

Фактичний результат: 
Зразу загружаються кілька блоків з фотографіями

Очікуваний результат:
Відображаються тільки фотографії першого блоку фотогалареї

Вимоги: 
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=4997-386&mode=design&t=tfVewGg3ZTCLHoJY-0

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![фотогалерея](https://github.com/scholokov/long-travel-2/assets/140165683/4eb01882-2cd3-4da8-ad38-33db20866c15)

![фото 2_13](https://github.com/scholokov/long-travel-2/assets/140165683/c609b3f3-5cea-4963-998f-8cba46922c8d)

**Comment by irunabychkovska** [comment]
#4076

**Comment by scholokov** [comment]
fixed

**Comment by irunabychkovska** [comment]
відтворюється далі баг

**Comment by Illia2810** [comment]
виправлено
