### ISSUE TITLE
wiki/ Pages: "Requirements" - "Подорожі - Сторінка" - "Пошук", in the point "1.1 is written the word "підподний"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4249]
Steps to Reproduce:

1. Open: https://qax.gitbook.io/qax-travel/requirements/3.travels/search
2. Scroll down to the point "1.1"
3. Pay attention to the word "підподний" on the page

Actual Result: in the point "1.1 is written the word "підподний"
Expected Result: in the point "1.1 is written the word "підводний"

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/a1c0b0aa-4abe-4670-8d77-fffeb939ff50)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
