### ISSUE TITLE
20190616_korostishevsky_kanyon/Error (Invalid argument supplied for foreach) of travel page

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#4261]
**Steps to reproduce: **
Open page <https://test.long-travel.live/20190616_korostishevsky_kanyon/>

**Actual result:**
 Error in the travel page title bar

**Expected result: **
No error in the travel page title bar

**Environment: **
MacBook/macOS Sonoma 14/Safari Version 17.0 (19616.1.27.111.16)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/4fd66958-b666-44c0-8ab4-8c5ce67900d7)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/long-travel-2/assets/88647733/f1227138-69c6-4599-a674-9b34d99c4860)

**Comment by SerhiiBurdieiev** [comment]
Corrected

**Comment by scholokov** [comment]
fixed
