### ISSUE TITLE
20180915_buki/In the block preview of the trip unnecessary graphic element

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#4282]
**Steps to reproduce:**
**1.** Open page <https://test.long-travel.live/20180915_buki/>
**2.** Scroll to header block "Буки – Белая Церковь"
**3.** Open console in DevTools

**Actual result:**
 Is displayed graphic element "Vector.png"

**Expected result:**
Graphic element "Vector.png" not be displayed

**Environment:**
MacBook/macOS Sonoma 14/Safari Version 17.0 (19616.1.26.11.3)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/98264ff6-00d1-4eed-b7ae-b2ca07696add)

**Comment by scholokov** [comment]
fixed
