### ISSUE TITLE
20180915_buki/No flag displayed in the travel title

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#4283]
**Steps to reproduce:**
**1.** Open page <https://test.long-travel.live/20180915_buki/>
**2.** Scroll to header block "Буки – Белая Церковь"

**Actual result:**
No  displayed flag of Ukraine

**Expected result:**
Displayed flag of Ukraine

**Environment:**
MacBook/macOS Sonoma 14/Safari Version 17.0 (19616.1.27.111.16)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/99023ca6-ecc2-47ea-a2ad-d532d6937dd0)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/05bfd157-6a50-4821-b7a8-6b9ea7b054ca)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/c0133c19-23a2-4307-b900-a8d29eb2948c)

**Comment by scholokov** [comment]
fixed
