### ISSUE TITLE
20180915_buki/Language of the city, region and country in Russian

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#4284]
**Steps to reproduce:**

**1.** Open page <https://test.long-travel.live/20180915_buki/>
**2.** Scroll through all block names

**Actual result:**
Language of the city, region and country is not in Ukrainian

**Expected result:**
Language of the city, region and country in Ukrainian

**Environment:**
MacBook/macOS Ventura 14/Safari Version 17 (19616.1.27.111.16)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/7c618118-be07-4170-93a9-ba6dc8f0dd4a)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/f08c13bd-d0bd-419e-afaf-27bf59a80c4e)
![Image](https://github.com/scholokov/long-travel-2/assets/108996909/b6a8ac02-e108-4de9-9de1-1cb929c6e23b)
![Image](https://github.com/scholokov/long-travel-2/assets/108996909/8ae9f842-e198-45ce-a752-e9d5766e2829)
![Image](https://github.com/scholokov/long-travel-2/assets/108996909/4fcba43a-ebce-4509-8ed5-54ad53201276)
![Image](https://github.com/scholokov/long-travel-2/assets/108996909/1c0ee68d-e158-497e-864a-c609f1a14aa8)
![Image](https://github.com/scholokov/long-travel-2/assets/108996909/6c025a5d-0e7e-422b-b39d-83e56500314a)
![Image](https://github.com/scholokov/long-travel-2/assets/108996909/98b3525a-84dd-4292-8dc1-0a9332ca7b70)

**Comment by DmytroMarkulych** [comment]
в Summary ви вказала як актуальний так і очікуваний результати. Давайте просто вкажемо що є по факту. А те як має бути вкажемо в Очікуваному результаті

**Comment by SerhiiBurdieiev** [comment]
Corrected.

**Comment by scholokov** [comment]
fixed
