### ISSUE TITLE
20160710_0807_italy_odessa/The distance traveled from the previous travel point is missing

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4287]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the Global Map.
3. Pay attention to the absence of the distance traveled from the previous travel point .

**Actual result:**
Next to each intermediate point, the distance traveled from the previous point of travel is missing
**Expected result:**
Next to each intermediate point, the distance traveled from the previous point of travel must be indicated

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/eac936a8-170a-4994-bff8-ddf918e0717b)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/d428f544-2ee9-4f07-ac79-51747b91a422)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
