### ISSUE TITLE
20160710_0807_italy_odessa/The list of the trips is missing on the map in the upper left corner

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4288]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the Global Map.
3. Pay attention to the absence of the list of the trips on the map in the upper left corner.

**Actual result:**
The list of the trips is missing on the map in the upper left corner

**Expected result:**
The list of the trips is on the map in the upper left corner

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/e2ea1ace-e100-4489-9c10-2da5a3cff058)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/737d5a50-2fb2-48a0-b33d-03ef33bc86cd)

**Comment by scholokov** [comment]
це коректна поведінка
внесені відповідні зміни у вимоги
<img width="523" alt="image" src="https://github.com/scholokov/long-travel-2/assets/22824947/e58d5d5f-ea01-4fa1-97da-acf74c0f75b8">

**Comment by prokopenkoga1977** [comment]
Passed
