### ISSUE TITLE
20190720_0811_balcans Прапори країн  в прев'ю відображаються в різних розмірах.

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4290]
Передумови:

Відкрити:
https://test.long-travel.live/20190720_0811_balcans/

Кроки для відтворення:
Звернути увагу на розміри прапорів у прев'ю

Фактичний результат: 
Розміри прапорів різні: 26 * 24, 36 * 24(DevTools)

Очікуваний результат:
розміри прапорів однакові 36 * 24

Вимоги: 
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-6&mode=design&t=rqcnZb8P26tTiOxL-0

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![прапори ](https://github.com/scholokov/long-travel-2/assets/140165683/f42f37cf-fcbb-4c45-a81c-e611238f2962)

![Некоректні розміри](https://github.com/scholokov/long-travel-2/assets/140165683/e9d2937e-8315-4611-89e2-4afbe9446656)

**Comment by DmytroMarkulych** [comment]
давайте вкажемо які конкретно розміри мають бути

**Comment by irunabychkovska** [comment]
ок

**Comment by irunabychkovska** [comment]
зробила

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
