### ISSUE TITLE
 20200918_20_kharkiv Відсутня лінка  у маршруті подорожі над фотографією

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4293]
Передумови:

Відкрити:
https://test.long-travel.live/20200918_20_kharkiv/

Кроки для відтворення:
Звернути увагу на наявність лінки

Фактичний результат: 
Лінка відсутня

Очікуваний результат
відображається лінка

Вимоги: 
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![лінк](https://github.com/scholokov/long-travel-2/assets/140165683/9373b426-aedb-462e-8e8f-e1e57c50dd7c)

**Comment by irunabychkovska** [comment]
#4091

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
bug-report isn't actual
