### ISSUE TITLE
"Горні дороги" / Standard blocks are sorted - top - oldest, bottom - newest

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4297]
**Steps to reproduce:**

1. Open https://test.long-travel.live/m-road/
2. Pay attention to the sorting blocks by the time.

**Actual result:**
Standard blocks are sorted - top - oldest, bottom - newest.

**Expected result:**
Standard blocks should be sorted by time (top - newest, bottom - oldest).

**Additional information:**
https://qax.gitbook.io/qax-travel/requirements/places

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/d1ec74df-efc2-4de3-ac25-eb3383c37b8b)

**Comment by GNatala** [comment]
#4207

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
