### ISSUE TITLE
"Горні дороги" / The page slug "m-road" does not match the name of the corresponding tag

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4300]
**Steps to reproduce:**

1. Open https://test.long-travel.live/m-road/
2. Pay attention to the page slug "m-road".

**Actual result:**
The page slug "**m-road**" does not match the name of the corresponding tag "**road**".

**Expected result:**
The page slug "**m-road**" matches the name of the corresponding tag "**road**".
.
**Additional information:**
https://qax.gitbook.io/qax-travel/requirements/places

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/c590f3a3-0858-47b5-97ac-f885ed115455)

**Comment by GNatala** [comment]
#4207

**Comment by scholokov** [comment]
виправлено у вимогах

**Comment by GNatala** [comment]
перевірено
