### ISSUE TITLE
20160710_0807_italy_odessa/The end point date is July 10, 2023 on the map

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4314]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the Global Map.
3. Pay attention to the end point date on the Map.

**Actual result:**
The end point date is July 10, 2023 on the map
**Expected result:**
The end point date is August 7, 2016 on the map

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/02bcf7cc-1bab-4f1e-92d4-e27defdd42e5)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/502093dc-5551-4268-b31c-b22482f1c18d)

**Comment by scholokov** [comment]
оновив вимоги
<img width="552" alt="image" src="https://github.com/scholokov/long-travel-2/assets/22824947/af9b0e80-bd3b-4cc0-bffa-9ce70c0f94e2">

**Comment by prokopenkoga1977** [comment]
@scholokov вніс зміни в баг репорт стосовно оновлених вимог. все одно дата вказана некоректна

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
