### ISSUE TITLE
20160710_0807_italy_odessa/The date of waypoint Krakow, Poland is July 22, 2016 on the map

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4316]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the Global Map.
3. Pay attention to the date of waypoint Krakow, Poland on the Map.

**Actual result:**
The date of waypoint Krakow, Poland is July 22, 2016 on the map
**Expected result:**
The date of waypoint Krakow, Poland is missing on the map

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/109cbde1-08f0-4fc5-b747-a608ebad6199)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/80804aae-4357-448e-991c-a421477d5c58)

**Comment by scholokov** [comment]
оновив вимоги
<img width="552" alt="image" src="https://github.com/scholokov/long-travel-2/assets/22824947/78a337e6-3b53-4fca-b4a8-9532b9415195">

**Comment by prokopenkoga1977** [comment]
Passed
