### ISSUE TITLE
20160710_0807_italy_odessa/The date of waypoint Ringhotel Die Gams, Beilngries, Germany is July 1, 2016 on the map

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4317]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the Global Map.
3. Pay attention to the date of waypoint Ringhotel Die Gams, Beilngries, Germany on the Map.

**Actual result:**
The date of waypoint Ringhotel Die Gams, Beilngries, Germany is July 1, 2016 on the map
**Expected result:**
The date of waypoint Ringhotel Die Gams, Beilngries, Germany is July 20, 2016 on the map

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/f3e8124f-896a-4d58-99bb-1ef70bcea788)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/a1ad3a67-82e1-4498-94a5-b050513027cf)

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/288c2f1f-d218-4a20-a531-25c2156fbbb0)

**Comment by scholokov** [comment]
оновив вимоги
<img width="552" alt="image" src="https://github.com/scholokov/long-travel-2/assets/22824947/40a00dcc-04da-458d-b329-3d61e3791340">

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
