### ISSUE TITLE
20160710_0807_italy_odessa/The memo Miniatures, Viserbella, Italy is displayed as a dot on the map

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4319]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the Global Map.
3. Pay attention to the memo Miniatures, Viserbella, Italy.

**Actual result:**
The memo Miniatures, Viserbella, Italy is displayed as a dot on the map
**Expected result:**
The memo Miniatures, Viserbella, Italy is displayed with asterisk on the map

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/9da79868-2b4a-4d25-bdee-d0e48a891646)

**Attachments:** 

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/b78e500d-68f9-4fcb-8714-d89c6efbe095)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
