### ISSUE TITLE
20170513_putivl_kruti/ The 1st Standard "Дорога" block is displayed the 1st line "Дорога – Киев – Путивль-Україна" Name

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4320]
Steps to reproduce:

1. Open https://test.long-travel.live/20170513_putivl_kruti/
2. Scroll down to the 1st Standard "Дорога" block
3. Pay attention to the 1st line Name in the Standard "Дорога" block

Actual Result: the 1st line "Дорога – Киев – Путивль-Україна" Name in the Standard "Дорога" block
Expected Result:  the 1st line "Дорога" Name in the Standard "Дорога" block

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/71c9dce0-7d10-4a11-a72e-aac9502aaad2)

**Comment by ODrobik** [comment]
#3229

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
