### ISSUE TITLE
20170513_putivl_kruti/ The 1st Standard "Дорога" block is displayed the 2nd line "13.05.2017"  the Route of the travel

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4321]
Steps to reproduce:

1. Open https://test.long-travel.live/20170513_putivl_kruti/
2. Scroll down to the 1st Standard "Дорога" block
3. Pay attention to the 2nd line Route of the travel in the Standard "Дорога" block

Actual Result: the 2nd line "13.05.2017"  the Route of the travel in the Standard "Дорога" block
Expected Result: the 2nd line "Київ – Путивль"  the Route of the travel in the Standard "Дорога" block

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/c6bc3cd9-9a81-438b-bd6d-1bd80c18f3f1)

**Comment by ODrobik** [comment]
#3229

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
