### ISSUE TITLE
20170513_putivl_kruti/ The 3rd line Date is not displayed in the 1st Standard "Дорога" block 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4323]
Steps to reproduce:

1. Open https://test.long-travel.live/20170513_putivl_kruti/
2. Scroll down to the 1st Standard "Дорога" block
3. Pay attention to the 3rd line Date  in the Standard "Дорога" block

Actual Result: The 3rd line Date is not displayed in the 1st Standard "Дорога" block
Expected Result:The 3rd line "13.05.2017" Date is displayed in the 1st Standard "Дорога" block

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/8d4452f6-343b-405c-82cd-245717a03755)

**Comment by ODrobik** [comment]
#3229

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/long-travel-2/assets/88647733/6bc1b5f5-1b52-4862-8d9e-93ff82e11c96)

**Comment by ODrobik** [comment]
Виправлено

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
