### ISSUE TITLE
20170513_putivl_kruti/ The Flag of Ukraine is not displayed in the 1st Standard "Дорога" block 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4324]
Steps to reproduce:

1. Open https://test.long-travel.live/20170513_putivl_kruti/
2. Scroll down to the 1st Standard "Дорога" block
3. Pay attention to the location of the Flag of Ukraine in the Standard "Дорога" block

Actual Result: The Flag of Ukraine is not displayed in the 1st Standard "Дорога" block 
Expected Result:The Flag of Ukraine is displayed in the 1st Standard "Дорога" block 

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/d0516711-142c-4a86-aae7-308932b24dfb)

**Comment by ODrobik** [comment]
#3229

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/long-travel-2/assets/88647733/ee3783aa-3d4a-49c6-83eb-d0d34dee7bb5)

**Comment by ODrobik** [comment]
Виправлено

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
