### ISSUE TITLE
Zoo in the block "Interesting places" - "Одеський дельфінарій НЕМО" standard block - Preview of the standard block has type is "zoo" and name doesn't contain the link to "Сергіївка – Одеса" travel

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4337]
**Steps of reproducing**
1. https://test.long-travel.live/zoo/
2. Scroll to "Одеський дельфінарій НЕМО" standard block
3. Pay attention to preview and name

**Actual Result**
Preview of the standard block has type is "zoo" and name doesn't contain the link to "Сергіївка – Одеса" travel
 
**Expected Result**
Preview of the standard block has preview of the "Сергіївка – Одеса" travel OR name contain the link to "Сергіївка – Одеса" travel

**Additional information**
https://test.long-travel.live/20210814_24_sergeevka_odessa/
https://qax.gitbook.io/qax-travel/requirements/places

**Enviroments**
Windows 10, Chrome 116.0.5845.111 (64 bit), Firefox 117.0 (64 bit)
Android 8.1.0, Chrome 116.0.5845.163, Firefox 117.0
![Зоопарки – Long-Travel - Google Chrome 06 09 2023 14_14_30](https://github.com/scholokov/long-travel-2/assets/95171672/62f6eb54-1cac-4d0b-ab89-497529ec6ac6)
![Зоопарки – Long-Travel — Mozilla Firefox 06 09 2023 14_14_39](https://github.com/scholokov/long-travel-2/assets/95171672/0b4a5224-f672-4183-915d-7d8761e93bd9)
![photo_2023-09-06_14-15-00](https://github.com/scholokov/long-travel-2/assets/95171672/9e0c51c9-cfe5-4f77-8499-ed0111c40bff)
![photo_2023-09-06_14-14-57](https://github.com/scholokov/long-travel-2/assets/95171672/63b792a6-d057-438c-84d4-2ce60a15326f)

**Comment by DmitriiNasonov** [comment]
#4206

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
