### ISSUE TITLE
20190616_korostishevsky_kanyon/Travel header in Russian

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#4345]
**Steps to reproduce:**

**1.** Open page <https://test.long-travel.live/20190616_korostishevsky_kanyon/>
**2.** Scroll to travel title

**Actual result:**
Language of travel title is not in Ukrainian

**Expected result:**
Language of travel title in Ukrainian

**Environment:**
MacBook/macOS Ventura 14/Safari Version 17 (19616.1.27.111.16)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/bb87c235-28ca-4d70-97da-89a8c01ed407)

**Comment by scholokov** [comment]
fixed
