### ISSUE TITLE
20190616_korostishevsky_kanyon/In the header block of photo the date of is less than the start date of the trip

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#4349]
**Steps to reproduce: **
**1.** Open page <https://test.long-travel.live/20190616_korostishevsky_kanyon/>
**2.** Scroll to the header block of photo "Ukraine 08.06.2019"

**Actual result:**
 Date header block photo "08.06.2019"

**Expected result: **
Date header block photo "16.06.2019"

**Environment: **
MacBook/macOS Sonoma 14/Safari Version 17.0 (19616.1.27.111.16)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/96a2a316-b638-4d88-856b-fdf7b3537cbb)

**Comment by scholokov** [comment]
fixed
