### ISSUE TITLE
20171027_cherkasy Зайвий URL  у прев'ю при перегляді сторінки подорожі

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4351]
Передумови:

Відкрити:
https://test.long-travel.live/20171027_cherkasy/

Кроки для відтворення:
1. Звернути увагу на прев'ю

Фактичний результат: 
відображається зайвий URL

Очікуваний результат:
Не відображається URL

Вимоги: 
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=0-1&mode=design&t=LCdC0dMiAkc7qpEL-0

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![Черкаси png](https://github.com/scholokov/long-travel-2/assets/140165683/ccc96527-7167-48d1-82e6-e1080064f099)

**Comment by irunabychkovska** [comment]
#3430

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
