### ISSUE TITLE
20170513_putivl_kruti/ The "Киев" name of the city is displayed in the 2nd line of the 1st Standard block "Дорога"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4368]
Steps to reproduce:

1. Open https://test.long-travel.live/20170513_putivl_kruti/
2. Scroll down to the Preview of the 1st Standard "Дорога" block
3. Pay attention to the in the 2nd line of Preview in the 1st Standard "Дорога" block

Actual Result: The "Киев" name of the city is displayed in the 2nd line of the 1st Standard block "Дорога"
Expected Result: The "Київ" name of the city is displayed in the 2nd line of the 1st Standard block "Дорога"

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/8dbe6e6b-bccf-4436-923b-fd5f0a016a3c)

**Comment by ODrobik** [comment]
#3229

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
