### ISSUE TITLE
20180915_buki/Multi tag(transport)header preview other type of travel

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#4369]
**Steps to reproduce: **
**1.** Open page <https://test.long-travel.live/20180915_buki/>
**2.** Scroll to title Preview travels

**Actual result:**
 When opening preview travel multi tag = "zoo.svg"

**Expected result: **
When opening preview travel multi tag = "автомобіль"

**Environment: **
MacBook/macOS Sonoma 14/Safari Version 17.0 (19616.1.27.111.16)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/c08817f7-5f8d-43bc-906f-606d9bcbbb0c)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/e7005735-d73f-4c77-8f19-5f63d5d98dbf)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/0a4e81b9-8b03-426c-9c94-bd1fa2c44f30)

**Comment by scholokov** [comment]
fixed
