### ISSUE TITLE
20190616_korostishevsky_kanyon/Multi tag(transport)header preview other type of travel

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#4370]
/**Steps to reproduce: **
**1.** Open page <https://test.long-travel.live/20190616_korostishevsky_kanyon/>
**2.** Scroll to title Preview travels

**Actual result:**
 When opening preview travel multi tag = "zoo.svg"

**Expected result: **
When opening preview travel multi tag = "автомобіль"

**Environment: **
MacBook/macOS Sonoma 14/Safari Version 17.0 (19616.1.27.111.16)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/8f8546e2-8693-4145-a24b-6d67b71b7ebc)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/304d9b48-c297-4d52-ba90-7ee9659e42b1)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/c2488a23-53a9-43fe-be0f-6e4b61a6a0ca)

**Comment by scholokov** [comment]
fixed
