### ISSUE TITLE
20160710_0807_italy_odessa/The date of waypoint Palm Spa Hotel, Nyírbátor, Hungary is missing on the map

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4384]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the Global Map.
3. Pay attention to the absence of the date of waypoint Palm Spa Hotel, Nyírbátor, Hungary on the Map.

**Actual result:**
The date of waypoint Palm Spa Hotel, Nyírbátor, Hungary is missing on the map
**Expected result:**
The date of waypoint Palm Spa Hotel, Nyírbátor, Hungary is July 10, 2016 on the map

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/2f10c889-d662-4ba5-98db-edf4ec9e23f3)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/33267d5d-8767-4907-8f36-bcd378fda079)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
