### ISSUE TITLE
20160710_0807_italy_odessa/The date of waypoint Hotel-Pension Melcher, Drobollach, Austria is missing on the map #4384

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4385]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the Global Map.
3. Pay attention to the absence of the date of waypoint Hotel-Pension Melcher, Drobollach, Austria on the Map.

**Actual result:**
The date of waypoint Hotel-Pension Melcher, Drobollach, Austria is missing on the map
**Expected result:**
The date of waypoint Hotel-Pension Melcher, Drobollach, Austria is is July 11, 2016  on the map

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/cfb0a9ab-2a7a-4651-8d2c-e8e0415c6b90)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/21bdd4cb-7426-4787-8290-5f25ca8fe0fa)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
