### ISSUE TITLE
20160710_0807_italy_odessa/The date of waypoint Hotel Kopa, Lviv is missing on the map

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4386]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the Global Map.
3. Pay attention to the absence of the date of waypoint Hotel Kopa, Lviv on the Map.

**Actual result:**
The date of waypoint Hotel Kopa, Lviv is missing on the map
**Expected result:**
The date of waypoint Hotel Kopa, Lviv is July 23, 2016 on the map

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/5d75e62b-70c2-42c5-b016-4adb0ea7710b)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/8d5dfc08-0cc0-476d-b466-3fd7872ff022)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
