### ISSUE TITLE
20160710_0807_italy_odessa/The date of waypoint Miniatures, Viserbella, Italy is July 1, 2016 on the map

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4387]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the Global Map.
3. Pay attention to the date of waypoint Miniatures, Viserbella, Italy on the Map.

**Actual result:**
The date of waypoint Miniatures, Viserbella, Italy is July 1, 2016 on the map
**Expected result:**
The date of waypoint Miniatures, Viserbella, Italy is July 16, 2016 on the map

**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/3f0137bf-20ee-4e1e-a700-dd1f199222b5)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/be5f90b3-bc9a-43a9-8096-fd9301d37657)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
