### ISSUE TITLE
20160710_0807_italy_odessa/The date of waypoint San Marino, San Marino is July 1, 2016 on the map

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4388]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the Global Map.
3. Pay attention to the date of waypoint San Marino, San Marino on the Map.

**Actual result:**
The date of waypoint San Marino, San Marino is July 1, 2016 on the map
**Expected result:**
The date of waypoint San Marino, San Marino is July 17, 2016 on the map
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/6d272899-7c85-4974-8441-17d82a14961f)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/5bf729c0-49ee-4de7-8672-efb156c48fed)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
