### ISSUE TITLE
20160710_0807_italy_odessa/The date of waypoint Residence Domus, Rimini, Italy is July 1, 2016 on the map

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4391]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the Global Map.
3. Pay attention to the date of waypoint Residence Domus, Rimini, Italy on the Map.

**Actual result:**
The date of waypoint Residence Domus, Rimini, Italy is July 1, 2016 on the map
**Expected result:**
The date of waypoint Residence Domus, Rimini, Italy is July 13, 2016 on the map
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)

**Requirements:** https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/c6f45988-b021-4f9f-ab76-a2583f01fc98)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/87a0d0f4-a3ca-4053-9d6d-95800d9c478d)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
