### ISSUE TITLE
20160710_0807_italy_odessa/The size of the flag of Ukraine in the block: Road Kyiv – Nyírbátor is 26x18

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4398]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the block Road Kyiv – Nyírbátor.
3. Pay attention to the size of the flag of Ukraine in the right side of the block.

**Actual result:**
The size of the flag of Ukraine in the block: Road Kyiv – Nyírbátor is 26x18
**Expected result:**
The size of the flag of Ukraine in the block: Road Kyiv – Nyírbátor is 36x24
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&mode=design&t=ONAqLNGHuOkjuVAh-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/74327601-b835-4080-a10c-5e0066ed041b)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/6bd24cb7-dfb7-47e9-be51-69c2ef248ff4)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
