### ISSUE TITLE
20200918_20_kharkiv Слово готель і його назва  в прев'ю галереї відображається російською мовою

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4399]
Передумови:

Відкрити:
https://test.long-travel.live/20200918_20_kharkiv/

Кроки для відтворення:
1. Звернути увагу на мову назви готелю

Фактичний результат: 
Слово готель і його назва написана російською мовою

Очікуваний результат:
Назва готелю написана українською мовою

Вимоги: 
https://qax.gitbook.io/qax-travel/requirements/4.travel

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![Мова назви готелю](https://github.com/scholokov/long-travel-2/assets/140165683/24aa4e96-9b6e-4c10-b74a-201fcba17db9)

**Comment by irunabychkovska** [comment]
#4091

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
