### ISSUE TITLE
20200918_20_kharkiv Назва міста дороги у описі відео написана російською мовою

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4400]
Передумови:

Відкрити:
https://test.long-travel.live/20200918_20_kharkiv/

Кроки для відтворення:
1. Звернути увагу на мову назви міста дороги:  Харків-Київ

Фактичний результат: 
Назва міста дороги: Харків-Київ відображається частково російською мовою

Очікуваний результат:
Назва міста дороги: Харків-Київ відображається частково українською  мовою

Вимоги: 
https://qax.gitbook.io/qax-travel/requirements/4.travel

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![назва міста Київ13](https://github.com/scholokov/long-travel-2/assets/140165683/35b66a00-ec7e-4974-914b-20259009adec)

**Comment by irunabychkovska** [comment]
#4091

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
