### ISSUE TITLE
20200918_20_kharkiv Відсутній тег автомобіля у верхньому лівому куті при перегляді прев'ю

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4412]
Передумови:

Відкрити:
https://test.long-travel.live/20200918_20_kharkiv/

Кроки для відтворення:
1. Звернути увагу на тег автомобіля у лівому верхньому куті прев'ю

Фактичний результат: 
тег автомобіля не відображається

Очікуваний результат:
тег автомобіля відображається

Вимоги: 
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-6&mode=design&t=Q5AaoBdrhyaCivC2-0

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![тег Харків](https://github.com/scholokov/long-travel-2/assets/140165683/021b4915-09b5-47d6-be2c-d0634b47b7b0)

**Comment by irunabychkovska** [comment]
#4091

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
