### ISSUE TITLE
20160710_0807_italy_odessa/The size of the flag of Austria in the block: Road Nyírbátor – Drobollach is 26x18

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4415]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the block Road Nyírbátor – Drobollach.
3. Pay attention to the size of the flag of Austria in the right side of the block.

**Actual result:**
The size of the flag of Austria in the block: Road Nyírbátor – Drobollach is 26x18
**Expected result:**
The size of the flag of Austria in the block: Road Nyírbátor – Drobollach is 36x24
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&mode=design&t=ONAqLNGHuOkjuVAh-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/2ac06a22-43d2-458a-a382-291a9cd5bfd9)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/95aa0700-b144-4a36-8c4d-7c2a7f64089f)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
