### ISSUE TITLE
20160710_0807_italy_odessa/The size of the flag of Austria in the block: Hotel-Pension Melcher is 26x18

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4417]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the block Hotel-Pension Melcher
3. Pay attention to the size of the flag of Austria in the right side of the block.

**Actual result:**
The size of the flag of Austria in the block: Hotel-Pension Melcher is 26x18
**Expected result:**
The size of the flag of Austria in the block: Hotel-Pension Melcher is 36x24
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&mode=design&t=ONAqLNGHuOkjuVAh-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/b577ce5d-7413-44f9-bbd2-f13aabe1777a)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/40332e1a-de26-4bba-8faf-39293cffc1ce)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
