### ISSUE TITLE
20160710_0807_italy_odessa/The size of the flag of Austria in the block: Drobollach is 26x18

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4418]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the block Drobollach
3. Pay attention to the size of the flag of Austria in the right side of the block.

**Actual result:**
The size of the flag of Austria in the block: Drobollach is 26x18
**Expected result:**
The size of the flag of Austria in the block: Drobollach is 36x24
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&mode=design&t=ONAqLNGHuOkjuVAh-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/3d4bdf1e-10f6-412b-b294-628627b1487f)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/5b5b66c6-73e5-4d2a-a40d-e0b6251cfd7c)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
