### ISSUE TITLE
20160710_0807_italy_odessa/The size of the flag of Austria in the block: Austria is 26x18

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4419]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the block Austria.
3. Pay attention to the size of the flag of Austria in the right side of the block.

**Actual result:**
The size of the flag of Austria in the block: Austria is 26x18
**Expected result:**
The size of the flag of Austria in the block: Austria is 36x24
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&mode=design&t=ONAqLNGHuOkjuVAh-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/bf669b81-f857-426a-80cd-428236160d06)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/cfadf0c8-903f-4152-86aa-6bbdbb8f8e91)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
