### ISSUE TITLE
20160710_0807_italy_odessa/The size of the flag of Italy in the block: Road Drobollach – Italy is 26x18

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4420]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the block Road Drobollach – Italy.
3. Pay attention to the size of the flag of Italy in the right side of the block.

**Actual result:**
The size of the flag of Italy in the block: Road Drobollach – Italy is 26x18
**Expected result:**
The size of the flag of Italy in the block: Road Drobollach – Italy is 36x24
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&mode=design&t=ONAqLNGHuOkjuVAh-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/9b9070a3-cf6a-4f07-b8d0-2674526dd4c2)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/b44aec19-2933-470b-a563-4ca057685d5d)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
