### ISSUE TITLE
20160710_0807_italy_odessa/The size of the flag of Italy in the block: Residence Domus is 26x18

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4421]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the block Residence Domus.
3. Pay attention to the size of the flag of Italy in the right side of the block.

**Actual result:**
The size of the flag of Italy in the block: Residence Domus is 26x18
**Expected result:**
The size of the flag of Italy in the block: Residence Domus is 36x24
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&mode=design&t=ONAqLNGHuOkjuVAh-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/d5306f15-265c-4a4e-9527-9807281aca2a)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/4e8cdd02-36bb-42c9-ba7b-4db511c74ba9)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
