### ISSUE TITLE
20190720_0811_balcans Тег автомобіля відображається у вигляді тварини при перегляді прев'ю

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4422]
Передумови:

Відкрити:
https://test.long-travel.live/20190720_0811_balcans/

Кроки для відтворення:
1.Звернути увагу на тег у лівому верхньому куті

Фактичний результат: 
Тег відображається у вигляді тварини

Очікуваний результат:
Відображається тег автомобіля

Вимоги: 
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![тег балкани ](https://github.com/scholokov/long-travel-2/assets/140165683/bdb44982-b1a6-4541-ab2d-e3cfbf571c1c)

**Comment by irunabychkovska** [comment]
#4076

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
