### ISSUE TITLE
20200918_20_kharkiv Відсутнє прев'ю фотогалереї перед кнопкою "Відобразити галерею" при перегляді галереї

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4424]
Передумови:

Відкрити:
https://test.long-travel.live/20200918_20_kharkiv/

Кроки для відтворення:
1. Звернути увагу на відображення прев'ю фотогалереї

Фактичний результат: Не відображається прев'ю у фотогалереї: "Харків 19.09.2020", "Ресторан Віват Провінція Тахтаулове
20.09.2020"

Очікуваний результат:
Відображається прев'ю

Вимоги: 
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-6&mode=design&t=h3GNPJgRFsQJMpvZ-0

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![Немає превю ](https://github.com/scholokov/long-travel-2/assets/140165683/e30947fa-ffa1-439a-b182-a74e33ec7aed)

![Превю відсутнє png](https://github.com/scholokov/long-travel-2/assets/140165683/7b736756-8d2f-46a5-a12f-9069d0a9f372)

**Comment by irunabychkovska** [comment]
#4091

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
