### ISSUE TITLE
Відсутній тег автомобіля у лівому верхньому куті прев'ю при перегляді прев'ю

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4425]
Передумови:

Відкрити:
https://test.long-travel.live/20171027_cherkasy/

Кроки для відтворення:
1. Звернути увагу  на відображення тегу автомобіля

Фактичний результат: 
Тег автомобіля не відображається

Очікуваний результат:
тег автомобіля відображається

Вимоги: 
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-6&mode=design&t=h3GNPJgRFsQJMpvZ-0

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![тег відсутній](https://github.com/scholokov/long-travel-2/assets/140165683/11111e1c-2997-465d-867a-41f97ba37c26)

**Comment by irunabychkovska** [comment]
#3430

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
