### ISSUE TITLE
20190720_0811_balcans Однакові  дві фотографії відображаються у блоці фотогалерея при перегляді фотографій

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4432]
Передумови:

Відкрити:
https://test.long-travel.live/20190720_0811_balcans/

Кроки для відтворення:
1. Прогорнути сторінку до галереї "Albania Tirana"
2. Звернути увагу на повторні фотографії

Фактичний результат: 
дві фотографії повторюються у галереї "Albania Tirana"

Очікуваний результат:
Фотографія не повторюється, всі різні

Вимоги: 
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![дубль ](https://github.com/scholokov/long-travel-2/assets/140165683/4b6d8c38-5b20-415a-bdfa-b143507b43b2)

**Comment by irunabychkovska** [comment]
#4076

**Comment by scholokov** [comment]
please retest

**Comment by irunabychkovska** [comment]
ок

**Comment by Illia2810** [comment]
verified
