### ISSUE TITLE
20190616_korostishevsky_kanyon/Language of the city and name canyon  in Russian

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#4434]
**Steps to reproduce:**

**1.** Open page <https://test.long-travel.live/20190616_korostishevsky_kanyon/>
**2.** Scroll through all block names

**Actual result:**
Language of the city and canyon is not in Ukrainian

**Expected result:**
Language of the city and canyon in Ukrainian

**Environment:**
MacBook/macOS Ventura 14/Safari Version 17 (19616.1.27.111.16)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/227fa4d2-4e5c-41c9-aa58-a5ee2cf38b2e)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/768d51f6-125c-41d8-bcf1-41009aca8b0a)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/4003e667-e37a-4a47-8d69-70c6d26263fa)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/dba76350-9001-457b-b5a5-637ca9eed4ae)

**Comment by scholokov** [comment]
fixed
