### ISSUE TITLE
20180915_buki/Errors name of the city "Біла церква"

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#4435]
**Steps to reproduce:**

**1.** Open page <https://test.long-travel.live/20180915_buki/>
**2.** Scroll through all block names

**Actual result:**
The name of the city is not in Ukrainian

**Expected result:**
The name of the city in Ukrainian

**Environment:**
MacBook/macOS Ventura 14/Safari Version 17 (19616.1.27.111.16)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/e73b5a17-05cd-4f68-803a-a3791f7bf387)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/66e5db9f-42a3-45ed-81cb-3b9c83d6d059)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/ac96a328-45bb-44c1-b706-c973e105eead)

**Comment by DmytroMarkulych** [comment]
давайте замінемо слово incorrect на більш конкретне

**Comment by SerhiiBurdieiev** [comment]
Corrected.

**Comment by scholokov** [comment]
fixed
