### ISSUE TITLE
20160710_0807_italy_odessa/The size of the flag of Italy in the block: Beach Italy is 26x18

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4438]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the block Beach Italy.
3. Pay attention to the size of the flag of Italy in the right side of the block.

**Actual result:**
The size of the flag of Italy in the block: Beach Italy is 26x18
**Expected result:**
The size of the flag of Italy in the block: Beach Italy is 36x24
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&mode=design&t=ONAqLNGHuOkjuVAh-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/af42b0df-efe5-4d92-8da0-5681d9fb0e34)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/56ba9a71-9e4e-4b7a-986a-257928f3e805)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
