### ISSUE TITLE
20160710_0807_italy_odessa/The size of the flag of Italy in the block: Miniatures is 26x18

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4440]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the block Miniatures.
3. Pay attention to the size of the flag of Italy in the right side of the block.

**Actual result:**
The size of the flag of Italy in the block: Miniatures is 26x18
**Expected result:**
The size of the flag of Italy in the block: Miniatures is 36x24
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&mode=design&t=ONAqLNGHuOkjuVAh-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/070faa45-abb8-43a8-b489-3161797b9902)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/f77f5951-86a4-4e91-8934-15c907db0aa4)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
