### ISSUE TITLE
20170513_putivl_kruti/ The Flag of the country is not displayed in the 2nd Standard block "Дорога"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4444]
Steps to reproduce:

1. Open https://test.long-travel.live/20170513_putivl_kruti/
2. Scroll down to the Preview of the 2nd Standard "Дорога" block after 1st Standard "Дорога"
3. Pay attention to the absence of a flag in the 2nd Standard "Дорога" block

Actual Result: The Flag of the country is not displayed in the 2nd Standard block "Дорога" on the right side

Expected Result: The Flag of the country is displayed in the 2nd Standard block "Дорога" on the right side

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/c308b17f-6246-4dfe-82dc-91b3a320d2b6)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
