### ISSUE TITLE
20170521_korosten / The drop-down list on the Map of the Tralel is present

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4445]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170521_korosten/
2. Pay attention to the presence drop-down list on the Map.

**Actual Result:** 
The drop-down list on the Map of the Tralel is present.

**Expected Result:** 
The drop-down list on the Map of the Tralel is absent.

**Additional information:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/9d06a9ea-c166-4ca3-b3c0-62169b63fce8)

**Comment by GNatala** [comment]
#1350

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
