### ISSUE TITLE
20200918_20_kharkiv У прев'ю фотогалереї  не відображається прапор України при перегляді прев'ю

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4447]
Передумови:

Відкрити:
https://test.long-travel.live/20200918_20_kharkiv/

Кроки для відтворення:
1. Звернути увагу на відображення прапора України у прев'ю фотогалереї : Харків 19.09.2020

Фактичний результат: 
Прапор України не відображається

Очікуваний результат:
прапор України відображається

Вимоги: 
https://qax.gitbook.io/qax-travel/requirements/4.travel

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![прапор](https://github.com/scholokov/long-travel-2/assets/140165683/f74d72fd-044c-4e32-8823-12223cc309ed)

**Comment by irunabychkovska** [comment]
#4091

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/long-travel-2/assets/88647733/e8338cbc-90bb-45c4-8ee5-180919ca0ebb)

**Comment by irunabychkovska** [comment]
воно чомусь мені інколи не дозволяє проставляти

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
