### ISSUE TITLE
20160710_0807_italy_odessa/The size of the flag of Germany in the block: Road Beilngries – Krakow is 26x18

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4451]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the block Road Beilngries – Krakow.
3. Pay attention to the size of the flag of Germany in the right side of the block.

**Actual result:**
The size of the flag of Germany in the block: Road Beilngries – Krakow is 26x18
**Expected result:**
The size of the flag of Germany in the block: Road Beilngries – Krakow is 36x24
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&mode=design&t=ONAqLNGHuOkjuVAh-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/67e46d66-112b-49a5-bdea-5fdef70d736a)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/1d5e1278-83dc-49f5-a722-82be502aefa4)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/long-travel-2/assets/88647733/f1f962ed-8925-4b83-8a00-8eac6dd47e03)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
