### ISSUE TITLE
20160710_0807_italy_odessa/The size of the flag of Poland in the block: Road Beilngries – Krakow is 26x18

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4452]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the block Road Beilngries – Krakow.
3. Pay attention to the size of the flag of Poland in the right side of the block.

**Actual result:**
The size of the flag of Poland in the block: Road Beilngries – Krakow is 26x18
**Expected result:**
The size of the flag of Poland in the block: Road Beilngries – Krakow is 36x24
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&mode=design&t=ONAqLNGHuOkjuVAh-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/d44ca9e6-e550-4038-a84a-245e0b6dc136)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/ff17db7d-7af5-4b68-9021-ae517ff945cf)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
