### ISSUE TITLE
20160710_0807_italy_odessa/The size of the flag of Ukraine in the block: Hotel Kopa is 16x11

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4454]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the block Hotel Kopa.
3. Pay attention to the size of the flag of Ukraine in the right side of the block.

**Actual result:**
The size of the flag of Ukraine in the block: Hotel Kopa is 16x11
**Expected result:**
The size of the flag of Ukraine in the block: Hotel Kopa is 36x24
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&mode=design&t=ONAqLNGHuOkjuVAh-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/1258aa52-01c0-4544-9ab0-53bc5847144b)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/94931571-8e4e-460e-947e-372bb3b0baeb)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
