### ISSUE TITLE
20160710_0807_italy_odessa/The flag of Poland in the Hotel Kopa block is an extra element

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4455]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the block Hotel Kopa.
3. Pay attention to the flag of Poland in the right side of the block.

**Actual result:**
The flag of Poland in the Hotel Kopa block is an extra element.
**Expected result:**
The flag of Poland in the Hotel Kopa block is missing.
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/4aaf2f9b-ae83-472b-a1aa-6ad1eda1e532)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/d307394e-af36-4ea1-89ed-9dfbd381f604)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
