### ISSUE TITLE
20160710_0807_italy_odessa/The date in the Preparation for Odessa block is an extra element

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4461]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the Preparation for Odessa block.
3. Pay attention to the date in the left side of the block.

**Actual result:**
The date in the Preparation for Odessa block is an extra element.
**Expected result:**
The date in the Preparation for Odessa block is missing.
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/b66f052d-1125-4311-a8f6-fd6b6b6f8103)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/1948ec99-2b06-47a8-a5b0-c72a661563f4)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
