### ISSUE TITLE
20160710_0807_italy_odessa/The size of the flag of Ukraine in the block: Road Kyiv - Sergiivka is 16x11

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4462]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the block Road Kyiv - Sergiivka.
3. Pay attention to the size of the flag of Ukraine in the right side of the block.

**Actual result:**
The size of the flag of Ukraine in the block: Road Kyiv - Sergiivka is 16x11
**Expected result:**
The size of the flag of Ukraine in the block: Road Kyiv - Sergiivka is 36x24
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&mode=design&t=ONAqLNGHuOkjuVAh-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/c134aa0f-f82d-4878-9732-8db7a9d89ce1)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/ccadb9d3-57dc-4ec5-a3c2-2ed8db32ea6e)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
