### ISSUE TITLE
20160710_0807_italy_odessa/The size of the flag of Ukraine in the Sergiivka block is 16x11

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4464]
**Steps to retroduce:**

1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the Sergiivka block.
3. Pay attention to the size of the flag of Ukraine in the right side of the block.

**Actual result:**
The size of the flag of Ukraine in the Sergiivka block is 16x11
**Expected result:**
The size of the flag of Ukraine in the Sergiivka block is 36x24
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&mode=design&t=ONAqLNGHuOkjuVAh-0

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/81f12fba-8a67-4bfb-9687-a6785dd04761)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/b9f124fd-bdf6-4537-a189-530a12ca47bf)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
