### ISSUE TITLE
20160710_0807_italy_odessa/The date in the Sergiivka block is missing

### ISSUE THREAD

**Issue by prokopenkoga1977** [scholokov/long-travel-2#4465]
**Steps to retroduce:**
1. Open https://test.long-travel.live/20160710_0807_italy_odessa/
2. Scroll down to the Sergiivka block.
3. Pay attention to the absence of the date in the block.

**Actual result:**
The date in the Sergiivka block is missing.
**Expected result:**
The date in the Sergiivka block is present.
**Environment:**
Windows 10 Home edition (x64)
Google Chrome v.110.0.5481.178 (x64)
**Requirements:** https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/62c5f492-6fd1-4c18-a23c-3ce128ef70be)

**Attachments:**

![Image](https://github.com/scholokov/long-travel-2/assets/125134112/bb5fd7da-7dca-4434-8a82-a03cec023ea0)

**Comment by scholokov** [comment]
fixed

**Comment by prokopenkoga1977** [comment]
Passed
