### ISSUE TITLE
Travels / The name of the tag is "Військовий музей" in the Filter "Визначна пам'ятка"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4484]
**Steps to reproduce:**

1. Open https://test.long-travel.live/travels/
2. Pay attention to tag "Військовий музей" in the Filter "Визначна пам'ятка" .

**Actual Result:** 
The name of the tag is **"Військовий музей"** in the Filter "Визначна пам'ятка".

**Expected Result:** 
**The name of the tag is "Військовий об'єкт"** in the Filter "Визначна пам'ятка".

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/0fbcbfdb-4d7c-47d9-8db4-157d8bed971c)

**Comment by GNatala** [comment]
An issue is reproduced.
Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/101987790/6ac93d06-8f4b-4155-a79b-d5dff1667b13)

**Comment by scholokov** [comment]
fixed

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
