### ISSUE TITLE
Цікаві місця - Зоопарки - Block "Одеський дельфінарій НЕМО" isn't sorted by time

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4487]
**Steps of reproducing**
1. https://test.long-travel.live/zoo/
2. Scroll to "Одеський дельфінарій НЕМО" block

**Actual Result**
Block "Одеський дельфінарій НЕМО" isn't sorted by time

**Expected Result**
Block "Одеський дельфінарій НЕМО" is sorted by time

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/places

**Enviroments**
Windows 10, Chrome 117.0.5938.92 (64 bit)
![Зоопарки – Long-Travel - Google Chrome 27 09 2023 16_12_35](https://github.com/scholokov/long-travel-2/assets/95171672/966c1069-1bae-48f0-8164-4dc4273b0e08)

**Comment by DmitriiNasonov** [comment]
#4206

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
