### ISSUE TITLE
Цікаві місця - Зоопарки - Block "Zoloski vrt grada Zagreba, Zoo" isn't sorted by time

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4488]
**Steps of reproducing**
1. https://test.long-travel.live/zoo/
2. Scroll to "Zoloski vrt grada Zagreba, Zoo" block

**Actual Result**
Block "Zoloski vrt grada Zagreba, Zoo" isn't sorted by time

**Expected Result**
Block "Zoloski vrt grada Zagreba, Zoo" is sorted by time

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/places

**Enviroments**
Windows 10, Chrome 117.0.5938.92 (64 bit)
![Зоопарки – Long-Travel - Google Chrome 27 09 2023 16_20_27](https://github.com/scholokov/long-travel-2/assets/95171672/2679a2c0-c108-4a06-b52c-f98b6f4b885e)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
