### ISSUE TITLE
Цікаві місця - Зоопарки - Block "Tiergarten Schoenbrunn, Zoo" isn't sorted by time

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4489]
**Steps of reproducing**
1. https://test.long-travel.live/zoo/
2. Scroll to "Tiergarten Schoenbrunn, Zoo" block

**Actual Result**
Block "Tiergarten Schoenbrunn, Zoo" isn't sorted by time

**Expected Result**
Block "Tiergarten Schoenbrunn, Zoo" is sorted by time

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/places

**Enviroments**
Windows 10, Chrome 117.0.5938.92 (64 bit)
![Зоопарки – Long-Travel - Google Chrome 27 09 2023 16_20_38](https://github.com/scholokov/long-travel-2/assets/95171672/4599ff78-0e02-45ee-99ca-8e93e56938e6)

**Comment by DmitriiNasonov** [comment]
#4206

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
