### ISSUE TITLE
Цікаві місця - Зоопарки - Block "Zoo (Хуст)" isn't sorted by time

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4490]
**Steps of reproducing**
1. https://test.long-travel.live/zoo/
2. Scroll to "Zoo (Хуст)" block

**Actual Result**
Block "Zoo (Хуст)" isn't sorted by time

**Expected Result**
Block "Zoo (Хуст)" is sorted by time

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/places

**Enviroments**
Windows 10, Chrome 117.0.5938.92 (64 bit)
![Зоопарки – Long-Travel - Google Chrome 27 09 2023 16_22_20](https://github.com/scholokov/long-travel-2/assets/95171672/504f3d39-90ca-48f6-9069-9818cbce1aea)

**Comment by DmitriiNasonov** [comment]
#4206

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
