### ISSUE TITLE
20170513_putivl_kruti/The Map of the travel is not displayed in the Map block

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4492]
Steps to reproduce:

1. Open https://test.long-travel.live/20170513_putivl_kruti/
2. Scroll down to the Map block after Preview of the travel
3. Pay attention to the location of the Map in the Map block

Actual Result: The Map of the travel **is not displayed** in the Map block
Expected Result: The Map of the travel **is displayed** in the Map block

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/93534701-549f-4fbf-92ed-8f1d542f8f1d)

**Comment by ODrobik** [comment]
#3229

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
