### ISSUE TITLE
20170513_putivl_kruti/ The "Україна" country is displayed in the 2nd line of the Standard block "Дорога" 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4493]
Steps to reproduce:

1. Open https://test.long-travel.live/20170513_putivl_kruti/
2. Scroll down to the Preview of the Standard "Дорога" block at the end of the page
3. Pay attention to the in the 2nd line of Preview in the Standard "Дорога" block

Actual Result: The "Україна" country is displayed in the 2nd line of the Standard block "Дорога"
Expected Result: The "Україна" country is displayed as a country flag in the 2nd line of the Standard block "Дорога"

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/e99bbabf-10d8-4f3e-b7aa-c281ba78c9ee)

**Comment by ODrobik** [comment]
#3229

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
