### ISSUE TITLE
20200918_20_kharkiv Прапор України відсутній праворуч при перегляді прев"ю

### ISSUE THREAD

**Issue by irunabychkovska** [scholokov/long-travel-2#4506]
Передумови:

Відкрити:
https://test.long-travel.live/20200918_20_kharkiv/

Кроки для відтворення:
1. звернути увагу на відображення прапора у прев'ю

Фактичний результат: 
прапор України не відображається

Очікуваний результат:
прапор України відображається

Вимоги: 
https://qax.gitbook.io/qax-travel/requirements/4.travel

Середовище: Windows 10  Операційна
система:
Браузер: Google Chrome Version 110.0.5481.104

![віват провінція](https://github.com/scholokov/long-travel-2/assets/140165683/4e8b93a4-ebd8-4e07-ab32-fbb54c0de308)

**Comment by irunabychkovska** [comment]
# 4091

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
