### ISSUE TITLE
"Горні дороги" / Block's content "n339, Serra da Estrela Natural Park" is in russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4517]
**Steps to reproduce:**

1. Open https://test.long-travel.live/m-road/
2. Pay attention to the language of the block's content "n339, Serra da Estrela Natural Park".

**Actual result:**
Block's content "n339, Serra da Estrela Natural Park" - "**n339 – самая красивая высокогорная дорога Португалии, очень-очень круто.**" is in russian

**Expected result:**
Block's content "n339, Serra da Estrela Natural Park" - "**n339 – самая красивая высокогорная дорога Португалии, очень-очень круто.**" is in Ukrainian.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/3e37ec30-8afe-4690-a38e-f2d426f4191a)

**Comment by GNatala** [comment]
#4207

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
