### ISSUE TITLE
"Горні дороги" / Block's content "n338, Serra da Estrela Natural Park" is in russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4518]
**Steps to reproduce:**

1. Open https://test.long-travel.live/m-road/
2. Pay attention to the language of the block's content "n338, Serra da Estrela Natural Park".

**Actual result:**
Block's content "n338, Serra da Estrela Natural Park" - "**Замечательная дорога с потрясающими видами, вторая по красоте после n339.**" is in russian

**Expected result:**
Block's content "n338, Serra da Estrela Natural Park" - "**Замечательная дорога с потрясающими видами, вторая по красоте после n339.**" is in Ukrainian.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/b1883aaa-e0cc-4e23-9edd-a517007ae4c7)

**Comment by GNatala** [comment]
#4207

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
