### ISSUE TITLE
20170513_putivl_kruti/The "Дорога - Крути - Киев" name of the block is displayed in the 1st line of the 3nd Standard block "Дорога"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4526]
Steps to reproduce:

1. Open https://test.long-travel.live/20170513_putivl_kruti/
2. Scroll down to the Preview of the 3nd Standard "Дорога" block
3. Pay attention to the in the 1st line of Preview in the 3nd Standard "Дорога" block

Actual Result: The "Дорога - Крути - Киев" name of the block is displayed in the 1st line of the 3nd Standard block "Дорога"
Expected Result: The "Дорога" name of the block is displayed in the 1st line of the 3nd Standard block "Дорога"

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/2247782c-8872-44a2-ac5d-ed5b6fd9fda6)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
