### ISSUE TITLE
20170513_putivl_kruti/The date of the travel is not displayed in the 3nd line of the 3nd Standard block "Дорога"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4528]
Steps to reproduce:

1. Open https://test.long-travel.live/20170513_putivl_kruti/
2. Scroll down to the Preview of the 3nd Standard "Дорога" block
3. Pay attention to the in the 3nd line of Preview in the 3nd Standard "Дорога" block

Actual Result: The date of the travel is not displayed in the 3nd line of the 3nd Standard block "Дорога"
Expected Result: The "13.05.2017" date of the travel is displayed in the 3nd line of the 3nd Standard block "Дорога"

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/c60b5967-3d35-45b3-8116-4114e9e81e57)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
