### ISSUE TITLE
20191019_roshen/Language of the city and country in Russian

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#4532]
**Steps to reproduce:**

**1.** Open page <https://test.long-travel.live/20191019_roshen/>
**2.** Scroll through all block names

**Actual result:**
Language of the city and country is not in Ukrainian

**Expected result:**
Language of the city and country in Ukrainian

**Environment:**
MacBook/macOS Ventura 14/Safari Version 17.1 (19616.2.8.11.2)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/22488a75-dc48-4953-a2ae-236624855472)

**Comment by scholokov** [comment]
fixed
