### ISSUE TITLE
20200104_07_berlin/Missing photo of travel preview

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#4533]
**Steps to reproduce:**
**1.** Open page <https://test.long-travel.live/20200104_07_berlin/>
**2.** Scroll to header block "Berlin"

**Actual result:**
No photo of travel preview

**Expected result:**
There is a photo preview of the trip

**Environment:**
MacBook/macOS Sonoma 14/Safari Version 17.1 (19616.2.8.11.2)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/b3c4a11b-c706-45e8-a45f-16a17fb9eee9)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/ad424619-c330-469a-bdd0-cb8451ac9224)

**Comment by scholokov** [comment]
fixed
