### ISSUE TITLE
20200104_07_berlin/City language and airport names in Russian

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#4534]
**Steps to reproduce:**

**1.** Open page <https://test.long-travel.live/20200104_07_berlin/>
**2.** Scroll through all block names

**Actual result:**
Language of the city and airport is not in Ukrainian(English)

**Expected result:**
Language of the city and airport in Ukrainian(English)

**Environment:**
MacBook/macOS Ventura 14/Safari Version 17.1 (19616.2.8.11.2)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/7f4b65e6-444c-44ec-b055-10d40ad8ec83)

![Image](https://github.com/scholokov/long-travel-2/assets/108996909/97e03481-8f0b-4f6a-ab41-ff16eae6d4c1)

**Comment by scholokov** [comment]
fixed
