### ISSUE TITLE
20190608_boguslav - Preview of the travel - Tags is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4540]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190608_boguslav/
2. Pay attention to the preview of the travel

**Actual Result**
Tags is missing

**Expected Result**
Tags is present

**Additional information**
List of missed tags: "Автомобіль", "Річка-Озеро", "Цікаво"
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1
https://qax.gitbook.io/qax-travel/requirements/4.travel/tags

**Enviroments**
Windows 10, Chrome 117.0.5938.150 (64 bit), Firefox 118.0.1 (64 bit)
Android 8.1.0, Chrome 117.0.5938.153, Firefox 118.1.1
![Чайки – Long-Travel - Google Chrome 11 10 2023 13_42_00](https://github.com/scholokov/long-travel-2/assets/95171672/42537df8-2b40-48cc-94c6-d693e3c20795)
![photo_2023-10-11_13-42-05](https://github.com/scholokov/long-travel-2/assets/95171672/0689ed20-b814-4ffa-85b4-e299bcc8ae92)

**Comment by DmitriiNasonov** [comment]
#4074

**Comment by scholokov** [comment]
які саме відсутні?
є вимоги з тегами по кожній подорожі

**Comment by DmitriiNasonov** [comment]
bug-report is fixed

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
