### ISSUE TITLE
20170513_putivl_kruti/ The "Киев" name of the city is displayed in the 2nd line of the 3nd Standard block "Дорога" in the end of the page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4541]
Steps to reproduce:

1. Open https://test.long-travel.live/20170513_putivl_kruti/
2. Scroll down to the Preview of the 3nd Standard "Дорога" block
3. Pay attention to the in the 2nd line of Preview in the 3nd Standard "Дорога" block

Actual Result: The "Киев" name of the city is displayed in the 2nd line of the 3nd Standard block "Дорога" in the end of the page

Expected Result: The "Київ" name of the city is displayed in the 2nd line of the 3nd Standard block "Дорога" in the end of the page

Requirements: https://qax.gitbook.io/qax-travel/requirements/1.overall/language

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/34ac4354-3724-4343-a33e-562b1c3e0c2e)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
