### ISSUE TITLE
20170513_putivl_kruti/The Preview of the "Museum" Standard block is not displayed in the page of the travel 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4542]
Steps to reproduce:

1, Open https://test.long-travel.live/20170513_putivl_kruti/
2, Scroll down to the Preview of the 3nd Standard "Дорога" block
3, Pay attention to the in the 2nd line of Preview in the 3nd Standard "Дорога" block

Actual Result: The Preview of the "Museum" Standard block is not displayed in the page of the travel 

Expected Result: The Preview of the "Museum" Standard block is displayed in the page of the travel 

Requirements:https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/484096de-4e26-48a2-8c02-d84644197c08)

**Comment by ODrobik** [comment]
#3229

**Comment by scholokov** [comment]
fixed
