### ISSUE TITLE
Regression / Links of Elements of the header - "Logo", "Головна", "Подорожі", "Цікаві місця" lead to the test environment

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4544]
**Steps to reproduce:**

1. Open https://long-travel.live/
2. Click on any element of the header - "Logo", "Головна", "Подорожі", "Цікаві місця".
4. The link leads to the test environment.

**Actual Result:**
Links of Elements of the header - "Logo", "Головна", "Подорожі", "Цікаві місця" lead to the test environment.

**Expected Result:**
Links of Elements of the header - "Logo", "Головна", "Подорожі", "Цікаві місця" lead to the production environment.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/101987790/b7d24a14-dc34-44c5-beb3-bf436c324e2a)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed

**Comment by GNatala** [comment]
#4557
