### ISSUE TITLE
Чайки 2019 - Map - Drop-down list with a travels is present

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4545]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190608_boguslav/
2. Scroll to Map
3. Pay attention to drop-down list with a travels is present

**Actual Result**
Drop-down list with a travels is present

**Expected Result**
Drop-down list with a travels is missing

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Enviroments**
Windows 10, Chrome 118.0.5993.71 (64 bit)
Android 8.1.0, Chrome 117.0.5938.153
![Чайки 2019 – Long-Travel - Google Chrome 17 10 2023 15_45_53](https://github.com/scholokov/long-travel-2/assets/95171672/e15c64e8-3812-46d6-9dec-72cfe11d6f4d)
![photo_2023-10-17_15-46-09](https://github.com/scholokov/long-travel-2/assets/95171672/41aa907c-d2d8-4879-9898-ec08ab4893e5)

**Comment by DmitriiNasonov** [comment]
#4074

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
