### ISSUE TITLE
Чайки 2019 - Map - Preview photo is missing in block "Маршрут подорожі"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4547]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190608_boguslav/
2. Scroll to Map
3. Pay attention to block "Маршрут подорожі"

**Actual Result**
Preview photo is missing in block "Маршрут подорожі"

**Expected Result**
Preview photo is present in block "Маршрут подорожі"

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Enviroments**
Windows 10, Chrome 118.0.5993.71 (64 bit)
Android 8.1.0, Chrome 117.0.5938.153
![Чайки 2019 – Long-Travel - Google Chrome 17 10 2023 16_08_45](https://github.com/scholokov/long-travel-2/assets/95171672/925c15e1-b7cb-4ca9-a5ef-d986013beacf)
![photo_2023-10-17_16-08-38](https://github.com/scholokov/long-travel-2/assets/95171672/177a1d4d-3f04-41a8-82eb-1b08958752f3)

**Comment by DmitriiNasonov** [comment]
#4074

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
