### ISSUE TITLE
Чайки 2019 - "Детское оздоровительное учреждение санаторного типа “Чайка”"/ "Дорога: Киев – Чайки" structure blocks - Preview photo is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4548]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190608_boguslav/
2. Scroll to structure blocks
3. Pay attention to sturcture blocks header

**Actual Result**
Preview photo is missing

**Expected Result**
Preview photo is present

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Enviroments**
Windows 10, Chrome 118.0.5993.71 (64 bit)
Android 8.1.0, Chrome 117.0.5938.153
![Чайки 2019 – Long-Travel - Google Chrome 17 10 2023 16_32_00](https://github.com/scholokov/long-travel-2/assets/95171672/8fcd41b7-851b-45e2-b6a3-0fc3422fcb2a)
![photo_2023-10-17_16-41-48](https://github.com/scholokov/long-travel-2/assets/95171672/71df15b0-246d-4144-bd0f-c2eacad82afb)
![photo_2023-10-17_16-41-52](https://github.com/scholokov/long-travel-2/assets/95171672/e2d82136-3627-4f00-8600-c01b1e0263c7)
![Чайки 2019 – Long-Travel - Google Chrome 17 10 2023 16_31_31](https://github.com/scholokov/long-travel-2/assets/95171672/f0cfdeab-0d58-43f8-9b8f-03b052c81211)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
