### ISSUE TITLE
20200725_26_piviha / Tag "Автомобіль" is missed in the Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4550]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20200725_26_piviha/
2. Pay attention to the absence of tag in the Preview block

**Actual result:**
Tag "Автомобіль" is missed in the Preview block.

**Expected result:**
Tag "Автомобіль" is present in the Preview block.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/a565666a-6fee-4aff-b077-17fa80243c8e)

**Comment by GNatala** [comment]
#4087

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
