### ISSUE TITLE
20200725_26_piviha /Preview's date format is DD.MM-DD.MM.YYYY 

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4551]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20200725_26_piviha/
2. Pay attention to the date format in the Preview block

**Actual result:**
The date format is **DD.MM-DD.MM.YYYY (25.07-26.07.2020)** 

**Expected result:**
The date format is **DD.MM.YYYY-DD.MM.YYYY(25.07.2020-26.07.2020)**

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/prevyu-podorozhi

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/386129ff-c411-415c-8ab7-a4e559467e33)

**Comment by GNatala** [comment]
#4087

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
