### ISSUE TITLE
20200725_26_piviha / All photo galleries load immediately

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4552]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20200725_26_piviha/
2. Pay attention that photo galleries load immediately.

**Actual result:**
All photo galleries load immediately.

**Expected result:**
Only the first photo galleries load immediately. The button "Відобразити галерею" appears in all galleries starting from the second one.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/b59f0ee6-b09a-435f-ac44-e54f0c7bb8f5)

**Comment by GNatala** [comment]
https://github.com/scholokov/long-travel-2/issues/4087

**Comment by scholokov** [comment]
думаю тут краще почати з того, що галереї не мають відображатися одразу. а тільки одна

**Comment by GNatala** [comment]
переформатувала баг

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
