### ISSUE TITLE
20170513_putivl_kruti/A drop-down list with cards is displayed in the Map block of the travel

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4553]
Steps to reproduce:

1. Open https://test.long-travel.live/20170513_putivl_kruti/
2. Scroll down to the Map block of the travel
3. Pay attention to the location of the drop-down list with cards on the Map block 

Actual Result: A drop-down list with cards is displayed in the Map block of the travel
Expected Result: A drop-down list with cards is not displayed in the Map block of the travel

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/8b185245-b173-4927-857e-b8010639eef9)

**Comment by ODrobik** [comment]
#3229

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
