### ISSUE TITLE
20170513_putivl_kruti/The"20170513_Putivl_Kruti" Name of travel is displayed in the drop-down list of the "Подорожі" page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4560]
Testing is carried out on https://test.long-travel.live/travels/

Steps to reproduce:

1. Open page https://long-travel.live/travels/
2. Scroll down to the "20170513_Putivl_Kruti" Name of travel in the drop-down list
3. Pay attention to the NAME of travel
4. Pay attention to the Name of the travel in the "Подорожі-список" section

Actual Result: The"20170513_Putivl_Kruti" Name of travel is displayed in the drop-down list

Expected Result: The"2017.05.13 Путивль - Крути" Name of travel is displayed in the drop-down list

Requirements: https://qax.gitbook.io/qax-travel/requirements/3.travels/map-routs

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/qax-portal-2/assets/123776698/a81e2b75-ceb9-479d-90ad-d1daa4210172)

**Comment by ODrobik** [comment]
#3229

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
