### ISSUE TITLE
Production_20170513_putivl_kruti/A drop-down list with cards is displayed in the Map block of the travel

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4562]
Steps to reproduce:

1. Open https://long-travel.live/20170513_putivl_kruti/
2. Scroll down to the Map block of the travel
3. Pay attention to the location of the drop-down list with cards on the Map block

Actual Result: A drop-down list with cards is displayed in the Map block of the travel
Expected Result: A drop-down list with cards is not displayed in the Map block of the travel

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/fab25d5a-0eb5-434e-9e93-9976b3badb62)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/long-travel-2/assets/88647733/ad840a42-ccff-453e-b847-f3051c77a376)

**Comment by ODrobik** [comment]
Виправлено

**Comment by scholokov** [comment]
полмилка є тільки на продакшені?

**Comment by ODrobik** [comment]
@scholokov Так. Помилка тільки на продакшені
![image](https://github.com/scholokov/long-travel-2/assets/123776698/6c995c82-35ba-4c17-a66e-bfeb935c0232)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
