### ISSUE TITLE
20190608_boguslav - The “Time period” block is duplicated

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4563]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190608_boguslav/

**Actual Result**
The “Time period” block is duplicated

**Expected Result**
The “Time period” block isn't duplicated

**Additional information**
[https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list (number "59")](https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-6&mode=design&t=YRLM1c2tNiAYtEB1-0)
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/prevyu-podorozhi

**Enviroments**
Windows 10, Chrome 118.0.5993.89 (64 bit), Firefox 118.0.2 (64 bit)
Android 8.1.0, Chrome 118.0.5993.80, Firefox 118.2.0
![Duolingo - Лучший в мире способ изучать английский - Google Chrome 24 10 2023 15_05_13](https://github.com/scholokov/long-travel-2/assets/95171672/20ba3950-a89c-4e20-95b0-9d490f1d3501)
![photo_2023-10-24_15-11-19](https://github.com/scholokov/long-travel-2/assets/95171672/f810f701-2e10-4764-a8b6-1066ba8b339a)

**Comment by DmitriiNasonov** [comment]
#4074

**Comment by DmitriiNasonov** [comment]
#4539

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
