### ISSUE TITLE
20190608_boguslav - "Детское оздоровительное учреждение санаторного типа “Чайка”" standart block - Part of the code is visible above the photo gallery

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4564]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190608_boguslav/
2. Scroll to "Детское оздоровительное учреждение санаторного типа “Чайка”" standart block

**Actual Result**
Part of the code is visible above the photo gallery

**Expected Result**
Code isn't visible 

**Additional information**
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-6&mode=design&t=mIzYfz8F5T84xeRH-0

**Enviroments**
Windows 10, Chrome 118.0.5993.89 (64 bit), Firefox 118.0.2 (64 bit)
Android 8.1.0, Chrome 118.0.5993.80, Firefox 118.2.0
![Duolingo - Лучший в мире способ изучать английский - Google Chrome 24 10 2023 16_31_26](https://github.com/scholokov/long-travel-2/assets/95171672/ff9b0cba-b3a1-4e47-955e-92471effdd3d)
![photo_2023-10-24_16-31-55](https://github.com/scholokov/long-travel-2/assets/95171672/8f8f5e5f-e2ef-4c37-801d-c4a6aa1658bd)

**Comment by DmitriiNasonov** [comment]
#4074

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
