### ISSUE TITLE
20190608_boguslav - "Детское оздоровительное учреждение санаторного типа “Чайка”" standart block - Fotogallery type is "random"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4565]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190608_boguslav/
2. Scroll to "Детское оздоровительное учреждение санаторного типа “Чайка”" standart block
3. Check fotogallery type

**Actual Result**
Fotogallery type is "random"

**Expected Result**
Fotogallery type is "mosaic"

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

**Enviroments**
Windows 10, Chrome 118.0.5993.89 (64 bit), Firefox 118.0.2 (64 bit)
![Duolingo - Лучший в мире способ изучать английский - Google Chrome 24 10 2023 16_38_28](https://github.com/scholokov/long-travel-2/assets/95171672/5591c864-cb5f-4eaf-89ed-384fc1f424ad)

**Comment by DmitriiNasonov** [comment]
#4074

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
