### ISSUE TITLE
20200725_26_piviha / Block "Дорога Київ – Пивиха" - the photo gallery type is "random"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4567]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20200725_26_piviha/
2. Pay attention to the block "Дорога Київ – Пивиха" photo gallery.

**Actual result:**
In the block "Дорога Київ – Пивиха" - the photo gallery type is "random".

**Expected result:**
In the block "Дорога Київ – Пивиха" - the photo gallery type is "mozaic".

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/47930f97-fb74-462e-af52-7cc4f6633ead)

**Comment by GNatala** [comment]
#4087

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
