### ISSUE TITLE
Requirements/The page "map-routs" the word "Link" is English language

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4568]
Steps to reproduce:

1. Open: https://qax.gitbook.io/qax-travel/requirements/3.travels/map-routs)
2. Scroll down to the "Детальний Список подорожей" section on the "map-routs" page 
3. Pay attention to the word "Link" on the "Детальний Список подорожей" section 

Actual Result: the word "Link" is English language
Expected Result: the phrase "Відкрити подорож" is Ukrainian language

Environment:
Windows 10 Pro (x64),
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/bdb6731a-95c1-429b-b8c3-67eb44b626ca)

**Comment by ODrobik** [comment]
#4557

**Comment by scholokov** [comment]
виправлеон

**Comment by ODrobik** [comment]
перевірено
