### ISSUE TITLE
20170513_putivl_kruti/The Photo gallery is loaded immediately in the "Museum" Standard block 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4569]
Steps to reproduce:

1. Open https://long-travel.live/20170513_putivl_kruti/
2. Scroll down to the "Museum" Standard block of the travel
3. Pay attention to the Photo gallery in the "Museum" Standard block

Actual Result: The Photo gallery is loaded immediately 
Expected Result: The Photo gallery is not loaded immediately  

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/95099263-1b80-47d5-86a1-15b8859649a0)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified

**Comment by ODrobik** [comment]
#4557
