### ISSUE TITLE
20170513_putivl_kruti/The Gallery is loaded immediately in the Standard block

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4570]
Steps to reproduce:

1. Open https://long-travel.live/20170513_putivl_kruti/
2. Scroll down to the "Museum" Standard block of the travel
3. Pay attention to the Gallery in the Standard block

Actual Result: The Gallery is loaded immediately
Expected Result: The "Відобразити галерею" button is displayed instead of the uploaded gallery  

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/34baac41-09cb-4be9-b29e-bea1154bfc5f)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
#4557

**Comment by ODrobik** [comment]
verified
