### ISSUE TITLE
20170513_putivl_kruti/The "Киев" name of the city is displayed in the Russian in the title of the video

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4571]
Steps to reproduce:

1. Open: https://long-travel.live/20170513_putivl_kruti/
2. Scroll down to the video of the 3nd "Дорога" Standard block
3. Pay attention to the "Киев" name of the city in the title of the video

Actual Result:The "Киев" name of the city is displayed in the Russian 

Expected Result: :The "Київ" name of the city is displayed in the Ukrainian

Environment:
Windows 10 Pro (x64),
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/897dc237-ad19-4955-8756-0be018399d59)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
#4557

**Comment by ODrobik** [comment]
verified
