### ISSUE TITLE
20170513_putivl_kruti/"13.05.2017" date format is displayed in the video title of the "Дорога" Standard block

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4572]
Steps to reproduce:

1. Open: https://long-travel.live/20170513_putivl_kruti/
2. Scroll down to the video of the 3nd "Дорога" Standard block
3. Pay attention to the "13.05.2017" date format in the video title of the "Дорога" Standard block

Actual Result:"13.05.2017" date format is displayed in the video title

Expected Result: :"2017.05.13" date format is displayed in the video title 

Environment:
Windows 10 Pro (x64),
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/85f9d6c4-0ffc-4a79-bc4d-71c52b9c1e75)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
