### ISSUE TITLE
20190907_baydarky - Name of the travel is "Байдарки, р.Днепр"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4581]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190608_boguslav/
2. Pay attention to the name of the travel

**Actual Result**
Name of the travel is "Байдарки, р.Днепр"

**Expected Result**
Name of the travel is "Сплав по Дніпру"

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list (number "59")

**Enviroments**
Windows 10, Chrome 118.0.5993.118 (64 bit)
Android 8.1.0, Chrome 118.0.5993.80
![Байдарки, р Днепр – Long-Travel - Google Chrome 31 10 2023 13_32_20](https://github.com/scholokov/long-travel-2/assets/95171672/5fab03de-868b-4b48-9d9d-919f50266b75)
![photo_2023-10-31_13-32-28](https://github.com/scholokov/long-travel-2/assets/95171672/a7734e1c-bd69-40d4-b3fa-57754a74d7ed)

**Comment by DmitriiNasonov** [comment]
#4077

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduced 
![Сплав по Дніпру – Long-Travel - Google Chrome 08 11 2023 12_40_16](https://github.com/scholokov/long-travel-2/assets/95171672/fc3ee417-76f7-4246-bd30-fa20a4d5a987)
![photo_2023-11-08_12-40-25](https://github.com/scholokov/long-travel-2/assets/95171672/2f07c80d-623e-43c8-88be-764f4ca836cd)

**Comment by scholokov** [comment]
скріни не відповідають першому багу
не зрозуміло чому "не пофікшено"

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
