### ISSUE TITLE
20190907_baydarky - Map - Drop-down list with a travels is present

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4583]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190907_baydarky/
2. Scroll to Map
3. Pay attention to drop-down list with a travels is present

**Actual Result**
Drop-down list with a travels is present

**Expected Result**
Drop-down list with a travels is missing

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Enviroments**
Windows 10, Chrome 118.0.5993.118 (64 bit)
Android 8.1.0, Chrome 118.0.5993.80
![Байдарки, р Днепр – Long-Travel - Google Chrome 31 10 2023 13_38_36](https://github.com/scholokov/long-travel-2/assets/95171672/88b76b75-3f8d-4434-b51c-9f08e809c417)
![photo_2023-10-31_13-39-57](https://github.com/scholokov/long-travel-2/assets/95171672/1845556a-3191-463c-bd0e-8a38b10e4134)

**Comment by DmitriiNasonov** [comment]
#4077

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
