### ISSUE TITLE
20190907_baydarky - Standart block "Сплав по Дніпру" is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4584]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190907_baydarky/
2. Scroll to space under the map

**Actual Result**
Standart block "Сплав по Дніпру" is missing

**Expected Result**
Standart block "Сплав по Дніпру" is present

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

**Enviroments**
Windows 10, Chrome 118.0.5993.118 (64 bit)
Android 8.1.0, Chrome 118.0.5993.80
![Байдарки, р Днепр – Long-Travel - Google Chrome 31 10 2023 13_43_19](https://github.com/scholokov/long-travel-2/assets/95171672/09983d22-d5d4-41cb-a04d-57b927015e05)
![photo_2023-10-31_13-43-27](https://github.com/scholokov/long-travel-2/assets/95171672/9d33a5dc-4527-4f82-8859-e38422fc2088)

**Comment by DmitriiNasonov** [comment]
#4077

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduced 
![Сплав по Дніпру – Long-Travel - Google Chrome 08 11 2023 12_24_59](https://github.com/scholokov/long-travel-2/assets/95171672/468fa4ed-5606-46ce-999d-8cf0b623ee0a)
![photo_2023-11-08_12-30-40](https://github.com/scholokov/long-travel-2/assets/95171672/7a51bf5e-2220-4fff-8181-e01a0134acf7)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
