### ISSUE TITLE
20190907_baydarky - Block "Місто або Місто, Область" is present above Map

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4587]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190907_baydarky/

**Actual Result**
Block "Місто або Місто, Область" is present above Map

**Expected Result**
Block "Місто або Місто, Область" is present in structure block

**Additional information**
If structure block is missing please fix this bug: https://github.com/scholokov/long-travel-2/issues/4584
[(Check 5.4 Перелік блоків) https://qax.gitbook.io/qax-travel/requirements/places](https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i)
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/prevyu-podorozhi

**Enviroments**
Windows 10, Chrome 118.0.5993.118 (64 bit)
Android 8.1.0, Chrome 118.0.5993.80
![Байдарки, р Днепр – Long-Travel - Google Chrome 31 10 2023 13_49_07](https://github.com/scholokov/long-travel-2/assets/95171672/79397a32-d0fe-49ef-b212-a00a801c72c4)
![photo_2023-10-31_13-50-39](https://github.com/scholokov/long-travel-2/assets/95171672/ccd859fb-2cab-49dd-8ad3-02b0a7f446b3)

**Comment by DmitriiNasonov** [comment]
#4077

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
