### ISSUE TITLE
20190907_baydarky - Preview of the travel - Tag "Цікаво" is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4588]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190907_baydarky/
2. Pay attention to the preview of the travel

**Actual Result**
Tag "Цікаво" is missing

**Expected Result**
Tag "Цікаво" is present

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1
https://qax.gitbook.io/qax-travel/requirements/4.travel/tags

**Enviroments**
Windows 10, Chrome 118.0.5993.118 (64 bit)
Android 8.1.0, Chrome 118.0.5993.80
![Байдарки, р Днепр – Long-Travel - Google Chrome 31 10 2023 14_03_26](https://github.com/scholokov/long-travel-2/assets/95171672/1afd8a0c-c35c-4d2d-afa3-6f2ec50558a0)
![photo_2023-10-31_14-03-50](https://github.com/scholokov/long-travel-2/assets/95171672/7e02a3bc-1496-45cc-a154-db1883d983f1)

**Comment by DmitriiNasonov** [comment]
#4077

**Comment by scholokov** [comment]
якого саме тегу не вистачає?

**Comment by DmitriiNasonov** [comment]
Bug-report fixed

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
