### ISSUE TITLE
Regression - Block "Парки" in "Цікаві місця" - Name of the "Тропа Голицина, Грот Шаляпина, Можжевеловая Роща" sctructural block isn't contains the link to travel

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4599]
**Steps of reproducing**
1. Open https://long-travel.live/park/
2. Scroll to "Тропа Голицина, Грот Шаляпина, Можжевеловая Роща" sctructural block 

**Actual Result**
Name of the "Тропа Голицина, Грот Шаляпина, Можжевеловая Роща" sctructural block isn't contains the link to travel

**Expected Result**
Name of the "Тропа Голицина, Грот Шаляпина, Можжевеловая Роща" sctructural block is contains the link to travel

**Additional information**
Link to travel with structural block: https://long-travel.live/20070722_0809_crimea/

**Enviroments**
Windows 10, Chrome 118.0.5993.118 (64 bit)
Android 8.1.0, Chrome 118.0.5993.80
![Байдарки, р Днепр – Long-Travel - Google Chrome 31 10 2023 15_38_03](https://github.com/scholokov/long-travel-2/assets/95171672/192fada1-8b35-41d4-9fed-3c432013d5fc)
![photo_2023-10-31_15-41-50](https://github.com/scholokov/long-travel-2/assets/95171672/04ee8ce1-2fe1-42bd-9173-cb8328539b1b)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduced 
![Парки – Long-Travel - Google Chrome 08 11 2023 13_42_14](https://github.com/scholokov/long-travel-2/assets/95171672/1c8fd5ab-6058-425e-89e9-cd700f205eba)
![photo_2023-11-08_13-42-52](https://github.com/scholokov/long-travel-2/assets/95171672/bd7be5ba-f936-447b-a8d8-f989deafb866)

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
