### ISSUE TITLE
Regression - Block "Парки" in "Цікаві місця" - Name of the "Национальный дендрологический парк "Софиевка"" sctructural block isn't contains the link to travel

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4600]
**Steps of reproducing**
1. Open https://long-travel.live/park/
2. Scroll to "Национальный дендрологический парк "Софиевка"" sctructural block

**Actual Result**
Name of the "Национальный дендрологический парк "Софиевка"" sctructural block isn't contains the link to travel

**Expected Result**
Name of the "Национальный дендрологический парк "Софиевка"" sctructural block is contains the link to travel

**Additional information**
Link to travel with structural block: https://long-travel.live/20071027_uman/

**Enviroments**
Windows 10, Chrome 118.0.5993.118 (64 bit)
Android 8.1.0, Chrome 118.0.5993.80
![Байдарки, р Днепр – Long-Travel - Google Chrome 31 10 2023 15_44_37](https://github.com/scholokov/long-travel-2/assets/95171672/83b31247-4416-4e62-80bf-26539677f973)
![photo_2023-10-31_15-44-30](https://github.com/scholokov/long-travel-2/assets/95171672/43ac0a0c-cf08-4fc2-b112-f3b232639e48)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduced 
![Парки – Long-Travel - Google Chrome 08 11 2023 13_39_30](https://github.com/scholokov/long-travel-2/assets/95171672/66c59d07-9463-44a7-94db-6cdd225fa11f)
![photo_2023-11-08_13-40-11](https://github.com/scholokov/long-travel-2/assets/95171672/7e5b5c4c-7d4a-45bd-9f5d-580934d400e5)

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
