### ISSUE TITLE
Regression - Block "Парки" in "Цікаві місця" - Standart block "Дендропарк "Софиевка"" (where date is 01.11.2015 ) is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4605]
**Steps of reproducing**
1. Open https://long-travel.live/park/
2. Scroll to "Институт эволюционной экологии НАН Украины Парк "Феофания"" scructure block

**Actual Result**
Standart block "Дендропарк "Софиевка"" (where date is 01.11.2015 ) is missing

**Expected Result**
Standart block "Дендропарк "Софиевка"" (where date is 01.11.2015 ) is present

**Additional information**
Link to travel with structural block: https://long-travel.live/20151031_haisyn_uman/

**Enviroments**
Windows 10, Chrome 118.0.5993.118 (64 bit)
Android 8.1.0, Chrome 118.0.5993.80
![Байдарки, р Днепр – Long-Travel - Google Chrome 31 10 2023 16_14_53](https://github.com/scholokov/long-travel-2/assets/95171672/e584b08d-dcf1-4edc-8245-c58bf48fae9b)
![photo_2023-10-31_16-16-03](https://github.com/scholokov/long-travel-2/assets/95171672/b8b5b224-c7a8-4376-8163-2b6cf67a6617)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduced 
![Парки – Long-Travel - Google Chrome 08 11 2023 13_06_37](https://github.com/scholokov/long-travel-2/assets/95171672/99cec1e3-4818-4c12-8f7e-15c3eadbbd00)
![photo_2023-11-08_13-08-22](https://github.com/scholokov/long-travel-2/assets/95171672/1836cbfb-68fa-4747-a4da-3afcc32898aa)

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
