### ISSUE TITLE
Regression - Block "Парки" in "Цікаві місця" - Standart block "Kyiv Fashion Park" is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4606]
**Steps of reproducing**
1. Open https://long-travel.live/park/
2. Scroll to "Институт эволюционной экологии НАН Украины Парк "Феофания"" scructure block

**Actual Result**
Standart block "Kyiv Fashion Park" is missing

**Expected Result**
Standart block "Kyiv Fashion Park" is present

**Additional information**
Link to travel with structural block: https://long-travel.live/20151226_kiev_fashion_park/

**Enviroments**
Windows 10, Chrome 118.0.5993.118 (64 bit)
Android 8.1.0, Ch
![Байдарки, р Днепр – Long-Travel - Google Chrome 31 10 2023 16_14_53](https://github.com/scholokov/long-travel-2/assets/95171672/4c15d374-074d-46b6-a6c4-86c5f0c04944)
![photo_2023-10-31_16-16-03](https://github.com/scholokov/long-travel-2/assets/95171672/7a022928-be7f-4e48-89c6-61e4087cb4df)
rome 118.0.5993.80

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduced 
![Парки – Long-Travel - Google Chrome 08 11 2023 13_06_37](https://github.com/scholokov/long-travel-2/assets/95171672/73c921c6-983a-4a01-b559-5a1ad8865650)
![photo_2023-11-08_13-08-22](https://github.com/scholokov/long-travel-2/assets/95171672/d2af3435-34b7-409b-b48e-1afa5846831c)

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
