### ISSUE TITLE
Regression - Block "Парки" in "Цікаві місця" - Standart block "Древлянский парк" is missing 

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4608]
**Steps of reproducing**
1. Open https://long-travel.live/park/
2. Scroll to "Институт эволюционной экологии НАН Украины Парк "Феофания"" scructure block

**Actual Result**
Standart block "Древлянский парк" is missing

**Expected Result**
Standart block "Древлянский парк' is present

**Additional information**
Link to travel with structural block: https://long-travel.live/20170521_korosten/

**Enviroments**
Windows 10, Chrome 118.0.5993.118 (64 bit)
Android 8.1.0, Chrome 118.0.5993.80
![Байдарки, р Днепр – Long-Travel - Google Chrome 31 10 2023 16_14_53](https://github.com/scholokov/long-travel-2/assets/95171672/f5fc6068-6e4a-4e84-8c23-8f5ab69ddfbb)
![photo_2023-10-31_16-16-03](https://github.com/scholokov/long-travel-2/assets/95171672/9b859206-9d5d-455d-8fc1-c112d5f3eed0)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduced 
![Парки – Long-Travel - Google Chrome 08 11 2023 13_06_37](https://github.com/scholokov/long-travel-2/assets/95171672/81d085f5-f905-45be-bc01-88fd7ed13151)
![photo_2023-11-08_13-08-22](https://github.com/scholokov/long-travel-2/assets/95171672/0fd3697b-95ea-47b4-b28b-bf0e8ae8ba00)

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
