### ISSUE TITLE
Regression - Block "Парки" in "Цікаві місця" - Standart block "Крещатик – Мариинский парк" (where date is 05.06.2017) is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4609]
**Steps of reproducing**
1. Open https://long-travel.live/park/
2. Scroll to "Институт эволюционной экологии НАН Украины Парк "Феофания"" scructure block

**Actual Result**
Standart block "Крещатик – Мариинский парк" (where date is 05.06.2017) is missing

**Expected Result**
Standart block "Крещатик – Мариинский парк" (where date is 05.06.2017) is present

**Additional information**
Link to travel with structural block: https://long-travel.live/20170605_kiev_mariinskiy/

**Enviroments**
Windows 10, Chrome 118.0.5993.118 (64 bit)
Android 8.1.0, Chrome 118.0.5993.80
![Байдарки, р Днепр – Long-Travel - Google Chrome 31 10 2023 16_14_53](https://github.com/scholokov/long-travel-2/assets/95171672/4e3d3925-cef5-4da7-a31a-c4701312bdb2)
![photo_2023-10-31_16-16-03](https://github.com/scholokov/long-travel-2/assets/95171672/ed3d76fb-775b-4020-a6c3-7f7dfc46a293)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduced 
![Парки – Long-Travel - Google Chrome 08 11 2023 13_06_37](https://github.com/scholokov/long-travel-2/assets/95171672/073bac1c-c072-472c-ae10-dc6daa8854b5)
![photo_2023-11-08_13-08-22](https://github.com/scholokov/long-travel-2/assets/95171672/3542086d-df7d-4341-a803-8d62f75ca9e3)
