### ISSUE TITLE
Regression - Block "Парки" in "Цікаві місця" - Standart block "Дендропарк “Александрия”" is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4610]
**Steps of reproducing**
1. Open https://long-travel.live/park/
2. Scroll to "Институт эволюционной экологии НАН Украины Парк "Феофания"" scructure block

**Actual Result**
Standart block "Дендропарк “Александрия”" is missing

**Expected Result**
Standart block "Дендропарк “Александрия”' is present

**Additional information**
Link to travel with structural block: https://long-travel.live/20180624_bila_tserkva/

**Enviroments**
Windows 10, Chrome 118.0.5993.118 (64 bit)
Android 8.1.0, Chrome 118.0.5993.80
![Байдарки, р Днепр – Long-Travel - Google Chrome 31 10 2023 16_14_53](https://github.com/scholokov/long-travel-2/assets/95171672/4be62ec6-9bfc-41db-8289-7c73dd2fb2a4)
![photo_2023-10-31_16-16-03](https://github.com/scholokov/long-travel-2/assets/95171672/62a82f08-2fa1-42d1-90ae-6bb13185d41c)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduced 
![Парки – Long-Travel - Google Chrome 08 11 2023 13_06_37](https://github.com/scholokov/long-travel-2/assets/95171672/cdec4723-f865-467f-8eec-53ee27dd1f9b)
![photo_2023-11-08_13-08-22](https://github.com/scholokov/long-travel-2/assets/95171672/355e46ac-55e1-4a86-918f-1910b62b8148)

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
