### ISSUE TITLE
Regression - Block "Парки" in "Цікаві місця" - Standart block "Бучанский Парк" (where date is 19.08.2018) is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4611]
**Steps of reproducing**
1. Open https://long-travel.live/park/
2. Scroll to "Институт эволюционной экологии НАН Украины Парк "Феофания"" scructure block

**Actual Result**
Standart block "Бучанский Парк" (where date is 19.08.2018) is missing

**Expected Result**
Standart block "Бучанский Парк" (where date is 19.08.2018) is present

**Additional information**
Link to travel with structural block: https://long-travel.live/20180819_bucha/

**Enviroments**
Windows 10, Chrome 118.0.5993.118 (64 bit)
Android 8.1.0, Chrome 118.0.5993.80
![Байдарки, р Днепр – Long-Travel - Google Chrome 31 10 2023 16_14_53](https://github.com/scholokov/long-travel-2/assets/95171672/12347233-e9b3-4c0e-a74b-e4ce230662fe)
![photo_2023-10-31_16-16-03](https://github.com/scholokov/long-travel-2/assets/95171672/59d9ab26-a86c-414b-87fe-17af6290b161)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
