### ISSUE TITLE
Regression - Block "Парки" in "Цікаві місця" - Standart block "Бучанский Парк" (where date is 09.09.2018) is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4612]
**Steps of reproducing**
1. Open https://long-travel.live/park/
2. Scroll to "Институт эволюционной экологии НАН Украины Парк "Феофания"" scructure block

**Actual Result**
Standart block "Бучанский Парк" (where date is 09.09.2018) is missing

**Expected Result**
Standart block "Бучанский Парк" (where date is 09.09.2018) is present

**Additional information**
Link to travel with structural block: https://long-travel.live/20180909_bucha/

**Enviroments**
Windows 10, Chrome 118.0.5993.118 (64 bit)
Android 8.1.0, Chrome 118.0.5993.80
![Байдарки, р Днепр – Long-Travel - Google Chrome 31 10 2023 16_14_53](https://github.com/scholokov/long-travel-2/assets/95171672/500d99ce-94be-42df-bf50-33e624bbeb18)
![photo_2023-10-31_16-16-03](https://github.com/scholokov/long-travel-2/assets/95171672/58f880b9-b597-452f-9384-aa745aa7e912)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduced 
![Парки – Long-Travel - Google Chrome 08 11 2023 13_06_37](https://github.com/scholokov/long-travel-2/assets/95171672/f196de46-1248-4cd1-b76c-256790db8c62)
![photo_2023-11-08_13-08-22](https://github.com/scholokov/long-travel-2/assets/95171672/4e4c7371-84d5-472a-8615-68218da55368)

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
