### ISSUE TITLE
Regression - Block "Парки" in "Цікаві місця" - Standart block "Ландшанфтный парк "Буки"" is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4613]
**Steps of reproducing**
1. Open https://long-travel.live/park/
2. Scroll to "Институт эволюционной экологии НАН Украины Парк "Феофания"" scructure block

**Actual Result**
Standart block "Ландшанфтный парк "Буки"" is missing

**Expected Result**
Standart block "Ландшанфтный парк "Буки"' is present

**Additional information**
Link to travel with structural block: https://long-travel.live/20180915_buki/

**Enviroments**
Windows 10, Chrome 118.0.5993.118 (64 bit)
Android 8.1.0, Chrome 118.0.5993.80
![Байдарки, р Днепр – Long-Travel - Google Chrome 31 10 2023 16_14_53](https://github.com/scholokov/long-travel-2/assets/95171672/35c6fa89-9754-479d-b267-9f00a2b629c3)
![photo_2023-10-31_16-16-03](https://github.com/scholokov/long-travel-2/assets/95171672/2a221b1e-f999-455f-b672-9ccc4e9ef18b)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduced 
![Парки – Long-Travel - Google Chrome 08 11 2023 13_06_37](https://github.com/scholokov/long-travel-2/assets/95171672/d14bcf69-0e44-4ff7-b4e0-1f44371e4af5)
![photo_2023-11-08_13-08-22](https://github.com/scholokov/long-travel-2/assets/95171672/f2cf805c-6f30-4f1c-820c-2624cf6562b7)

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
