### ISSUE TITLE
Regression - Block "Парки" in "Цікаві місця" - Standart block "Vingio parkas" is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4614]
**Steps of reproducing**
1. Open https://long-travel.live/park/
2. Scroll to "Институт эволюционной экологии НАН Украины Парк "Феофания"" scructure block

**Actual Result**
Standart block "Vingio parkas" is missing

**Expected Result**
Standart block "Vingio parkas' is present

**Additional information**
Link to travel with structural block: https://long-travel.live/20190427_belarus_litva/

**Enviroments**
Windows 10, Chrome 118.0.5993.118 (64 bit)
Android 8.1.0, Chrome 118.0.5993.80
![Байдарки, р Днепр – Long-Travel - Google Chrome 31 10 2023 16_14_53](https://github.com/scholokov/long-travel-2/assets/95171672/755c9aae-8e63-4778-9b43-cbcc17a3e2b6)
![photo_2023-10-31_16-16-03](https://github.com/scholokov/long-travel-2/assets/95171672/0512168e-f90b-40f6-9454-77fb48d8b678)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduced 
![Парки – Long-Travel - Google Chrome 08 11 2023 13_06_37](https://github.com/scholokov/long-travel-2/assets/95171672/d3e0e67a-00b7-486b-8ba8-9907691de7a4)
![photo_2023-11-08_13-08-22](https://github.com/scholokov/long-travel-2/assets/95171672/d1824e6e-a3bb-424d-8c41-8740cc05b546)

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
