### ISSUE TITLE
20200725_26_piviha / Name of the Road block "Дорога Пивиха – Київ" is written in one line

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4618]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20200725_26_piviha/
2. Pay attention to the Road block "Дорога Пивиха – Київ".

**Actual Result:** 
Name of the Road block "Дорога Пивиха – Київ" is written in one line.

**Expected Result:** 
Name of the Road block "Дорога Пивиха – Київ" is written in two lines.

**Additional information:**
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986%3A6&mode=dev

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/5762da51-13f2-41ff-a11e-da29e813cf50)

**Comment by GNatala** [comment]
#4087

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
