### ISSUE TITLE
20200725_26_piviha / The tag "Пляж" is missed in the Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4619]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20200725_26_piviha/
2. Pay attention to the absence of the tag "Пляж" in the Preview block

**Actual result:**
The tag "Пляж" is missed in the Preview block.

**Expected result:**
The Tag "Пляж" is present in the Preview block.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/eb103647-89a7-449c-9a91-b66a2441b69c)

**Comment by GNatala** [comment]
#4087

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
