### ISSUE TITLE
20200725_26_piviha / The tag "Цікаво" is missed in the Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4620]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20200725_26_piviha/
2. Pay attention to the absence of the tag "Цікаво" in the Preview block

**Actual result:**
The tag "Цікаво" is missed in the Preview block.

**Expected result:**
The Tag "Цікаво" is present in the Preview block.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/a4998c32-5dce-40da-9daf-8366b96ca722)

**Comment by GNatala** [comment]
#4087

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
