### ISSUE TITLE
Regression - Block "Парки" in "Цікаві місця" - Standart block "Park and National Palace of Pena, Sintra, Portugal"  is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4659]
**Steps of reproducing**
1. Open https://long-travel.live/park/
2. Scroll to "Парк “Сосновий Бір”" scructure block

**Actual Result**
Standart block "Park and National Palace of Pena, Sintra, Portugal" is missing

**Expected Result**
Standart block "Park and National Palace of Pena, Sintra, Portugal" is present

**Additional information**
Link to travel with structural block: https://long-travel.live/20211029_0911_portugal/

**Enviroments**
Windows 10, Chrome 119.0.6045.106 (64 bit)
Android 8.1.0, Chrome 118.0.5993.111
![Парки – Long-Travel - Google Chrome 07 11 2023 18_22_48](https://github.com/scholokov/long-travel-2/assets/95171672/c3a4b4c3-ee11-4431-b28b-d2ee572ed45d)
![photo_2023-11-07_18-23-56](https://github.com/scholokov/long-travel-2/assets/95171672/8c4f730a-ca56-4b54-b5e7-1b339e9cadfd)

**Comment by scholokov** [comment]
fixed
