### ISSUE TITLE
20200725_26_piviha/ The names of the second and seventh blocks are different

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4664]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20200725_26_piviha/
2. Scroll down to the 2nd Block "г.Пивиха Полтавська Область" .
3. Scroll down to the 7th Block "г.Пивиха, Полтавська Область, Україна".
4. Compare the Blocks.

**Actual Result:** 
The names of the second and seventh blocks are different.

**Expected Result:** 
The names of the second and seventh blocks are the same.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/8161d9da-3647-414a-804b-a2250ef5f196)

**Comment by GNatala** [comment]
#4087

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
