### ISSUE TITLE
20200725_26_piviha /Hotel Block date format is DD.MM-DD.MM.YYYY 

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4665]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20200725_26_piviha/
2. Scroll down to the Hotel Block "Готель Кременчук 25-26.07.2020"
3. Pay attention to the date format in the Block.

**Actual result:**
The date format is **DD.MM-DD.MM.YYYY (25.07-26.07.2020)** 

**Expected result:**
The date format is **DD.MM.YYYY-DD.MM.YYYY(25.07.2020-26.07.2020)**

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/5579b0e8-7fc3-4d29-a34f-0491527bfd78)

**Comment by GNatala** [comment]
#4087

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/long-travel-2/assets/88647733/8e46b24e-453a-481e-9c69-fd946f20b3aa)

**Comment by GNatala** [comment]
Дякую, виправила

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
