### ISSUE TITLE
20170513_putivl_kruti/ The "Музей памяти героев Крут, Крути"  text is displayed in the 1st line of the Standard block "Museum"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4667]
Testing is carried out on https://test.long-travel.live/20170513_putivl_kruti/

Steps to reproduce:

1. Open https://long-travel.live/20170513_putivl_kruti/
2. Scroll down to the Preview of the Standard "Museum" block
3. Pay attention to the 1st line of Preview in the Standard "Museum" block

Actual Result: The "Музей памяти героев Крут, Крути"  text is displayed in the 1st line of the Standard block "Museum"
Expected Result: The "Музей пам"яті героїв Крут" text is displayed in the 1st line of the Standard block "Museum"

Requirements:https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/f83753bc-9f86-44ee-bf3f-0ac19523e803)

**Comment by ODrobik** [comment]
#4557

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
