### ISSUE TITLE
20170513_putivl_kruti/ The "Черниговская область, Украина" text is displayed in the 2nd line of the Standard block "Museum"

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4668]
Testing is carried out on https://test.long-travel.live/20170513_putivl_kruti/

Steps to reproduce:

1. Open https://test.long-travel.live/20170513_putivl_kruti/
2. Scroll down to the Preview of the Standard "Museum" block 
3. Pay attention to the 2nd line of Preview in the Standard "Museum" block

Actual Result:  The "Черниговская область, Украина" text is displayed in the 2nd line of the Standard block "Museum"
Expected Result:  The "Крути, Чернігівська область" text is displayed in the 2nd line of the Standard block "Museum"

Requirements:https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/8826542c-5074-4b60-a0ff-2cefe633d979)

**Comment by ODrobik** [comment]
#4557

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
