### ISSUE TITLE
20170513_putivl_kruti/ The "Україна" country is displayed in the 2nd line of the in the Standard "Museum" block

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4696]
Steps to reproduce:

1, Open https://test.long-travel.live/20170513_putivl_kruti/
2. Scroll down to the Preview of the Standard "Museum" block
3. Pay attention to the in the 2nd line of Preview in the Standard "Museum" block

Actual Result: **The "Україна" country** is displayed in the 2nd line of the in the Standard "Museum" block

Expected Result: **The "Україна" country** is displayed as **a flag** in the Standard "Museum" block

Requirements:https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/f53ffbbc-7ea7-497c-93c8-a2c116950ccc)

**Comment by ODrobik** [comment]
#3229

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
