### ISSUE TITLE
20181014_vinnitsa - Travel preview - Ukraine flag is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4702]
**Steps of reproducing**
1. Open https://test.long-travel.live/20181014_vinnitsa/

**Actual Result**
Ukraine flag is missing

**Expected Result**
Ukraine flag is present

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/prevyu-podorozhi
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-6&mode=design&t=BLNplPUY0uVax2LZ-0

**Enviroments**
Windows 10, Chrome 119.0.6045.124 (64 bit)
Android 8.1.0, Chrome 119.0.6045.134
![Стрижавка – Винница – Long-Travel - Google Chrome 14 11 2023 16_14_49](https://github.com/scholokov/long-travel-2/assets/95171672/ace9297b-ab4d-47db-9451-7a6110f7be3d)
![photo_2023-11-14_16-14-57](https://github.com/scholokov/long-travel-2/assets/95171672/ae1daa69-be6f-4179-9073-03a1e71ce08d)

**Comment by DmitriiNasonov** [comment]
#4071

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
