### ISSUE TITLE
20181014_vinnitsa - Travel preview - The "Автомобіль" tag is located in the upper right corner

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4704]
**Steps of reproducing**
1. Open https://test.long-travel.live/20181014_vinnitsa/

**Actual Result**
The "Автомобіль" tag is located in the upper right corner

**Expected Result**
The "Автомобіль" tag is located in the upper left corner

**Additional information**
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-6&mode=design&t=BLNplPUY0uVax2LZ-0

**Enviroments**
Windows 10, Chrome 119.0.6045.124 (64 bit)
Android 8.1.0, Chrome 119.0.6045.134
![Стрижавка – Винница – Long-Travel - Google Chrome 14 11 2023 16_33_09](https://github.com/scholokov/long-travel-2/assets/95171672/f0c713a0-8fbb-4eb7-8d5a-5770d9ba8379)
![photo_2023-11-14_16-33-15](https://github.com/scholokov/long-travel-2/assets/95171672/07feda50-3e2f-4956-9bd1-fe2f597a13a7)

**Comment by DmitriiNasonov** [comment]
#4071

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is partially fixed
created new bug-report

**Comment by DmitriiNasonov** [comment]
#4773
