### ISSUE TITLE
20181014_vinnitsa - Map - Drop-down list with a travels is present

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4706]
**Steps of reproducing**
1. Open https://test.long-travel.live/20181014_vinnitsa/
2. Scroll to Map
3. Pay attention to drop-down list with a travels is present

**Actual Result**
Drop-down list with a travels is present

**Expected Result**
Drop-down list with a travels is missing

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Enviroments**
Windows 10, Chrome 119.0.6045.124 (64 bit)
Android 8.1.0, Chrome 119.0.6045.134
![Стрижавка – Винница – Long-Travel - Google Chrome 14 11 2023 16_46_30](https://github.com/scholokov/long-travel-2/assets/95171672/7eb80177-6a61-4d3a-97c5-37c9c19fa096)
![photo_2023-11-14_16-52-33](https://github.com/scholokov/long-travel-2/assets/95171672/c7a40479-8c46-42c3-b62f-bde5ecc76459)

**Comment by DmitriiNasonov** [comment]
#4071

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
