### ISSUE TITLE
20181014_vinnitsa - Map - Preview photo is missing in block "Маршрут подорожі"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4708]
**Steps of reproducing**
1. Open https://test.long-travel.live/20181014_vinnitsa/
2. Scroll to Map
3. Pay attention to block "Маршрут подорожі"

**Actual Result**
Preview photo is missing in block "Маршрут подорожі"

**Expected Result**
Preview photo is present in block "Маршрут подорожі"

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Enviroments**
Windows 10, Chrome 119.0.6045.124 (64 bit)
Android 8.1.0, Chrome 11
![Стрижавка – Винница – Long-Travel - Google Chrome 14 11 2023 16_56_05](https://github.com/scholokov/long-travel-2/assets/95171672/0d06c171-b5f1-41d9-8c4a-aa991a5c45e5)
![photo_2023-11-14_16-56-21](https://github.com/scholokov/long-travel-2/assets/95171672/eb837c29-9c7b-49b0-a017-98e490c1a83d)
9.0.6045.134

**Comment by DmitriiNasonov** [comment]
#4071

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
