### ISSUE TITLE
20181014_vinnitsa - Standart block "Кафе “Старый Йорк”" - Preview is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4715]
**Steps of reproducing**
1. Open https://test.long-travel.live/20181014_vinnitsa/
2. Scroll to the "Кафе “Старый Йорк”" standart block

**Actual Result**
Standart block preview is missing

**Expected Result**
Standart block preview is present

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=4829-92&mode=design&t=BLNplPUY0uVax2LZ-0

**Enviroments**
Windows 10, Chrome 119.0.6045.124 (64 bit)
Android 8.1.0, Chrome 119.0.6045.134
![Стрижавка – Винница – Long-Travel - Google Chrome 14 11 2023 17_12_05](https://github.com/scholokov/long-travel-2/assets/95171672/6820344a-afca-40bd-ae88-1b6cca2f451c)
![photo_2023-11-14_17-25-08](https://github.com/scholokov/long-travel-2/assets/95171672/a1debc14-2069-4431-9eed-f77cfe1dbe32)

**Comment by DmitriiNasonov** [comment]
#4071

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
