### ISSUE TITLE
20181014_vinnitsa - Standart block "Дорога: Киев – Винница" - Ukrainian flag is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4717]
**Steps of reproducing**
1. Open https://test.long-travel.live/20181014_vinnitsa/
2. Scroll to "Дорога: Киев – Винница" structural block

**Actual Result**
Ukrainian flag is missing

**Expected Result**
Ukrainian flag is present

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=4829-72&mode=design&t=eEfhGP8rKZ5zOyjO-0

**Enviroments**
Windows 10, Chrome 119.0.6045.124 (64 bit)
Android 8.1.0, Chrome 119.0.6045.134
![Стрижавка – Винница – Long-Travel - Google Chrome 14 11 2023 17_43_26](https://github.com/scholokov/long-travel-2/assets/95171672/8bf0c39c-b3d5-412c-8144-db7c96efee3d)
![photo_2023-11-14_17-43-43](https://github.com/scholokov/long-travel-2/assets/95171672/809b8779-5eb5-4601-8697-26bffad056ae)

**Comment by DmitriiNasonov** [comment]
#4071

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
