### ISSUE TITLE
20181014_vinnitsa - Standart block "Кафе “Старый Йорк”" - Ukrainian flag is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4719]
**Steps of reproducing**
1. Open https://test.long-travel.live/20181014_vinnitsa/
2. Scroll to "Кафе “Старый Йорк”" structural block

**Actual Result**
Ukrainian flag is missing

**Expected Result**
Ukrainian flag is present

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=4829-72&mode=design&t=eEfhGP8rKZ5zOyjO-0

**Enviroments**
Windows 10, Chrome 119.0.6045.124 (64 bit)
Android 8.1.0, Chrome 119.0.6045.134
![Стрижавка – Винница – Long-Travel - Google Chrome 14 11 2023 17_47_02](https://github.com/scholokov/long-travel-2/assets/95171672/c4979943-332c-43e9-a876-d1ddc9b0286e)
![photo_2023-11-14_17-47-09](https://github.com/scholokov/long-travel-2/assets/95171672/6a4d65c4-0840-44c1-ba99-3e53d4b35663)

**Comment by scholokov** [comment]
_fixed_

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
