### ISSUE TITLE
20181014_vinnitsa - "Выставка оружия и техники ВОВ" structural block - Part of the code is visible

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4721]
**Steps of reproducing**
1. Open https://test.long-travel.live/20181014_vinnitsa/
2. Scroll to "Выставка оружия и техники ВОВ" structural block

**Actual Result**
Part of the code is visible

**Expected Result**
Part of the code isn't visible

**Additional information**
Visible part of the code: [ngg src=”galleries” ids=”310″ display=”pro_mosaic”]
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=4829-72&mode=design&t=S6r2b2tigmwdoMuN-0

**Enviroments**
Windows 10, Chrome 119.0.6045.124 (64 bit)
Android 8.1.0, Chrome 119.0.6045.134
![Стрижавка – Винница – Long-Travel - Google Chrome 14 11 2023 19_40_10](https://github.com/scholokov/long-travel-2/assets/95171672/69b63ad8-1d82-468a-a0ff-f8d0f8a5c006)
![photo_2023-11-14_19-41-36](https://github.com/scholokov/long-travel-2/assets/95171672/a34d5203-3a44-4af0-863e-aa1204aafa39)

**Comment by DmitriiNasonov** [comment]
#4071

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
