### ISSUE TITLE
20191207_08_vinnitsa / The Preview's photo is missing

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4733]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20191207_08_vinnitsa/
2. Pay attention to the Preview block.

**Actual result:**
The preview's photo is missing.

**Expected result:**
The preview's photo is present.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/prevyu-podorozhi

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/f717c865-eeca-4924-b289-a48b91a6ca67)

**Comment by GNatala** [comment]
#4080

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
