### ISSUE TITLE
20191207_08_vinnitsa / Tags "Автомобіль", "Музей", "Цікаво" are missing in the Preview block 

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4734]
**Steps to reproduce:**

1. Open   https://test.long-travel.live/20191207_08_vinnitsa/
2. Pay attention to the absence of the tags  in the Preview block

**Actual result:**
Tags "Автомобіль", "Музей", "Цікаво" are missing in the Preview block.

**Expected result:**
Tags "Автомобіль", "Музей", "Цікаво" are present in the Preview block.

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/b10f1e8e-8529-4c87-9250-fa89dcd5a032)

**Comment by GNatala** [comment]
#4080

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
