### ISSUE TITLE
20191207_08_vinnitsa / In the Map's legend, the date of the end of the travel is Dec 7, 2019

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4737]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20191207_08_vinnitsa/
2. Pay attention to the Map's legend.

**Actual Result:** 
In the Map's legend, the date of the end of the travel is Dec 7, 2019

**Expected Result:** 
 In the Map's legend, **the date of the end of the travel is Dec 8, 2019.**

**Additional information:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/05e450f2-3d10-463c-a2a6-8ea1fdfc0905)

**Comment by GNatala** [comment]
#4080

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
