### ISSUE TITLE
"Харків" travel - Preview of the travel - Tag "Цікаво" is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4742]
**Steps of reproducing**
1. Open https://test.long-travel.live/20200918_20_kharkiv/
2. Pay attention to the preview of the travel

**Actual Result**
Tag "Цікаво" is missing

**Expected Result**
Tag "Цікаво" is present

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1
https://qax.gitbook.io/qax-travel/requirements/4.travel/tags

**Enviroments**
Windows 10, Chrome 119.0.6045.160 (64 bit)
Android 8.1.0, Chrome 119.0.6045.163
![Стрижавка – Винница – Long-Travel - Google Chrome 21 11 2023 16_50_42](https://github.com/scholokov/long-travel-2/assets/95171672/a0028f66-f49c-45ac-a0df-906214cecbcc)
![photo_2023-11-21_16-51-22](https://github.com/scholokov/long-travel-2/assets/95171672/c673bfe0-e285-4844-9ad8-94cb3b63932d)

**Comment by DmitriiNasonov** [comment]
#4091

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
