### ISSUE TITLE
"Харків" travel - Travel preview - Date format is DD - DD.MM.YYYY

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4743]
**Steps of reproducing**
1. Open https://test.long-travel.live/20200918_20_kharkiv/
2. Pay attention to date formate in the travel preview

**Actual Result**
Date format is DD - DD.MM.YYYY

**Expected Result**
Date format is DD.MM.YYYY - DD.MM.YYYY

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/prevyu-podorozhi

**Enviroments**
Windows 10, Chrome 119.0.6045.160 (64 bit)
Android 8.1.0, Chrome 119.0.6045.163
![Харків – Long-Travel - Google Chrome 21 11 2023 16_57_27](https://github.com/scholokov/long-travel-2/assets/95171672/7714c593-ce35-40bf-aec8-0f0bb51f3aaf)
![photo_2023-11-21_16-57-34](https://github.com/scholokov/long-travel-2/assets/95171672/0f2d2fb7-e07f-430b-8c47-1ba2e7a73cc4)

**Comment by DmitriiNasonov** [comment]
#4091

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
