### ISSUE TITLE
"Харків" travel - Map - Drop-down list with a travels is present

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4744]
**Steps of reproducing**
1. Open https://test.long-travel.live/20190907_baydarky/
2. Scroll to Map
3. Pay attention to drop-down list with a travels is present

**Actual Result**
Drop-down list with a travels is present

**Expected Result**
Drop-down list with a travels is missing

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Enviroments**
Windows 10, Chrome 119.0.6045.160 (64 bit)
Android 8.1.0, Chrome 119.0.6045.163
![Харків – Long-Travel - Google Chrome 21 11 2023 17_00_29](https://github.com/scholokov/long-travel-2/assets/95171672/b4b93fbc-8ecc-4e7c-a243-a3f8d3f6b864)
![photo_2023-11-21_17-01-04](https://github.com/scholokov/long-travel-2/assets/95171672/3afee67d-48da-4b9a-834d-c42cf0c035ef)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
