### ISSUE TITLE
"Харків" travel - Preview of standard block "Дорога: Харків – Київ" (where date is 18.09.2020) is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4745]
**Steps of reproducing**
1. Open https://test.long-travel.live/20200918_20_kharkiv/
2. Scroll to block "Дорога: Харків – Київ" (where date is 18.09.2020)

**Actual Result**
Preview of standard block "Дорога: Харків – Київ" (where date is 18.09.2020) is missing

**Expected Result**
Preview of standard block "Дорога: Харків – Київ" (where date is 18.09.2020) is present

**Additional information**
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-27&mode=design&t=FgpH3JUrffE2UJEF-0

**Enviroments**
Windows 10, Chrome 119.0.6045.160 (64 bit)
Android 8.1.0, Chrome 119.0.6045.163
![Харків – Long-Travel - Google Chrome 21 11 2023 17_07_22](https://github.com/scholokov/long-travel-2/assets/95171672/3365226c-9bfa-403b-9f0a-61f1622073bb)
![photo_2023-11-21_17-07-41](https://github.com/scholokov/long-travel-2/assets/95171672/d2957307-00a0-47e7-aac5-1ba3ca97a6b4)

**Comment by DmitriiNasonov** [comment]
#4091

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
