### ISSUE TITLE
"Харків" travel - Body - Preview of "Дорога: Харків – Київ" (where date is 18.09.2020) structural block - Flag of Ukraine is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4746]
**Steps of reproducing**
1. Open https://test.long-travel.live/20200918_20_kharkiv/
2. Scroll to "Дорога: Харків – Київ" (where date is 18.09.2020) block
3. Pay attention to the presence of the flag of Ukraine in the preview

**Actual Result**
Flag of Ukraine is missing

**Expected Result**
Flag of Ukraine is present

**Additional information**
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-27&mode=design&t=8kUGmL7YC412Jd9R-0

**Enviroments**
Windows 10, Chrome 119.0.6045.160 (64 bit)
Android 8.1.0, Chrome 119.0.6045.163
![Харків – Long-Travel - Google Chrome 21 11 2023 17_09_36](https://github.com/scholokov/long-travel-2/assets/95171672/a30891b6-02d5-4499-8ec2-34a183428cf2)
![photo_2023-11-21_17-12-11](https://github.com/scholokov/long-travel-2/assets/95171672/cc736baf-244d-406a-b3c8-76e6836520c4)

**Comment by DmitriiNasonov** [comment]
#4091

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
