### ISSUE TITLE
"Харків" travel - "Готель “Адмірал”" structural block - The meaning of the block "Проміжок часу" is 18-20.09.2020

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4747]
**Steps of reproducing**
1. Open https://test.long-travel.live/20200918_20_kharkiv/
2. Pay attention to the block "Проміжок часу" in the "Готель “Адмірал”" structural block

**Actual Result**
The meaning of the block "Проміжок часу" is 18-20.09.2020

**Expected Result**
The meaning of the block "Проміжок часу" is 18.09.2020

**Enviroments**
Windows 10, Chrome 119.0.6045.160 (64 bit)
Android 8.1.0, Chrome 119.0.6045.163
![Харків – Long-Travel - Google Chrome 21 11 2023 17_19_20](https://github.com/scholokov/long-travel-2/assets/95171672/adcb86fd-9b92-4fb8-b876-bf4af12b2a26)
![photo_2023-12-05_15-21-47](https://github.com/scholokov/long-travel-2/assets/95171672/f30e0615-45c8-421e-bd7c-610eb6e03e0b)

**Comment by DmitriiNasonov** [comment]
#4091

**Comment by scholokov** [comment]
не зрозуміло в чому проблема

**Comment by DmitriiNasonov** [comment]
bug-report is fixed

**Comment by DmytroMarkulych** [comment]
закрийте будь ласка дефект якщо він фіксед

**Comment by DmitriiNasonov** [comment]
bug-report is fixed. BUG is reproduced

**Comment by DmytroMarkulych** [comment]
додайте будь ласка скрін

**Comment by scholokov** [comment]
а чому має бути одна дата?

**Comment by DmitriiNasonov** [comment]
canceled
