### ISSUE TITLE
"Харків" travel - "Готель “Адмірал”" structural block - PhotoGallery type is "random"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4748]
**Steps of reproducing**
1. Open https://test.long-travel.live/20200918_20_kharkiv/
2. Scroll to FotoGallery
3. Pay attention to the FotoGallery type

**Actual Result**
FotoGallery type is "random"

**Expected Result**
FotoGallery type is "Mosaic"

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

**Enviroments**
Windows 10, Chrome 119.0.6045.160 (64 bit)
![DevTools - test long-travel live_20200918_20_kharkiv_ 21 11 2023 17_32_13](https://github.com/scholokov/long-travel-2/assets/95171672/ea6845a7-8964-4588-afb9-435e7703d4e5)

**Comment by DmitriiNasonov** [comment]
#4091

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
