### ISSUE TITLE
"Харків" travel - Name and date of the "Харків" structural block is duplicated

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4749]
**Steps of reproducing**
1. Open https://test.long-travel.live/20200918_20_kharkiv/
2. Scroll to the "Харків" structural block

**Actual Result**
Name and date of the "Харків" structural block is duplicated

**Expected Result**
Name and date of the "Харків" structural block isn't duplicated

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-27&mode=design&t=8kUGmL7YC412Jd9R-0

**Enviroments**
Windows 10, Chrome 119.0.6045.160 (64 bit)
Android 8.1.0, Chrome 119.0.6045.163
![Харків – Long-Travel - Google Chrome 21 11 2023 17_38_28](https://github.com/scholokov/long-travel-2/assets/95171672/e25aa668-f1f6-47a4-91db-ff15f200ef54)
![photo_2023-11-21_17-38-57](https://github.com/scholokov/long-travel-2/assets/95171672/30ee8d6b-7761-4877-bf46-8266fac80bca)

**Comment by DmitriiNasonov** [comment]
#4091

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
