### ISSUE TITLE
"Харків" travel - Name, date and "Місто або Місто, Область" block of the "Ресторан Віват Провінція" structural block is duplicated

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4750]
**Steps of reproducing**
1. Open https://test.long-travel.live/20200918_20_kharkiv/
2. Scroll to the "Ресторан Віват Провінція" structural block

**Actual Result**
Name, date and "Місто або Місто, Область" block of the "Ресторан Віват Провінція" structural block is duplicated

**Expected Result**
Name, date and "Місто або Місто, Область" block of the "Ресторан Віват Провінція" structural block isn't duplicated

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-27&mode=design&t=8kUGmL7YC412Jd9R-0

**Enviroments**
Windows 10, Chrome 119.0.6045.160 (64 bit)
Android 8.1.0, Chrome 119.0.6045.163
![Харків – Long-Travel - Google Chrome 21 11 2023 17_47_26](https://github.com/scholokov/long-travel-2/assets/95171672/e2e2fc22-42fc-4071-a38a-fa168ced4d2f)
![photo_2023-11-21_17-47-45](https://github.com/scholokov/long-travel-2/assets/95171672/3e945349-14e0-4e85-8c85-21127e526cab)

**Comment by DmitriiNasonov** [comment]
#4091

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
