### ISSUE TITLE
"Харків" travel - Preview of standard block "Дорога: Харків – Київ" (where date is 20.09.2020) is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4751]
**Steps of reproducing**
1. Open https://test.long-travel.live/20200918_20_kharkiv/
2. Scroll to block "Дорога: Харків – Київ" (where date is 20.09.2020)

**Actual Result**
Preview of standard block "Дорога: Харків – Київ" (where date is 20.09.2020) is missing

**Expected Result**
Preview of standard block "Дорога: Харків – Київ" (where date is 20.09.2020) is present

**Additional information**
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-27&mode=design&t=FgpH3JUrffE2UJEF-0

**Enviroments**
Windows 10, Chrome 119.0.6045.160 (64 bit)
Android 8.1.0, Chrome 119.0.6045.163
![Харків – Long-Travel - Google Chrome 21 11 2023 17_54_36](https://github.com/scholokov/long-travel-2/assets/95171672/77a6ca82-c589-4089-a32a-a3c78a7614ab)
![photo_2023-11-21_17-54-58](https://github.com/scholokov/long-travel-2/assets/95171672/ea90062f-5f31-49c2-8b0e-6105e8711666)

**Comment by DmitriiNasonov** [comment]
#4091

**Comment by scholokov** [comment]
please retesst
