### ISSUE TITLE
"Харків" travel - Body - Preview of "Дорога: Харків – Київ" (where date is 20.09.2020) structural block - Flag of Ukraine is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4752]
**Steps of reproducing**
1. Open https://test.long-travel.live/20200918_20_kharkiv/
2. Scroll to "Дорога: Харків – Київ" (where date is 20.09.2020) block
3. Pay attention to the presence of the flag of Ukraine in the preview

**Actual Result**
Flag of Ukraine is missing

**Expected Result**
Flag of Ukraine is present

**Additional information**
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-27&mode=design&t=8kUGmL7YC412Jd9R-0

**Enviroments**
Windows 10, Chrome 119.0.6045.160 (64 bit)
Android 8.1.0, Chrome 119.0.6045.163
![Харків – Long-Travel - Google Chrome 21 11 2023 17_58_16](https://github.com/scholokov/long-travel-2/assets/95171672/c8f1367d-695d-4a46-8478-fd7c0a60949d)
![photo_2023-11-21_17-57-38](https://github.com/scholokov/long-travel-2/assets/95171672/0746de1f-cf79-4e99-a0d0-927d6a34e78b)

**Comment by DmitriiNasonov** [comment]
#4091

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
