### ISSUE TITLE
"Харків" travel - Name of the "Дорога: Харків – Київ" (where date is 18.09.2020) structural block is "Дорога: Харків – Київ"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4753]
**Steps of reproducing**
1. Open https://test.long-travel.live/20200918_20_kharkiv/
2. Scroll to "Дорога: Харків – Київ" (where date is 18.09.2020) structural block
3. Pay attention to the name of the structural block

**Actual Result**
Name of the structural block is "Дорога: Харків – Київ"

**Expected Result**
Name of the structural block is "Дорога: Київ - Харків"

**Enviroments**
Windows 10, Chrome 119.0.6045.160 (64 bit)
Android 8.1.0, Chrome 119.0.6045.163
![Харків – Long-Travel - Google Chrome 21 11 2023 18_05_18](https://github.com/scholokov/long-travel-2/assets/95171672/42d00c1b-4254-42c2-9376-7ad5ec4256d4)
![photo_2023-11-21_18-01-49](https://github.com/scholokov/long-travel-2/assets/95171672/d22d4f01-e722-4b72-ac60-42e8ffb71b77)

**Comment by DmitriiNasonov** [comment]
#4091

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
