### ISSUE TITLE
"Харків" travel -  Publication date is 18.09.2020

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4754]
**Steps of reproducing**
1. Open https://test.long-travel.live/20200918_20_kharkiv/
2. Scroll to Publication date

**Actual Result**
Publication date is 18.09.2020

**Expected Result**
Publication date is 20.09.2020 or later

**Additional information**
Publication could not have occurred earlier than or on the day the three-day trip began

**Enviroments**
Windows 10, Chrome 119.0.6045.160 (64 bit)
Android 8.1.0, Chrome 119.0.6045.163
![Харків – Long-Travel - Google Chrome 21 11 2023 18_18_06](https://github.com/scholokov/long-travel-2/assets/95171672/0dec77c6-9b95-42af-bca6-8ea7b6e7af67)
![photo_2023-11-21_18-19-02](https://github.com/scholokov/long-travel-2/assets/95171672/7d6ecdbc-6989-4dc7-9868-d83d765d4ed5)

**Comment by DmitriiNasonov** [comment]
#4091

**Comment by DmytroMarkulych** [comment]
додайте будь ласка деталей в баг репорт

**Comment by DmitriiNasonov** [comment]
canceled
