### ISSUE TITLE
20191207_08_vinnitsa / "Кафе Terra Mare 07.12.2019" preview photo is missing 

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4765]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20191207_08_vinnitsa/
2. Pay attention to the Preview "Кафе Terra Mare 07.12.2019" block.

**Actual result:**
"Кафе Terra Mare 07.12.2019" preview photo is missing.

**Expected result:**
"Кафе Terra Mare 07.12.2019" preview photo is present.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/prevyu-podorozhi

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/04b70074-879a-407e-9886-0c7fdae15275)

**Comment by GNatala** [comment]
#4080

**Comment by DmytroMarkulych** [comment]
додайте будь ласка скрін

**Comment by GNatala** [comment]
Дякую, додала

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
