### ISSUE TITLE
20191207_08_vinnitsa / All photo galleries load immediately

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4766]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20191207_08_vinnitsa/
2. Pay attention that photo galleries load immediately.

**Actual result:**
All photo galleries load immediately.

**Expected result:**
Only the first photo galleries load immediately. The button "Відобразити галерею" appears in all galleries starting from the second one.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://github.com/scholokov/long-travel-2/assets/101987790/951ac15d-544a-497f-aa65-26d669615425)

**Comment by GNatala** [comment]
#4080

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
