### ISSUE TITLE
20191207_08_vinnitsa / The name of Travel in the Preview block is "Винница"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4767]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20191207_08_vinnitsa/
2. Pay attention to the name of Travel in the Preview block.

**Actual result:**
The name of Travel in the Preview block is "Винница".

**Expected result:**
The name of Travel in the Preview block is "Вінниця 2019".

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/52e48752-9cb7-45bc-9269-41fcdaf40abb)

**Comment by GNatala** [comment]
#4080

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
