### ISSUE TITLE
20191207_08_vinnitsa / The preview photo of the Museum block "Музей науки Ukraine 08.12.2019" is missing

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4770]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20191207_08_vinnitsa/
2. Scroll down to the Museum block "Музей науки Ukraine 08.12.2019".
3. Pay attention to the Preview photo of the block.

**Actual result:**
 The preview photo of the Museum block "Музей науки Ukraine 08.12.2019" is missing.

**Expected result:**
 **The preview photo of theMuseum block "Музей науки Ukraine 08.12.2019" is present.**

**Requirements:**
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-6&mode=design&t=kfhgRlkqRGcMVzc4-0
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/prevyu-podorozhi

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/d9716af5-e2b6-40b3-ac5f-093b1743aa66)

**Comment by GNatala** [comment]
#4080

**Comment by scholokov** [comment]
please retest

**Comment by GNatala** [comment]
passed
