### ISSUE TITLE
"Стрижавка – Винница" travel - Travel preview - The "Автомобіль" tag is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4773]
**Steps of reproducing**
1. Open https://test.long-travel.live/20181014_vinnitsa/

**Actual Result**
The "Автомобіль" tag is missing

**Expected Result**
The "Автомобіль" tag is present

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1 (number 57)
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-6&mode=design&t=BLNplPUY0uVax2LZ-0

**Enviroments**
Windows 10, Chrome 119.0.6045.160 (64 bit)
Android 8.1.0, Chrome 119.0.6045.163
![Стрижавка – Винница – Long-Travel - Google Chrome 28 11 2023 13_48_54](https://github.com/scholokov/long-travel-2/assets/95171672/6abdc7eb-0fe2-4c01-90c4-dabafd7e58ac)
![photo_2023-11-28_13-49-01](https://github.com/scholokov/long-travel-2/assets/95171672/39ca77ac-428c-45e5-b224-7d991f77b4cd)

**Comment by DmitriiNasonov** [comment]
#4704

**Comment by DmitriiNasonov** [comment]
#4071

**Comment by scholokov** [comment]
fized

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
