### ISSUE TITLE
Тестове завдання - 1 - Оформлення багів 

### ISSUE THREAD

**Issue by tatianasheremet** [scholokov/long-travel-2#4812]
<h3>Завдання:</h3>

- Оформити відповідно стандартам і завести у GitHub наступні дефекти
- Посилання на заведені дефекти додати у коментар до цієї задачі 

<details>
    <summary><h3>Корисні посилання:</h3></summary> 

| Назва | Посилання
| --- | ---
| Репозиторій, для заведення дефектів | https://github.com/scholokov/long-travel-2/issues
| Додаток, що тестується | https://test.long-travel.live/20210510_staryi_solotvyn_test/
  
</details>

<details>
    <summary><h3>Теорія по темі:</h3></summary> 

| Назва | Посилання
| --- | ---
| Теоретичний матеріал "Як оформляти дефекти" (для доступу необхідно авторизуватися) | https://www.qax-camp.com.ua/courses/practise/lessons/defect/
| Теоретичний матеріал "Як користуватися GitHub" (для доступу необхідно авторизуватися) | https://www.qax-camp.com.ua/courses/qa-basic-programs/lessons/github/
</details>

<h3>Опис помилок:</h3>

| # | Опис помилки | Зображення
| --- | ---     | ---
| 1   | Дата подорожі не там | <img width="1223" alt="image" src="https://github.com/scholokov/long-travel-2/assets/22824947/c1becc88-71af-4682-ad02-cf3490a85393">
| 2   | Має бути тіки прапор України | <img width="1220" alt="image" src="https://github.com/scholokov/long-travel-2/assets/22824947/01833472-0e6b-4f3d-bc0d-8047f008ef2b">
| 3   | Мають бути присутні певні теги | <img width="1214" alt="image" src="https://github.com/scholokov/long-travel-2/assets/22824947/227b54e9-a7a6-4b07-a4d9-6e53d22b1373">
| 4   | Назва кнопки невірна | <img width="1240" alt="image" src="https://github.com/scholokov/long-travel-2/assets/22824947/337e0752-8f10-4731-bdbb-683cfc7f0545">
| 5   | Дублюється інформація у Дорога | <img width="1274" alt="image" src="https://github.com/scholokov/long-travel-2/assets/22824947/f5e19d43-8828-4df3-80b3-b670c15b5644">
| 6   | Відсутнє зображення | <img width="1278" alt="image" src="https://github.com/scholokov/long-travel-2/assets/22824947/ca92b01e-cd67-49bb-836d-4c1cae970249">
| 7   | Відсутній прапор країни | <img width="1277" alt="image" src="https://github.com/scholokov/long-travel-2/assets/22824947/ae66e1af-dcd2-4d41-8e3a-f5e115a26729">
| 8   | Неправильний розмір прапорця | <img width="1276" alt="image" src="https://github.com/scholokov/long-travel-2/assets/22824947/9725ae4f-8bf4-4670-be92-4260263f3982">
| 9   | Неправильний формат галереї | <img width="1276" alt="image" src="https://github.com/scholokov/long-travel-2/assets/22824947/c79a0a46-cb51-4e8f-86aa-32834a442f05">
| 10  | 2 галереї | <img width="712" alt="image" src="https://github.com/scholokov/long-travel-2/assets/22824947/8f5914cc-f9d3-477c-a07e-f1ceffb226cd">
| 11  | Випадаючий список зайвий | <img width="1280" alt="image" src="https://github.com/scholokov/long-travel-2/assets/22824947/f6e5e025-4c36-4609-9490-421dfef484ce">

**Comment by DmitriiNasonov** [comment]
task is completed
