### ISSUE TITLE
20191207_08_vinnitsa / The first photo gallery does not load immediately

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4834]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20191207_08_vinnitsa/
2. Pay attention to the first photo gallery.

**Actual result:**
The first photo gallery does not load immediately. The button "Відобразити галерею" is present.

**Expected result:**
The first photo gallery loads immediately. The button "Відобразити галерею" does not appear in the first gallery.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/565a5bdb-c59c-4ebf-9445-294429bae94f)

**Comment by GNatala** [comment]
#4080

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
