### ISSUE TITLE
20191207_08_vinnitsa / Restaurant Block "Кафе Terra Mare" -  the Ukrainian flag is missing 

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4835]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20191207_08_vinnitsa/
2. Pay attention to the Restaurant Block "Кафе Terra Mare".

**Actual result:**
In the Restaurant Block "Кафе Terra Mare" the Ukrainian flag is missing.

**Expected result:**
In the Restaurant Block "Кафе Terra Mare" the Ukrainian flag is present.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://github.com/scholokov/long-travel-2/assets/101987790/814441d6-0c2e-4c1d-9e89-095f3da27ab9)

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
