### ISSUE TITLE
20191207_08_vinnitsa / Restaurant Block "Кафе Terra Mare" - the location city "Вінниця" is missing 

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4836]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20191207_08_vinnitsa/
2. Pay attention to the Restaurant Block "Кафе Terra Mare".

**Actual result:**
In the Restaurant Block "Кафе Terra Mare" the location city "Вінниця" is missing.

**Expected result:**
In the Restaurant Block "Кафе Terra Mare" the location city "Вінниця" is present.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/ba52fc1d-d429-457e-a3fd-92480030528e)

**Comment by GNatala** [comment]
#4080

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
