### ISSUE TITLE
20191207_08_vinnitsa / Hotel block "Hotel Boutique TOVMED" - the location city "Вінниця" is missing

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4838]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20191207_08_vinnitsa/
2. Scroll down to the Hotel block "Hotel Boutique TOVMED"
3. Pay attention to the block.

**Actual result:**
In the Hotel block "Hotel Boutique TOVMED" the location city "Вінниця" is missing.

**Expected result:**
In the Hotel block "Hotel Boutique TOVMED" the location city "Вінниця" is present.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/1cf68d9d-858a-40e0-9295-dc0b5421994e)

**Comment by GNatala** [comment]
#4080

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
