### ISSUE TITLE
20191207_08_vinnitsa / City block "Винница Ukraine 08.12.2019" - the Ukrainian flag is missing

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4839]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20191207_08_vinnitsa/
2. Scroll down to the City block "Винница Ukraine 08.12.2019"
3. Pay attention to the block.

**Actual result:**
In the City block "Винница Ukraine 08.12.2019" the Ukrainian flag is missing.

**Expected result:**
In the City block "Винница Ukraine 08.12.2019" the Ukrainian flag is present.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/fb4046a5-c128-46df-b69a-2254b82cf1cc)

**Comment by GNatala** [comment]
#4080

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
