### ISSUE TITLE
20191207_08_vinnitsa / Museum block "Музей науки" - the Ukrainian flag is missing

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4840]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20191207_08_vinnitsa/
2. Scroll down to the Museum block "Музей науки"
3. Pay attention to the block.

**Actual result:**
In the Museum block "Музей науки" the Ukrainian flag is missing.

**Expected result:**
In the Museum block "Музей науки" the Ukrainian flag is present.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/e2eb175b-5ea4-4cdb-9550-1a1c3e787821)

**Comment by GNatala** [comment]
#4080

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
An issue is reproduced.

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/101987790/f7ce4e22-7ab7-4521-a511-41067474d5e8)
![image](https://github.com/scholokov/long-travel-2/assets/101987790/4c87804e-24cf-453c-888c-dbdf2c7e504a)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
