### ISSUE TITLE
20191207_08_vinnitsa / Road block "Road: Винница – Киев" - the Ukrainian flag is missing

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4841]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20191207_08_vinnitsa/
2. Scroll down to the Road block "Road: Винница – Киев"
3. Pay attention to the block.

**Actual result:**
In the Road block "Road: Винница – Киев" the Ukrainian flag is missing.

**Expected result:**
In the Road block "Road: Винница – Киев" the Ukrainian flag is present.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://github.com/scholokov/long-travel-2/assets/101987790/7a77f97b-5ca3-4cec-838d-bad9c89d484c)

**Comment by GNatala** [comment]
#4080

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
