### ISSUE TITLE
20191207_08_vinnitsa /  The Extra text "Ukraine" is in the City block "Винница"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4862]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20191207_08_vinnitsa/
2. Scroll down to the City block "Винница Ukraine 08.12.2019"
3. Pay attention to the name of the country Ukraine in the Block.

**Actual result:**
 The xtra text "Ukraine" in the City block "Винница".

**Expected result:**
 The extra text "Ukraine" is not in the City block "Винница". 

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/3bed8fc6-22be-4c9c-8fba-b60a8c4dd1de)

**Comment by GNatala** [comment]
#4080

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
