### ISSUE TITLE
"Старий Солотвин" travel - Travel preview - The Black Tag is present

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4869]
**Steps of reproducing**
1. Open https://test.long-travel.live/20210510_staryi_solotvyn_test/

**Actual Result**
The Black Tag is present

**Expected Result**
The Black Tag is missing

**Additional information**
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=0-1&mode=design&t=z0XLFtV2sGcghzxY-0

**Environments**
Windows 10, Chrome 119.0.6045.200 (64 bit)
Android 8.1.0, Chrome 119.0.6045.163
![Старий Солотвин – Long-Travel - Google Chrome 09 12 2023 20_45_12](https://github.com/scholokov/long-travel-2/assets/95171672/87013bfb-bfa9-4923-8650-2cb2d903bc4c)
![photo_2023-12-09_20-45-06](https://github.com/scholokov/long-travel-2/assets/95171672/faf6bb59-7b16-40ce-acf4-b1651d3b1475)

**Comment by DmitriiNasonov** [comment]
#4812

**Comment by scholokov** [comment]
це тестувати не потрібно:
20210510_staryi_solotvyn_test
подорож для тестування:
20210510_staryi_solotvyn

**Comment by DmitriiNasonov** [comment]
canceled
