### ISSUE TITLE
"Старий Солотвин" travel - "Острів кохання" structural block - PhotoGallery type is "random"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4870]
**Steps of reproducing**
1. Open https://test.long-travel.live/20210510_staryi_solotvyn_test/
2. Scroll to FotoGallery
3. Pay attention to the FotoGallery type

**Actual Result**
The FotoGallery type is "random"

**Expected Result**
The FotoGallery type is "Mosaic"

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

**Environments**
Windows 10, Chrome 120.0.6099.71 (64 bit)
![DevTools - test long-travel live_20210510_staryi_solotvyn_test_ 09 12 2023 20_52_54](https://github.com/scholokov/long-travel-2/assets/95171672/4f4a3924-7d1b-4a84-94b7-dd04f8e99bc3)

**Comment by DmitriiNasonov** [comment]
#4812

**Comment by scholokov** [comment]
це тестувати не потрібно:
20210510_staryi_solotvyn_test
подорож для тестування:
20210510_staryi_solotvyn

**Comment by DmitriiNasonov** [comment]
canceled
