### ISSUE TITLE
20191207_08_vinnitsa / Name of the City block "Винница"  is written in russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4871]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20191207_08_vinnitsa/
2. Scroll down to the City block "Винница Ukraine 08.12.2019"
3. Pay attention to the name of the Block.

**Actual result:**
 The name of the City block "Винница"  is written in russian.

**Expected result:**
 The name of the City block "Винница"  is written in Ukrainian.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/1.overall/language

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/f828038a-fafa-4c0b-82e3-eea323ccb0aa)

**Comment by GNatala** [comment]
#4080

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
