### ISSUE TITLE
20191207_08_vinnitsa / The name city in the Museum block "Музей науки" is written as "Ukraine"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4872]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20191207_08_vinnitsa/
2. Scroll down to the Museum block "Музей науки"
3. Pay attention to the block.

**Actual result:**
 The name city in the Museum block "Музей науки" is written as "Ukraine".

**Expected result:**
 The name city in the Museum block "Музей науки" is written as "Вінниця".

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/f7ab2454-3720-4720-a1e9-069966064f08)

**Comment by GNatala** [comment]
#4080

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/long-travel-2/assets/88647733/9db9bdce-dbe0-4947-b29e-5005a57f25da)

**Comment by GNatala** [comment]
Дякую, виправила

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
