### ISSUE TITLE
20191207_08_vinnitsa /The Road block name format is  "Road: Винница – Киев Ukraine 08.12.2019" 

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4873]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20191207_08_vinnitsa/
2. Scroll down to the Road block "Road: Винница – Киев"
3. Pay attention to the block.

**Actual result:**
The Road block name format is:  
"Road: Винница – Киев 
Ukraine 
08.12.2019".

**Expected result:**
**The Road block name format is:
                                                      "Дорога: 
                                                        Вінница – Київ 
                                                        08.12.2019".**

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/41849be9-0657-45dc-9d4a-702a750c3a2a)

**Comment by GNatala** [comment]
#4080

**Comment by scholokov** [comment]
виправлено

**Comment by GNatala** [comment]
перевірено
