### ISSUE TITLE
20191207_08_vinnitsa /The Road block name  "Дорога Винница – Киев" is written in russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4880]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20191207_08_vinnitsa/
2. Scroll down to the Road block "Дорога Винница – Киев"
3. Pay attention to the block name.

**Actual result:**
The Road block name  "Дорога Винница – Киев" is written in russian.

**Expected result:**
The Road block name  "Дорога Винница – Киев" is written in Ukrainian.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/41a21515-cf99-4bfe-87b3-05d54ea96416)

**Comment by GNatala** [comment]
#4080

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
