### ISSUE TITLE
"Черкаси 2017" travel - Map -  Drop-down list with a travels is present

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4884]
**Steps of reproducing**
1. Open https://test.long-travel.live/20171027_cherkasy/
2. Scroll to the map

**Actual Result**
The drop-down list with travels is present

**Expected Result**
The drop-down list with travels is missing

**Additional information**
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=0-1&mode=design&t=z0XLFtV2sGcghzxY-0

**Environments**
Windows 10, Chrome 120.0.6099.110 (64 bit)
![Черкаси 2017 – Long-Travel - Google Chrome 20 12 2023 16_59_35](https://github.com/scholokov/long-travel-2/assets/95171672/bc425875-74b9-4e7d-b571-30336ff1e1e2)

**Comment by DmitriiNasonov** [comment]
#3430

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
