### ISSUE TITLE
20151031_haisyn_uman/  Tags "Автомобиль", "Парк", "Цікаво" are missing in the Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4896]
**Steps to reproduce:**

1. Open   https://test.long-travel.live/20151031_haisyn_uman/
2. Pay attention to the absence of the tags in the Preview block.

**Actual result:**
Tags "Автомобиль", "Парк", "Цікаво" are missing in the Preview block.

**Expected result:**
Tags "Автомобиль", "Парк", "Цікаво" are present in the Preview block.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/01b9463e-a7a7-4143-8cf2-108a87307046)

**Comment by GNatala** [comment]
#4895

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
An issue is reproduced.
The tag "Цікаво" is missing in the Preview block.

Attachment:


![Image](https://github.com/scholokov/long-travel-2/assets/101987790/fb69cd02-8414-4e9a-b701-379636eb5cdf)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
