### ISSUE TITLE
20160326_Konotop/ Tag "Автомобиль" is missing in the Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4898]
**Steps to reproduce:**

1. Open   https://test.long-travel.live/20160326_Konotop/
2. Pay attention to the absence of the tag in the Preview block

**Actual result:**
Tag "Автомобиль" is missing in the Preview block.

**Expected result:**
Tag "Автомобиль" is present in the Preview block.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/60aa122e-c912-4416-bfa8-ca23779c9467)

**Comment by GNatala** [comment]
#4895

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
Passed
