### ISSUE TITLE
20160518_22_Eger/ Tags "Long travel", "Цікаво" are missing in the Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4899]
**Steps to reproduce:**

1. Open   https://test.long-travel.live/20160518_22_Eger
2. Pay attention to the absence of the tags in the Preview block

**Actual result:**
Tags "Long travel", "Цікаво" are missing in the Preview block.

**Expected result:**
Tags "Long travel", "Цікаво" are present in the Preview block.

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/f138b64c-75b1-4fbc-b950-4afa0d05825a)

**Comment by GNatala** [comment]
#4896

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
An issue is reproduced.
The tag "Цікаво" is missing in the Preview block.

Attachment:


![Image](https://github.com/scholokov/long-travel-2/assets/101987790/2905c712-cffc-4ab6-a75f-cfb640c00c75)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
