### ISSUE TITLE
"Пошук" module - "Біла церква" travel (where date is 2006.10.28) can't be founded with the "Автомобіль" tag

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4902]
**Steps of reproducing**
1. Open https://test.long-travel.live/travels/
2. Enable search for "Автомобіль" tag
3. Scroll to the end of the travel list

**Actual Result**
"Біла церква" travel (where the date is 2006.10.28) CAN'T be founded with the "Автомобіль" tag

**Expected Result**
"Біла церква" travel (where the date is 2006.10.28) CAN be founded with the "Автомобіль" tag

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1 (number of travel is "1")
Travel id - 20061028_bila_tserkva
The “Автомобіль” tag is present in the travel

**Environments**
Windows 10, Chrome 120.0.6099.130 (64 bit)
Android 8.1.0, Chrome 120.0.6099.115
![Travels – Long-Travel - Google Chrome 27 12 2023 12_47_38](https://github.com/scholokov/long-travel-2/assets/95171672/e244188d-d785-47fd-b5d4-1b94c863f2a9)
![photo_2023-12-27_13-37-09](https://github.com/scholokov/long-travel-2/assets/95171672/2a2bc657-ff63-4432-a35c-786fde5d9cab)

**Comment by DmitriiNasonov** [comment]
#4891

**Comment by scholokov** [comment]
не вистачає айді подорожі

**Comment by DmitriiNasonov** [comment]
Travel ID added to the "Additional information" block

**Comment by scholokov** [comment]
але ж там знайдено 40 подорожей. подивився на всіх закладках?

**Comment by DmitriiNasonov** [comment]
canceled
