### ISSUE TITLE
"Пошук" module - "Львів_Львівска область_Україна" travel can't be founded with the "Автомобіль" tag

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4904]
**Steps of reproducing**
1. Open https://test.long-travel.live/travels/
2. Enable search for "Автомобіль" tag
3. Scroll to the end of the travel list

**Actual Result**
"Львів_Львівска область_Україна" travel CAN'T be founded with the "Автомобіль" tag

**Expected Result**
"Львів_Львівска область_Україна" travel CAN be founded with the "Автомобіль" tag

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1 (number of travel is "2")

**Environments**
Windows 10, Chrome 120.0.6099.130 (64 bit)
Android 8.1.0, Chrome 120.0.6099.115
![Travels – Long-Travel - Google Chrome 27 12 2023 14_13_18](https://github.com/scholokov/long-travel-2/assets/95171672/b36d4d19-708c-470d-9de0-10c8c06ec68b)
![photo_2023-12-27_14-14-40](https://github.com/scholokov/long-travel-2/assets/95171672/17b2567d-1625-4f4e-9ce7-dd7577297bb1)

**Comment by DmitriiNasonov** [comment]
#4891

**Comment by scholokov** [comment]
не вистачає айді подорожі

**Comment by DmitriiNasonov** [comment]
bug isn't reproducing. bug-report is canceled
