### ISSUE TITLE
"Пошук" module - "Національний дендрологічний парк “Софіївка”" travel (where date is 2007.10.27) can't be founded with the "Автомобіль" tag

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4908]
**Steps of reproducing**
1. Open https://test.long-travel.live/travels/
2. Enable search for "Автомобіль" tag
3. Scroll to the end of the travel list

**Actual Result**
"Біла церква" travel (where the date is 2006.10.28) CAN'T be founded with the "Автомобіль" tag

**Expected Result**
"Біла церква" travel (where the date is 2006.10.28) CAN be founded with the "Автомобіль" tag

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1 (number of travel is "4")

**Environments**
Windows 10, Chrome 120.0.6099.130 (64 bit)
Android 8.1.0, Chrome 120.0.6099.115
![Travels – Long-Travel - Google Chrome 27 12 2023 14_48_05](https://github.com/scholokov/long-travel-2/assets/95171672/46c606bd-b0a9-43a2-a100-93c39b90413d)

**Comment by DmitriiNasonov** [comment]
#4891

**Comment by scholokov** [comment]
не вистачає айді подорожі

**Comment by DmitriiNasonov** [comment]
bug isn't reproducing. Bug-report canceled
