### ISSUE TITLE
"Пошук" module - Tags - The "Парк" tag is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4909]
**Steps of reproducing**
1. Open https://test.long-travel.live/travels/

**Actual Result**
The "Парк" tag is missing

**Expected Result**
The "Парк" tag is present

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/tags

**Environments**
Windows 10, Chrome 120.0.6099.130 (64 bit)
Android 8.1.0, Chrome 120.0.6099.115
![Travels – Long-Travel - Google Chrome 27 12 2023 15_00_17](https://github.com/scholokov/long-travel-2/assets/95171672/fa220207-370f-4541-9312-f7d0a65f9eab)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
