### ISSUE TITLE
"Пошук" module - Tags - The "Цікаво" tag is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#4910]
**Steps of reproducing**
1. Open https://test.long-travel.live/travels/

**Actual Result**
The "Цікаво" tag is missing

**Expected Result**
The "Цікаво" tag is present

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/tags

**Environments**
Windows 10, Chrome 120.0.6099.130 (64 bit)
Android 8.1.0, Chrome 120.0.6099.115
![Travels – Long-Travel - Google Chrome 27 12 2023 15_00_21](https://github.com/scholokov/long-travel-2/assets/95171672/af22075e-cbdb-446b-ad06-38adcdd3e64d)

**Comment by DmitriiNasonov** [comment]
#4891

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
