### ISSUE TITLE
20150530_Kiev_Aviation_Museum/ The "Державний музей авіації" name of the travel is displayed in the Preview of the Travel

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4927]
Steps to reproduce:

1. Open page https://test.long-travel.live/20150530_Kiev_Aviation_Museum/
2. Pay attention to the "Державний музей авіації" name of the travel in the Preview of the Travel

Actual Result: The "Державний музей авіації" name of the travel is displayed in the Preview of the Travel

Expected Result:The "Державний музей авіації літо 2015" name of the travel is displayed in the Preview of the Travel

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:![image](https://github.com/scholokov/long-travel-2/assets/123776698/10899474-cdf7-4d20-8bed-2562e640b2d1)612816cc-dc61-4149-9917-10fbaae19e76)

**Comment by ODrobik** [comment]
#4894

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
