### ISSUE TITLE
20130613_0628_bulgaria / У "Прев'ю подорожі" у назві "Болград – Слънчев бряг – București – Саврань" відображено 44 символи

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#4930]
**Кроки відтворення:**
1. Відкрити веб-сторінку подорожі Болград – Слънчев бряг – București – Саврань https://test.long-travel.live/20130613_0628_bulgaria/
2. Звернути увагу на кількість символів у назві блока "Прев'ю подорожі"

**Фактичний результат:**
1. У назві 44 символи

**Очікуваний результат:**
1. У назві максимальна довжина 39 символів згідно вимог

**Прикріплені файли:**
<img width="1278" alt="Снимок экрана 2023-12-27 в 21 50 36" src="https://github.com/scholokov/long-travel-2/assets/130754297/45a35e00-5a47-42f6-b0bf-398178e0b969">
<img width="1280" alt="Снимок экрана 2023-12-27 в 21 27 21" src="https://github.com/scholokov/long-travel-2/assets/130754297/3eec4e92-d8e5-4b0b-9263-30de427defe4">

**Документація:**
[Подорожі - список](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list)

**Додаткова інформація:**
Браузер: Google Chrome версія 120.0.6099.109
ОС: macOS версія 11.7.10

**Comment by Nanafox2010** [comment]
https://github.com/scholokov/long-travel-2/issues/4892

**Comment by scholokov** [comment]
ок - відносно нових вимог

**Comment by Nanafox2010** [comment]
перевірено
