### ISSUE TITLE
20130613_0628_bulgaria / У "Прев'ю подорожі" відсутній прапор Молдови

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#4931]
**Кроки відтворення:**
1. Відкрити веб-сторінку подорожі Болград – Слънчев бряг – București – Саврань https://test.long-travel.live/20130613_0628_bulgaria/
2. Звернути увагу на правий верхній кут блока "Прев'ю подорожі"

**Фактичний результат:**
1. Відсутній прапор Молдови

**Очікуваний результат:**
1. Прапор Молдови відображається

**Прикріплені файли:**
<img width="1280" alt="Снимок экрана 2023-12-27 в 22 15 18" src="https://github.com/scholokov/long-travel-2/assets/130754297/96abcc7d-99bf-43d6-aaee-e77c268e639e">

**Документація:**
[Подорожі - список](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list)

**Додаткова інформація:**
Браузер: Google Chrome версія 120.0.6099.109
ОС: macOS версія 11.7.10

**Comment by Nanafox2010** [comment]
https://github.com/scholokov/long-travel-2/issues/4892

**Comment by scholokov** [comment]
у молдові не було зупинок. тому не виносив у список...

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
помилка відтворюється. 
Згідно [Повного переліку всіх подорожей](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list) та [Вимог до "Прев'ю подорожі"](https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/prevyu-podorozhi) (п. 1.1.3, п.1.1.3.1) прапор Молдови повинен відображатись у Прев'ю. 


![Image](https://github.com/scholokov/long-travel-2/assets/130754297/1fe7e683-c20d-4a4a-b5f0-e076f5dcb932)
![Image](https://github.com/scholokov/long-travel-2/assets/130754297/20cd5c3c-feb3-466d-b0be-894bc64d66d7)

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
