### ISSUE TITLE
Search / The tag "Цікаво" has the checker named "Варто відвідати"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4932]
**Steps to reproduce:**

1. Open: https://test.long-travel.live/travels/
2. Pay attention to the checker "Варто відвідати" in the column "Обрати за цікавістю".
3. Pay attention to the corresponding tag "Цікаво" in the Requirements.

**Actual result:**
The tag "Цікаво" has the checker named "Варто відвідати".

**Expected result:**
The tag "Цікаво" has the checker named "Цікаво".

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1
https://www.canva.com/design/DAFw91Vnt90/x5sS_mHl-eBxCXZYT2tf3w/edit

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/35ad6b09-a47c-40ee-b983-97fba5c0c01a)

**Comment by GNatala** [comment]
#4895

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
Passed
