### ISSUE TITLE
20151031_haisyn_uman/ In the Preview the name of Travel is "Гайсинська ДЮСШ та Дендропарк “Софіївка”" 

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4934]
**Steps to reproduce:**

1. Open   https://test.long-travel.live/20151031_haisyn_uman/
2. Pay attention to the name of Travel is "Гайсинська ДЮСШ та Дендропарк “Софіївка” the Preview.

**Actual result:**
 In the Preview the name of Travel is "Гайсинська ДЮСШ та Дендропарк “Софіївка”".

**Expected result:**
 In the Preview, the name of Travel is "Гайсин - Умань".

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/fcb7751e-0e67-49fb-90b9-7a2ffeb7397c)

**Comment by GNatala** [comment]
#4895

**Comment by scholokov** [comment]
виправлено у вимогах

**Comment by GNatala** [comment]
В вимогах назва подорожі все ще не змінена "Гайсин - Умань".

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/101987790/6b533b82-ca88-4619-a59d-824a344d1f99)

**Comment by scholokov** [comment]
![image](https://github.com/scholokov/long-travel-2/assets/22824947/a5805bfd-7f69-4057-9a6b-47aadb7905aa)

**Comment by GNatala** [comment]
passed
