### ISSUE TITLE
Requirements / The image for the tag "Парк" is missing in Canva

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4935]
**Steps to reproduce:**

1. Open https://www.canva.com/design/DAFw91Vnt90/x5sS_mHl-eBxCXZYT2tf3w/edit
2. Pay attention that the image for the tag "Парк" is missing.

**Actual result:**
 The image for the tag "Парк" is missing in Canva.

**Expected result:**
 The image for the tag "Парк" is present in Canva.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/21b77a76-81c2-4849-be3f-f8a46fac3dc4)
![image](https://github.com/scholokov/long-travel-2/assets/101987790/ba9ac8bc-4c4a-46f6-8835-87717c74a0fe)

**Comment by GNatala** [comment]
#4895

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
