### ISSUE TITLE
20150919_Kiev_Aviation_Museum/ The "Музей" tag is not displayed in the Preview of the Travel 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4946]
Steps to reproduce:

1. Open page https://test.long-travel.live/20150919_Kiev_Aviation_Museum/
2. Pay attention to the "Автомобіль" tag in the Preview of the Travel

Actual Result: The "Музей" tag is not displayed in the Preview of the Travel

Expected Result:The "Музей" tag is displayed in the Preview of the Travel

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/3950cefb-88ae-4d49-9e9b-8c41136c77fe)

**Comment by ODrobik** [comment]
#4894

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
