### ISSUE TITLE
Search/ The "Цікаво" item of the filter is not displayed on the Travels page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4949]
Steps to reproduce:

1. Open page https://test.long-travel.live/travels/
2. Pay attention to the ""Цікаво" item of the filter on the Travels page

Actual Result: The "Цікаво" item of the filter is not displayed on the Travels page

Expected Result: The "Цікаво" item of the filter is displayed on the Travels page

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/38942cb5-4a94-40a0-8e0a-b78449e104c3)

**Comment by ODrobik** [comment]
#4894

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
