### ISSUE TITLE
20191207_08_vinnitsa / In the Map's legend, position of the event "Музей науки" is missed

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4951]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20191207_08_vinnitsa/
2. Pay attention to the Map's legend -  position of the event "Музей науки".

**Actual Result:** 
The current position of the event "Музей науки" is such that its date is Dec 7, 2019.

**Expected Result:** 
The date of the event **"Музей науки" is Dec 8, 2019.**, so it should be placed after Kyiv, Ukraine - Dec 8, 2019

**Additional information:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/2b8030e0-02d5-4197-b495-3256588b3b60)

![image](https://github.com/scholokov/long-travel-2/assets/101987790/3c3da7ca-f1e3-42c8-a27d-93fc425ed749)

**Comment by GNatala** [comment]
#4080

**Comment by scholokov** [comment]
але в даному випадку точки не ідуть по черзі. а готель є материнською точкою для музея. тому музей просто під готелем...

**Comment by GNatala** [comment]
passed
