### ISSUE TITLE
20150623_0711_Croati/ The "Море" tag is not displayed in the Preview of the Travel

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#4953]
Steps to reproduce:

1. Open page https://test.long-travel.live/20150623_0711_Croatia/
2. Pay attention to the "Море" tag in the Preview of the Travel

Actual Result: The "Море" tag is not displayed in the Preview of the Travel

Expected Result:The "Море" tag is displayed in the Preview of the Travel

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/2656f8c9-8f60-4276-b2cc-7e009f9d3f27)

**Comment by ODrobik** [comment]
#4894

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
