### ISSUE TITLE
20170417_kiylov/ In the Preview, the name of Travel is "Київська область, Кийлів, ферма-заповідник Кийлівська Асканія"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4963]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20170417_kiylov/
2. Pay attention to the name of Travel is "Київська область, Кийлів, ферма-заповідник Кийлівська Асканія"

**Actual result:**
 In the Preview, the name of Travel is "Київська область, Кийлів, ферма-заповідник Кийлівська Асканія".

**Expected result:**
 In the Preview, the name of Travel is "Заповідник "Кийлівська Асканія"".

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/03defd77-52ae-4f82-a38f-658a002270ca)

**Comment by GNatala** [comment]
#4960

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
An issue is reproduced.

Attachment:

![image](https://github.com/scholokov/long-travel-2/assets/101987790/d85c00e1-3af0-4814-8523-7d7abee43493)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
