### ISSUE TITLE
20170417_Kiylov/ Tags "Автомобиль", "Річка-Озеро", "Зоопарк", "Цікаво" are missing in the Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4964]
**Steps to reproduce:**

1. Open   https://test.long-travel.live/20170417_Kiylov/
2. Pay attention to the absence of the tags in the Preview block.

**Actual result:**
Tags "Автомобиль", "Річка-Озеро", "Зоопарк", "Цікаво" are missing in the Preview block.

**Expected result:**
Tags "Автомобиль", "Річка-Озеро", "Зоопарк", "Цікаво" are present in the Preview block.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/2f71ba0a-e28c-41db-8efd-81619e6f37cb)

**Comment by GNatala** [comment]
#4960

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
An issue is reproduced.

The tag "Цікаво" is missing in the Preview block.

Attachment:

![Image](https://github.com/scholokov/long-travel-2/assets/101987790/8996febd-442a-4886-9e23-24aa0f293f97)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
