### ISSUE TITLE
20170509_Kiev_Museum_Great_Patriotic_War/ The extra tag "Автомобиль" is in the Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4965]
**Steps to reproduce:**
1. Open   https://test.long-travel.live/20170509_Kiev_Museum_Great_Patriotic_War/
2. Pay attention to the tag "Автомобиль" in the Preview block.

**Actual result:**
The extra tag "Автомобиль" is in the Preview block.

**Expected result:**
The extra tag "Автомобиль" is not present in the Preview block.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/0104e9e8-8fde-46f5-8e2d-f1842afad575)

**Comment by GNatala** [comment]
#4960

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
Passed
