### ISSUE TITLE
20170509_Kiev_Museum_Great_Patriotic_War/ Tags "Військовий об'єкт", "Цікаво" are missing in the Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4966]
**Steps to reproduce:**

1. Open   https://test.long-travel.live/20170509_Kiev_Museum_Great_Patriotic_War/
2. Pay attention to the absence of the two tags in the Preview block.

**Actual result:**
Tags "Військовий об'єкт", "Цікаво" are missing in the Preview block.

**Expected result:**
Tags "Військовий об'єкт", "Цікаво" are present in the Preview block.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/6d744ee0-79bf-4fea-bc35-bcff2f4569ea)

**Comment by GNatala** [comment]
#4960

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
An issue is reproduced.
The tag "Цікаво" is missing in the Preview block.

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/101987790/e06111db-f626-4252-b0eb-32adb1e76468)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
