### ISSUE TITLE
20170513_Putivl_Kruti/ Tags "Військовий об'єкт", "Цікаво" are missing in the Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4967]
**Steps to reproduce:**

1. Open   https://test.long-travel.live/20170513_Putivl_Kruti/
2. Pay attention to the absence of the two tags in the Preview block.

**Actual result:**
Tags "Військовий об'єкт", "Цікаво" are missing in the Preview block.

**Expected result:**
Tags "Військовий об'єкт", "Цікаво" are present in the Preview block.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/3aa37a90-8419-4bbc-93be-0bc04d3ca387)

**Comment by GNatala** [comment]
#4960

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
