### ISSUE TITLE
Travel / The tag "Цікаво" is missing in the Preview block of 21 Travels

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#4984]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/travels/
2. Mark the checker  "Цікаво".
3. 21 Travels with the tag "Цікаво" are shown.
4. Open any Travel from the chosen.
5. Pay attention to the absence of the tag "Цікаво" in the Preview block

**Actual result:**
The tag "Цікаво" is missing in the Preview block of 21 Travels.

**Expected result:**
The tag "Цікаво" is present in the Preview block of 21 Travels.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/75e31a72-b822-47f6-a73c-b48c80228c9c)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
