### ISSUE TITLE
20130613_0628_bulgaria / У "Прев'ю подорожі" картинка тегу "Зоопарк" розташована з правої сторони біля прапорів

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#4985]
**Кроки відтворення:**
1. Відкрити веб-сторінку подорожі Болград – Слънчев бряг – București – Саврань https://test.long-travel.live/20130613_0628_bulgaria/
2. Звернути увагу на правий верхній кут блока "Прев'ю подорожі"

**Фактичний результат:**
1. Картинка тегу "Зоопарк" розташована з правої сторони

**Очікуваний результат:**
1. Картинка тегу "Зоопарк" відсутня

**Прикріплені файли:**
![Image](https://github.com/scholokov/long-travel-2/assets/130754297/4e15ab81-bc3f-4935-8982-e86d9176d70c)

**Документація:**
[Подорожі - теги](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1)

**Додаткова інформація:**
Браузер: Google Chrome версія 120.0.6099.199
ОС: macOS версія 11.7.10

**Comment by Nanafox2010** [comment]
https://github.com/scholokov/long-travel-2/issues/4892

**Comment by scholokov** [comment]
fixed
