### ISSUE TITLE
Long-travel 2 / У Вимогах не вистачає посилання на існуючі іконки тегів з відповідними назвами

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#4987]
**Кроки відтворення:**
1. Відкрити [Вимоги](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1)
2. Звернути увагу на відсутність посилань на іконки тегів

**Фактичний результат:**

1. Посилання на іконки тегів відсутнє

**Очікуваний результат:**

1. Посилання на іконки тегів зазначено

**Прикріплені файли:**
<img width="1280" alt="Снимок экрана 2024-01-08 в 17 18 04" src="https://github.com/scholokov/long-travel-2/assets/130754297/cff99010-4cbe-4e86-959d-50a28cf9a3f4">

Додаткова інформація:
Браузер: Google Chrome версія 120.0.6099.199
ОС: macOS версія 11.7.10

**Comment by Nanafox2010** [comment]
https://github.com/scholokov/long-travel-2/issues/4892

**Comment by scholokov** [comment]
реалізовано

**Comment by Nanafox2010** [comment]
verified
