### ISSUE TITLE
20070406_09_lviv / У блоці "Прев'ю подорожі" відсутній тег "Автомобіль"

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#4990]
**Кроки відтворення:**
1. Відкрити веб-сторінку подорожі Львів https://test.long-travel.live/20070406_09_lviv/
2. Звернути увагу на лівий верхній кут блока "Прев'ю подорожі"

**Фактичний результат:**
1. Відсутній тег "Автомобіль" у блоці

**Очікуваний результат:**
1. У блоці відображен такий тег:
- Автомобіль

**Прикріплені файли:**
<img width="1280" alt="Снимок экрана 2024-01-08 в 22 29 18" src="https://github.com/scholokov/long-travel-2/assets/130754297/2cb2cfb0-6b64-4645-9bf9-088bfc0c7960">

**Документація:**
[Подорожі - теги](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1)

**Додаткова інформація:**
Браузер: Google Chrome версія 120.0.6099.199
ОС: macOS версія 11.7.10

**Comment by Nanafox2010** [comment]
https://github.com/scholokov/long-travel-2/issues/4958

**Comment by DmytroMarkulych** [comment]
було б добре вказати який тег відсутній

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
