### ISSUE TITLE
20070406_09_lviv / У блоці "Прев'ю подорожі" зазначена назва "Львів_Львівска область_Україна"

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#4991]
**Кроки відтворення:**
1. Відкрити веб-сторінку подорожі Львів https://test.long-travel.live/20070406_09_lviv/
2. Звернути увагу на назву блоку "Прев'ю подорожі"

**Фактичний результат:**
1. Зазначено назву "Львів_Львівска область_Україна"

**Очікуваний результат:**
1. Зазначено назву "Львів 2007"

**Прикріплені файли:**
<img width="1280" alt="Снимок экрана 2024-01-08 в 22 29 41" src="https://github.com/scholokov/long-travel-2/assets/130754297/3a0276cf-eb5e-47db-897b-8ea02803d9ad">

**Документація:**
[Подорожі - список](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list)

**Додаткова інформація:**
Браузер: Google Chrome версія 120.0.6099.199
ОС: macOS версія 11.7.10

**Comment by Nanafox2010** [comment]
https://github.com/scholokov/long-travel-2/issues/4958

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
