### ISSUE TITLE
20070722_0809_Crimea / У блоці "Прев'ю подорожі" зазначена назва "Рибаче – Ялта – Балаклава – Севастополь – Судак – Новий Світ"

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#4993]
**Кроки відтворення:**

1. Відкрити веб-сторінку подорожі Крим https://test.long-travel.live/20070722_0809_crimea/
2. Звернути увагу на назву блоку "Прев'ю подорожі"

**Фактичний результат:**
1. Зазначено назву "Рибаче – Ялта – Балаклава – Севастополь – Судак – Новий Світ"

**Очікуваний результат:**
1. Зазначено назву "Крим"

**Прикріплені файли:**
<img width="1280" alt="Снимок экрана 2024-01-09 в 18 57 50" src="https://github.com/scholokov/long-travel-2/assets/130754297/5fababb5-4d63-4849-8974-33c6b4b23c42">

**Документація:**
[Подорожі - список](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list)

**Додаткова інформація:**
Браузер: Google Chrome версія 120.0.6099.199
ОС: macOS версія 11.7.10

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
