### ISSUE TITLE
20071027_uman /  У блоці "Прев'ю подорожі" відсутні теги "Автомобіль", "Парк", "Цікаво"

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#4994]
**Кроки відтворення:**
1. Відкрити веб-сторінку подорожі Національний дендрологічний парк “Софіївка” 2007  
https://test.long-travel.live/20071027_uman/
3. Звернути увагу на лівий верхній кут блока "Прев'ю подорожі"

**Фактичний результат:**
1. Відсутні теги у блоці:
- Автомобіль
- Парк
- Цікаво

**Очікуваний результат:**
1. У блоці відображені такі теги:
- Автомобіль
- Парк
- Цікаво

**Прикріплені файли:**
<img width="1280" alt="Снимок экрана 2024-01-09 в 20 16 34" src="https://github.com/scholokov/long-travel-2/assets/130754297/4243d708-91a7-432c-b856-ccf729724774">

**Документація:**
[Подорожі - теги](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1)

**Додаткова інформація:**
Браузер: Google Chrome версія 120.0.6099.199
ОС: macOS версія 11.7.10

**Comment by Nanafox2010** [comment]
https://github.com/scholokov/long-travel-2/issues/4958

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
