### ISSUE TITLE
20071027_uman / В назві "Національний дендрологічний парк “Софіївка” не зазначено рік подорожі

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#4995]
**Кроки відтворення:**
1. Відкрити веб-сторінку подорожі Національний дендрологічний парк “Софіївка” 2007
 https://test.long-travel.live/20071027_uman/
2. Звернути увагу на назву блока "Прев'ю подорожі"
3. Звірити відповідність з назвою у [Вимогах](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list)

**Фактичний результат:**
1. Відображена назва "Національний дендрологічний парк “Софіївка”"

**Очікуваний результат:**
1. Відображена назва "Національний дендрологічний парк “Софіївка” 2007"

**Прикріплені файли:**
<img width="1280" alt="Снимок экрана 2024-01-09 в 21 33 02" src="https://github.com/scholokov/long-travel-2/assets/130754297/f10ae137-e2a8-40c7-bb8e-adcc723d3457">
<img width="853" alt="Снимок экрана 2024-01-09 в 21 50 00" src="https://github.com/scholokov/long-travel-2/assets/130754297/a738ca41-34a8-4834-be88-1f7846492d40">

**Документація:**
[Подорожі - список](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list)

**Додаткова інформація:**
Браузер: Google Chrome версія 120.0.6099.199
ОС: macOS версія 11.7.10

**Comment by Nanafox2010** [comment]
https://github.com/scholokov/long-travel-2/issues/4958

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
