### ISSUE TITLE
20071027_uman / В назві "Національний дендрологічний парк “Софіївка” вказано 43 символи

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#4996]
**Кроки відтворення:**
1. Відкрити веб-сторінку подорожі Національний дендрологічний парк “Софіївка” 2007
https://test.long-travel.live/20071027_uman/
2. Звернути увагу на назву блока "Прев'ю подорожі"
3. Підрахувати кількість символів у назві (https://charactercalculator.com/uk/)
4. Звірити із дозволеною максимальною кількістю символів у [Вимогах](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list) 

**Фактичний результат:**
1. У назві "Національний дендрологічний парк “Софіївка”" 43 символи

**Очікуваний результат:**
1. Назва подорожі менше 39 символів

**Прикріплені файли:**
<img width="1280" alt="Снимок экрана 2024-01-09 в 20 17 12" src="https://github.com/scholokov/long-travel-2/assets/130754297/830552cb-9164-48d3-90cc-99ebe0d1c020">
<img width="510" alt="Снимок экрана 2024-01-09 в 22 01 17" src="https://github.com/scholokov/long-travel-2/assets/130754297/d629891a-ca1e-43f1-b850-0477d1759f95">
<img width="1280" alt="Снимок экрана 2024-01-09 в 20 16 11" src="https://github.com/scholokov/long-travel-2/assets/130754297/25affa9c-13bd-40cd-9cb9-41aefd143e47">

**Документація:**
[Подорожі - список](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list)

**Додаткова інформація:**
Браузер: Google Chrome версія 120.0.6099.199
ОС: macOS версія 11.7.10

**Comment by Nanafox2010** [comment]
https://github.com/scholokov/long-travel-2/issues/4958

**Comment by scholokov** [comment]
не помилка відносно нових вимог

**Comment by Nanafox2010** [comment]
не є помилкою
