### ISSUE TITLE
20080427_feofania /  У блоці "Прев'ю подорожі" відсутні теги "Парк", "Цікаво"

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#4997]
**Кроки відтворення:**
1. Відкрити веб-сторінку подорожі Парк "Феофанія" https://test.long-travel.live/20080427_feofania/
2. Звернути увагу на лівий верхній кут блока "Прев'ю подорожі"

**Фактичний результат:**
1. Відсутні теги у блоці:
- Парк
- Цікаво

**Очікуваний результат:**
1. У блоці відображені такі теги:
- Парк
- Цікаво

**Прикріплені файли:**
<img width="1280" alt="Снимок экрана 2024-01-09 в 22 15 06" src="https://github.com/scholokov/long-travel-2/assets/130754297/e3130b96-0fca-4c53-9e65-c2efbca13fc3">

**Документація:**
[Подорожі - теги](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1)

**Додаткова інформація:**
Браузер: Google Chrome версія 120.0.6099.199
ОС: macOS версія 11.7.10

**Comment by Nanafox2010** [comment]
https://github.com/scholokov/long-travel-2/issues/4958

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
