### ISSUE TITLE
20080427_feofania / У блоці "Прев'ю подорожі" відображено назву "Київська область, Київ, парк “Феофанія”"

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#4998]
**Кроки відтворення:**
1. Відкрити веб-сторінку подорожі Парк "Феофанія" https://test.long-travel.live/20080427_feofania/
2. Звернути увагу на назву блока "Прев'ю подорожі"
3. Звірити відповідність з назвою у [Вимогах](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list)

**Фактичний результат:**
1. Зазначено назву "Київська область, Київ, парк “Феофанія”"

**Очікуваний результат:**
1. Зазначено назву "Парк “Феофанія”"

**Прикріплені файли:**
<img width="1280" alt="Снимок экрана 2024-01-09 в 22 15 32" src="https://github.com/scholokov/long-travel-2/assets/130754297/0114dd53-22d8-410a-b30a-e703e0ff3723">
<img width="778" alt="Снимок экрана 2024-01-09 в 22 27 42" src="https://github.com/scholokov/long-travel-2/assets/130754297/5981d38b-7420-4cd7-a1f1-d46d27736bac">

**Документація:**
[Подорожі - список](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list)

**Додаткова інформація:**
Браузер: Google Chrome версія 120.0.6099.199
ОС: macOS версія 11.7.10

**Comment by Nanafox2010** [comment]
https://github.com/scholokov/long-travel-2/issues/4958

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
