### ISSUE TITLE
Search/ The "Slovenia" country item of the filter by Categories is not displayed on the Travels page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#5003]
Steps to reproduce:

1. Open page https://test.long-travel.live/travels/
2. Pay attention to the "Slovenia" item of the filter by Categories on the Travels page

Actual Result: The "Slovenia" country item of the filter by Categories is not displayed on the Travels page

Expected Result: The "Slovenia" country item of the filter by Categories is displayed on the Travels page

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/671701c1-ebbd-432b-bcd7-0dd96411188d)

**Comment by ODrobik** [comment]
#4894

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
