### ISSUE TITLE
20180708_boguslav / In the "Post data" is the date of publication 01.09.2021

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5010]
**Steps to reproduce:**
1. Open the page "Чайки 2018" https://test.long-travel.live/20180708_boguslav/
2. Scroll down the page till "Post data"
5. Pay attention to the date of publication

**Actual result:**
1. The date of publication is 01.09.2021

**Expected result:**
1. The date of publication is 08.07.2018

**Attachments:**
<img width="1280" alt="Снимок экрана 2024-01-11 в 14 38 37" src="https://github.com/scholokov/long-travel-2/assets/130754297/581cf18f-5cce-4c55-a69a-b9f0f341c5be">

**Documentation:**
[Requirements](https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/data-publikaciyi) point 1.4.2

**Environment:**
Browser: Google Chrome 120.0.6099.199
OS: macOS 11.7.10

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
