### ISSUE TITLE
20180204_Zhitomyr/ Tags "Автомобиль", "Музей", "Цікаво" are missing in the Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5019]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20180204_Zhitomyr/
2. Pay attention to the absence of the tags in the Preview block.

**Actual result:**
Tags "Автомобиль", "Музей", "Цікаво" are missing in the Preview block.

**Expected result:**
Tags "Автомобиль", "Музей", "Цікаво" are present in the Preview block.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://github.com/scholokov/long-travel-2/assets/101987790/b00430a9-1d04-46d3-8bc8-acb150c58775)

**Comment by GNatala** [comment]
#5008

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
The issue is reproduced.

**Attachment:**


![Image](https://github.com/scholokov/long-travel-2/assets/101987790/3e550506-1336-4094-92db-3b57ae80ee97)

**Comment by GNatala** [comment]
passed
