### ISSUE TITLE
20180428_0501_Beregovo/ Tags "Замок", "Цікаво" are missing in the Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5020]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20180428_0501_Beregovo/
2. Pay attention to the absence of the tags "Замок", "Цікаво" in the Preview block.

**Actual result:**
Tags "Замок", "Цікаво" are missing in the Preview block.

**Expected result:**
Tags "Замок", "Цікаво" are present in the Preview block.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://github.com/scholokov/long-travel-2/assets/101987790/12143066-5444-4eda-aaba-d827c3c8fbde)

**Comment by GNatala** [comment]
#5008

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
The issue is reproduced.

**Environment:**


![Image](https://github.com/scholokov/long-travel-2/assets/101987790/9da78de1-4914-403b-9f54-1b99336c5204)

**Comment by GNatala** [comment]
passed
