### ISSUE TITLE
20180611_kiev_sea/ Tags "Річка-Озеро", "Цікаво" are missing in the Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5021]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20180611_kiev_sea/
2. Pay attention to the absence of the tags "Річка-Озеро", "Цікаво" in the Preview block.

**Actual result:**
Tags "Річка-Озеро", "Цікаво" are missing in the Preview block.

**Expected result:**
Tags "Річка-Озеро", "Цікаво" are present in the Preview block.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/a7acb81f-585d-4541-b27f-a75cd245c728)

**Comment by GNatala** [comment]
#5008

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
