### ISSUE TITLE
20180624_Bila_Tserkva/  In the Preview the name of Travel is "Дендропарк “Александрия”"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5023]
**Steps to reproduce:**

1. Open   https://test.long-travel.live/20180624_Bila_Tserkva
2. Pay attention to the name of Travel is "Дендропарк “Александрия”" the Preview.

**Actual result:**
 In the Preview the name of Travel is "Дендропарк “Александрия”".

**Expected result:**
 In the Preview, the name of Travel is "Дендропарк “Олександрія” 2018".

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**|
![image](https://github.com/scholokov/long-travel-2/assets/101987790/486e06b9-d4fe-4aa9-9300-a36f983cc0ee)

**Comment by GNatala** [comment]
#5008

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
The issue is reproduced.

**Attachment:|**

![Image](https://github.com/scholokov/long-travel-2/assets/101987790/2d25a6dc-255f-4cdf-a39f-13003713eb85)

**Comment by GNatala** [comment]
passed
