### ISSUE TITLE
20180624_Bila_Tserkva/ In the Preview of the Travel the Ukrainian flag is missing

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5024]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20180624_Bila_Tserkva/
2. Pay attention to the absence of the Ukranian flag in the Preview of the Travel.

**Actual result:**
In the Preview of the Travel the Ukrainian flag is missing.

**Expected result:**
In the Preview of the Travel the Ukrainian flag is present.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/prevyu-podorozhi

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/6cce42c8-79e0-4993-9124-44748016e598)

**Comment by GNatala** [comment]
#5008

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
The issue is reproduced.

**Attachment:**
![Image](https://github.com/scholokov/long-travel-2/assets/101987790/2afb20d7-dcfb-4d53-b96f-5b9141ea40a5)

**Comment by GNatala** [comment]
passed
