### ISSUE TITLE
20180624_Bila_Tserkva/ Tags "Автомобіль", "Парк", "Цікаво" are missing in the Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5025]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20180624_Bila_Tserkva
2. Pay attention to the absence of the tags "Автомобіль", "Парк", "Цікаво" in the Preview block.

**Actual result:**
Tags "Автомобіль", "Парк", "Цікаво" are missing in the Preview block.

**Expected result:**
Tags "Автомобіль", "Парк", "Цікаво" are present in the Preview block.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/ae22ea36-4ea3-4e2d-a1ec-72876ead5cce)

**Comment by GNatala** [comment]
#5008

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
The issue is reproduced.

**Attachment:**


![Image](https://github.com/scholokov/long-travel-2/assets/101987790/d9854078-570e-47eb-846c-320a64365054)

**Comment by GNatala** [comment]
passed
