### ISSUE TITLE
20180624_Bila_Tserkva/ In the Preview of the Travel the "Time period" is missing

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5027]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20180624_Bila_Tserkva/
2. Pay attention to the absence of "Time period" in the Preview of the Travel.

**Actual result:**
In the Preview of the Travel the "Time period" is missing.

**Expected result:**
In the Preview of the Travel the "Time period"  is present - **24.06.2018**

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/prevyu-podorozhi

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/040673fa-6977-4051-9433-a092946172b4)

**Comment by GNatala** [comment]
#5008

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
The issue is reproduced.

**Attachment:**

![Image](https://github.com/scholokov/long-travel-2/assets/101987790/5ac4511e-1926-47ff-ae0c-11031a305fec)
