### ISSUE TITLE
"Бучанський парк осінь 2018" travel can't be founded with the tags

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5029]
**Steps of reproducing**
1. Open https://test.long-travel.live/travels/
2. Enable search for "Автомобіль", "Парк", "Цікаво" tags
3. Scroll to the end of the travel list

**Actual Result**
"Бучанський парк осінь 2018" travel CAN'T be found with tags

**Expected Result**
"Бучанський парк осінь 2018" travel CAN be found with tags

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1 (number of travel is "55")
Travel ID is "20180909_bucha"

**Environments**
Windows 10, Chrome 120.0.6099.217 (64 bit)
![Travels – Long-Travel - Google Chrome 15 01 2024 14_50_50](https://github.com/scholokov/long-travel-2/assets/95171672/7949e82c-d04f-4734-973d-94224d41444d)
![Travels – Long-Travel - Google Chrome 15 01 2024 14_53_26](https://github.com/scholokov/long-travel-2/assets/95171672/8e42b3a3-6ae2-4fab-a53c-32740f8ddfd2)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
