### ISSUE TITLE
"Бучанський парк осінь 2018" travel can't be found with the travel name

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5031]
**Steps of reproducing**
1. Open https://test.long-travel.live/travels/
2. Search by travel name "Бучанський парк осінь 2018"
3. Scroll to the end of the travel list

**Actual Result**
"Бучанський парк осінь 2018" travel CAN'T be found with the travel name

**Expected Result**
"Бучанський парк осінь 2018" travel CAN be found with the travel name

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list (number of travel is "55")
Travel ID is "20180909_bucha"

**Environments**
Windows 10, Chrome 120.0.6099.217 (64 bit)
![New Issue · scholokov_long-travel-2 - Google Chrome 15 01 2024 16_18_18](https://github.com/scholokov/long-travel-2/assets/95171672/c273a8e3-fad2-4a68-b44e-3638846f860e)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
