### ISSUE TITLE
"Буки – Біла Церква" travel can't be founded with the "Парк", "Цікаво" tags

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5035]
**Steps of reproducing**
1. Open https://test.long-travel.live/travels/
2. Enable search for "Парк", "Цікаво" tags
3. Scroll to the end of the travel list

**Actual Result**
"Буки – Біла Церква" travel CAN'T be found with the "Парк", "Цікаво" tags

**Expected Result**
"Буки – Біла Церква" travel CAN be found with the "Парк", "Цікаво" tags

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1 (number of travel is "56")
Travel ID is "20180915_buki"

**Environments**
Windows 10, Chrome 120.0.6099.217 (64 bit)
![Lisboa – Aveiro – Porto – Nazare – Long-Travel - Google Chrome 19 02 2024 21_45_50](https://github.com/scholokov/long-travel-2/assets/95171672/aea87941-5b6f-4f3c-b930-8ead7cbc7a08)

**Comment by scholokov** [comment]
чоум пошук через довге тире, а не через коротке?

**Comment by DmitriiNasonov** [comment]
1. Search is carried out using tags
2. This name is indicated in the requirements

![Подорожі - список - QAX Travel - Google Chrome 22 01 2024 16_47_11](https://github.com/scholokov/long-travel-2/assets/95171672/196036fd-5c4c-4305-9063-d83b34313404)

**Comment by scholokov** [comment]
незрозумілий опис. тобто опис за назвою таки працює, але не працює за тегами? якщо так, то за якими саме?

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
