### ISSUE TITLE
20170605_Kiev_Mariinskiy/ The Photo of the Travel is not displayed in the Preview of the Travel

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#5041]
Steps to reproduce:

1. Open page https://test.long-travel.live/20170605_Kiev_Mariinskiy/
2. Pay attention to the Photo of the Travel in the Preview of the Travel

Actual Result: The Photo of the Travel is not displayed in the Preview of the Travel

Expected Result:The Photo of the Travel is displayed in the Preview of the Travel

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/prevyu-podorozhi

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/cfc35332-8e00-4d55-b16d-525b6d636650)

**Comment by ODrobik** [comment]
#4961

**Comment by scholokov** [comment]
виправлено

**Comment by ODrobik** [comment]
перевірено
