### ISSUE TITLE
20170605_Kiev_Mariinskiy/ The "Парк" tag is not displayed on the Preview of the Travel

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#5042]
Steps to reproduce:

1. Open page https://test.long-travel.live/20170605_Kiev_Mariinskiy/
2. Pay attention to the "Парк"  tag on the Preview of the Travel

Actual Result: The "Парк" tag is not displayed on the Preview of the Travel

Expected Result: The "Парк"  tag is displayed on the Preview of the Travel

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/05d4e4cd-e611-4564-aa5a-46b52cccefda)

**Comment by ODrobik** [comment]
#4961

**Comment by scholokov** [comment]
виправлено
