### ISSUE TITLE
20170521_Korosten/ The "Коростень – “Скеля” – Древлянський парк" Name of the Travel is displayed on the Preview  

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#5045]
Steps to reproduce:

1. Open page https://test.long-travel.live/20170521_Korosten/
2. Pay attention to the Name of the Travel on the Preview

Actual Result: The "Коростень – “Скеля” – Древлянський парк" Name of the Travel is displayed on the Preview 

Expected Result: The "Коростень - "Скеля" - парк Островського" Name of the Travel is displayed on the Preview 

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/2e8e55f5-9b4e-472e-a574-d042a8f5eff7)

**Comment by ODrobik** [comment]
#4961

**Comment by scholokov** [comment]
fixed

**Comment by scholokov** [comment]
почистив кеш. має бути ок

**Comment by ODrobik** [comment]
перевірено
