### ISSUE TITLE
20180708_Boguslav / The block "Travel Preview" has no tag icons "river-lake" and "interesting place"

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5048]
**Steps to reproduce:**
1. Open the page https://test.long-travel.live/20180708_boguslav/
2. Pay attention to the upper left corner of the block "Travel Preview"

**Actual result:**
1. The tag icon "river-lake" is missing
2. The tag icon "interesting place" is missing

**Expected result:**
1. The tag icon "river-lake" is present
2. The tag icon "interesting place" is present

**Attachments:**
![Снимок экрана 2024-01-23 в 23 38 29](https://github.com/scholokov/long-travel-2/assets/130754297/7e3774b9-4a92-45a2-a2f9-6c15c1c696c0)

**Documentation:**
[Requirements](https://qax.gitbook.io/qax-travel/requirements)
[Travels-tags](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1)

**Environment:**
Browser: Google Chrome 120.0.6099.234
OS: macOS 10.15.7

**Comment by Nanafox2010** [comment]
[#5009](https://github.com/scholokov/long-travel-2/issues/5009)

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
