### ISSUE TITLE
20180721_Cherkassy / The block "Travel Preview" has the wrong travel name "Черкассы"

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5049]
Steps to reproduce:
1. Open the page https://test.long-travel.live/20180721_cherkassy/
2. Pay attention to the travel name of the block "Travel Preview"

Actual result:
1. The travel name is "Черкассы"

Expected result:
1. The travel name is "Черкаси 2018"

Attachments:
![Снимок экрана 2024-01-24 в 00 05 32](https://github.com/scholokov/long-travel-2/assets/130754297/6c117d75-a472-433e-bb7f-e9ea773cccd5)

Documentation:
[Requirements](https://qax.gitbook.io/qax-travel/requirements)
[Travels-list](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list)

Environment:
Browser: Google Chrome 120.0.6099.234
OS: macOS 10.15.7

**Comment by Nanafox2010** [comment]
https://github.com/scholokov/long-travel-2/issues/5009

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
Verified
