### ISSUE TITLE
20190616_korostishevsky_kanyon/ Tags "Річка-Озеро", "Цікаво" are missing in the Preview block 

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5055]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20190616_korostishevsky_kanyon/
2. Pay attention to the absence of the tags "Річка-Озеро", "Цікаво" in the Preview block.

**Actual result:**
Tags "Річка-Озеро", "Цікаво" are missing in the Preview block.

**Expected result:**
Tags "Річка-Озеро", "Цікаво" are present in the Preview block.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/8935c0df-1bcc-4a50-9761-73238274d033)

**Comment by GNatala** [comment]
#5050

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
