### ISSUE TITLE
20190616_korostishevsky_kanyon/ In the Preview of the Travel the "Time period" is missing

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5056]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20190616_korostishevsky_kanyon/
2. Pay attention to the absence of "Time period" in the Preview of the Travel.

**Actual result:**
In the Preview of the Travel the "Time period" is missing.

**Expected result:**
In the Preview of the Travel the "Time period"  is present - **16.06.2019**

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/prevyu-podorozhi

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/4f35a161-63d5-489d-8c65-0a5b0b792ac9)

**Comment by GNatala** [comment]
#5050

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
