### ISSUE TITLE
20190616_korostishevsky_kanyon/ The publication date is 27.07.2021

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5057]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20190616_korostishevsky_kanyon/
2. Scroll down to the date of publication.
3. Pay attention to the date of publication.

**Actual result:**
 The publication date is 27.07.2021

**Expected result:**
 The publication date is 16.06.2019

**Environment:**
Windows 7 Home edition (x64),
Google Chrome v 108.0.5359.125 (x64)

**Requirements:** 
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/data-publikaciyi

**Attachments:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/1ef21914-1272-4df2-b7fb-c38b53b8b1d2)

**Comment by GNatala** [comment]
#5050

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
