### ISSUE TITLE
20190907_baydarky/ The tag "Річка-Озеро" is missing in the Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5064]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20190907_baydarky/
2. Pay attention to the absence of the tag "Річка-Озеро" in the Preview block.

**Actual result:**
The tag "Річка-Озеро" is missing in the Preview block.

**Expected result:**
The tag "Річка-Озеро" is present in the Preview block.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/1cad0cb2-5653-452f-8474-32946a2f9b50)

**Comment by GNatala** [comment]
#5050

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
