### ISSUE TITLE
"20200913_mariinskiy" travel - The travel name is "Маріїнський парк_Київ, Київська обл, Україна"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5068]
**Steps of reproducing**
1. Open https://test.long-travel.live/20200913_mariinskiy/

**Actual Result**
The travel name is "Маріїнський парк_Київ, Київська обл, Україна"

**Expected Result**
The travel name is "Маріїнський парк"

**Additional information**
Travel id is " 20200913_mariinskiy"
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list (number of travel is "75")

**Environments**
Windows 10, Chrome 121.0.6167.86 (64 bit)
![Маріїнський парк_Київ, Київська обл, Україна – Long-Travel - Google Chrome 30 01 2024 18_09_25](https://github.com/scholokov/long-travel-2/assets/95171672/2e933756-5bba-4b91-9569-0c80ee9b34fc)

**Comment by DmitriiNasonov** [comment]
#5053

**Comment by scholokov** [comment]
вказано невідповідний айді подорожі

**Comment by DmytroMarkulych** [comment]
@DmitriiNasonov можливо буде цей id? 20200913_mariinskiy

**Comment by DmitriiNasonov** [comment]
added

**Comment by DmytroMarkulych** [comment]
@DmitriiNasonov я мав це на увазі6 

![Image](https://github.com/scholokov/long-travel-2/assets/88647733/a0eb0670-5426-433b-ba52-a9bced637591)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
