### ISSUE TITLE
"Маріїнський парк_Київ, Київська обл, Україна" travel - Travel preview - The "Парк", "Цікаво" tags are missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5069]
**Steps of reproducing**
1. Open https://test.long-travel.live/20200913_mariinskiy/

**Actual Result**
The "Парк", "Цікаво" tags are missing

**Expected Result**
The "Парк", "Цікаво" tags are present

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1 (number of travel is "75")

**Environments**
Windows 10, Chrome 121.0.6167.86 (64 bit)
![Маріїнський парк_Київ, Київська обл, Україна – Long-Travel - Google Chrome 30 01 2024 18_12_20](https://github.com/scholokov/long-travel-2/assets/95171672/841e787e-2aa9-4ace-b373-9e79de3178dc)

**Comment by DmitriiNasonov** [comment]
#5053

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
