### ISSUE TITLE
wiki/The "Каньон" word is displayed on the page "Подорожі - теги" 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#5072]
**Steps to reproduce:**

1. Open page https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1
2. Scroll down to the "Перелік всіх тегів"  and "20170612_buki" points
3. Pay attention to the "Каньон" word in the "Перелік всіх тегів" and "20170612_buki" points on the page "Подорожі - теги" 

**Actual Result:** The "Каньон" word is displayed on the page "Подорожі - теги" 
**Expected Result:** The "Каньйон" word is displayed on the page "Подорожі - теги" 

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list

**Environment:**
Windows 10 Pro,
Opera v 96.0.4693.80

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/123776698/d46d8eac-4b23-41a3-814a-f4eb814bb973)

**Comment by ODrobik** [comment]
#4961

**Comment by scholokov** [comment]
не зрозуміло в чому помилка і на чому вона базується

**Comment by ODrobik** [comment]
виправлено

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
vеrified
