### ISSUE TITLE
Search/ The "Каньон" point is displayed in the "Filter by Природа" filter on the Travels page

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#5073]
Steps to reproduce:

1. Open page https://test.long-travel.live/travels/
2. Pay attention to the "Каньон" point in the "Filter by Природа" filter on the Travels page

Actual Result: The "Каньон" point is displayed in the "Filter by Природа" filter on the Travels page

Expected Result: The "Каньйон" point is displayed in the "Filter by Природа" filter on the Travels page

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/c756c775-d985-4335-a9d2-39b1a752ea28)

**Comment by ODrobik** [comment]
#4961

**Comment by scholokov** [comment]
please retest

**Comment by ODrobik** [comment]
Issue is existed
![image](https://github.com/scholokov/long-travel-2/assets/123776698/5b19c7cc-4a10-4822-9029-0f5d3e24f5a3)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
