### ISSUE TITLE
20170612_buki/ The "Річка-озеро", "Каньйон" and "Цікаво" tags are not displayed on the Preview of the Travel

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#5074]
**Steps to reproduce:**
1. Open page https://test.long-travel.live/20170612_buki/
2. Pay attention to the "Річка-озеро", "Каньйон" and "Цікаво" tags on the Preview of the Travel

**Actual Result:** The "Річка-озеро", "Каньйон" and "Цікаво" tags **are not displayed** on the Preview of the Travel

**Expected Result:** The "Річка-озеро", "Каньйон" and "Цікаво" tags **are displayed** on the Preview of the Travel

**Requirements:** https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

**Environment:**
Windows 10 Pro,
Opera v 96.0.4693.80

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/123776698/93d2fce6-6fb3-43bd-8245-f69d2a9be3dc)

**Comment by ODrobik** [comment]
#4961

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
