### ISSUE TITLE
20170625_Gusintsi/ The "Автомобіль", "Річка-озеро", "Iнше" and "Цікаво" tags are not displayed on the Preview of the Travel

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#5075]
**Steps to reproduce:**
1. Open page https://test.long-travel.live/20170625_Gusintsi/
2. Pay attention to the "Автомобіль", "Річка-озеро", "Iнше" and "Цікаво" tags on the Preview of the Travel

**Actual Result:** The "Автомобіль", "Річка-озеро", "Iнше" and "Цікаво"  tags are not displayed on the Preview of the Travel

**Expected Result:** The "Автомобіль", "Річка-озеро", "Iнше" and "Цікаво" tags are displayed on the Preview of the Travel

**Requirements:** https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

**Environment:**
Windows 10 Pro,
Opera v 96.0.4693.80

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/123776698/de3121f1-8b76-4144-a2c4-4af99338659c)

**Comment by ODrobik** [comment]
#4961

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
