### ISSUE TITLE
20201231_sofievskaya/ The"Софі́ївська площа,31.12.2020" name of the travel is displayed on the Preview 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#5080]
Steps to reproduce:
1. Open page https://test.long-travel.live/20201231_sofievskaya/
2. Pay attention to the "Софі́ївська площа,31.12.2020" name on the Preview of the Travel

Actual Result:  The"Софі́ївська площа,31.12.2020" name of the travel is displayed on the Preview 

Expected Result:  The"Софі́ївська площа - Новий Рік" name of the travel is displayed on the Preview 

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/8710d566-7c65-42f9-8a3e-2b0ad9869edb)

**Comment by ODrobik** [comment]
#5054

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
