### ISSUE TITLE
20210305_07_odessa/ The "Автомобіль", "Море" and "Цікаво" tag are not displayed on the Preview of the Travel

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#5082]
Steps to reproduce:
1. Open page https://test.long-travel.live/20210305_07_odessa/
2. Pay attention to the "Цікаво" tag on the Preview of the Travel

Actual Result: The "Автомобіль", "Море" and "Цікаво" tag are not displayed on the Preview of the Travel

Expected Result: The "Автомобіль", "Море" and "Цікаво" tag are displayed on the Preview of the Travel

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/dbbf8f24-7545-472d-9477-edf3fdc91f4b)

**Comment by ODrobik** [comment]
#5054

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
