### ISSUE TITLE
20210403_zahaltsi/ The "03.04.2021 Загальці_Київська область_Україна" name of the travel is displayed on the Preview 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#5083]
Steps to reproduce:
1. Open page https://test.long-travel.live/20210403_zahaltsi/
2. Pay attention to the "03.04.2021 Загальці_Київська область_Україна" name on the Preview of the Travel

Actual Result: The"03.04.2021 Загальці_Київська область_Україна" name of the travel is displayed on the Preview 
Expected Result: The"Загальці" name of the travel is displayed on the Preview 

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/2a9c92df-e675-40a8-bc89-4d4ba6c9ce14)

**Comment by ODrobik** [comment]
#5054

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
