### ISSUE TITLE
20210403_zahaltsi/ The "Автомобіль" tag is not displayed on the Preview of the Travel

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#5084]
Steps to reproduce:
1. Open page https://test.long-travel.live/20210403_zahaltsi/
2. Pay attention to the "Автомобіль" tag on the Preview of the Travel

Actual Result: The "Автомобіль" tag is not displayed on the Preview of the Travel

Expected Result: The "Автомобіль" tag is displayed on the Preview of the Travel

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/6c888623-493d-4524-9846-93c8bc580f66)

**Comment by ODrobik** [comment]
#5054

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
