### ISSUE TITLE
20180721_Cherkassy /  The block "Travel Preview" has no tag icons, "car" and "interesting place"

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5087]
**Steps to reproduce:**

1. Open the page https://test.long-travel.live/20180721_cherkassy/
2. Pay attention to the upper left corner of the block "Travel Preview"

**Actual result:**

1. The tag icon "car" is missing
2. The tag icon "interesting place" is missing

**Expected result:**

1. The tag icon "car" is present
2. The tag icon "interesting place" is present

**Attachments:**

![Снимок экрана 2024-02-07 в 13 35 36](https://github.com/scholokov/long-travel-2/assets/130754297/1c23af85-279a-4f1f-8b40-f8b344c34cee)

**Documentation:**

[Requirements](https://qax.gitbook.io/qax-travel/requirements)
[Travels-tags](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1)

**Environment:**

Browser: Google Chrome 121.0.6167.139 
OS: macOS 10.15.7

**Comment by Nanafox2010** [comment]
[#5009](https://github.com/scholokov/long-travel-2/issues/5009)

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
