### ISSUE TITLE
20201010_11_brech - Travel preview - Tag "Цікаво" is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5088]
**Steps of reproducing**
1. Open https://test.long-travel.live/20201010_11_brech/
2. Pay attention to the travel preview

**Actual Result**
Tag "Цікаво" is missing

**Expected Result**
Tag "Цікаво" is present

**Additional information**
Travel id is "20201010_11_brech"
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1 (travel number is 77)

**Environments**
Windows 10, Chrome 121.0.6167.161 (64 bit)
![Подорожі - список - QAX Travel - Google Chrome 07 02 2024 16_06_02](https://github.com/scholokov/long-travel-2/assets/95171672/c784f9b2-5d4e-41ff-90e2-6341ea1ddc9b)

**Comment by DmitriiNasonov** [comment]
#5053

**Comment by DmytroMarkulych** [comment]
додайте id подорожі

**Comment by DmitriiNasonov** [comment]
added

**Comment by DmytroMarkulych** [comment]
сюди id подорожі

![Image](https://github.com/scholokov/long-travel-2/assets/88647733/a47a199b-00e1-4903-80de-2453daa9cef2)

**Comment by DmitriiNasonov** [comment]
added

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
