### ISSUE TITLE
20190720_0811_balcans/  Preview block date format is DD.MM-DD.MM.YYYY

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5089]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20190720_0811_balcans/
2. Pay attention to the date format in the Preview block.

**Actual result:**
The date format is **DD.MM-DD.MM.YYYY (20.07-08.11.2019)** 

**Expected result:**
The date format is **DD.MM.YYYY-DD.MM.YYYY (20.07.2019-08.11.2019)**

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/prevyu-podorozhi

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/e3f12e60-d241-46f6-9fa1-5affee471fef)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
