### ISSUE TITLE
20201024_uman - Travel preview - Travel name is "Національний дендрологічний парк “Софіївка”"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5091]
**Steps of reproducing**
1. Open https://test.long-travel.live/20201024_uman/
2. Pay attention to the travel preview

**Actual Result**
Travel name is "Національний дендрологічний парк “Софіївка”"

**Expected Result**
Travel name is "Національний дендрологічний парк “Софіївка” 2020"

**Additional information**
Travel id is "20201024_uman"
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list (travel number is 78)

**Environments**
Windows 10, Chrome 121.0.6167.161 (64 bit)
![Національний дендрологічний парк “Софіївка” – Long-Travel - Google Chrome 07 02 2024 16_48_51](https://github.com/scholokov/long-travel-2/assets/95171672/94310410-ae28-4996-98f8-6b5a73baa39c)

**Comment by DmitriiNasonov** [comment]
#5053

**Comment by DmytroMarkulych** [comment]
додайте id подорожі

**Comment by DmitriiNasonov** [comment]
added

**Comment by DmytroMarkulych** [comment]
додайте id подорожі в summary

**Comment by DmitriiNasonov** [comment]
added

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
