### ISSUE TITLE
20180804_piryatin_mirgorod / In the "Travel Preview" the tag icon "interesting place" is missing

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5097]
Steps to reproduce:

1. Open the page https://test.long-travel.live/20180804_piryatin_mirgorod/
2. Pay attention to the upper left corner of the block "Travel Preview"

Actual result:

1. The tag icon "interesting place" is missing

Expected result:

1. The tag icon "interesting place" is present

Attachments:
<img width="1280" alt="Снимок экрана 2024-02-08 в 13 00 50" src="https://github.com/scholokov/long-travel-2/assets/130754297/b6763583-af56-47b0-9528-cf96c201560c">

Documentation:
[Requirements](https://qax.gitbook.io/qax-travel/requirements)
[Travels-tags](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1)

Environment:
Browser: Google Chrome 120.0.6099.234
OS: macOS 10.15.7

**Comment by Nanafox2010** [comment]
[#5009](https://github.com/scholokov/long-travel-2/issues/5009)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/long-travel-2/assets/88647733/ccd7c3d6-5948-4503-8a34-97668da13c39)

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
