### ISSUE TITLE
20210625_28_cherkassy/ Tags "Автомобіль", "Парк", "Інше", "Цікаво" are missing in the Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5098]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20210625_28_cherkassy/
2. Pay attention to the absence of the tags "Автомобіль", "Парк", "Інше", "Цікаво" in the Preview block.

**Actual result:**
Tags "Автомобіль", "Парк", "Інше", "Цікаво" are missing in the Preview block.

**Expected result:**
Tags "Автомобіль", "Парк", "Інше", "Цікаво" are present in the Preview block.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/d4fa8d08-b79f-4ec4-804d-088a53f871dc)

**Comment by GNatala** [comment]
#5093

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
