### ISSUE TITLE
20210625_28_cherkassy/ In the Preview block the "Time period" is missing

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5099]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20210625_28_cherkassy/
2. Pay attention to the absence of the "Time period" in the Preview block.

**Actual result:**
In the Preview block the "Time period" is missing.

**Expected result:**
In the Preview block the "Time period"  is 25.06.2021-28.06.2021.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/prevyu-podorozhi

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/7b54815c-4d3d-4505-87b1-e1a577ec4944)

**Comment by GNatala** [comment]
#5093

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
