### ISSUE TITLE
20210811_tsum_music/ In the Preview block the "Time period" is missing

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5101]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20210811_tsum_music/
2. Pay attention to the absence of the "Time period" in the Preview block.

**Actual result:**
In the Preview block of the Travel the "Time period" is missing.

**Expected result:**
In the Preview block of the Travel the "Time period"  is 11.08.2021.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/prevyu-podorozhi

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/8816a23c-f623-49d9-9428-cedf182f00b0)

**Comment by GNatala** [comment]
#5093

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
