### ISSUE TITLE
20210814_24_sergeevka_odessa/ Tags "Автомобиль", "Море", "Пляж", "Зоопарк", "Цікаво" are missing in the Preview block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5102]
**Steps to reproduce:**

1. Open   https://test.long-travel.live/20210814_24_sergeevka_odessa/
2. Pay attention to the absence of the tags in the Preview block.

**Actual result:**
TTags "Автомобиль", "Море", "Пляж", "Зоопарк", "Цікаво" are missing in the Preview block.

**Expected result:**
Tags "Автомобиль", "Море", "Пляж", "Зоопарк", "Цікаво" are present in the Preview block.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/e34ae5c0-9d43-41d4-b78b-23fcd1149e2a)

**Comment by GNatala** [comment]
#5093

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
