### ISSUE TITLE
20210814_24_sergeevka_odessa/ Preview block date format is DD-DD.MM.YYYY

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5104]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20210814_24_sergeevka_odessa/
2. Pay attention to the date format in the Preview block.

**Actual result:**
The date format is **DD-DD.MM.YYYY (14-24.08.2021)** 

**Expected result:**
The date format is **DD.MM.YYYY-DD.MM.YYYY (14.08.2021-24.08.2021).

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/prevyu-podorozhi

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/01097756-e19c-432a-9397-bac8ef749608)

**Comment by GNatala** [comment]
#5093

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
