### ISSUE TITLE
20180819_Bucha / "Travel Preview" has an unknown icon in the upper right corner

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5107]
Steps to reproduce:
1. Open the page https://test.long-travel.live/20180819_bucha/
2. Pay attention to the icon in the upper right corner of the block "Travel Preview"

Actual result:
1. The unknown icon in the upper right corner

Expected result:
1. The flag of "Ukraine" is placed in the upper right corner

Attachments:
<img width="1280" alt="Снимок экрана 2024-02-08 в 16 50 12" src="https://github.com/scholokov/long-travel-2/assets/130754297/a0a1e18a-0846-4414-98d3-780ef8c0ed47">

Documentation:
[Requirements](https://qax.gitbook.io/qax-travel/requirements)
[Подорожі - список](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list)

Environment:
Browser: Google Chrome 121.0.6167.160 
OS: macOS 11.7.10

**Comment by Nanafox2010** [comment]
[#5009](https://github.com/scholokov/long-travel-2/issues/5009)

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
