### ISSUE TITLE
20180819_Bucha / The block "Travel Preview" has no tag icons "car" "park" and "interesting place"

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5108]
Steps to reproduce:
1. Open the page https://test.long-travel.live/20180819_bucha/
2. Pay attention to the upper left corner of the block "Travel Preview"

Actual result:
1. There are no tag icons

Expected result:
1. The tag icons "car" "park" and "interesting place" are present

Attachments:
<img width="1280" alt="Снимок экрана 2024-02-08 в 19 46 28" src="https://github.com/scholokov/long-travel-2/assets/130754297/452bc164-ebec-465c-9122-6cc72c208107">

Documentation:
[Requirements](https://qax.gitbook.io/qax-travel/requirements)
[Travels-tags](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1)

Environment:
Browser: Google Chrome 121.0.6167.160 
OS: macOS 111.7.10

**Comment by Nanafox2010** [comment]
#5009

**Comment by Nanafox2010** [comment]
the tag "interesting place" is missing
<img width="1280" alt="Снимок экрана 2024-02-09 в 18 15 11" src="https://github.com/scholokov/long-travel-2/assets/130754297/29e9110b-6753-4a3a-b6ed-5fb18f80cf4f">
<img width="855" alt="Снимок экрана 2024-02-09 в 18 17 14" src="https://github.com/scholokov/long-travel-2/assets/130754297/3467cc3a-1317-4c84-8ca2-2b7e55e3df5b">

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
