### ISSUE TITLE
20180819_Bucha / In the "Post data" is the date of publication 11.08.2021

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5110]
Steps to reproduce:
1. Open the page https://test.long-travel.live/20180819_bucha/
2. Scroll down the page to "Post data"
3. Pay attention to the date of publication

Actual result:
1. The date of publication is 11.08.2021

Expected result:
1. The date of publication is 19.08.2018

Attachments:
<img width="1280" alt="Снимок экрана 2024-02-08 в 20 02 52" src="https://github.com/scholokov/long-travel-2/assets/130754297/85f39ee6-9891-478c-9024-96e35c72a6a8">

Documentation:
[Requirements](https://qax.gitbook.io/qax-travel/requirements)
[Подорожі - список](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list)

Environment:
Browser: Google Chrome 121.0.6167.160
OS: macOS 11.7.10

**Comment by Nanafox2010** [comment]
#5009

**Comment by scholokov** [comment]
fixed
