### ISSUE TITLE
20170628_Trahtemorov/ unnecessary tag "Катер", "Літак", "Паром", "Підводний човен", "Потяг", "Лінивець", "Водоспад", "Гори", "Море", "Океан", "Військовий об'єкт", "Замок", "Зоопарк", "Музей", "Довга дорога" in the trip "Трахтемирів"

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5111]
Pre-conditions:
Open: https://test.long-travel.live/travels/

Steps to reproduce:

Note that unnecessary tag "Катер", "Літак", "Паром", "Підводний човен", "Потяг", "Лінивець", "Водоспад", "Гори", "Море",, "Окен", "Військовий об'єкт", "Замок", "Зоопарк", "Музей", "Довга дорога" in the trip "Трахтемирів"
Actual result:
unnecessary tag "Катер", "Літак", "Паром", "Підводний човен", "Потяг", "Лінивець", "Водоспад", "Гори", "Море",, "Окен", "Військовий об'єкт", "Замок", "Зоопарк", "Музей", "Довга дорога" in the trip "Трахтемирів"
Expected result:
according to the search requirements, the "Автомобіль", "Річка-Озеро", "Цікаво" tag must be in the trip "Трахтемирів"

Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1 - 040

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/25c080af-5147-42a9-9a59-3cad51891b4a)
green - should be
red - should not be
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/2dfea7fd-59a2-4e5d-9466-77693754bed9)

**Comment by Illia2810** [comment]
#5111

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
Створено новий схожий баг #5136

**Comment by Illia2810** [comment]
Створено новий схожий баг #5136
