### ISSUE TITLE
20180826_Kiylov /  The block "Travel Preview" has no tag icons, "car" "river-lake" and "interesting place"

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5112]
Steps to reproduce:
1. Open the page https://test.long-travel.live/20180826_kiylov/
2. Pay attention to the upper left corner of the block "Travel Preview"

Actual result:
1. The tag icon "car" is missing
2. The tag icon "river-lake" is missing
3. The tag icon "interesting place" is missing

Expected result:
1. The tag icon "car" is present
2. The tag icon "river-lake" is present
3. The tag icon "interesting place" is present

Attachments:
<img width="1280" alt="Снимок экрана 2024-02-08 в 22 28 44" src="https://github.com/scholokov/long-travel-2/assets/130754297/89255d20-d1dc-4065-955b-ba9f23b7138e">

Documentation:
[Requirements](https://qax.gitbook.io/qax-travel/requirements)
[Travels-tags](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1)

Environment:
Browser: Google Chrome 121.0.6167.160
OS: macOS 11.7.10

**Comment by Nanafox2010** [comment]
#5009

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
