### ISSUE TITLE
20180826_Kiylov / The block "Travel Preview" has name of travel "Кийлов"

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5113]
Steps to reproduce:
1. Open the page https://test.long-travel.live/20180826_kiylov/
2. Pay attention to the travel name of the block "Travel Preview"

Actual result:
1. The travel name is "Кийлов"

Expected result:
1. The travel name is "Кийлів"

Attachments:
<img width="1280" alt="Снимок экрана 2024-02-08 в 22 41 47" src="https://github.com/scholokov/long-travel-2/assets/130754297/8041e53c-c6e8-4b9a-9b2a-3d43cd613762">

Documentation:
[Requirements](https://qax.gitbook.io/qax-travel/requirements)
[Travels-list](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list)

Environment:
Browser: Google Chrome 121.0.6167.160
OS: macOS 11.7.10

**Comment by Nanafox2010** [comment]
#5009

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
