### ISSUE TITLE
20200627_29_yuzhniy / The block "Travel Preview" has no tag icons "beach" and "interesting place" 

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5114]
Steps to reproduce:

1. Open the page https://test.long-travel.live/20200627_29_yuzhniy/
2. Pay attention to the upper left corner of the block "Travel Preview"

Actual result:

1. There are no tag icons

Expected result:

1. The tag icons "beach" and "interesting place" must be present

Attachments:
<img width="1280" alt="Снимок экрана 2024-02-09 в 18 46 28" src="https://github.com/scholokov/long-travel-2/assets/130754297/881abbc1-81d3-4442-80ae-dcc7bb5d47e1">
<img width="849" alt="Снимок экрана 2024-02-09 в 18 55 47" src="https://github.com/scholokov/long-travel-2/assets/130754297/d679fffe-b325-4a04-8848-50d0b406ed6e">

Documentation:
[Requirements](https://qax.gitbook.io/qax-travel/requirements)
[Travels-tags](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1)

Environment:
Browser: Google Chrome 121.0.6167.160
OS: macOS 111.7.10

**Comment by Nanafox2010** [comment]
[#5052](https://github.com/scholokov/long-travel-2/issues/5052)

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
