### ISSUE TITLE
20200627_29_yuzhniy /  The block "Travel Preview" has the travel name "Южне"

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5115]
Steps to reproduce:
1. Open the page https://test.long-travel.live/20200627_29_yuzhniy/
2. Pay attention to the travel name 

Actual result:
1. The travel name "Южне"

Expected result:
1. The travel name must be "Южне - Вінниця"

Attachments:
<img width="1278" alt="Снимок экрана 2024-02-09 в 19 20 29" src="https://github.com/scholokov/long-travel-2/assets/130754297/9f544c82-c3e5-416c-b415-f9009bbd8166">

Documentation:
[Requirements](https://qax.gitbook.io/qax-travel/requirements)
[Travels list](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list)

Environment:
Browser: Google Chrome 121.0.6167.160
OS: macOS 111.7.10

**Comment by Nanafox2010** [comment]
https://github.com/scholokov/long-travel-2/issues/5052

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
