### ISSUE TITLE
20200719_Belya_tsercov /  The block "Travel Preview" has no tag icons "car" "park" and "interesting place"

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5116]
Steps to reproduce:
1. Open the page https://test.long-travel.live/20200719_belya_tsercov/
2. Pay attention to the upper left corner of the block "Travel Preview"

Actual result:
1. There are no tag icons

Expected result:
1. The tag icons "car" "park" and "interesting place" must be present

Attachments:
<img width="1280" alt="Снимок экрана 2024-02-09 в 19 28 57" src="https://github.com/scholokov/long-travel-2/assets/130754297/5e722402-51cc-40bb-aa04-377612aa22e9">
![Image](https://github.com/scholokov/long-travel-2/assets/130754297/5ad64394-2c39-4adc-93a1-b41bfbde5772)

Documentation:
[Requirements](https://qax.gitbook.io/qax-travel/requirements)
[Travels-tags](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1)

Environment:
Browser: Google Chrome 121.0.6167.160
OS: macOS 111.7.10

**Comment by Nanafox2010** [comment]
#5052

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
