### ISSUE TITLE
20200719_Belya_tsercov / The block "Travel Preview" has the travel name "Біла Церква – Дендропарк “Александрія”

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5117]
Steps to reproduce:
1. Open the page https://test.long-travel.live/20200719_belya_tsercov/
2. Pay attention to the travel name

Actual result:
1. The travel name "Біла Церква – Дендропарк “Александрія"

Expected result:
1. The travel name must be "Дендропарк “Олександрія” 2020"

Attachments:
<img width="1280" alt="Снимок экрана 2024-02-09 в 19 43 49" src="https://github.com/scholokov/long-travel-2/assets/130754297/2760bb72-d0d5-4b48-b386-03031e9baf9a">

Documentation:
[Requirements](https://qax.gitbook.io/qax-travel/requirements)
[Travels list](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list)

Environment:
Browser: Google Chrome 121.0.6167.160
OS: macOS 111.7.10

**Comment by Nanafox2010** [comment]
#5052

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
