### ISSUE TITLE
20211029_0911_portugal - Travel preview - The "Водоспад", "Парк", "Пляж", "Горна дорога", "Зоопарк", "Цікаво" tags are missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5119]
**Steps of reproducing**
1. Open https://test.long-travel.live/20211029_0911_portugal/

**Actual Result**
The "Водоспад", "Парк", "Пляж", "Горна дорога", "Зоопарк", "Цікаво" tags are missing

**Expected Result**
The "Водоспад", "Парк", "Пляж", "Горна дорога", "Зоопарк", "Цікаво" tags are present

**Additional information**
Travel id is "20211029_0911_portugal"
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1 (Travel number is 94)

**Environments**
Windows 10, Chrome 121.0.6167.161 (64 bit)
![Lisboa – Aveiro – Porto – Nazare – Long-Travel - Google Chrome 13 02 2024 17_34_39](https://github.com/scholokov/long-travel-2/assets/95171672/4764750e-022a-440a-904b-ec58a9deb782)

**Comment by DmitriiNasonov** [comment]
#5095

**Comment by DmytroMarkulych** [comment]
Додайте id подорожі в summary

**Comment by DmitriiNasonov** [comment]
added

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is fixed partly. created new bug-reprot

**Comment by DmitriiNasonov** [comment]
#5138
