### ISSUE TITLE
20211029_0911_portugal - Travel preview - The "Військовий об'єкт" tag is present

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5120]
**Steps of reproducing**
1. Open https://test.long-travel.live/20211029_0911_portugal/

**Actual Result**
The "Військовий об'єкт" tag is present

**Expected Result**
The "Військовий об'єкт" tag is missing

**Additional information**
Travel id is "20211029_0911_portugal"
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1 (Travel number is 94)

**Environments**
Windows 10, Chrome 121.0.6167.161 (64 bit)

![Image](https://github.com/scholokov/long-travel-2/assets/95171672/35e04262-ea90-4ee4-88fe-eedb60dd2bd0)

**Comment by DmitriiNasonov** [comment]
#5095

**Comment by DmytroMarkulych** [comment]
Додайте id подорожі в summary

**Comment by DmitriiNasonov** [comment]
added

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduced
![Lisboa – Aveiro – Porto – Nazare – Long-Travel - Google Chrome 19 02 2024 21_34_36](https://github.com/scholokov/long-travel-2/assets/95171672/6f72a234-e646-4003-afcd-4e2eab7bad25)

**Comment by DmitriiNasonov** [comment]
bug report was closed accidentally

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
