### ISSUE TITLE
20210611_13_vinnitsa/ The "Автомобіль", "Річка-Озеро", "Парк" and "Цікаво" tags are not displayed on the Preview of the Travel

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#5121]
Steps to reproduce:

1. Open page https://test.long-travel.live/20210611_13_vinnitsa/
2. Pay attention to the "Автомобіль", "Річка-Озеро", "Парк" and "Цікаво" tags on the Preview of the Travel

Actual Result: The "Автомобіль", "Річка-Озеро", "Парк" and "Цікаво" tags are not displayed on the Preview of the Travel

Expected Result: The "Автомобіль", "Річка-Озеро", "Парк" and "Цікаво" tags are displayed on the Preview of the Travel

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/cf729c26-13ad-4adc-b6df-e03e37898274)

**Comment by ODrobik** [comment]
#5092

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
varified
