### ISSUE TITLE
20210510_staryi_solotvyn/ The "Річка-Озеро", "Інше" and "Цікаво" tags are not displayed on the Preview of the Travel 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#5122]
Steps to reproduce:

1. Open page https://test.long-travel.live/20210510_staryi_solotvyn/
2. Pay attention to the "Річка-Озеро", "Інше" and "Цікаво" tags on the Preview of the Travel

Actual Result: The "Річка-Озеро", "Інше" and "Цікаво" tags are not displayed on the Preview of the Travel

Expected Result: The "Річка-Озеро", "Інше" and "Цікаво" tags are displayed on the Preview of the Travel

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/8cb5d4c5-cab9-43bf-98d8-67d6251078d5)

**Comment by ODrobik** [comment]
#5092

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
