### ISSUE TITLE
"20220124_28_netherlands" travel - Travel preview - The "Військовий об'єкт" tag is present

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5123]
**Steps of reproducing**
1. Open https://test.long-travel.live/20220124_0128_netherlands/

**Actual Result**
The "Військовий об'єкт" tag is present

**Expected Result**
The "Військовий об'єкт" tag is missing

**Additional information**
Travel id is "20220124_28_netherlands"
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1 (Travel number is 95)

**Environments**
Windows 10, Chrome 121.0.6167.161 (64 bit)
![Eindhoven – Den Haag – Amsterdam – Long-Travel - Google Chrome 14 02 2024 14_30_53](https://github.com/scholokov/long-travel-2/assets/95171672/e0a2e9ed-56ae-4fad-b71e-a73e1d9b2cb3)

**Comment by DmitriiNasonov** [comment]
#5095

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
