### ISSUE TITLE
"20220124_28_netherlands" travel - Travel preview - The "Пляж", "Море", "Long-travel", "Цікаво" tags are missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5124]
**Steps of reproducing**
1. Open https://test.long-travel.live/20220124_0128_netherlands/

**Actual Result**
The "Пляж", "Море", "Long-travel", "Цікаво" tags are missing

**Expected Result**
The "Пляж", "Море", "Long-travel", "Цікаво" tags are present

**Additional information**
Travel id is "20220124_28_netherlands"
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list-1 (Travel number is 94)

**Environments**
Windows 10, Chrome 121.0.6167.161 (64 bit)
![Eindhoven – Den Haag – Amsterdam – Long-Travel - Google Chrome 14 02 2024 14_35_22](https://github.com/scholokov/long-travel-2/assets/95171672/1e1ae0f1-e9d5-40ad-a6a5-d943668bc4c9)

**Comment by DmitriiNasonov** [comment]
#5095

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
