### ISSUE TITLE
20200820_23-karpati / The block "Travel Preview" has name of travel "Карпати"

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5125]
Steps to reproduce:
1. Open the page https://test.long-travel.live/20200820_23-karpati/
2. Pay attention to the travel name of the block "Travel Preview"

Actual result:
1. The travel name is "Карпати"

Expected result:
1. The travel name is "Яремче"

Attachments:
<img width="860" alt="Снимок экрана 2024-02-14 в 15 40 23" src="https://github.com/scholokov/long-travel-2/assets/130754297/0f4561e9-ee2f-4809-8a9c-e0e901544277">
<img width="1280" alt="Снимок экрана 2024-02-14 в 15 41 18" src="https://github.com/scholokov/long-travel-2/assets/130754297/338d0b34-79de-492d-9916-5b98de54453d">

Documentation:
[Requirements](https://qax.gitbook.io/qax-travel/requirements)
[Travels-list](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list)

Environment:
Browser: Google Chrome 121.0.6167.160
OS: macOS 11.7.10

**Comment by Nanafox2010** [comment]
[#5052](https://github.com/scholokov/long-travel-2/issues/5052)

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
