### ISSUE TITLE
20200725_26_piviha / The block "Travel Preview" has name of travel "Гора Пивиха,Полтавська область,Україна"

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5126]
Steps to reproduce:
1. Open the page https://test.long-travel.live/20200725_26_piviha/
2. Pay attention to the travel name of the block "Travel Preview"

Actual result:
1. The travel name is "Гора Пивиха,Полтавська область,Україна"

Expected result:
1. The travel name is "Гора Пивиха"

Attachments:
<img width="844" alt="Снимок экрана 2024-02-14 в 15 51 05" src="https://github.com/scholokov/long-travel-2/assets/130754297/dfe623ef-3c19-4760-80c0-8b82c3c14630">
<img width="1280" alt="Снимок экрана 2024-02-14 в 15 52 59" src="https://github.com/scholokov/long-travel-2/assets/130754297/40c4dcad-4e4a-4869-b2e9-2d7c6f5c2d7e">

Documentation:
[Requirements](https://qax.gitbook.io/qax-travel/requirements)
[Travels-list](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list)

Environment:
Browser: Google Chrome 121.0.6167.160
OS: macOS 11.7.10

**Comment by Nanafox2010** [comment]
#5052

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
