### ISSUE TITLE
20200725_26_piviha /  The "Travel Preview" has an unknown icon in the upper right corner

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5132]
Steps to reproduce:
1. Open the page https://test.long-travel.live/20200725_26_piviha/
2. Pay attention to the icon in the upper right corner of the block "Travel Preview"

Actual result:
1. In the upper right corner is the flag of "Ukraine" and an unknown icon

Expected result:
1. Only the flag of "Ukraine" is placed in the upper right corner

Attachments:
![Снимок экрана 2024-02-16 в 10 19 31](https://github.com/scholokov/long-travel-2/assets/130754297/38f5b96e-a909-4b20-857d-a4abf5617abe)

Documentation:
[Requirements](https://qax.gitbook.io/qax-travel/requirements)
[Подорожі - список](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list)

Environment:
Browser: Google Chrome 121.0.6167.184
OS: macOS 11.7.10

**Comment by Nanafox2010** [comment]
https://github.com/scholokov/long-travel-2/issues/5052

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
