### ISSUE TITLE
20180826_Kiylov / In the Search Result block, the Travel has no Preview image

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5133]
Steps to reproduce:
1. Open the page "Подорожі" https://test.long-travel.live/travels/
2. Insert to the block the Travel name "Кийлів" and search
3. Pay attention to the Travel Preview image In the Search Result block

Actual result:
1. The Travel has no Preview image

Expected result:
1. The Travel must have the Preview image

Attachments:
![Снимок экрана 2024-02-16 в 12 29 15](https://github.com/scholokov/long-travel-2/assets/130754297/a3c68299-cf45-4ba3-8518-703bbc1fe85e)

Documentation:
[Requirements](https://qax.gitbook.io/qax-travel/requirements)

Environment:
Browser: Google Chrome 121.0.6167.184
OS: macOS 11.7.10

**Comment by Nanafox2010** [comment]
https://github.com/scholokov/long-travel-2/issues/5009

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
