### ISSUE TITLE
20200820_23-karpati / The "Travel Preview" has an unknown icon in the upper right corner 

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5135]
Steps to reproduce:
1. Open the page https://test.long-travel.live/20200820_23-karpati/
2. Pay attention to the icon in the upper right corner of the block "Travel Preview"

Actual result:
1.  The "Travel Preview" has an unknown icon

Expected result:
1.  The "Travel Preview" must have the flag of "Ukraine" in the upper right corner

Attachments:
![Снимок экрана 2024-02-16 в 15 05 24](https://github.com/scholokov/long-travel-2/assets/130754297/7d10c863-addf-4d2c-92e6-1887e61093e0)

Documentation:
[Requirements](https://qax.gitbook.io/qax-travel/requirements)
[Подорожі - список](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list)

Environment:
Browser: Google Chrome 121.0.6167.184
OS: macOS 11.7.10

**Comment by Nanafox2010** [comment]
https://github.com/scholokov/long-travel-2/issues/5052

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
The bug is displayed.
There should be the flag of "Ukraine" instead of the icon.
<img width="1280" alt="Снимок экрана 2024-02-23 в 15 35 37" src="https://github.com/scholokov/long-travel-2/assets/130754297/0c585be0-3c38-47bb-b615-d4dd6953160d">

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
