### ISSUE TITLE
20091026_1102_toronto - Travel preview - Flag icon size is 36 by 24 pixels

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5152]
**Steps of reproducing**
1. Open https://test.long-travel.live/20091026_1102_toronto/
2. Check flag icon size

**Actual Result**
Flag icon size is 26 by 18 pixels

**Expected Result**
Flag icon size is 36 by 24 pixels

**Additional information**
DevTools screen size is 1920 by 1080 pixels
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=3531-195&mode=design&t=r0IXW8P3lu2yE0Jf-0

**Environments**
Windows 10, Chrome 122.0.6261.95 (64 bit)
![Toronto – Long-Travel - Google Chrome 28 02 2024 13_50_16](https://github.com/scholokov/long-travel-2/assets/95171672/ba6f1029-bba8-4f55-b71d-c3fd041e75fd)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is reproduced
![Toronto – Long-Travel - Google Chrome 06 03 2024 14_11_33](https://github.com/scholokov/long-travel-2/assets/95171672/a10cd942-ac56-41aa-bea0-1cb96ec83de7)
![Toronto – Long-Travel - Google Chrome 06 03 2024 14_11_37](https://github.com/scholokov/long-travel-2/assets/95171672/3ed79f08-3dbf-47f7-ae58-aec04e9f0993)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
