### ISSUE TITLE
20151226_kiev_fashion_park/ all flags on standard blocks are not sized according to the design

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5155]
Pre-conditions:
Open: https://test.long-travel.live/travels/
Open: https://test.long-travel.live/20151226_kiev_fashion_park/

Steps to reproduce:

Note that all flags on standard blocks are not sized according to the design

Actual result:
all flags on standard blocks are not sized according to the design 28х18
Expected result:
the size of the flags should match the design 36х24
​
Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-2459&mode=design&t=SufQ2AsN9r2UGmkS-0

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/125801673/5a131742-a407-4e9b-b57f-1b24fdd26b07)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/726467ff-51e3-451c-8372-93819dde4854)

**Comment by Illia2810** [comment]
#5155

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
