### ISSUE TITLE
20150502_06_hungary / Points on the travel route are displayed with a "star"

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5157]
Steps to reproduce:

1. Open the page https://test.long-travel.live/20150502_06_hungary
2. Pay attention to the upper left corner of the block "Map route"

Actual result:
1. Points are displayed with a "star"

Expected result:
1. Points are displayed with a "dot"
Travel points on the route are not the "Пам'ятка" and can`t displayed with a "star"

Attachments:
![Снимок экрана 2024-03-04 в 16 09 14](https://github.com/scholokov/long-travel-2/assets/130754297/4a8ccea3-cfa9-4b2a-9747-5cecc0cfa623)

![Снимок экрана 2024-03-04 в 13 44 37](https://github.com/scholokov/long-travel-2/assets/130754297/94d038c6-cefa-45a4-8e2f-dbf8fedb0098)

Documentation:
[Requirements](https://qax.gitbook.io/qax-travel/requirements)
[Map](https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa) p.2.4, 2.5

Environment:
Browser: Google Chrome 122.0.6261.69
OS: macOS 10.15.7

**Comment by Nanafox2010** [comment]
[#5096](https://github.com/scholokov/long-travel-2/issues/5096)

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
