### ISSUE TITLE
"20091026_1102_toronto" travel - Map - Inscriptions except for the names of countries and cities are written in English

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5159]
**Steps of reproducing**
1. Open https://test.long-travel.live/20091026_1102_toronto/
2. Scroll to the Map
3. Pay attention to the "Маршрут подорожі" block

**Actual Result**
Inscriptions except for the names of countries and cities are written in English

**Expected Result**
Inscriptions except for the names of countries and cities are written in Ukrainian

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environments**
Windows 10, Chrome 122.0.6261.95 (64 bit)
![Toronto – Long-Travel - Google Chrome 05 03 2024 17_36_55](https://github.com/scholokov/long-travel-2/assets/95171672/753a41cc-95e9-466c-9651-032ba9fefb03)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by DmitriiNasonov** [comment]
In the bug report isn't written about bugs in countries or cities names.
"Best Western Primrose" is the name of the hotel, if that's what you're talking about.

**Comment by scholokov** [comment]
Best Western Primrose - така назва готелю. що тут зробиш :)))

**Comment by DmitriiNasonov** [comment]
bug is fixed partly. created new bug report: #5203
