### ISSUE TITLE
"20091026_1102_toronto" travel - standard blocks photogallery type is "random"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5161]
**Steps of reproducing**
1. Open https://test.long-travel.live/20091026_1102_toronto/
2. Scroll to the any standard block
3. Check photogallery type

**Actual Result**
Photogallery type is "random"

**Expected Result**
Photogallery type is "mosaic"

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

**Environments**
Windows 10, Chrome 122.0.6261.95 (64 bit)
![DevTools - test long-travel live_20091026_1102_toronto_ 05 03 2024 21_40_18](https://github.com/scholokov/long-travel-2/assets/95171672/e95d972d-3b2f-4dad-beac-199ced85c9a8)
![DevTools - test long-travel live_20091026_1102_toronto_ 05 03 2024 21_57_01](https://github.com/scholokov/long-travel-2/assets/95171672/32d8f6b8-93aa-413e-ba72-b04c3e706f9a)
![DevTools - test long-travel live_20091026_1102_toronto_ 05 03 2024 21_57_16](https://github.com/scholokov/long-travel-2/assets/95171672/78a70355-2d15-45e2-adb1-76a603b0bafa)
![DevTools 05 03 2024 21_57_28](https://github.com/scholokov/long-travel-2/assets/95171672/898c4951-e1e1-4469-ba4f-6bb6ea616e35)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
#5181
