### ISSUE TITLE
20160326_konotop on the trip "Конопська ДЮСШ" a drop-down list is present from the map

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5165]
Pre-conditions:
Open: https://test.long-travel.live/travels/

Steps to reproduce:

Note that on the trip "Конопська ДЮСШ" a drop-down list is present from the map

Actual result:
on the trip "Конопська ДЮСШ" a drop-down list is present from the map
Expected result:
the drop-down list with cards should be absent

Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/05a1a11b-aa4f-4f90-b118-eaca80db9470)

**Comment by Illia2810** [comment]
#5165

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified

**Comment by Illia2810** [comment]
verified
