### ISSUE TITLE
20061028_bila_tserkva / The Photo gallery type is "Random"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5168]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20061028_bila_tserkva
2. Pay attention to the photo gallery type.

**Actual result:**
The photogallery type is "Random".

**Expected result:**
The Photo gallery type is "Mosaic".

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/79dd2fc1-2bf3-4cef-b933-8c1719cd8b45)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
