### ISSUE TITLE
20061028_bila_tserkva / The name of the Travel in the drop-down list on the Map is "20061028_Bila_Tserkva"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5169]
**Steps to reproduce:**

1. Open https://test.long-travel.live/travels/
2. Pay attention to the name of the Travel in the drop-down list on the Map.

**Actual Result:** 
The name of the Travel in the drop-down list on the Map is "20061028_Bila_Tserkva".

**Expected Result:** 
The name of the Travel in the drop-down list on the Map is "2006.10.28 Біла Церква".

**Additional information:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/fd93eddf-e34f-4ae2-9be9-24cc360aa37d)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
