### ISSUE TITLE
20160326_konotop flag on standard block "Конотопська дитячо-юнацька спортивна школа Михайла Маміашвілі Конотопської міської ради Сумської області" are not sized according to the design

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5172]
Pre-conditions:
Open: https://test.long-travel.live/travels/
Open: https://test.long-travel.live/20160326_konotop/
Steps to reproduce:

Note that flag on standard block "Конотопська дитячо-юнацька спортивна школа Михайла Маміашвілі Конотопської міської ради Сумської області" are not sized according to the design
Actual result:
flag on standard block "Конотопська дитячо-юнацька спортивна школа Михайла Маміашвілі Конотопської міської ради Сумської області" are not sized according to the design 28х18
Expected result:
the size of the flags should match the design 36х24
​
Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=1201-2459&mode=design&t=SufQ2AsN9r2UGmkS-0

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/125801673/5a131742-a407-4e9b-b57f-1b24fdd26b07)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/6216c307-0eef-4727-97bc-08b11da697c6)

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
