### ISSUE TITLE
20160326_konotop on the trip "Конопська ДЮСШ" on map the name of the city in English, and a trip around Ukraine

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5174]
Pre-conditions:
Open: https://test.long-travel.live/travels/

Steps to reproduce:

Note that on the trip "Конопська ДЮСШ" on map the name of the city in English, and a trip around Ukraine

Actual result:
on the trip "Конопська ДЮСШ" on map the name of the city in English, and a trip around Ukraine
Expected result:
the names of the cities must be in the language of the countries to which they belong

Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/83bc5712-8b09-424e-9274-9b6edf16ec2b)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/7c44917b-87f7-44c0-b3e3-bd80bf74811f)

**Comment by Illia2810** [comment]
#5174

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified

**Comment by Illia2810** [comment]
verified
