### ISSUE TITLE
20070406_09_lviv/  Extra text "Дорога – Киев – Коростень" after map block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5176]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20070406_09_lviv/ 
2. Pay attention to the text "06-09.04.2007" between Preview and Map blocks.

**Actual Result:** 
There is the text "06-09.04.2007" between Preview and Map blocks.

**Expected Result:** 
There is no text "06-09.04.2007" between Preview and Map blocks.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/009ca456-fe2c-4e7c-9e0c-b97ceb99f5ac)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
