### ISSUE TITLE
20070406_09_lviv/ Name of the city and the street in the map's legend are in English

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5179]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20070406_09_lviv/
2. Pay attention to the name of the city "Kyiv", and the street "Stryiska Street" in the map's legend.

**Actual result:**
The name of the city "Kyiv", and the street "Stryiska Street" in the map's legend are in English.

**Expected result:**
The name of the city "Kyiv", and the street "Stryiska Street" in the map's legend are in Ukrainian.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/fb350553-bc8f-40bc-8fb7-9fb67218454a)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
