### ISSUE TITLE
20070406_09_lviv/ The name of the Travel in the drop-down list on the Map is "20070406_09_Lviv" 

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5180]
**Steps to reproduce:**

1. Open https://test.long-travel.live/travels/
2. Find Travel "20070406_09_lviv" in the drop-down list on the Map.
3. Pay attention to the name of the Trave.

**Actual Result:** 
The name of the Travel in the drop-down list on the Map is "20070406_09_Lviv".

**Expected Result:** 
The name of the Travel in the drop-down list on the Map is "2007.04.06 Львів 2007".

**Additional information:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/d1a49d58-f29b-4f62-b87a-c249a593e0ac)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
