### ISSUE TITLE
"20120827_0913_karpathian_crimia" travel - Travel preview - Date format is "DD.MM-DD.MM.YYYY"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5182]
**Steps of reproducing**
1. Open https://test.long-travel.live/20120827_0913_karpathian_crimia/
2. Pay attention to the date format on travel preview

**Actual Result**
The date format is "DD.MM-DD.MM.YYYY"

**Expected Result**
The date format is "DD.MM.YYYY-DD.MM.YYYY"

**Additional information**
[travel with number 007](https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list)

**Environments**
Windows 10, Chrome 122.0.6261.112 (64 bit)
Android 8.1.0, Chrome 122.0.6261.105
![Карпати – Крим – Long-Travel - Google Chrome 12 03 2024 14_46_31](https://github.com/scholokov/long-travel-2/assets/95171672/2df46b12-afd3-4d85-bb20-4234c9e4da15)
![photo_2024-03-12_14-48-55](https://github.com/scholokov/long-travel-2/assets/95171672/aa14343d-52b0-4361-a03c-3f691dbfa6df)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
