### ISSUE TITLE
"20120827_0913_karpathian_crimia" travel - Map - Cities and villages are marked with a "Пам'ятка" dot

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5183]
*Steps of reproducing**
1. Open https://test.long-travel.live/20120827_0913_karpathian_crimia/
2. Scroll to map

**Actual Result**
Cities and villages are marked with a "Пам'ятка" dot

**Expected Result**
Cities and villages are marked with a "проміжна точка" dot

**Additional information**
[point 2.5 and 2.5.1](https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa)

**Environments**
Windows 10, Chrome 122.0.6261.112 (64 bit)
Android 8.1.0, Chrome 122.0.6261.105
![Карпати – Крим – Long-Travel - Google Chrome 12 03 2024 15_21_07](https://github.com/scholokov/long-travel-2/assets/95171672/1ba858e8-bfb9-477d-88e1-b49c1a17b11d)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
