### ISSUE TITLE
"20120827_0913_karpathian_crimia" travel - Map - Cities and villages names are written on English

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5184]
*Steps of reproducing**
1. Open https://test.long-travel.live/20120827_0913_karpathian_crimia/
2. Scroll to Map
3. Pay attention to the "Маршрут подорожі" block

**Actual Result**
Cities and villages names are written on English

**Expected Result**
Cities and villages names are written on Ukranian

**Additional information**
[point 6.2](https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa)

**Environments**
Windows 10, Chrome 122.0.6261.112 (64 bit)
Android 8.1.0, Chrome 122.0.6261.105
![Карпати – Крим – Long-Travel - Google Chrome 12 03 2024 15_34_53](https://github.com/scholokov/long-travel-2/assets/95171672/7c7c9e1d-bb7b-4d6b-89f1-4f62b43957ec)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
