### ISSUE TITLE
"20120827_0913_karpathian_crimia" travel - "Крим" standard block - Standard block type is "none"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5187]
*Steps of reproducing**
1. Open https://test.long-travel.live/20120827_0913_karpathian_crimia/
2. Scroll to the "Крим" standard block

**Actual Result**
Standard block type is "none"

**Expected Result**
Standard block type is "Country"

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/prevyu-podorozhi
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=3531-33&mode=design&t=iUL2ACQPdtMoSdT7-0

**Environments**
Windows 10, Chrome 122.0.6261.112 (64 bit)
Android 8.1.0, Chrome 122.0.6261.105
![Карпати – Крим – Long-Travel - Google Chrome 12 03 2024 16_29_13](https://github.com/scholokov/long-travel-2/assets/95171672/af84f7be-a12b-4f62-bf72
![photo_2024-03-12_16-39-06](https://github.com/scholokov/long-travel-2/assets/95171672/6990c55b-aed8-440d-b5d9-d18837ecf7c3)
-7b3ca8c09785)

**Comment by DmitriiNasonov** [comment]
https://github.com/scholokov/long-travel-2/issues/5128

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
