### ISSUE TITLE
20070406_09_lviv/ The extra element "Stryiska Street 179" in the Map's legend

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5196]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20070406_09_lviv/
2. Scroll down to the Map of Travel.
3. Pay attention to the text after the preview foto in the map's legend.

**Actual result:**
The extra element "Stryiska Street 179" is after the preview photo in the map's legend.

**Expected result:**
The extra element Stryiska Street 179" does not appear after the preview photo in the map's legend.

**Additional information:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/91946310-6190-48d5-82bf-9bfedcab6c4c)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
