### ISSUE TITLE
20070406_09_lviv/ The preview photo of the Road block "Дорога обратно 06-09.04.2007" is missing

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5201]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20070406_09_lviv/ 
2. Scroll down to the Road block "Дорога обратно 06-09.04.2007".
3. Pay attention to the Preview photo of the block.

**Actual result:**
 The preview photo of the Road block "Дорога обратно 06-09.04.2007" is missing.

**Expected result:**
 **The preview photo of the Road block "Дорога обратно 06-09.04.2007" is present.**

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/prevyu-podorozhi

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/b7289eff-eb1c-4705-89eb-dca6fb9ce836)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
