### ISSUE TITLE
20150502_06_hungary / The blocks "Header (Прев'ю)" has no flags

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5202]
Steps to reproduce:
1. Open the page https://test.long-travel.live/20150502_06_hungary
2. Pay attention to the right side of the blocks "Header (Прев'ю)"

Actual result:
1. There are no flags

Expected result:
1. On the right side of the block "Header (Прев'ю)" should be the flag of the country to which it belongs.
- Ukraine
- Hungary

Attachments:
![Снимок экрана 2024-03-19 в 14 55 18](https://github.com/scholokov/long-travel-2/assets/130754297/d6c7cf2b-c6c1-45db-9f6d-c9177ebf2d58)
![Снимок экрана 2024-03-19 в 14 55 26](https://github.com/scholokov/long-travel-2/assets/130754297/d9345a72-366f-4a1b-b4e9-b3348a450867)
![Снимок экрана 2024-03-19 в 14 55 37](https://github.com/scholokov/long-travel-2/assets/130754297/49c32d88-beb9-4c29-8295-6801dc6536ab)
![Снимок экрана 2024-03-19 в 14 55 49](https://github.com/scholokov/long-travel-2/assets/130754297/39061661-2001-4dae-9412-3627fd30a110)
![Снимок экрана 2024-03-19 в 14 56 00](https://github.com/scholokov/long-travel-2/assets/130754297/d493d122-e8d1-47c0-95bf-2436b3bfc05b)
![Снимок экрана 2024-03-19 в 14 56 10](https://github.com/scholokov/long-travel-2/assets/130754297/8eb30f8d-7d3b-4125-9aaf-4a999f5b880a)
![Снимок экрана 2024-03-19 в 14 56 20](https://github.com/scholokov/long-travel-2/assets/130754297/34f17797-f0a9-41b7-a8b6-23ecfe0e589e)

Documentation:
[Requirements](https://qax.gitbook.io/qax-travel/requirements)

Environment:
Browser: Google Chrome 122.0.6261.129
OS: macOS 10.15.7

**Comment by Nanafox2010** [comment]
https://github.com/scholokov/long-travel-2/issues/5096

**Comment by Nanafox2010** [comment]
Some blocks "Header (Прев'ю)" have wrong flags
![Снимок экрана 2024-03-22 в 15 04 58](https://github.com/scholokov/long-travel-2/assets/130754297/503d7736-68f6-4494-8615-2b8166b67d84)
![Снимок экрана 2024-03-22 в 15 05 30](https://github.com/scholokov/long-travel-2/assets/130754297/0b5681db-6c4a-4ea5-b2d5-20c515d3b2a0)
![Снимок экрана 2024-03-22 в 15 06 22](https://github.com/scholokov/long-travel-2/assets/130754297/53978e59-4699-416e-b0f3-67630c475e8a)

**Comment by scholokov** [comment]
але дана помилка не відповідає описаній вище. це має бути новий баг

**Comment by scholokov** [comment]
подивиться на процес офрмлення "частково виправленого багу"

**Comment by Nanafox2010** [comment]
Verified
