### ISSUE TITLE
"20120827_0913_karpathian_crimia" travel - Part of the standarts blocks (Indicated in the "Additional information" block) - Fotogallery type is "random"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5204]
**Steps of reproducing**
1. Open https://test.long-travel.live/20120827_0913_karpathian_crimia/
2. Scroll to the "Крим" standard block

**Actual Result**
Fotogallery type is "random"

**Expected Result**
Fotogallery type is "mosaic"

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i
List of the standard blocks with this bug: 
1. Готель Карина, Поляна, Закарпаття, Україна
2. Мотель Ластівчине гніздо, Війтівці, Вінницька Область
3. Готель Пілігрим
4. Готель
5. Крим
6. Пляж
7. Алушта
8. Ялта
9. Азовське море
10. Готель Пілігрим

**Environments**
Windows 10, Chrome 123.0.6312.59 (64 bit)
![DevTools - test long-travel live_20120827_0913_karpathian_crimia_ 20 03 2024 16_37_49](https://github.com/scholokov/long-travel-2/assets/95171672/44266d03-55e3-4e53-a10c-b44645f66e2d)
![Demonur_13 _ Статистика игроков War Thunder - Google Chrome 02 04 2024 15_25_35](https://github.com/scholokov/long-travel-2/assets/95171672/6bcc4780-dfec-4bf0-9949-811e9775afe3)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by DmytroMarkulych** [comment]
@DmitriiNasonov а яка саме галерея?

**Comment by scholokov** [comment]
а скрін хочаб одної галереї?

**Comment by DmitriiNasonov** [comment]
Added. But why do you need it?

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
