### ISSUE TITLE
20160518_22_eger/ the preview shows an incorrect date

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5206]
Pre-conditions:
Open: https://test.long-travel.live/20160518_22_eger/

Steps to reproduce:

   1. Open https://test.long-travel.live/travels/
   2. Select 20160518_22_eger
   3. Open https://test.long-travel.live/20160518_22_eger/
   4. Note that the preview shows an incorrect date

Actual result:
the preview shows an incorrect date
Expected result:
the date must be 18 - 22.05.2016

Environment:
system: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/3e982e66-5a98-44da-b150-0a3633033928)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/5c55de4e-0f82-42b3-9e17-064620628fe6)

**Comment by Illia2810** [comment]
#5206

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified

**Comment by Illia2810** [comment]
verified
