### ISSUE TITLE
20160518_22_eger/ in the trip "Egerszalok – Львів", "Пам'ятка" is the city  "Lviv", "Egerszalók"

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5207]
Pre-conditions:
Open: https://test.long-travel.live/20160518_22_eger/

Steps to reproduce:

    Open https://test.long-travel.live/travels/
    Select 20160518_22_eger
    Open https://test.long-travel.live/20160518_22_eger/
    Note the  "Пам'ятка"  cannot be a city

Actual result:
"Пам'ятка" - cannot be a city
Expected result:
"Пам'ятка"- the object of visit. For example: Museum, Zoo

Environment:
system: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/01c447cc-a5fd-4630-87a5-a42f0e49b4b4)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/492c637f-d04b-4fe6-b0ab-c4a973158219)

**Comment by DmytroMarkulych** [comment]
Давайте додамо більш конкретні умови в баг репорті

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/long-travel-2/assets/88647733/bdad2568-4bae-4bae-974f-445be7664500)

**Comment by Illia2810** [comment]
виправлено

**Comment by DmytroMarkulych** [comment]
Вкажіть що конкретно має бути

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
