### ISSUE TITLE
20160518_22_eger/  on the trip "Egerszalok – Львів" on map the name of the city in English, and a trip around Ukraine 

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5208]
Pre-conditions:
Open: https://test.long-travel.live/20160518_22_eger/

Steps to reproduce:

Note that on the trip "Egerszalok – Львів" on map the name of the city in English, and a trip around Ukraine 

Actual result:
on the trip "Egerszalok – Львів" on map the name of the city in English, and a trip around Ukraine 
Expected result:
the names of the cities must be in the language of the countries to which they belong

Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/53a0f811-dae3-45db-bfe9-cafac3b89228)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/83bc5712-8b09-424e-9274-9b6edf16ec2b)

**Comment by Illia2810** [comment]
#5208

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
