### ISSUE TITLE
20160518_22_eger/ in a trip "Egerszalok – Львів", all blocks of photos are loaded simultaneously

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5209]
Pre-conditions:
Open: https://test.long-travel.live/20160518_22_eger/

Steps to reproduce:

    Open https://test.long-travel.live/travels/
    Select 20160518_22_eger
    Open https://test.long-travel.live/20160518_22_eger/
    Note that in a trip "Egerszalok – Львів", all blocks of photos are loaded simultaneously

Actual result:
in a trip "Egerszalok – Львів", all blocks of photos are loaded simultaneously
Expected result:
all subsequent galleries should NOT be loaded at once

Environment:
system: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/517a1946-707c-49bb-ac60-26f706110c74)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/431490ef-2589-4e97-bb22-24582df76351)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/a0a9d648-eeea-4f09-b54d-5db7efeae96e)

**Comment by Illia2810** [comment]
#5209

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified

**Comment by Illia2810** [comment]
verified
