### ISSUE TITLE
20160518_22_eger/ in a trip "Egerszalok – Львів", all standard blocks do not have country flags

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5210]
Pre-conditions:
Open: https://test.long-travel.live/20160518_22_eger/

Steps to reproduce:

Open https://test.long-travel.live/travels/
Select 20160518_22_eger
Open https://test.long-travel.live/20160518_22_eger/
Note that in a trip "Egerszalok – Львів", all standard blocks do not have country flags

Actual result:
in a trip "Egerszalok – Львів", all standard blocks do not have country flags
Expected result:
all standard blocks must have the flag or flags of the countries to which it belongs;
standard block road "Київ, Україна – Egerszalók, Magyarország" - should be flags of Ukraine and Hungary
standard block hotel "Ámbitus-ház" - should be flag of Hungary
standard block city "Egerszalók" - should be flag of Hungary
standard block restaurant - should be flag of Hungary
standard block road "Egerszalok – Львів" - should be flags of Hungary and Ukraine
standard block hotel  "Отель Копа" - should be flag of Ukraine
standard block city ""Львів, Україна" - should be flag of Ukraine
standard block road "Львів, Україна – Київ, Україна" - should be flag of Ukraine

Environment:
system: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

Attachment:
should be flags of Ukraine and Hungary
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/9e41ca71-acc9-4255-bcc3-eef7d8b1db96)
should be flag of Hungary
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/060777dc-bfbf-4cb5-9653-be7df6767014)
should be flag of Hungary
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/d41004c1-7703-4f51-9f9d-5fbcfe14b082)
should be flag of Hungary
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/b6410659-2c2c-4ccc-9b7e-4ca595609965)
should be flags of Hungary and Ukraine
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/e88a2ea4-ff33-435d-92a3-8a2ee3081efe)
should be flag of Ukraine
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/a0d8ca9c-4db1-43f0-87a8-27745c203ac7)
should be flag of Ukraine
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/c3249817-2a0f-499b-9468-42e3e85617a4)
should be flag of Ukraine
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/5a28a2a8-c8ee-4119-9c02-ea3fb9aac9ba)

**Comment by Illia2810** [comment]
#5210

**Comment by DmytroMarkulych** [comment]
Який саме прапор має бути?

**Comment by Illia2810** [comment]
який саме  має бути прапор вказано над скріншотом
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/cd0e9a46-d115-447a-ba9b-079cbdc8e982)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/95580e8e-bfc0-4ff2-a91a-8653e0e48606)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/7b08e094-0897-4e28-948f-96bf08517e88)

**Comment by DmytroMarkulych** [comment]
краще додати в expected result

**Comment by Illia2810** [comment]
виправлено

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
