### ISSUE TITLE
20160518_22_eger/ the date of check-in to the hotel is not correct 17-20.05.2016, in the standard block, hotel "Ámbitus-ház"

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5211]
Pre-conditions:
Open: https://test.long-travel.live/20160518_22_eger/

Steps to reproduce:

Open https://test.long-travel.live/travels/
Select 20160518_22_eger
Open https://test.long-travel.live/20160518_22_eger/
Note that the date of check-in to the hotel is not correct 17-20.05.2016, in the standard block, hotel "Ámbitus-ház"

Actual result:
the date of check-in to the hotel is not correct 17-20.05.2016, in the standard block, hotel "Ámbitus-ház"
Expected result:
the start date of the trip is 18.05.2016. Check-in to the hotel cannot be on 17.05.2016

Environment:
system: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/ed66a3e4-b1c9-4c25-a729-24472b6cc064)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/c3eb5f7b-f8d1-463f-ab8f-2eb7b5e88fb7)

**Comment by Illia2810** [comment]
#5211

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
