### ISSUE TITLE
20160518_22_eger/  in the standard block, the "Ámbitus-ház" hotel, the city and the region are indicated

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5212]
Pre-conditions:
Open: https://test.long-travel.live/20160518_22_eger/

Steps to reproduce:

Open https://test.long-travel.live/travels/
Select 20160518_22_eger
Open https://test.long-travel.live/20160518_22_eger/
Note that in the standard block, the "Ámbitus-ház" hotel, the city and the region are indicated

Actual result:
in the standard block, the "Ámbitus-ház" hotel, the city and the region are indicated
Expected result:
in the standard block, the hotel should be indicated only by the city

Environment:
system: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/acfbf040-a402-4af9-a52d-9eccc07831fd)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/15dab184-d2a5-455f-b487-37efdd4ad525)

**Comment by Illia2810** [comment]
#5212

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
