### ISSUE TITLE
20160518_22_eger/ in the standard block, the Road "Kyiv, Ukraine – Egerszalók, Magyarország" the date 17.05.2016 of the start of the trip is incorrectly indicated

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5213]
Pre-conditions:
Open: https://test.long-travel.live/20160518_22_eger/

Steps to reproduce:

Open https://test.long-travel.live/travels/
Select 20160518_22_eger
Open https://test.long-travel.live/20160518_22_eger/
Note that in the standard block, the Road "Kyiv, Ukraine – Egerszalók, Magyarország" the date 17.05.2016 of the start of the trip is incorrectly indicated

Actual result:
in the standard block, the Road "Kyiv, Ukraine – Egerszalók, Magyarország" the date 17.05.2016 of the start of the trip is incorrectly indicated
Expected result:
the date of publication should be 18.05.2016

Environment:
system: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/243a67ce-f076-4cf1-92d0-7188d9baee31)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/bca197a0-1e66-4b23-bca7-aada2c537bf3)

**Comment by Illia2810** [comment]
#5213

**Comment by DmytroMarkulych** [comment]
В Expected Result просто вказуємо що має бути

**Comment by Illia2810** [comment]
виправлено

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
