### ISSUE TITLE
in the requirements "Types of standard bdocs" in clause 1.3.3.11 City, line 2 is missing

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5215]
Open: https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

Steps to reproduce:
Scroll to clause 1.3.3.11 City
Note that in clause 1.3.3.11 City, line 2 is missing

Actual result:
in clause 1.3.3.11 City, line 2 is missing
Expected result:
should be 2 line

Environment:
system: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/15ae7c4a-e5da-461c-a48d-7eae63fc6fef)

**Comment by Illia2810** [comment]
#5215

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
помилка відтворюється
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/1a4c92e5-0037-47e0-9463-7b2d94e61b5c)
