### ISSUE TITLE
20160518_22_eger/ information from the standard block hotel "Отель Копа" is duplicated

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5216]
Pre-conditions:
Open: https://test.long-travel.live/20160518_22_eger/

Steps to reproduce:

Open https://test.long-travel.live/20160518_22_eger/
Scroll oт standard block "Отель Копа"
Note that information from the standard block hotel "Отель Копа" is duplicated

Actual result:
information from the standard block hotel "Отель Копа" is duplicated
Expected result:
information should not be duplicated

Environment:
system: Windows 10 Pro
Browser: FireFox

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/8b8dad24-7b5e-44bc-9ef6-1da7d2fe858a)

**Comment by Illia2810** [comment]
#5216

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
