### ISSUE TITLE
20160518_22_eger/ in the standard block, the restaurant does not have a restaurant name

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5217]
Pre-conditions:
Open: https://test.long-travel.live/20160518_22_eger/

Steps to reproduce:

Open https://test.long-travel.live/20160518_22_eger/
Scroll on standard block "Restaurant"
Note that in the standard block, the restaurant does not have a restaurant name

Actual result:
in the standard block, the restaurant does not have a restaurant name
Expected result:
the name of the restaurant should be in the standard block

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/data-publikaciyi

Environment:
system: Windows 10 Pro
Browser: FireFox

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/cd911597-9306-478b-a45b-0877caf21347)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/ffde4f8f-4b85-40ed-b137-9fb300ffa537)

**Comment by Illia2810** [comment]
#5217

**Comment by scholokov** [comment]
не маю назву щоб додати :)
