### ISSUE TITLE
 20160518_22_eger/ in a standard block, the restaurant does not have a city

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5218]
Pre-conditions:
Open: https://test.long-travel.live/20160518_22_eger/

Steps to reproduce:

Open https://test.long-travel.live/20160518_22_eger/
Scroll on standard block "Restaurant"
Note that in a standard block, the restaurant does not have a city

Actual result:
in a standard block, the restaurant does not have a city
Expected result:
in the standard block restaurant there must be a city

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/data-publikaciyi

Environment:
system: Windows 10 Pro
Browser: FireFox

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/935e7a03-d17f-4d62-b165-efd8338528c6)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/add8b575-718d-4233-9173-ced3f32650ea)

**Comment by Illia2810** [comment]
#5218

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
