### ISSUE TITLE
20150502_06_hungary / In the "Header (Прев'ю)" the country name is displayed

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5230]
Steps to reproduce:

1. Open the page https://test.long-travel.live/20150502_06_hungary
2. Pay attention to the left side on the "Header (Прев'ю)"

Actual result:

1. The country name is displayed

Expected result:

1. The country name should not displayed in the "Header (Прев'ю)"

Attachments:
![Снимок экрана 2024-03-27 в 10 52 23](https://github.com/scholokov/long-travel-2/assets/130754297/832d9e09-41d3-4fb4-9f4c-6bd290709164)
![Снимок экрана 2024-03-27 в 11 19 29](https://github.com/scholokov/long-travel-2/assets/130754297/4e41ec2d-a507-4814-b6fc-25dec9353249)
![Снимок экрана 2024-03-27 в 15 13 08](https://github.com/scholokov/long-travel-2/assets/130754297/8d70d339-f93c-40ac-b9ac-5f8ce4291520)
![Снимок экрана 2024-03-27 в 15 14 23](https://github.com/scholokov/long-travel-2/assets/130754297/35e0b723-9ff4-46f8-aabc-bdc88f3b044e)
![Снимок экрана 2024-03-27 в 15 14 51](https://github.com/scholokov/long-travel-2/assets/130754297/fd09291c-01ad-4b9a-a52d-eab66ff8477d)
![Снимок экрана 2024-03-27 в 15 15 17](https://github.com/scholokov/long-travel-2/assets/130754297/75852261-29bd-41b1-b9c0-d9a2d47d90c7)
![Снимок экрана 2024-03-27 в 15 15 42](https://github.com/scholokov/long-travel-2/assets/130754297/ec69e321-05a7-49db-a571-6e2f9a5101ad)
![Снимок экрана 2024-03-27 в 15 16 01](https://github.com/scholokov/long-travel-2/assets/130754297/294351d3-fba0-404a-81ab-61bf78e097e0)
![Снимок экрана 2024-03-27 в 15 16 26](https://github.com/scholokov/long-travel-2/assets/130754297/e3389d37-553c-4201-b5a0-7038d72ff71a)

Documentation:
[Requirements](https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv)

Environment:
Browser: Google Chrome 122.0.6261.129
OS: macOS 10.15.7

**Comment by Nanafox2010** [comment]
https://github.com/scholokov/long-travel-2/issues/5096

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
