### ISSUE TITLE
20160618_mezhigorie/ on the trip "Національний парк “Межигір’я”" on the map, the names of the cities are in English

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5231]
Pre-conditions:
Open: https://test.long-travel.live/travels/

Steps to reproduce:

Note that on the trip "Національний парк “Межигір’я”" on the map, the names of the cities are in English

Actual result:
on the trip "Національний парк “Межигір’я”" on the map, the names of the cities are in English
Expected result:
the names of the cities must be in the language of the countries to which they belong

Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/83bc5712-8b09-424e-9274-9b6edf16ec2b)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/98731ac8-8a8e-4612-8ee4-2321a1b268ec)

**Comment by Illia2810** [comment]
#5231

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
