### ISSUE TITLE
"20091026_1102_toronto" travel - "Best Western Primrose Hotel", "Downtown-Toronto", "CN Tower" standard blocks - Photo gallery is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5232]
**Steps of reproducing**
1. Open https://test.long-travel.live/20091026_1102_toronto/
2. Scroll to the "Best Western Primrose Hotel", "Downtown-Toronto", "CN Tower" standard blocks

**Actual Result**
Photo gallery is missing

**Expected Result**
Photo gallery is present

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

**Environments**
Windows 10, Chrome 123.0.6312.86 (64 bit)
![Toronto – Long-Travel - Google Chrome 27 03 2024 15_29_38](https://github.com/scholokov/long-travel-2/assets/95171672/b601e423-cbed-49bb-aef1-3615c11f8cfb)
![DevTools - test long-travel live_20091026_1102_toronto_ 27 03 2024 15_33_18](https://github.com/scholokov/long-travel-2/assets/95171672/e50f62db-3bc6-4ea6-996d-ccb0f387155b)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/long-travel-2/assets/88647733/75cf6028-52ee-4458-b59b-3e0933e0f5ce)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
