### ISSUE TITLE
20160618_mezhigorie/ on the trip "Національний парк “Межигір’я”"  a drop-down list is present from the map 

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5233]
Pre-conditions:
Open: https://test.long-travel.live/travels/

Steps to reproduce:

Note that on the trip "Національний парк “Межигір’я”"  a drop-down list is present from the map 

Actual result:
on the trip "Національний парк “Межигір’я”"  a drop-down list is present from the map 
Expected result:
the drop-down list with cards should be absent

Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/021fc051-cd3b-4234-9311-f2f7d122a432)

**Comment by Illia2810** [comment]
#5233

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
