### ISSUE TITLE
20150502_06_hungary / The "Відобразити галерею" button is missed and all subsequent galleries are loaded at once

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5235]
Steps to reproduce:

1. Open the page https://test.long-travel.live/20150502_06_hungary
2. Pay attention to photo galleries

Actual result:

1. The "Відобразити галерею" button is missed
2. All subsequent galleries loaded at once

Expected result:

1. All subsequent galleries should NOT be loaded at once
2. "Відобразити галерею" button should be displayed instead of the unloaded gallery
3. Only after clicking the "Відобразити галерею" button, the corresponding gallery should load and be displayed

Attachments:
![Снимок экрана 2024-03-27 в 16 07 23](https://github.com/scholokov/long-travel-2/assets/130754297/2f382707-965b-4456-839c-3a2179737f18)
![Снимок экрана 2024-03-27 в 16 05 38](https://github.com/scholokov/long-travel-2/assets/130754297/1e32293c-c21b-4b0d-85a9-6391f49e9158)

Documentation:
p. 1.3.3.2.4, 1.3.3.2.5
[Requirements](https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i)

Environment:
Browser: Google Chrome 122.0.6261.129
OS: macOS 10.15.7

**Comment by Nanafox2010** [comment]
https://github.com/scholokov/long-travel-2/issues/5096

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
