### ISSUE TITLE
20070406_09_lviv/ Missed active link from the name of the hotel "Отель Жокей 06-09.04.2007" 

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5236]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20070406_09_lviv/ 
2. Scroll down to the Hotel block "Отель Жокей 06-09.04.2007".
3. Pay attention to that the name of the hotel "Отель Жокей 06-09.04.2007" is not an active link.

**Actual result:**
 Missed active link from the name of the hotel "Отель Жокей 06-09.04.2007".

**Expected result:**
 The name of the hotel "Отель Жокей 06-09.04.2007" is not an active link.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/bff0c1cf-1cff-429b-b5db-e94e074528eb)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
