### ISSUE TITLE
20150502_06_hungary / The Photo gallery type is Random

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5237]
Steps to reproduce:

1. Open the page https://test.long-travel.live/20150502_06_hungary
2. Pay attention to the type layout in the DevTools Elements

Actual result:

1. The Photo gallery type is Random

Expected result:

1. The Photo gallery type should be Mosaic

Attachments:
![Снимок экрана 2024-03-28 в 13 15 40](https://github.com/scholokov/long-travel-2/assets/130754297/de706a65-f72b-41d9-a101-b568344f1df3)
![Снимок экрана 2024-03-28 в 13 16 22](https://github.com/scholokov/long-travel-2/assets/130754297/1438a0c6-f2f0-4bd7-8831-8c35d71976ee)
![Снимок экрана 2024-03-28 в 13 16 47](https://github.com/scholokov/long-travel-2/assets/130754297/b05f77f5-e0ef-4bcd-a658-80e3042e41b8)
![Снимок экрана 2024-03-28 в 13 17 14](https://github.com/scholokov/long-travel-2/assets/130754297/7d3ed209-c85d-466c-a428-216e7ecb4061)
![Снимок экрана 2024-03-28 в 13 17 38](https://github.com/scholokov/long-travel-2/assets/130754297/ad5ccfdc-4bdf-453b-b5c7-4c9e6a6ad825)
![Снимок экрана 2024-03-28 в 13 18 07](https://github.com/scholokov/long-travel-2/assets/130754297/4e432d12-73a2-401e-88bf-eb7beca4363a)
![Снимок экрана 2024-03-28 в 13 18 39](https://github.com/scholokov/long-travel-2/assets/130754297/d590640e-3ac1-42cf-ad5d-4f2722561c79)

Documentation:
p.1.3.3.2.3
[Requirements](https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i)

Environment:
Browser: Google Chrome 123.0.6312.59
OS: macOS 10.15.7

**Comment by Nanafox2010** [comment]
https://github.com/scholokov/long-travel-2/issues/5096

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
