### ISSUE TITLE
20070406_09_lviv/ Hotel Block date format is DD.-DD.MM.YYYY

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5240]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20070406_09_lviv/ 
2. Scroll down to the Hotel block "Отель Жокей 06-09.04.2007".
3. Pay attention to the date format 06-09.04.2007.

**Actual result:**
Hotel Block date format is DD.-DD.MM.YYYY - 06-09.04.2007.

**Expected result:**
Hotel Block date format is DD.MM.YYYY - DD.MM.YYYY - **06.04.2007 - 09.04.2007**.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/6fc93a6b-241f-4d06-bccc-83bf3b4f4a8d)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
@GNatala 
вас не засмучує
"DD.MM.YYYY - DD.MM.YYYY - 06.04.2007-09.04.2007"
що формат різний? :))))

**Comment by GNatala** [comment]
@scholokov 
:(  - додала два пробіли
Дякую

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
