### ISSUE TITLE
20070406_09_lviv/ Missed the city name in the Hotel Block 

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5241]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20070406_09_lviv/ 
2. Scroll down to the Hotel block.
3. Pay attention to the absence of the city name.

**Actual result:**
Missed the city name in the Hotel Block.

**Expected result:**
City name is present in the Hotel Block.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**

![image](https://github.com/scholokov/long-travel-2/assets/101987790/3af81f2c-2cd0-4b44-ac19-a36dc7a53eb7)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
