### ISSUE TITLE
20070406_09_lviv/ The word "отель"  is written in russian in the Hotel Block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5242]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20070406_09_lviv/ 
2. Scroll down to the Hotel block.
3. Pay attention to the word "отель".

**Actual result:**
The word "отель"  is written in russian in the Hotel Block.

**Expected result:**
The word "отель"  is written in Ukrainian in the Hotel Block.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/1.overall/language

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/93774cb0-8b71-4af3-aafa-8ff88849bba3)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
