### ISSUE TITLE
20070406_09_lviv/ Names of 3 blocks are written in russian 

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5243]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20070406_09_lviv/ 
2. Scroll down to the "Львов", "Львовская область", "Дорога обратно" blocks.
3. Pay attention to the word language of the names of the blocks.

**Actual result:**
Names of 3 blocks: "Львов", "Львовская область", "Дорога обратно" are written in russian.

**Expected result:**
Names of 3 blocks: "Львов", "Львовская область", and "Дорога обратно" are written in Ukrainian.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/1.overall/language

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/824a2d53-e4fd-4a96-b740-2b5dcaee42a9)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
