### ISSUE TITLE
"20130526_vishgorod" travel - Map - "Маршрут подорожі" block - "Vyshgorod" point has point type "Пам'ятка"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5248]
**Steps of reproducing**
1. Open https://test.long-travel.live/20130526_vishgorod/
2. Scroll to map

**Actual Result**
"Vyshgorod" point has point type "Пам'ятка"

**Expected Result**
"Vyshgorod" point has point type "проміжна точка"

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environments**
Windows 10, Chrome 123.0.6312.106 (64 bit)
![Вишгород – Long-Travel - Google Chrome 03 04 2024 15_04_18](https://github.com/scholokov/long-travel-2/assets/95171672/0918bc92-163c-45fd-83f5-fdf7bc602e64)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
