### ISSUE TITLE
"20130526_vishgorod" travel - Map - "Маршрут подорожі" block - The names of the cities "Vyshgorod" and "Kyiv" written in English

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5249]
**Steps of reproducing**
1. Open https://test.long-travel.live/20130526_vishgorod/
2. Scroll to map

**Actual Result**
The names of the cities "Vyshgorod" and "Kyiv"  written in English

**Expected Result**
The names of the cities "Vyshgorod" and "Kyiv" written in Ukraine

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environments**
Windows 10, Chrome 123.0.6312.106 (64 bit)
![Вишгород – Long-Travel - Google Chrome 03 04 2024 15_20_33](https://github.com/scholokov/long-travel-2/assets/95171672/02f33208-1278-474e-9931-24294a83c604)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
