### ISSUE TITLE
"20130526_vishgorod" travel - Map - Travels dropdown list is present

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5252]
**Steps of reproducing**
1. Open https://test.long-travel.live/20130526_vishgorod/
2. Scroll to map

**Actual Result**
Travels dropdown list is present

**Expected Result**
Travels dropdown list is missing

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environments**
Windows 10, Chrome 123.0.6312.106 (64 bit)
![Вишгород – Long-Travel - Google Chrome 03 04 2024 15_50_13](https://github.com/scholokov/long-travel-2/assets/95171672/213afe15-82a8-4326-94c9-64bb5529dd17)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
