### ISSUE TITLE
"20130526_vishgorod" travel - "Вишгород" standard block - Photogallery type is "random"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5253]
**Steps of reproducing**
1. Open https://test.long-travel.live/20130526_vishgorod/
2. Scroll to "Вишгород" standard block 

**Actual Result**
Photogallery type is "random"

**Expected Result**
Photogallery type is "mosaic"

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

**Environments**
Windows 10, Chrome 123.0.6312.106 (64 bit)
![Вишгород – Long-Travel - Google Chrome 03 04 2024 15_56_48](https://github.com/scholokov/long-travel-2/assets/95171672/6aac1367-b8ce-4e49-9874-d3fd9975085c)
![DevTools - test long-travel live_20130526_vishgorod_ 03 04 2024 15_56_42](https://github.com/scholokov/long-travel-2/assets/95171672/3123f51e-5292-421e-a7ed-c5590f0da119)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
