### ISSUE TITLE
20130908_tropical_park/ The "Київ_Kиївска область_ Україна_tropical_park" Name of the Travel is displayed on the Preview

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#5254]
Steps to reproduce:

1. Open page https://test.long-travel.live/20130908_tropical_park/
2. Pay attention to the Name of the Travel on the Preview

Actual Result: The "Київ_Kиївска область_ Україна_tropical_park" Name of the Travel is displayed on the Preview

Expected Result: The "Розважальний комплекс "Tropical Park"" Name of the Travel is displayed on the Preview

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/28f4c0d0-f5d4-476e-94b3-fce64b9b5b20)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified

**Comment by ODrobik** [comment]
#5129
