### ISSUE TITLE
20131019_petrovtsi_bitva_za_kiev/ The "Битва за Київ у 1943 році" Name of the Travel is displayed on the Preview

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#5255]
Steps to reproduce:

1. Open page https://test.long-travel.live/20131019_petrovtsi_bitva_za_kiev/
2. Pay attention to the Name of the Travel on the Preview

Actual Result: The "Битва за Київ у 1943 році" Name of the Travel is displayed on the Preview

Expected Result: The "Національний музей-заповідник "Битва за Київ у 1943 році" Name of the Travel is displayed on the Preview

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/938decf9-5e1c-441a-843f-083486f9a544)

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified

**Comment by ODrobik** [comment]
#5129
