### ISSUE TITLE
20070406_09_lviv/ The month of Travel in the map's legend is June

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5258]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20070406_09_lviv
2. Scroll down to the Map of Travel.
3. Pay attention to the month of Travel in the map's legend.

**Actual result:**
The month of Travel in the map's legend is June.

**Expected result:**
**The month of Travel in the map's legend is April.**

**Additional information:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/bad0ceeb-0175-4d7a-8e74-85f33ef96c84)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
