### ISSUE TITLE
20070406_09_lviv/ The travel dates on the map's legend do not correspond to the dates in the Blocks

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5259]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20070406_09_lviv
2. Scroll down to the Map of Travel.
3. Pay attention to the month of travel dates on the map's legend.

**Actual result:**
The travel dates on the map's legend do not correspond to the dates in the Blocks.

**Expected result:**
The travel dates on the map's legend correspond to the dates in the Blocks.

**Additional information:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/3c65b0bc-34d7-444b-a28b-0244f2ddaf4d)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
