### ISSUE TITLE
20070406_09_lviv/ Missed format of the Road Block

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5261]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20070406_09_lviv/ 
2. Scroll down to the Road block "Дорога назад 06-09.04.2007".
3. Pay attention to the format of the Road Block.

**Actual result:**
 Missed format of the Road Block: Дорога назад 06-09.04.2007.

**Expected result:**
Format of the Road Block: 
**Дорога 
Львів - Київ
09.04.2007**

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/ad24145b-017f-4d7d-be10-cbceba5181c7)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
