### ISSUE TITLE
20070406_09_lviv/ "Готель Жокей" point has type "Пам'ятка" on the Map

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5263]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20070406_09_lviv
2. Scroll down to the Map of Travel.
3. Pay attention to the "Готель Жокей" point.

**Actual result:**
Готель Жокей" point has the type "Пам'ятка" and is displayed with "star".

**Expected result:**
"Готель Жокей" can not have type "Пам'ятка". **"Готель Жокей" type is "проміжна точка".**

**Additional information:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/e44c1aa1-a523-48e4-9698-3cf20efbd7af)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
