### ISSUE TITLE
"20130613_0628_bulgaria" travel - Travel preview - Date format is "DD-DD.MM.YYYY"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5265]
**Steps of reproducing**
1. Open https://test.long-travel.live/20130613_0628_bulgaria/
2. Pay attention to the date format on the travel preview

**Actual Result**
The date format is "DD-DD.MM.YYYY"

**Expected Result**
The date format is "DD.MM.YYYY-DD.MM.YYYY"

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/travels-list)](https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/prevyu-podorozhi

**Environments**
Windows 10, Chrome 123.0.6312.106 (64 bit)
Android 8.1.0, Chrome 123.0.6312.99
![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 10 04 2024 12_57_23](https://github.com/scholokov/long-travel-2/assets/95171672/fb815ca0-862e-4620-bff7-4494bb4988bb)
![photo_2024-04-10_12-59-49](https://github.com/scholokov/long-travel-2/assets/95171672/cab97375-76fe-4d49-88ef-38aa8821eb1d)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
