### ISSUE TITLE
20170128_konotop  on the trip "Конотоп" on map the name of the city in English, and a trip around Ukraine

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5267]
Pre-conditions:
Open: https://test.long-travel.live/travels/

Steps to reproduce:

Note that on the trip "Конотоп" on map the name of the city in English, and a trip around Ukraine

Actual result:
on the trip "Конотоп" on map the name of the city in English, and a trip around Ukraine
Expected result:
the names of the cities must be in the language of the countries to which they belong

Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/83bc5712-8b09-424e-9274-9b6edf16ec2b)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/9aaa1e6d-6991-42f9-a6a3-c097398d167d)

**Comment by Illia2810** [comment]
#5267

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
