### ISSUE TITLE
"20130613_0628_bulgaria" travel - Map - "Маршрут подорожі" block - "Savran' ", "Slănic-Moldova, Romania", "Bucharest", and "Bolhrad, Ukraine" points have point type "Пам'ятка"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5268]
**Steps of reproducing**
1. Open https://test.long-travel.live/20130613_0628_bulgaria/
2. Scroll to map

**Actual Result**
"Savran' ", "Slănic-Moldova, Romania", "Bucharest", and "Bolhrad, Ukraine" points have point type "Пам'ятка"

**Expected Result**
"Savran' ", "Slănic-Moldova, Romania", "Bucharest", and "Bolhrad, Ukraine" points have point type "проміжна точка"

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environments**
Windows 10, Chrome 123.0.6312.106 (64 bit)
![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 10 04 2024 14_13_28](https://github.com/scholokov/long-travel-2/assets/95171672/24304b7f-7fc1-4f3a-998f-713b80a6a5e1)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/long-travel-2/assets/88647733/2618ac02-b674-4395-b67f-0a344156a026)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
