### ISSUE TITLE
20170128_konotop in the trip "Конотоп", the standard block "Конотоп – Київ" does not have Name, Date and Country in search of the flag

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5269]
Pre-conditions:
Open: https://test.long-travel.live/travels/

Steps to reproduce:

Note that in the trip "Конотоп", the standard block "Конотоп – Київ" does not have Name, Date and Country in search of the flag

Actual result:
in the trip "Конотоп", the standard block "Конотоп – Київ" does not have Name, Date and Country in search of the flag
Expected result:
in the standard block must be the name - Road
in the standard block must be Date - 28.01.17
in the standard block must be Country in search of the flag - Ukraine

Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/741dfa01-4791-486d-b5b8-b6191877365a)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/df63bda6-9b68-40d7-bcde-db422df86900)

**Comment by Illia2810** [comment]
#5269

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
