### ISSUE TITLE
"20130613_0628_bulgaria" travel - Map - "Маршрут подорожі" block - "Savran' ", "Kyiv", and "Bolhrad" city names are written on English

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5271]
**Steps of reproducing**
1. Open https://test.long-travel.live/20130613_0628_bulgaria/
2. Scroll to map

**Actual Result**
"Savran' ", "Kyiv", and "Bolhrad" city names are written in English

**Expected Result**
"Savran' ", "Kyiv", and "Bolhrad" city names are written in Ukraine

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environments**
Windows 10, Chrome 123.0.6312.106 (64 bit)
![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 10 04 2024 14_50_06](https://github.com/scholokov/long-travel-2/assets/95171672/f53d13cb-bbb7-4dc1-b37b-9e30080c60ae)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
