### ISSUE TITLE
"20130613_0628_bulgaria" travel - Map - "Маршрут подорожі" block - "Bucharest", and "Slănic-Moldova" city names are written on English

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5272]
**Steps of reproducing**
1. Open https://test.long-travel.live/20130613_0628_bulgaria/
2. Scroll to map

**Actual Result**
"Bucharest", and "Slănic-Moldova" city names are written in English

**Expected Result**
"Bucharest", and "Slănic-Moldova" city names are written in Romanian

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environments**
Windows 10, Chrome 123.0.6312.106 (64 bit)
![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 10 04 2024 14_53_20](https://github.com/scholokov/long-travel-2/assets/95171672/f7e1e43c-5bac-40dd-b36d-955c69944867)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/long-travel-2/assets/88647733/26c5b009-c28d-4adc-8fad-839a7741924b)

**Comment by scholokov** [comment]
Сленік вродь як і так був на руминській
Бухарест - поправив

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
