### ISSUE TITLE
"20130613_0628_bulgaria" travel - Map - Name of the resort "Sunny Beach" is written in English

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5273]
**Steps of reproducing**
1. Open https://test.long-travel.live/20130613_0628_bulgaria/
2. Scroll to the Map
3. Pay attention to the "Маршрут подорожі" block

**Actual Result**
Name of the resort "Sunny Beach" is written in English

**Expected Result**
Name of the resort "Sunny Beach" is written in Ukrainian

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environments**
Windows 10, Chrome 123.0.6312.106  (64 bit)
![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 10 04 2024 15_04_40](https://github.com/scholokov/long-travel-2/assets/95171672/e0447087-551b-45a2-9020-9d6cbb4d93f4)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by scholokov** [comment]
але це назва самого пляжу, а не міста...

**Comment by DmitriiNasonov** [comment]
canceled
