### ISSUE TITLE
20130908_tropical_park/ The Drop down list with maps is displayed on the Map

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#5274]
Steps to reproduce:
1. Open page https://test.long-travel.live/20130908_tropical_park/
2. Pay attention to the Drop-down list with maps of the Travel on the Map

Actual Result: The Drop-down list with maps of the Travel on the Map is displayed on the Map

Expected Result: The Drop-down list with maps of the Travel on the Map is not displayed on the Map

Requirements: https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachment:

![image](https://github.com/scholokov/long-travel-2/assets/123776698/c202877d-cf33-4a0c-88e2-08ba59653fd5)

**Comment by ODrobik** [comment]
#5129

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
