### ISSUE TITLE
20170416_kiev_sof_plosha on the trip "Софійська Площа – Фестиваль писанок" a drop-down list is present from the map

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5276]
Pre-conditions:
Open: https://test.long-travel.live/20170416_kiev_sof_plosha/

Steps to reproduce:

Note that on the trip "Софійська Площа – Фестиваль писанок" a drop-down list is present from the map

Actual result:
on the trip "Софійська Площа – Фестиваль писанок" a drop-down list is present from the map
Expected result:
the drop-down list with cards should be absent

Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/9851dfe1-394b-4591-aad0-b9094f8874ae)

**Comment by Illia2810** [comment]
#5276

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
