### ISSUE TITLE
20150502_06_hungary / Some blocks "Header (Прев'ю)" have an Italian flag

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5277]
Steps to reproduce:

1. Open the page https://test.long-travel.live/20150502_06_hungary
2. Pay attention to the right side of the blocks "Header (Прев'ю)"

Actual result:

1. There is an Italian flag

Expected result:

1. On the right side of the block "Header (Прев'ю)" should be a Hungarian flag

Attachments:

![Image](https://github.com/scholokov/long-travel-2/assets/130754297/b6a5a4dd-1f56-4472-89f3-56d97cc11be9)

Documentation:
1.3.1.1 
[Requirements](https://github.com/scholokov/long-travel-2/blob/main/requirements/4.travel/struktura/standartnii-blok-i/README.md)

Environment:
Browser: Google Chrome 122.0.6261.129
OS: macOS 10.15.7

**Comment by Nanafox2010** [comment]
https://github.com/scholokov/long-travel-2/issues/5096

**Comment by scholokov** [comment]
fixed

**Comment by Nanafox2010** [comment]
verified
