### ISSUE TITLE
20170416_kiev_sof_plosha on the trip "Софійська Площа – Фестиваль писанок" flag sizes in standard blocks do not match 36*24 and 26*18

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5278]
Pre-conditions:
Open: https://test.long-travel.live/20170416_kiev_sof_plosha/

Steps to reproduce:

    Note that the sizes of the flag are not the same

Actual result:
the dimensions of the flag are not the same 36 24 and 26 18
Expected result:
the dimensions of the flag must be the same 36*24

Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=344-13&mode=design

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/a4e618bb-d8a0-4c16-80aa-a42174aceb92)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/f4d544d8-a8c4-45e0-9ade-00993abd693e)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/1c02f7fd-d5f6-4fa5-bc5e-6e4c25c8bcdf)

**Comment by Illia2810** [comment]
#5278

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
