### ISSUE TITLE
20170416_kiev_sof_plosha on the trip "Софійська Площа – Фестиваль писанок" all blocks of photo galleries - Random

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5279]
Pre-conditions:

Open: https://test.long-travel.live/20170416_kiev_sof_plosha/

Steps to reproduce:

Note that on the trip "Софійська Площа – Фестиваль писанок" all blocks of photo galleries - Random

Actual result:
on the trip "Софійська Площа – Фестиваль писанок" all blocks of photo galleries - Random
Expected result:
the photo gallery type should be - Mosaic
​
Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/60bd6ef5-2358-4414-b5ee-c899f509fc1a)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/3aecbf70-b23c-497c-b928-5165202a9a29)

**Comment by Illia2810** [comment]
#5279

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
