### ISSUE TITLE
20170416_kiev_sof_plosha in a trip "Софійська Площа – Фестиваль писанок", all blocks of photos are loaded simultaneously

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5280]
Pre-conditions:
Open: https://test.long-travel.live/20170416_kiev_sof_plosha/

Steps to reproduce:

Note that in a trip "Софійська Площа – Фестиваль писанок", all blocks of photos are loaded simultaneously

Actual result:
in a trip "Софійська Площа – Фестиваль писанок", all blocks of photos are loaded simultaneously
Expected result:
all subsequent galleries should NOT be loaded at once

Environment:
system: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/f61080a8-aae3-4f2e-a80e-d9eb20a9f2ad)

**Comment by Illia2810** [comment]
#5280

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
