### ISSUE TITLE
20070406_09_lviv/ Missed word "Дорога" in the Road Block "Львів - Київ"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5281]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20070406_09_lviv/ 
2. Scroll down to the Road block "Львів - Київ".
3. Pay attention to the absence of the word "Дорога".

**Actual result:**
Missed word "Дорога" in the Road Block "Львів - Київ".

**Expected result:**
The word "Дорога" is present on the 1st line of  the Road Block "Львів - Київ".

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/bb0b7979-42df-435e-8701-e4b5e7ea6301)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
