### ISSUE TITLE
20070722_0809_crimea/ Preview block date format is YYYY.MM.DD-MM.DD 

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5285]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20070722_0809_crimea/
2. Pay attention to the date format in the Preview block.

**Actual result:**
The date format is **YYYY.MM.DD-MM.DD (2007.07.22-08.09)** 

**Expected result:**
The date format is **DD.MM.YYYY - DD.MM.YYYY (22.07.2007 - 09.08.2007)**.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/prevyu-podorozhi

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/2ba95e83-b929-4743-8986-4a992c9d5d3a)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
