### ISSUE TITLE
20150523_picnic_dnipro / The Photo gallery type is Random

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5286]
Steps to reproduce:

1. Open the page https://test.long-travel.live/20150523_picnic_dnipro/
2. Pay attention to the type layout in the DevTools Elements

Actual result:

1. The Photo gallery type is Random

Expected result:

1. The Photo gallery type should be Mosaic

Attachments:
![Снимок экрана 2024-04-16 в 12 51 38](https://github.com/scholokov/long-travel-2/assets/130754297/5d563740-387e-4d6f-9297-90ba8a9352a2)

Documentation:
1.3.3.2.3 Тип фотогалереї повинен бути Mosaic
[Requirements](https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i)

Environment:
Browser: Google Chrome 123.0.6312.59
OS: macOS 10.15.7

**Comment by Nanafox2010** [comment]
https://github.com/scholokov/long-travel-2/issues/5096

**Comment by scholokov** [comment]
fxed

**Comment by Nanafox2010** [comment]
verified
