### ISSUE TITLE
20070722_0809_crimea/ Names of the city and the sights in the map's legend are in English and russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5288]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20070722_0809_crimea
2. Pay attention to the names of the city and the sights in the map's legend.

**Actual result:**
The names of the city and the sights in the map's legend are in English and russian.

**Expected result:**
The names of the city and the sights in the map's legend are in Ukrainian.

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Additional information:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/27fe4405-0649-4d28-92b0-f2d6d32e7868)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
