### ISSUE TITLE
20070722_0809_crimea/ The travel months and dates on the map's legend do not correspond to the dates in the Blocks

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5289]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20070722_0809_crimea
2. Scroll down to the Map of Travel.
3. Pay attention to the travel months and dates on the map's legend.

**Actual result:**
The travel months and dates on the map's legend do not correspond to the dates in the Blocks.

**Expected result:**
The travel months and dates on the map's legend correspond to the dates in the Blocks.

**Additional information:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/bbee57bf-fc0b-4faa-9010-d82abd4a6bb7)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed

**Comment by GNatala** [comment]
passed
