### ISSUE TITLE
"20130613_0628_bulgaria" travel - Map - Travels drop-down list is present

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5297]
**Steps of reproducing**
1. Open https://test.long-travel.live/20130613_0628_bulgaria/
2. Scroll to Map

**Actual Result**
Travels drop-down list is present

**Expected Result**
Travels drop-down list is missing

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environments**
Windows 10, Chrome 124.0.6367.61 (64 bit)
![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 17 04 2024 17_32_25](https://github.com/scholokov/long-travel-2/assets/95171672/b6aa7b83-1987-457e-bc6e-6d2bf71e03b7)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
