### ISSUE TITLE
"20130613_0628_bulgaria" travel - Map - "Маршрут подорожі" block - Preview photo is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5299]
**Steps of reproducing**
1. Open https://test.long-travel.live/20130613_0628_bulgaria/
2. Scroll to Map

**Actual Result**
Preview photo is missing

**Expected Result**
Preview photo is present

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environments**
Windows 10, Chrome 124.0.6367.61 (64 bit)

![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 17 04 2024 17_46_36](https://github.com/scholokov/long-travel-2/assets/95171672/5941600a-0f36-488c-bc1b-784f4ba8a6e2)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
