### ISSUE TITLE
20170417_kiylov no date in the preview of the trip "Заповідник “Кийлівська Асканія”", it is under the preview photo

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5301]
Pre-conditions:
Open: https://test.long-travel.live/20170417_kiylov/

Steps to reproduce:

Note that no date in the preview of the trip "Заповідник “Кийлівська Асканія”", it is under the preview photo

Actual result:
no date in the preview of the trip "Заповідник “Кийлівська Асканія”", it is under the preview photo
Expected result:
the date should be in the preview

Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/prevyu-podorozhi

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/4c3fea8e-d5d8-4d4d-af61-e890879862a8)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/71c61034-687f-4749-96c0-304c5d6a0341)

**Comment by Illia2810** [comment]
#5301

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
