### ISSUE TITLE
20170417_kiylov on the trip "Заповідник “Кийлівська Асканія”"" a drop-down list is present from the map 

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5303]
Pre-conditions:
Open: https://test.long-travel.live/20170417_kiylov/

Steps to reproduce:

Note that on the trip "Заповідник “Кийлівська Асканія”"" a drop-down list is present from the map 

Actual result:
on the trip "Заповідник “Кийлівська Асканія"" a drop-down list is present from the map 
Expected result:
the drop-down list with cards should be absent

Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/f0e748a0-d49d-43ea-89be-4fc624bb6642)

**Comment by Illia2810** [comment]
#5303

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified

**Comment by Illia2810** [comment]
verified
