### ISSUE TITLE
"20130613_0628_bulgaria" travel - Part of the standards blocks (Indicated in the "Additional information" block) - Standard block preview is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5305]
**Steps of reproducing**
1. Open https://test.long-travel.live/20130613_0628_bulgaria/
2. Scroll to standards blocks

**Actual Result**
Standard block preview is missing

**Expected Result**
Standard block preview is present

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i
List of the standard blocks with this bug: 
1. Готель Інзов, Болград, Одеська область, Україн
2. Aparthotel Excelsior, Sunny Beach, Bulgaria
3. Beach, Sunny Beach, Bulgaria
4. Water-pool, Sunny Beach, Bulgaria
5. Sunny Beach, Bulgaria
6. Presents, Sunny Beach, Bulgaria
7. Дорога: Sunny Beach, Bulgaria – Bucharest, Romania
8. Hotel, Bucharest, Romania
9. Bucharest, Romania
10. Дорога: Bucharest, Romania – Slanic-Moldova, Romania
11. Hotel Vila Teleconstructia, Slanic-Moldova, Romania
12. Slanic-Moldova, Romania
13. Дорога: Slanic-Moldova, Romania – Кишенів, Молдова – Придністров’я – Саврань, Україна
14. Готель Чорне Море, Саврань, Одеська область, Україна
15. Дорога: Саврань, Україна – Київ, Україна

**Environments**
Windows 10, Chrome 124.0.6367.61 (64 bit)
![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 19 04 2024 19_29_12](https://github.com/scholokov/long-travel-2/assets/95171672/378f38ea-eb5b-435a-a283-1e4d6220fa40)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is fixed partly. Created new bug-reprort
