### ISSUE TITLE
"20130613_0628_bulgaria" travel - Part of the standards blocks (Indicated in the "Additional information" block) - Time period type is "DD-DD.MM.YYYY"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5306]
**Steps of reproducing**
1. Open https://test.long-travel.live/20130613_0628_bulgaria/
2. Scroll to standards blocks

**Actual Result**
Time period type is "DD-DD.MM.YYYY"

**Expected Result**
Time period type is "DD.MM.YYYY-DD.MM.YYYY"

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i
List of the standard blocks with this bug: 
1. Готель Інзов, Болград, Одеська область, Україн
2. Aparthotel Excelsior, Sunny Beach, Bulgaria
3. Beach, Sunny Beach, Bulgaria
4. Water-pool, Sunny Beach, Bulgaria
5. Sunny Beach, Bulgaria
6. Presents, Sunny Beach, Bulgaria
7. Hotel, Bucharest, Romania
8. Bucharest, Romania
9. Hotel Vila Teleconstructia, Slanic-Moldova, Romania
10. Slanic-Moldova, Romania
11. Готель Чорне Море, Саврань, Одеська область, Україна

**Environments**
Windows 10, Chrome 124.0.6367.61 (64 bit)
![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 19 04 2024 19_54_17](https://github.com/scholokov/long-travel-2/assets/95171672/52d6dff3-ac28-4230-9838-5ac4fef043de)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is reproducing
![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 01 05 2024 13_22_49](https://github.com/scholokov/long-travel-2/assets/95171672/adb8e460-23c4-41bc-9fa7-b57ae3195c45)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug fixed partly. Created new bug-report
