### ISSUE TITLE
"20130613_0628_bulgaria" travel - All standards blocks - Flags are missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5307]
**Steps of reproducing**
1. Open https://test.long-travel.live/20130613_0628_bulgaria/
2. Scroll to standards blocks

**Actual Result**
Flags are missing

**Expected Result**
Flags are present

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-6&mode=design&t=2grIsKwoHgmFQJLJ-0

**Environments**
Windows 10, Chrome 124.0.6367.61 (64 bit)
![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 20 04 2024 15_14_17](https://github.com/scholokov/long-travel-2/assets/95171672/a7098e1d-2239-421c-82e2-36270b3cffe8)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is fixed partly. Created bug-reprort
