### ISSUE TITLE
"20130613_0628_bulgaria" travel - "Travel time" block is duplicated

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5310]
**Steps of reproducing**
1. Open https://test.long-travel.live/20130613_0628_bulgaria/
2. Scroll to standards blocks

**Actual Result**
"Travel time" block is duplicated

**Expected Result**
"Travel time" block isn't duplicated

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/prevyu-podorozhi

**Environments**
Windows 10, Chrome 124.0.6367.61 (64 bit)
![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 20 04 2024 16_09_57](https://github.com/scholokov/long-travel-2/assets/95171672/7ea4bf98-39f7-4e70-a948-f8335dae75b7)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
