### ISSUE TITLE
20070722_0809_crimea/ All photo galleries load immediately

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5311]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20070722_0809_crimea
2. Pay attention that photo galleries load immediately.

**Actual result:**
All photo galleries load immediately.

**Expected result:**
Only the first photo galleries load immediately. The button "Відобразити галерею" appears in all galleries starting from the second one.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

**Environment:**
**Lambdatest**
Windows 10,
Google Chrome v 123

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/ddb4ea37-903d-44a6-a0bb-8d5c52c2b1b4)

![image](https://github.com/scholokov/long-travel-2/assets/101987790/2a3afffc-546a-4e2c-ba28-797b3116c76b)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
The issue is reproduced.

**Attachment**:
![image](https://github.com/scholokov/long-travel-2/assets/101987790/7b24348c-c027-4481-aa48-402334b39a78)
![image](https://github.com/scholokov/long-travel-2/assets/101987790/b306c9a9-00e4-43c3-8f5f-58f857929e1c)

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
пофікшено частково, на нову проблему заведено баг #5418
