### ISSUE TITLE
20070722_0809_crimea/ Missed format of the Road Block "Киев - Рыбачье"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5313]
**Steps to reproduce:**

1. Open  https://test.long-travel.live/20070722_0809_crimea/
2. Scroll down to the Road block "Киев - Рыбачье 22.07.2007".
3. Pay attention to the format of the Road Block.

**Actual result:**
 Missed format of the Road Block: "Киев - Рыбачье 22.07.2007".

**Expected result:**
Format of the Road Block: 
**Дорога 
Київ - Рибаче
22.07.2007**

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i/tipi-standartnikh-blokiv

**Environment:**
Windows 7,
Google Chrome v 108.0.5359.125 (x64)

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/c02a70c3-b434-49bc-a600-9ed6ec3b575c)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
шось по моему тут наплутано....

**Comment by GNatala** [comment]
Дякую, змінила

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
