### ISSUE TITLE
Retest: Testing Home page using HTML & CSS Validators

### ISSUE THREAD

**Issue by ABatalov** [scholokov/long-travel-2#5317]
- [ ] Perform testing using HTML validator

- [ ] Perform testing using CSS validator

- [ ] Create two bugs (for the results of the check by each validator)

- [ ] Make a report according to the template below

**Template** 

| ID Дефекту | Назва | Валідатор | Статус | Автор 
| --- | --- | --- | --- | ---
| #4672 | 20191012_14_dnipro_В "Маршруті подорожі" блоку "Мапа" не відображається назва готелю | CSS Валідатор | Done | DmitriiNasonov 
| #4672 | 20191012_14_dnipro_В "Маршруті подорожі" блоку "Мапа" не відображається назва готелю | HTML Валідатор | Done | DmitriiNasonov  

Useful links 

| Назва | Посилання
| --- | ---
| LambdaTest & BrowserStack | [Посилання](https://www.qax-camp.com.ua/lessons/validators/)

**Comment by ODrobik** [comment]
verified
