### ISSUE TITLE
20150623_0711_croatia / On the Preview block, the flags have the wrong margin

### ISSUE THREAD

**Issue by Nanafox2010** [scholokov/long-travel-2#5326]
Steps to reproduce:

1. Open the page https://test.long-travel.live/20150623_0711_croatia/
2. Open the Elements Styles in the DevTools
3. Pay attention to the margin

Actual result:

1. Each flag has a margin: 
    margin-top: 0px;
    margin-right:  0px;
    margin-left: 10px;
    margin-bottom: 10px;
Expected result:

1. Each flag should have a margin: 
    margin-top: 8px;
    margin-right:  2px;
    margin-left: 8px;
    margin-bottom: 2px;

Attachments:
![Снимок экрана 2024-04-25 в 14 44 53](https://github.com/scholokov/long-travel-2/assets/130754297/5edae7e4-bacf-4554-a6ba-829dbb23c5ce)
![Снимок экрана 2024-04-25 в 14 43 44](https://github.com/scholokov/long-travel-2/assets/130754297/f9e5df32-2be0-4969-8dd5-5932241d2cf8)

Documentation:
[Figma](https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=3053-42&mode=design&t=iDxSFEnHfxXCD7TH-4)

Environment:
Browser: Google Chrome 123.0.6312.59
OS: macOS 10.15.7

**Comment by Nanafox2010** [comment]
#5096

**Comment by scholokov** [comment]
у даному контксті важливі саме фізичні розміри прапорця. так як ніяких об'єктів поруч не має, то марджини для нас будуть не важливі

**Comment by Nanafox2010** [comment]
verified
