### ISSUE TITLE
20170417_kiylov points of interest are not combined with the main point by a dotted line

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5338]
Pre-conditions:
Open: https://test.long-travel.live/20170417_kiylov/

Steps to reproduce:

Note that points of interest are not combined with the main point by a dotted line

Actual result:
points of interest are not combined with the main point by a dotted line
Expected result:
Points of interest are combined with the main point with a dotted line

Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

Attachment:
https://jam.dev/c/a1768d83-4612-465f-8b8a-f522b8858909
![image](https://github.com/scholokov/long-travel-2/assets/125801673/4f8c3046-b9bc-4e58-a5dc-64e7a157471f)

**Comment by Illia2810** [comment]
#5239

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/scholokov/long-travel-2/assets/88647733/caf632e5-4ce2-42dd-bf24-4e33e95ff43c)

**Comment by Illia2810** [comment]
виправлено

**Comment by scholokov** [comment]
не зрозуміло про що річ

**Comment by Illia2810** [comment]
виправлено

**Comment by scholokov** [comment]
у кроках ви пишете про дату, у експекті вже про крапки.... напишіть в чому саме проблема :)

**Comment by Illia2810** [comment]
виправлено

**Comment by scholokov** [comment]
ви пишете що точка має бути з'єдната крапковою лінією. але ж вона лежить на прямій... не зрозуміло тоді в чому саме проблема....

**Comment by Illia2810** [comment]
не э помилкою
