### ISSUE TITLE
"20130613_0628_bulgaria" travel - Part of the standards blocks (Indicated in the "Additional information" block) - Standard block preview is missing (Additional bug-report)

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5340]
**Steps of reproducing**
1. Open https://test.long-travel.live/20130613_0628_bulgaria/
2. Scroll to standards blocks

**Actual Result**
Standard block preview is missing

**Expected Result**
Standard block preview is present

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i
List of the standard blocks with this bug: 
1. Aparthotel Excelsior, Sunny Beach, Bulgaria
2. Beach, Sunny Beach, Bulgaria
3. Water-pool, Sunny Beach, Bulgaria
4. Sunny Beach, Bulgaria
5. Presents, Sunny Beach, Bulgaria
6. Дорога: Sunny Beach, Bulgaria – Bucharest, Romania
7. Hotel, Bucharest, Romania
8. Bucharest, Romania
9. Дорога: Bucharest, Romania – Slanic-Moldova, Romania
10. Hotel Vila Teleconstructia, Slanic-Moldova, Romania
11. Slanic-Moldova, Romania
12. Дорога: Slanic-Moldova, Romania – Кишенів, Молдова – Придністров’я – Саврань, Україна
13. Готель Чорне Море, Саврань, Одеська область, Україна
14. Дорога: Саврань, Україна – Київ, Україна

**Environments**
Windows 10, Chrome 124.0.6367.61 (64 bit)
![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 01 05 2024 13_14_00](https://github.com/scholokov/long-travel-2/assets/95171672/1a937223-335e-46aa-8e40-c0e0ba6b2ceb)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by DmitriiNasonov** [comment]
#5305

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
