### ISSUE TITLE
"20130613_0628_bulgaria" travel - All standards blocks (without "Готель Інзов, Болград, Одеська область, Україна" standard block) - Flags are missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5342]
**Steps of reproducing**
1. Open https://test.long-travel.live/20130613_0628_bulgaria/
2. Scroll to standards blocks (without "Готель Інзов, Болград, Одеська область, Україна" standard block)

**Actual Result**
Flags are missing

**Expected Result**
Flags are present

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=986-6&mode=design&t=2grIsKwoHgmFQJLJ-0

**Environments**
Windows 10, Chrome 124.0.6367.61 (64 bit)
![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 01 05 2024 13_35_02](https://github.com/scholokov/long-travel-2/assets/95171672/7599efb8-b170-4307-bb3f-851588775b15)
![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 01 05 2024 13_35_12](https://github.com/scholokov/long-travel-2/assets/95171672/4e52552a-b886-4069-a17a-1802dcaf3dad)
![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 01 05 2024 13_35_15](https://github.com/scholokov/long-travel-2/assets/95171672/003b5760-62d1-4639-a691-dfe698c45e2e)
![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 01 05 2024 13_35_19](https://github.com/scholokov/long-travel-2/assets/95171672/3773699b-3bda-4897-9f34-4fd421810428)
![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 01 05 2024 13_35_22](https://github.com/scholokov/long-travel-2/assets/95171672/295c08dd-ca1f-41b4-bed4-c1584f5004b9)
![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 01 05 2024 13_35_30](https://github.com/scholokov/long-travel-2/assets/95171672/abff75c1-fdb6-4e4d-86fb-574cb465a5e2)
![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 01 05 2024 13_35_37](https://github.com/scholokov/long-travel-2/assets/95171672/10789f4d-538e-425b-a5fd-819737721adc)
![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 01 05 2024 13_35_46](https://github.com/scholokov/long-travel-2/assets/95171672/37c6a366-017f-445c-ae88-e48f76a8ab11)
![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 01 05 2024 13_35_50](https://github.com/scholokov/long-travel-2/assets/95171672/d306b22e-5549-4af5-b6b5-264cc0b0fd30)
![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 01 05 2024 13_35_53](https://github.com/scholokov/long-travel-2/assets/95171672/13f8e34a-ab0c-41cc-8362-adb7c6d27fbb)
![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 01 05 2024 13_35_57](https://github.com/scholokov/long-travel-2/assets/95171672/15ef12db-aa91-4789-a502-0078d9b82d0e)
![Болград – Слънчев бряг – București – Саврань – Long-Travel - Google Chrome 01 05 2024 13_36_02](https://github.com/scholokov/long-travel-2/assets/95171672/37f67fcd-040a-49a9-9360-3ce0124a3d94)

**Comment by DmitriiNasonov** [comment]
#5307

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug is fixed partly. Created new bug-reprort
