### ISSUE TITLE
"20130721_vitachev" travel - Map - "Маршрут подорожі" block - "Vitachov" travel point type is "Пам'ятка"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5343]
**Steps of reproducing**
1. Open https://test.long-travel.live/20130721_vitachev/
2. Scroll to map

**Actual Result**
"Vitachov" travel point type is "Пам'ятка"

**Expected Result**
"Vitachov" travel point type is "Intermediate point"

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environments**
Windows 10, Chrome 124.0.6367.119 (64 bit)
![Витачів – Long-Travel - Google Chrome 01 05 2024 14_59_05](https://github.com/scholokov/long-travel-2/assets/95171672/9b0245cd-7326-4d1c-ac93-553680122c9b)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
