### ISSUE TITLE
"20130721_vitachev" travel - Map - "Маршрут подорожі" block - "City" travel points name is written on English

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5344]
**Steps of reproducing**
1. Open https://test.long-travel.live/20130721_vitachev/
2. Scroll to map

**Actual Result**
"City" travel points name is written in English

**Expected Result**
"City" travel points name is written in Ukrainian

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environments**
Windows 10, Chrome 124.0.6367.119 (64 bit)
![Витачів – Long-Travel - Google Chrome 01 05 2024 15_05_09](https://github.com/scholokov/long-travel-2/assets/95171672/832f6f38-5c96-4f99-a7c9-be7a4f776763)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
