### ISSUE TITLE
"20130721_vitachev" travel - Map - Travels dropdown list is present

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5345]
**Steps of reproducing**
1. Open https://test.long-travel.live/20130721_vitachev/
2. Scroll to map

**Actual Result**
Travels dropdown list is present

**Expected Result**
Travels dropdown list is missing

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environments**
Windows 10, Chrome 124.0.6367.119 (64 bit)
![Витачів – Long-Travel - Google Chrome 01 05 2024 15_14_52](https://github.com/scholokov/long-travel-2/assets/95171672/646b0c4b-5dbd-4400-87cb-3d6d50902ec9)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
