### ISSUE TITLE
"20130721_vitachev" travel - Map - "Маршрут подорожі" block - Photo preview is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5347]
**Steps of reproducing**
1. Open https://test.long-travel.live/20130721_vitachev/
2. Scroll to map

**Actual Result**
Photo preview is missing

**Expected Result**
Photo preview is present

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environments**
Windows 10, Chrome 124.0.6367.119 (64 bit)
![Витачів – Long-Travel - Google Chrome 01 05 2024 15_27_50](https://github.com/scholokov/long-travel-2/assets/95171672/131e42fb-8077-4089-9f60-7d302215a4dc)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
