### ISSUE TITLE
"20130721_vitachev" travel - Header of the standard block is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5348]
**Steps of reproducing**
1. Open https://test.long-travel.live/20130721_vitachev/

**Actual Result**
Header of the standard block is missing

**Expected Result**
Header of the standard block is present

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environments**
Windows 10, Chrome 124.0.6367.119 (64 bit)
![Витачів – Long-Travel - Google Chrome 01 05 2024 15_34_54](https://github.com/scholokov/long-travel-2/assets/95171672/3e5e93b8-7ffc-4b62-bfb9-fb5620ec7c68)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
