### ISSUE TITLE
"20130721_vitachev" travel - Travel name and time period is duplicated

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5349]
**Steps of reproducing**
1. Open https://test.long-travel.live/20130721_vitachev/

**Actual Result**
Travel name and time period are duplicated

**Expected Result**
Travel name and time period aren't duplicated

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Environments**
Windows 10, Chrome 124.0.6367.119 (64 bit)
![Витачів – Long-Travel - Google Chrome 01 05 2024 15_47_42](https://github.com/scholokov/long-travel-2/assets/95171672/5b756390-34ef-4f14-803d-250d83221630)

**Comment by DmitriiNasonov** [comment]
#5128

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
