### ISSUE TITLE
20170521_korosten/ the title of the video is written in Russian "Киев"

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5358]
Steps to reproduce:

  1. Open https://test.long-travel.live/20170521_korosten/
  2. Open the Legend of the Map.
  3. Pay attention the title of the video is written in Russian "Киев"

Actual Result:
the title of the video is written in Russian "Киев"

Expected Result:
the title of the video is only in Ukrainian

Environment:
Lambdatest,
Mobile,
System: Windows 10 Pro
Browser: FireFox

Additional information:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/4973856a-9fc1-418d-b20e-893db348516a)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/957de57a-0afb-444c-a4c0-2cc476640601)

**Comment by Illia2810** [comment]
#5314

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
