### ISSUE TITLE
20170605_kiev_mariinskiy/ the drop-down list on the map of the trip "Хрещатик – Маріїнський парк" is present 

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5360]
Steps to reproduce:

  1. Open https://test.long-travel.live/20170605_kiev_mariinskiy/
  2. Pay attention to the presence drop-down list on the map

Actual Result:
the drop-down list on the map of the trip "Хрещатик – Маріїнський парк" is present 
Expected Result:
the drop-down list on the map of the trip "Хрещатик – Маріїнський парк" is absent

Environment:
Lambdatest - Desktop,
System: Windows 10 Pro
Browser: FireFox

Additional information:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/d90d51a5-920b-4ce9-8f0b-f284ff2c89d2)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/614d9cba-e06f-4d54-aec2-438c064cbb57)

**Comment by Illia2810** [comment]
#5315

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
