### ISSUE TITLE
"Хрещатик – Маріїнський парк" travel - Map - Travels dropdown list is present

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5363]
**Steps of reproducing**
1. Open https://test.long-travel.live/20170605_kiev_mariinskiy/ on the LambdaTest
2. Scroll to "Map" block

**Actual Result**
Travels dropdown list is present

**Expected Result**
Travels dropdown list is missing

**Additional information**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa
**Used LambdaTest Emulator:**
macOS Sonoma, Chrome 125, Screen size is 1440x900 pixels
AND
Galaxy S24 Ultra, Chrome 113.0.5672.136

**Environments**
Windows 10, Chrome 124.0.6367.156 (64 bit)

![Realtime Browser Viewer - Google Chrome 08 05 2024 18_07_09](https://github.com/scholokov/long-travel-2/assets/95171672/828b7722-1bd6-4963-a700-bdb31c5332ab)
![Realtime Browser Viewer - Google Chrome 08 05 2024 18_16_30](https://github.com/scholokov/long-travel-2/assets/95171672/8a828f90-97eb-4bcc-be50-479985b765b8)

**Comment by DmitriiNasonov** [comment]
#5314

**Comment by DmitriiNasonov** [comment]
#5315

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
