### ISSUE TITLE
20200627_29_yuzhniy - Южне – Вінниця - in the review tag are missing

### ISSUE THREAD

**Issue by Myroslava2** [scholokov/long-travel-2#5400]
Steps to reproduce:

    1. Open the page "Южне – Вінниця" https://test.long-travel.live/20200627_29_yuzhniy/

Actual result:

     1. Tags are present: автомобіль, пляж, цікаві місця

Expected result:

     1. Tags are present: автомобіль, пляж, цікаво

Attachments:

![1](https://github.com/scholokov/long-travel-2/assets/158490558/4cda3e82-bbac-4f04-9c03-cd9d495911d3)

Environment:
Windows 10 (x64)
Firefox Browser 126.0 (64)

**Comment by scholokov** [comment]
третій тег - тож "цікаво". у вимогах саме 3 теги...
