### ISSUE TITLE
20200627_29_yuzhniy - Южне – Вінниця - Landmarks on the map in the form of cities

### ISSUE THREAD

**Issue by Myroslava2** [scholokov/long-travel-2#5401]
Steps to reproduce:

    1. Open the page "Южне – Вінниця" https://test.long-travel.live/20200627_29_yuzhniy/
    2. Scroll down to the TravelMap

Actual result:

    1. The landmark is indicated as a city

Expected result:

    1. The landmark is indicated as an object of visit

Attachments:

![2](https://github.com/scholokov/long-travel-2/assets/158490558/cb9c33fa-e356-4841-9317-cf7e5965c788)

Environment:
Windows 10 (x64)
Firefox Browser 126.0 (64)

**Comment by scholokov** [comment]
fixed
