### ISSUE TITLE
20200627_29_yuzhniy - Южне – Вінниця - The names of cities belonging to Ukraine written in English

### ISSUE THREAD

**Issue by Myroslava2** [scholokov/long-travel-2#5403]
Steps to reproduce:

    1. Open the page "Южне – Вінниця" https://test.long-travel.live/20200627_29_yuzhniy/
    2. Scroll down to the TravelMap

Actual result:

    1. The cities Вінниця and Южне in English

Expected result:

    1. The cities Вінниця and Южне in Ukrainian

Attachments:

![4](https://github.com/scholokov/long-travel-2/assets/158490558/5d79999b-c736-4d2a-bf78-eb8dfac64345)

Environment:
Windows 10 (x64)
Firefox Browser 126.0 (64)

**Comment by scholokov** [comment]
fixed
