### ISSUE TITLE
20200627_29_yuzhniy - Южне – Вінниця - The arrival date at the last point doesn't match the travel end date

### ISSUE THREAD

**Issue by Myroslava2** [scholokov/long-travel-2#5404]
Steps to reproduce:

    1. Open the page "Южне – Вінниця" https://test.long-travel.live/20200627_29_yuzhniy/
    2. Scroll down to the TravelMap

Actual result:

    1. The travel end date is 08.07.2020

Expected result:

    1. The travel end date is 29.06.2020

Attachments:

![5](https://github.com/scholokov/long-travel-2/assets/158490558/80b98924-e17a-4cd3-abeb-7ff47e818094)

Environment:
Windows 10 (x64)
Firefox Browser 126.0 (64)

**Comment by scholokov** [comment]
fixed
