### ISSUE TITLE
20200627_29_yuzhniy - Южне – Вінниця - The list on the map is displayed

### ISSUE THREAD

**Issue by Myroslava2** [scholokov/long-travel-2#5406]
Steps to reproduce:

    1. Open the page "Южне – Вінниця" https://test.long-travel.live/20200627_29_yuzhniy/
    2. Scroll down to the TravelMap

Actual result:

    1. The list on the map is present

Expected result:

    1. The list on the map is not present

Attachments:

![7](https://github.com/scholokov/long-travel-2/assets/158490558/c81010b6-2485-4ad7-86b4-d25282ca4005)

Environment:
Windows 10 (x64)
Firefox Browser 126.0 (64)

**Comment by scholokov** [comment]
fixed
