### ISSUE TITLE
20200627_29_yuzhniy - Южне – Вінниця - The image in Header is not present

### ISSUE THREAD

**Issue by Myroslava2** [scholokov/long-travel-2#5407]
Steps to reproduce:

    1. Open the page "Южне – Вінниця" https://test.long-travel.live/20200627_29_yuzhniy/
    2. Scroll down to the Header

Actual result:

    1. The preview photo is missing

Expected result:

    1. The preview photo is present

Attachments:

![8](https://github.com/scholokov/long-travel-2/assets/158490558/e52c4a48-5907-4803-9855-aa9ea31a4bb1)

Environment:
Windows 10 (x64)
Firefox Browser 126.0 (64)

**Comment by scholokov** [comment]
fixed
