### ISSUE TITLE
20200627_29_yuzhniy - Южне – Вінниця - The city in Header is not present

### ISSUE THREAD

**Issue by Myroslava2** [scholokov/long-travel-2#5408]
Steps to reproduce:

    1. Open the page "Южне – Вінниця" https://test.long-travel.live/20200627_29_yuzhniy/
    2. Scroll down to the Header

Actual result:

    1. The city of Южне is missing

Expected result:

    1. The city of Южне is present

Attachments:

![9](https://github.com/scholokov/long-travel-2/assets/158490558/0f9c159e-853c-45e0-89b0-3b162c491ee4)

Environment:
Windows 10 (x64)
Firefox Browser 126.0 (64)

**Comment by scholokov** [comment]
fixed
