### ISSUE TITLE
20200627_29_yuzhniy - Южне – Вінниця - The gallery doesn't employ Lazy Loading

### ISSUE THREAD

**Issue by Myroslava2** [scholokov/long-travel-2#5409]
Steps to reproduce:

    1. Open the page "Южне – Вінниця" https://test.long-travel.live/20200627_29_yuzhniy/
    2. Scroll down to the gallery

Actual result:

    1. The photos have fast loading

Expected result:

    1. The photos have lazy loading

Attachments:

![10](https://github.com/scholokov/long-travel-2/assets/158490558/202c14f3-f44e-4902-9dea-df0eabba0e54)

Environment:
Windows 10 (x64)
Firefox Browser 126.0 (64)

**Comment by scholokov** [comment]
fixed
