### ISSUE TITLE
20200627_29_yuzhniy - Южне – Вінниця - The galleries have the shape of a random layout

### ISSUE THREAD

**Issue by Myroslava2** [scholokov/long-travel-2#5410]
Steps to reproduce:

    1. Open the page "Южне – Вінниця" https://test.long-travel.live/20200627_29_yuzhniy/
    2. Scroll down to the gallery

Actual result:

    1. The galleries have a random layout

Expected result:

    1. The galleries have a mosaic layout

Attachments:

![11](https://github.com/scholokov/long-travel-2/assets/158490558/b264f83e-0f73-4a93-a55b-fcb9584aa1a0)

Environment:
Windows 10 (x64)
Firefox Browser 126.0 (64)

**Comment by scholokov** [comment]
fixed
