### ISSUE TITLE
20200627_29_yuzhniy - Южне – Вінниця - The "Відкрити галерею" button is not displaying

### ISSUE THREAD

**Issue by Myroslava2** [scholokov/long-travel-2#5411]
Steps to reproduce:

    1. Open the page "Южне – Вінниця" https://test.long-travel.live/20200627_29_yuzhniy/
    2. Scroll down to the gallery

Actual result:

    1. The "Відкрити галерею" button is missing

Expected result:

    1. The "Відкрити галерею" button is present

Attachments:

![12](https://github.com/scholokov/long-travel-2/assets/158490558/8ef55f65-5625-4555-ac49-26279f24aa08)

Environment:
Windows 10 (x64)
Firefox Browser 126.0 (64)

**Comment by scholokov** [comment]
fixed
