### ISSUE TITLE
20200627_29_yuzhniy - Южне – Вінниця - Title of the video not in Ukrainian

### ISSUE THREAD

**Issue by Myroslava2** [scholokov/long-travel-2#5412]
Steps to reproduce:

    1. Open the page "Южне – Вінниця" https://test.long-travel.live/20200627_29_yuzhniy/
    2. Scroll down to the video

Actual result:

    1. Title of the video in Russian

Expected result:

    1. Title of the video in Ukrainian

Attachments:

![13](https://github.com/scholokov/long-travel-2/assets/158490558/e62cb93d-c197-49b4-a6d4-12cbbb66184b)

Environment:
Windows 10 (x64)
Firefox Browser 126.0 (64)

**Comment by scholokov** [comment]
fixed
