### ISSUE TITLE
Home page - Functional testing - Web missing letter in the word  "фоматі"

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5413]
Pre-conditions:
Open: https://test.long-travel.live/

Steps to reproduce:

Note that missing letter in the word  "фоматі"

Actual result:
missing letter in the word  "фоматі"
Expected result:
correct word "фо**_р_**маті"

Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/home

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/8d110472-38a8-4056-8b77-c53600efb1ee)

**Comment by Illia2810** [comment]
#5386

**Comment by Illia2810** [comment]
#5387

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
