### ISSUE TITLE
20070722_0809_crimea/ The first photo gallery does not load immediately

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5418]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20070722_0809_crimea
2. Pay attention first photo gallery.

**Actual result:**
The first photo gallery does not load immediately.

**Expected result:**
The first photo galleries load immediately. The button "Відобразити галерею" does not appear in the gallery.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

**Environment:**

Windows 10,
Google Chrome v 125

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/adb4eb57-1b26-450f-99e7-6a962ffccbc8)
![image](https://github.com/scholokov/long-travel-2/assets/101987790/8a05f4b8-afb9-44d0-8d2a-f316946db367)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
