### ISSUE TITLE
Testing page "Цікаві місця" Web and Mob - blocks are not in alphabetical order of names

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5422]
Pre-conditions:
https://test.long-travel.live/places/

Steps to reproduce:

Note that blocks are not in alphabetical order of names

Actual result:
blocks are not in alphabetical order of names
Expected result:
blocks should be arranged in alphabetical order of names
​
Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/placesс 5.2

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/147203fa-5395-4766-b29c-b46c943ea005)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/c7495f4d-518e-4ca0-bf4a-448a25732340)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/6fcc98b6-ada9-43aa-91fc-cce0b86962f4)

**Comment by Illia2810** [comment]
#5388

**Comment by Illia2810** [comment]
#5390

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
Створено новий схожий баг #5430
