### ISSUE TITLE
Testing page "Цікаві місця" Web and Mob - all galleries are loaded at once

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5423]
Pre-conditions:
https://test.long-travel.live/places/

Steps to reproduce:
Open https://test.long-travel.live/museum/
Note that all galleries are loaded at once

Actual result:
all galleries are loaded at once
Expected result:
gallery blocks after the first block should be loaded when the button is clicked  "Відобразити галерею"
Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/places 5.7

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/19058600-0341-4f70-bfce-513ad47a2beb)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/9d9a8290-9b28-4203-ad5d-bc5fdc4f4e8c)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/fa604ac7-8e47-418c-bec0-1035bb017577)

**Comment by Illia2810** [comment]
#5388

**Comment by Illia2810** [comment]
#5390

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
створив новий схожий баг #5432
