### ISSUE TITLE
Testing page "Цікаві місця" Web and Mob - sorting of standard blocks does not meet the requirements

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5424]
Pre-conditions:
https://test.long-travel.live/places/

Steps to reproduce:
Open https://test.long-travel.live/museum/
Note that sorting of standard blocks does not meet the requirements

Actual result:
sorting of standard blocks does not meet the requirements
Expected result:
standard blocks should be sorted by time (newest on top)

Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/places 5.8

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/1eea5821-10f0-4f53-bd69-0c1194735b2e)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/61a36e44-306c-4593-8a69-206ae6bafc7d)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/1856f173-a21e-48cb-8f4d-df1b7543dbec)

**Comment by Illia2810** [comment]
#5390

**Comment by Illia2810** [comment]
#5388

**Comment by scholokov** [comment]
fxd

**Comment by Illia2810** [comment]
verified
