### ISSUE TITLE
Home page - Functional testing Web/Mob - The author's introduction lacks photos

### ISSUE THREAD

**Issue by Myroslava2** [scholokov/long-travel-2#5427]
Steps to reproduce:

    1. Open the Home page https://test.long-travel.live/

Actual result:

     1. Photos are absent 

Expected result:

     1. Photos are present 

Attachments:

![1](https://github.com/scholokov/long-travel-2/assets/158490558/56cafa76-7654-4c04-a4f3-23e51939e528)

Environment:
Windows 10 (x64)
Firefox Browser 126.0.1 (64)
Samsung Galaxy A35

**Comment by poroskundenys** [comment]
Готово

**Comment by Myroslava2** [comment]
fixed
