### ISSUE TITLE
20170521_korosten/ "Древлянский парк" way point is displayed on the Map block

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#5428]
Steps to reproduce:

1. Open page https://test.long-travel.live/20170521_korosten/
2. Scroll down to the Legend of the Map
3. Pay attention to the "Древлянский" way point on the Map

Actual Result:
"Древлянский парк" way point is displayed on the Map block in russian language

Expected Result:
"Древлянський парк"  way point is displayed on the Map block in Ukrainian language

**Requirements:**https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapaa

Environment:
Lambdatest
Mobile
Samsung A51, Android 10.0

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/123776698/64a4bd33-3bd9-4f0f-934a-3012b9eeecd8)

**Comment by scholokov** [comment]
так жеж і має бути... чи в вимогах інкше?

**Comment by ODrobik** [comment]
Додала уточнення до Актуального та Очікуваного результатів

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
Перевірено
