### ISSUE TITLE
20070722_0809_crimea/ Extra photos are loaded in photo gallery of the block "Пляж Рыбачье, Крым 27.07.2007"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5429]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20070722_0809_crimea
2. Pay attention to the photo gallery of the block "Пляж Рыбачье, Крым 27.07.2007".

**Actual result:**
The button "Відобразити галерею" is present in the gallery. Extra photos are loaded photo gallery of the block "Пляж Рыбачье, Крым 27.07.2007".

**Expected result:**
Only button "Відобразити галерею" appears in the photo gallery of the block "Пляж Рыбачье, Крым 27.07.2007".

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

**Environment:**

Windows 10,
Google Chrome v 125

**Attachment:**

![image](https://github.com/scholokov/long-travel-2/assets/101987790/ab00f90b-1251-4730-948d-36fc8ee8fa96)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
