### ISSUE TITLE
Testing page "Цікаві місця" Web and Mob - in "Цікаві місця" the name of the block "Браття наші менші" is not in alphabetical order

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5430]
Pre-conditions:
https://test.long-travel.live/places/

Steps to reproduce:

Note that in "Цікаві місця" the name of the block "Браття наші менші" is not in alphabetical order

Actual result:
in "Цікаві місця" the name of the block "Браття наші менші" is not in alphabetical order
Expected result:
blocks should be arranged in alphabetical order of names
​
Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
[https://qax.gitbook.io/qax-travel/requirements/placesс](https://qax.gitbook.io/qax-travel/requirements/places%D1%81) 5.2

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/e54de796-f43d-4b42-a0e7-74f5223d7721)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/4a740df5-e654-4882-a7d7-94cdd3f4be64)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/147203fa-5395-4766-b29c-b46c943ea005)

**Comment by Illia2810** [comment]
#5388

**Comment by Illia2810** [comment]
#5390

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
створив новий схожий баг #5457
