### ISSUE TITLE
Testing page "Цікаві місця" Web and Mob - the first block with the photo does not load immediately

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5432]
Pre-conditions:
https://test.long-travel.live/places/

Steps to reproduce:
Open https://test.long-travel.live/museum/
Note that the first block with the photo does not load immediately

Actual result:
the first block with the photo does not load immediately
Expected result:
the first block of the gallery should be loaded immediately, and then all other blocks should be loaded after clicking the "Відобразити галерею" button 

Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/places 5.7

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/000da9b5-c62d-4714-8f2c-f651879c6676)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/923f3e5e-4908-49d5-a562-919802f0edd3)

**Comment by Illia2810** [comment]
#5425

**Comment by Illia2810** [comment]
#5426

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
