### ISSUE TITLE
20070722_0809_crimea/ Names in 1st Road block are written in russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5433]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20070722_0809_crimea
2. Scroll down to the 1st Road block "Киев - Рыбачье 22.07.2007".
3. Pay attention to the language of the names.

**Actual result:**
Names in 1st Road block are written in russian "Киев - Рыбачье 22.07.2007".

**Expected result:**
**Names in 1st Road block are written in Ukrainian.**

**Environment:**
Windows 10,
Google Chrome v 125

**Additional information:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/cc9c1085-31aa-430f-a221-eac20958fcd9)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
