### ISSUE TITLE
"Цікаві місця" - "Парки" page - "Парк “Сосновий Бір”" structural block - Time period is 25.06.2021

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5435]
**Steps of reproducing**
1. Open https://test.long-travel.live/park/
2. Pay attention to Time period at "Парк “Сосновий Бір”" structural block

**Actual Result**
Time period is 25.06.2021

**Expected Result**
Time period is 26.06.2021

**Additional information**
Time period at "Парк “Сосновий Бір”" structural block on "Черкаси 2021" page is 26.06.2021
https://test.long-travel.live/20210625_28_cherkassy/

**Environments**
Windows 10, Chrome 126.0.6478.57 (64 bit)
Android 8.1.0, Chrome 125.0.6422.165
![Парки – Long-Travel - Google Chrome 12 06 2024 16_49_03](https://github.com/scholokov/long-travel-2/assets/95171672/83f9df89-3f13-42db-bd68-5006b36196e0)
![photo_2024-06-12_17-00-23](https://github.com/scholokov/long-travel-2/assets/95171672/274eb33c-476f-420b-bb64-e0d37c2826aa)

**Comment by DmitriiNasonov** [comment]
#5388

**Comment by DmitriiNasonov** [comment]
#5390

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproduced
