### ISSUE TITLE
"Цікаві місця" - "Парки" page - "Древлянський парк" structural block type is "Animals"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#5436]
**Steps of reproducing**
1. Open https://test.long-travel.live/park/
2. Scroll to "Древлянський парк" structural block

**Actual Result**
"Древлянський парк" structural block type is "Animals"

**Expected Result**
"Древлянський парк" structural block type is "Park"

**Additional information**
https://www.figma.com/design/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?node-id=986-6&t=ZDjgFMvQhKPoPoO3-0

**Environments**
Windows 10, Chrome 126.0.6478.57 (64 bit)
Android 8.1.0, Chrome 125.0.6422.165
![Парки – Long-Travel - Google Chrome 12 06 2024 16_49_03 png - Paint 12 06 2024 17_44_09](https://github.com/scholokov/long-travel-2/assets/95171672/e3b94765-ddd2-4b3f-8584-9ee1d4d53af9)
![photo_2024-06-12_17-50-10](https://github.com/scholokov/long-travel-2/assets/95171672/0efd9017-8f18-43bb-ac41-114672ee2664)

**Comment by DmitriiNasonov** [comment]
#5388

**Comment by DmitriiNasonov** [comment]
#5390

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
checked. bug isn't reproducing
