### ISSUE TITLE
20170417_kiylov no preview photo in the map

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5438]
Pre-conditions:
Open: https://test.long-travel.live/20170417_kiylov/

Steps to reproduce:

Note that an active element is missing "Відкрити подорож"

Actual result:
no preview photo in the map
Expected result:
a preview photo must be present

Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa 5.0

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/308724c6-3697-4d69-9a62-012fd6e3b0d7)

**Comment by Illia2810** [comment]
#5239

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified

**Comment by Illia2810** [comment]
verified
