### ISSUE TITLE
Testing page "Цікаві місця" Web and Mob - in "Цікаві місця" blocks are not in alphabetical order

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5457]
Pre-conditions:
https://test.long-travel.live/places/

Steps to reproduce:

Note that in "Цікаві місця" blocks are not in alphabetical order

Actual result:
in "Цікаві місця" blocks are not in alphabetical order
Expected result:
blocks should be arranged in alphabetical order of names
​
Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
[https://qax.gitbook.io/qax-travel/requirements/placesс](https://qax.gitbook.io/qax-travel/requirements/places%D1%81) 5.2

Attachment:
![image](https://github.com/scholokov/long-travel-2/assets/125801673/55113ff6-f0d6-47e9-9d8b-63529aff8e40)
![image](https://github.com/scholokov/long-travel-2/assets/125801673/678a7eeb-873d-486d-9bd1-3439333fb2f3)
![image](https://github.com/scholokov/long-travel-2/assets/125801673/99c96b7a-7167-4cc0-b02a-7f7b4f947be4)

**Comment by Illia2810** [comment]
#5388

**Comment by Illia2810** [comment]
#5390

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
зробив новий схожий баг #5478
