### ISSUE TITLE
20170417_kiylov  on the trip "Заповідник “Кийлівська Асканія”" on map the name of the city in English, and a trip around Ukraine

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5461]
Pre-conditions:
Open: https://test.long-travel.live/travels/
Open: https://test.long-travel.live/20170417_kiylov/

Steps to reproduce:
Note that on the trip "Заповідник “Кийлівська Асканія”" on map the name of the city in English, and a trip around Ukraine

Actual result:
on the trip "Заповідник “Кийлівська Асканія”" on map the name of the city in English, and a trip around Ukraine
Expected result:
the names of the cities must be in the language of the countries to which they belong

Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/2a71cf32-0b72-4d24-80df-26e47bc6324b)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/0f773577-561d-4ce5-9aee-92f2cc5c361f)

**Comment by Illia2810** [comment]
#5239

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
