### ISSUE TITLE
20170417_kiylov on the trip "Заповідник “Кийлівська Асканія”" flag sizes in standard blocks do not match 36*24 and 26*18

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5462]
Pre-conditions:
Open: https://test.long-travel.live/20170417_kiylov/

Steps to reproduce:

Note that the sizes of the flag are not the same

Actual result:
on the trip "Заповідник “Кийлівська Асканія”" flag sizes in standard blocks do not match 36*24 and 26*18
Expected result:
the dimensions of the flag must be the same 36*24

Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://www.figma.com/file/mh7iDnG6ec7yiC0SCGad7L/Long-Travel?type=design&node-id=344-13&mode=design

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/3a4f63a8-9f15-4e72-9267-bfe777087dde)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/20660b93-c487-4e87-b650-6e582fff713e)

**Comment by Illia2810** [comment]
#5239

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
