### ISSUE TITLE
20170417_kiylovno city on the standard block "Кийлівська Асканія" 

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5463]
Pre-conditions:
Open: https://test.long-travel.live/20170417_kiylov/

Steps to reproduce:

Note that city on the standard block "Кийлівська Асканія" and "Кийлів – Пікнік, р. Дніпро"

Actual result:
city on the standard block "Кийлівська Асканія" and "Кийлів – Пікнік, р. Дніпро"
Expected result:
a City or Region must be present on a standard block

Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

Attachment:
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/2ca8e803-e77e-42c9-9a68-9c71f0cc76d1)
![зображення](https://github.com/scholokov/long-travel-2/assets/125801673/5d76e606-415d-43e8-aaf3-330d75842ff6)

**Comment by Illia2810** [comment]
#5239

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
