### ISSUE TITLE
20070722_0809_crimea/ Name "Крым" in 2nd block is written in russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5474]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20070722_0809_crimea
2. Scroll down to the 2nd block "Рибаче Крым 25.07.2007".
3. Pay attention to the language of the names.

**Actual result:**
Names in 2nd block are written in russian "Рибаче Крым 25.07.2007" .

**Expected result:**
Names in 2nd block are written in russian in Ukrainian "Рибаче **Крим** 25.07.2007" .

**Environment:**
Windows 10,
Google Chrome v 125

**Additional information:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/mapa

**Attachment:**
![image](https://github.com/scholokov/long-travel-2/assets/101987790/c9e86d9f-d397-4309-94ed-51502a011f92)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
