### ISSUE TITLE
20070722_0809_crimea/ The Block "Отель Рибаче, Крим 29.07.2007" photo gallery loads immediately

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5475]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20070722_0809_crimea
2. Pay attention to the Block "Отель Рибаче, Крим 29.07.2007" photo gallery.

**Actual result:**
The extra photo gallery loads in the Block "Отель Рибаче, Крим 29.07.2007".

**Expected result:**
Only the button "Відобразити галерею" appears in the gallery.

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

**Environment:**

Windows 10,
Google Chrome v 125

**Attachment:**
https://jam.dev/c/79b4bc03-88ac-4829-be99-ceca84412780
![image](https://github.com/scholokov/long-travel-2/assets/101987790/d4c0b332-8fa2-4af3-b2c9-9d0846fddeee)

**Comment by GNatala** [comment]
#5127

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
Алеж тут зовсім інша проблема
кнопка "відобразити галерею" присутня і вона корекно працює
але присутня галеря, яка дублює галерею, що з'являється по кнопці...

**Comment by GNatala** [comment]
Дякую, змінила

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
