### ISSUE TITLE
Testing page "Цікаві місця" Web and Mob - in "Цікаві місця" blocks are not in alphabetical order

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5478]
Pre-conditions:
https://test.long-travel.live/places/

Steps to reproduce:

Note that in "Цікаві місця" blocks are not in alphabetical order

Actual result:
in "Цікаві місця" blocks are not in alphabetical order
Expected result:
blocks should be arranged in alphabetical order of names
​
Environment:
System: Windows 10 Pro
Browser: FireFox

Requirements:
[https://qax.gitbook.io/qax-travel/requirements/placesс](https://qax.gitbook.io/qax-travel/requirements/places%D1%81) 5.2

Attachment:
![зображення](https://github.com/user-attachments/assets/0c55d4e2-0f74-4334-8386-510f09145a9a)

**Comment by Illia2810** [comment]
#5388

**Comment by Illia2810** [comment]
#5390

**Comment by scholokov** [comment]
fixed

**Comment by Illia2810** [comment]
verified
