### ISSUE TITLE
Командний репорт за тиждень

### ISSUE THREAD

**Issue by Illia2810** [scholokov/long-travel-2#5487]
Звіт за тиждень18.07.2024-24.07.2024

| ID Дефекту | Назва | Статус | Автор
| --- | --- | --- | ---
|  #5480 | Пошук - Функціональне тестування - Web - The journey "egypt_hurghada" is not displayed when selecting actual tags | To do | Myroslava2
|#5481 | Пошук - Функціональне тестування - Web - The journey "kiev_aviation_museum" is not displayed when selecting actual tags |  To do | Myroslava2
| #5482 |  Пошук - Функціональне тестування - Web - The journey "italy_odessa" is not displayed when selecting duration   |  To do| Myroslava2
|#5483  |   Пошук - Функціональне тестування - Web - The journey "shadsk" is not displayed when selecting duration and actual tags    |  To do| Myroslava2
| #5484 |   Пошук - Функціональне тестування - Web - The journey "bucha" is not displayed when selecting duration and actual tags    |   Ready for review |  Myroslava2
| #5485 |   Пошук - Функціональне тестування - Web - Date in search and documentation don't match    |  Ready for review | Myroslava2

**Comment by Illia2810** [comment]
#5471

**Comment by scholokov** [comment]
ok
