### ISSUE TITLE
20070722_0809_crimea/ Names in block "Объект 825ГТС, Музей холодной войны Балаклава, Крим 27.07.2007" are written in russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5494]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20070722_0809_crimea
2. Scroll down to the block "Объект 825ГТС, Музей холодной войны Балаклава, Крим 27.07.2007".
3. Pay attention to the language of the names.

**Actual result:**
Names in the block "**Объект 825ГТС, Музей холодной войны Балаклава**, Крим 27.07.2007"  are written in russian. 
**Expected result:**
**Names in the block "**Объект 825ГТС, Музей холодной войны Балаклава**, Крим 27.07.2007" are written in Ukrainian.**

**Environment:**
Windows 10,
Google Chrome v 127

**Additional information:**
https://qax.gitbook.io/qax-travel/requirements/1.overall/language

**Attachment:**
![image](https://github.com/user-attachments/assets/a2b4e650-290b-4467-82cc-20125cc85548)

![image](https://github.com/user-attachments/assets/b639a757-9912-49a6-94c1-d2488c047882)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
