### ISSUE TITLE
20070722_0809_crimea/ Names in block "Генуэзская крепость Судак, Крим 01.08.2007" are written in russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5495]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20070722_0809_crimea
2. Scroll down to the block "Генуэзская крепость Судак, Крим 01.08.2007".
3. Pay attention to the language of the names.

**Actual result:**
Names "**Генуэзская крепость**" in the block "Генуэзская крепость Судак, Крим 01.08.2007'' are written in russian  .

**Expected result:**
Names "**Генуэзская крепость**" in the block "Генуэзская крепость Судак, Крим 01.08.2007'' are written in Ukrainian.

**Environment:**
Windows 10,
Google Chrome v 127

**Additional information:**
https://qax.gitbook.io/qax-travel/requirements/1.overall/language

**Attachment:**
![image](https://github.com/user-attachments/assets/52980104-c080-4014-a37c-77a7c4439584)
![image](https://github.com/user-attachments/assets/b639a757-9912-49a6-94c1-d2488c047882)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
