### ISSUE TITLE
20070722_0809_crimea/ Names in block "Тропа Голицина, Грот Шаляпина, Можжевеловая Роща Новый Свет, Крим 01.08.2007" are written in russian

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5496]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20070722_0809_crimea
2. Scroll down to the block "Тропа Голицина, Грот Шаляпина, Можжевеловая Роща Новый Свет, Крим 01.08.2007".
3. Pay attention to the language of the names.

**Actual result:**
Names "**Тропа Голицина, Грот Шаляпина, Можжевеловая Роща Новый Свет**" in the block "Тропа Голицина, Грот Шаляпина, Можжевеловая Роща Новый Свет, Крим 01.08.2007'' are written in russian.

**Expected result:**
Names "**Тропа Голицина, Грот Шаляпина, Можжевеловая Роща Новый Свет**" in the block "Тропа Голицина, Грот Шаляпина, Можжевеловая Роща Новый Свет, Крим 01.08.2007'' are written in Ukrainian.

**Environment:**
Windows 10,
Google Chrome v 127

**Additional information:**
https://qax.gitbook.io/qax-travel/requirements/1.overall/language

**Attachment:**

![image](https://github.com/user-attachments/assets/2e37990a-ea9d-4de8-8c67-1281f90a36ce)
![image](https://github.com/user-attachments/assets/b639a757-9912-49a6-94c1-d2488c047882)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixex

**Comment by GNatala** [comment]
passed
