### ISSUE TITLE
Home page/ "Інвестиції у подорожі це інвестіції у себе" main title is displayed with mistake in the second "iнвестіції" word

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#5497]
Steps to Reproduce:
1. Open page: https://test.long-travel.live/
2. Pay attention to the mistake in the "iнвестіції" word of the "Інвестиції у подорожі це інвестіції у себе" main title

Actual Result: 
"Інвестиції у подорожі це **інвестіції** у себе" main title is displayed with mistake in the second "iнвестіції" word

Expected Result: 
"Інвестиції у подорожі це **інвестиції** у себе" main title is displayed without mistake in the second "iнвестиції" word

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachments:
![image](https://github.com/user-attachments/assets/e5f480af-e9e7-4e3b-ba57-ab8bc0c5f6a3)

**Comment by ODrobik** [comment]
#5396 
#5395

**Comment by scholokov** [comment]
fixzed

**Comment by ODrobik** [comment]
Verify
