### ISSUE TITLE
Home page/ The author's "Мэттью" name of the main title "Інвестиції у подорожі це інвестіції у себе" is written in russian 

### ISSUE THREAD

**Issue by ODrobik** [scholokov/long-travel-2#5498]
Steps to Reproduce:
1. Open page: https://test.long-travel.live/
2. Pay attention to the author's "Мэттью" name of the main title "Інвестиції у подорожі це інвестіції у себе"

Actual Result:
 The author's **"Мэттью"** name of the main title "Інвестиції у подорожі це інвестіції у себе" is written in russian 

Expected Result:
 The author's **"Меттью"** name of the main title "Інвестиції у подорожі це інвестіції у себе" is written in Ukrainian 

Environment:
Windows 10 Pro,
Opera v 96.0.4693.80

Attachments:
![image](https://github.com/user-attachments/assets/2cefa3b8-b618-4213-9105-197c3ec4e1b3)

**Comment by ODrobik** [comment]
#5396 
#5395

**Comment by scholokov** [comment]
fixed

**Comment by ODrobik** [comment]
verified
