### ISSUE TITLE
Search - Preview - Title - Duplicate trip with incorrect data - Буцький каньйон 2023 11 23

### ISSUE THREAD

**Issue by VasylynaF** [scholokov/long-travel-2#5514]
Steps to reproduce:
1. Open the page: https://test.long-travel.live/
2. Click on ''Travels'' in the header
3. Enter ''Буцький каньйон'' in the search fiel
Actual result:
Duplicate trip with incorrect data ''Буцький каньйон 2023 11 23''

Expected result:
Should be only one trip ''Буцький каньйон'' with date 06.12.2017 

Attachments:
![image](https://github.com/user-attachments/assets/fbbb7722-5afa-4472-8973-b4dcf7349c20)

Environment:
Windows 10 (x64)
Google Chrome 127.0.6533.120 (Офіційне складання) (64-розрядна версія)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/user-attachments/assets/82c78e4c-54df-46cd-a286-a0d089c31f83)

**Comment by scholokov** [comment]
fixed

**Comment by VasylynaF** [comment]
якщо fixed, то мені відзначати як done? 
![image](https://github.com/user-attachments/assets/eac76490-ff6f-4922-87d2-081a3ab029b0)

**Comment by scholokov** [comment]
![image](https://github.com/user-attachments/assets/738cd058-5e2c-443d-9bfe-89e460d66c9d)

**Comment by VasylynaF** [comment]
ок, дякую.

**Comment by VasylynaF** [comment]
#5499
