### ISSUE TITLE
Search - Preview - ID: 20170612_buki - Unnecessary tag 

### ISSUE THREAD

**Issue by VasylynaF** [scholokov/long-travel-2#5515]
Steps to reproduce:

Open the page: https://test.long-travel.live/
Click on ''Travels'' in the header
Enter ''Буцький каньйон'' in the search field

Actual result: One unnecessary tag

![image](https://github.com/user-attachments/assets/42fd7ac1-5d0d-48e8-989b-61ada20da860)

Expected result:
Should be 3 tags (автомобіль, річка-озеро, каньйон) according to requirements
![image](https://github.com/user-attachments/assets/c7c5daab-f838-435e-9ef3-54fd46288c80)

Environment:
Windows 10 (x64)
Google Chrome 127.0.6533.120 (Офіційне складання) (64-розрядна версія)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/user-attachments/assets/761183b2-d833-4afa-8346-87c4b8442951)

**Comment by scholokov** [comment]
@VasylynaF 
- краще кроки нумурувати
- якщо ви силаєтесь на вимоги, то краще додавати і посилання на них

**Comment by scholokov** [comment]
ви зробили маленький скрін вимог. це дуже пагана практика
тим паче у цьому прикладі у вимогах присутній цей тег
![image](https://github.com/user-attachments/assets/dadd5c60-e7db-4ace-9167-446a2fbbeacb)

**Comment by VasylynaF** [comment]
#5499
