### ISSUE TITLE
20170612_buki_test - Travel - Map - Funс - Web - The Butsky Canyon "пам'ятка" is not marked with star

### ISSUE THREAD

**Issue by VasylynaF** [scholokov/long-travel-2#5516]
Steps to reproduce:
Open the page: https://test.long-travel.live/travels/
Enter '' Буцький каньйон'' in the search field
Scroll down to the map

Actual result:
The Butsky Canyon "пам'ятка" is not marked with star

Expected result:
The Butsky Canyon "пам'ятка" should be marked with star

Attachments:
![image](https://github.com/user-attachments/assets/fa7c9db2-438d-4c3f-8244-a51a93d877d2)

Environment:
Windows 10 (x64)
Google Chrome 127.0.6533.120 (Офіційне складання) (64-розрядна версія)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/user-attachments/assets/abb95094-d06f-4d28-93c1-6be7bdde9e02)

**Comment by VasylynaF** [comment]
#5500
