### ISSUE TITLE
20170612_buki_test - Travel - Map - Funс - Web - Drop-down list present

### ISSUE THREAD

**Issue by VasylynaF** [scholokov/long-travel-2#5517]
Steps to reproduce:
1. Open the page: https://test.long-travel.live/travels/
2. Enter '' Буцький каньйон'' in the search field
3. Scroll down to the map

Actual result:
Drop-down list present

Expected result:
There should not be a drop-down list

Attachments:
![image](https://github.com/user-attachments/assets/fd327d2b-75f4-405a-9d84-e40e4e9eb5c2)

Environment:
Windows 10 (x64)
Google Chrome 127.0.6533.120 (Офіційне складання) (64-розрядна версія)

**Comment by DmytroMarkulych** [comment]
![Image](https://github.com/user-attachments/assets/49d3d1f8-f86a-4ad3-b7c7-2f74ddf6329d)

**Comment by scholokov** [comment]
fixed

**Comment by VasylynaF** [comment]
#5500
