### ISSUE TITLE
20070722_0809_crimea/ Extra button "Відобразити галерею" is in block "Дорога: Рибаче – Балаклава – Севастополь – Рибаче", photos in the gallery load immediately 

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5521]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20070722_0809_crimea
2. Pay attention to the photo gallery of the block "Дорога: Рибаче – Балаклава – Севастополь – Рибаче".

**Actual result:**
Extra button "Відобразити галерею" is in block "Дорога: Рибаче – Балаклава – Севастополь – Рибаче" shows not corresponding photos. Photos in the gallery load immediately. 

**Expected result:**
Extra button "Відобразити галерею" is not in block "Дорога: Рибаче – Балаклава – Севастополь – Рибаче". Photos in the gallery do not load immediately, the button "Відобразити галерею" appears. 

**Requirements:**

https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

**Environment:**

Windows 10,
Google Chrome v 125

**Attachment:**
https://jam.dev/c/f4ab2ec6-3724-4301-afa5-69543b1da0df
![image](https://github.com/user-attachments/assets/2cbc0a34-db3b-4d79-a8dd-258199cfe070)

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
