### ISSUE TITLE
20070722_0809_crimea/ Photos in the gallery load immediately, extra button "Відобразити галерею" is in block "Балаклава"

### ISSUE THREAD

**Issue by GNatala** [scholokov/long-travel-2#5522]
**Steps to reproduce:**

1. Open https://test.long-travel.live/20070722_0809_crimea
2. Pay attention to the photo gallery of the block "Балаклава".

**Actual result:**
Photos in the gallery load immediately, extra button "Відобразити галерею" is in block "Балаклава" that shows not corresponding photos. 

**Expected result:**
Photos in the gallery do not load immediately, the button "Відобразити галерею" appears. extra button "Відобразити галерею" is in block "Балаклава" 

**Requirements:**
https://qax.gitbook.io/qax-travel/requirements/4.travel/struktura/standartnii-blok-i

**Environment:**

Windows 10,
Google Chrome v 125

**Attachment:**
![image](https://github.com/user-attachments/assets/03b9815c-3def-4d40-ace9-21b36366566a)

https://jam.dev/c/c39d4d3a-f1ad-43ae-ab35-004f79e5a3ce

**Comment by GNatala** [comment]
#5127

**Comment by scholokov** [comment]
fixed

**Comment by GNatala** [comment]
passed
