### ISSUE TITLE
Цікаві місця - Funk - Web, Mobile - Пляжі - Lexical error in ''пляжи''

### ISSUE THREAD

**Issue by VasylynaF** [scholokov/long-travel-2#5566]
Steps to reproduce:

1. Open the page: https://test.long-travel.live/places/
2. Click on ''Пляжі''
3. Сheck the text

Actual result:
Lexical error in the word ''пляжи''
![image](https://github.com/user-attachments/assets/a09aa6f8-ad89-4ce8-8106-6b1317009ff9)

Expected result:
The word ''пляжи'' should be ''пляжі''

Environment:
Web: Windows 10 (x64)
Google Chrome 127.0.6533.120 (Офіційне складання) (64-розрядна версія)

Mobile:
Safari, iOS 17.7
iPhone 12

**Comment by VasylynaF** [comment]
#5530

**Comment by scholokov** [comment]
fixed
