### ISSUE TITLE
Travel page Preview image inappropriate travel tags 

### ISSUE THREAD

**Issue by vetalyQaEn** [scholokov/long-travel-2#5573]
Steps to Reproduce:
1. Click to URL 
https://test.long-travel.live/20210510_staryi_solotvyn_test/

 Actual Result: 
inappropriate travel tags 
![inappropriate tags](https://github.com/user-attachments/assets/5ed62447-ddfe-4925-b5fc-5fdaaa49c441)

 Expected Result: 
ppropriate travel tags 
![Teg](https://github.com/user-attachments/assets/8ed420c0-9945-411a-ae07-b41ef9a9797f)

![Monosnap Подорожі - теги _ QAX Travel - Google Chr](https://github.com/user-attachments/assets/3f147626-0b30-4371-bc50-e917511a1988)

 Environment: 
Windows 10
Версия 130.0.6723.59 (Официальная сборка), (64 бит)

**Comment by scholokov** [comment]
незрозуміла проблема. а як має бути? на чому базується?

**Comment by vetalyQaEn** [comment]
к сожалению в документации которую вчера просмотрел Теги не описывают своей сущности 
![Monosnap Travel - 40 × 40px - Google Chrome 2024-1](https://github.com/user-attachments/assets/262a09ab-d584-420b-8e8e-fe3d63a1415a)
Можно двойственно расценивать эти Теги. 
 В Travel Tag на поездку под номером 085 есть запись Iншe которая не отвечает какие теги туда должны входить, мы отталкиваемся от Шаблона в Фигме, где под Поездкой Старый Солотвин, есть определенные Теги.
Добавил в отчет о дефекте поездку 085 которая к сожалению тоже не раскроет проблемы  заведение дефекта,
 ввиду того что в поездке есть записи Речка-Озеро и Iнше и как эти теги должны выглядеть в изображении.
Завести дефект по записи "Мають бути певнi теги" вообще не даст  разработчику подсказки что ему нужно исправить.

**Comment by scholokov** [comment]
все має бути простіше:
- у вас є вимоги, в яких написано які саме теги мають бути (там явно вони перераховані для кожної подорожі)
- у вас є додаток у якому інакше
- то ви і пишете що актулаьна ситуація така - а з вимог: як має бути. тим паче ви скріна з вимог вставили
- в даному випадку у експекті можна списком текстом зазначити які теги мають бути

**Comment by vetalyQaEn** [comment]
![Monosnap Long-Travel – Figma - Google Chrome 2024-](https://github.com/user-attachments/assets/b7062510-4ec3-42e8-86a8-6ccf86bfed19)
 к сожалению моих усилий оказалось не достаточно чтобы отыскать эту информацию по тегам, в Фигме из тегов только верхняя картинка,
 знаю что сильно заморачиваюсь, если заводить дефект то должен наверное указать что теги их изображения не соответствуют путешествию и какие должны быть  
  
можно ссылку на Теги  их изображения и их сущность в какую группу они относятся
![Monosnap long-travel-2_requirements_4 travel_trave](https://github.com/user-attachments/assets/09fd0a2b-3e0c-41fd-82c3-ab3ae94657a0)

Подскажите в канве нарисованы Теги и их очередность с верху вниз это соответствие табличному списку начиная от катер и заканчивая цiкаво правильно?

**Comment by scholokov** [comment]
яж кажу що все простіше :)

ось ваш скрін
![image](https://github.com/user-attachments/assets/29e1b3be-9dac-41a8-877b-cdf04db45366)
на ньому перераховано "що там має бути". тобто:
- Автомобіль
- Річка-озеро
- Інше
- Цікаво

ця вся інформація іде у експект. але саме списком (краще і скріном). і відповідно в екшуалі ви кажете що маєте невідповідність. тобто точно перераховувати що у вас є в єкшуалі - немає сенсу, а от перерахувати, що має бути - потрібно

**Comment by scholokov** [comment]
![image](https://github.com/user-attachments/assets/5cd4ce73-926d-46e8-88cf-86a678e0069b)
це скрін з канви - там теж є назва біля кожної картинки. для того щоб вона відобразилася потрібно або навести мишку на назву і подивитися у тултипі, або пицнути

<img width="1095" alt="image" src="https://github.com/user-attachments/assets/dee3a193-84de-4639-86fc-7e994ad9961f">

**Comment by vetalyQaEn** [comment]
У меня было выставлено в scrolle view  в таком виде теги не читаемы, когда перешёл в Grid view как у вас, увидел полный перечень с названиями , спасибо, не хватило знаний по изменению вида отображения.
