### ISSUE TITLE
Пошук - Funk - Web, Mobile - Filter by Природа is not working

### ISSUE THREAD

**Issue by VasylynaF** [scholokov/long-travel-2#5604]
**Steps to reproduce:**

1. Open the page: https://test.long-travel.live/travels/
2. Choose any category in the filter by Природа

**Actual result:**
Filter by Природа is not working.
There are two answer options either nothing found or two trips
![image](https://github.com/user-attachments/assets/c968d429-3b14-45f4-9626-1d61771ee38e)
![image](https://github.com/user-attachments/assets/e281f059-72e1-4ad2-ae6c-68e95a6442fe)
![image](https://github.com/user-attachments/assets/890f9013-1848-45be-b86d-6d567f6bb50a)

**Expected result:**
Filter by Природа should be working

**Environment:**
Web: Windows 10 (x64)
Google Chrome 127.0.6533.120 (Офіційне складання) (64-розрядна версія)

Mobile:
Safari, iOS 17.7
iPhone 12

**Comment by VasylynaF** [comment]
#5574

**Comment by scholokov** [comment]
на чому оснований баг?

треба ссилатися на приклад
тобто взяти подорож з вимог де точно є цей тег
і казати що ця подорож не відображається

або якщо писати загальний баг, то перерахувати подорожі, які мають відобразитися

**Comment by VasylynaF** [comment]
цей теж пофіксили? він працює

**Comment by DmytroMarkulych** [comment]
якщо пофікшено то можна передивитися і закрити
