### ISSUE TITLE
Пошук - Funk - Web, Mobile - Filter by Визначна пам'ятка is not working

### ISSUE THREAD

**Issue by VasylynaF** [scholokov/long-travel-2#5605]
Steps to reproduce:

1. Open the page: https://test.long-travel.live/travels/
2. Choose Обрати все category in the filter by Визначні пам'ятка

Actual result:
Filter by Визначні пам'ятка is not working. Incorrect search according to the list of trips of the requirements
![image](https://github.com/user-attachments/assets/1bc221fe-85bc-4e60-b482-309cab37d564)

**Expected result:**
Filter by  Визначні пам'ятка should be working.

**Environment:**
Web: Windows 10 (x64)
Google Chrome 127.0.6533.120 (Офіційне складання) (64-розрядна версія)

Mobile:
Safari, iOS 17.7
iPhone 12

**Comment by VasylynaF** [comment]
#5574

**Comment by scholokov** [comment]
на чому оснований баг?

треба ссилатися на приклад
тобто взяти подорож з вимог де точно є цей тег
і казати що ця подорож не відображається

або якщо писати загальний баг, то перерахувати подорожі, які мають відобразитися

**Comment by VasylynaF** [comment]
Цей фільтр почав працювати, але  треба дотестувати
