### ISSUE TITLE
20210814_24_sergeevka_odessa No blocks

### ISSUE THREAD

**Issue by VikaSavluk** [scholokov/long-travel-2#563]
Steps to reproduce:
Open page https://test.long-travel.live/20210814_24_sergeevka_odessa/

Actual result:
No blocks with names.

Expected result:
Each block must have its own name.

Environment:
Desktop/W7/Google Chrome 94.0.4606.81 (32bit)

**Comment by scholokov** [comment]
fixed

**Comment by VikaSavluk** [comment]
verified
