### ISSUE TITLE
20210814_24_sergeevka_odessa No region name

### ISSUE THREAD

**Issue by VikaSavluk** [scholokov/long-travel-2#568]
Steps to reproduce:
Open page https://test.long-travel.live/20210814_24_sergeevka_odessa/

Actual result:
No region name.

Expected result:
The name of the region : Одеська область.

Environment:
Desktop/W7/Google Chrome 94.0.4606.81 (32bit)
![скрин20](https://user-images.githubusercontent.com/92604614/151243887-dd57cd95-8846-488f-9c84-136979df53b4.png)

**Comment by scholokov** [comment]
fixed

**Comment by VikaSavluk** [comment]
verified
