### ISSUE TITLE
20210508_12month - Header - Отсутствует карта путешествия

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#626]
Шаги воспроизведения:
1)Открыть страницу путешествия: https://long-travel.live/.test/20210508_12months/

Ожидаемый результат:
Карта присутствует

Фактический результат:
Карта отсутствует

Операционная система:
Android 8.1.0, Windows 10

Браузер:
Chrome
![!!! 20210508_12months – Long-Travel - Google Chrome 16 05 2022 16_35_33](https://user-images.githubusercontent.com/95171672/168616255-9d45efe7-976c-4f4a-b44d-cfc00924ed2b.png)
![изображение_viber_2022-05-16_15-48-49-913](https://user-images.githubusercontent.com/95171672/168616273-27fd7bdc-530d-4c62-af62-7e9b4bd9f7b3.jpg)

**Comment by scholokov** [comment]
- нет скрина
- экшуал и экспектид - лучше писать в едином формате
- зачем пролистать всю страницу?
- зачем третий шаг?

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
Проверено. Баг не воспроизводится
![!!! 20210508_12months_Demidov – Long-Travel - Google Chrome 26 05 2022 14_11_05](https://user-images.githubusercontent.com/95171672/170477501-df2e8c76-55af-4b87-86a3-546ed07e1768.png)
