### ISSUE TITLE
20210508_12month - Header - Отсутствует превью

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#627]
Шаги воспроизведения:
1)Открыть страницу путешествия: https://long-travel.live/.test/20210508_12months/

Ожидаемый результат:
Превью присутствует

Фактический результат:
Превью отсутствует

Операционная система:
Android 8.1.0, Windows 10

Браузер:
Chrome
![!!! 20210508_12months – Long-Travel - Google Chrome 16 05 2022 16_35_33](https://user-images.githubusercontent.com/95171672/168615136-ddab3b54-ba93-48e3-9e5e-87911933c4b4.png)
![изображение_viber_2022-05-16_15-48-49-913](https://user-images.githubusercontent.com/95171672/168615147-63cc0be3-772b-4275-b8ae-d629d6ec048c.jpg)

**Comment by scholokov** [comment]
- нет скрина
- экшуал и экспектид - лучше писать в едином формате
- зачем пролистать всю страницу?
- зачем третий шаг?

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
Проверено. Баг не воспроизводится
![!!! 20210508_12months_Demidov – Long-Travel - Google Chrome 26 05 2022 14_35_02](https://user-images.githubusercontent.com/95171672/170480407-82ff73b2-6db1-46dc-8dfc-e76548524d8e.png)
![2](https://user-images.githubusercontent.com/95171672/170480417-9701bbce-7410-4d25-bded-998d4514c120.jpg)
