### ISSUE TITLE
20210508_12month - Header - Отсутствует структурный блок "Город, Область, страна"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#628]
Шаги воспроизведения:
1)Открыть страницу путешествия: https://test.long-travel.live/20210508_12months/
2)Обнаружить отсутствие структурного блока "Город, Область, страна" в Header

Ожидаемый результат:
Структурный блок "Город, Область, страна" присутствует

Фактический результат:
Структурный блок "Город, Область, страна" отсутствует

Операционная система:
Android 8.1.0, Windows 10

Браузер:
Chrome
![!!! 20210508_12months – Long-Travel - Google Chrome 16 05 2022 16_35_33](https://user-images.githubusercontent.com/95171672/168610092-e922e752-3dbe-4008-8e2c-99f17713f09c.png)
![изображение_viber_2022-05-16_15-48-49-913](https://user-images.githubusercontent.com/95171672/168610113-ffe6011f-7089-4af2-997a-d4887a2d8027.jpg)

**Comment by scholokov** [comment]
- нет скрина
- экшуал и экспектид - лучше писать в едином формате
- а надо точно всю страницу пролистать?

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
verified. not fixed
![!!! 20210508_12months_Demidov – Long-Travel - Google Chrome 10 06 2022 14_44_18](https://user-images.githubusercontent.com/95171672/173059114-c5419b0f-7d96-423f-bc76-1b44fe8b3d6a.png)
![photo_2022-06-10_14-44-42](https://user-images.githubusercontent.com/95171672/173059124-18562c2f-f051-4450-aab2-23f97e19e2d4.jpg)

**Comment by GeorgiiZ90** [comment]
http://www.test.long-travel.live/20210508_12months/\
fixed

**Comment by DmitriiNasonov** [comment]
verified. fixed
