### ISSUE TITLE
20210508_12month - Header - Отсутсвует Временной период путешествия

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#629]
Шаги воспроизведения:
1)Открыть страницу путешествия: https://test.long-travel.live/20210508_12months/
2)Обнаружить отсутствие структурного блока "Временной период" в Header

Ожидаемый результат:
Временной период присутствует 

Фактический результат:
Временной период отсутствует

Операционная система:
Android 8.1.0, Windows 10

Браузер:
Chrome
![!!! 20210508_12months – Long-Travel - Google Chrome 16 05 2022 16_35_33](https://user-images.githubusercontent.com/95171672/168605747-75525b38-b052-4e16-82f1-ca15e92457e5.png)
![изображение_viber_2022-05-16_15-48-49-913](https://user-images.githubusercontent.com/95171672/168605772-32c1b1e8-ab96-427a-8f27-445b3c5b1578.jpg)

**Comment by scholokov** [comment]
- нет скрина
- упомниание про хедер должно быть в шагах, а не экспекте
- логический и структурный - разные слова на тот же самый элемент

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
verified. not fixed
![!!! 20210508_12months_Demidov – Long-Travel - Google Chrome 10 06 2022 14_22_55](https://user-images.githubusercontent.com/95171672/173057372-968e7901-600f-4c35-8c99-ee632d6b2df7.png)
![photo_2022-06-10_14-40-48](https://user-images.githubusercontent.com/95171672/173057378-47f32252-1065-434c-8df6-9211ed3e196e.jpg)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
an issue is reproduced

![2022-07-07 12 15 44](https://user-images.githubusercontent.com/105543094/177739384-31ca8fa0-4215-4b76-a397-522ce36b1e63.png)
