### ISSUE TITLE
20210508_12month - Надпись single.php

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#638]
Шаги воспроизведения:
1)Открыть страницу путешествия: https://test.long-travel.live/20210508_12months/
2) Посмотреть в левый верхний угол страницы путешествия
3) Обратить внимание на надпись single.php 

Ожидаемый результат:
Надписи single.php нет

Фактический результат:
Надпись single.php находится в левом верхнем углу и не покидает своего места при пролистывании страницы

Операционная система:
Android, 8.1.0

![Screenshot_20220320-191249_1](https://user-images.githubusercontent.com/95171672/159175117-6fa6623e-e04d-42c5-9ac4-5266d56838c8.jpg)

https://user-images.githubusercontent.com/95171672/159175122-29360695-5b32-4b6d-ac7e-bbe912e0ce3a.mp4

**Comment by scholokov** [comment]
проблема до конца не исследована

**Comment by DmitriiNasonov** [comment]
fixed
![photo_2022-06-13_16-20-02](https://user-images.githubusercontent.com/95171672/173362999-43abdf91-4a73-4ff5-871b-dfcb44237408.jpg)
