### ISSUE TITLE
Путешествие - 20210508_12month - Отсутсвует Временной период путешествия (ПК)

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#639]
Шаги воспроизведения:
1)Открыть страницу путешествия: https://long-travel.live/.test/20210508_12months/
2)Пролистать всю страницу
3)Обнаружить отсутствие логического блока "Временной период"

Ожидаемый результат:
Присутствует Временной период в структурном блоке Body

Фактический результат:
Временной период отсутсвует

Операционная система:
Windows 10

**Comment by scholokov** [comment]
- "путешествие" - тут все баги по путешествия, потому писать это тут необязательно
- логического и структурном , тот же самый элемент должен называться одинаково
-  в тайтле есть ПК - воспроизводится только на ПК? или зачем это тут?
- нет скрина
