### ISSUE TITLE
20210508_12month - Body - Отсутствует Временной период путешествия

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#640]
Шаги воспроизведения:
1)Открыть страницу путешествия: https://test.long-travel.live/20210508_12months/
2)Обнаружить отсутствие логического блока "Временной период" в Body

Ожидаемый результат:
Временной период присутствует

Фактический результат:
Временной период отсутствует

Операционная система:
Android 8.1.0, Windows 10

Браузер:
Chrome
![!!! 20210508_12months – Long-Travel - Google Chrome 16 05 2022 15_43_49](https://user-images.githubusercontent.com/95171672/168597099-8b537551-1fce-4f9d-a663-d0eb8680b3a2.png)
![изображение_viber_2022-05-16_15-48-49-913](https://user-images.githubusercontent.com/95171672/168597122-ae6c7e93-f7ff-4ec5-9c5e-bd74127d5851.jpg)

**Comment by scholokov** [comment]
- "путешествие" - тут все баги по путешествия, потому писать это тут необязательно
- логического и структурном , тот же самый элемент должен называться одинаково
- нет скрина

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
verified. not fixe
![!!! 20210508_12months_Demidov – Long-Travel - Google Chrome 10 06 2022 14_44_18](https://user-images.githubusercontent.com/95171672/173057915-cdbae4fc-52da-43a4-9ebb-d6d69f2c35a7.png)
![photo_2022-06-10_14-44-42](https://user-images.githubusercontent.com/95171672/173057921-267c8bf8-3000-46cf-92ec-9ac782390a2b.jpg)
d

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
verified. not fixed
![08 05 2021 Демидів, Київская область, Україна – Long-Travel - Google Chrome 23 06 2022 17_34_09](https://user-images.githubusercontent.com/95171672/175326674-48e6131d-ea10-49f3-9152-e82b493f03aa.png)
![photo_2022-06-23_17-40-42](https://user-images.githubusercontent.com/95171672/175326687-588fb445-fbb7-4b0d-9aee-05daf34f4ce0.jpg)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
verified
