### ISSUE TITLE
20210508_12month - Header - Отсутствует Временной период путешествия

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#641]
Шаги воспроизведения:
1)Открыть страницу путешествия: https://test.long-travel.live/20210508_12months/
2)Обнаружить отсутствие логического блока "Временной период"  в Header

Ожидаемый результат:
Временной период присутствует

Фактический результат:
Временной период отсутствует

Операционная система:
Android 8.1.0, Windows 10

Браузер:
Chrome
![!!! 20210508_12months_Demidov – Long-Travel - Google Chrome 26 05 2022 14_45_38](https://user-images.githubusercontent.com/95171672/170482872-d538c78a-13b8-4c76-9b2e-9bfe6a145f34.png)
![1](https://user-images.githubusercontent.com/95171672/170482888-6be7654b-3813-40dd-8bf8-18c7e691a295.jpg)

**Comment by scholokov** [comment]
- "путешествие" - тут все баги по путешествия, потому писать это тут необязательно
- логического и структурном , тот же самый элемент должен называться одинаково
-  в тайтле есть ПК - воспроизводится только на ПК? или зачем это тут?
- нет скрина

**Comment by GeorgiiZ90** [comment]
fixed
