### ISSUE TITLE
20150523_picnic_dnipro The sound of the video does not stop after closing it

### ISSUE THREAD

**Issue by OlhaKlochak** [scholokov/long-travel-2#645]
Steps to reproduce:
1. Open website https://test.long-travel.live/20150523_picnic_dnipro/
2. Scroll down the page to the video
3. Сlick on the play button
4. Сlick on the close button in the right corner of the header in the webpage.

Actual result:
The sound of the video does not stop after closing it
Expected result:
The sound of the video stop after closing it

Environment:
Operating system Windows 10 Pro.
Browser version Chrome 100.0.4896.127
Screen resolution 1920 х 1028

**Comment by scholokov** [comment]
#339 ???

**Comment by scholokov** [comment]
Сlick on the close button in the right corner of the header

тут что имеется в виду?

**Comment by OlhaKlochak** [comment]
Имелось в виду нажать на крестик

**Comment by scholokov** [comment]
крестик где? браузер? приложение?
просто это важная информация, которая должна присутстовать

**Comment by tatianasheremet** [comment]
@OlhaKlochak 
pls add the priority of the ticket 
thx:)

**Comment by KaterinaNimenko35** [comment]
an issue is not reproduced


https://user-images.githubusercontent.com/105543094/200119767-72a1bc82-494a-4123-a50b-2a659f9eab54.mp4
