### ISSUE TITLE
20150523_picnic_dnipro There isn't the text description in the body of the page

### ISSUE THREAD

**Issue by OlhaKlochak** [scholokov/long-travel-2#649]
Steps to reproduce:

1. Open website https://long-travel.live/20150523_picnic_dnipro/
2. Scroll down the page

Actual result:
There isn't the text description in the body of the page

Expected result:
There is the text description in the body of the page

Environment:
Operating system Windows 10 Pro.
Browser version Chrome 101.0.4951.41
Screen resolution 1440 х 900

**Comment by scholokov** [comment]
а что такое text description?
есть требование - какие блоки должны присутствовать, на это и опираемся

**Comment by scholokov** [comment]
нет нумерации шагов

**Comment by scholokov** [comment]
#339 что это

**Comment by OlhaKlochak** [comment]
Да, «текстовий опис» необязательный блок

Пн, 2 мая 2022 г. в 20:43, Denis Scholokov ***@***.***>:

**Comment by scholokov** [comment]
тогда почему он должен присутствовать, если он необязательный?

**Comment by scholokov** [comment]
и?

**Comment by OlhaKlochak** [comment]
Я имею право удалить?

**Comment by scholokov** [comment]
нет. идеологически удалять нельзя
но можно закрыть с комментарием, что баз был заведен по ошибке

**Comment by OlhaKlochak** [comment]
Issue was created by mistake
