### ISSUE TITLE
20210508_12month - Body - Отсутствует структурный блок "Город, Область, страна"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#661]
Шаги воспроизведения:
1)Открыть страницу путешествия: https://test.long-travel.live/20210508_12months/
2)Обнаружить отсутствие структурного блока "Город, Область, страна" в Body

Ожидаемый результат:
Структурный блок "Город, Область, страна" присутствует

Фактический результат:
Структурный блок "Город, Область, страна" отсутствует

Операционная система:
Android 8.1.0, Windows 10

Браузер:
Chrome
![!!! 20210508_12months – Long-Travel - Google Chrome 24 05 2022 11_24_55](https://user-images.githubusercontent.com/95171672/169992769-97e13bbb-fc5f-4ca6-9bac-2fc15c1a070b.png)
![изображение_viber_2022-05-24_11-36-44-127](https://user-images.githubusercontent.com/95171672/169992789-12aa6317-e55a-4b73-9e67-ab90b26e97e6.jpg)

**Comment by GeorgiiZ90** [comment]
Fixed

**Comment by DmitriiNasonov** [comment]
not fixed

**Comment by scholokov** [comment]
please update screenshot

**Comment by DmitriiNasonov** [comment]
![!!! 20210508_12months – Long-Travel - Google Chrome 24 05 2022 12_18_25](https://user-images.githubusercontent.com/95171672/169999535-86eb6462-db08-4658-a5bc-0c19ef5a4ced.png)
.
.
![0-02-0a-dca0076224a13be4a706f06e315930ccddc348dde2922ae2fd35c08f183de175_8120336aaf22a3d5](https://user-images.githubusercontent.com/95171672/169999612-cd0e6dfa-31c8-49e8-af55-1ce9836d104e.jpg)

**Comment by scholokov** [comment]
а где ты тестируешь?

**Comment by DmitriiNasonov** [comment]
not fixed
![!!! 20210508_12months_Demidov – Long-Travel - Google Chrome 10 06 2022 14_44_18](https://user-images.githubusercontent.com/95171672/173060311-b9e1e70e-495b-4aba-bc1c-890d0b98d74f.png)
![photo_2022-06-10_14-44-42](https://user-images.githubusercontent.com/95171672/173060321-53eff5d5-41b8-49d5-a677-a3e6d2d09c6a.jpg)

**Comment by KaterinaNimenko35** [comment]
an issue is reproduced

![test long-travel live_20210508_12months_](https://user-images.githubusercontent.com/105543094/177740825-541ace1e-b7bd-4521-b996-43d97b60914a.png)

![2022-07-072 12 24 36](https://user-images.githubusercontent.com/105543094/177741478-7ad66934-5011-4d10-8c21-9bc0d01fafb7.png)

**Comment by KaterinaNimenko35** [comment]
verified
