### ISSUE TITLE
20210508_12month - Неверный тип фото галереи (вертикальный экран)

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#671]
Шаги воспроизведения:

1)Открыть страницу путешествия: https://long-travel.live/.test/20210508_12months/
2)Обратить внимание на тип фото галереи

Ожидаемый результат:
Мозаика

Фактический результат:
Лента

Операционная система:
Android 8.1.0

Браузер:
Chrome
![изображение_viber_2022-05-21_18-05-36-871](https://user-images.githubusercontent.com/95171672/169657697-e49dcdbe-b993-414c-956d-1539a272b0ad.jpg)
![изображение_viber_2022-05-21_18-05-37-018](https://user-images.githubusercontent.com/95171672/169657702-ebc6c040-f441-4b55-86ff-a0b365299231.jpg)

**Comment by scholokov** [comment]
тестировалось на телефоне
на узком разрешении выстраивается лентой...
