### ISSUE TITLE
20220124_28_netherlands: Intermediate block / Font not meet requirement

### ISSUE THREAD

**Issue by JuliAntoshchuk** [scholokov/long-travel-2#676]
**Steps to reproduce:**
1. Open page https://test.long-travel.live/20220124_28_netherlands/
2. Scroll down the page to the point "Restraurant: Puncake Burger"
3. Open Chrome DevTools, tab "Elements"
4. Pay attention to fonts size of the intermediate point

**Actual result:**
Fonts size of the intermediate point and date of travel are missing.

**Expected result:**
Fonts size of the intermediate point of travel - H2, date of travel - H3.

![fonts](https://user-images.githubusercontent.com/105114364/169714457-e99b6b0f-683e-4438-a2fa-6d2d335af52d.png)

**Environment:**
Operating system Windows 10 Pro
Browser Opera 85.0.4341.75
Google Chrome 101.0.4951.67 (64 bit)
Screen resolution: 1920 x 1080

**Comment by JuliAntoshchuk** [comment]
#622

**Comment by scholokov** [comment]
fixed

**Comment by JuliAntoshchuk** [comment]
Шрифт промежуточной точки путешествия (название города) не соответствует требованиям (должен быть H2)
Шрифт даты путешествия не соответствует требованиям (должен быть H3)
![1](https://user-images.githubusercontent.com/105114364/169788948-2993ac6a-088a-4bc7-b284-151354e5132a.png)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by JuliAntoshchuk** [comment]
Баг все еще присутствует
**Шрифт промежуточной точки путешествия (название города)** не соответствует требованиям (**должен быть H2**)
**Шрифт даты путешествия** не соответствует требованиям **(должен быть H3)**
![1](https://user-images.githubusercontent.com/105114364/170221649-d31e187c-5c4a-41ff-b722-26318855e665.png)
![фонт](https://user-images.githubusercontent.com/105114364/170221698-1c25a904-2a5a-4bde-9f12-3247d253981b.jpg)

**Comment by scholokov** [comment]
fixed

**Comment by JuliAntoshchuk** [comment]
bug is still reproduced

![1](https://user-images.githubusercontent.com/105114364/170876976-55dd5764-c695-4e81-918a-419a7245b061.png)

**Comment by JuliAntoshchuk** [comment]
verified

**Comment by JuliAntoshchuk** [comment]
bug is not reproduced. closed
