### ISSUE TITLE
20220124_28_netherlands: Incorrect hotel link

### ISSUE THREAD

**Issue by JuliAntoshchuk** [scholokov/long-travel-2#677]
**Description:**
Hotel link is incorrect.

**Steps to reproduce:**
1. Open page https://test.long-travel.live/20220124_28_netherlands/
2. Scroll down to Olympic Hotel

**Actual result:**
Hotel link is incorrect.

**Expected result:**
Hotel link is correct.

![hotel-1](https://user-images.githubusercontent.com/105114364/169805933-cd462673-6611-4db2-956f-69fe5405c258.png)

**Environment:**
Operating system Windows 10 Pro
Browser Opera 85.0.4341.75
Google Chrome 101.0.4951.67 (64 bit)
Screen resolution: 1920 x 1080

**Comment by JuliAntoshchuk** [comment]
#622

**Comment by scholokov** [comment]
fixed

**Comment by JuliAntoshchuk** [comment]
verified
