### ISSUE TITLE
20220124_28_netherlands: Page Travels - Unreadable Travel name and Category of travel

### ISSUE THREAD

**Issue by JuliAntoshchuk** [scholokov/long-travel-2#678]
**Description:**
The Travel name and the Category of travel are unreadable (dark print) and can't be found.

**Steps to reproduce:**
1. Open page https://test.long-travel.live/travels/
2. Scroll down the page
3. Pay attention to the Travel name and the Category of travel

**Actual result:**
Travel name and Category of travel are unreadable (dark print) and can't be found.

**Expected result:**
Travel name and Category of travel are readable (white print) and can be found.

![1](https://user-images.githubusercontent.com/105114364/169816162-bc47ffd0-7a35-4020-ba39-d68e88e5c826.jpg)

**Environment:**
Operating system Windows 10 Pro
Browser Opera 85.0.4341.75
Google Chrome 101.0.4951.67 (64 bit)
Screen resolution: 1920 x 1080

**Comment by JuliAntoshchuk** [comment]
#677

**Comment by JuliAntoshchuk** [comment]
#622

**Comment by scholokov** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
Verified, an issue is not reproduced
