### ISSUE TITLE
20220124_28_netherlands: Global map - Тravel name not meet requirement

### ISSUE THREAD

**Issue by JuliAntoshchuk** [scholokov/long-travel-2#680]
**Description:**
The Travel name in Global map has incorrect format. It should be in the following format: YYYY.MM.DD [Journey Name] (for example: 2021.10.29-11.10 Portugal) according to requirement.

**Steps to reproduce:**
1. Open page https://test.long-travel.live/20220124_28_netherlands/
2. Scroll down the page Global map
3. Pay attention to the Travel name in Global map

**Actual result:**
The Travel name in Global map has incorrect format.

**Expected result:**
The Travel name in Global map must be in the following format: 20220124_0128_netherlands according to requirement.

![5](https://user-images.githubusercontent.com/105114364/170197354-11e0a1a3-47e9-4447-bfab-190de8eb8896.png)

Environment:
_Desktop_
Operating system Windows 10 Pro / Browser Opera 85.0.4341.75 / Google Chrome 101.0.4951.67 (64 bit) / Screen resolution: 1920 x 1080
_Mobile_
Iphone 11 / Operation sistem iOS 15.5 / Browser Safari / Screen resolution 1792×828

**Comment by scholokov** [comment]
fixed

**Comment by JuliAntoshchuk** [comment]
bug is not reproduced. closed
