### ISSUE TITLE
20200725_26_piviha The name of the trip does not meet the requirements  

### ISSUE THREAD

**Issue by AlexandrLyahov** [scholokov/long-travel-2#694]
Description:
On the page https://test.long-travel.live/20200725_26_piviha/,the name of the trip does not meet the requirements

Steps to reproduce:
Open page https://test.long-travel.live/20200725_26_piviha/

Actual result:
not specified city,region,country

Expected result:
city,region,country specified

![Знімок екрана 2022-05-29 173047](https://user-images.githubusercontent.com/105969368/170874584-acaa41ee-e905-4f4b-9295-5024d2263dc5.png)

![Знімок екрана 2022-05-29 172728](https://user-images.githubusercontent.com/105969368/170874603-459dc316-5aaf-44b6-8a2b-d12ff13e27b4.png)

![Знімок екрана 2022-05-29 173319](https://user-images.githubusercontent.com/105969368/170874725-7b5baf30-ec54-45fd-843a-bf398aefba35.png)

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 102.0.5005.63 (64bit)
Screen resolution: 1600 x 900

**Comment by scholokov** [comment]
20200725_26_piviha The name of the trip does not meet the requirements #337 #694

лишний айди в тайтле

**Comment by AlexandrLyahov** [comment]
Исправленно

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by AlexandrLyahov** [comment]
> Description: On the page https://test.long-travel.live/20200725_26_piviha/,the name of the trip does not meet the requirements
> 
> Steps to reproduce: Open page https://test.long-travel.live/20200725_26_piviha/
> 
> Actual result: not specified city,region,country
> 
> Expected result: city,region,country specified
> 
> ![Знімок екрана 2022-05-29 173047](https://user-images.githubusercontent.com/105969368/170874584-acaa41ee-e905-4f4b-9295-5024d2263dc5.png)
> 
> ![Знімок екрана 2022-05-29 172728](https://user-images.githubusercontent.com/105969368/170874603-459dc316-5aaf-44b6-8a2b-d12ff13e27b4.png)
> 
> ![Знімок екрана 2022-05-29 173319](https://user-images.githubusercontent.com/105969368/170874725-7b5baf30-ec54-45fd-843a-bf398aefba35.png)
> 
> Environment: Operating system: Windows 10 Pro Browser: Google Chrome 102.0.5005.63 (64bit) Screen resolution: 1600 x 900

**Comment by scholokov** [comment]
@AlexandrLyahov 
ошибка исправлена?
