### ISSUE TITLE
20220124_28_netherlands: Global map - Sorting of trips incorect

### ISSUE THREAD

**Issue by JuliAntoshchuk** [scholokov/long-travel-2#702]
**Description:**
Sorting of trips in Global map is incorect. It must be from last trip (at the top) to old one (at the bottom).
Trip "20220124_28_netherlands" is in the bottom of the travel's list in Global map. It doesn't meet to requirements (date of trip 24.01.2022-28.01.2022). It must be in top of the list as the lattest trip on the page "Travels".

**Steps to reproduce:**
1. Open page https://test.long-travel.live/travels/
2. Scroll down to the Global map
3. Pay attention on sorting of trips in Global map
4. Find Trip "20220124_28_netherlands" in Global map

**Actual result:**
Trip "20220124_28_netherlands" in Global map in the bottom of the travel's list.

**Expected result:**
Trip "20220124_28_netherlands" in Global map in the top of the travel's list.

![44](https://user-images.githubusercontent.com/105114364/170884203-b223be91-604e-4797-ad5d-fe0f42938d7a.jpg)

**Environment:**
Operating system: Windows 10 Pro
Browser: Google Chrome 102.0.5005.6 (64 bit)
Screen resolution: 1920 x 1080

**Comment by JuliAntoshchuk** [comment]
#622

**Comment by scholokov** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
An issue is reproduced

![2022-11-01 15 30 42](https://user-images.githubusercontent.com/105543094/199234849-3bbcadaf-8998-4d76-925f-40efa9affe3e.png)



https://user-images.githubusercontent.com/105543094/199234883-7d24d6fa-e88b-43b0-9cf8-3aed53e9c1f8.mp4

**Comment by scholokov** [comment]
fixed
