### ISSUE TITLE
20190720_0811_balcans : The name of the Travel page not meet the requirement

### ISSUE THREAD

**Issue by JuliAntoshchuk** [scholokov/long-travel-2#721]
**Description:**
The name of the Travel page doesn't meet the requirement. It should not contain the start and the end of the trip.

**Steps to reproduce:**
1. Open page https://test.long-travel.live/20190720_0811_balcans/
2. Scroll down to the Name of the Travel page
3. Pay attention to the Name of the Travel page

**Actual result:**
The name of the Travel page **doesn't** meet the requirement

**Expected result:**
The name of the Travel page **meet** the requirement

![3](https://user-images.githubusercontent.com/105114364/171642380-6d738da2-253e-4274-abd9-791daa8385eb.jpg)

**Environment:**
Operating system Windows 10 Pro
Browser Google Chrome 102.0.5005.6 (64 bit)
Screen resolution: 1920 x 1080

**Comment by JuliAntoshchuk** [comment]
#233

**Comment by JuliAntoshchuk** [comment]
verified. bug is not reproduced

**Comment by JuliAntoshchuk** [comment]
bug is still present. name "Ukraine" is unnecessary
![3](https://user-images.githubusercontent.com/105114364/173124813-d02b13c1-3e7a-4ce1-839c-591d581ebae6.jpg)

**Comment by scholokov** [comment]
а тут Украина - из-за предпоследней, а не последней точки

**Comment by JuliAntoshchuk** [comment]
тогда Украина должна быть в конце, как предпоследняя точка путешествия
![2](https://user-images.githubusercontent.com/105114364/173794919-39dc0ec3-60b0-4a14-bf90-4b7469d9c6f1.jpg)

**Comment by JuliAntoshchuk** [comment]
verified
