### ISSUE TITLE
20200725_26_piviha unexpected gaps between photos

### ISSUE THREAD

**Issue by AlexandrLyahov** [scholokov/long-travel-2#724]
Steps to reproduce:
1,Open https://test.long-travel.live/20200725_26_piviha/
2,Scroll down

Actual result:
unexpected gaps between photos

Expected result:
 there are no unexpected gaps between photos

![Знімок екрана 2022-06-02 210528](https://user-images.githubusercontent.com/105969368/171697628-fac3dc34-be08-4733-8b46-2f8d3031edcd.png)
![Знімок екрана 2022-06-02 210824](https://user-images.githubusercontent.com/105969368/171697655-733235ad-4c0d-4d65-a48d-8ba625ee6f21.png)

![Знімок екрана 2022-06-02 211157](https://user-images.githubusercontent.com/105969368/171698136-72779866-c9e9-4719-840c-d53fcaecb3b2.png)
![Знімок екрана 2022-06-02 211127](https://user-images.githubusercontent.com/105969368/171698153-8a657925-a786-4f3e-8528-b785a6439d11.png)

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 102.0.5005.63 (64bit)
Screen resolution: 1600 x 900

**Comment by scholokov** [comment]
free space between photos

тут лучше писать в формате

unexpected spaces between photos

**Comment by AlexandrLyahov** [comment]
Исправлено

**Comment by scholokov** [comment]
а в теле?

**Comment by AlexandrLyahov** [comment]
Исправлено

**Comment by GeorgiiZ90** [comment]
fixed
