### ISSUE TITLE
Global.Search: Absence of search panel 

### ISSUE THREAD

**Issue by JuliAntoshchuk** [scholokov/long-travel-2#731]
**Description:**
Search panel is missing on the top.

**Steps to reproduce:**
1. Open page https://test.long-travel.live/
2. Pay attention to the absence of search panel 

**Actual result:**
Search panel **isn't** present on the top.

**Expected result:**
Search panel **is** present on the top.
![172153860-8d4018be-9fa0-4224-bd8f-284d0b70aa70](https://user-images.githubusercontent.com/105114364/172156012-f153581e-8359-477a-ad2e-2b1c1520a65b.png)

**Environment:**
Operating system Windows 10 Pro
Browser Google Chrome 102.0.5005.6 (64 bit)
Screen resolution: 1920 x 1080

**Comment by JuliAntoshchuk** [comment]
#622

**Comment by scholokov** [comment]
баг относится к путешествию?

**Comment by scholokov** [comment]
теплее :))))
проблема же не только в тревелах

**Comment by JuliAntoshchuk** [comment]
просто по требованиям именно в Тревелс прописано о Поиске
или лучше отнести к "Global.Structure" ?
![1](https://user-images.githubusercontent.com/105114364/172154609-42f835bc-ff3f-46e8-b2a4-0572f16042da.png)

**Comment by scholokov** [comment]
а там немного про другое
там должна быть целая панель для поиска, которой еще нет. там не про главное меню

**Comment by JuliAntoshchuk** [comment]
такой вариант?)

**Comment by scholokov** [comment]
да, что то в этом духе. тут уже как команда договорится

**Comment by scholokov** [comment]
by design
