### ISSUE TITLE
20200725_26_piviha-date and address of travel missing 

### ISSUE THREAD

**Issue by AlexandrLyahov** [scholokov/long-travel-2#755]
Steps to reproduce:
Open page https://test.long-travel.live/20200725_26_piviha/

Actual result:
no travel date and address 

Expected result:
there is a date and address of the trip 

![2022-06-09 22_08_13-Window](https://user-images.githubusercontent.com/105969368/172925388-e081ae94-a0b5-4a54-84d8-055efecd7488.png)

![2022-06-09 22_18_54-](https://user-images.githubusercontent.com/105969368/172927191-8937954d-6da8-434d-858f-af2637d99c9e.png)

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 102.0.5005.63 (64bit)
Screen resolution: 1600 x 900

**Comment by GeorgiiZ90** [comment]
fixed
