### ISSUE TITLE
20200725_26_piviha - photo is not loading

### ISSUE THREAD

**Issue by AlexandrLyahov** [scholokov/long-travel-2#757]
Steps to reproduce:
1,Open https://test.long-travel.live/20200725_26_piviha/
2,Scroll down

Actual result:
no photo visible

Expected result:
photo visible

![2022-06-09 23_36_57-Window](https://user-images.githubusercontent.com/105969368/172939977-fb6a022d-2f24-4068-8446-5396598311d0.png)
![2022-06-09 23_37_33-Window](https://user-images.githubusercontent.com/105969368/172939980-ffda9b4a-68f5-42fc-8893-95318b1d4509.png)

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 102.0.5005.63 (64bit)
Screen resolution: 1600 x 900

**Comment by scholokov** [comment]
please retest
