### ISSUE TITLE
20210508_12months_Demidov - Body - Фото и видео галереи недоступны

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#758]
Описание:
Рамки под превью фото на странице присутствуют, но сами превью не прогружаются. Если открыть LightBox, будет видна надпись "The image could not be loaded"

Шаги воспроизведения:
1) Открыть среду http://www.test.long-travel.live/20210508_12months/
2) Проскролить страницу до фотогалереи

Ожидаемый результат:
Все фото и их превью доступны к просмотру

Фактический результат:
Все фото и их превью не доступны к просмотру

Операционная система:
Windows 10, Android 8.1.0

Браузер:
Chrome
![!!! 20210508_12months_Demidov – Long-Travel - Google Chrome 10 06 2022 14_44_18](https://user-images.githubusercontent.com/95171672/173097432-a68f9e13-fa43-4bd8-a10f-9c5c888b1a5e.png)
![photo_2022-06-10_14-44-42](https://user-images.githubusercontent.com/95171672/173097446-430781da-f3ba-4721-a6df-277057b71f70.jpg)
![!!! 20210508_12months_Demidov – Long-Travel - Google Chrome 10 06 2022 18_19_06](https://user-images.githubusercontent.com/95171672/173097747-0fd05060-e4d7-4741-abba-f127f3538a3c.png)
![photo_2022-06-10_18-19-47](https://user-images.githubusercontent.com/95171672/173097764-bf532fdf-1926-461b-9270-c59afd24456a.jpg)

**Comment by scholokov** [comment]
please retest

**Comment by DmitriiNasonov** [comment]
verified. fixed
