### ISSUE TITLE
20220124_0128_netherlands : No displayed photos in the Gallery 

### ISSUE THREAD

**Issue by JuliAntoshchuk** [scholokov/long-travel-2#764]
**Description:**
Photos are not displayed in the Gallery

**Steps to reproduce:**
1. Open page http://www.test.long-travel.live/20220124_0128_netherlands/
2. Scroll down the page
3. Pay attention to the photos in the Gallery on the page of the travel

**Actual result:**
Photos **are not** displayed in the Gallery.

**Expected result:**
Photos **are** displayed in the Gallery .

**Screenshot:**
1. Desktop
https://user-images.githubusercontent.com/105114364/173796393-348f3406-44fb-4b7b-b257-85b406dadb1d.mp4

2. Mobile
![1](https://user-images.githubusercontent.com/105114364/173797286-4bb6e4c9-60d7-41a3-ab6b-662eeda2fae7.jpg)

**Environment:**
1. Desktop
Operating system Windows 10 Pro
Browser Google Chrome 102.0.5005.63 (64 bit)
Screen resolution: 1920 x 1080

2. Mobile
Iphone 11
Operation sistem iOS 15.5
Browser Safari
Screen resolution 1792×828

**Comment by scholokov** [comment]
fixed

**Comment by JuliAntoshchuk** [comment]
issue is reproduce
![1](https://user-images.githubusercontent.com/105114364/174770183-922c9f07-43dc-482a-8613-29be80db7582.png)

**Comment by scholokov** [comment]
please repeat with cleared cache

**Comment by JuliAntoshchuk** [comment]
verified. after cleared cache bug isn`t reproduce
![2](https://user-images.githubusercontent.com/105114364/174788475-75c5bdc5-c51c-45e3-af1c-636a8feadd39.png)

**Comment by scholokov** [comment]
дык а чего тогда не закрываешь?

**Comment by JuliAntoshchuk** [comment]
уже)
