### ISSUE TITLE
20200725_26_piviha - publication date does not match travel date

### ISSUE THREAD

**Issue by AlexandrLyahov** [scholokov/long-travel-2#779]
Steps to reproduce:
1,Open https://test.long-travel.live/20200725_26_piviha/
2,Scroll down

Actual result:
dates don't match

Expected result:
dates match

![2022-06-15 22_42_06-Window](https://user-images.githubusercontent.com/105969368/173912869-c09ee9f4-dcbf-4fb7-b9dc-18e0143b077d.png)

![2022-06-15 22_44_15-Window](https://user-images.githubusercontent.com/105969368/173913357-d4af46fe-9261-4293-a053-4273468293ca.png)

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 102.0.5005.115 (64 bit)
Screen resolution: 1600 x 900

**Comment by GeorgiiZ90** [comment]
fixed
