### ISSUE TITLE
20200725_26_piviha - block 25-26.07.2020 Hotel, Kremenchuk - no Booking Link

### ISSUE THREAD

**Issue by AlexandrLyahov** [scholokov/long-travel-2#780]
Steps to reproduce:
1,Open https://test.long-travel.live/20200725_26_piviha/
2,Scroll down

Actual result:
no Booking Link

Expected result:
there is a Link Booking

![2022-06-15 22_57_47-Window](https://user-images.githubusercontent.com/105969368/173917645-23eca418-90bc-48ee-adbf-ab41da77bdf8.png)

![2022-06-15 22_56_39-Window](https://user-images.githubusercontent.com/105969368/173917740-92ca254e-7686-49db-9ed0-9f3637b9242e.png)
![2022-06-15 22_51_13-Window](https://user-images.githubusercontent.com/105969368/173917774-272aa2ea-6073-4244-adb8-c274cc75783d.png)

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 102.0.5005.115 (64 bit)
Screen resolution: 1600 x 900

**Comment by scholokov** [comment]
fixed
