### ISSUE TITLE
The Site _ Unsecure protocol HTTP

### ISSUE THREAD

**Issue by JuliAntoshchuk** [scholokov/long-travel-2#781]
Description:
The site uses unsecure protocol HTTP  instead of HTTPS.

**Steps to reproduce:**
1. Open page http://www.test.long-travel.live/
2. Pay attention to the notification "Not protected" in the Address bar

**Actual result:**
The site uses **unsecure protocol HTTP.**

**Expected result:**
The site uses **secure protocol HTTPS.**

![1](https://user-images.githubusercontent.com/105114364/174014439-fddebf54-8785-4a44-9b10-8d83bf643b46.png)

**Environment:**
Operating system Windows 10 Pro
Browser Google Chrome 102.0.5005.63 (64 bit)
Screen resolution: 1920 x 1080

**Comment by scholokov** [comment]
fixed

**Comment by JuliAntoshchuk** [comment]
issue isn`t reproduced. verified
![2](https://user-images.githubusercontent.com/105114364/174791503-10b62aed-719d-480c-968d-e44d726a1208.png)
