### ISSUE TITLE
20130908_tropical_park - no travel map

### ISSUE THREAD

**Issue by AlexandrLyahov** [scholokov/long-travel-2#784]
Steps to reproduce:
Open http://www.test.long-travel.live/20130908_tropical_park/

Actual result:
no map

Expected result:
have a map

![2022-06-21 21_58_17-20130908_Київ_Україна_tropical_park – Long-Travel](https://user-images.githubusercontent.com/105969368/174877395-014f07b0-534b-436c-af0c-1af382ac7bcf.png)

![2022-06-16 21_37_18-Window](https://user-images.githubusercontent.com/105969368/174141966-802bd7e2-9dc0-438b-beaf-aa7ef54bf1cd.png)

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 102.0.5005.115 (64 bit)
Screen resolution: 1600 x 900

**Comment by scholokov** [comment]
fixed

**Comment by AlexandrLyahov** [comment]
нет карты

**Comment by scholokov** [comment]
fixed
