### ISSUE TITLE
20200725_26_piviha - block region, country - no punctuation mark

### ISSUE THREAD

**Issue by AlexandrLyahov** [scholokov/long-travel-2#786]
Steps to reproduce:
1,Open https://test.long-travel.live/20200725_26_piviha/
2,Scroll down

Actual result:
without punctuation mark

Expected result:
there is a punctuation mark

![2022-06-16 22_01_51-Window](https://user-images.githubusercontent.com/105969368/174145865-aab0a7a9-93c5-4767-8dbf-b66219a232ba.png)

![2022-06-16 21_28_51-Window](https://user-images.githubusercontent.com/105969368/174145923-09c25034-b407-457d-9221-93a40b32e10b.png)

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 102.0.5005.115 (64 bit)
Screen resolution: 1600 x 900

**Comment by scholokov** [comment]
в тайтле:
no punctuation mark
в результах:
no comma

должно быть одинаково
