### ISSUE TITLE
Mobile _ All pages _ Design of button Menu does not meet the Figma's design

### ISSUE THREAD

**Issue by JuliAntoshchuk** [scholokov/long-travel-2#787]
**Description:**
On Mobile version of Site the design of button Menu doesn't meet the Figma's design.

**Steps to reproduce:**
1. Open page http://www.test.long-travel.live/ on Mobile
2. Pay attention to the button Menu 

**Actual result:**
The design of button Menu **doesn't meet** the Figma's design.

**Expected result:**
The structure of button Menu **meets** the the Figma's design.
![1](https://user-images.githubusercontent.com/105114364/174248405-1ceceab3-41e6-48ce-bf6b-6baddf2fc220.jpg)
![2](https://user-images.githubusercontent.com/105114364/174809946-ca79f47f-c136-420a-a543-4c834acebfcb.png)

**Environment:**
Iphone 11
Operation sistem iOS 15.5
Browser Safari
Screen resolution 1792×828

**Comment by scholokov** [comment]
исходя из описания непонятно в чем именно проблема

**Comment by JuliAntoshchuk** [comment]
обновила описание

**Comment by scholokov** [comment]
- в тикете нигде не говорится, что разговор именно про моб версию
- это внешний вида, а не функциональность. бургер должен быть на дизайне. а вот если его там нет - то это баг

**Comment by JuliAntoshchuk** [comment]
подправила тайтл, дискрипш и резалтс. и добавила скрин с Фигмы. так можно?

**Comment by scholokov** [comment]
Mobile version of Site
слишком много слов в тайтле. достаточно:
Mobile -

**Comment by scholokov** [comment]
fixed

**Comment by JuliAntoshchuk** [comment]
verified
