### ISSUE TITLE
20190720_0811_balcans Фото в Gallery  на половину маршрута не загружается

### ISSUE THREAD

**Issue by YulyaBaday** [scholokov/long-travel-2#796]
Шаги воспроизведения:

1. Открыть https://test.long-travel.live/20190720_0811_balcans/
2. Проскролить вниз до промежуточной точки путешествия Hotel: Apartment Gubec

Фактический результат:
Фото не отображается

Ожидаемый результат:
Фото отображается

Notes (так же ошибка воспроизводится в следующих галереях):
1. Hotel: Apartment Gubec
2. Osijec Croatia
3. Road: Croatia - Hungary

![балканы2](https://user-images.githubusercontent.com/105633624/174765268-b12f9fbd-d1f7-4438-bd3a-49fc933f017e.png)

Cреда:
Операционная система: Windows 10
Версия браузера: Chrome 101.0.4951.67
Разрешение экрана: 1366x768

**Comment by YulyaBaday** [comment]
#773

**Comment by scholokov** [comment]
fixed

**Comment by YulyaBaday** [comment]
Была указана не полная информацию в описании, поэтому пофикшен баг частично. Добавляю незагрузившееся промежуточные точки.
![11](https://user-images.githubusercontent.com/105633624/174770723-c9b27914-0670-4807-b91a-3140b772224f.png)

**Comment by scholokov** [comment]
это уже новый баг
