### ISSUE TITLE
20190720_0811_balcans Фото в Gallery  частично не загружается(Hotel Palma и т.д.)

### ISSUE THREAD

**Issue by YulyaBaday** [scholokov/long-travel-2#798]
Шаги воспроизведения:

Открыть https://test.long-travel.live/20190720_0811_balcans/
Проскролить вниз до промежуточной точки путешествия Hotel Palma

Фактический результат:
Фото не отображается

Ожидаемый результат:
Фото отображается

Notes (так же ошибка воспроизводится в следующих галереях):
Nyirbator Hungary
Road: Hungary - Ukraine
Hotel: Амбер
Road: Богородчаны-Киев

![11](https://user-images.githubusercontent.com/105633624/174772770-c0f57c61-fb32-4382-a247-cafa0d743b3e.png)

Cреда:
Операционная система: Windows 10
Версия браузера: Chrome 101.0.4951.67
Разрешение экрана: 1366x768

**Comment by YulyaBaday** [comment]
#773

**Comment by scholokov** [comment]
я зачем попросил второй баг создать - у тебя тайтл один и тот же выходит. т.е. не уникальный

**Comment by YulyaBaday** [comment]
Исправлено

**Comment by scholokov** [comment]
как писал в предыдущем:
есть смысл написать какие именно галереи без фото.
в первом тогда уже перечислить исправленные и закрыть его
а во второй добавить неисправленные

**Comment by YulyaBaday** [comment]
Написать какие именно галереи без фото надо в тайтле или в фактическом и ожидаемом результате?

**Comment by scholokov** [comment]
в тайтле можно одну как пример
в факт и экспекте- не надо
а внизу добавить в ноутс: что так же воспроизвеодится в: и перечнем

**Comment by scholokov** [comment]
только эта информация должна быть в теле, а не коментах

**Comment by YulyaBaday** [comment]
Я просто не понимаю к какой части отнести данную информацию. Это должно быть отмечено в шагах воспроизведения или нужно добавить  Description?

**Comment by scholokov** [comment]
обновил тело
