### ISSUE TITLE
20200627_29_yuzhniy. Map. Wrong font size of intermediate points.

### ISSUE THREAD

**Issue by yuriiboikokiev** [scholokov/long-travel-2#80]
**Steps:**
1.Open page https://long-travel.live/20200627_29_yuzhniy/
2.Attention to the map.
2.Selecting intermediate travel points "Vinnytsia".
3.Open devtools
4.Attention  font size of the intermediate points.

**Expected result:**
The font size of the intermediate points is h2.

**Actual result :**
Font size of intermediate points - span (not correct according to requirements)
Screenshot: https://skr.sh/s9nNU9Hzorw?a

Additional Information:
-Operating System: windows 8, x64.
-browser : Google Chrome 91.0.4472.77 (Official build), (64 bit).

**Comment by scholokov** [comment]
- отсутствует "ожидаемый результат"

**Comment by scholokov** [comment]
- скриншот создан не по правилам (непонятно к чему он относится)

**Comment by scholokov** [comment]
из-за отсутствия адекватного скрина, вообще непонятно о чем идет речь

**Comment by scholokov** [comment]
требований к размеру шрифта на карте нет.
на тесте все ок
