### ISSUE TITLE
20210508_12months _ Name of the Trip not meet requirement

### ISSUE THREAD

**Issue by JuliAntoshchuk** [scholokov/long-travel-2#819]
**Description:**
Name of the Trip doesn't meet the requirement. It should be on language of the country to which City belongs.

**Steps to reproduce:**
1. Open page https://test.long-travel.live/20210508_12months/
2. Scroll down to the name of the Trip
3. Pay attention to the name of the Trip

**Actual result:**
The name of the Trip **doesn't meet** the requirement.

**Expected result:**
The name of the Trip **meets** the requirement.
![5](https://user-images.githubusercontent.com/105114364/175067234-72e7cc14-7dfa-453a-8bd5-87da17deae89.png)
![4](https://user-images.githubusercontent.com/105114364/175067227-5bb3653d-2c7b-48ab-b0ce-9ad4e8e33645.png)

**Environment:**
Operating system Windows 10 Pro
Browser Google Chrome 102.0.5005.115 (64 bit)
Screen resolution: 1920 x 1080

**Comment by JuliAntoshchuk** [comment]
#775

**Comment by JuliAntoshchuk** [comment]
mistake in name of region "Київська область" - on language of the country to which Region belongs.
![1](https://user-images.githubusercontent.com/105114364/175280618-fc400bcf-4b87-442e-84d5-15a84c9b3f5b.png)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by JuliAntoshchuk** [comment]
verified. bug isn't reproduced
