### ISSUE TITLE
20200627_29_yuzhniy/.Block Yuzhniy. Wrong text size 

### ISSUE THREAD

**Issue by yuriiboikokiev** [scholokov/long-travel-2#82]
**Steps:**
1.Open page https://long-travel.live/20200627_29_yuzhniy/
2. Attention to the "Yuzhniy" block.
2.Selecting text in the block "28.07.2020".
3.Open devtools.
4.Pay attention to the size of the text/

**Expected result:**
Text size - h4.

**Actual result :**
A paragraph is specified instead of the text size. (Incorrect according to the requirements).
Screenshot: https://skr.sh/s9n0t2sFIui?a

Additional Information:
-Operating System: windows 8, x64.
-Browser : Google Chrome 91.0.4472.77 (Official build), (64 bit).

**Comment by scholokov** [comment]
отсутствует ожидаемый результат

**Comment by scholokov** [comment]
2.Selecting text on the page.
какой текст? любой?

**Comment by scholokov** [comment]
скин - не по правилам

**Comment by scholokov** [comment]
исходя из бага - вообще непонятно о чем речь

**Comment by scholokov** [comment]
fixed
