### ISSUE TITLE
20170417_Kiylov - Header - Неверное расположение структурного блока "Название"

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#820]
Шаги воспроизведения:
1) Открыть https://test.long-travel.live/20170417_Kiylov/
2) Обратить внимание на расположение структурного блока "Название" в Header

Ожидаемый результат:
Структурный блок "Название" расположен над структурным блоком "Хлебные крошки с категорией"

Фактический результат:
Структурный блок "Название" расположен над структурным блоком "Карта"

Environment:
Windows 10, Chrome 103.0.5060.53 (64 бит);
Android 8.1.0, Chrome 102.0.5005.125;
![Кийлов – Кийловская Аскания – Long-Travel - Google Chrome 24 06 2022 15_48_04](https://user-images.githubusercontent.com/95171672/175539875-33f2a73f-f132-4b8a-96be-c7d72291bbc2.png)

![photo_2022-06-24_15-57-44](https://user-images.githubusercontent.com/95171672/175540783-b88ce7cf-059d-45c2-8e99-eac96cf09876.jpg)

**Comment by scholokov** [comment]
а что ту т такое - верно и неверно?

**Comment by KaterinaNimenko35** [comment]
The bug is not relevant
Design outdated
