### ISSUE TITLE
20170509_Kiev_Museum_Great_Patriotic_War - Страница не найдена 

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#821]
Шаги воспроизведения:
1. Открыть https://test.long-travel.live/20170509_Kiev_Museum_Great_Patriotic_War/

Ожидаемый результат:
Страница найдена

Фактический результат:
Страница не найдена

Environments:
Windos 10, Chrome 103.0.5060.53 (64 бит)
Android 8.1.0, Chrome 103.0.5060.53
![Page not found – Long-Travel - Google Chrome 25 06 2022 09_49_57](https://user-images.githubusercontent.com/95171672/175763579-ffe2bc20-88c2-437a-a43e-73f361fea9c6.png)
![photo_2022-06-25_10-18-40](https://user-images.githubusercontent.com/95171672/175763585-af60bb0b-1efe-4262-87bd-db4610037b84.jpg)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
verified
