### ISSUE TITLE
Travel page. Header. The photo from the gallery is displayed.

### ISSUE THREAD

**Issue by KaterinaNimenko35** [scholokov/long-travel-2#838]
**Description:**
On the page of the selected travel, after viewing and closing the lightbox, the last viewed photo from the photo gallery is displayed in the Header block.

**Steps to reproduce:**
1. Open page https://test.long-travel.live/20130613_0628_bulgaria/
2. Scroll the page down to the photo gallery block.
3. Click on any photo in the photo gallery.
4. Close the lightbox after viewing the photo.
5. Scroll the page up to the site menu block.
6. Please note that the last viewed photo from the photo gallery is displayed at the top of the page.

**Actual result:**
The viewed photo is displayed.

**Expected result:**
Viewed photo is **not** displayed.

**Notes:**
Please note, that the issue is reproduced on travel pages:

 20061028_Bila_Tserkva/
 20070406_09_Lviv/
 20070722_0809_Crimea/
 20071027_Uman/
 20080427_Feofania/
 20091026_1102_Toronto/
 20120827_0913_Karpathian_Crimia/
 20130526_Vishgorod/
 20130721_Vitachev/
 20131019_Petrovtsi_Bitva_Za_Kiev/
 20140616_0707_Greece/
 20140913_Kiev_Spivoche_Pole/
 20141102_10_Egypt_Hurghada/
 20150502_06_Hungary/

Please note that on travel pages where the photo gallery is not displayed, the problem is reproduced.
Please note that to close the photo, you need to reload the travel page.

**Environment:**
Desktop/W10/Google Chrome 101.0.4951.67 (64-bit).

![2022-06-27 10 24 56](https://user-images.githubusercontent.com/105543094/175883996-66182de0-e03d-448e-b776-47cfe9ddf0f3.png)

**Comment by scholokov** [comment]
pleae retest

**Comment by scholokov** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
an issue is reproduced

![2022-07-08 14 44 20](https://user-images.githubusercontent.com/105543094/177986689-c934e0cb-b063-4010-9aec-365ff0fdeb4e.png)

**Comment by scholokov** [comment]
fixed

**Comment by scholokov** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
verified
