### ISSUE TITLE
Invalid requirements in "Travel" section in "Global.Structure.Pages" page

### ISSUE THREAD

**Issue by NataliaDotsenko** [scholokov/long-travel-2#844]
Steps to reproduce:
1. go to https://github.com/scholokov/long-travel-2/wiki/1.-Global.Structure.Pages page.
2. look at the "Travel" section requirements. 

Actual result: 
"Search panel on the top" requirement is present.

Expected result:
"Search panel on the top" requirement should not be present.

Environments:
https://test.long-travel.live/travels/ - test env.
https://long-travel.live/travels/ - prod. env.

macOS Monterey 12.2/Chrome 103.0.5060.53 (x86_64)

<img width="927" alt="Снимок экрана 2022-07-06 в 22 04 53" src="https://user-images.githubusercontent.com/108013348/177633997-01dc5728-4dbc-46ff-84dc-302d8e43e190.png">

**Comment by scholokov** [comment]
некорректный тайтл
Invalid requirements in "Travel" section in "Global.Structure.Pages" page #844
слишком общий. необходима уникализация
