### ISSUE TITLE
20170513_Putivl_Kruti - Header - structural block "Город, Область, страна" is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#846]
Steps to Reproduce:
1) Open http://test.long-travel.live/20170513_Putivl_Kruti/

Expected Result:
Structural block "Город, Область, страна" is present

Actual Result:
Structural block "Город, Область, страна" is missing

Environment:
Windows 10, Chrome 103.0.5060.114 (64 bit)
Android 8.1.0, Chrome 103.0.5060.71
![Путивль – Крути – Long-Travel - Google Chrome 07 07 2022 15_09_26](https://user-images.githubusercontent.com/95171672/177770011-075593a9-3543-4510-9553-736de042dda1.png)
![photo_2022-07-07_15-09-51](https://user-images.githubusercontent.com/95171672/177770022-7489e303-d1fd-4fee-b894-03e5d6bfd8df.jpg)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
verified
