### ISSUE TITLE
20170513_Putivl_Kruti - Header - Structural block "Временной период" is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#847]
Steps to Reproduce:
1) Open http://test.long-travel.live/20170513_Putivl_Kruti/

Expected Result:
Structural block "Временной период" is present above the "Map" structural block

Actual Result:
Structural block "Временной период" is missing

Environment:
Windows 10, Chrome 103.0.5060.114 (64 bit)
Android 8.1.0, Chrome 103.0.5060.71
![Путивль – Крути – Long-Travel - Google Chrome 07 07 2022 15_09_26](https://user-images.githubusercontent.com/95171672/177774444-0c45e6fc-bacc-4520-8e2a-b468d79752f7.png)
![photo_2022-07-07_15-09-51](https://user-images.githubusercontent.com/95171672/177774456-d7262156-8200-4f20-9561-6d18cb6e73de.jpg)

**Comment by scholokov** [comment]
но на скрине он присутствует...
13.05.2017

**Comment by DmitriiNasonov** [comment]
Но ведь структурный блок называется "Временной период", разве не должно быть 2 даты? (Например даты начала и конца путешествия)

**Comment by scholokov** [comment]
а как его показать, если поездка была длиной в один день?
