### ISSUE TITLE
travels - photos not showing

### ISSUE THREAD

**Issue by AlexandrLyahov** [scholokov/long-travel-2#856]
Steps to reproduce:
1.Open http://www.test.long-travel.live
2.Enter any journey
3.Scroll down

Actual result:
photos not showing

Expected result:
photos are displayed

![2022-07-07 22_03_02-](https://user-images.githubusercontent.com/105969368/177852309-a1b12af2-1077-4de1-8883-3705230876a9.png)

![2022-07-07 22_03_28-Window](https://user-images.githubusercontent.com/105969368/177852312-f82d053b-a7e9-4fcb-8f23-51b2ca40e8b8.png)

![2022-07-07 22_03_53-Window](https://user-images.githubusercontent.com/105969368/177852336-6475a393-ba58-42a3-9fe4-38f1fb1f4d63.png)

![2022-07-07 22_04_15-Window](https://user-images.githubusercontent.com/105969368/177852338-2a02705b-0928-485f-bf44-6b2ccf061a76.png)

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 103.0.5060.114 (64 bit)
Screen resolution: 1600 x 900

**Comment by scholokov** [comment]
fixed

**Comment by Vshapko** [comment]
Actual result:
photos are displayed

Expected result:
photos are displayed

**Comment by Vshapko** [comment]
Actual result:
photos are displayed

Expected result:
photos are displayed
