### ISSUE TITLE
20130908_tropical_park - block region, country - no punctuation mark

### ISSUE THREAD

**Issue by AlexandrLyahov** [scholokov/long-travel-2#862]
Steps to reproduce:
1,Open https://test.long-travel.live/20130908_tropical_park/
2,Scroll down

Actual result:
without punctuation mark

Expected result:
there is a punctuation mark

![2022-07-11 19_07_01-Window](https://user-images.githubusercontent.com/105969368/178309306-3bc3519f-4076-4813-9ac8-d007fa57029c.png)

![2022-07-11 19_10_17-Window](https://user-images.githubusercontent.com/105969368/178309332-fad3e72d-e767-4cc0-bad9-a2e44275ce79.png)

![2022-07-11 19_08_30-Window](https://user-images.githubusercontent.com/105969368/178309368-99570154-13bd-497f-95fb-255b0d106aca.png)

![2022-07-07 21_51_48-Window](https://user-images.githubusercontent.com/105969368/178309420-914564e3-b13e-4293-ac72-711d7a63b022.png)

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 103.0.5060.114 (64 bit)
Screen resolution: 1600 x 900

OS: iOS, v15.3
Browser: Chrome
Resolution: 1170 x 2532 px

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by AlexandrLyahov** [comment]
verified
