### ISSUE TITLE
wrong requirements - photo gallery type

### ISSUE THREAD

**Issue by AlexandrLyahov** [scholokov/long-travel-2#867]
Steps to reproduce:
1,Open https://github.com/scholokov/long-travel-2/wiki/2.5-Travels.FotoGallery
2,Scroll down

Actual result:
photo gallery type - Mosaic

Expected result:
photo gallery type - Justified Grid
 
![2022-07-11 21_00_43-Window](https://user-images.githubusercontent.com/105969368/178328695-1487ebf2-7165-458c-ad3b-13fbb603436e.png)

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 103.0.5060.114 (64 bit)
Screen resolution: 1600 x 900

**Comment by scholokov** [comment]
fixed

**Comment by AlexandrLyahov** [comment]
verified
