### ISSUE TITLE
20200725_26_Гора Пивиха Incorrect travel name

### ISSUE THREAD

**Issue by NazariiDemydenko** [scholokov/long-travel-2#868]
Steps to reproduce:
Open page https://test.long-travel.live/20200725_26_piviha/

Actual result:
20200725_26_Гора Пивиха_Полтавська область_Україна

Expected result:
Гора Пивиха

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 103.0.5060.114 (64 bit)

![пивиха](https://user-images.githubusercontent.com/108928675/178449987-11abe00f-ccd7-498f-b610-4410318c927d.png)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by NazariiDemydenko** [comment]
Має бути дата подорожі у виділеному фрагменті?

**Comment by scholokov** [comment]
не должна

**Comment by NazariiDemydenko** [comment]
not fixed
