### ISSUE TITLE
Київська кондитерська фабрика "Рошен" 23.09.2021 map bug

### ISSUE THREAD

**Issue by NazariiDemydenko** [scholokov/long-travel-2#869]
Steps to reproduce:
Open page https://test.long-travel.live/20191019_roshen/

Actual result:
Фабрика Рошен, Kyiv, Ukraine

Expected result:
Kyiv - Roshen - Kyiv

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 103.0.5060.114 (64 bit)

![rosh](https://user-images.githubusercontent.com/108928675/178452242-3357d529-57c8-423c-9541-7e2fd139042d.png)

**Comment by scholokov** [comment]
нет конкретики в тайтле. т.е. тайтл слишком общий

**Comment by scholokov** [comment]
требования обновлены
