### ISSUE TITLE
Київська кондитерська фабрика "Рошен" 23.09.2021 Incorrect travel category

### ISSUE THREAD

**Issue by NazariiDemydenko** [scholokov/long-travel-2#871]
Steps to reproduce:
Open page https://test.long-travel.live/20191019_roshen/

Actual result:
Uncategorized

Expected result:
Ukraine

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 103.0.5060.114 (64 bit)

![Безымянный](https://user-images.githubusercontent.com/108928675/178455078-a6720430-43b0-4307-ab3f-cf1af65bae65.png)

**Comment by scholokov** [comment]
нет айди в тайтле

**Comment by GeorgiiZ90** [comment]
fixed
