### ISSUE TITLE
20190907_baydarky - Incorrect travel date

### ISSUE THREAD

**Issue by NazariiDemydenko** [scholokov/long-travel-2#881]
Steps to reproduce:
Open page https://test.long-travel.live/20190907_baydarky/

Actual result:
23.09.2021

Expected result:
07.09.2019

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 103.0.5060.114 (64 bit)

![Безымянный](https://user-images.githubusercontent.com/108928675/178690300-29088e32-68cb-4d68-957d-ebe56947fd23.png)

**Comment by GeorgiiZ90** [comment]
fixed
