### ISSUE TITLE
20190907_baydarky - preview on global map

### ISSUE THREAD

**Issue by NazariiDemydenko** [scholokov/long-travel-2#884]
Steps to reproduce:
1. Open page https://test.long-travel.live/travels/
2. Find travel 20190907_baydarky on global map

Actual result:
Preview not showing

Expected result:
Preview is displayed

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 103.0.5060.114 (64 bit)

![Безымянный](https://user-images.githubusercontent.com/108928675/178694480-17742ade-2270-4a5b-b394-4bb5102f098c.png)

**Comment by scholokov** [comment]
fixed
