### ISSUE TITLE
20210510_stariy_solvin - preview on global map

### ISSUE THREAD

**Issue by NazariiDemydenko** [scholokov/long-travel-2#885]
Steps to reproduce:

1. Open page https://test.long-travel.live/travels/
2. Find travel 20210510_stariy_solvin on global map

Actual result:
Preview not showing

Expected result:
Preview is displayed

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 103.0.5060.114 (64 bit)

![Безымянный](https://user-images.githubusercontent.com/108928675/178696031-d08c1b98-2e80-42f7-82fa-3905e00023f3.png)

**Comment by scholokov** [comment]
fixed
