### ISSUE TITLE
20170805_20_Odessa - Header - Structural block "Город, Область, страна" is missing

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#923]
Steps of reprodusing:
1) Open https://test.long-travel.live/20170805_20_Odessa/

Expected Result:
Structural block "Город, Область, страна" is present

Actual Result:
Structural block "Город, Область, страна" is missing

Environments:
Windows 10, Chrome 103.0.5060.114 (64 bit)
Android 8.1.0, Crome 103.0.5060.71
![New Issue · scholokov_long-travel-2 - Google Chrome 15 07 2022 14_09_35](https://user-images.githubusercontent.com/95171672/179212419-186360c6-e1ec-4eb6-a736-d4a8c5fc70d8.png)
![photo_2022-07-15_14-11-34](https://user-images.githubusercontent.com/95171672/179212427-b59d0dd7-f562-46dc-87d4-e1cc2ee1404a.jpg)

**Comment by GeorgiiZ90** [comment]
Fixed

**Comment by DmitriiNasonov** [comment]
verified. bug is not reproducing
