### ISSUE TITLE
20180611_Kiev_Sea - Error 404 Not Found

### ISSUE THREAD

**Issue by DmitriiNasonov** [scholokov/long-travel-2#934]
Steps of reprodusing:
1) Open https://test.long-travel.live/20180611_Kiev_Sea/

Expected Result:
Travel page is found

Actual Result:
Travel page is not found

Environments:
Windows 10, Chrome 103.0.5060.114 (64 bit)
Android 8.1.0, Crome 103.0.5060.71
![Берегове – Long-Travel - Google Chrome 15 07 2022 15_05_30](https://user-images.githubusercontent.com/95171672/179219736-99c7bf84-484a-4fa6-a098-89edd83e173a.png)
![photo_2022-07-15_15-05-15](https://user-images.githubusercontent.com/95171672/179219747-d91b86d0-f6c4-4767-a2e6-31b00a8b9e83.jpg)

**Comment by scholokov** [comment]
fixed

**Comment by DmitriiNasonov** [comment]
verified. bug is not reproducing
