### ISSUE TITLE
20130908_tropical_park - empty space between photos

### ISSUE THREAD

**Issue by AlexandrLyahov** [scholokov/long-travel-2#935]
Steps to reproduce:
1,Open http://www.test.long-travel.live/20130908_tropical_park/
2,Scroll down

Actual result:
there is an empty space

Expected result:
no empty space

![2022-07-17 09_17_56-Window](https://user-images.githubusercontent.com/105969368/179386994-692fd7a7-f990-40fe-812b-cef161d06312.png)
![2022-07-17 09_18_22-Window](https://user-images.githubusercontent.com/105969368/179386996-d294bd11-7634-4a83-84ca-470743984ff2.png)
![2022-07-17 09_18_36-Window](https://user-images.githubusercontent.com/105969368/179386997-973baddc-3ec4-4591-b3b0-6839f1d14cf8.png)
![2022-07-17 09_18_50-](https://user-images.githubusercontent.com/105969368/179386998-99b6a29f-b815-4d80-9292-aaf56d27afe3.png)
![2022-07-17 09_19_08-Window](https://user-images.githubusercontent.com/105969368/179386999-11558ac1-d6bd-4a59-8be3-56768010e4cd.png)
![2022-07-17 09_19_31-Window](https://user-images.githubusercontent.com/105969368/179387000-7cfbcb1d-9e25-40a2-ae28-3e37710b7ebb.png)
![2022-07-17 09_24_32-](https://user-images.githubusercontent.com/105969368/179387001-df774148-6c3b-4ab4-8102-48785ec7921f.png)
![2022-07-17 09_24_48-](https://user-images.githubusercontent.com/105969368/179387002-f3a5edc7-fdf5-4e77-885d-7d4fce5e0b19.png)
![2022-07-17 09_25_02-Window](https://user-images.githubusercontent.com/105969368/179387003-29a6f6bb-cd34-4db2-9d3b-c9d9c4cccdbb.png)
![2022-07-17 09_25_25-](https://user-images.githubusercontent.com/105969368/179387004-0fc2ae29-6257-4d95-af46-b37cd0475ae2.png)

Environment:
Operating system: Windows 10 Pro
Browser: Google Chrome 103.0.5060.114 (64 bit)
Screen resolution: 1600 x 900

OS: iOS, v15.3
Browser: Chrome
Resolution: 1170 x 2532 px

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by AlexandrLyahov** [comment]
verified
