### ISSUE TITLE
20200725_26_piviha  The photo gallery type does not match the requirements of the project

### ISSUE THREAD

**Issue by KaterinaNimenko35** [scholokov/long-travel-2#938]
**Steps to reproduce:**

1. Open page  https://test.long-travel.live/20200725_26_piviha/
2. Pay attention to the type of photo gallery 

**Actual result:**
Photo gallery type **Square Grid / Masonry / Justified Grid**

**Expected result:**
Photo gallery type **Justified Grid**

**Environment:**
Desktop/W10/Google Chrome 101.0.4951.67 (64-bit)

![2022-07-18 14 14 29111](https://user-images.githubusercontent.com/105543094/179502549-0006f845-65b8-4016-983d-5307e00222ca.png)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
verified
