### ISSUE TITLE
20210109_kiev - Body - Photo doesn't disappear when closing LightBox

### ISSUE THREAD

**Issue by ViktoriiaDerhausova** [scholokov/long-travel-2#944]
**Steps To Reproduce:**
1. Open https://test.long-travel.live/20210109_kiev/
2. Clik on first photo
3. Press button "Close (Esc)" in LightBox

**Expected result:**
The LightBox with photo has closed

**Actual result:**
The LightBox with photo has closed, but photo didn't disappear

**Notes:**
1. Actual result is the same if the LightBox is closed with the keyboard button "Esc"
2.  Photo will disappear if reload the page
3. Same bug reproduced with video

**Environment:**
Windows 11, Chrome 103.0.5060.114 (64 bit)
![LightBox](https://user-images.githubusercontent.com/107997177/179808452-13ade276-4d79-4fb8-a93e-45945d4e056a.jpg)

**Comment by ViktoriiaDerhausova** [comment]
Actual result is the same if the LightBox is closed with the keyboard button "Esc"

**Comment by scholokov** [comment]
Actual result is the same if the LightBox is closed with the keyboard button "Esc"

это надо не коментом, а в боди.
писать, например:

Notes:
Actual result is the same if the LightBox is closed with the keyboard button "Esc"

**Comment by scholokov** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
Verified, an issue is not reproduced
