### ISSUE TITLE
20200627_29_yuzhniy.Block title. Incorrect block name 

### ISSUE THREAD

**Issue by yuriiboikokiev** [scholokov/long-travel-2#95]
**Steps:**
1.Open page 20200627_29_yuzhniy
2.Attention to the "Южный" - name of the block.

**Actual result :**
Block name  - "Южный".

**Expected result:**
Block name - "Киев-Южный-Киев".( according to the requirements).
[https://github.com/scholokov/long-travel-2/wiki/Travels]

**Screenshot:** https://skr.sh/s9rXnxbYKwT?a

**Additional Information:**
-Operating System: Windows 10, x64.
-Browser : Google Chrome 93.0.4577.63 (Official build), (64 bit).

**Comment by scholokov** [comment]
20200627_29_yuzhniy. Title. Incorrect block name #95
->>>>
20200627_29_yuzhniy - Title - Киев-Южный-Киев

**Comment by scholokov** [comment]
Block - можно не указывать в тексте - это и так понятно

**Comment by scholokov** [comment]
Block name - "Южный".(Incorrect according to the requirements).

это експектид. потому тут не может быть incorrect
(according to the requirements).
а еще лучше линку на требования

**Comment by scholokov** [comment]
2.Attention to the "Южный" block.
2.Аttention to the name of the block.

на два блока нет смысла "обращать внимание"
тем более у тебя нумерация одинаковая:
2.Attention to the "Южный" - name of the block.

**Comment by sokol13ua** [comment]
fixed

**Comment by scholokov** [comment]
ошибка на предыдущей среды.
на тесте все ок
