### ISSUE TITLE
20210109_kiev - LightBox - Error 403 when downloading image

### ISSUE THREAD

**Issue by ViktoriiaDerhausova** [scholokov/long-travel-2#951]
**Steps To Reproduce:**

1. Open https://test.long-travel.live/20210109_kiev/
2. Clik on first photo
3. Clik on "Download image" on LightBox

**Expected result:**
The window for chooseing a folder to save has opened

**Actual result:**
Error 403

**Environment:**
Windows 11, Chrome 103.0.5060.114 (64 bit)

**Notes:**
Actual result is the same with all photos from 20210109_kiev

![Photo Download Error](https://user-images.githubusercontent.com/107997177/180007987-3b85d4f9-32fb-481a-ba1c-3dc921ab1e38.jpg)

**Comment by scholokov** [comment]
please retest
