### ISSUE TITLE
20201231_sofievskaya _#957_on the travel page, videos do not open after pressing the play button.

### ISSUE THREAD

**Issue by Vshapko** [scholokov/long-travel-2#957]
Steps to reproduce:
1.Open page https://test.long-travel.live/20201231_sofievskaya
2. click on video
3. click on play button
4. pay attention to the all video on the page

Actual result:
Video doesn't play after pressing play button

Expected result:
The video  play after pressing the Play button

Scrin:
![image](https://user-images.githubusercontent.com/108400151/180182235-f08c4754-0403-4224-97b2-814d108467b3.png)

Environment:
Lenovo/Windows 10 Pro 21H1/google chrome 103.0.5060.114

**Comment by scholokov** [comment]
в тайтле не описана проблема

**Comment by Vshapko** [comment]
@scholokov  Денис, прошу пояснить что значит в "тайтле не описана проблема"? 
В теме баги - есть краткое описание (20201231_sofievskaya - **Video not playing** #957)
в теле есть описание и скрин.
Хочу понять и сделать качественно.
Спасибо

**Comment by DmytroMarkulych** [comment]
@Vshapko Давайте ми зробимо цей баг репорт ідеальним) 
1. При написанні Summary ми дотримуємося правила Де? Що? Коли?, і називаємо UI елементи своїми іменами. Тобто, до прикладу сформулюємо Ваш дефект.:
**Де?** - На сторінці подорожі **Що?** - не відкривається відео **Коли?** - після натискання на кнопку "Play"
Якщо проблема стосується одного відео, то, ми вказуємо назву, якщо це притаманно для всіх, то відповідно у множинній формі. 

2. Кроки для відтворення . Першим кроком у нас має бути сторінка яку ми маємо відкрити. Далі від контексту дефекту в наказовій формі пишемо кроки. Один крок має містити одну дію (Приклад.: Клікнути на кнопку Save. ) якщо для відтворення дефекту потрібно багато дій ми можемо писати передумову, або ж в 1 пункт поміщати 2 кроки (не більше). 
Приклад Вашого баг репорту: 
1. Відкрити сторінку https://....com
2. Клікнути на відео.. (вказуємо назву)
3. Клікнути на кнопку Play
4. Звернуту увагу на відео 

3. Актуальний результат, теж в лаконічній формі пишемо що ми маємо по факту. Приклад. Відео (назва) не відтворилося після натискання на кнопку Play/ 
4. Фактичний результат в лаконічній формі пишемо що ми мало б відбутися після натискання на кнопку. Приклад: Відео відтворилося після натискання на кнопку Play

5. Робимо скрін сторінки, виділяємо прямокутником (прийнято червоний, так для більшого привернення уваги) та позначаємо стрілкою даний прямокутник. Додаємо скрін до баг репорту. Якщо ж дефект важко показати на скрінах робимо запис екрану

**Comment by Vshapko** [comment]
@DmytroMarkulych дякую за детальний розбор, але трохи не розумію різниці у підході оцінювання баг репортів.
За основу оформлення свого репорту я взяла як приклад один з репортів, в зоні Вашої відповідальності. 
По цьому репорту не було багато зауважень, були коментарі "чудова робота",  бага була пофікшена.
 Не розумію, але дякую. 
Намагатимусь оформлювати згідно цього шаблону.
![image](https://user-images.githubusercontent.com/108400151/191909814-dabd0212-19d7-482f-86d8-6b78a65263ed.png)
![image](https://user-images.githubusercontent.com/108400151/191909980-9c1f5697-f0d6-4a35-9882-f2dcf54bace6.png)

**Comment by Vshapko** [comment]
@DmytroMarkulych  и ще питання, де взяти назву відео? з коду сторінки? 
дякую

**Comment by DmytroMarkulych** [comment]
@Vshapko Якщо є назва під відео то беремо з відти. А якщо відео одне на сторінці то просто пишемо відео

**Comment by Vshapko** [comment]
@DmytroMarkulych  на сторінках назв відео немає.

**Comment by DmytroMarkulych** [comment]
@Vshapko тоді просто відео

**Comment by DmytroMarkulych** [comment]
@Vshapko Молодець) Тільки скрін ставимо після Expected Result )

**Comment by Vshapko** [comment]
Дякую, прочитала статтю за посиланням, зрозуміла принцип оформлення, виправила

**Comment by Vshapko** [comment]
@DmytroMarkulych  доброго дня Дмитро. 
Перевірила мєдія, які будо додані на сторінку. 
Всі фото в галереї і сама галерея відображаютья коректно, відповідно до вимог ТЗ, 
відео на цій сторінці зараз відсутнє.
Відповідно вважаю, що цей кейс вже не актуальний.
Чи можу я його закрити?
Дякую

**Comment by DmytroMarkulych** [comment]
@Vshapko Якщо не відтворюється ,напишіть будь ласка, комент та закрийте його)

**Comment by Vshapko** [comment]
@DmytroMarkulych  зараз відєо на сторінці вже немає, тому вважаю цей репорт не актуальним і закриваю.
Дякую

**Comment by Vshapko** [comment]
@DmytroMarkulych 
відео не відтворюється, здається я врахувала всі Ваші зауваження і виправила репорт.
Змінюю йому статус на Needs triage.
Якщо э ще зауваження по цьому репорту - допрацю.
Дякую

**Comment by DmytroMarkulych** [comment]
@Vshapko Хороша робота.!) Маленькі зауваження, на кнопки ми не press, а click..  
І в цьому пункті "4. pay attention to the all video on the page", ми перед тим говоримо, про одне конкретне відео, а в 4-му пункті що звертаємо увагу на всі відео.. думаю, що слово all зайве
