### ISSUE TITLE
20210814_24_sergeevka_odessa  The font in the date of departure does not meet the requirements #324

### ISSUE THREAD

**Issue by komarov-denys** [scholokov/long-travel-2#967]
Steps to reproduce:
Open page https://test.long-travel.live/20210814_24_sergeevka_odessa/

Actual result:
The font does not meet requirements (H3)

Expected result:
The font meets the requirements (H3)

Environment:
Operating system: Windows 10 Home 
Browser: Google Chrome 103.0.5060.134 (64 bit)

![imgonline-com-ua-2to1-ThrUY5kjqIaAdNq](https://user-images.githubusercontent.com/97951627/181490605-31e850f1-eaad-4c06-ab30-44cfab19b587.jpg)

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by komarov-denys** [comment]
Проверил
