### ISSUE TITLE
20210814_24_sergeevka_odessa - Gallery - Video not playing 

### ISSUE THREAD

**Issue by komarov-denys** [scholokov/long-travel-2#971]
Steps to reproduce:
1.Open page https://test.long-travel.live/20210814_24_sergeevka_odessa/
2. Scroll down to the gallery 
3. Click on the video

Actual result: 
Video not playing 

Expected result:
Video plays 

Environment:
Operating system: Windows 10 Home
Browser: Google Chrome 103.0.5060.134 (64 bit)

![merge_from_ofoct](https://user-images.githubusercontent.com/97951627/181709309-6979fea9-89fb-49a8-b4e2-5315774ea4bb.jpg)

**Comment by scholokov** [comment]
2. Scroll down to the gallery and click on the video

очень плохая практика 2 действия запихивать в один шаг
обычно когда читают шаги - доходят до одного шага - и выполнив его переходят на след строку. потому есть потенциальный риск, что не дочитают до конца

**Comment by scholokov** [comment]
Actual result:
Video not playing in gallery

Expected result:
Video plays in gallery

в шагах указано, что в галерее
в таком случае нет смыла повторяться еще и в результах

**Comment by scholokov** [comment]
20210814_24_sergeevka_odessa Video not playing in gallery #324 #971

как вариант упрощения тайтла:
20210814_24_sergeevka_odessa - Gallery - Video not playing

**Comment by komarov-denys** [comment]
Понял, внес правки, спасибо!

**Comment by scholokov** [comment]
процедура:
вносишь правки - возвращаешь мне на ревью в - need triage

но там от меня коментов несколько было :))

**Comment by komarov-denys** [comment]
+

**Comment by scholokov** [comment]
fixed

**Comment by komarov-denys** [comment]
verified
