### ISSUE TITLE
20210814_24_sergeevka_odessa - Travel title photo is not present -> preview

### ISSUE THREAD

**Issue by komarov-denys** [scholokov/long-travel-2#975]
Steps to reproduce:
Open page https://test.long-travel.live/20210814_24_sergeevka_odessa/

Actual result:
Travel title photo is not present.

Expected result:
Travel title photo present.

Environment:
Operating system: Windows 10 Home
Browser: Google Chrome 103.0.5060.134 (64 bit)
![photo_2022-08-01_12-23-32](https://user-images.githubusercontent.com/97951627/182117387-86179e1e-89a0-44d1-bce7-f6086e210c82.jpg)

**Comment by scholokov** [comment]
в тайтле не раскрыто "в чем именно проблема", а только указано место - где

**Comment by komarov-denys** [comment]
Исправлено

**Comment by scholokov** [comment]
fixed

**Comment by komarov-denys** [comment]
Проверил
