### ISSUE TITLE
20210814_24_sergeevka_odessa - Intermediate block, unreadable date.

### ISSUE THREAD

**Issue by komarov-denys** [scholokov/long-travel-2#976]
Steps to reproduce:
Open page https://test.long-travel.live/20210814_24_sergeevka_odessa/

Actual result:
Travel date, dark font.

Expected result:
Travel date, light font.

Environment:
Operating system: Windows 10 Home
Browser: Google Chrome 103.0.5060.134 (64 bit)
![photo_2022-08-01_13-03-54](https://user-images.githubusercontent.com/97951627/182131491-d76a6119-7894-4672-bcae-f9135d8130e0.jpg)

**Comment by KaterinaNimenko35** [comment]
verified
an issue is not reproduced
