### ISSUE TITLE
20201010_11_brech.Travel distance not specified.

### ISSUE THREAD

**Issue by SerhiiBurdieiev** [scholokov/long-travel-2#985]
**Steps to reproduce:**

1.  Open page <https://test.long-travel.live/20201010_11_brech/>
2. Scroll down the page to the trip map.
3. Pay attention of missing of travel distance.

**Actual result:**
Travel distance isn't indicated.

**Expected result:**
Travel distance is indicated.

**Environment:**
MacBook/macOS Monterey 12.5/Chrome 103.0.5060.134 (arm64)

![20201010_11_brech](https://user-images.githubusercontent.com/108996909/182360014-0dc61ead-456a-4b37-a269-794ca64dc0ee.png)

![требования дистанция](https://user-images.githubusercontent.com/108996909/182360084-b44bd6b1-cc07-4ff7-99f1-e78fcc16b832.png)

**Comment by scholokov** [comment]
Actual result:
The distance from the start point to the intermediate point and from the intermediate point to the end point is not indicated.

Expected result:
The distance from the start point to the intermediate point and from the intermediate point to the end point is specified.

очень сложно читать.
в данном случае можно действовать по принципу:

- в шагах указываем "обратить внимание на такой то объект"
- в экшуал и экспектид - пишем его характеристики

**Comment by SerhiiBurdieiev** [comment]
Corrected.

**Comment by scholokov** [comment]
fixed
