### ISSUE TITLE
20151031_haisyn_uman - link to the hotel is not visible

### ISSUE THREAD

**Issue by OleksiiShch** [scholokov/long-travel-2#987]
Steps to reproduce:
  1.Open page https://test.long-travel.live/20151031_haisyn_uman/
  2.Scroll down to the “Mini Gotel Pozitiv”
  3. Under the date link is not visible

Actual result:
link is not visible

Expected result:
link is visible

Environment:
Windows 10, Google Chrome Версія 103.0.5060.134 (Розробка) (64-розрядна версія)
![Link](https://user-images.githubusercontent.com/25012427/182356784-7d727015-3c90-4166-960a-982ea8953ccd.png)

**Comment by scholokov** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
Verified, an issue is not reproduced
