### ISSUE TITLE
20151031_haisyn_uman - date fonts does not meet the requirements

### ISSUE THREAD

**Issue by OleksiiShch** [scholokov/long-travel-2#990]
Steps to reproduce
   1.Open page https://test.long-travel.live/20151031_haisyn_uman/
   2.Scroll down to the name of the intermediate point of the travel "Дендропарк "Софиевка""
   3.Pay attention to the date fonts of the intermediate point of the travel

Actual Result:
date fonts - "p"

Expected result:
date fonts - "h3"

Environment:
Windows 10, Google Chrome Версія 103.0.5060.134 (Розробка) (64-розрядна версія)
![Date fonts](https://user-images.githubusercontent.com/25012427/182365988-10c60e70-ba62-4aaf-bd21-a4b9b7acb58e.png)

**Comment by OleksiiShch** [comment]
corrected

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by OleksiiShch** [comment]
Verified
