### ISSUE TITLE
20151031_haisyn_uman - the name of the intermediate point of the travel does not meet the requirements

### ISSUE THREAD

**Issue by OleksiiShch** [scholokov/long-travel-2#991]
**Steps to reproduce**

   1. Open page https://test.long-travel.live/20151031_haisyn_uman/
   2. Scroll down to the name of the intermediate point of the travel "Дендропарк "Софиевка"
   3. Pay attention to the name of the intermediate point of the travel

**Actual Result:**

 Дендропарк "Софиевка" Умань

**Expected result:**

Національний дендрологічний парк «Софіївка»
Черкаська область, Україна

**Environment:**

Windows 10, Google Chrome Версія 103.0.5060.134 (Розробка) (64-розрядна версія)

![Умань](https://user-images.githubusercontent.com/25012427/182367812-d787eccb-0430-44ea-ba0c-89d3ce12d6ea.png)

**Comment by scholokov** [comment]
Actual Result:
The name of the intermediate point of the travel - "Дендропарк "Софиевка
Умань"

Expected result:
The name of the city of the intermediate point of the travel - "Національний дендрологічний парк "Софіївка" НАН України
Умань, Черкаська обл., Україна"

зачем
The name of the intermediate point of the travel
в экшуале и экспекте, если эта информация уже есть в шагах?

**Comment by OleksiiShch** [comment]
corrected

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
an issue is reproduced

![test long-travel live_20151031_haisyn_uman_ (3)](https://user-images.githubusercontent.com/105543094/194709974-41c97eb7-dec6-4f91-9510-be39a403c0f6.png)
![2022-10-08 16 14 22](https://user-images.githubusercontent.com/105543094/194709976-00cc7d14-a7ca-489b-8fb0-55c0d96db65b.png)

**Comment by scholokov** [comment]
fixed
