### ISSUE TITLE
20151031_haisyn_uman - name fonts of the intermediate point of the travel does not meet the requirements

### ISSUE THREAD

**Issue by OleksiiShch** [scholokov/long-travel-2#992]
Steps to reproduce
   1.Open page https://test.long-travel.live/20151031_haisyn_uman/
   2.Scroll down to the name of the intermediate point of the travel "Дендропарк "Софиевка"
   3.Pay attention to the name fonts of the intermediate point of the travel

Actual Result:
name fonts of the intermediate point of the travel - "p"

Expected result:
name fonts of the intermediate point of the travel - "h2"

Environment:
Windows 10, Google Chrome Версія 103.0.5060.134 (Розробка) (64-розрядна версія)
![Name fonts](https://user-images.githubusercontent.com/25012427/182368601-14c605da-ae3f-44d3-8b8a-4c189a4b3d93.png)

**Comment by scholokov** [comment]
экшуал и эксппектид одинаковые

**Comment by OleksiiShch** [comment]
corrected

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by KaterinaNimenko35** [comment]
The bug is not relevant - font requirements are outdated
