### ISSUE TITLE
20151226_kiev_fashion_park - the name of the city - the name is not correct

### ISSUE THREAD

**Issue by OleksiiShch** [scholokov/long-travel-2#999]
Steps to reproduce
Open page https://test.long-travel.live/20151226_kiev_fashion_park/
Pay attention to the name of the city

Actual Result:
City name - "Киев, Украина"

Expected result:
City name - "Київ, Україна"

Environment:
Windows 10, Google Chrome Версія 103.0.5060.134 (Розробка) (64-розрядна версія)
![City name](https://user-images.githubusercontent.com/25012427/182379733-4bce5c11-88f1-44af-a00f-9069a1fae66d.png)

**Comment by scholokov** [comment]
does not meet the requirements

не раскрывает смысл бага

**Comment by OleksiiShch** [comment]
corrected

**Comment by GeorgiiZ90** [comment]
fixed

**Comment by OleksiiShch** [comment]
Verified
